denoland/deno

cli/tests/integration/test_tests.rs, cli/tests/test/exit_sanitizer.out, cli/tests/test/fail.out, cli/tests/test/fail_fast.out, cli/tests/test/finally_timeout.out, cli/tests/test/ignore_permissions.out, cli/tests/test/ignore_permissions.ts, cli/tests/test/no_check.out, runtime/js/40_testing.js
=> fix(runtime): ignored tests should not cause permission changes

Cargo.toml
=> perf: opt-level = 3 for deno_net

.github/workflows/ci.yml
=> ci: fix typo 'CCFLAGs' to 'CFLAGS'

.github/workflows/ci.yml
=> ci: avoid running man-db triggers when setting up sysroot

extensions/web/09_file.js, extensions/web/10_filereader.js
=> refactor: use primordials in extensions/web, part2

tools/wpt.ts
=> tests: parallelize test runs in wpt

cli/tests/unit/webcrypto_test.ts, extensions/crypto/lib.rs
=> fix(extensions/crypto): hash input for RSASSA-PKCS1-v1_5 before signing

extensions/web/Cargo.toml
=> fix: uuid crate needs 'serde' feature

tools/wpt.ts, tools/wpt/utils.ts
=> tests: Escape lone surrogates in wptreport test names and messages

docs/contributing/building_from_source.md
=> fix(docs): update contributing instructions to mention installing python 3 instead of 2

cli/tests/integration/upgrade_tests.rs, cli/tools/standalone.rs, cli/tools/upgrade.rs
Closes #11237
Also minor clean up that didnt feel like a separate PR was necesary
=> fix(cli/tools/upgrade): check if passed version is valid

.github/workflows/ci.yml, Cargo.lock, cli/Cargo.toml, core/Cargo.toml, extensions/broadcast_channel/Cargo.toml, extensions/crypto/Cargo.toml, extensions/fetch/Cargo.toml, extensions/net/Cargo.toml, extensions/timers/Cargo.toml, extensions/url/Cargo.toml, extensions/web/Cargo.toml, extensions/webgpu/Cargo.toml, extensions/websocket/Cargo.toml, extensions/webstorage/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
=> chore: update crates

extensions/web/02_event.js, tools/wpt/expectation.json
Aligns `EventTarget.addEventListener` to spec
=> chore(extensions/web):  AddEventListenerOptions.signal shouldn't be nullable

cli/tests/integration/run_tests.rs, cli/tests/worker_event_handler_test.js, cli/tests/worker_event_handler_test.js.out, cli/tests/workers/worker_event_handlers.js, runtime/js/01_web_util.js, runtime/js/99_main.js
=> fix(runtime): Align the DedicatedWorkerGlobalScope event handlers to the spec.

docs/typescript/overview.md
=> docs(manual/typescript): Use consistent tenses in discussing cross-lang imports

cli/flags.rs
=> fix: non-existent field in cli/flags.rs

Cargo.lock, core/Cargo.toml
=> chore: upgrade rusty_v8

Cargo.lock, cli/Cargo.toml, cli/tests/unit/io_test.ts
=> upgrade: deno_lint 0.10.0

extensions/crypto/00_crypto.js
=> chore(extensions/crypto): use primoridials with verify()

cli/tests/unit/http_test.ts, extensions/http/lib.rs
Cookie headers should not be concatenated by commas, rather by
semicolons.
=> fix(ext/http): correctly concat cookie headers

cli/flags.rs
Closes https://github.com/denoland/deno/issues/11414
=> fix(cli): add help description for test --jobs option

cli/flags.rs
Fixes https://github.com/denoland/deno/issues/11432
=> fix(cli): re-enable --watch flag for test

docs/tools/bundler.md
=> docs: tag bundler code blocks as bash

docs/linking_to_external_code/reloading_modules.md
=> docs: fix bash code blocks tagged as ts

cli/tests/unit/fetch_test.ts, cli/tests/unit/response_test.ts, extensions/fetch/22_body.js
=> tests: re-enable disabled test

README.md
=> chore: change links in README

cli/tests/integration/inspector_tests.rs, runtime/inspector_server.rs
Fixes https://github.com/denoland/deno/issues/11449
=> fix: panic for non-WS connections to inspector

.github/workflows/ci.yml
=> build: publish canary version file in seperate job

cli/build.rs
=> fix(cli): rebuild when environment variables change

.github/workflows/ci.yml
=> build: fix publishing of canaries

cli/lsp/analysis.rs
It was a logic error to populate that slot for `import type` or `export type` as it really should only be populated with `@deno-types` values for things to work properly.  The `cli/module_graph` has a similar logic issue, but manifests itself different (see: #11476, but even then there is another issue that means just fixing this same logic error still doesn't resolve the issue, so I will do it as a seperate PR).
Fixes: #11458
Fixes: #11461
Closes: denoland/vscode_deno#414
=> fix(lsp): do not populate maybe_type slot with import type dep

extensions/crypto/lib.deno_crypto.d.ts
Ref https://github.com/denoland/deno/pull/11367#discussion_r676006350
=> chore(crypto): use WebIDL BufferSource in types

tools/cut_a_release.md
=> chore: update cut_a_release.md

cli/tests/integration/worker_tests.rs, cli/tests/workers/test.ts.out
=> test: make integration::workers::workers test inspectable

README.md
=> chore: update logo links in README

cli/flags.rs
Add testing for `shuffle` options.
=> test(cli): add test for deno test --shuffle

cli/tests/unit/http_test.ts, extensions/http/01_http.js, extensions/http/lib.deno_http.unstable.d.ts
=> BREAKING(unstable): Rename Deno.WebSocketUpgrade::websocket to socket

README.md
The contributing section recommends to read the style guide and other useful things.
=> chore: update README.md to point at the contributing section rather than the style guide

Cargo.lock, cli/Cargo.toml, extensions/fetch/Cargo.toml, runtime/Cargo.toml
=> chore: release deno_fetch

cli/import_map.rs
=> fix: support windows file specifiers with import maps

Cargo.lock, extensions/ffi/Cargo.toml
=> Upgrade deno-libffi to 0.0.4, fixes M1 build

cli/lsp/config.rs, cli/lsp/language_server.rs, cli/tests/integration/lsp_tests.rs, cli/tests/lsp/code_action_params_refactor.json, cli/tests/lsp/code_action_response_no_disabled.json, cli/tests/lsp/code_action_response_refactor.json, cli/tests/lsp/initialize_params.json, cli/tests/lsp/initialize_params_ca_no_disabled.json, cli/tests/lsp/initialize_params_code_lens_test.json, cli/tests/lsp/initialize_params_code_lens_test_disabled.json, cli/tests/lsp/initialize_params_did_config_change.json, cli/tests/lsp/initialize_params_disabled.json, cli/tests/lsp/initialize_params_registry.json, cli/tests/lsp/initialize_params_unstable.json
=> feat(lsp): support clients which do not support disabled code actions

.github/workflows/ci.yml
https://github.com/softprops/action-gh-release/issues/139
=> build: pin softprops/action-gh-release

.github/workflows/ci.yml, Cargo.lock, cli/tests/error_018_hide_long_source_js.js.out, cli/tests/test/no_check.out, core/Cargo.toml
=> upgrade: rusty_v8 0.26.0

cli/tests/cafile_info.ts.out, cli/tests/integration/mod.rs
=> test: reenable cafile tests

cli/flags.rs
See https://github.com/denoland/manual/issues/42. 
This PR updates the CLI help test for code coverage to make clear the coverage value.
=> doc: improve coverage CLI help text

cli/tools/test_runner.rs
=> fix(cli): sort file test module specifiers

cli/tests/integration/watcher_tests.rs
Ref https://github.com/denoland/deno/issues/10948
=> test: mark run_watch test as flaky

cli/tests/unit/webcrypto_test.ts, ext/crypto/00_crypto.js
=> fix(ext/crypto): take a copy of keyData bytes

cli/tests/integration/test_tests.rs, cli/tests/testdata/test/filter.out, cli/tests/testdata/test/filter/a_test.ts, cli/tests/testdata/test/filter/b_test.ts, cli/tests/testdata/test/filter/c_test.ts
=> test(cli): add test for test filtering

cli/fs_util.rs, cli/main.rs, cli/tools/test_runner.rs
=> refactor(cli): generalize module specifier collection

cli/tests/unit/http_test.ts, ext/http/lib.rs
Fixes https://github.com/denoland/deno/issues/11651
=> fix(ext/http): remove unwrap() when HTTP conn errors

cli/fs_util.rs
Specifier collection partitions remote specifiers in their own group which is appended to the collected specifiers at the end of the routine meaning that the input order isn't respected for remote specifiers.
This retains the input order so that remote tests run in the order they're listed.
=> fix(cli): retain input order of remote specifiers

tools/wpt/expectation.json
This PR rolls WPT to https://github.com/web-platform-tests/wpt/commit/7eb7372a613fb3a4a7d4160d8292ac2b95b29864
=> chore: roll wpt

.github/workflows/ci.yml
This change was suggested by @ry in a comment
=> ci: rename `kind` to `job`

cli/tests/integration/test_tests.rs, cli/tests/testdata/test/load_unload.out, cli/tests/testdata/test/load_unload.ts, cli/tools/test_runner.rs
Fixes https://github.com/denoland/deno/issues/11701
=> fix(cli): dispatch load event before tests are run

cli/tests/unit/http_test.ts, ext/http/lib.rs
Closes https://github.com/denoland/deno/issues/11595
Thanks to @asos-craigmorten for providing a test case.
=> test(ext/http): add test for incomplete HTTP message

cli/tests/unit/net_test.ts
=> chore(cli/tests): disable flaky test on macos ci

cli/lsp/README.md
=> docs(lsp): Change deno/registryStatus -> deno/registryState

runtime/web_worker.rs
=> refactor: fix typo in web_worker.rs

cli/flags.rs, cli/main.rs, cli/tools/test_runner.rs
Closes https://github.com/denoland/deno/issues/11799
=> fix(cli/flags): require a non zero usize for concurrent jobs

cli/main.rs
=> fix main branch

ext/web/10_filereader.js, tools/wpt/expectation.json
=> fix: FileReader.readAsText compat

.github/stale.yml
Getting a few stales on things that should be stale...
=> chore: add refactor and chore to exempt stale labels

core/inspector.rs, runtime/inspector_server.rs, runtime/web_worker.rs, runtime/worker.rs
Preparatory work for https://github.com/denoland/deno/pull/11732
=> refactor: cleanup Inspector and InspectorServer implementations

README.md
=> docs(README): Change the logo to vector image

.github/workflows/ci.yml
No code changes, minor grammatical errors in comments.
=> cleanup(.github/workflows): Minor typo in comments

Cargo.lock, cli/bench/deno_http_native.js, core/Cargo.toml
This updates V8 to version 9.4.
=> chore: update to rusty_v8 0.27.0

runtime/js/40_testing.js
This gives reporting stage a distinct function in the test harness for clarity as the way to serialise the enums aren't that obvious and can't easily be forwarded.
Minor thing that's been bugging me that I didn't do initially, partially extracted from https://github.com/denoland/deno/pull/11789 which is probably blocked for a while.
=> refactor(testing): use discrete report functions

cli/tests/integration/run_tests.rs, cli/tests/testdata/dom_exception_formatting.ts, cli/tests/testdata/dom_exception_formatting.ts.out, core/error.rs
=> fix(ext/web): Format terminal DOMExceptions properly

runtime/js/40_signals.js
Closes https://github.com/denoland/deno/issues/11933
=> chore: add better error message for signal API on Windows

Cargo.lock, cli/Cargo.toml, ext/http/Cargo.toml, runtime/Cargo.toml
Requested by @bnoordhuis, contains fixed resource leak (#11955)
=> chore: release deno_http 0.8.0

ext/http/README.md
=> chore: add README to ext/http/

.devcontainer/Dockerfile, .github/workflows/ci.yml, runtime/errors.rs
=> chore: upgrade Rust to 1.55.0

core/01_core.js, core/ops_builtin.rs, ext/http/01_http.js
=> perf(ext/http): optimize auto cleanup of request resource

cli/import_map.rs
Regression introduced in https://github.com/denoland/deno/pull/11551
Fixes https://github.com/denoland/deno/issues/11975
=> fix: Query string percent-encoded in import map

core/lib.deno_core.d.ts, ext/fetch/26_fetch.js, ext/http/01_http.js, ext/websocket/01_websocket.js, ext/websocket/02_websocketstream.js
Using API introduced in https://github.com/denoland/deno/pull/11978 we can get rid of some more code throughout the codebase.
=> refactor: use Deno.core.tryClose

ext/web/10_filereader.js, tools/wpt/expectation.json
fix https://github.com/denoland/deno/issues/11816
=> fix: FileReader onevent attributes don't conform to spec

cli/tests/unit/webcrypto_test.ts, ext/crypto/lib.deno_crypto.d.ts
whoops! (again :face_with_head_bandage:)
=> fix(ext/crypto): add HkdfParams and Pkdf2Params types

cli/tests/testdata/worker_message_before_close.js, cli/tests/testdata/worker_message_before_close.js.out
=> fix: worker_message_before_close was flaky

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/integration/mod.rs, runtime/js/90_deno_ns.js
Closes https://github.com/denoland/deno/issues/12021
=> feat: stabilise Deno.upgradeWebSocket

cli/tests/unit/http_test.ts
Closes https://github.com/denoland/deno/issues/12046
=> fix: change assertion in httpServerIncompleteMessage test

cli/schemas/config-file.v1.json, cli/schemas/module-graph.json
=> chore: update URL for schemas

tools/cut_a_release.md, tools/release/02_publish_dependency_crates.ts, tools/release/helpers/deno_workspace.ts
Improvements based on doing the 1.14 release.
=> chore(scripts): improvements to the release scripts based on the 1.14 release

cli/flags.rs, core/Cargo.toml
=> chore: update tagline

cli/tests/unit/flock_test.ts
=> chore(tests): fix flaky flock tests

cli/fmt_errors.rs, cli/ops/errors.rs, cli/tests/integration/run_tests.rs, cli/tests/testdata/import_data_url_error_stack.ts.out, cli/tests/testdata/long_data_url_formatting.ts, cli/tests/testdata/long_data_url_formatting.ts.out, core/02_error.js, runtime/js/40_error_stack.js, runtime/js/99_main.js
Co-authored-by: Mike White <mike.white@auctane.com>
=> fix(cli/fmt_errors): Abbreviate long data URLs in stack traces

ext/net/lib.rs, ext/net/ops.rs, ext/net/ops_tls.rs
=> refactor(ext/net): make op_connect & op_connect_tls public

cli/tests/unit/ffi_test.ts, test_ffi/src/lib.rs, test_ffi/tests/integration_tests.rs, test_ffi/tests/test.js
=> test(ext/ffi): add tests for different parameter and return types

Cargo.lock, cli/Cargo.toml, ext/net/Cargo.toml, runtime/Cargo.toml
=> chore: bump deno_net

.github/workflows/ci.yml, Cargo.lock, core/Cargo.toml
=> upgrade serde_v8 and rusty_v8

cli/specifier_handler.rs
=> refactor: simplify FetchFuture

tools/cut_a_release.md
Last bit of feedback for the document was a pre-flight checklist that I think would help someone who doesn't do it often or for the first time.
=> docs(tools): updates to cutting a release

cli/tests/integration/watcher_tests.rs
no behavior change, just less code
=> refactor: clean up watcher tests

runtime/web_worker.rs, runtime/worker.rs
=> refactor: Remove depreated Worker::execute_module

runtime/worker.rs
A trivial PR to test fastci with cache, improves/shortens wording of a comment
=> chore(runtime): minor comment improvement

cli/tests/integration/mod.rs, cli/tests/testdata/http2_request_url.ts, cli/tests/unit/http_test.ts, ext/http/lib.rs
=> fix(ext/http): include port number in h2 urls

ext/fetch/23_request.js
=> refactor(fetch/Request): inline defaultInnerRequest

ext/http/01_http.js
fix(ext/http/01_http.js) sonarlint(javascript:S1871) 
This branch's code block is the same as the block for the branch on line 73. [+1 location]sonarlint(javascript:S1871)
=> fix(ext/http/01_http.js) sonarlint(javascript:S1871)

ext/crypto/lib.rs
As per spec.
Can I get a `hacktoberfest-accepted` label for this PR? :-)
=> fix(ext/crypto): use NotSupportedError in importKey()

ext/crypto/lib.rs
Ref https://www.rfc-editor.org/rfc/rfc3447#appendix-A.2.1
can this be marked for Hacktoberfest? :-)
=> feat(ext/crypto): decode RSAES-OAEP-params with default values

.github/workflows/ci.yml, Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml
=> chore: Release crates for v1.14.3

.dlint.json
Ref https://github.com/denoland/deno_lint/pull/966
=> chore: enable camelcase rule in dlint

.github/workflows/ci.yml
=> upgrade to Node 17

ext/web/lib.deno_web.d.ts
=> fix(ext/web/streams): typings: make getReader return ReadableStreamBYOBReader & stricter byob typings 

cli/file_fetcher.rs, cli/lsp/completions.rs, cli/lsp/registries.rs
=> fix(lsp): cache unsupported import completion origins

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/tests/integration/lsp_tests.rs
=> fix(lsp): display module types only dependencies on hover

cli/tools/lint.rs
=> fix(lint): use recommended tags when no tags specified in config, but includes or excludes are

test_ffi/src/lib.rs, test_ffi/tests/test.js
=> feat(test_ffi): add mutable buffer tests

Cargo.lock, cli/tests/unit/http_test.ts, serde_v8/Cargo.toml, serde_v8/src/de.rs, serde_v8/src/magic/string_or_buffer.rs, serde_v8/tests/de.rs
Test for #12724. The offending commit is https://github.com/denoland/deno/commit/c27ef0ac7b5fd7aba4de24292e80387c8243896e.
=> fix: non ascii buffer response in http server

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
Waiting on https://github.com/denoland/deno/pull/12730
=> chore: bump crate version for 1.16.1

test_util/src/pty.rs
=> chore(tests): fix typo in pty.rs

cli/file_fetcher.rs
=> refactor: clean ups in cli/file_fetcher.rs

cli/tests/integration/lsp_tests.rs
When making an edit that prevents a successful parsing of the file, the LSP loses type information on the identifiers whose type is declared outside the current file.
This is made apparent when trying to get completion on a method right after adding the dot, as the dot often introduced a syntax error prior to starting typing the method. If the object is of a type declared outside the current file, the LSP would give it the type `any` during that short span, making the completion of methods impossible.
This commits adds an ignored test that demonstrates the bug. It passes on commit 74a93fdf63a17de990954399b10eb6dfe7dd1973 but fails on commit 34a9ddff091950aee9d89915cd13944259e7d346.
=> tests(lsp): regression test for #12753

Cargo.lock, core/Cargo.toml, serde_v8/Cargo.toml
=> upgrade: v8 crate 0.35.0 (V8 9.7.106.5)

core/runtime.rs
=> fix(core): don't panic when evaluating module after termination

cli/tests/unit/read_file_test.ts
This commit adds some tests that demonstrate that Deno.readFile reads
the entire file, even if the read file is extended during read.
#12366 is tangentially related
=> tests: extend readFile file length during read

cli/tests/unit/webcrypto_test.ts, ext/crypto/lib.rs, tools/wpt/expectation.json
=> fix(ext/crypto): don't panic on decryption failure

cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/lsp/semantic_tokens.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs, cli/tests/testdata/lsp/document_symbol_response.json, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
Ref: #8643
This also does some other minor cleanups and refactors in the lsp.
=> feat(lsp): add workspace symbol provider

cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
=> feat(lsp): add type definition provider

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: bump crate versions for 1.16.3

Cargo.lock, cli/Cargo.toml, cli/lsp/analysis.rs, cli/lsp/capabilities.rs, cli/lsp/completions.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/registries.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs
=> chore: upgrade lspower to 1.4.0

cli/tests/unit/buffer_test.ts, cli/tests/unit/testing_test.ts, cli/tests/unit/webcrypto_test.ts
=> tests: add 'await' to all invocations of 'assertRejects'

cli/tests/testdata/websocketstream_test.ts, ext/websocket/lib.rs
Fix a bad resource ID error when aborting a WebSocketStream immediately
after its creation.
=> [v1.16] fix(websocket): bad rid on WebSocketStream abort (#12913)

cli/tools/fmt.rs, cli/tools/lint.rs
=> refactor(cli): simplify lint/format resolver logic

ext/fetch/lib.rs
A bit more clean up that should have been in cc83ad39ce3e8186c8785d47fa4801317c8fac4a
=> refactor: remove deno_fetch::HttpClientDefaults

core/runtime.rs
=> [v1.16] fix(core): Wake up the runtime if there are ticks scheduled (#12933)

.github/workflows/ci.yml
=> ci: fix sysroot setup

cli/tests/testdata/test/unresolved_promise.out, cli/tests/testdata/top_level_await_circular.out, cli/tests/testdata/top_level_await_unresolved.out, core/runtime.rs
Fixes https://github.com/denoland/deno/issues/12947
=> fix(core): Fix typo in no-pending-ops error message

Cargo.lock, ext/tls/Cargo.toml, ext/tls/lib.rs
=> refactor: deno_tls does not depend on reqwest

.github/workflows/wpt_epoch.yml
Version `v1` is no longer supported.
Latest releases: https://github.com/actions/setup-python/releases
1. Give the PR a descriptive title. ✅ 
2. Ensure there is a related issue and it is referenced in the PR text. 🚫 
3. Ensure there are tests that cover the changes. 🚫 
4. Ensure `cargo test` passes. ✅ 
5. Ensure `./tools/format.js` passes without changing files. ✅ 
6. Ensure `./tools/lint.js` passes. ✅
=> fix(ci): Updates `setup-python` action version

.github/workflows/ci.yml
=> [v1.16] ci: fix sysroot setup (#12958)

.github/workflows/ci.yml, Cargo.lock, core/Cargo.toml, serde_v8/Cargo.toml
=> chore: update to rusty v8 0.36.0

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: bump crate version for v1.16.4

.github/workflows/ci.yml, bench_util/src/profiling.rs, cli/lsp/mod.rs, cli/tools/installer.rs, core/async_cancel.rs, core/modules.rs, core/runtime.rs, ext/net/ops_tls.rs, runtime/ops/permissions.rs, serde_v8/examples/basic.rs, serde_v8/src/de.rs
=> chore: upgrade to Rust 1.57.0

cli/lockfile.rs, cli/tools/coverage.rs, cli/tools/fmt.rs
This pr used deno_format to format json.
Try to support #9693
=> feat(cli): use deno fmt for lock and coverage files

ext/web/06_streams.js, tools/wpt/expectation.json
=> feat(streams): support abort reasons in streams

Cargo.lock, cli/Cargo.toml, cli/ast/mod.rs, cli/http_util.rs, cli/lsp/code_lens.rs, cli/tests/integration/repl_tests.rs, cli/tests/testdata/bundle.test.out, cli/tests/testdata/compiler_api_test.ts, cli/tools/repl/mod.rs, core/Cargo.toml
Closes #12808
Closes #11591
Closes #12532
Closes #10861
Closes #12739
Closes #12448
Closes #12313
Closes #12220
Closes #12086 
Closes #11575 
Closes #11354
=> fix: upgrade swc fixing many bundling and `--no-check` bugs

ext/crypto/00_crypto.js
This commit de-duplicates and cleans up some logic in `importKey`. There
are no functional changes in this commit (just moves code around).
=> refactor(ext/crypto): clean up `importKey` logic

ext/crypto/00_crypto.js
This commit de-duplicates and cleans up some logic in `exportKey`. There
are no functional changes in this commit (just moves code around).
=> refactor(ext/crypto): clean up `exportKey` logic

ext/crypto/00_crypto.js
This commit de-duplicates the buffer copying code in ext/crypto.
Co-authored-by: yacinehmito <yacinehmito@users.noreply.github.com>
=> refactor(ext/crypto): de-duplicate copyBuffer code

ext/web/03_abort_signal.js, ext/web/lib.deno_web.d.ts, tools/wpt/expectation.json
=> feat(ext/web): Implement `AbortSignal.prototype.throwIfAborted()`

Cargo.lock
Closes https://github.com/denoland/deno/issues/12989
=> chore: update swc_ecma_dep_graph

cli/dts/lib.deno.unstable.d.ts
=> docs(EmitOptions): Fix typo

Cargo.lock, ext/crypto/00_crypto.js, ext/crypto/Cargo.toml, ext/crypto/generate_key.rs, ext/crypto/lib.rs, ext/crypto/shared.rs
Clean up the rust side of crypto.subtle.generateKey using some enums.
=> refactor(ext/crypto): generateKey rust cleanup

Cargo.lock, cli/Cargo.toml, cli/emit.rs, cli/lsp/documents.rs, cli/proc_state.rs, cli/tests/testdata/095_cache_with_bare_import.ts.out, cli/tests/testdata/error_011_bad_module_specifier.ts.out, cli/tests/testdata/error_012_bad_dynamic_import_specifier.ts.out, cli/tests/testdata/error_014_catch_dynamic_import_error.js.out, cli/tests/testdata/error_027_bundle_with_bare_import.ts.out, cli/tests/testdata/error_type_definitions.ts.out, cli/tools/test.rs, cli/tsc.rs
This is what it takes to update to the deno_graph changes.
=> chore: updates to support deno_graph API changes

tools/lint.js
=> chore: lint cli/tests/unit/

ext/crypto/00_crypto.js
This aligns all of the error messages, and makes falsey comparisons
more strict.
=> fix(ext/crypto): various cleanup in JWK imports

cli/Cargo.toml
=> chore: update cli/Cargo.toml

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/tests/integration/lsp_tests.rs, cli/tests/testdata/lsp/code_action_params_import_assertion.json, cli/tests/testdata/lsp/code_action_response_import_assertion.json
=> fix(lsp): provide diagnostics for import assertions

cli/tests/testdata/websocketstream_test.ts, cli/tests/unit/read_file_test.ts, cli/tests/unit/read_text_file_test.ts, cli/tests/unit/write_file_test.ts, ext/websocket/02_websocketstream.js, ext/websocket/lib.rs, runtime/errors.rs, runtime/js/12_io.js, runtime/js/40_write_file.js
=> feat: Support abort reasons in Deno APIs and `WebSocketStream`

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: release crates for v1.17.0

cli/dts/lib.deno.shared_globals.d.ts
=> chore: add codeblocks for lib.deno.shared_globals.d.ts

cli/ast/transforms.rs
=> fix(repl): support assertions on import & export declarations

ext/websocket/02_websocketstream.js
=> fix(ext/websocket): don't error with "sending after closing" when closing

cli/main.rs, cli/tools/coverage.rs, cli/tools/doc.rs, cli/tools/test.rs
=> refactor: Use dedicated flags structures

cli/main.rs, cli/standalone.rs, cli/tools/installer.rs, cli/tools/test.rs, cli/tools/upgrade.rs, runtime/worker.rs
=> refactor: cleanup cli/main.rs

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: release crates for v1.17.1

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, cli/tests/testdata/compat/import_map.json, cli/tests/testdata/compat/import_map_https_imports.mjs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: merge v1.17.1 into main

tools/cut_a_release.md
=> update release instructions for M1 build

core/runtime.rs
=> chore(core): remove stale TODOs

cli/compat/mod.rs, cli/main.rs, cli/tests/integration/compat_tests.rs, cli/tests/testdata/compat/test_runner/cjs.js, cli/tests/testdata/compat/test_runner/cjs.out, cli/tests/testdata/compat/test_runner/esm.mjs, cli/tests/testdata/compat/test_runner/esm.out, cli/tests/testdata/compat/test_runner/top_level_assertion_cjs.js, cli/tests/testdata/compat/test_runner/top_level_assertion_cjs.out, cli/tests/testdata/compat/test_runner/top_level_assertion_esm.mjs, cli/tests/testdata/compat/test_runner/top_level_assertion_esm.out, cli/tests/testdata/compat/test_runner/top_level_fail_cjs.js, cli/tests/testdata/compat/test_runner/top_level_fail_cjs.out, cli/tests/testdata/compat/test_runner/top_level_fail_esm.mjs, cli/tests/testdata/compat/test_runner/top_level_fail_esm.out, cli/tools/test.rs
=> feat(test): Add support for "deno test --compat"

.github/CODEOWNERS
=> chore: add divy to CODEOWNERS

cli/tests/testdata/045_proxy_test.ts, cli/tests/unit/http_test.ts
Blocked by https://github.com/denoland/deno_std/pull/1776
Required for https://github.com/denoland/deno/pull/13127
=> chore: update std submodule to efa94f2

cli/compat/mod.rs, cli/main.rs, cli/tests/integration/compat_tests.rs
=> feat(compat) preload Node.js native modules in global vars in node compat REPL

Cargo.lock, cli/tests/unit/signal_test.ts, runtime/Cargo.toml, runtime/ops/signal.rs
=> fix(signals): prevent panic when listening to forbidden signals

.dprint.json, Cargo.lock, cli/Cargo.toml, cli/ast/mod.rs, cli/ast/transforms.rs, cli/lsp/language_server.rs, cli/tests/testdata/bundle_jsx.out, cli/tests/unit/test_util.ts, cli/tools/fmt.rs
Closes #13193
Closes #12799
Closes #13183
Closes #12570
=> fix: upgrade swc_ecmascript to 0.103

cli/fs_util.rs
=> fix: support mts files for `deno test` & `deno fmt`

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: release crates for v1.17.2

.github/workflows/ci.yml
=> ci: cycle cache key

core/lib.deno_core.d.ts
I have tried to used this to typecheck a project and TSC found issues
in lib.deno_core.d.ts itself.
=> fix: Get lib.deno_core.d.ts to parse correctly

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, cli/tests/testdata/compat/import_map.json, cli/tests/testdata/compat/import_map_https_imports.mjs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: forward 1.17.2 to main

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/registries.rs, cli/tests/integration/lsp_tests.rs, cli/tests/testdata/lsp/did_open_params_import_hover.json, cli/tests/testdata/lsp/initialize_params.json, cli/tests/testdata/lsp/initialize_params_registry.json, cli/tests/testdata/lsp/registries/deno-import-intellisense.json, cli/tests/testdata/lsp/registries/doc_a_latest_mod.ts.json
Closes: #13272
https://user-images.githubusercontent.com/1282577/148323679-cf72e74a-a97b-401b-b615-e40d859dba2c.mp4
=> feat(lsp): provide registry details on hover if present

ext/web/05_base64.js
WPT tests are pending on getting html idlharness tests running.
Closes #13341
=> fix(ext/web): handle no arguments in atob

.github/workflows/ci.yml
=> error on warnings

cli/dts/lib.deno.unstable.d.ts, ext/ffi/00_ffi.js, ext/ffi/lib.rs, runtime/js/90_deno_ns.js, test_ffi/src/lib.rs, test_ffi/tests/ffi_types.ts, test_ffi/tests/integration_tests.rs, test_ffi/tests/test.js
=> feat(ext/ffi): UnsafeFnPointer API

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, cli/tests/testdata/compat/import_map.json, cli/tests/testdata/compat/import_map_https_imports.mjs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: forward v1.17.3 to main

Cargo.lock, cli/Cargo.toml, cli/lsp/language_server.rs, cli/ops/runtime_compiler.rs, cli/proc_state.rs, cli/resolver.rs, cli/tools/doc.rs
Upgrades to version 0.6 of import_map.
=> refactor: upgrade to import_map v0.6

ext/web/06_streams.js, ext/web/06_streams_types.d.ts, tools/wpt/expectation.json
=> feat(streams): reject pending reads when releasing reader

ext/web/06_streams.js
Follow up to #13375, as per https://github.com/denoland/deno/pull/13375#discussion_r784998827
=> fix(streams): update TypeError message for pending reads when releasing reader

.devcontainer/Dockerfile
Followup https://github.com/denoland/deno/pull/13377
=> chore: upgrade to rust 1.58 in the dev container

cli/lsp/language_server.rs
=> refactor: simplify how LSP deals with config file specifier

cli/tests/integration/run_tests.rs, cli/tests/testdata/colors_without_globalThis.js, ext/console/01_colors.js, ext/console/02_console.js, runtime/js/99_main.js
Fixes https://github.com/denoland/deno/issues/13357
=> fix(ext/console): don't depend on globalThis present

ext/crypto/import_key.rs
=> fix(ext/crypto): validate maskGenAlgorithm asn1 in importKey

cli/dts/lib.deno.ns.d.ts, cli/tests/unit/error_test.ts
=> fix(cli/dts): add NotSupported error type

cli/tests/integration/inspector_tests.rs, cli/tests/testdata/inspector/memory.js
Closes https://github.com/denoland/deno/issues/13244
=> tests: Add inspector tests for "Memory" and "Profile" tabs

core/runtime.rs
This is similar to run_event_loop X poll_event_loop. The reason for
this is that the future returned by resolve_value has the same
lifetime as the runtime. That is fine when rust can reason about it,
but in some cases it can't.
In the particular case we have, our runtime, which includes a
JsRuntime, is stored in a Rc<RefCell<...>>. With this change we can
easily poll to see if a value has been fulfilled.
=> refactor(core): Extract poll_value out of resolve_value

cli/lsp/diagnostics.rs, cli/tests/integration/lsp_tests.rs
Previously I must have accidentally tested the wrong binary in the editor and forgot that each publish needs to include the diagnostics from all sources (instead of the client figuring that out). I've fixed the tests now to properly only select the last messages sent for each specifier and it gets the diagnostics for that.
Also fixes some flaky tests caused by it now being done in parallel.
=> fix(lsp): independent diagnostic publishing should include all diagnostic sources on each publish

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, cli/tests/testdata/compat/import_map.json, cli/tests/testdata/compat/import_map_https_imports.mjs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: forward v1.18.1 to main

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/process_test.ts, runtime/js/90_deno_ns.js, runtime/ops/signal.rs
=> feat: stabilize addSignalListener API

cli/tests/integration/run_tests.rs, cli/tests/testdata/import_extensionless.ts, cli/tests/testdata/import_extensionless.ts.out, cli/tsc.rs, test_util/src/lib.rs
=> fix(cli): handle extensionless imports better

Cargo.lock, core/Cargo.toml, core/examples/ts_module_loader.rs, core/examples/ts_module_loader.ts
=> example(core): Add example for TypeScript transpiling via deno_ast

cli/tests/integration/run_tests.rs, cli/tests/testdata/issue13562.ts, cli/tests/testdata/issue13562.ts.out, cli/tsc.rs
=> fix(cli): handle local files with query params on emit

sanitizers_test.ts
Accidentally introduced in https://github.com/denoland/deno/pull/13296 ?
=> chore: rm toplevel sanitizer_test.ts

ext/webgpu/01_webgpu.js
=> refactor: fix primordials for WebGPU

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, cli/tests/testdata/compat/import_map.json, cli/tests/testdata/compat/import_map_https_imports.mjs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/timers/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: forward v1.18.2 to main

cli/lsp/language_server.rs
I haven't been able to reproduce this scenario in order to write a test, but this should help give us better information for the error message and probably not fail.
Closes #13601
=> fix(lsp): do not panic getting root_uri to auto discover configuration file

cli/compat/esm_resolver.rs, cli/compat/testdata/subpath/main.js, cli/compat/testdata/subpath/node_modules/foo/package.json
=> fix(compat): ESM resolver for package subpath

cli/lsp/tsc.rs
=> fix(lsp): op_exists handles bad specifiers

cli/cdp.rs, cli/main.rs, cli/tests/integration/repl_tests.rs, cli/tools/coverage/mod.rs, cli/tools/repl/channel.rs, cli/tools/repl/editor.rs, cli/tools/repl/mod.rs, cli/tools/repl/session.rs, core/inspector.rs, test_util/src/pty.rs
=> refactor: factor out CDP message types

Cargo.lock, cli/Cargo.toml, cli/lsp/completions.rs, cli/lsp/language_server.rs, cli/proc_state.rs, cli/tests/integration/lsp_tests.rs, cli/tests/testdata/lsp/import-map-completions.json
Closes #13619
(This also updates to import_map v0.8.0)
=> feat(lsp): provide completions from import map if available

cli/dts/lib.deno.ns.d.ts, runtime/js/40_files.js, runtime/js/40_process.js, runtime/js/90_deno_ns.js
<s>Still need to update `deno lint` to warn about deprecated `Deno.File`.</s>
Closes https://github.com/denoland/deno/issues/13661
=> feat: Add Deno.FsFile, deprecate Deno.File

cli/dts/lib.deno.ns.d.ts
=> fix: add missing fields to Deno.FsFile

Cargo.lock, core/Cargo.toml, serde_v8/Cargo.toml
=> chore: update v8

cli/tests/unit/http_test.ts
=> tests: unflake httpServerIncompleteMessage

cli/tests/integration/mod.rs, cli/tests/testdata/websocket_server_idletimeout.ts, cli/tests/testdata/websocketstream_test.ts, cli/tests/unit/fetch_test.ts, cli/tests/unit/http_test.ts, cli/tests/unit/net_test.ts
=> tests: deflake a bunch of net related tests

cli/dts/lib.deno.unstable.d.ts, ext/net/lib.deno_net.d.ts, ext/net/ops.rs
=> chore: make new TCP conn methods unstable

runtime/permissions.rs
=> feat: never prompt for hrtime permission

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: release crates for v1.19.0

cli/flags.rs, cli/tests/integration/test_tests.rs, cli/tests/testdata/test/no_prompt_by_default.out, cli/tests/testdata/test/no_prompt_by_default.ts, cli/tests/testdata/test/no_prompt_with_denied_perms.out, cli/tests/testdata/test/no_prompt_with_denied_perms.ts
=> fix(test): use --no-prompt by default

.github/workflows/ci.yml
Addresses https://github.com/denoland/deno/pull/13811#issuecomment-1056738147
=> chore: add `test-flaky-ci` label to disable default workflow concurrency

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: bump crate version for 1.19.2

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
- chore: bump crate version for 1.19.2 (#13824)
- 1.19.2 (#13825)
=> 1.19.2 commits into main

Cargo.lock, ext/http/Cargo.toml, runtime/Cargo.toml
=> chore: bump deno_http

README.md
=> docs(README): update urls of `shell` and `powershell` deno installers

.github/workflows/ci.yml
=> fix(ci): restore compatibility with old glibc

cli/tools/test.rs
https://github.com/denoland/deno/pull/13713#discussion_r821824325
=> refactor(test): don't spawn additional thread

cli/display.rs, cli/main.rs, cli/tools/test.rs
=> refactor: add cli/display.rs module

cli/tests/testdata/test/no_prompt_by_default.out, cli/tests/testdata/test/no_prompt_by_default.ts, cli/tests/testdata/test/no_prompt_with_denied_perms.out, cli/tests/testdata/test/no_prompt_with_denied_perms.ts
These tests were not checking what they were supposed to check. Upstreaming changes from https://github.com/denoland/deno/pull/13713
=> test: update expected test output for 'deno test'

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts
https://github.com/denoland/deno/pull/13713#discussion_r821764638
=> types: add Deno.PermissionOptions

cli/tests/integration/test_tests.rs, cli/tests/testdata/test/markdown_with_comment.md, cli/tests/testdata/test/markdown_with_comment.out, cli/tools/test.rs
=> fix(test): skip typechecking for blocks inside HTML comments

Cargo.lock, core/Cargo.toml, core/bindings.rs, core/runtime.rs, core/serialize_deserialize_test.js, serde_v8/Cargo.toml, serde_v8/examples/basic.rs, serde_v8/src/utils.rs
=> chore: update rusty_v8 to 0.41.0

cli/tests/unit/webcrypto_test.ts, ext/crypto/00_crypto.js
=> fix(ext/crypto): handle JWK import with "use"

cli/tools/task.rs
=> feat(task): allow colons in task name

cli/tests/integration/compat_tests.rs
Closes https://github.com/denoland/deno/issues/13919
=> test: fix flaky compat tests

.cargo/config
Waiting on https://github.com/denoland/deno_third_party/pull/103
Incremental debug builds:
Fresh debug builds are ~50s
```
brew install llvm
cargo build 
```
=> chore: use LLD on aarch64-apple-darwin

Cargo.toml
=> perf: opt-level-3 all of ext/*

core/01_core.js, core/bindings.rs, core/runtime.rs
To avoid OOB & other ExternalReference snapshot serialization issues
=> fix(core): nuke Deno.core.ops pre-snapshot

ext/webidl/README.md
=> chore(ext/webidl): change spec link

.github/workflows/ci.yml, rust-toolchain.toml
https://github.com/denoland/deno/pull/13814#discussion_r817802958
=> chore: add Rust toolchain components

cli/tools/upgrade.rs
Related to https://github.com/denoland/deno/issues/7409
Add support for DENO_CERT in the `deno upgrade` command
=> fix(cli): Add support for DENO_CERT in upgrade command

cli/tests/integration/compile_tests.rs, cli/tools/standalone.rs
=> fix(cli): improve `deno compile` error messages

cli/tests/unit/http_test.ts, ext/http/01_http.js, runtime/ops/http.rs
=> feat(ext/net): Deno.upgradeHttp handles unix connections

core/runtime.rs, ops/lib.rs
=> fix(ops): throw TypeError on op return failure

cli/tests/unit/console_test.ts, ext/console/02_console.js
closed: #13991 
before
after this pr
I don't know if this is the right way to resolve this issue, if not please let me know the right way, I'll change the PR
=> fix(ext/console): Console log error with a Proxy of a Map

cli/tests/testdata/bench/allow_all.ts, cli/tests/testdata/test/allow_all.ts, cli/tests/testdata/workers/permission_echo.js, cli/tests/testdata/workers/test.ts, cli/tests/unit/http_test.ts, cli/tests/unit/net_test.ts, cli/tests/unit/timers_test.ts, cli/tests/unit/tty_color_test.ts, runtime/permissions.rs
=> fix: actually don't inherit runtime permissions

cli/lsp/capabilities.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/repl.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs, cli/tests/testdata/lsp/initialize_params_workspace_enable_paths.json
Ref: denoland/vscode_deno#633
This is functionally working, just need to write tests, but this branch plus https://github.com/denoland/vscode_deno/pull/635 should allow folks to take it for a test spin. @dsherret especially if you could give it a spin on Windows.  I think I have done everything to make it work well, but windows always has surprises.
=> feat(lsp): support deno.enablePaths setting

cli/tests/unit/http_test.ts
Closes https://github.com/denoland/deno/issues/13988
=> refactor: remove loops in cli/tests/unit/http_test.ts

cli/tests/integration/test_tests.rs, cli/tests/testdata/test/ops_sanitizer_missing_details.out, cli/tests/testdata/test/ops_sanitizer_missing_details.ts, runtime/js/40_testing.js
Closes https://github.com/denoland/deno/issues/13938
Closes https://github.com/denoland/deno/issues/13729
=> fix(test): don't error on missing op details

cli/tests/integration/compile_tests.rs
=> tests(cli): ignore previously unignored test

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
Contains release commits from v1.20 branch for 1.20.2.
=> Release 1.20.2

.github/workflows/ci.yml
https://github.com/actions/checkout#checkout-v3
=> Update actions/checkout@v2 to v3

ext/fetch/20_headers.js, ext/fetch/23_request.js, ext/webgpu/02_idl_types.js
=> chore(ext): fix typo in ext/webgpu, ext/fetch

cli/dts/lib.deno.ns.d.ts, cli/tests/unit/process_test.ts, runtime/js/40_process.js
=> fix: `Deno.run` - do not modify user provided `cmd` array

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/esm_resolver.rs, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: forward v1.20.3 release commit to main

cli/compat/mod.rs
=> chore: add semi-colon to compat/mod.rs export default output

Cargo.lock, cli/tests/integration/lsp_tests.rs, test_util/Cargo.toml, test_util/src/lsp.rs
=> chore(tests): add more lsp tests for formatting

cli/standalone.rs, cli/tests/integration/compile_tests.rs, cli/tests/testdata/standalone_follow_redirects.ts, cli/tests/testdata/standalone_follow_redirects_2.js
Fixes https://github.com/denoland/deno/issues/13704
=> fix(compile): follow redirects when resolving

tools/release/01_bump_crate_versions.ts, tools/release/04_create_release_tag.ts, tools/release/deps.ts
This will fix the Release.md for next time and also the tag name.
=> chore(ci): fix Releases.md creation and tag name

cli/tests/integration/compile_tests.rs
I thought I had merged in all the latest changes to the PR, but had missed one.
=> chore: fix main compile error

ext/http/01_http.js, ext/websocket/01_websocket.js, ext/websocket/02_websocketstream.js, ext/websocket/lib.rs
LLVM lines:
Before:
```
64998 (100%)  1906 (100%)  (TOTAL)
```
After:
```
63830 (100%)  1886 (100%)  (TOTAL)
```
=> chore(ext/websocket): custom arity

tools/cut_a_release.md
Waiting on https://github.com/denoland/deno_std/pull/2079
=> chore(ci): update deno_std release steps

cli/tests/unit/webcrypto_test.ts, ext/crypto/00_crypto.js
=> fix(ext/crypto):  check extractable in exportKey

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml, tools/release/04_post_publish.ts
Unfortunately my automated forward release commit script failed. Forgot to fetch main (will do another PR fixing it later)
=> chore: forward v1.20.5 release commit to main

cli/flags.rs
=> refactor: improve clap help text

tools/bench/rebootstrap.js
Ref https://github.com/denoland/deno/issues/14131
=> chore: use local copy of std in tools/bench/ scripts

cli/flags.rs
=> chore: add info about DENO_FUTURE_CHECK env var to --help

.github/workflows/version_bump.yml, Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
Seems like this didn't work automatically again :/ (hopefully fixed in #14289)
=> chore: forward v1.20.6 release commit to main

runtime/permissions.rs
Instead of panicking. I'm not sure how to test this.
Closes #14234
=> fix(permissions): fallback to denied access if the permission prompt fails

Cargo.lock, core/Cargo.toml, serde_v8/Cargo.toml
=> upgrade: rusty_v8 0.42.0

.github/workflows/cargo_publish.yml, .github/workflows/version_bump.yml
It seems we can't use the actor for this.
=> chore: fix version bump credentials

.github/workflows/ci.yml, Cargo.lock, cli/tests/unit/http_test.ts, core/examples/http_bench_json_ops.rs, core/resources.rs, ext/fetch/lib.rs, ext/http/01_http.js, ext/http/Cargo.toml, ext/http/lib.rs, ext/net/01_net.js, ext/net/io.rs, ext/net/ops_tls.rs, ext/web/06_streams.js, runtime/js/40_files.js, runtime/ops/io.rs, serde_v8/magic/buffer.rs
This reverts commit 8b258070542a81d217226fe832b26d81cf20113d
This reverts commit 2612b6f20fc21fb92402aa9086d13a7192ae3814
This reverts commit 57a8fc37fc99491fa2559694f78af52a597bc501
These cause `deno_std` tests to fail
=> Revert various PRs related to "ext/http"

Cargo.lock, cli/tests/unit/http_test.ts, ext/http/Cargo.toml, ext/http/lib.rs
=> Reland "feat(ext/http): stream auto resp body compression"

cli/file_watcher.rs, cli/tests/integration/watcher_tests.rs
Closes https://github.com/denoland/deno/issues/14349
=> fix(watcher): don't clear screen on start

tools/cut_a_release.md
=> chore: add release step failure instructions

cli/tests/integration/bench_tests.rs, cli/tests/testdata/bench/multifile_summary.out, cli/tools/bench.rs
=> fix(bench): report pending summary before clearing context

runtime/js/40_testing.js
=> fix(bench): eliminate sanitizeExit overhead

cli/dts/lib.deno.unstable.d.ts, cli/tests/integration/run_tests.rs, cli/tests/testdata/spawn_stdout_inherit.ts, cli/tests/testdata/spawn_stdout_inherit.ts.out, cli/tests/unit/command_test.ts, runtime/js/40_spawn.js
=> fix(runtime/js/spawn): Pass stdio options for spawn() and spawnSync()

.github/workflows/ci.yml, cli/lsp/testing/execution.rs, cli/main.rs, cli/ops/testing.rs, cli/standalone.rs, cli/tests/integration/test_tests.rs, cli/tests/testdata/test/captured_output.out, cli/tests/testdata/test/captured_output.ts, cli/tests/testdata/test/captured_output.worker.js, cli/tools/bench.rs, cli/tools/test.rs, runtime/examples/hello_runtime.rs, runtime/ops/io.rs, runtime/web_worker.rs, runtime/worker.rs
Also improves the runtime API for this scenario.
=> fix(test): capture worker stdout and stderr in test output

cli/flags.rs
fix https://github.com/denoland/deno/issues/14404
=> fix(cli): Wrap long line of the env variables help

cli/flags.rs
See https://github.com/denoland/deno/pull/14419#issuecomment-1113127332
=> fix(task): allow hyphen values after task name

Cargo.lock, cli/Cargo.toml
Closes #14427
Has https://github.com/denoland/deno_task_shell/pull/38
=> feat(unstable/task): resolve the current executable for the deno command

cli/diagnostics.rs, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/error_stack_test.ts, runtime/js/40_error_stack.js, runtime/js/90_deno_ns.js
Closes https://github.com/denoland/deno/issues/14469
=> BREAKING: Remove unstable Deno.applySourceMap API

cli/tests/unit/http_test.ts, ext/http/01_http.js
Closes https://github.com/denoland/deno/issues/14458
=> fix(ext/http): explicitly close resource after reading

cli/tools/test.rs
See #14478 for more details on why this is required :(
=> chore: fix flaky `steps_output_within` test

cli/tests/integration/run_tests.rs, cli/tests/testdata/error_name_non_string.js, cli/tests/testdata/error_name_non_string.js.out, core/error.rs
=> fix(core): avoid panic on non-string Error.name

cli/tests/testdata/compat/test_runner/cjs.out, cli/tests/testdata/compat/test_runner/esm.out, cli/tests/testdata/test/aggregate_error.out, cli/tests/testdata/test/allow_none.out, cli/tests/testdata/test/exit_sanitizer.out, cli/tests/testdata/test/fail.out, cli/tests/testdata/test/fail_fast.out, cli/tests/testdata/test/fail_fast_with_val.out, cli/tests/testdata/test/finally_timeout.out, cli/tests/testdata/test/no_prompt_by_default.out, cli/tests/testdata/test/no_prompt_with_denied_perms.out, cli/tests/testdata/test/ops_sanitizer_missing_details.out, cli/tests/testdata/test/ops_sanitizer_multiple_timeout_tests.out, cli/tests/testdata/test/ops_sanitizer_multiple_timeout_tests_no_trace.out, cli/tests/testdata/test/ops_sanitizer_unstable.out, cli/tests/testdata/test/resource_sanitizer.out, cli/tests/testdata/test/steps/failing_steps.out, cli/tests/testdata/test/steps/invalid_usage.out, cli/tools/test.rs, runtime/colors.rs
Closes https://github.com/denoland/deno/issues/14190
=> feat(test): change "failures:" headers in test report

cli/flags.rs
Adds current `deno` version to all manual links in CLI.
Closes #14250.
=> feat(cli): add deno version to manual links

.github/workflows/ci.yml, cli/tests/integration/run_tests.rs, cli/tests/testdata/event_listener_error_immediate_exit_worker.ts, cli/tests/testdata/event_listener_error_immediate_exit_worker.ts.out, runtime/web_worker.rs, runtime/worker.rs
Like existing https://github.com/denoland/deno/blob/2f7f41533bf3059bba55b206282080fc70a3eec8/runtime/worker.rs#L227-L230 but in other similar places.
=> fix(runtime/web_worker): Use biased select when getting module result

.github/workflows/ci.yml
=> ci: use xl windows runners

runtime/ops/fs.rs, runtime/ops/io.rs, runtime/ops/tty.rs
The option wasn't being used and adding some complexity.
=> refactor: remove unused `Option`s on `StdFileResource.fs_file`

cli/flags.rs
This is unfortunate, but provides a temporary workaround for a bug in clap.
Closes #14514
=> fix(task): accept double hyphen arg immediately following task name

cli/tests/integration/lsp_tests.rs
=> chore: fix flaky lsp_testing_api test

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> 1.21.3 (#14580)

bench_util/benches/op_baseline.rs, cli/build.rs, cli/lsp/tsc.rs, cli/ops/bench.rs, cli/tsc.rs, core/modules.rs, ext/url/lib.rs, ext/web/blob.rs, ext/web/compression.rs, ext/web/lib.rs, ext/web/message_port.rs, ext/web/timers.rs, runtime/ops/os.rs, runtime/ops/web_worker.rs, runtime/ops/worker_host.rs
=> chore(runtime): Make some ops in ext and runtime infallible.

cli/tests/integration/compat_tests.rs, cli/tests/testdata/compat/globals.ts
=> chore: update test_util/std/ submodule

cli/dts/lib.deno.shared_globals.d.ts, cli/tests/unit/performance_test.ts, ext/web/15_performance.js, tools/wpt/expectation.json
Closes #10838. Needs https://github.com/denoland/deno_std/pull/2209
=> feat(ext/web): add performance.toJSON

.github/workflows/ci.yml, cli/diagnostics.rs, cli/dts/lib.deno.ns.d.ts, cli/tests/integration/mod.rs, cli/tests/testdata/resolve_dns.ts, cli/tests/testdata/resolve_dns.ts.out, cli/tests/testdata/resolve_dns.zone.in, ext/net/ops.rs
*This is new recreated PR from #14374.*
Add `SOA` record type support for `Deno.resolveDns()`
=> feat(ext/net): support SOA records, support DNS zone file for testing

cli/dts/lib.deno.ns.d.ts, cli/tests/testdata/resolve_dns.ts.out, ext/net/ops.rs
Extend implementation to full `SOA` record type interface support for `Deno.resolveDns()`.
Required for Node compat:
- <https://nodejs.org/api/dns.html#dnsresolvesoahostname-callback>
- <https://github.com/denoland/deno_std/pull/2233>
=> feat(ext/net): support full `SOA` record interface

cli/lsp/config.rs
Ref https://github.com/denoland/vscode_deno/pull/665
=> feat(lsp): enable linting by default

cli/tests/unit/http_test.ts, ext/http/lib.rs
=> fix(ext/http): skip auto-compression if content-encoding present

ext/http/lib.rs
Minor regression/change-in-behaviour from #14552 that filtered out invalid http headers in rust vs error-ing back to JS
=> fix(ext/http): error on invalid headers

ext/web/benches/encoding.rs
=> chore: fix failing bench

cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/spawn_test.ts, runtime/ops/signal.rs, runtime/ops/spawn.rs
=>  feat: return a signal string instead number on ChildStatus 

ext/http/01_http.js
=> fix(ext/http): no response body reader when cancelling during shutdown

cli/bench/main.rs, cli/tests/unit/console_test.ts, cli/tests/unit/rename_test.ts, cli/tests/unit/spawn_test.ts
=> chore: upgrade test_util/std/ submodule

Cargo.lock, cli/Cargo.toml, core/Cargo.toml, core/inspector.rs, core/runtime.rs, runtime/Cargo.toml, serde_v8/Cargo.toml, tools/wpt/expectation.json
=> chore: upgrade rusty_v8 to 0.43.1

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
This forwards the commit of 1.22.1 to main.
=> Forward commit of 1.22.1

Cargo.toml
I eliminate a extra line of comment
=> Eliminate a extra #

Cargo.lock, cli/Cargo.toml
Fix is at https://github.com/denoland/deno_task_shell/pull/44
Closes #14806
=> fix(task): support parsing quotes in a word

cli/lsp/language_server.rs
Fixes https://github.com/denoland/deno/issues/14628
=> fix(lsp): change glob to watch json and jsonc files

.github/FUNDING.yml
=> chore: delete FUNDING.yml

.github/stale.yml
=> chore: Fix broken link in stale bot text

Cargo.lock, cli/Cargo.toml
Adds redirects, cat, xargs. Manual: https://github.com/denoland/manual/pull/335
=> feat(task): support redirects, cat, xargs

Cargo.lock, cli/tests/testdata/import_assertions/json_with_shebang.ts.out, core/Cargo.toml, serde_v8/Cargo.toml
=> upgrade: v8 10.4.132.5

ext/web/08_text_encoding.js
=> fix(ext/web): handle rid=0 in TextDecoder#decode

cli/tests/unit/fetch_test.ts, ext/fetch/26_fetch.js, tools/wpt/expectation.json
Add default `Accept-Language: *` header to fetch request.
Closes #10987.
=> fix(ext/fetch): add `accept-language` default header to fetch

cli/tests/integration/bundle_tests.rs, cli/tests/integration/install_tests.rs, cli/tests/integration/repl_tests.rs, cli/tests/integration/watcher_tests.rs, test_util/src/assertions.rs, test_util/src/lib.rs
Adds some string assertion macros so we can get more details about why a certain test fails.
=> chore(test_util): add new string assertion macros

cli/tools/repl/editor.rs
More info here https://github.com/denoland/deno/pull/14927
I did not test my changes on windows but it should theoretically work. Hopefully someone with a windows machine can test it.
=> chore(repl): fix tab handler on windows

ext/ffi/lib.rs
Minor improvement to FFI static symbols. Mostly just code cleanup.
=> chore(ext/ffi): Improve FFI static handling

Cargo.lock, core/Cargo.toml, serde_v8/Cargo.toml
=> chore: upgrade rusty_v8 to 0.44.2

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> v1.23.1 (#14952)

cli/main.rs, cli/tests/unit/process_test.ts, core/module_specifier.rs
Fixes https://github.com/denoland/deno/issues/14868
=> fix(core): don't panic on non-existent cwd

cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
Fixes https://github.com/denoland/deno/issues/14207
Co-authored-by: David Sherret <dsherret@gmail.com>
Co-authored-by: Kayla Washburn <mckayla@hey.com>
=> fix(lsp): restart TS language service when caching dependencies

cli/bench/http.rs
remove unnecessary unsafe in bench
=> fix(cli): remove unnecessary unsafe in bench

cli/tests/unit/event_test.ts, ext/web/02_event.js, tools/wpt/expectation.json
Update WPT and remove `ErrorEventInit`'s error default.
Closes #14791.
=> fix(ext/web): remove `ErrorEventInit`'s error default

cli/args/mod.rs, cli/lsp/testing/execution.rs, cli/main.rs, cli/module_loader.rs, cli/proc_state.rs, cli/tools/bench.rs, cli/tools/doc.rs, cli/tools/fmt.rs, cli/tools/lint.rs, cli/tools/task.rs, cli/tools/test.rs, cli/tools/vendor/mod.rs
From https://github.com/denoland/deno/pull/14998#discussion_r909042578
=> refactor: rename `RootConfig` to `CliOptions`

core/runtime.rs
The fix is related to the issue #15012.
=> fix(core): handle exception from Wasm termination

serde_v8/magic/v8slice.rs
Extracted from https://github.com/denoland/deno/pull/15032
=> perf(serde_v8): avoid extra is_array_buffer_view check

ext/fetch/23_request.js, ext/http/01_http.js, ext/http/lib.rs
Extracted from #15032 
No headers:
```
Running 10s test @ http://127.0.0.1:4500
Latency    95.89us   59.87us   4.87ms   97.74%
Req/Sec    49.72k     3.66k   53.86k    94.06%
50%   92.00us
75%  106.00us
90%  122.00us
99%  189.00us
999544 requests in 10.10s, 104.86MB read
Requests/sec:  98968.27
Transfer/sec:     10.38MB
```
```
Running 10s test @ http://127.0.0.1:4500
Latency    90.65us   30.14us   1.26ms   86.37%
Req/Sec    51.76k     2.64k   54.26k    99.01%
50%   87.00us
75%  102.00us
90%  116.00us
99%  161.00us
1040014 requests in 10.10s, 109.10MB read
Requests/sec: 102975.04
Transfer/sec: …
```
=> perf(ext/http): lazy load headers

cli/dts/typescript.d.ts, tools/update_typescript.md
Also update the update_typescript.md document to match the current
status.
=> feat: update to TypeScript 4.7.4

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/compat/mod.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml, tools/release/04_post_publish.ts
Should land as separate commits.
=> Forward 1.23.3 release commits back to main

ext/fetch/23_response.js
=> perf(ext/http): skip `core.isProxy` check for default ResponseInit

ext/http/01_http.js
=> fix(ext/http) nextRequest return type annotation from ResponseEvent to RequestEvent

core/runtime.rs
Closes https://github.com/denoland/deno/issues/15095
Alternative to https://github.com/denoland/deno/pull/15094
=> fix(core): deflake WASM termination test

cli/diff.rs
=> refactor: update diff.rs

.github/workflows/ci.yml
=> chore(ci): Run wpt launcher with preinstalled Deno

cli/bench/main.rs, cli/bench/metrics.rs
=> benchmarks: fix exec_time and latency benchmarks

Cargo.lock, cli/Cargo.toml, cli/tests/testdata/coverage/complex_expected.lcov, cli/tests/testdata/coverage/complex_expected.out, cli/tools/coverage/json_types.rs, cli/tools/coverage/merge.rs, cli/tools/coverage/mod.rs, cli/tools/coverage/range_tree.rs
Was mixing character indexes and byte indexes.
=> fix(coverage): better handling of multi-byte characters

cli/tests/integration/repl_tests.rs
=> chore: fix repl::pty_emoji test on linux

cli/lsp/completions.rs, cli/tests/integration/repl_tests.rs
=> fix(repl): do not panic for import completions when the import specifier is empty

cli/tests/testdata/test/meta.out, cli/tests/testdata/test/meta.ts
=> chore: fix flaky `integration::test::meta`

Cargo.lock, cli/Cargo.toml, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs
This should be good for a test spin, but it needs tests.
=> feat(lsp): provide import map remapping diags and fixes

core/bindings.rs, core/runtime.rs
Update "deno_core" to not forward rejection of top level module
if it was already handled by appropriate handlers.
Co-authored-by: Colin Ihrig <cjihrig@gmail.com>
=> fix(core): unhandled rejection in top-level scope

cli/deno_dir.rs, cli/lsp/parent_process_checker.rs, cli/windows_util.rs, ext/ffi/build.rs, ext/ffi/lib.rs, runtime/ops/process.rs, runtime/ops/runtime.rs, runtime/ops/tty.rs, runtime/permissions.rs, test_util/src/pty.rs
=> chore: fix Windows specific clippy errors

cli/tests/testdata/test/uncaught_errors.out, cli/tests/testdata/test/uncaught_errors_1.ts
Alternative to https://github.com/denoland/deno/pull/15230 as suggested in https://github.com/denoland/deno/pull/15230#discussion_r923425583
CC @dsherret @nayeemrmn
=> fix: revert changes to test output for uncaught errors

core/bindings.rs, core/runtime.rs
…5204)" (#15226)"
This reverts commit 0f6b455c964933692f4c82476692ab66eba242c2.
=> reland: "fix(core): unhandled rejection in top-level scope"

cli/schemas/config-file.v1.json
These configurations were recently added by #15079, but the schema wasn't updated.
=> chore(cli): update config file schema to include test config

Cargo.lock, core/Cargo.toml, ext/ffi/lib.rs, serde_v8/Cargo.toml
=> chore: upgrade rusty_v8 to 0.47.0

Cargo.lock, cli/Cargo.toml
https://github.com/denoland/deno_task_shell/pull/53
=> fix(task): do not overflow attempting to parse large number as redirect

Cargo.lock, cli/args/config_file.rs, cli/tests/integration/task_tests.rs
=> fix(task): resolve deno configuration file first from specified `--cwd` arg

cli/bench/main.rs, cli/dts/lib.deno.shared_globals.d.ts, cli/tests/integration/run_tests.rs, cli/tests/testdata/unhandled_rejection.js, cli/tests/testdata/unhandled_rejection.js.out, core/01_core.js, core/bindings.rs, core/ops_builtin_v8.rs, core/runtime.rs, ext/web/02_event.js, runtime/js/99_main.js, tools/wpt/expectation.json
=> Reland "feat: add "unhandledrejection" event support"

cli/cache/emit.rs, cli/emit.rs, cli/tools/coverage/mod.rs
Attempt to fix https://github.com/denoland/deno_std/actions/runs/2707182094
=> fix(coverage): do not verify emit source hash for coverage

cli/emit.rs, cli/tests/integration/test_tests.rs, cli/tests/testdata/test/deno_custom_jsx.json, cli/tests/testdata/test/hello_world.out, cli/tests/testdata/test/hello_world.ts
=> fix(cli): unset jsxFragmentFactory & jsxFactory options

cli/dts/lib.deno.window.d.ts, cli/dts/lib.deno.worker.d.ts, cli/tests/integration/run_tests.rs, cli/tests/testdata/unhandled_rejection.js.out, cli/tests/testdata/unhandled_rejection.ts, cli/tests/testdata/unhandled_rejection.ts.out
Closes https://github.com/denoland/deno/issues/15270
=> fix: proper typings for unhandledrejection event

cli/tests/integration/run_tests.rs, cli/tests/testdata/unhandled_rejection_sync_error.ts, cli/tests/testdata/unhandled_rejection_sync_error.ts.out, core/bindings.rs, core/runtime.rs, runtime/js/99_main.js
=> fix: unhandledrejection handling for sync throw in top level

core/bindings.rs, core/ops_builtin_v8.rs, core/runtime.rs
=> refactor(core): remove unneeded ops for uncaughtException

Cargo.lock, cli/Cargo.toml, cli/args/config_file.rs, cli/tools/vendor/mod.rs
It has the ability to parse only as JSON now.
=> chore: update jsonc_parser to 0.20

rust-toolchain.toml
https://github.com/rust-lang/rust/blob/1.62.1/RELEASES.md
=> chore: use Rust 1.62.1

cli/tests/integration/run_tests.rs, cli/tests/testdata/nested_error.ts, cli/tests/testdata/nested_error.ts.out, core/error.rs
Closes https://github.com/denoland/deno/issues/15335
CC @nayeemrmn
=> fix(core): BorrowMutError in nested error

cli/cache/emit.rs
Slight simplification to remove storing the `cli_version` property, which is not necessary because this information can just be in the emit hash (pointed out to me by @evmar).
=> refactor(emit/cache): move cli version into emit hash

.github/workflows/ci.yml
=> chore: cycle cache key

.github/workflows/ci.yml, core/01_core.js, core/02_error.js
=> refactor(core/error): use evaluated call sites for formatting

core/lib.deno_core.d.ts
=> core: remove heapStats type definition

cli/compat/mod.rs
=> chore(compat): update list of supported modules

ext/webgpu/src/01_webgpu.js, ext/webgpu/src/02_idl_types.js, ext/webgpu/src/command_encoder.rs, ext/webgpu/src/lib.rs
=> fix(ext/webgpu): use correct IDL key name

cli/tools/vendor/build.rs, cli/tools/vendor/import_map.rs
Fixes vendoring dotland and #15206.
Fixes #15206
=> fix(vendor): existing import map with bare specifier in remote

tools/wpt.ts
=> chore(tools): update wpt setup to new spawn api

ext/ffi/tcc.rs
Fixes https://github.com/denoland/deno/issues/15385
=> chore(ext/ffi): remove flaky test

Cargo.lock, cli/Cargo.toml, cli/graph_util.rs, cli/lsp/documents.rs, cli/tests/testdata/035_cached_only_flag.out, cli/tests/testdata/052_no_remote_flag.out, cli/tests/testdata/060_deno_doc_displays_all_overloads_in_details_view.ts.out, ops/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
=> fix: update deno_graph to fix importing config as JSON module

ext/ffi/lib.rs
Has no security implications, but should be unstable anyway.
=> fix(ext/ffi): unstable op_ffi_unsafe_callback_ref

cli/file_watcher.rs, cli/lsp/testing/execution.rs, cli/main.rs, cli/standalone.rs, cli/tools/bench.rs, cli/tools/test.rs, runtime/permissions.rs
=> fix(permissions): ignore empty values

ext/node/01_require.js
=> refactor(ext/node): remove several TODOs

Cargo.toml, ext/node/README.md
I've manually published this already to fix the publish workflow so this is for next time.
=> fix(ext/node): correct publishing for ext/node

cli/dts/lib.deno.unstable.d.ts
=> chore(cli/dts): fix typo

ext/web/timers.rs
=> perf: improve performance.now

Releases.md
Thanks for great repo!!
Ive just fixed trivial typo : )
=> fix(releases doc): Fix trivial typo

cli/tests/integration/run_tests.rs, cli/tests/testdata/report_error_end_of_program.ts, cli/tests/testdata/report_error_end_of_program.ts.out, core/runtime.rs
=> fix(core/runtime): always cancel termination in exception handling

cli/npm/mod.rs
=> chore: fix typo in mod.rs

Cargo.lock, core/Cargo.toml, core/runtime.rs, serde_v8/Cargo.toml
=> chore: upgrade rusty_v8 to v0.49.0

cli/tests/unit/flash_test.ts, ext/flash/lib.rs
Allows "Deno.serve()" API to parse non-IP hostnames (like "localhost").
=> fix(unstable): Deno.serve() can parse hostnames

ext/node/lib.rs, runtime/build.rs, runtime/permissions.rs, runtime/web_worker.rs, runtime/worker.rs
=> feat(unstable): add more permission checks for ext/node/

cli/tests/unit/flash_test.ts, ext/flash/01_http.js, ext/flash/lib.rs
=> fix(ext/flash): panic on AddrInUse

ops/README.md
=> fix: typo on ops README

cli/tests/integration/npm_tests.rs, cli/tests/testdata/npm/compare_globals/main.js, cli/tests/testdata/npm/compare_globals/main.out, cli/tests/testdata/npm/registry/@denotest/cjs-local-global-decls/1.0.0/package.json, cli/tests/testdata/npm/registry/@denotest/globals/1.0.0/index.js, cli/tests/testdata/npm/registry/@denotest/globals/1.0.0/package.json, ext/node/01_node.js
=> fix(ext/node): fix global in node env

Cargo.lock, ext/webstorage/Cargo.toml
=> chore(ext/webstorage): upgrade rusqlite to 0.28.0

cli/tools/upgrade.rs
=> fix(cli): `deno upgrade --canary` always downloaded latest version even if it was already latest

cli/dts/lib.deno.unstable.d.ts
The final markdown block does not render as code in editors right now.
=> fix(ext/flash): add missing backticks in server docs

ext/flash/lib.rs
'Syncrhonous' -> 'Synchronous'
=> Fix(ext/flash): Correct comment typo in `lib.rs`

ops/lib.rs
Inline `String` and `Option<String>` arguments in the #[op] macro bypassing serde_v8. 
Extracted from #15664
=> perf(ops): inline String args

Cargo.lock, ext/flash/Cargo.toml
=> chore: upgrade httparse to 1.8

Cargo.lock, serde_v8/Cargo.toml, serde_v8/magic/rawbytes.rs, serde_v8/magic/v8slice.rs
Fixes https://github.com/denoland/deno/issues/15566
=> fix(serde_v8): update bytes::Bytes layout assumptions

cli/args/flags.rs, cli/tests/integration/init_tests.rs, cli/tools/init/mod.rs
=> fix(init): suppress info logs when using quiet mode

.devcontainer/devcontainer.json
https://github.com/denoland/deno/pull/15344/commits/8d4ef9ba1b906981a209f70dbdf405e7948ab0ec#r933469806
=> chore: update devcontainer configuration

cli/main.rs, cli/npm/cache.rs, cli/npm/mod.rs, cli/tests/testdata/041_info_flag.out, cli/tests/testdata/041_info_flag_location.out, cli/tests/testdata/info_json.out, cli/tests/testdata/info_json_location.out
Add information about npm modules cache to "deno info"
subcommand.
=> feat(info): add information about npm modules cache

cli/node/mod.rs, ext/node/resolution.rs
Closes https://github.com/denoland/deno/issues/15775
=> fix(npm): conditional exports in npm: specifiers

cli/tests/integration/watcher_tests.rs, cli/worker.rs, core/runtime.rs
=> fix(watch): ignore unload errors on drop

cli/args/flags.rs
Modifies the --reload flag to handle invalid URLs gracefully instead of panicking.
https://github.com/denoland/deno/issues/15770
**Before:**
**After:**
1. Issue for ticket: ✅ https://github.com/denoland/deno/issues/15770
2. Tests are written: ✅
3.  Tests pass: ✅
4. Formatting Passes: ✅
5. Linting Passes: ✅
=> fix(cli): Fix panic when providing invalid urls to --reload

cli/tests/testdata/wasm_unreachable.out, core/01_core.js
https://github.com/denoland/deno/runs/8220745555?check_suite_focus=true#step:33:3176
=> fix(test): unflake wasm_unreachable test

cli/tests/unit/flash_test.ts, core/01_core.js, core/ops_builtin.rs, ext/flash/01_http.js
Fixes https://github.com/denoland/deno/issues/15781
~1-2% negative perf difference but it might just be noise.
=> fix(ext/flash): use utf8 length as Content-Length

cli/dts/lib.deno.ns.d.ts
=> fix(docs): change category for Deno.Process to "Sub Process"

cli/dts/lib.deno.shared_globals.d.ts
=> docs: dedupe DOM category

cli/module_loader.rs, cli/node/mod.rs, cli/tests/integration/npm_tests.rs, cli/tests/testdata/npm/builtin_module_module/main.js, cli/tests/testdata/npm/builtin_module_module/main.out, cli/tests/testdata/npm/registry/@denotest/builtin-module-module/1.0.0/index.js, cli/tests/testdata/npm/registry/@denotest/builtin-module-module/1.0.0/package.json
Closes https://github.com/denoland/deno/issues/15880
=> fix(npm): use shim from deno_node crate for 'module' built-in module

cli/dts/lib.deno.unstable.d.ts
Causes extreme noise on dotland built-in docs PR
=> docs: remove unstable messages

cli/dts/lib.deno.unstable.d.ts
=> docs: make unstable warnings consistent

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/deno_std.rs, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/flash/Cargo.toml, ext/http/Cargo.toml, ext/net/Cargo.toml, ext/node/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
=> chore: forward v1.25.3 release commit to main

ext/node/01_node.js, ext/node/02_require.js
Ref https://github.com/denoland/deno/issues/11224
=> refactor(ext/node): use primordials

cli/tests/unit/flash_test.ts, ext/flash/01_http.js
Closes https://github.com/denoland/deno/issues/15939
=> fix(flash): panic if response if undefined

cli/tests/integration/run_tests.rs
Temporary for #15726 in order to do a release. We should investigate this issue after though.
=> chore: temporarily ignore websocketstream test

ext/crypto/import_key.rs
=> chore(ext/crypto): fix typo in import_key.rs

cli/tests/unit/console_test.ts, ext/console/02_console.js
fix https://github.com/denoland/deno/issues/14164
=> fix(ext/console): fix error when logging a proxied Date

cli/lsp/analysis.rs, cli/progress_bar.rs, cli/tools/fmt.rs, cli/tools/lint.rs, cli/tsc.rs, cli/worker.rs, rust-toolchain.toml
https://github.com/rust-lang/rust/blob/1.64.0/RELEASES.md
=> chore: use Rust 1.64.0

Cargo.toml
This reverts commit 06c77a30f9c00a562ff2a34b96fe828e0d29a33f.
=> Revert "perf(cli): use -O3 instead of -Oz (#15952)"

cli/tests/unit/fetch_test.ts, ext/fetch/26_fetch.js
Co-authored-by: Luca Casonato <hello@lcas.dev>
=> fix(ext/fetch): blob url

runtime/js/99_main.js
=> refactor(runtime): don't use destructuring assignment in JS code

tools/wpt/expectation.json
Closes https://github.com/denoland/deno/issues/16072
Closes https://github.com/denoland/deno/issues/11740
=> chore(wpt): ignore some flaky tests

cli/tests/integration/lint_tests.rs, cli/tests/testdata/lint/expected_compact.out
=> chore: fix flaky integration::lint::compact

runtime/js/90_deno_ns.js
=> fix: move hostname from denoNsUnstable to denoNs

cli/display.rs
=> test(cli): add test cases

cli/dts/lib.deno.ns.d.ts
Ref: https://github.com/denoland/deno/blob/20c7300412bdb487fc758577d6256bbcf96efd12/runtime/ops/fs.rs#L149-L159
=> docs(fs): add default info of `OpenOptions`

cli/node/mod.rs
=> fix(node): add dns/promises and stream/consumers

Cargo.lock, core/Cargo.toml, serde_v8/Cargo.toml, serde_v8/ser.rs
=> chore: upgrade rusty_v8 to 0.52.0

tools/wpt/expectation.json
This PR enables the following test:
https://github.com/web-platform-tests/wpt/blob/master/fetch/content-type/multipart.window.js
=> test(ext/fetch): enable fetch/content-type/multipart.window WPT

cli/tests/unit/console_test.ts, ext/console/02_console.js
fix https://github.com/denoland/deno/issues/16202
=> fix sparse array inspection

cli/tools/installer.rs
Fixes #16243 
I confirmed that now it doesn't panic. See below.
```shell
$ ./target/debug/deno compile /tmp/denotest/@abc.ts
Compile file:///tmp/denotest/@abc.ts
Emit @abc
```
```shell
$ ./target/debug/deno compile /tmp/denotest/@foo/cli.ts
Compile file:///tmp/denotest/@foo/cli.ts
Emit @foo
```
=> fix(cli): skip removing the latter part if `@` appears at the beginning

ext/web/lib.deno_web.d.ts
implictly -> implicitly
assiging -> assigning
=> chore(ext/web): fix typo

cli/bench/http.rs, core/examples/http_bench_json_ops.js, core/examples/http_bench_json_ops.rs
Closes https://github.com/denoland/deno/issues/16275
=> bench: avoid port collision

Cargo.lock, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/deno_std.rs, cli/napi_sym/Cargo.toml, core/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/cache/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/flash/Cargo.toml, ext/http/Cargo.toml, ext/napi/Cargo.toml, ext/net/Cargo.toml, ext/node/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webgpu/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, ops/Cargo.toml, runtime/Cargo.toml, serde_v8/Cargo.toml
Co-authored-by: bartlomieju <bartlomieju@users.noreply.github.com>
=> chore: forward v1.26.2 to main

cli/lockfile.rs
A small cleanup that improves errors in the lockfile as well
as prepares for adding a new format of the lock file that will
allow to provide backward compatibility with existing format
(ie. "Lockfile::content" will be changed into an enum "LockfileContent"
that will have "V1" and "V2" variants).
=> refactor: better errors in lockfile and preparation for new version

ext/websocket/01_websocket.js, serde_v8/magic/string_or_buffer.rs
=> perf(serde_v8):  `serde_v8::StringOrBuffer` return JS ArrayBuffer instead of Uint8Array

Cargo.lock, core/Cargo.toml, core/bindings.rs, ext/ffi/lib.rs, ext/flash/lib.rs, ext/napi/function.rs, ops/lib.rs, serde_v8/Cargo.toml
=> chore: upgrade rusty_v8 to 0.54.0

cli/main.rs, cli/tools/upgrade.rs
=> feat(update): prompt for new version once per day

cli/lockfile.rs
=> refactor(lockfile): migrate from v1 to v2 in-memory

cli/Cargo.toml, cli/tools/upgrade.rs
fix https://github.com/denoland/deno/issues/16371
=> feat(upgrade): Check if user have write access to deno exe

cli/args/flags.rs, cli/tools/upgrade.rs
This code is complex enough that we should test it.
=> refactor: testable update checker code

cli/diagnostics.rs, cli/dts/lib.deno.ns.d.ts, cli/tests/integration/run_tests.rs, runtime/ops/tty.rs
=> feat: Stabilize Deno.stdin.setRaw()

cli/diagnostics.rs, cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/testdata/run/unstable.js, cli/tests/testdata/run/unstable.ts, cli/tests/testdata/run/unstable_disabled.out, cli/tests/testdata/run/unstable_enabled.out, cli/tests/testdata/run/unstable_enabled_js.out, runtime/js/90_deno_ns.js, runtime/ops/os.rs
=> feat: stabilize Deno.loadavg()

cli/napi/README.md
=> chore(napi): fix typo in README.md

cli/tests/unit/tls_test.ts
=> fix: listenTlsWithReuseAddr test

core/ops_builtin_v8.rs, core/runtime.rs, runtime/web_worker.rs, runtime/worker.rs
Part of https://github.com/denoland/deno/pull/16377
=> perf(core): do not drive JsInspector by default

cli/main.rs, cli/tests/integration/npm_tests.rs
=> fix(compile): show an error when using npm specifiers

core/runtime.rs
Enables [Change Array by copy proposal](https://github.com/tc39/proposal-change-array-by-copy) via a V8 flag.
=> core: enable --harmony-change-array-by-copy V8 flag

cli/diagnostics.rs, runtime/js/90_deno_ns.js
Fixes: https://github.com/denoland/deno/issues/16446
=> fix: finish stabilizing Deno.osRelease()

cli/tests/unit/webcrypto_test.ts, ext/crypto/00_crypto.js
=> fix(ext/crypto): fix HMAC jwk import "use" check

runtime/worker_bootstrap.rs
Pointed by @zbraniecki in https://github.com/denoland/deno/pull/12322#discussion_r1007416061, I made a mistake with default locale value.
=> fix: change default locale value

cli/main.rs, cli/proc_state.rs, cli/worker.rs
Ensures that "std/node" graph is analyzed only once.
=> refactor(npm): reorganize initialization of compat layer

cli/napi/js_native_api.rs, test_napi/Cargo.toml, test_napi/arraybuffer_test.js, test_napi/src/arraybuffer.rs, test_napi/src/lib.rs
=> fix(napi): fix is_detached_arraybuffer

cli/tools/upgrade.rs
=> fix(tools): show correct upgrade command for upgrading canary

cli/proc_state.rs
Just a drive-by, noticed some stale comments that haven't been removed earlier.
=> chore: remove stale comments

cli/tests/testdata/run/websocket_test.ts, ext/websocket/01_websocket.js, ext/websocket/02_websocketstream.js, ext/websocket/lib.rs
Closes https://github.com/denoland/deno/issues/16450
CC @littledivy
=> revert 9ea0ce61981aa09851c3d1e0a2b7dbd7f7a392f5

runtime/ops/os/sys_info.rs
=> chore: fix clippy warning

Cargo.lock, cli/Cargo.toml, cli/tests/testdata/doc/types_header.out, cli/tests/testdata/doc/types_hint.out, cli/tests/testdata/doc/types_ref.out
=> chore: update deno_doc

cli/lockfile.rs, cli/tests/integration/run_tests.rs
=> fix(lock): require --unstable flag to auto discover lockfile

cli/tools/upgrade.rs
fix https://github.com/denoland/deno/issues/16539
fix https://github.com/denoland/deno/issues/16537
I did not test the change, but I guessed that this is the problem by reading the code, hopefully its a correct guess.
=> fix(upgrade): Don't prompt if current version have changed

ext/node/lib.rs
=> refactor(ext/node): remove unwraps

cli/tests/unit/flash_test.ts, ext/flash/01_http.js, ext/flash/lib.rs
This PR reverts #16284 and adds a test case to prevent #16567 happening again.
closes #16567
=> fix(ext/flash): revert #16284 and add test case

cli/lockfile.rs, cli/tests/integration/run_tests.rs
=> feat(lock): don't require --unstable for auto discovery

cli/tests/testdata/jsx/deno.lock
=> test: update lockfile for tests

Cargo.lock, cli/napi/js_native_api.rs, core/Cargo.toml, core/ops_builtin_v8.rs, core/runtime.rs, ext/web/lib.rs, serde_v8/Cargo.toml, serde_v8/magic/detached_buffer.rs
=> chore: upgrade rusty_v8 to 0.55.0

cli/npm/resolution/specifier.rs
The npm specifier resolution wasn't handling data urls and this also improves the handling of modules found at a directory.
=> fix(npm): specifier resolution - handle data urls and modules at a directory

cli/tests/integration/run_tests.rs, cli/tests/testdata/jsx/deno.lock
=> test: don't use lock file in JSX tests

cli/npm/registry.rs, cli/npm/resolution/graph.rs, cli/npm/semver/mod.rs, cli/npm/semver/specifier.rs
=> fix(npm): support dist tags specified in npm package dependencies

cli/npm/resolvers/common.rs, cli/npm/resolvers/global.rs, cli/npm/resolvers/local.rs
=> fix(npm): properly handle getting `@types` package for scoped packages

cli/node/mod.rs
=> fix(npm): add suggestions to error message when can't find binary entrypoint

cli/tests/unit/command_test.ts
Ref #16700. 
I'll work on fixing this test before stabilizing the API.
=> test: disable commandChildUnref flaky test

cli/lsp/tsc.rs, cli/tests/testdata/inspector/inspector3.js, cli/tests/unit/console_test.ts, ext/console/02_console.js, ext/console/lib.deno_console.d.ts
This came up when I was testing new CDP Performance panel.
=> fix(inspector): ensure console methods provided by inspector are available

Cargo.lock, cli/Cargo.toml
=> chore: update import_map and deno_doc

.dprint.json, Cargo.lock, cli/Cargo.toml
https://github.com/dprint/dprint-plugin-markdown/pull/69
Closes #16730
=> fix(fmt/markdown): scenario where whitespace was being incorrectly stripped in inline links

Cargo.lock, cli/Cargo.toml, cli/tests/integration/task_tests.rs, cli/tests/testdata/task/deno.json, cli/tests/testdata/task/task_no_args.out, cli/tests/testdata/task/task_non_existent.out
=> fix(task): output encoding issues on windows

cli/fs_util.rs, cli/lsp/completions.rs, cli/lsp/tsc.rs
=> refactor(lsp): consolidate relative_specifier

Cargo.lock, Cargo.toml, core/inspector.rs
=> chore: update rusty_v8 to 0.56.1

cli/node/mod.rs, cli/tests/npm_tests.rs, cli/tests/testdata/npm/no_types_cjs/main.ts, cli/tests/testdata/npm/registry/@denotest/no-types-cjs/1.0.0/main.js, cli/tests/testdata/npm/registry/@denotest/no-types-cjs/1.0.0/package.json, ext/node/resolution.rs
=> fix(npm): don't resolve JS files when resolving types

cli/lsp/documents.rs, cli/tests/lsp_tests.rs, test_util/src/lsp.rs
=> fix(lsp): analyze fs dependencies of dependencies to find npm package requirements

Cargo.lock, Cargo.toml
=> chore: upgrade rusty_v8 to 0.57.0

Cargo.lock, Cargo.toml, cli/napi/js_native_api.rs, core/ops_builtin_v8.rs, ext/web/lib.rs, serde_v8/magic/detached_buffer.rs
=> chore: upgrade rusty_v8 to 0.58.0

cli/lsp/documents.rs, cli/node/mod.rs, cli/npm/resolvers/common.rs, cli/npm/resolvers/global.rs, cli/npm/resolvers/local.rs, cli/npm/resolvers/mod.rs, cli/proc_state.rs, cli/tests/npm_tests.rs, cli/tests/testdata/npm/registry/@denotest/types-exports-import-types/1.0.0/dist/main.d.ts, cli/tests/testdata/npm/registry/@denotest/types-exports-import-types/1.0.0/dist/main.mjs, cli/tests/testdata/npm/registry/@denotest/types-exports-import-types/1.0.0/package.json, cli/tests/testdata/npm/types_exports_import_types/main.out, cli/tests/testdata/npm/types_exports_import_types/main.ts, cli/tsc/mod.rs, ext/node/lib.rs, ext/node/resolution.rs
=> fix(npm): improve package.json exports support for types

cli/tools/upgrade.rs
Also, use `ProgressBar` for upgrading.
=> fix(upgrade): respect the `--quiet` flag

core/inspector.rs
=> fix(inspector): even if already woken, always schedule an interrupt

cli/tests/inspector_tests.rs
Closes https://github.com/denoland/deno/issues/13491
=> test: reenable inspector_break_on_first_line_in_test test

cli/js/40_testing.js, ext/node/02_require.js
Prerequisite for https://github.com/denoland/deno/pull/16881
=> refactor: remove references to Deno.core in bootstrap code

Cargo.lock, cli/Cargo.toml
Ref https://github.com/denoland/deno_task_shell/pull/67
=> fix(task): improve word parsing

cli/build.rs, cli/lsp/tsc.rs, cli/tests/lsp_tests.rs, cli/tests/testdata/lsp/selection_range_response.json, cli/tests/testdata/test/doc.out, cli/tests/unit/version_test.ts, cli/tsc/README.md, cli/tsc/dts/lib.dom.d.ts, cli/tsc/dts/lib.dom.iterable.d.ts, cli/tsc/dts/lib.es2015.promise.d.ts, cli/tsc/dts/lib.es2015.proxy.d.ts, cli/tsc/dts/lib.es2015.reflect.d.ts, cli/tsc/dts/lib.es2015.symbol.wellknown.d.ts, cli/tsc/dts/lib.es2019.intl.d.ts, cli/tsc/dts/lib.es2020.intl.d.ts, cli/tsc/dts/lib.es5.d.ts, cli/tsc/dts/lib.webworker.d.ts, cli/tsc/dts/lib.webworker.iterable.d.ts, cli/tsc/dts/typescript.d.ts
Updated from: https://github.com/denoland/TypeScript/pull/2
=> feat: upgrade to TypeScript 4.9.3

cli/args/flags.rs, cli/args/mod.rs, cli/main.rs, cli/proc_state.rs, cli/tests/compile_tests.rs, cli/tests/testdata/compile/standalone_import_map_config.json, cli/tools/doc.rs, cli/tools/info.rs, cli/tools/installer.rs, cli/tools/standalone.rs, cli/tsc/mod.rs, cli/worker.rs
=> fix(compile): ensure import map is used when specified in deno config file

cli/tests/repl_tests.rs
This test doesn't run on the CI.
=> chore: fix pty_complete_imports test

cli/tools/upgrade.rs
The second attempt at fixing https://github.com/denoland/deno/issues/15342. Not sure why @kidonng's first attempt got stale.
=> fix(cli/upgrade): properly cleanup after finished

cli/graph_util.rs, cli/main.rs, cli/proc_state.rs, cli/tools/bundle.rs, cli/tools/coverage/mod.rs, cli/tools/installer.rs, cli/tools/mod.rs, cli/tools/repl/mod.rs, cli/tools/run.rs, cli/tools/standalone.rs
1. Extracts out some code from main.rs
2. Inlines all the `x_command` functions in main.rs
=> refactor: cleanup main.rs

cli/tests/unit/write_file_test.ts, cli/tsc/dts/lib.deno.ns.d.ts, runtime/js/40_write_file.js, runtime/ops/fs.rs
=> feat: support `createNew` in `Deno.writeFile`

.github/workflows/ci.yml
=> ci: update release action

Cargo.lock, Cargo.toml
=> chore: upgrade rusty_v8 to 0.60.0

cli/npm/semver/mod.rs
`<= ~1.2.3` matches `1.2.4` and not `1.2.2`... ok sure.
Closes #17013
=> fix(npm): support loose node semver ranges like `>= ^x.x.x`

core/runtime.rs
PR #16376 duplicated the definition of `JsRuntime::event_loop_pending_state` into a new method `JsRuntime::event_loop_pending_state_from_isolate`, which just changes how the state and module map are borrowed, as an optimization to avoid accessing isolate slots. This change deduplicates the logic of these two methods into `EventLoopPendingState::new`, which takes borrows of the arguments, making this much more future-proof.
=> chore(core): Deduplicate `event_loop_pending_state`

.dprint.json, Cargo.lock, cli/Cargo.toml
=> fix(fmt): panic in yaml header with multi-byte characters

cli/build.rs, cli/tests/unit/version_test.ts
Was released a few days ago.
Built from https://github.com/denoland/TypeScript/pull/3
=> fix: upgrade to TS 4.9.4

cli/file_fetcher.rs
The new internal progress bar change broke progress information specifically for remote modules (npm is fine) because the drop guard here was being dropped immediately (the previous progress bars would keep showing the last item so were also technically incorrect). Spotted by Luca.
=> fix(regression): ensure progress information is shown when downloading remote modules

cli/node/mod.rs, cli/tests/npm_tests.rs, cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/client.d.ts, cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/dist/client.mjs, cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/dist/entry-c.d.ts, cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/dist/entry-c.js, cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/entry-b.d.ts, cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/package.json, cli/tests/testdata/npm/types/main.out, cli/tests/testdata/npm/types/main.ts, ext/node/errors.rs, ext/node/resolution.rs
=> fix(npm): improve exports resolution when type checking

cli/lsp/testing/collectors.rs
Fixes denoland/vscode_deno#764
=>  fix(lsp): handle template literal as first arg in test function 

cli/tests/repl_tests.rs, cli/tools/repl/mod.rs, cli/tools/repl/session.rs
Closes https://github.com/denoland/deno/issues/17080
=> fix(repl): errors shouldn't terminate repl

cli/tools/installer.rs
=> fix(install): use a hidden file for the lockfile and config

cli/lsp/testing/collectors.rs
~~Includes support for #17096~~
=> fix(lsp/testing): support not needing to declare first arg function in test declaration

im.json
`im.json` was added in https://github.com/denoland/deno/commit/435948e47057a5d8f2ffffebf74b9f84e31770f8 
=> chore: remove im.json

cli/tests/testdata/lint/expected_quiet.out, cli/tests/testdata/lint/with_config.out, cli/tests/testdata/lint/with_config_and_flags.out, cli/tests/testdata/lint/with_config_without_tags.out, cli/tools/lint.rs
=> fix(lint): column number for pretty reporting was off by 1

cli/tests/unit/fetch_test.ts
=> test(ext/fetch): fix test in release mode

cli/file_fetcher.rs, cli/http_util.rs, cli/main.rs, cli/util/draw_thread.rs, cli/util/progress_bar/mod.rs, runtime/permissions/prompter.rs
Also adds download bytes progress when downloading remote specifiers.
Closes #16860
https://user-images.githubusercontent.com/1609021/208489297-2bafafb5-1684-4a8f-93cf-d03cb38ddcb5.mp4
=> fix: hide progress bars when showing permission prompt

cli/tests/testdata/run/077_fetch_empty.ts.out, cli/tests/unit/url_test.ts, ext/url/00_url.js
=> fix: display URL in invalid URL error

cli/args/config_file.rs, cli/schemas/config-file.v1.json, cli/tests/check_tests.rs, cli/tests/testdata/check/no_error_truncation/deno.json, cli/tests/testdata/check/no_error_truncation/main.out, cli/tests/testdata/check/no_error_truncation/main.ts
> Seems reasonable to allow this.
— @dsherret 
Fixes https://github.com/denoland/deno/issues/16568
=> fix(cli): allow for specifying `noErrorTruncation` compiler option

Cargo.lock, Cargo.toml, ext/fetch/Cargo.toml, ext/http/Cargo.toml
Ref https://github.com/denoland/deno/pull/17081 https://github.com/denoland/deno/pull/17126
=> chore: release deno_fetch 0.106.0

cli/npm/resolution/specifier.rs
=> fix(npm): resolve npm specifiers when root redirected

cli/args/lockfile.rs, cli/tests/install_tests.rs
=> fix: ignore local lockfile for deno install and uninstall

cli/deno_std.rs
Fixed a performance regression for express server
=> chore: update node compat layer to std@0.170.0

cli/lsp/completions.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp_tests.rs
=> fix(lsp/format): language formatter used should be based on language id

ext/crypto/00_crypto.js, ext/web/13_message_port.js, ext/webidl/00_webidl.js
In the for-in loops, there were a few places where we forgot to check if objects owned some properties, so I added them.
=> fix(ext): Add checks for owning properties in for-in loops

cli/schemas/config-file.v1.json
=> fix: add missing verb in description

cli/npm/resolvers/local.rs
=> fix(npm): typo in local.rs

runtime/js/30_os.js, runtime/js/99_main.js, runtime/ops/os/mod.rs, runtime/ops/os/sys_info.rs
Based on work from https://github.com/denoland/deno/pull/16520
=> fix(node): Add op_node_unstable_os_uptime to allow for node interop

cli/lsp/tsc.rs, cli/tests/lsp_tests.rs
Closes https://github.com/denoland/deno/issues/13820
=> fix(lsp): completions for private variables

cli/lsp/tsc.rs, cli/tests/lsp_tests.rs
Closes https://github.com/denoland/deno/issues/17056
Closes https://github.com/denoland/deno/issues/17055
=> fix(lsp): less agressive completion triggers

runtime/permissions/prompter.rs
Closes https://github.com/denoland/deno/issues/17244
=> fix(permissions): fix italic font in permission prompt

cli/Cargo.toml, cli/README.md
As [the doc](https://docs.rs/crate/deno/latest) never gen
=> docs(cli): do not need gen doc for cli

cli/build.rs, cli/file_fetcher.rs, cli/tools/check.rs, cli/tsc/diagnostics.rs, ext/web/blob.rs, runtime/ops/web_worker/sync_fetch.rs
=> chore(cli,ext,rt): remove some unnecessary `clone` or `malloc`

.cargo/config.toml, .dprint.json, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/js/40_testing.js, cli/standalone.rs, cli/tests/repl_tests.rs, cli/tests/testdata/fmt/fmt_check_parse_error.out, cli/tests/testdata/lint/expected_json.out, cli/tests/testdata/run/error_syntax.js.out, cli/tests/testdata/run/error_syntax_empty_trailing_line.mjs.out, cli/tests/testdata/run/swc_syntax_error.ts.out, cli/tests/watcher_tests.rs, cli/tools/fmt.rs, cli/tools/repl/editor.rs, cli/tools/repl/session.rs, ext/console/02_console.js
Closes #17172
Closes #15669
Closes #8529
=> fix: upgrade deno_ast to 0.23

core/bindings.rs, runtime/js/99_main.js
Fix https://github.com/denoland/deno/issues/14658
=> fix(core): get v8 console from context extra bindings

cli/tests/unit/os_test.ts, cli/tsc/dts/lib.deno.ns.d.ts, runtime/js/30_os.js
=> feat(runtime/os): add `Deno.env.has()`

cli/tests/cert_tests.rs, cli/tests/testdata/cert/deno_land_unsafe_ssl.ts, cli/tests/testdata/cert/deno_land_unsafe_ssl.ts.out
=> test: fix flaky deno_land_unsafe_ssl test

cli/tools/test.rs
=> fix: don't unwrap in test pipe handling logic

cli/tests/testdata/lsp/completion_resolve_response.json, cli/tests/unit/write_file_test.ts, cli/tests/unit/write_text_file_test.ts, cli/tsc/dts/lib.deno.ns.d.ts, runtime/js/40_write_file.js
=> feat: allow passing a ReadableStream to Deno.writeFile/Deno.writeTextFile

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
=> chore(ci): do not clone submodule ./test_util/wpt unnecessarily

cli/tests/integration/run_tests.rs
=> tests: Disable flaky flash_shutdown test

cli/napi/env.rs
=> fix(napi): update node version to lts

cli/args/flags.rs, cli/tools/doc.rs
=> refactor: create enum for `--builtin` doc flag

core/bindings.rs, core/ops_builtin_v8.rs, core/runtime.rs
This is a requirement before supporting modules in realms.
=> refactor(core): Move `pending_promise_rejections` to `ContextState`

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/tools/bench.rs, cli/tools/test.rs, ops/fast_call.rs
This PR reduces clones across the CLI some more.
=> refactor(cli): fewer clones

cli/tsc/dts/lib.deno.unstable.d.ts, ext/net/01_net.js, ext/net/lib.deno_net.d.ts, runtime/js/99_main.js
Closes https://github.com/denoland/deno/issues/17307
=> feat: Stabilize Deno.Listener.ref/unref

cli/napi/js_native_api.rs, ext/napi/function.rs, test.js
Fixes https://github.com/denoland/deno/issues/17472
=> fix(napi): correctly handle name in napi_create_function

ext/napi/lib.rs, test_napi/src/lib.rs
Fixes https://github.com/denoland/deno/issues/17349
=> fix(napi): handle return value from initializer

cli/napi/js_native_api.rs, test_napi/mem_test.js, test_napi/src/lib.rs, test_napi/src/mem.rs
=> fix(napi): improve napi_adjust_external_memory

cli/tests/testdata/run/with_config/auto_discovery_log.out
Or should I wildcard the line numbers?
=> fix: update expected output for config auto-discovery debug log

Cargo.lock, Cargo.toml, cli/tests/testdata/run/worker_close_in_wasm_reactions.js.out, core/inspector.rs, core/runtime.rs
This reverts commit e2d75491d5fc6fbac67da89c7350c4c9ca99d8e9.
=> Revert "chore: upgrade rusty_v8 to 0.62.0 (#17200)"

cli/tools/upgrade.rs
=> fix(upgrade): don't display release information for canary

cli/args/config_file.rs, cli/args/flags.rs, cli/args/mod.rs, cli/schemas/config-file.v1.json, cli/tests/testdata/fmt/with_config/deno.jsonc, cli/tools/fmt.rs
=> feat(fmt): make semi-colon option a boolean

core/runtime.rs
=> chore(core): fix typo in runtime.rs

cli/tools/standalone.rs, cli/tools/upgrade.rs
=> fix(upgrade): ensure temp dir cleanup on failure

cli/file_fetcher.rs, cli/lsp/completions.rs, cli/lsp/config.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/performance.rs, cli/lsp/refactor.rs, cli/lsp/urls.rs
=> refactor(lsp): fewer clones

cli/graph_util.rs, cli/lsp/diagnostics.rs, cli/tests/integration/lsp_tests.rs
=> fix: ensure "fs" -> "node:fs" error/quick fix works when user has import map

ext/napi/lib.rs
Closes https://github.com/denoland/deno/issues/17457
=> fix(napi): guard threadsafe function counters behind a mutex

cli/tools/installer.rs
=> fix(install): tsconfig.json -> deno.json for config file suffix

cli/napi/js_native_api.rs, ext/napi/lib.rs, ext/node/02_require.js, test.js, test_napi/common.js, test_napi/env_test.js, test_napi/src/env.rs, test_napi/src/lib.rs
Fixes https://github.com/denoland/deno/issues/17587
=> fix(napi): return node globalThis from napi_get_global

cli/tests/integration/repl_tests.rs, cli/tools/repl/session.rs
=> fix(repl): handle @types/node not being cached in the repl

ext/webgpu/src/03_surface.js
upstream patch https://github.com/gfx-rs/wgpu/pull/3446
=> fix(webgpu): specify viewFormats in surface configuration

cli/lsp/documents.rs
=> fix(lsp): prevent crash analyzing module

cli/tests/integration/repl_tests.rs, cli/tests/testdata/npm/esm_import_cjs_default/main.out, cli/tests/testdata/npm/tarball_with_global_header/main.out, cli/tests/testdata/run/070_location.ts.out, cli/tests/testdata/run/071_location_unset.ts.out, cli/tests/testdata/run/top_level_await/loop.out, cli/tests/unit/console_test.ts, ext/console/02_console.js
fix #17197
add check for class constructor
=> fix(ext): log class for class constructor

cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/lsp/urls.rs, cli/tests/integration/lsp_tests.rs
To fix reports of breakage from #17655
=> fix: revert lsp related internal specifiers

cli/tests/testdata/run/tls_starttls.js
=> chore: update std submodule to 0.176.0

bench_util/benches/utf8.rs, core/extensions.rs, core/lib.rs, core/runtime.rs, ext/url/benches/url_ops.rs, ext/web/benches/encoding.rs, ext/web/benches/timers_ops.rs, ext/webidl/benches/dict.rs
Prerequisite for https://github.com/denoland/deno/pull/17653
=> refactor(core): change SourcePair to ExtensionFileSource

cli/tools/upgrade.rs
=> chore(cli/tools): fix typo in upgrade.rs

core/bindings.rs, core/modules.rs, core/runtime.rs
Addressing Luca concerns from https://github.com/denoland/deno/pull/17648#discussion_r1099352286
=> fix(core): don't allow to import internal code is snapshot is loaded

ext/webidl/00_webidl.js
=> refactor(ext/webidl): use `TypedArrayPrototypeGetSymbolToStringTag`

runtime/permissions/prompter.rs
=> refactor(permissions): use less space for permissions prompt

Cargo.lock, Cargo.toml, core/ops_builtin_v8.rs
=> chore: upgrade rusty_v8 to 0.63.0

core/async_cell.rs
=> Fix minor typo in AsyncRefCell comment

ext/node/polyfills/stream/web.ts
#17752
https://github.com/denoland/deno_std/pull/3204
=> feat(ext/node/polyfills/stream/web): Adding support for BYOB streams

core/runtime.rs
I missed this in https://github.com/denoland/deno/pull/17826
=> fix(core): rebuild when JS sources for snapshotting change

cli/tests/integration/node_unit_tests.rs, cli/tests/unit_node/tls_test.ts
=> test(ext/node): add tls_test

cli/tests/unit_node/tty_test.ts, cli/tests/unit_node/util_test.ts
This PR ports tty_test and util_test from std/node.
part of #17840
=> test(ext/node): add tty_test and util_test

ext/flash/01_http.js
=> fix(flash): wrong order of arguments passed to `http1Response`

cli/tests/integration/npm_tests.rs, cli/tests/testdata/.gitignore, ext/node/02_require.js
=> fix(ext/node): fix npm module resolution when --node-modules-dir specified

cli/tests/testdata/task/both/package_json_selected.out, cli/tests/testdata/task/npx/non_existent.out, cli/tests/testdata/task/npx/on_own.out, cli/tests/testdata/task/package_json/bin.out, cli/tools/task.rs
=> feat(task): add warning about package.json scripts support

cli/tests/testdata/task/both/package_json_selected.out, cli/tests/testdata/task/npx/non_existent.out, cli/tests/testdata/task/npx/on_own.out, cli/tests/testdata/task/package_json/bin.out, cli/tools/task.rs
=> feat(task): adjust warning

cli/tests/unit/flash_test.ts, cli/tsc/dts/lib.deno.unstable.d.ts, ext/flash/01_http.js
Applies suggestion from #17912
=> refactor(flash): move remoteAddr to options bag

cli/args/package_json.rs
=> fix: ignore workspace specifiers in package.json

cli/tests/integration/bench_tests.rs, cli/tests/integration/test_tests.rs, cli/tests/testdata/package_json/basic/fail_check.ts, cli/tests/testdata/package_json/basic/lib.bench.out, cli/tests/testdata/package_json/basic/lib.bench.ts, cli/tests/testdata/package_json/basic/lib.test.out, cli/tests/testdata/package_json/basic/lib.test.ts, cli/tests/testdata/package_json/basic/lib.ts, cli/tests/testdata/package_json/basic/main.info.out, cli/tests/testdata/package_json/basic/main.ts
https://github.com/denoland/deno/actions/runs/4267836955/jobs/7429836369
Closes #17946
=> chore: fix flaky package_json_basic tests

Cargo.lock, Cargo.toml
Resolves https://github.com/denoland/deno/issues/17962
=> fix(cli,ext/web): Upgrading uuid from =1.1.2 to 1.3.0

cli/tests/integration/bench_tests.rs, cli/tests/integration/cert_tests.rs, cli/tests/integration/lint_tests.rs, cli/tests/integration/mod.rs, cli/tests/integration/test_tests.rs, test_util/src/assertions.rs, test_util/src/builders.rs, test_util/src/lib.rs
Start of adding test builders to simplify integration tests.
I only updated a few test files. We can complete upgrading over time.
=> chore: test builders for integration tests

cli/tsc/dts/lib.deno.ns.d.ts
Closes https://github.com/denoland/deno/issues/17969
=> chore(docs): add note about loadavg returning 0 on windows

cli/tests/integration/bench_tests.rs, runtime/ops/process.rs, test_util/src/builders.rs
This is to allow making assertions on stdout and stderr separately.
=> chore(tests): ability to capture stdout and stderr separately

cli/tests/integration/repl_tests.rs
=> chore(tests): use temp dir in test `missing_deno_dir`

runtime/js/99_main.js
This commit moves some of the code from "99_main.js" to
be executed during the snapshot time instead of on each
worker bootstrap. These should minimally help with startup
time benchmark.
=> perf: move runtime bootstrap code to snapshot time

runtime/js/99_main.js
No need to do it on startup every time.
=> perf: move setting up Deno namespace to snapshot time

Cargo.lock, cli/Cargo.toml
=> chore: update tempfile dependency

runtime/build.rs
ref https://github.com/denoland/deno/pull/18093
=> chore(runtime): fix build.rs

runtime/build.rs
=> chore(runtime): fix build.rs (2)

.github/workflows/bench_cron.yml, .github/workflows/cargo_publish.yml, .github/workflows/version_bump.yml
I accidentally missed these in #18104
=> chore(ci): update other workflows to use cargo-toolchain.toml

ext/webgpu/surface.rs, tools/lint.js
=> build: run clippy with --all-features

cli/tests/integration/coverage_tests.rs
=> chore: fix typo in coverage_tests.rs

.github/CODE_OF_CONDUCT.md
=> Update code-of-conduct email

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, tools/verify_pr_title.js
This verifies the PR title as part of the lint step.
=> chore(ci): verify the PR title as part of linting

ext/fs/lib.rs
=> fix(ext/fs): retry if file already exists in makeTempFile

cli/args/mod.rs
Trying to fix https://github.com/denoland/deno/issues/18180
=> test: fix flaky resolve_import_map_flags_take_precedence test

ext/web/09_file.js
=> fix(ext/web): Stop using `globalThis.ReadableStream` in `Blob`

Cargo.lock, Cargo.toml, cli/Cargo.toml, lockfile/Cargo.toml, lockfile/error.rs, lockfile/lib.rs
=> refactor(lockfile): move `anyhow` to `thiserror`

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
=> chore(ci): escape quotes in "Lint PR title" step

core/runtime.rs
=> chore(core): don't print cargo directives if not creating snapshot

cli/tests/testdata/lockfile/basic/bench.nolock.out, cli/tests/testdata/lockfile/basic/main.bench.ts, cli/tests/testdata/lockfile/basic/main.test.ts, cli/tests/testdata/lockfile/basic/main.ts, cli/tests/testdata/lockfile/basic/mod.ts, cli/tests/testdata/lockfile/basic/test.nolock.out
The test output capturing is known to be flaky.
Closes #18199
=> chore(tests): fix flaky test_no_lock

cli/tests/unit/websocket_test.ts, test_util/src/lib.rs
This commit adds test for https://github.com/denoland/deno/issues/17761 which was fixed by https://github.com/denoland/deno/pull/17762. Verified that test fails on Deno 1.30.1
=> chore: add test for ws ping/pong

cli/tests/integration/repl_tests.rs, cli/tools/repl/editor.rs, cli/tools/repl/session.rs
=> fix(repl): do not panic deleting `Deno` or deleting all its properties

tools/wpt/expectation.json
This test is very flaky on CI, ignoring it for now.
=> test: ignore global-immutable-prototype.any.worker.html

core/bindings.rs, core/modules.rs, core/runtime.rs, core/snapshot_util.rs
This PR cleans up APIs related to snapshot creation and how ops are initialized.
Prerequisite for #18080
=> refactor(core): op initialization and snapshot creator

cli/tests/integration/mod.rs
=> fix(cli/integration): clippy lints

core/extensions.rs
Avoid creating an extra closure when no config needed. I eventually want to make OpStateFn fixed sized to avoid boxing it.
=> chore(core): simplify extension config codegen

cli/tests/integration/macos_tests.rs, cli/tests/integration/mod.rs
As per review comment in original PR: https://github.com/denoland/deno/pull/18244#issuecomment-1473769606
=> chore(cli/tests): move macos_shared_libraries test to macos_test.rs

tools/verify_pr_title.js
We should be able to land PRs like https://github.com/denoland/deno/pull/18272
=> chore(ci): allow 'Reland' PR title prefix

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/build.rs, cli/tsc/mod.rs
This reverts commit 0d27de943a60f5ca60e2116648719c235163361a.
=> Revert "perf: disable TSC snapshot compression (#18333)"

cli/tests/integration/macos_tests.rs
This test is flaky: https://github.com/denoland/deno/issues/18341
=> test: disable macos_shared_libraries test

Cargo.lock, Cargo.toml, cli/tests/integration/inspector_tests.rs, cli/tsc/mod.rs
=> chore: upgrade rusty_v8 to 0.66.0

cli/tests/unit/kv_test.ts, cli/tsc/dts/lib.deno.unstable.d.ts, ext/kv/01_db.ts, ext/kv/lib.rs, ext/kv/sqlite.rs, runtime/js/90_deno_ns.js
=> refactor: rename Deno.openKv() to Deno.kv()

cli/tests/unit/fetch_test.ts
https://github.com/denoland/deno/issues/18350
=> test: ignore fetchWithInvalidContentLength and fetchConnectionError on Windows

cli/tests/unit/kv_test.ts, cli/tsc/dts/lib.deno.unstable.d.ts, ext/kv/01_db.ts, ext/kv/lib.rs, ext/kv/sqlite.rs, runtime/js/90_deno_ns.js
This reverts commit 50b793c9ed866ee29e8f04b4fa24b485b01a2b74.
=> Revert "refactor: rename Deno.openKv() to Deno.kv() (#18349)"

cli/tests/unit/kv_test.ts
https://github.com/denoland/deno/issues/18363
=> chore(ext/kv): disable ci tests on darwin

cli/tests/unit_node/crypto_cipher_test.ts, ext/node/polyfills/internal/crypto/cipher.ts
This PR adds `Transform` stream (of Node.js) interface to Cipheriv/Decipheriv classes.
=> fix(ext/node): make cipher/decipher transform stream

Cargo.lock, cli/Cargo.toml, cli/tools/bench.rs, runtime/colors.rs
=> refactor: include mitata

ext/fs/lib.rs
=> chore: Improving FS Error Message for op_realpath_sync and op_realpath_async

cli/tests/unit_node/timers_test.ts
This PR ports timers_tests.ts from std/node as part of #17840
=> test(ext/node): add timers_tests.ts from std/node

tools/release/04_post_publish.ts
This change commits with conflicts that can then be resolved manually.
=> chore(release): improve merge commit back to main for patch releases

ext/fetch/23_request.js, ext/fetch/internal.d.ts, ext/http/01_http.js
Follow up to https://github.com/denoland/deno/pull/18578
We will need to do another pass cleaning up `ext/fetch/23_request.js`
=> refactor: remove remaining references to "flash" server

cli/tests/integration/node_compat_tests.rs, cli/tests/node_compat/import_map.json, cli/tests/node_compat/test.ts, ext/node/polyfills/README.md
A few drive-by cleanup while I'm working on the "crypto"
module. It makes it easier and faster to debug the failing
test case.
=> tests: cleanup "node_compat_tests"

cli/args/lockfile.rs, cli/npm/installer.rs, cli/npm/registry.rs, cli/resolver.rs, cli/tests/integration/npm_tests.rs
=> fix(npm): eagerly reload package information when version from lockfile not found locally

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Seems ok to only run these on release.
=> ci: don't run wpt tests on debug

cli/tests/unit_node/child_process_test.ts
https://pipelines.actions.githubusercontent.com/serviceHosts/017db9bc-b473-404c-99a5-60dc190743f8/_apis/pipelines/1/runs/46134/signedlogcontent/10?urlExpires=2023-04-13T15%3A34%3A53.0008682Z&urlSigningMethod=HMACV1&urlSignature=u7gsY8eZE34N05VdYKpI9mAjhMMtCaX8FgH26uWSaPg%3D
=> chore: bump child_process_test timeouts for slow CI

core/01_core.js, ext/console/02_console.js, ext/crypto/00_crypto.js, ext/fetch/21_formdata.js, ext/fetch/26_fetch.js, ext/ffi/00_ffi.js, ext/http/01_http.js, ext/web/00_infra.js, ext/web/01_mimesniff.js, ext/web/02_event.js, ext/web/02_structured_clone.js, ext/web/02_timers.js, ext/web/03_abort_signal.js, ext/web/06_streams.js, ext/web/09_file.js, ext/web/10_filereader.js, ext/web/12_location.js, ext/webidl/00_webidl.js, ext/websocket/01_websocket.js, ext/websocket/02_websocketstream.js, runtime/js/10_permissions.js, runtime/js/40_signals.js
I would like to get this change into Deno before merging https://github.com/denoland/deno_lint/pull/1146
=> fix(core): Use safe primordials wrappers

cli/tests/integration/npm_tests.rs, cli/tests/testdata/.gitignore
=> chore: remove node_modules folder being created in testdata directory

cli/graph_util.rs, cli/module_loader.rs, cli/proc_state.rs, cli/tools/check.rs
Adds a `TypeChecker` struct and pushes more shared functionality into it.
=> refactor: add `TypeChecker` struct

cli/lsp/urls.rs
=> fix(lsp): ensure language server status works on unix

ext/net/ops.rs
=> test: don't silently fail in check_sockopt

core/extensions.rs, ext/fs/interface.rs, ext/fs/lib.rs, ext/fs/ops.rs
This commit removes the dependencies on `deno_core` for the Fs trait.
This allows to move the trait into a different crate that does not
depend on core in the limit.
This adds a new `bounds` field to `deno_core::extension!` that expands to
`where` clauses on the generated code. This allows to add bounds to the
extension parameters, such as `Fs::File: Resource`.
=> chore(ext/fs): decouple fs trait from deno_core

cli/tests/testdata/workers/permissions_blob_remote.ts.out, cli/tests/testdata/workers/permissions_data_remote.ts.out
https://github.com/denoland/deno/actions/runs/4734585198/jobs/8403719901?pr=18753
=> test: fix flaky worker test

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/tests/testdata/bundle/decorators/ts_decorators.out
=> feat: upgrade deno_ast to 0.26

Cargo.lock, Cargo.toml, ext/websocket/Cargo.toml, ext/websocket/lib.rs, test_util/Cargo.toml
This should unblock https://github.com/denoland/deno/pull/18499
=> chore: remove tokio-tungstenite dependency

cli/module_loader.rs, ext/node/analyze.rs
Need to share this with the loader used in deno compile
=> refactor(cli): extract out NpmModuleLoader from CliModuleLoader

ext/websocket/01_websocket.js, ext/websocket/02_websocketstream.js, ext/websocket/lib.rs
Automatically done in the fastwebsockets crate
=> chore(ext/websocket): remove ping frame handling

ext/http/00_serve.js
2% improvement on macOS hello world.
=> perf(ext/http): avoid spread arg deopt in op_http_wait

.dprint.json, .github/workflows/ci.generate.ts, .github/workflows/ci.yml, .gitignore, ext/websocket/autobahn/autobahn_server.js, ext/websocket/autobahn/fuzzingclient.js, ext/websocket/autobahn/fuzzingclient.json
=> chore(ext/websocket): Add autobahn|testsuite fuzzingclient

cli/args/config_file.rs, cli/schemas/config-file.v1.json, cli/tests/integration/fmt_tests.rs, cli/tests/integration/test_tests.rs, cli/tests/testdata/bench/collect/deno.jsonc, cli/tests/testdata/bench/collect/deno.malformed.jsonc, cli/tests/testdata/bench/collect/deno2.jsonc, cli/tests/testdata/bench/collect_with_malformed_config.out, cli/tests/testdata/fmt/deno.malformed.jsonc, cli/tests/testdata/fmt/deno.malformed2.jsonc, cli/tests/testdata/fmt/fmt_with_deprecated_config.out, cli/tests/testdata/fmt/fmt_with_malformed_config.out, cli/tests/testdata/fmt/fmt_with_malformed_config2.out, cli/tests/testdata/fmt/with_config/deno.deprecated.jsonc, cli/tests/testdata/fmt/with_config/deno.jsonc, cli/tests/testdata/lint/Deno.compact.format.jsonc, cli/tests/testdata/lint/Deno.jsonc, cli/tests/testdata/lint/Deno.malformed.jsonc, cli/tests/testdata/lint/Deno.malformed2.jsonc, cli/tests/testdata/lint/Deno.no_tags.jsonc, cli/tests/testdata/lint/with_malformed_config.out, cli/tests/testdata/lint/with_malformed_config2.out, cli/tests/testdata/lsp/deno.lint.exclude.jsonc, cli/tests/testdata/test/collect.deprecated.out, cli/tests/testdata/test/collect/deno.deprecated.jsonc, cli/tests/testdata/test/collect/deno.jsonc, cli/tests/testdata/test/collect/deno2.jsonc, cli/tests/testdata/test/collect_with_malformed_config.out
- resolves #17529
cli flags are already fixed by #17550
=> feat(cli): flatten deno.json configuaration

cli/tests/unit/kv_test.ts, cli/tsc/dts/lib.deno.unstable.d.ts, ext/kv/01_db.ts
=> feat(kv): return ok bool from atomic commit

cli/tests/unit/fetch_test.ts, ext/fetch/22_body.js
=> fix(ext/fetch): subview Uint8Array in Req/Resp

cli/tests/unit/url_test.ts, ext/url/00_url.js
=> fix(ext/url): throw `TypeError` for empty argument

cli/tsc/diagnostics.rs, runtime/js/99_main.js, runtime/ops/runtime.rs, runtime/worker_bootstrap.rs
This is very apparent on Windows.
Before: 45.74ms (Hello world)
After: 33.92ms
Closes #18939
=> perf: lazily retrieve ppid

ext/node/polyfills/http.ts
=> fix(node/http): Request.setTimeout(0) should clear

ext/node/resolution.rs
Fixes https://github.com/denoland/deno/issues/18953
Sadly I haven't found a way to test it...
=> fix(npm): canonicalize search directory when looking for package.json

cli/tsc/dts/lib.deno.ns.d.ts
Closes https://github.com/denoland/deno/issues/18985#issuecomment-1534493623
=> docs: update Deno.Writer docstring

Cargo.lock, core/Cargo.toml, core/runtime.rs
This reverts commit 022aae9854bed6219d75eeb82fcf46652c21050d.
=> Revert "perf(core): use jemalloc for V8 array buffer allocator (#18875)"

core/runtime.rs
This commit adds a "debug build" only check that verifies on startup that
there are no duplicate ops (ie. the op names are unique).
=> refactor(core): verify there are no ops with duplicate names

Cargo.lock, Cargo.toml
=> chore: upgrade tokio to 1.28

cli/tools/vendor/build.rs, cli/tools/vendor/import_map.rs
=> fix(vendor): better handling of redirects

cli/tsc/dts/lib.deno.ns.d.ts
=> fix(dts): align `seekSync` `position` arg with `seek`

cli/tests/testdata/npm/conditional_exports/main.js, cli/tests/testdata/npm/conditional_exports/main.out, cli/tests/testdata/npm/conditional_exports/main_node_modules.out, cli/tests/testdata/npm/registry/@denotest/conditional-exports/1.0.0/esm/client/m.js, ext/node/resolution.rs
Fixes https://github.com/denoland/deno/issues/18743
=> fix(node): conditional exports edge case

cli/tests/node_compat/config.jsonc, cli/tests/node_compat/test/fixtures/run-main.js, cli/tests/node_compat/test/parallel/test-module-run-main.js, ext/node/polyfills/01_require.js
This PR adds the missing `Module.runMain()` function which is required for tools like `ts-node`. 
Fixes #19033
=> feat(node): add `Module.runMain()`

ext/fs/ops.rs
=> fix(ext/fs): add more context_path

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno/issues/19021
=> chore: upgrade rusty_v8 to 0.71.1

cli/tools/upgrade.rs
Instead of just supporting X.Y.Z, support vX.Y.Z. Otherwise we'll try to download something like vvX.Y.Z
=> fix(deno/upgrade): allow --version vX.Y.Z

cli/tsc/dts/lib.deno.unstable.d.ts
Fixes https://github.com/denoland/deno/issues/19049
=> fix(kv): kv.close() interrupts in-flight operations

ext/node/polyfill.rs, ext/node/polyfills/01_require.js
Closes https://github.com/denoland/deno/issues/19166
=> fix(node): export diagnostics_channel module

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, cli/tests/node_compat/test.ts, cli/tests/testdata/run/worker_close_in_wasm_reactions.js.out
This commit updates rusty_v8 to 0.72.0 and by extension
V8 to version 11.5.150.1.
=> chore: upgrade rusty_v8 to 0.72.0

Cargo.lock, Cargo.toml
Has fix for https://github.com/denoland/deno_npm/pull/9
=> fix(npm): better handling of optional peer dependencies

cli/tests/unit/serve_test.ts, ext/http/http_next.rs, ext/http/response_body.rs
Add Brotli streaming compression to HTTP
=> feat(ext/http): Brotli Compression

cli/tests/unit/http_test.ts, cli/tests/unit/serve_test.ts
Fixes occasional test flake due to overlapping ports
=> chore(core): Ensure that net test ports aren't used elsewhere

ext/node/polyfills/http.ts
=> fix(ext/node): ClientRequest.setTimeout(0) should remove listeners

cli/args/mod.rs, cli/cache/cache_db.rs, cli/cache/caches.rs, cli/cache/deno_dir.rs, cli/cache/mod.rs, cli/factory.rs, cli/lsp/language_server.rs, cli/standalone/mod.rs, cli/tests/integration/compile_tests.rs, cli/tools/repl/mod.rs
=> fix(compile): handle when DENO_DIR is readonly

cli/standalone/virtual_fs.rs
I'm not sure what's going on here, so this will help us debug.
For #19251
=> fix(compile): improve panic message when stripping root path fails

ext/node/polyfills/README.md, tools/node_compat/README.md
- _tools/TODO.md -> _tools/node_compat/TODO.md
- json -> jsonc
=> chore(node_compat): fix broken link and typo

cli/bench/lsp.rs, cli/lsp/client.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/lsp_custom.rs, cli/lsp/mod.rs, cli/tests/integration/lsp_tests.rs, test_util/src/lsp.rs
Merge on approval as it fixes the flaky test.
=> chore(lsp/tests): diagnostic synchronization (reland)

cli/standalone/binary.rs, cli/standalone/virtual_fs.rs
=> chore: fix flaky test_include_dir_recursive

cli/standalone/virtual_fs.rs
Not sure why these don't fail on a PR run: https://github.com/denoland/deno/actions/runs/5102317156/jobs/9171796164
=> chore: maybe fix cli/standalone/virtual_fs tests on main

ext/http/response_body.rs
We probably need to free the BrotliEncoderState once the stream has finished.
=> fix(ext/http): fix a possible memleak in Brotli

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
Closes https://github.com/denoland/deno/issues/19238
=> fix(node): http.IncomingMessageForClient.complete

cli/tests/integration/node_unit_tests.rs, cli/tests/unit_node/os_test.ts
Part of #17840
I haven't made any changes or additions to the tests themselves, just moved the tests over and updated to match.
=> test(ext/node): add os_test.ts

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts, ext/web/03_abort_signal.js, test_util/src/lib.rs
Closes https://github.com/denoland/deno/issues/18300
=> refactor: further work on node http client

ext/node/polyfills/README.md, tools/node_compat/README.md, tools/node_compat/deno.json
- `deno task setup`: setting up tests
- `deno task test`: running specific tests
=> chore(node_compat): add deno task for setting up and running tests

ext/http/http_next.rs
=> chore(ext/http): add env var to disable writev syscall

ext/kv/sqlite.rs
`rusqlite` does not support async operations; with this PR SQLite operations will run through `spawn_blocking` to ensure that the event loop does not get blocked.
There is still only a single SQLite connection. So all operations will do an async wait on the connection. In the future we can add a connection pool if needed.
=> fix(kv) run sqlite transactions via spawn_blocking

ext/http/http_next.rs
~This PR is based on work from https://github.com/denoland/deno/pull/19354 and only 2nd commit is relevant. I'll rebase this PR once the initial commit that introduced `smallvec` will be merged.~
Tackles 3rd item from https://github.com/denoland/deno/issues/19330 list.
cc @mmastrac
=> perf(ext/http): Migrate op_http_get_request_method_and_url to v8::Array

Cargo.lock, cli/Cargo.toml, ext/cache/01_cache.js, ext/console/01_console.js, ext/fetch/21_formdata.js, ext/fetch/22_body.js, ext/http/00_serve.js, ext/url/00_url.js, ext/web/06_streams.js, ext/web/09_file.js, ext/websocket/01_websocket.js
=> chore: Update deno_lint to 0.46.0

core/01_core.js, core/examples/http_bench_json_ops/http_bench_json_ops.js, core/runtime.rs, ext/fs/30_fs.js, ext/http/00_serve.js, ext/http/01_http.js, ext/node/polyfills/internal/crypto/random.ts, ext/web/02_timers.js, ext/websocket/01_websocket.js, ext/websocket/02_websocketstream.js
Startup benchmark shows no changes (within 1ms, identical system/user times).
=> refactor(core): ensureFastOps is an op-generating proxy

serde_v8/magic/v8slice.rs
I did that change recently, did spot that we're calling 
`get_backing_store()` in succession and that API call
is not cheap.
=> refactor(serde_v8): don't access backing store twice

cli/factory.rs, cli/graph_util.rs, cli/lsp/language_server.rs, cli/tests/integration/bench_tests.rs, cli/tests/integration/cache_tests.rs, cli/tests/integration/run_tests.rs, cli/tests/integration/test_tests.rs, cli/tests/testdata/run/type_directives_js_main.js.out, cli/tools/bench.rs, cli/tools/compile.rs, cli/tools/doc.rs, cli/tools/info.rs, cli/tools/test.rs, cli/tools/vendor/mod.rs, cli/tools/vendor/test.rs, cli/tsc/mod.rs
=> perf(cli): conditionally load typescript declaration files
