denoland/deno

- cli/tests/unit/README.md
Some unit test depend the `--location=http://js-unit-tests/foo/bar` to work，if run unit test without specify the `--location` some unit test will fail. 
Take `cli/tests/unit/request_test.ts` as a example:
```
% target/debug/deno test --allow-all --unstable  cli/tests/unit/request_test.ts running 6 tests from file:///Users/feng/Projects/deno/cli/tests/unit/request_test.ts
test fromInit ... ok (107ms)
test requestNonString ... ok (14ms)
test methodNonString ... ok (11ms)
test requestRelativeUrl ... FAILED (103ms)
test cloneRequestBodyStream ... ok (20ms)
test customInspectFunction ... ok (19ms)
failures:
requestRelativeUrl
TypeError: Invalid URL
at deno:core/01_core.js:106:46
at unwrapOpResult (deno:core/01_core.js:126:13)
at Object.opSync (deno:core/01_core.js:140:12)
at opUrlParse …
```
> doc(test): add --location to unit test command

- cli/flags.rs
- cli/main.rs
- cli/tools/test_runner.rs
Changes the type of the `fail_fast` flag from `Option<usize>` to `Option<NonZeroUsize>` as an optional value of zero isn't sound.
> refactor(cli/flags): use an optional non zero usize for `fail-fast`

- cli/tests/unit/http_test.ts
- ext/http/01_http.js
Closes https://github.com/denoland/deno/issues/11743
This is implemented in JavaScript, because we don't have necessary infrastructure
in Rust.
> fix(ext/http): resource leak on HttpConn.close()

- Cargo.lock
- cli/tests/unit/ffi_test.ts
- core/Cargo.toml
- ext/ffi/lib.rs
This fixes #11741. It is an alternative to #11791 that doesn't add webidl things to Deno namespace APIs.
> fix(ext/ffi): don't panic on invalid enum values

- cli/dts/lib.deno.unstable.d.ts
The types are currently inconsistent with the data presented.
```
{
category: 1,
code: 2322,
start: { line: 42, character: 2 },
end: { line: 42, character: 77 },
messageText: null,
messageChain: {
messageText: "Type 'Promise<unknown>' is not assignable to type 'Promise<X>'.",
category: 1,
code: 2322,
next: [
{
messageText: "Type 'unknown' is not assignable to type 'X'.",
category: 1,
code: 2322,
next: [Array]
}
]
},
source: null,
sourceLine: "  return (p instanceof Promise ? p as Promise<unknown> : Promise.resolve(p));",
fileName: "file:///Users/sebastienfilion/Developer/i-y.land/web-component/library/utilities.ts",
relatedInformation: null
}
```
I've run the tests and got a few errors; but I'm not sure how they relate to this issue, I would need guidance.
> Fix error in DiagnosticMessageChain interface

- ext/webgpu/01_webgpu.js
- ext/webgpu/02_idl_types.js
- ext/webgpu/binding.rs
- ext/webgpu/buffer.rs
- ext/webgpu/bundle.rs
- ext/webgpu/command_encoder.rs
- ext/webgpu/compute_pass.rs
- ext/webgpu/lib.rs
- ext/webgpu/pipeline.rs
- ext/webgpu/queue.rs
- ext/webgpu/render_pass.rs
- ext/webgpu/sampler.rs
- ext/webgpu/texture.rs
- ext/webidl/00_webidl.js
This commit reorganizes some code in ext/webgpu to clean up some cruft. WebIDL enums are now represented as Rust enums in Rust.
Also cleans up some code around `unsafe` blocks and gives them safety comments.
> refactor(webgpu): use op interface idiomatically

- cli/tests/unit/http_test.ts
- ext/http/01_http.js
> fix(ext/http): websocket upgrade header check

- core/bindings.rs
- ext/console/02_console.js
- ext/web/13_message_port.js
- ext/web/internal.d.ts
- ext/web/message_port.rs
- runtime/js/11_workers.js
- runtime/js/99_main.js
- tools/wpt/expectation.json
Adds support for transfering ArrayBuffers in structured clone, as used by
Web Workers and `self.structuredClone`.
Closes #11303
> feat: ArrayBuffer in structured clone transfer

- tools/cut_a_release.md
- tools/release/01_bump_dependency_crate_versions.ts
- tools/release/02_publish_depenency_crates.ts
- tools/release/03_bump_cli_version.ts
- tools/release/helpers/cargo.ts
- tools/release/helpers/crates_io.ts
- tools/release/helpers/deno_workspace.ts
- tools/release/helpers/helpers.ts
- tools/release/helpers/mod.ts
These scripts help automate more parts of the release process. See *cut_a_release.md* for the process change.
It would probably be good if I did the next release as well so I can fix any issues I might encounter when doing an actual release with this.
> chore: add scripts for helping with a release

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/00_crypto.js
- ext/crypto/lib.deno_crypto.d.ts
> feat(ext/crypto): support JWK export for HMAC

- tools/release/01_bump_dependency_crate_versions.ts
- tools/release/03_bump_cli_version.ts
- tools/release/helpers/cargo.ts
- tools/release/helpers/deno_workspace.ts
I was showing Ryan the release scripts and he pointed out that we need to update the lock file when bumping the versions.
I looked into using `cargo generate-lockfile` (https://doc.rust-lang.org/cargo/commands/cargo-generate-lockfile.html) but it updated too much in the lockfile. Instead the solution is to just build, which is probably something we want to do anyway as it ensures it still builds.
> chore: release scripts should update Cargo.lock file when bumping versions

- cli/tests/testdata/workers/deno_worker.ts
- runtime/js/06_util.js
- runtime/js/99_main.js
This is the worker counterpart of PR #11062.
> feat(workers): Make the `Deno` namespace configurable and unfrozen

- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/doc_only.out
- cli/tests/testdata/test/doc_only/mod.ts
- cli/tools/test.rs
Collection keeps track of what is what depending on the predicate used (`collect_specifiers_with_test_mode`).
But seems I added an else branch that sets them all to TestMode::Both in the `fetch_specifiers_with_test_mode` (this shouldn't have been here) which is a secondary pass that is supposed to reduce unknown media types (like README.md) down to `TestMode::Documentation` so that no attempts to execute are made if invoked as `deno test README.md`.
Fixes https://github.com/denoland/deno_std/pull/1171#issuecomment-908409163
> fix(cli): retain path based test mode inference

- cli/tests/integration/lsp_tests.rs
This test was failing on the CI with `'assertion failed: params.diagnostics.is_empty()'`. This change makes it so that the CI gives us a little more information about what's going on.
> chore(test): improve flaky `lsp_diagnostics_refresh_dependents` test to give more info

- cli/flags.rs
- cli/main.rs
- cli/tools/standalone.rs
Ref https://github.com/denoland/deno/pull/11776#discussion_r699701642
> refactor: factor out DenoSubcommand enum variant into structs

- cli/http_cache.rs
- cli/import_map.rs
- cli/lsp/urls.rs
- cli/text_encoding.rs
- cli/tools/fmt.rs
- core/inspector.rs
- core/lib.rs
- core/module_specifier.rs
- core/modules.rs
- core/normalize_path.rs
Lint rules: https://doc.rust-lang.org/rustdoc/lints.html?highlight=bare#bare_urls
```
$ cargo doc --open
warning: unresolved link to `deno:<filename>:<line>:<column>`
--> core/lib.rs:104:36
|
104 | /// Returns a string in form of: "[deno:<filename>:<line>:<column>]"
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ has invalid path separator
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
warning: this URL is not a hyperlink
--> core/inspector.rs:4:5
|
4 | //! https://chromedevtools.github.io/devtools-protocol/
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://chromedevtools.github.io/devtools-protocol/>`
|
= note: `#[warn(rustdoc::bare_urls)]` on by default
= note: bare URLs are not automatically …
```
> fix(doc): Fix rustdoc bare_urls warning

- .dprint.json
We were on dprint 0.13 and the plugin cache has differed for a while so whenever I would run `./tools/format.js` it would clear my plugin cache and cause a redownload. This change upgrades to the latest dprint 0.17.
> chore: upgrade third_party for dprint 0.17

- ext/net/lib.deno_net.d.ts
This PR adds a side note about the default address (0.0.0.0) of Deno.listen().
Listening this address works for all platforms, but the browsers on windows don't work with the address 0.0.0.0, and that's been causing the confusions to Windows users of several tools (ref: https://github.com/denoland/deno_std/issues/1165 https://github.com/denoland/deployctl/issues/63 https://github.com/kt3k/packup/issues/10
This side note tries to warn the tool authors about the above situation.
closes https://github.com/denoland/deno_std/issues/1165
> docs(ext/net): add note about listening 0.0.0.0

- cli/tests/unit/process_test.ts
- runtime/ops/process.rs
- runtime/ops/signal.rs
> fix: remove windows-only panic when calling `Deno.kill`

- Cargo.lock
- cli/Cargo.toml
- cli/tools/lint.rs
This commit updated "deno_lint" crate to 0.15.1 and refactors
"cli/tools/lint.rs" to create only a single vector of lint rules,
instead of creating a vector for each linted file.
<s>Blocked by #11780</s>
> refactor(lint): reuse lint rules

- cli/tests/unit/http_test.ts
- ext/http/01_http.js
> fix(ext/http): resource leak if request body is not consumed

- ext/fetch/23_request.js
- ext/fetch/26_fetch.js
- ext/fetch/lib.rs
- ext/web/09_file.js
- ext/web/blob.rs
- ext/web/internal.d.ts
- ext/web/lib.rs
- tools/wpt/expectation.json
In the spec, a URL record has an associated "blob URL entry", which for `blob:` URLs is populated during parsing to contain a reference to the `Blob` object that backs that object URL. It is this blob URL entry that the `fetch` API uses to resolve an object URL.
Therefore, since the `Request` constructor parses URL inputs, it will have an associated blob URL entry which will be used when fetching, even if the object URL has been revoked since the construction of the `Request` object. (The `Request` constructor takes the URL as a string and parses it, so the object URL must be live at the time it is called.)
This PR adds a new `blobFromObjectUrl` JS function (backed by a new `op_blob_from_object_url` op) that, if the URL is a valid object URL, returns a new `Blob` object whose parts are …
> A `Request` whose URL is a revoked blob URL should still fetch

- cli/diagnostics.rs
Erroneously removed in https://github.com/denoland/deno/pull/11909/files
> fix: bring back Deno.Signal to unstable props

- cli/tools/test.rs
Cause of #11937, which is already fixed by #11942 so this is just future proofing.
> fix(test): propagate join errors in deno test

- cli/tests/testdata/dom_exception_formatting.ts.out
- ext/web/01_dom_exception.js
```ts
throw new DOMException("foo", "SyntaxError");
```
`v1.13.2`:
```
error: Uncaught
```
`main` (as of #11834)
```
error: Uncaught SyntaxError: foo
```
This PR:
```
error: Uncaught SyntaxError: foo
throw new DOMException("foo", "SyntaxError");
^
at file:///home/nayeem/projects/deno/temp.js:1:7
```
> fix(ext/web): Preserve stack traces for DOMExceptions

- runtime/js/99_main.js
refactor(runtime): Use `util.nonEnumerable` to define `console`
A comment in `runtime.js` reads that `console` seems to be "the only one that should be writable and non-enumerable", which explains why it is declared with `util.writable` but then has its property descriptor's `enumerable` key changed to false.
But it is not in fact true that `console` is the only global property for which this holds, and it wasn't even when this behavior was introduced in denoland#9013. All WebIDL interfaces are also writable and non-enumerable – the only difference here being that `console` is a namespace rather than an interface.
Since WebIDL interfaces are defined with `util.nonEnumerable`, and `console` uses the same descriptor keys, this PR changes the definition of `console` to use …
> refactor(runtime): Use `util.nonEnumerable` to define `console`

- cli/lsp/analysis.rs
Since we re-used the AST in deno lint there have been some reports on canary of false positives with the "cannot redeclare block-scoped variable" rule (https://discord.com/channels/684898665143206084/775366479143108608/886145809521967124).
This is because when deno lint parses an AST it, it does some post processing on the file:
https://github.com/denoland/deno_lint/blob/7825cb95115bfdffc62c076c8f458b3424f7190c/src/ast_parser.rs#L116
I really dislike this post processing and we should look into hopefully not needing to do it somehow then turning this back on.
> chore(lsp): temporarily reparse AST for linting

- cli/file_fetcher.rs
- cli/lsp/language_server.rs
- cli/standalone.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/initialize_params_import_map.json
The second commit contains the actual implementation. Even though this PR adds support for data URLs, we can't support relative paths in data URLs as we won't have a valid base path. For example, the following won't work:
```json
{
"deno.importMap": "data:application/json;utf8,{\"imports\": { \"a\": \"./a.ts\" }}",
}
```
Closes #11392
> fix(lsp): support data urls in `deno.importMap` option

- core/bindings.rs
- core/lib.deno_core.d.ts
- core/ops_builtin.rs
- ext/fetch/26_fetch.js
Async WebAssembly compilation was implemented in #11200 by adding two bindings: `set_wasm_streaming_callback`, which registered a callback to be called whenever a streaming wasm compilation was started, and `wasm_streaming_feed`, which let the JS callback modify the state of the v8 wasm compiler.
`set_wasm_streaming_callback` cannot currently be implemented as anything other than a binding, but `wasm_streaming_feed` does not really need to use anything specific to bindings, and could indeed be implemented as one or more ops. This PR does that, resulting in a simplification of the relevant code.
There are three operations on the state of the v8 wasm compiler that `wasm_streaming_feed` allowed: feeding new bytes into the compiler, letting it know that there are no more bytes coming from the …
> refactor(core): Turn the `wasm_streaming_feed` binding into ops

- .github/workflows/ci.yml
- Cargo.lock
- core/Cargo.toml
> chore: update rusty_v8

- cli/flags.rs
- cli/main.rs
- cli/tools/fmt.rs
Follow up to https://github.com/denoland/deno/pull/11944 as requested by @lucacasonato
> feat: add option flags to 'deno fmt'

- cli/config_file.rs
- cli/flags.rs
This commit changes parsing of configuration file provided with
"--config" strict, ie. if the file contains unknown fields it will
refuse to parse.
> docs: Update --config flag help text

- cli/lsp/analysis.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/code_action_ignore_lint_response.json
- cli/tests/testdata/lsp/code_action_update_ignore_lint_params.json
- cli/tests/testdata/lsp/code_action_update_ignore_lint_response.json
- ts
https://user-images.githubusercontent.com/29819102/133035885-3109a104-f93d-4271-8030-2bdbda39892c.mp4
Closes #11833
> feat(lsp): ignore specific lint for entire file

- Cargo.lock
- cli/Cargo.toml
- cli/tests/integration/lsp_tests.rs
Improves lsp developer experience by 10x.
Before:
After:
> chore(lsp): use pretty_assertions in e2e tests

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
> fix(lsp): align filter text to vscode logic

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/00_crypto.js
> fix(ext/crypto): don't use core.decode for encoding jwk keys

- cli/bench/deno_common.js
- runtime/js/12_io.js
- runtime/js/40_read_file.js
This avoids allocating N buffers when reading entire files and copying when concatenating them.
```
❯ deno run -A ./cli/bench/deno_common.js
read_128k_sync:      	n = 50000, dt = 1.941s, r = 25760/s, t = 38820ns/op
read_128k:           	n = 50000, dt = 9.613s, r = 5201/s, t = 192259ns/op
❯ ./target/release/deno run -A ./cli/bench/deno_common.js
read_128k_sync:      	n = 50000, dt = 1.746s, r = 28637/s, t = 34920ns/op
read_128k:           	n = 50000, dt = 8.865s, r = 5640/s, t = 177300ns/op
```
- The improvements to `read_128k_sync` are somewhat reduced here by the extra cwd lookups caused by the `stat`, so https://github.com/denoland/deno/pull/12056 will work hand in hand with this change to improve file reads
- This operates under the assumption that files won't change (truncated or …
> perf(runtime/fs): optimize readFile by using a single large buffer

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/error_for_await.ts
- cli/tests/testdata/error_for_await.ts.out
- cli/tsc/99_main_compiler.js
> fix(cli): don't ignore diagnostics about for await

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- ext/fetch/Cargo.toml
- ext/net/Cargo.toml
- ext/url/Cargo.toml
- ext/web/Cargo.toml
- runtime/Cargo.toml
- test_util/Cargo.toml
Potential removal of some unused deps?
> Removal of unused deps

- cli/tests/unit/flock_test.ts
Removes any timing from these tests. Instead just checks that the file can be read or written based on the type of lock.
Closes #12094
> chore(tests): maybe fix flaky flock tests

- cli/main.rs
- cli/standalone.rs
- cli/tools/test.rs
- core/modules.rs
- core/runtime.rs
- runtime/examples/hello_runtime.rs
- runtime/web_worker.rs
- runtime/worker.rs
Fixes https://github.com/denoland/deno/issues/10803
> fix(core): prevent multiple main module loading

- cli/tools/test.rs
As of https://github.com/denoland/deno/pull/12128 I no longer need to generate a module to side-load test modules so this removes the module generation entirely.
Closes https://github.com/denoland/deno/issues/11872
> refactor(cli): don't generate a module for side loading tests

- cli/dts/lib.deno.ns.d.ts
- cli/dts/lib.deno.unstable.d.ts
`Deno.lock` and `Deno.unlock`(and sync variants) are marked as unstable, but are in the stable type definitions.
This moves them into the unstable type definitions.
> fix(cli): move Deno.flock and Deno.funlock to unstable types

- cli/schemas/config-file.v1.json
Changed it from `"deno.window"` to `["deno.window"]`
> Fix default value of "lib"

- cli/bench/deno_common.js
Indirectly measures:
- url parsing
- abort signal no-ops
- webidl & other overhead
```
request_new:         	n = 500000, dt = 1.296s, r = 385802/s, t = 2592ns/op
```
> bench(deno_common): track new Request()

- ext/web/03_abort_signal.js
- Use regular class constructor and symbol "private" attributes
- Lazy init Set of follower signals
Some benchmark data on class init:
```
class_member_private:    n = 1000000, dt = 0.076s, r = 13157895/s, t = 75ns/op
class_member:            n = 1000000, dt = 0.091s, r = 10989011/s, t = 91ns/op
class_constructor:       n = 1000000, dt = 0.008s, r = 125000000/s, t = 8ns/op
class_symbol_x:          n = 1000000, dt = 0.006s, r = 166666667/s, t = 6ns/op
class_symbol_anon:       n = 1000000, dt = 0.007s, r = 142857143/s, t = 7ns/op
```
> perf(web): optimize AbortController

- ext/web/02_event.js
and all its subclasses including `AbortSignal` ...
Instead of storing associated data in a global WeakMap we store them as private attributes (via a Symbol) on the object instances
> perf(ext/web): optimize EventTarget

- ext/fetch/26_fetch.js
Since those inputs are passed to `new Request(...)` which applies webidl converters
> cleanup(ext/fetch): drop redundant webidl converters in fetch()

- ext/net/ops_tls.rs
- ext/websocket/lib.rs
Default to None if UnsafelyIgnoreCertificateErrors is not present in the
OpState.
Embedders may not have a need for restricting outgoing TLS connections
and having them hunt through the source code for the magic incantation
that makes the borrow panics go away, is less user friendly.
<hr>
It'd be nice if this pattern was adopted more broadly (hint, hint.)
> chore(ext/net): improve embedder friendliness

- .github/workflows/ci.yml
- Cargo.toml
This experiment evaluates reducing total CI time, by using debug mac/windows build on PR CI.
CI checks in aggregate are as slow as the slowest check, which is windows (& macOS 2nd) in our case.
- [macOS](https://github.com/denoland/deno/pull/11884/checks?check_run_id=3472067920): ~31mn (~11mn build, ~18mn test)
- [windows](https://github.com/denoland/deno/pull/11884/checks?check_run_id=3472067939): ~23mn (~14mn build, ~7mn test)
Currently total PR CI time is ~40mn (since it has to wait for the slowest job, windows), currently:
- macOS: ~30mn
- windows: ~40mn
- The data measured here is **without cargo cache** (whereas release builds currently do use cargo cache)
- CI time is variable, depending mainly on what needs to be rebuilt, changes deeper in the dependency tree naturally require …
> ci: experiment mac & windows debug builds

- .github/workflows/ci.yml
Quickfix follow up to #11884, will cleanup and refactor CI jobs later to better separate PR & Main jobs
> quickfix(ci): only run "Build product size info" on main/tag

- .github/workflows/ci.yml
Follow up to #11884 that enables cache to further reduce mac/win fastci
> ci: enable cache for fastci

- ext/fetch/23_request.js
Since URL parsing will effectively normalize it, this is essentially another redundant webidl conversion
Assumes #12167
> perf(ext/fetch): skip USVString webidl conv on string constructor

- runtime/permissions.rs
Currently `Deno.permissions.revoke()` no-ops if you try to revoke a permission which is weaker than one that was _explicitly granted_ on the CLI, since it would still be implied. This makes it stronger, now purging all permission entries required to ensure that the passed permission descriptor no longer returns granted.
Fixes #12153.
Also makes runtime-requested permissions, when granted or already granted, count as _explicitly granted_ entries. A clean side-effect of this is allowing a hack for more granular revokes.
```ts
// deno run --allow-read=foo temp.ts
// This request doesn't actually prompt because it's already transitively
// granted. But `--allow-read=foo/bar is now "explicitly granted".
console.log(await Deno.permissions.request({ name: "read", path: "foo/bar" })); // granted …
```
> fix(cli/permissions): ensure revoked permissions are no longer granted

- cli/lsp/sources.rs
- cli/main.rs
- cli/module_loader.rs
- cli/ops/errors.rs
- cli/ops/runtime_compiler.rs
- cli/proc_state.rs
- cli/program_state.rs
- cli/source_maps.rs
- cli/specifier_handler.rs
- cli/standalone.rs
- cli/tools/coverage.rs
- cli/tools/doc.rs
- cli/tools/repl.rs
- cli/tools/test.rs
And move the Arc inside the struct.
> refactor: Rename ProgramState to ProcState

- cli/module_loader.rs
- cli/standalone.rs
- core/modules.rs
- core/runtime.rs
> refactor: Remove op_state parameter

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/worker_close_nested.js
- cli/tests/testdata/worker_close_nested.js.out
- cli/tests/testdata/workers/close_nested_child.js
- cli/tests/testdata/workers/close_nested_parent.js
Before #12156, closing a worker which had children would cause a panic (https://github.com/denoland/deno/issues/11342#issuecomment-918327693). After that PR, closing a worker will also close any child workers.
> chore(workers): Test that closing a worker closes any child workers

- ext/http/lib.rs
Check for expected headers more rigorously and, notably, check that
it's a HTTP/1.1 GET request. Hyper panics if you try to upgrade HTTP/2
connections.
This mirrors what Deno Deploy and the tungstenite crate do, with the
caveat that tungstenite supports multiple Connection header tokens
(e.g. "Connection: upgrade, foo") whereas Deploy does not.
I'm reasonably sure no reasonable client sends multiple tokens when it
also sends "Upgrade: websocket" so I opted to leave that out.
The presence of "Sec-Websocket-Version: 13" is now also enforced.
I don't expect that to break anything: conforming clients already send
it and tungstenite can't talk to older clients anyway.
The new code is more efficient due to heap-allocating less.
> fix(ext/http): fortify "is websocket?" check

- cli/tests/unit/http_test.ts
- ext/http/lib.rs
Our oneshot receiver in `HyperService::call` would unwrap and panic, the `.await` on the oneshot receiver errors when the sender is dropped.
The sender is dropped in `op_http_response` because:
1. We take `ResponseSenderResource` (which owns the sender)
2. Then we hit an early exit in `op_http_response` due to the conn being closed
3. Then the taken sender gets dropped in this early exit before any response is sent over the channel
Fallbacking to returning a dummy response to hyper seems to be a fine quickfix
> fix(http): panic when responding to a closed conn

- ext/web/10_filereader.js
Previously FileReader error messages misidentified the failing function.
> fix(ext/web): FileReader error messages

- cli/bench/main.rs
- cli/tests/testdata/response_string_perf.js
- ext/fetch/22_body.js
- ext/fetch/23_request.js
- ext/fetch/23_response.js
Fixes performance issue https://github.com/denoland/deno/issues/12090
* Replaces conversion to `USVString` by `DOMString` at the `BodyInit` WebIDL conversion.
* Adds benchmark `response_string` which produced the following results before and after the change:
* using `USVString`:
```
Benchmark #13: /home/luismalheiro/projects/deno_pr/target/release/deno run cli/tests/testdata/response_string_perf.js 
Time (mean ± σ):     432.9 ms ±  26.8 ms    [User: 308.8 ms, System: 192.8 ms]
Range (min … max):   409.5 ms … 485.4 ms    10 runs
```
* using `DOMString`:
```
Benchmark #13: /home/luismalheiro/projects/deno_pr/target/release/deno run cli/tests/testdata/response_string_perf.js 
Time (mean ± σ):     175.8 ms ±  17.6 ms    [User: 168.6 ms, System: 73.9 ms]
Range (min … max):   147.3 ms … 211.6 …
```
> perf(ext/fetch): Use the WebIDL conversion to DOMString rather than USVString for Response constructor

- ext/fetch/20_headers.js
Use a single regex to check for `\0`, `\n`, `\r` instead of 3 `String.includes(...)` calls
> perf(fetch/headers): optimize appendHeader

- ext/fetch/22_body.js
Avoid initializers due to overhead
> perf(fetch): optimize InnerBody constructor

- ext/webidl/00_webidl.js
This replaces a looped `.codePointAt(i)` ASCII check with a regex, which is ~3x faster. This ascii check is the dominant cost in the webidl `ByteString` converter which is used for headers etc... in http hot path
Bench script: https://gist.github.com/AaronO/676dee49b4fdd4d6e0ad0efbff45b75c
```
❯ deno run https://gist.githubusercontent.com/AaronO/676dee49b4fdd4d6e0ad0efbff45b75c/raw/f6a9c14da88c68ac947dcd369a4b4939da15bbaa/deno_webidl_bstring_bench.js
ascii:               	n = 1000000, dt = 0.038s, r = 26315789/s, t = 37ns/op
ascii_inline:        	n = 1000000, dt = 0.049s, r = 20408163/s, t = 49ns/op
codepoint_loop:      	n = 1000000, dt = 0.124s, r = 8064516/s, t = 124ns/op
ascii:               	n = 1000000, dt = 0.048s, r = 20833333/s, t = 48ns/op
ascii_inline:        	n = 1000000, dt = …
```
> perf(webidl/ByteString): 3x faster ASCII check

- ext/web/02_event.js
Assign in constructor instead of using class initializers which are currently ~10x slower
Note:`[_attributes]` is assigned further down
These initializers currently take up about ~60% of the `Event` class constructor (and thus impacts all of its subclasses such as `FetchEvent` ...)
> perf(web): optimize Event constructor

- ext/fetch/23_response.js
Not useful to have the defaults externally defined when they're only used in `newInnerResponse()`. Also match order in `newInnerResponse()` and `cloneInnerResponse`
> refactor(fetch/response): inline defaultInnerResponse

- ext/fetch/23_request.js
- ext/http/01_http.js
Avoid "blob:" prefix check on requests built in the http module since those can never be blob objects
Reduces cost of `newInnerRequest()` from 20ms to 0.1ms in my profiled run on ~2.5M reqs
Follow up to #12241 
- Also removed default args on `newInnerRequest` since they weren't helpful given we only have 2 call sites that supply all args (and it's not user facing)
> perf(fetch): optimize newInnerRequest blob url check

- runtime/js/99_main.js
This stabilizes the URLPattern API introduced in Deno 1.14.
- Yes: Chrome 95, which is currently in beta. I got confirmation from @wanderview that it is proceeding to stable as planned.
- Yes: wicg.github.io/urlpattern
- Yes: https://github.com/web-platform-tests/wpt/tree/master/urlpattern
Also has extensive docs on MDN now: https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API.
> feat: stabilize URLPattern API

- cli/bench/deno_http_native_headers.js
The use of headers reduces throughput by 30%, we want to reduce this gap since most real world apps will provide custom headers. So I added this benchmark so we can track that delta and measure improvements shipped over the next few days
- `deno@1.14.0`:
- `deno_http_native.js`: 107k rps
- `deno_http_native_headers.js`: 74k rps
- `deno@1.14.2`:
- `deno_http_native.js`: 117k rps
- `deno_http_native_headers.js`: 82k rps
---
In addition to adding headers we also don't pre-encode the body, which likely better reflects typical use.
> bench(cli): add deno_http_native_headers.js

- ext/webidl/00_webidl.js
Avoids needlessly creating String objects, can reduce GC-pressure.
On a micro-bench, avoiding this unwrap (via typeof if or switch) is ~4x faster:
```
DOMString_main:      	n = 10000000, dt = 0.235s, r = 42553191/s, t = 23ns/op
DOMString_typeof:    	n = 10000000, dt = 0.055s, r = 181818182/s, t = 5ns/op
DOMString_typeof2:   	n = 10000000, dt = 0.056s, r = 178571429/s, t = 5ns/op
DOMString_switch:    	n = 10000000, dt = 0.055s, r = 181818182/s, t = 5ns/op
```
> perf(webidl/DOMString): don't wrap string primitives

- cli/dts/lib.deno.unstable.d.ts
- cli/file_fetcher.rs
- cli/http_util.rs
- cli/tests/unit/README.md
- cli/tests/unit/fetch_test.ts
- cli/tests/unit/http_test.ts
- cli/tests/unit/tls_test.ts
- ext/fetch/22_http_client.js
- ext/fetch/lib.rs
- ext/net/02_tls.js
- ext/net/lib.deno_net.d.ts
- ext/net/ops_tls.rs
- ext/tls/lib.rs
- ext/websocket/lib.rs
- test_util/src/lib.rs
This adds support for using in memory CA certificates for
`Deno.startTLS`, `Deno.connectTLS` and `Deno.createHttpClient`.
`certFile` is deprecated in `startTls` and `connectTls`, and removed
from `Deno.createHttpClient`.
Closes #11608.
> feat(tls): custom in memory CA certificates

- cli/tests/integration/repl_tests.rs
- cli/tools/repl.rs
This PR fixes the crash of repl described in #9916
Repl internally uses `globalThis` for getting `closed` variable. This PR uses `this` (in global scope) instead of `globalThis` to reference the global variable.
closes #9916
> fix(repl): avoid panic when assigned to globalThis

- cli/flags.rs
- cli/main.rs
- cli/tools/installer.rs
Fix https://github.com/denoland/deno/issues/3139
> feat(cli/uninstall): Add uninstall command

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/worker_close_in_wasm_reactions.js
- cli/tests/testdata/worker_close_in_wasm_reactions.js.out
- cli/tests/testdata/workers/close_in_wasm_reactions.js
- core/runtime.rs
> fix: Don't panic when a worker is closed in the reactions to a wasm operation.

- ext/webidl/00_webidl.js
On a benchmark constructing `Response`s with headers this shaves off 25%:
```
Before:
resp_w_h:            	n = 1000000, dt = 2.284s, r = 437828/s, t = 2283ns/op
After:
resp_w_h:            	n = 1000000, dt = 1.725s, r = 579710/s, t = 1725ns/op
```
> perf(webidl): optimize createDictionaryConverter()

- cli/tests/unit/flock_test.ts
Hopefully fixes #12094 for good. Fix is adding the `waitBothEnteredLock: true` for this scenario.
> chore: ensure first process in shared flock test does not enter and exit lock before second enters

- cli/tests/testdata/workers/env_read_check_worker.js
- cli/tests/testdata/workers/test.ts
- cli/tests/unit/worker_permissions_test.ts
- cli/tests/unit/worker_types.ts
- runtime/js/11_workers.js
- runtime/ops/worker_host.rs
- runtime/permissions.rs
Fixes a Windows only clippy lint, but also aligns the worker environment permissions with accepting an array.
> fix: worker environment permissions should accept an array

- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/aggregate_error.out
- cli/tests/testdata/test/aggregate_error.ts
- runtime/js/40_testing.js
Prints out the actual errors contained in aggregate errors rather than just stating that an aggregate error occured.
Before:
```
test aggregate ... FAILED (11ms)
failures:
aggregate
AggregateError
at file:///home/caspervonb/deno/cli/tests/testdata/test/aggregate_error.ts:5:9
at asyncOpSanitizer (deno:runtime/js/40_testing.js:35:15)
at resourceSanitizer (deno:runtime/js/40_testing.js:72:13)
at exitSanitizer (deno:runtime/js/40_testing.js:99:15)
at runTest (deno:runtime/js/40_testing.js:215:13)
at Object.runTests (deno:runtime/js/40_testing.js:283:28)
at file:///home/caspervonb/deno/a4959e45-e14a-4088-9481-1767fec6e3e4$deno$test.js:4:27
failures:
aggregate
```
After:
```
test aggregate ... FAILED (23ms)
failures:
aggregate
Error: Error 1
at …
```
> fix(runtime/testing): format aggregate errors

- tools/bench/README.md
- tools/bench/mod.js
- tools/bench/rebench.js
- tools/bench/rebootstrap.js
Enable deno devs to bench/profile/test JS code changes without doing a full --release rebuild.
Incremental release builds take ~4mn on M1s, often more on other machines ...
This allows devs to make benches like the following:
```js
import { benchSync, rebootstrap } from "./tools/bench/mod.js";
const bootstrap = rebootstrap([
"webidl",
"console",
"url",
"web",
"fetch",
]);
benchSync("resp_w_h", 1e6, () =>
new bootstrap.fetch.Response("yolo", {
status: 200,
headers: {
server: "deno",
"content-type": "text/plain",
},
})
);
```
> tools(bench): rebootstrap

- ext/web/00_infra.js
To use `String.prototype.toLowerCase()`, this is safe since all callers convert the values to webidl ByteString so we know these inputs are already ASCII
We don't convert it in `getHeader()` but that shouldn't be an issue since those lookups will miss
Shaves off ~20% of total time spent constructing Responses with headers, ~1700ns/iter => ~1400ns/iter
> perf(web): optimize byteLowerCase()

- cli/tests/integration/worker_tests.rs
- cli/tests/testdata/worker_drop_handle_race.js.out
- cli/tests/testdata/workers/async_error.ts
- cli/tests/testdata/workers/message_handler_error.ts
- cli/tests/testdata/workers/nonexistent_worker.out
- cli/tests/testdata/workers/permissions_blob_local.ts.out
- cli/tests/testdata/workers/permissions_blob_remote.ts.out
- cli/tests/testdata/workers/permissions_data_local.ts.out
- cli/tests/testdata/workers/permissions_data_remote.ts.out
- cli/tests/testdata/workers/permissions_dynamic_remote.ts.out
- cli/tests/testdata/workers/permissions_remote_remote.ts.out
- cli/tests/testdata/workers/test.ts
- cli/tests/testdata/workers/test_worker.js
- cli/tests/testdata/workers/worker_async_error.ts
- cli/tests/testdata/workers/worker_async_error.ts.out
- cli/tests/testdata/workers/worker_error.ts.out
- cli/tests/testdata/workers/worker_message_handler_error.ts
- cli/tests/testdata/workers/worker_message_handler_error.ts.out
- cli/tests/testdata/workers/worker_nested_error.ts.out
- runtime/js/11_workers.js
- runtime/js/99_main.js
- runtime/ops/web_worker.rs
- runtime/web_worker.rs
> fix(runtime/js/workers): throw errors instead of using an op

- ext/fetch/20_headers.js
Reduces self-time by ~70x (~70ms => ~1ms on 1M iters)
for...in filtered by hasOwnProperty yields the same set of keys as Object.keys()
> perf(fetch): optimize fillHeaders() key iteration

- core/bindings.rs
- core/runtime.rs
Another binding ... but it's required for https://github.com/denoland/deno/pull/12286 and could be useful elsewhere
`core.getProxyDetails(...)` isn't fast enough for fast-path checks:
```
No fast path:
resp_w_bh:               n = 1000000, dt = 1.295s, r = 772201/s, t = 1294ns/op
Fast path with getProxyDetails check:
resp_w_bh:               n = 1000000, dt = 1.321s, r = 757002/s, t = 1321ns/op
Fast path with isProxy check:
resp_w_bh:               n = 1000000, dt = 1.146s, r = 872600/s, t = 1146ns/op
Forced fast path:
resp_w_bh:               n = 1000000, dt = 1.112s, r = 899281/s, t = 1112ns/op
```
> feat(core): implement Deno.core.isProxy()

- cli/tests/unit/net_test.ts
- ext/net/ops.rs
Fixes #11412
The test detects the runtime whether running into a panic by `asset` after `Deno.listen`, would like to see a better way to detect the panic, feel free to suggest.
> fix(ext/net): should not panic when listening to unix abstract address

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/lib.deno_crypto.d.ts
Key generation support was added in #11869
> fix(ext/crypto): missing Aes key typings

- ext/web/01_dom_exception.js
- tools/wpt/expectation.json
[As per WebIDL](https://heycam.github.io/webidl/#es-DOMException-specialness), if `Error` objects have a `stack` property, so should `DOMException` instances.
> feat(web): Implement `DOMException`'s `stack` property.

- core/01_core.js
- core/runtime.rs
Instead of the wrapper dispatch() func, also now forbids passing opIds to opSync()/opAsync() callers must always pass names.
This is admittedly a micro-optimization, it shaves off ~10ns/iter for async ops and ~4ns/iter for sync ops (though on the scale of sync ops that's ~7%), it's half micro-optimization and half cleanup:
```
Before:
bench async:     393,383 ns/iter (+/- 6,025)
bench nop:      50,881 ns/iter (+/- 1,073)
bench sync:      57,920 ns/iter (+/- 669)
After:
bench async:     380,437 ns/iter (+/- 8,691)
bench nop:      46,860 ns/iter (+/- 1,470)
bench sync:      54,840 ns/iter (+/- 1,499)
```
> perf(core): use opcall() directly

- core/runtime.rs
Decouple JsRuntime::sync_ops_cache() from the availability of the Deno.* namespace in the global scope
This avoids crashes when calling sync_ops_cache() on a bootstrapped WebWorker who has dropped its Deno.* namespace
It's also just cleaner and more robust ...
- Observed when refactoring Worker setup in https://github.com/denoland/deno/pull/12299
> fix(core/runtime): sync_ops_cache if nuked Deno ns

- core/01_core.js
- core/bindings.rs
- core/runtime.rs
Cleaner separation of concerns and easier to reason about, simplifies some upcoming changes (e.g: rust-side promise ring)
Also somewhat improves robustness and prevents users from calling async ops with `core.opSync()` and vice-versa
> refactor(core): split opcall into sync/async

- ext/webidl/00_webidl.js
Cuts self-time by ~6x, 172ns/iter => 22ns/iter benched on 1M Response builds / HeadersInit calls
This should be functionally identical to the old code since:
1. `for...in` loops on objects iterate over all enumberable string keys of an object (including inherited)
2. Then we filter out inherited keys with `.hasOwnProperty(...)`
**Note:** WebIDL / WPT is coupled to a subpar implementation so our hands are tied, unless an isProxy fast path check isn't too expensive
```
No fast path:
resp_w_bh:           	n = 1000000, dt = 1.295s, r = 772201/s, t = 1294ns/op
Fast path with isProxy check:
resp_w_bh:           	n = 1000000, dt = 1.146s, r = 872600/s, t = 1146ns/op
Forced fast path:
resp_w_bh:           	n = 1000000, dt = 1.112s, r = 899281/s, t = 1112ns/op
```
Pending on …
> perf(webidl): optimize createRecordConverter()

- ext/fetch/lib.rs
- ext/ffi/lib.rs
- ext/net/lib.rs
- ext/timers/benches/timers_ops.rs
- ext/timers/lib.rs
- ext/websocket/lib.rs
- runtime/build.rs
These are confusing. They say they are "for users that don't care about
permissions", but that isn't correct. `NoTimersPermissions` disables
permissions instead of enabling them.
I would argue that implementors should decide what permissions they want
themselves, and not take our opinionated permissions struct.
> chore: remove No*Permissions structs

- cli/ops/errors.rs
- cli/ops/runtime_compiler.rs
- core/error.rs
- core/examples/http_bench_json_ops.rs
- core/ops_builtin.rs
- core/runtime.rs
- ext/broadcast_channel/lib.rs
- ext/crypto/lib.rs
- ext/fetch/lib.rs
- ext/http/lib.rs
- ext/net/io.rs
- ext/net/ops.rs
- ext/net/ops_unix.rs
- ext/timers/lib.rs
- ext/webgpu/buffer.rs
- ext/webgpu/queue.rs
- ext/websocket/01_websocket.js
- ext/websocket/02_websocketstream.js
- ext/websocket/lib.rs
- runtime/js/30_os.js
- runtime/metrics.rs
- runtime/ops/fs.rs
- runtime/ops/io.rs
- runtime/ops/os.rs
- runtime/ops/runtime.rs
- runtime/ops/signal.rs
Primarily just gets rid of the `Option<ZeroCopyBuf>` and the `ok_or_else` for it which is the first thing in ops which stems from the first iteration of ZeroCopyBuf support, but doesn't make much sense anymore now.
For the webgpu related changes i will open up a PR at wgpu as well
> chore: various op cleanup

- cli/main.rs
- cli/standalone.rs
- runtime/examples/hello_runtime.rs
- runtime/lib.rs
- runtime/web_worker.rs
- runtime/worker.rs
- runtime/worker_bootstrap.rs
- Factors out shared portions of WorkerOptions & WebWorkerOptions to BootstrapOptions
- Adds ::bootstrap_from_options() methods
- Passes options by value instead of by ref so that we can mutate them and drain a vec of extensions passed
- I suppose the main reason we passed them by ref is that we had to repass them to .bootstrap()
- Conceptually, BootstrapOptions holds "higher-level" nice-to-have options compared to the rest of WorkerOptions that are closer tied to internal rust-side mechanics
> refactor(runtime): Worker bootstrap options

- cli/compat.rs
- cli/flags.rs
- cli/main.rs
- cli/proc_state.rs
- cli/tests/integration/compat_tests.rs
- cli/tests/testdata/compat/existing_import_map.out
- cli/tests/testdata/compat/globals.out
- cli/tests/testdata/compat/globals.ts
This commit adds automatic injection of Node globals when "--compat" flag
is present.
This is done by executing "https://deno.land/std/node/global.ts" as a "side module",
before main module is executed.
This commit makes "--compat" required to be used with "--unstable" flag, as some
of Node globals require unstable Deno APIs.
Towards #12295
> feat(compat): inject Node globals

- bench_util/benches/op_baseline.rs
`Deno.core.isProxy()` isn't an op but it establishes a good reference point for the overhead of calling into rust (aka binding overhead, of which opcall overhead is a superset)
We're currently at ~20ns/call on M1, <10% of that is actually spent in `v8::Value::IsProxy()` and `v8::Boolean::New()`
So there's room for improvement in `rusty_v8` that would benefit bindings & opcalls, but not trivial
> bench(op_baseline): measure Deno.core.isProxy()

- cli/dts/lib.deno.ns.d.ts
- cli/tests/unit/symlink_test.ts
- runtime/ops/fs.rs
This change requires full write and read permissions in order to create a symlink. The reason is to prevent multiple scenarios where someone could create a symlink to escape the directories they have restricted permissions to. For example:
1. Creating a symlink target in a directory outside the sandbox then reading from or writing to that folder.
2. Creating a valid relative symlink like `../../etc` and then moving an ancestor directory so the descendant symlink now points outside the sandbox.
This does not prevent an application causing trouble with existing relative symlinks (ex. `../../etc`) in a directory with write permissions where the write permissions are limited to certain folders.
Closes #12152
> fix(runtime): require full read and write permissions in order to create symlinks

- cli/tests/testdata/workers/test.ts.out
- cli/tools/test.rs
Closes https://github.com/denoland/deno/issues/12609
> feat(test): better formatting for test elapsed time

- ext/fetch/22_http_client.js
- ext/fetch/lib.rs
Rename `op_create_http_client` to `op_fetch_custom_client` to follow prefix/namespaced convention
> cleanup(ext/fetch): consistent op names

- cli/tools/test.rs
Just catched this in #12610, nice to have this formatting
Are milliseconds intentionally not shown when the test takes longer than a second (eg: `1s43ms`)?
> chore(cli): fix typo in `tools/test.rs`

- cli/tests/unit/fetch_test.ts
- ext/fetch/fs_fetch_handler.rs
- ext/fetch/lib.rs
- runtime/build.rs
- runtime/web_worker.rs
- runtime/worker.rs
> feat(ext/fetch): support fetching local files

- ext/web/06_streams.js
- ext/web/lib.deno_web.d.ts
Has a TODO for all the way back to 1.8. Also, std doesnt use getIterator anywhere anymore, so it should be safe to remove
> chore(ext/web): remove `ReadableStream.getIterator`

- cli/lsp/tsc.rs
- cli/tests/integration/lsp_tests.rs
These were previously displayed as plain text. Now they are displayed as
`MarkupContent` with type `Markdown`.
Fixes #12620.
> fix(lsp): display signature docs as markdown

- Cargo.lock
- cli/dts/lib.esnext.array.d.ts
- cli/tests/unit/esnext_test.ts
- core/Cargo.toml
- serde_v8/Cargo.toml
This commit updates the rusty_v8 to 0.34.0. This commit also adds
the required typings for the new Array#findLast and Array#findIndexLast
methods.
> feat: update to V8 9.7

- ext/web/03_abort_signal.js
Closes #12695
Also includes some webidl cleanup
> feat(ext/web): Add `AbortSignal.reason`

- ext/net/ops_tls.rs
This makes it posssible for implementors to cherry-pick which ops they
want to use.
> fix(ext/net): expose all tls ops

- cli/tools/upgrade.rs
Previously just a generic "error: No such file or directory (os error
2)" was printed. Now "`unzip` was not found on your PATH, please install
`unzip`" will be printed.
Closes #7085
> fix(cli/upgrade): nice error when unzip is missing

- cli/lsp/tsc.rs
- cli/tests/testdata/lsp/document_symbol_response.json
There has been a bit of "drift" in what TypeScript supports and what vscode does with information included in the navigation tree.
> chore(lsp): align ScriptElementKind to current versions of TypeScript/vscode

- cli/tests/unit/http_test.ts
- ext/http/01_http.js
- ext/http/lib.rs
- ext/websocket/lib.rs
- runtime/errors.rs
- runtime/ops/http.rs
This reverts commit 5b1e537446454f6332de44adbeb6a15ff072c2fa.
This change updates some behaviour that caused std/http to break. We will try to reland this for 1.16.1.
> Revert "refactor(ext/http): rewrite hyper integration and fix bug (#12332)"

- cli/tests/unit/fetch_test.ts
- ext/fetch/lib.rs
- test_util/src/lib.rs
This commit changes `fetch` to set `content-length: 0` on POST and PUT
requests with no body.
The relevant fetch spec text:
Fixes #12597
Fixes #11920
> fix(fetch): set content-length for empty POST/PUT

- .github/workflows/ci.yml
Sometimes you have to wait up to an hour before you can upgrade to the
latest canary build, because the file that stores the hash of the latest
commit is cached for up to an hour.
> build: set cache-control for dl.deno.land

- cli/tests/unit/http_test.ts
- ext/http/01_http.js
- ext/http/lib.rs
- ext/websocket/lib.rs
- runtime/errors.rs
- runtime/ops/http.rs
> reland #12332: refactor(ext/http): rewrite hyper integration and fix bug

- .github/workflows/ci.yml
The existing ubuntu-latest-xl runner image (based on Ubuntu 18.04 XL) is
deprecated and will retire soon. Migrate to ubuntu-20.04-xl instead.
> ci: use 'ubuntu-20.04' runner image rather than 'ubuntu-latest'

- cli/tests/unit/abort_controller_test.ts
- ext/web/lib.deno_web.d.ts
> fix: add typings for AbortSignal.reason

- cli/ast/mod.rs
There is a hidden `swc_ecma_utils::HANDLER` API that we need to take into account (it's a thread local variable that we need to set a value for).
Relates to #11613, but I think ideally it should not error and instead it should handle this scenario.
> fix(transpile): do not panic on `swc_ecma_utils::HANDLER` diagnostics

- Cargo.lock
- cli/Cargo.toml
- cli/emit.rs
- cli/main.rs
- cli/module_loader.rs
- cli/proc_state.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/095_cache_with_bare_import.ts.out
- cli/tests/testdata/disallow_http_from_https_js.out
- cli/tests/testdata/disallow_http_from_https_ts.out
- cli/tests/testdata/error_011_bad_module_specifier.ts.out
- cli/tests/testdata/error_014_catch_dynamic_import_error.js.out
- cli/tests/testdata/error_015_dynamic_import_permissions.out
- cli/tests/testdata/error_016_dynamic_import_permissions2.out
- cli/tests/testdata/error_local_static_import_from_remote.js.out
- cli/tests/testdata/error_local_static_import_from_remote.ts.out
- cli/tests/testdata/error_missing_module_named_import.ts.out
- cli/tests/testdata/import_blob_url_import_relative.ts.out
- cli/tests/testdata/import_data_url_import_relative.ts.out
- cli/tests/testdata/localhost_unsafe_ssl.ts.out
- cli/tests/testdata/ts_type_only_import.ts.out
- cli/tests/testdata/workers/permissions_dynamic_remote.ts.out
- cli/tools/coverage.rs
- cli/tools/test.rs
Additionally improve `ProcState::prepare_module_load()` to detect all errors it is supposed to, so no error handling needs to be done in `ProcState::load()` for supposedly prepared modules.
Fixes #12519.
Fixes #12740.
> fix(cli/proc_state): Short-circuit in prepare_module_load()

- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tests/integration/lsp_tests.rs
> fix(lsp): retain module dependencies when parse is invalid

- cli/lsp/diagnostics.rs
- cli/tests/integration/lsp_tests.rs
We weren't tagging deprecated diagnostics as deprecated, meaning they would not appear properly in the editor.
> fix(lsp): tag deprecated diagnostics properly

- core/runtime.rs
Demonstrates that nextTick() callbacks aren't invoked when there isn't
anything else keeping the event loop alive. Specifically:
1. nextTickCallback is invoked, but
2. macrotaskCallback is not
> fix(core): keep event loop alive if there are ticks scheduled

- runtime/js/40_testing.js
In tests, the function to format errors would assume that any property `errors` on error would contain an array, which is not necessarily the case.
I am currently porting a library to Deno and I was just bit by this.
> fix(testing): do not throw on error.errors.map

- cli/tests/unit/read_file_test.ts
- cli/tests/unit/read_text_file_test.ts
- runtime/js/40_read_file.js
Fixes #12366
Node also does a non sized read under the hood if stat returns a 0 size.
> fix(runtime): support reading /proc using readFile

- cli/lsp/diagnostics.rs
I think it will be better to move the vector of ignored paths to somewhere like `StateSnapshot` and update it on every config change, not on every `publish_diagnostics`.
Also, I've inverted an if statement in `publish_diagnostics`, so it looks a bit better.
Fixes #12608
> fix(lsp): use exclude files list from the config file

- ext/fetch/20_headers.js
- ext/fetch/23_request.js
- ext/fetch/23_response.js
- ext/fetch/26_fetch.js
This reverts commit 49ec3d10ad90851f4d28274a3f0fe96c642204ac.
This might introduce a slight performance degredation, but correctness is more important here. We can optimize this structure down the line by storing headers in a more optimized format internally (like Chromium does).
Fixes #12829
> revert: store header keys lower case internally

- cli/dts/lib.deno.ns.d.ts
- runtime/ops/fs_events.rs
This commit adds support for "other" events in `FSWatcher`. Flags on
events are now exposed via the `flag` property  on `FsEvent`.
There are no tests for this change, as the only known cause for this `"other"`
event being emitted, is watching an SMB share on macOS. Not something we can
really test for in CI.
Closes #12097
> fix: support "other" event type in FSWatcher

- cli/dts/lib.deno.ns.d.ts
- cli/tests/integration/mod.rs
- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/overloads.out
- cli/tests/testdata/test/overloads.ts
- cli/tests/unit/testing_test.ts
- runtime/js/40_testing.js
This commit adds 4 more overloads to "Deno.test()" API.
```
// Deno.test(function testName() { });
export function test(fn: (t: TestContext) => void | Promise<void>): void;
// Deno.test("test name", { only: true }, function() { });
export function test(
name: string,
options: Omit<TestDefinition, "name">,
fn: (t: TestContext) => void | Promise<void>,
): void;
// Deno.test({ name: "test name" }, function() { });
export function test(
options: Omit<TestDefinition, "fn">,
fn: (t: TestContext) => void | Promise<void>,
): void;
// Deno.test({ only: true }, function testName() { });
export function test(
options: Omit<TestDefinition, "fn" | "name">,
fn: (t: TestContext) => void | Promise<void>,
): void;
```
Closes https://github.com/denoland/deno/issues/12744
> feat(test): Add more overloads for "Deno.test"

- cli/lsp/language_server.rs
Fixes #12871
I've noticed that the rest of the functions handle URLs using `normalize_url`, but that was missing in `did_change_watched_files`.
> fix(lsp): normalize urls in did_change_watched_files

- cli/emit.rs
- cli/main.rs
- cli/ops/runtime_compiler.rs
- cli/proc_state.rs
- cli/tests/integration/run_tests.rs
Fixes #12755.
Fixes #12807.
Fixes #12832.
> fix(cli/emit): Don't cache .tsbuildinfo unless emitting

- cli/proc_state.rs
Currently modules that go through redirects are duplicated in the in-memory cache.
> refactor(cli/proc_state): Dedup source cache for redirected specifiers

- cli/lsp/diagnostics.rs
The tests expect 3 publish notifications. It was possible for less than 3 to occur if two or more tasks set the diagnostics in the collection, exited the lock at the same time, then called `publish_diagnostics`.
> chore(lsp): fix possible race condition with tests expecting 3 publishDiagnostics messages, but getting 2 or 1

- cli/tests/integration/compat_tests.rs
- test_util/src/lib.rs
This commit speeds up compat tests by using local copy of "deno_std"
instead of downloading it from https://deno.land for each test.
Additionally type checking is skipped.
Depends on https://github.com/denoland/deno/pull/12883
> chore: speed up compat tests

- cli/compat/errors.rs
- cli/compat/esm_resolver.rs
- cli/compat/mod.rs
- cli/main.rs
- cli/proc_state.rs
- cli/tests/integration/compat_tests.rs
- cli/tests/testdata/compat/dyn_import_reject.out
- cli/tests/testdata/compat/import_esm_from_cjs/index.js
- cli/tests/testdata/compat/import_esm_from_cjs/node_modules/pure-cjs/index.js
- cli/tests/testdata/compat/import_esm_from_cjs/node_modules/pure-cjs/package.json
- cli/tests/testdata/compat/import_esm_from_cjs/node_modules/pure-esm/index.js
- cli/tests/testdata/compat/import_esm_from_cjs/node_modules/pure-esm/package.json
This commit introduces "ProcState::maybe_resolver" field, which
stores a single instance of resolver for the whole lifetime of the
process, instead of creating these resolvers for each creation
of module graph. As a result, this resolver can be used in fallback
case where graph is not constructed (REPL, loading modules using
"require") unifying resolution logic.
Closes https://github.com/denoland/deno/issues/12628
Closes https://github.com/denoland/deno/issues/12872
> compat: support compat mode in REPL

- cli/tests/testdata/blob_gc_finalization.js
Reduce the number of iterations from 1,024 to 128.
On my big bruiser of a desktop machine it already takes up close to a
minute to complete when nothing else is running so no way it's going to
finish in the allotted time on the CI.
The fact that the test used to pass may be indicative of a performance
regression somewhere but it's not clear to me when or where that would
have been introduced.
Fixes #12887.
> fix(cli): fix slow test, unbreak ci

- core/01_core.js
- core/bindings.rs
- core/lib.deno_core.d.ts
- core/lib.rs
- core/ops.rs
- core/ops_json.rs
- core/ops_metrics.rs
- core/runtime.rs
- runtime/js/40_signals.js
- runtime/ops/signal.rs
This commit adds an ability to "ref" or "unref" pending ops.
Up to this point Deno had a notion of "async ops" and "unref async ops";
the former keep event loop alive, while the latter do not block event loop
from finishing. It was not possible to change between op types after 
dispatching, one had to decide which type to use before dispatch.
Instead of storing ops in two separate "FuturesUnordered" collections,
now ops are stored in a single collection, with supplemental "HashSet"
storing ids of promises that were "unrefed".
Two APIs were added to "Deno.core":
- "Deno.core.refOp(promiseId)" which allows to mark promise id 
to be "refed" and keep event loop alive (the default behavior)
- "Deno.core.unrefOp(promiseId)" which allows to mark promise 
id as "unrefed" which won't block event …
> feat(core): Add ability to "ref" and "unref" pending ops

- cli/tools/repl/channel.rs
- cli/tools/repl/mod.rs
I extracted this out of the repl import specifier autocompletion PR I'm working on.
Basically, for that PR I'm going to have to also get messages from the LSP for autocompletion and it would get out of hand quickly to not extract this out.
> refactor(repl): move rustyline sync channel communication into struct

- cli/tests/unit/wasm_test.ts
- ext/fetch/26_fetch.js
Fetching of local files, added in #12545, returns a response with no headers, including the `Content-Type` header. This currently makes it not work with the WebAssembly streaming APIs, which require the response to have a content type of `application/wasm`.
Since the only way to obtain a `Response` object with a non-empty `url` field is via `fetch()`, this change changes the content type requirement to only apply to responses whose url has the `file:` scheme.
> feat(wasm): Support `WebAssembly.instantiateStreaming` for file fetches

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/tls_test.ts
- ext/net/02_tls.js
- ext/net/lib.deno_net.d.ts
- ext/net/ops.rs
- ext/net/ops_tls.rs
* Make `connectTls()` accept `alpnProtocols` option
(string[]), just like `listenTls()`.
* Add `alpnProtocol` to `TlsConn#handshake` return
value to query the protocol agreed with the peer via ALPN.
The `alpnProtocols` is added as an unstable API (mirroring
how it's supported in `listenTls()`).
We need this change for making a Deno client for EdgeDB. EdgeDB
requires TLS by default and uses ALPN to upgrade connections to
its binary protocol. Without these APIs we can't support Deno,
something we really want to have.
Fixes: https://github.com/denoland/deno/issues/11479
> feat: ALPN support in `Deno.connectTls()`

- cli/main.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/set_exit_code_0.ts
- cli/tests/testdata/set_exit_code_1.ts
- cli/tests/testdata/set_exit_code_2.ts
- runtime/js/30_os.js
- runtime/lib.rs
- runtime/ops/os.rs
Set the exit code to use if none is provided to Deno.exit(), or when
Deno exits naturally.
Needed for process.exitCode Node compat. Paves the way for #12888.
> feat(runtime): add op_set_exit_code

- core/bindings.rs
- core/lib.deno_core.d.ts
- core/runtime.rs
Provide a programmatic means of intercepting rejected promises without a
.catch() handler. Needed for Node compat mode.
Also do a first pass at uncaughtException support because they're
closely intertwined in Node. It's like that Frank Sinatra song:
you can't have one without the other.
Stepping stone for #7013.
> feat(core): intercept unhandled promise rejections

- cli/tests/testdata/websocketstream_test.ts
- ext/websocket/lib.rs
> fix(websocket): Bad resource ID when aborting `WebSocketStream` after creation

- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/ops_sanitizer_timeout_failure.out
- cli/tests/testdata/test/ops_sanitizer_timeout_failure.ts
- runtime/js/40_testing.js
Although not easy to replicate in the wild, the `deno test` op sanitizer can fail when there are intervals that started before a test runs, since the op sanitizer can end up running in the time between the timer op for an interval's run resolves and the op for the next run starts.
This change fixes that by adding a new macrotask callback that will run after the timer macrotask queue has drained. This ensures that there is a timer op if there are any timers which are unresolved by the time the op sanitizer runs.
> fix(test): Improve reliability of `deno test`'s op sanitizer with timers

- runtime/lib.rs
> chore: re-export `deno_core` from `deno_runtime`

- cli/tests/unit/net_test.ts
- ext/net/ops.rs
Alternative proposal to #12817 
Fixes #10470 
Enable UDP sockets to send messages to the broadcast address (`255.255.255.255`).
See relevant discussion on linked PR #12817 for considerations.
> feat(ext/net): Enable sending UDP messages to the broadcast address

- core/runtime.rs
See #12771 and #12814.
Needed to reland #12908, which was reverted in #12929.
> fix(core): Wake up the runtime if there are ticks scheduled

- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/ops_sanitizer_nexttick.out
- cli/tests/testdata/test/ops_sanitizer_nexttick.ts
- cli/tests/testdata/test/ops_sanitizer_timeout_failure.out
- cli/tests/testdata/test/ops_sanitizer_timeout_failure.ts
- runtime/js/40_testing.js
This relands #12908 –which was reverted by #12929– now that #12933 has landed. It also adds @kt3k's tests from https://github.com/denoland/deno/pull/12908#issuecomment-981462813
> reland #12908: fix(test): Improve reliability of `deno test`'s op sanitizer with timers

- core/bindings.rs
Instead of panicking via asserts, since JS-callable code (even Deno.core ...) should not cause process crashes/panics
> fix(core): throw on invalid callConsole args

- core/bindings.rs
Instead of panicking via asserts, since JS-callable code (even Deno.core ...) should not cause process crashes/panics
> [v1.16] fix(core): throw on invalid callConsole args (#12973)

- .github/workflows/ci.yml
Closes https://github.com/denoland/deno/issues/12985
> build: don't publish canary version from non-main branch

- cli/tests/unit/http_test.ts
> fix(ext/timers): fix flakiness of `httpConnAutoCloseDelayedOnUpgrade` test

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/http_test.ts
- cli/tests/unit/timers_test.ts
- ext/timers/01_timers.js
- runtime/js/90_deno_ns.js
depends on #12862 (alternative to #12942)
This PR adds Deno.refTimer and Deno.unrefTimer APIs in the unstable namespace.
---
closes #6141
> feat(ext/timers): add refTimer, unrefTimer API (alt)

- Cargo.lock
- cli/Cargo.toml
- cli/file_fetcher.rs
- cli/http_cache.rs
- cli/http_util.rs
- cli/lsp/registries.rs
- test_util/src/lib.rs
Fixes #9931
Effectively this adds a "cache strategy" to the file fetcher to respect the headers of the cached response, and the LSP registry cache is the only instance of file fetcher that uses this strategy. It isn't a 100% compliant, in the sense that we a) cache in memory per session, irrespective of headers and b) we will always persist a response to the cache, even if the headers tell us not to.  Now though for the registry cache, when we go to access that cache, we will respect any headers we received and only use the cached value if it was valid. We will still only do it once per "session" though.
I have tested it locally and it works, but wanted to get any feedback on it before I flesh out all the unit tests, specially from @lucacasonato as you probably have the strongest …
> feat(lsp): registry suggestion cache respects cache headers

- ext/crypto/00_crypto.js
As per request @lucacasonato in #12022. 
Refac covers:
1) Move importKey(jwt) for symmetric-keys to Rust, using `fn decode_b64url()`
2) Use enum `ImportExportKeyData` and related `pub struct`s to distinguish raw/jwk import data. Will be extended for RSA and EC JWK imports.
3) Move common js code to `function importKeyRSA(...)`
4) Added importkey for ECDH(raw) and moved common code to `function importKeyEC(...)`
5) Standardize use of `type`/`keyType`/`format` in key structures.
- includes `read_rsa_public_key()` from #12921, along with validation of `r#type` where necessary
6) Cleanup, 
- use const/alias `algorithmName` for `normalizedAlgorithm.name`
- use const/alias for `namedCurve` and 'keyType'
- use short-form to build js hashes, where possible, for example `{ format, namedCurve, ... …
> refactor(ext/crypto): various cleanups in js code

- cli/dts/lib.deno.ns.d.ts
- ext/net/lib.deno_net.d.ts
The way JSDoc tags work, once a tag is encountered, the text associated with the tag is everything up to the next tag, so all tags should come _after_ the documentation block associated with the entity.  This is consistent with how the likes of vscode and other parse tags, including now `deno_doc`.
This will fix issues where the documentation block is not appearing for certain entries in `doc.deno.land` because only the doc block is being displayed in a listing (along with just the `deprecated` tag).
> chore: place `@deprecated` tag after documentation block

- cli/tests/unit/webcrypto_test.ts
Use fixed data that is known to error as the test intends.
Closes #13039
> tests: deflake crypto InvalidIntializationVector

- runtime/colors.rs
> fix(cli):  refrain from adding colours to the non-tty outputs

- Cargo.lock
- ext/crypto/00_crypto.js
- ext/crypto/Cargo.toml
- ext/crypto/import_key.rs
This commit moves JWK secret importing for HMAC and AES to Rust.
> refactor(ext/crypto): symmetric jwk decode in rust

- runtime/js/40_testing.js
> fix(test): Make the op sanitizer delay macrotask into a queue

- runtime/colors.rs
This reverts commit 38f163022373c9adb050f17140f7d29bb403abe2.
Ref #13049
> Revert "fix(cli): don't add colors for non-tty outputs (#13031)"

- core/bindings.rs
```
> Deno.core.opSync(undefined, 1, 1);
Uncaught TypeError: invalid op id: received `undefined` instead of an integer.
This error is often caused by a typo in an op name, or not calling
JsRuntime::sync_ops_cache() after JsRuntime initialization.
at Object.opSync (deno:core/01_core.js:149:27)
at <anonymous>:2:11
>
```
Closes https://github.com/denoland/deno/issues/12919
> fix(core): improve error on invalid op id

- core/examples/fs_module_loader.rs
Just adding a simple example of module loading, I'm using it
to test import assertions/JSON modules integration.
> example(core): add example for FS module loading

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/071_location_unset.ts.out
- ext/web/12_location.js
Currently `globalThis.location` throws an error when `--location` is not specified. This behavior is inconvenient if a script does the feature detection like `typeof window.location` ([type-detect](https://npm.im/type-detect) is an example of such a script)
This PR changes it to return `undefined` for `window.location` when `--location` is not specified.
closes #12969
previous version: #10828
> fix(ext/web): set location undefined when `--location` is not specified

- cli/tests/unit/net_test.ts
- ext/net/ops.rs
- ext/net/ops_unix.rs
std/http/server knows how to handle "Listener has been closed"
exceptions but not "operation canceled" errors.
Make "unix" listen sockets throw the same exception as "tcp" listen
sockets when the socket is closed and has a pending accept operation.
There is still a discrepancy when multiple accept requests are posted
but that's probably a less visible issue and something for another day.
Fixes #13033
> fix(ext/net): make unix and tcp identical on close

- cli/flags.rs
- cli/main.rs
- cli/tests/integration/watcher_tests.rs
- cli/tools/standalone.rs
> feat(watch): support watching external files

- ext/crypto/00_crypto.js
- ext/crypto/encrypt.rs
- ext/crypto/lib.rs
- ext/crypto/shared.rs
Cleans up the rust side of `crypto.subtle.encrypt`, and properly asyncifies it.
> refactor(ext/crypto): clean up encrypt rust code

- cli/tests/integration/inspector_tests.rs
- cli/tests/testdata/inspector_test.js
- runtime/worker.rs
Fixes #12584
This the first time I've ever worked with rust so apologies if this a terrible PR.
All tests passed locally except for `test_respect_cache_revalidates` which was already failing without this change.
One thing I was a bit worried about was that this change would cause multiple breaks every time a new module is loaded. But I couldn't find any case where this happens.
Also, should a new test case for this specific issue be added? I couldn't find any existing tests checking for the inspector like this, so I'm not sure I'm capable of writing such a test case.
> fix(test): wait for inspector session in side modules

- cli/tests/unit/fetch_test.ts
- ext/fetch/26_fetch.js
The spec PR for this (whatwg/fetch#1343) hasn't been finalized yet because some questions regarding service worker integration are not settled yet, but since that is not relevant to Deno and everything else seems settled, and it seems best to not wait for another Deno version to support abort reasons in the fetch API.
> feat(fetch): Support abort reasons in fetch

- ext/ffi/lib.rs
👋
This patch fixes a build error I get when [compiling for aarch64 in Linux](https://github.com/LukeChannings/deno-arm64/runs/4552696134?check_suite_focus=true):
```
Compiling deno_ffi v0.16.0 (/deno/ext/ffi)
error[E0308]: mismatched types
--> ext/ffi/lib.rs:612:30
|
612 |   Ok(unsafe { CStr::from_ptr(ptr) }.to_str()?.to_string())
|                              ^^^ expected `u8`, found `i8`
|
= note: expected raw pointer `*const u8`
found raw pointer `*const i8`
For more information about this error, try `rustc --explain E0308`.
error: could not compile `deno_ffi` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```
This is caused by `CStr::from_ptr` returning an `i8` on aarch64, instead of a `u8`.
Using `std::os::raw::c_char` will …
> fix(ext/ffi): Use `c_char` instead of `i8` in `op_ffi_cstr_read` for compatibility with aarch64

- cli/tools/coverage.rs
I think coverage values use char index? Fixes #13111.
> fix(cli/tools/coverage): Split sources by char index

- cli/tests/integration/inspector_tests.rs
- runtime/inspector_server.rs
- runtime/web_worker.rs
- runtime/worker.rs
This commit fixes prompts printed to the terminal when
running with "--inspect" or "--inspect-brk" flags.
When debugger disconnects error is no longer printed as
users don't care about the reason debugger did disconnect.
A message suggesting to go to "chrome://inspect" is printed 
if debugger is active.
Additionally and information that process is waiting for
debugger to connect is printed if running with "--inspect-brk"
flag.
Closes https://github.com/denoland/deno/issues/13110
Closes https://github.com/denoland/deno/issues/13124
> fix: inspector prompts

- .github/workflows/wpt_epoch.yml
Runs either fail or keep running for days. I noticed this recently:
- https://github.com/littledivy/deno/actions/runs/1600071948
- https://github.com/littledivy/deno/actions/runs/1597394500
> fix(wpt_ecoch): Don't schedule on forks

- cli/lsp/code_lens.rs
- cli/tests/testdata/lsp/code_lens_response_test.json
Fixes: #13130
Existing clients still need to add support for the `{inspect: true}` option.
I'm not sure what the current state is of the stability of lsp. I noticed a document saying lsp was still experimental and not feature complete, but this got removed when the document was moved to https://deno.land/manual@v1.17.0/language_server/overview last week.
Either way this shouldn't break any existing IDE plugins in a significant way. The debug button will simply run the test rather than debug it.
> feat(lsp) add code lens for debugging tests

- cli/main.rs
Closes #9263
Looks like this:
```
/m/s/P/g/d/deno ❯❯❯ ./target/debug/deno run --quiet --reload --allow-net --unstable workers/permissions_dynamic_remote.ts
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: linux x86_64
Version: 1.16.4
Args: ["./target/debug/deno", "run", "--quiet", "--reload", "--allow-net", "--unstable", "workers/permissions_dynamic_remote.ts"]
thread 'main' panicked at 'foo!', cli/main.rs:1493:3
```
> chore: add custom panic message

- cli/file_fetcher.rs
- cli/http_util.rs
- cli/lsp/registries.rs
- test_util/src/lib.rs
Closes #13153
This will set the following header when fetching a registry configuration:
```
Accept: application/vnd.deno.reg.v2+json, application/vnd.deno.reg.v1+json;q=0.9, application/json;q=0.8
```
This will allow servers to understand that a language server client would prefer a v2 version of the registry configuration.
> feat(lsp): supply accept header when fetching registry config

- test_util/src/lsp.rs
The following, which does not contain `r\n\r\n`, would have resulted in an infinite loop.
```rs
let msg2 = b"hello world";
let mut reader2 = std::io::Cursor::new(msg2);
read_message(&mut reader2);
```
> test(test_util/lsp): Add invalid case

- cli/module_loader.rs
- core/lib.rs
- core/modules.rs
Closes https://github.com/denoland/deno/issues/13095
> refactor: core/modules.rs

- cli/tests/integration/repl_tests.rs
Closes #13158. Right now, [`resolve_path`](https://github.com/denoland/deno/blob/aca41a472a07932dd973cbefcf8a94920646ee58/core/module_specifier.rs#L141) in deno_core panics when the cwd doesn't exist and it seems like a big change to fix that (maybe not even worth it) so removing this test for now.
> chore(tests): remove pty_complete_imports test for deleting the cwd

- Cargo.lock
- runtime/Cargo.toml
- runtime/ops/os.rs
Add an op to list the network interfaces on the system.
Prep work for #8137 and `os.networkInterfaces()` Node compat in std.
Refs denoland/deno_std#1436.
<hr>
Opening this as a WIP because I'd like feedback on what permissions to check for.
> feat(ext/net): add op_network_interfaces

- cli/tests/unit/console_test.ts
- ext/console/02_console.js
closes #13165
---
This will colorize the 8 basic colors in css that are also ansi colors (black, white, red, green, blue, yellow, magenta, cyan). It works regardless of the method used to specify the color, e.g. #000000 and "black" will both make the text black. If you want only the color's name to colorize output, i'll update the PR.
I couldn't find the unit tests for this part of the code, but if someone could point me in the right direction i'd be glad to add coverage for this, and I wasn't able to run the lint & format scripts locally for some reason. Are they broken?
> fix: map basic css color keywords to ansi

- cli/ast/mod.rs
- cli/tests/integration/bundle_tests.rs
- cli/tests/testdata/subdir/json_3.json
- cli/tests/testdata/subdir/mod7.js
- cli/tests/testdata/subdir/mod8.js
> fix(cli): include JSON modules in bundle

- cli/lsp/code_lens.rs
Fixes: #13216
This now identifies tests and applies code lenses that follow the following format:
```ts
Deno.test(function aTestFunction() {
// ...
});
```
> fix(lsp): add code lens for tests just using named functions

- cli/main.rs
- cli/ops/errors.rs
- cli/ops/mod.rs
- cli/ops/runtime_compiler.rs
- cli/ops/testing.rs
- cli/standalone.rs
- cli/tools/test.rs
- runtime/ops/mod.rs
Enabling op-middleware for overrides in lieu of imperative .replace_op() etc...
Impacts #13219,  #12938, #13122
> cleanup(cli): use op Extensions

- core/examples/hello_world.rs
- core/examples/http_bench_json_ops.rs
- core/modules.rs
- core/ops_json.rs
- core/runtime.rs
In examples and tests.
It's slightly more verbose but I think we should encourage the declarative approach in all examples/code and ultimately deprecate the imperative APIs
> cleanup(core): use Extensions to register ops

- cli/lsp/tsc.rs
Since registering ops declaratively is a best practice
> cleanup(cli/lsp): use op Extensions

- cli/fmt_errors.rs
- cli/source_maps.rs
- cli/tests/integration/mod.rs
- cli/tests/testdata/error_cause.ts
- cli/tests/testdata/error_cause.ts.out
- cli/tests/testdata/error_cause_recursive.ts
- cli/tests/testdata/error_cause_recursive.ts.out
- core/error.rs
> feat: output cause on JS runtime errors

- core/lib.rs
- ext/broadcast_channel/lib.rs
`CrossIsolateStore`, `ExtensionBuilder` and `InMemoryChannelResource` are private types which are referred to by other public APIs, and so they show up in the rustdoc, but not as links. This is especially confusing for `ExtensionBuilder`, since there is nothing in the docs that explains how to build an extension.
Exposing these three types doesn't add any new capabilities: `ExtensionBuilder` can be created from `Extension::builder()`, `SharedArrayBufferStore` and `CompiledWasmModuleStore` already enable doing anything that `CrossIsolateStore` can do, and `InMemoryChannelResource` isn't constructable.
> fix(doc): Make private types which show up in the rustdocs public

- cli/lsp/registries.rs
- cli/tests/testdata/lsp/registries/deno-import-intellisense.json
Discovered an issue with registry completions when generating the documentation URLs where matched variables needed to be interpolated.
> fix(lsp): properly generate data URLs for completion items

- .github/workflows/ci.yml
- .github/workflows/wpt_epoch.yml
GHA keeps redacting all occurrences of the word "deno" out of logs
because this is our wpt.fyi username. This is rather annoying (suprise suprise),
so I am just hardcoding the username in the CI script now.
> build: hardcode WPT_FYI_USER

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/import_key.rs
Ref: #13222
Base-64-url values in JWK are encoded without padding, and have a non-canonical representation since the last character may include 2 or 4 unused "overflow" bits. Encoding should be canonical but decoders may be tolerant, as per `btoa` - [forgiving-base64-decode](https://infra.spec.whatwg.org/#forgiving-base64-decode). 
Chrome and Node implementations of webcrypto `importKey` are tolerant and ignore the overflow bits. 
Previous Deno implementation in js used `btoa` so was tolerant, see [here](https://github.com/denoland/deno/pull/13047/files#diff-863c907dfc6c1c6e507b662a7fc0ead3446473facaf183b7ca1a6908b50ab444L194)
PR implements "forgiving" in JWK decode passing suitable `config` to `base64::decode_config`. Includes test-case.
Rationale: Specifications are somewhat unclear on …
> fix(ext/crypto) base-64 for JWK

- core/inspector.rs
This commit rewrites "InspectorSession" to no longer implement "Future"
trait but instead implement "Stream" trait. "Stream" trait is implemented 
by yielding a raw pointer to the "v8::inspector::V8InspectorSession" and 
received message. In effect received messages are no longer dispatched 
from within the future, but are explicitly dispatched by the caller.
This change should allow us to dispatch a message to the session when
another message is being dispatched, ie. 
"V8InspectorSesssion::dispatch_protocol_message" is already on the 
call stack. This situation can happen during an execution pause, especially
in situation from #13234
> refactor(core): InspectorSession implements Stream

- ext/web/08_text_encoding.js
In the `transform` function to `TextEncoderStream`'s internal `TransformStream`, if `chunk` is the empty string and `this.#pendingHighSurrogate` is null, then `lastCodeUnit` will be NaN. As it turns out, this does not cause a bug because the comparison to check for lone surrogates turns out to be false for NaN, but to rely on it makes the code brittle.
> refactor(ext/web): Don't rely on NaN comparisons in `TextEncoderStream`

- ext/ffi/lib.rs
- test_ffi/tests/integration_tests.rs
- test_ffi/tests/test.js
Also improves error message for symbol which could not be found (this has been bugging me when developing FFI related projects...)
closes #13280
> fix(ext/ffi): throw errors instead of panic

- serde_v8/src/de.rs
- serde_v8/tests/de.rs
Fixes #13185 but slightly degrades error quality
Also rewrote struct deserialization to use a `SeqAccess` instead of a `MapAccess` making it simpler
> fix(serde_v8): support #[serde(default)]

- cli/flags.rs
- cli/tools/installer.rs
- cli/tools/standalone.rs
This changes doing `deno install` with `-A`/`--allow-all` to output a shim with `--allow-all` only instead of listing every permission flag.
We do not need to be concerned about potential future permission flags because `--allow-all` has a permission for `--allow-run` which allows for anything to occur already.
Closes #11819
> fix: `deno install` with `--allow-all` should output shim with `--allow-all` instead of each permission

- cli/dts/lib.deno.ns.d.ts
`Deno.writeAllSync` is deprecated and its docs say to use `writeAllSync` from std.
> docs: update `writeSync` docs to refer to `writeAllSync` in deno.land/std instead of `Deno.writeAllSync`

- cli/file_fetcher.rs
- cli/tests/integration/coverage_tests.rs
- cli/tools/coverage.rs
This commit changes "deno coverage" command not to type check.
Instead of relying on infrastructure for module loading in "deno run";
the code now directly reaches into cache for original and transpiled
sources. In case sources are not available the error is returned to the
user, suggesting to first run "deno test --coverage" command.
Fixes https://github.com/denoland/deno/issues/13161
Fixes https://github.com/denoland/deno/issues/13326
> fix(coverage): don't type check

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/build.rs
- cli/tsc.rs
- runtime/Cargo.toml
- runtime/build.rs
- runtime/js.rs
depends on  denoland/rusty_v8@1cedb0eb21a05eecd67869440005b6ac77dde503 reversal
replaces v8 zlib compression with lz4 and zstd for better speed and compression ratio
| build | size |
|:---| --- |
| deno-new | 79mb |
| deno-uncompressed | 103mb |
| deno-v8-compressed | 80mb |
| `deno run` with cache (cli snapshot) | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `deno-new run -A b.ts` | 30.4 ± 0.5 | 29.6 | 32.3 | 1.03 ± 0.02 |
| `deno-uncompressed run -A b.ts` | 29.6 ± 0.4 | 28.9 | 31.5 | 1.00 |
| `deno-v8-compressed run -A b.ts` | 44.6 ± 0.5 | 43.8 | 46.6 | 1.51 ± 0.03 |
| `deno cache` with no cache (tsc snapshot) | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `deno-new cache -r b.ts` | 266.5 ± 1.6 | 264.1 | 269.0 | 1.05 ± 0.01 |
| …
> feat(cli, runtime): compress snapshots

- cli/fs_util.rs
- cli/main.rs
- cli/tests/integration/compile_tests.rs
- cli/tools/standalone.rs
Pull request in reference to issue #13233
When --output flag value contains a directory structure it used to throw an error message which has been fixed in this commit. Now when directory structure is passed it will infer binary name and even create directory structure if it does not already exists on the filesystem.
> cli(compile): Fix output flag behaviour on compile command

- cli/dts/lib.deno.unstable.d.ts
- ext/ffi/lib.rs
- test_ffi/tests/integration_tests.rs
- test_ffi/tests/test.js
> feat(ext/ffi): support alias names for symbol definitions

- .github/workflows/wpt_epoch.yml
Since ubuntu-latest-xl is based on Ubuntu 18 (so indeed not "latest") and will be deprecated by GitHub on January 24th, 2022
> chore(ci): ubuntu-latest-xl => ubuntu-20.04-xl

- cli/dts/lib.es2021.intl.d.ts
- cli/tests/unit/esnext_test.ts
V8 has supported `Intl.ListFormat` since version 7.2, but TypeScript doesn't have typings for it yet. This PR manually adds those typings, copying them from microsoft/TypeScript#47254.
Fixes #13199.
> fix(tsc): Add typings for `Intl.ListFormat`

- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/lsp/performance.rs
- cli/lsp/tsc.rs
`Performance` was hoping along for the ride on `StateSnapshot`, but it is not really part of the concept of a "snapshot". Instead it should be a constructor dependency on these other structs.
> refactor(lsp): remove `performance` from `StateSnapshot`

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/delete_window.js
- ext/web/02_event.js
- runtime/worker.rs
This commit fixes an error when user deletes "window" global JS
variable. Instead of relying on "window" or "globalThis" to dispatch
"load" and "unload" events, we are default to global scope of the
worker.
Fixes https://github.com/denoland/deno/issues/13358
> fix(runtime): don't crash when window is deleted

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
This PR stores all assests behind a mutex in order to make more language server messages not require mutability.
This is possible to do because the assets are static and it is ok if two threads race to retrieve a non-cached asset from tsc.
This is slowly moving towards #11307.
> refactor(lsp): store assets behind a mutex

- cli/lsp/analysis.rs
- cli/lsp/code_lens.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/lsp/urls.rs
Similar to #13414, this PR stores the state of `LspUrlMap` behind a mutex in order to make more language server messages not require mutability (and run concurrently in the future).
I believe this is ok to do because the `LspUrlMap` is a cache whose value doesn't change once set and providing a value to `normalize_specifier` will always have the same output. That said, `normalize_url` might be different based on whether `normalize_specifier` has been called yet or not. I think for how `LspUrlMap` is used this shouldn't matter?
Again, slowly moving towards #11307.
> refactor(lsp): store the `LspUrlMap`'s state behind a mutex

- cli/lsp/analysis.rs
- cli/lsp/code_lens.rs
- cli/lsp/completions.rs
- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
This PR reduces the amount of data stored in `StateSnapshot` to only what is necessary for TSC and diagnostics.
This should be slightly more efficient and slowly works towards not passing around `language_server::Inner` and #11307.
> refactor(lsp): reduce data stored in `StateSnapshot`

- runtime/Cargo.toml
- runtime/ops/signal.rs
Unblocks building the runtime for aarch64-linux-android:
```shell
RUSTFLAGS="-C linker=/home/divy/gh/rusty_v8/third_party/android_ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch
64-linux-android21-clang++" cargo build --target aarch64-linux-android
```
> chore: update netif to 0.1.1

- serde_v8/src/de.rs
- serde_v8/src/error.rs
- serde_v8/src/magic/buffer.rs
- serde_v8/src/magic/zero_copy_buf.rs
- serde_v8/src/payload.rs
- serde_v8/tests/de.rs
Previously we would only deserialize `ArrayBufferView`s as zero-copy bufs
This avoids rewrapping `ArrayBuffer`s in `ArrayBufferView`s when implementing APIs that take [BufferSource](https://webidl.spec.whatwg.org/#BufferSource) args passed through the op-layer
> feat(serde_v8): deserialize ArrayBuffers

- ext/crypto/lib.deno_crypto.d.ts
Can be observed here: https://doc.deno.land/deno/stable/~/RsaHashedImportParams
It did not break `importKey` and wasn't detected by our tests because the right definition was inferred as [HmacImportParams](https://doc.deno.land/deno/stable/~/HmacImportParams) 
(i wish lint could complaint about overriding fields in duplicate definitions)
> fix(ext/crypto): duplicate RsaHashedImportParams types

- cli/file_fetcher.rs
- cli/lsp/cache.rs
- cli/lsp/config.rs
- cli/lsp/language_server.rs
- cli/lsp/registries.rs
- cli/lsp/repl.rs
- cli/proc_state.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/did_open_params_tls_cert.json
- cli/tests/testdata/lsp/initialize_params_tls_cert.json
Fixes #13437
The LSP now respects `DENO_CERT` and `DENO_TLS_CA_STORE` for registry suggestions and caching remote modules.
This also adds the options to the configuration of the LSP:
- `tlsCertificate` - this mirrors the `--cert` option (and overrides the `DENO_CERT` environment variable)
- `certificateStores` - this overrides the `DENO_TLS_CA_STORE` enviornment variable.
- `unsafelyIgnoreCertificateErrors` - this mirrors the `--unsafely-ignore-certificate-errors` command line option.
It extracts the creation logic for `RootCertStore` which is used by the file fetcher to the file fetcher which is now shared between `ProcState` and the lsp.
> fix(lsp): respect DENO_CERT and other options related to TLS certs

- cli/lsp/documents.rs
- cli/lsp/performance.rs
- cli/lsp/tsc.rs
Chasing down another issues I realised that while individual `op_exists` and `op_script_version` are not performance issues themselves, they are often called 1000s of time per document and we should really try to be as efficient with them as possible.
> perf(lsp): improve some tsc op hot paths

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/network_interfaces_test.ts
- runtime/js/30_os.js
- runtime/js/90_deno_ns.js
This PR adds an unstable new API `Deno.networkInterfaces` which returns an array of network interface informations.
closes #8137
> feat(unstable): add Deno.networkInterfaces

- cli/lsp/completions.rs
- cli/lsp/documents.rs
- cli/lsp/tsc.rs
`Document.exists` was added in #13473, but we already have a method for doing this. This changes combines the two methods and uses the new functionality.
> refactor(lsp): Documents - combine duplicate exists methods

- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/resource_sanitizer.out
- cli/tests/testdata/test/resource_sanitizer.ts
- runtime/js/40_testing.js
- sanitizers_test.ts
This commit makes the errors produced from the resource sanitizer much
more human readable. It does this by using real words rather than our
"resource names" when referring to resources, and by giving helpful
hints on how to clean up each of the resources.
> feat(test): better errors for resource sanitizer

- cli/dts/lib.deno.unstable.d.ts
sleepSync jsdoc has an error in markdown syntax. This affects the rendered doc in doc.deno.land https://doc.deno.land/deno/unstable/~/Deno.sleepSync
> docs: fix markdown error in sleepSync jsdoc

- .github/workflows/ci.yml
The reverted PR had the unintentional side effect of disabling static linking on Windows.
See https://github.com/denoland/deno/issues/13471.
This reverts commit 79b698f88b5f8e247df7280ccb52c2a8271a426c.
> Revert "error on warnings (#13344)"

- cli/lsp/diagnostics.rs
> fix(lsp): regression where certain diagnostics were showing for disabled files

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/decrypt.rs
> fix(ext/crypto): enforce 128bits tagLength for AES-GCM decryption

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/os_test.ts
- runtime/js/30_os.js
- runtime/js/90_deno_ns.js
- runtime/ops/os.rs
> feat(unstable): add Deno.getUid

- cli/dts/lib.deno_webgpu.d.ts
https://github.com/denoland/deno/blob/bd5d445da98435d03e2f6a6f6d5478ff623bd714/ext/webgpu/webgpu.idl#L628-L632
> fix(cli/dts/webgpu): make GPUBlendComponent properties optional

- cli/lsp/diagnostics.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
Adds the ability to cancel generating TypeScript diagnostics while they're being generated. I'm not sure how to test this to see what kind of improvement this may bring, but I assume it will be helpful.
> perf(lsp): cancellable TS diagnostics

- cli/bench/lsp_bench_standalone.rs
- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/tests/integration/lsp_tests.rs
- test_util/src/lsp.rs
Was looking through the code for more deadlocks and did some refactoring to remove the circular dependency between `LanguageServer` and `DiagnoticsServer`. To be clear, I don't see any deadlock potential in this code, but removing the circular dependency will reduce the chance of code changes in the future causing a deadlock.
The circular dependency is removed by the language server sending a snapshot to the diagnostics server when causing a diagnostics update.
> refactor(lsp): remove circular dependency between `LanguageServer` and `DiagnosticsServer`

- cli/deno_dir.rs
- cli/tests/integration/cache_tests.rs
Canonicalize the cache/home dir before use in DenoDir.
Fixes #13561
> fix: don't crash when $HOME is a relative path

- cli/lsp/analysis.rs
- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/code_action_redirect_response.json
Ref: #12864
This is a more general solution to #12864, which I think I like better.  It also "works" for pinning URLs with the Deno warnings like `deno.land/x` and `deno.land/std`.
Basically if a specifier is redirected, a quick fix will be available to replace the import with the redirected URL.  For example:
https://user-images.githubusercontent.com/1282577/152283410-ff95954d-b2ca-4a93-8f04-e623e2e50ffa.mp4
> feat(lsp): add redirect diagnostic and quick fix

- cli/tests/unit/console_test.ts
- ext/console/02_console.js
When using css coloring in the console, non-color values should be ignored rather than throw exceptions.
Fixes #13469
> Fix uncaught TypeError in ext/console (css styling)

- cli/flags.rs
- cli/tests/integration/mod.rs
- cli/tools/installer.rs
- cli/tools/standalone.rs
> feat: prompt by default

- ext/websocket/lib.deno_websocket.d.ts
As somewhat discussed OOB, I think it makes sense to call attention to `Deno.upgradeWebSocket()` in the WebSocket documentation. I hope I went about this right.
> docs(websockets): add comment about Deno.upgradeWebSocket() for WebSocket servers

- Cargo.lock
- cli/tests/unit/http_test.ts
- ext/http/Cargo.toml
- ext/http/lib.rs
- runtime/ops/http.rs
This adds support for unix domain sockets in ext/http (#13626). The primary change is replace `std::net::SocketAddr` with a custom enum so we can store the address of a unix domain socket. I have to make this type `pub` in order to refer to it in runtime/ops/http.rs .
> feat(ext/http): add support for unix domain sockets

- ext/web/14_compression.js
This commit makes the error messages that one sees when passing
something other than a BufferSource to a (De)CompressionStream. The
WPT tests already pass, because they just check for error type
(TypeError), and not error message. A TypeError was already thrown for
invalid values via serde_v8.
> chore: improve error messages in CompressionStream

- ext/fetch/lib.deno_fetch.d.ts
The document of some methods in the `Request` object refers to `Response`, which I believe are copy-paste error (there are same methods in the `Response` object with identical doc string)
> docs(ext/fetch): fix copy-paste errors in Request docs

- ext/console/02_console.js
This must have slipped in the previous PR
> fix(ext/console): print circular ref indicator in cyan

- cli/tests/testdata/test/ops_sanitizer_multiple_timeout_tests.out
- cli/tests/testdata/test/ops_sanitizer_multiple_timeout_tests.ts
- cli/tests/testdata/test/ops_sanitizer_unstable.out
- cli/tests/testdata/test/ops_sanitizer_unstable.ts
- cli/tests/unit/http_test.ts
- cli/tests/unit/timers_test.ts
- cli/tools/test.rs
- core/01_core.js
- core/lib.deno_core.d.ts
- runtime/js/40_testing.js
This commit improves the error messages for the `deno test` async op
sanitizer. It does this in two ways:
- it uses handwritten error messages for each op that could be leaking
- it includes traces showing where each op was started
This "async op tracing" functionality is a new feature in deno_core.
It likely has a significant performance impact, which is why it is only
enabled in tests.
> feat(test): improved op sanitizer errors + traces

- Cargo.lock
- cli/Cargo.toml
- runtime/Cargo.toml
As advised by `cargo audit`
```
$ cargo audit
Crate:         nix
Version:       0.22.1
Title:         Out-of-bounds write in nix::unistd::getgrouplist
Date:          2021-09-27
ID:            RUSTSEC-2021-0119
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0119
Solution:      Upgrade to ^0.20.2 OR ^0.21.2 OR ^0.22.2 OR >=0.23.0
Dependency tree:
nix 0.22.1
├── rustyline 9.0.0
│   └── deno 1.19.0
├── deno_runtime 0.45.0
│   └── deno 1.19.0
└── deno 1.19.0
```
I think we should also add a `actions-rs/audit-check` job in the CI workflow
> chore: bump nix to 0.23

- runtime/permissions.rs
`self.name` is being passed twice under different arguments
> chore: clean up #13695

- cli/tools/vendor/build.rs
- cli/tools/vendor/import_map.rs
See expected vs actual here: https://github.com/denoland/deno/issues/13708#issuecomment-1044638802
Closes #13708
> fix(vendor): do not add remote specifier with same origin to scopes

- .dprint.json
- tools/format.js
This PR uses dprint to orchestrate formatting via rustfmt.
Before: 6384ms
After: 932ms
> chore: use rustfmt cli via dprint for faster format

- cli/dts/lib.deno.ns.d.ts
- cli/dts/lib.deno.window.d.ts
- ext/web/lib.deno_web.d.ts
- ext/websocket/lib.deno_websocket.d.ts
Also this updates some more jsdoc that is not rendering well on hover in VS Code.
The compression examples are from the 1.19 release notes, thought it would be nice to add them in
> docs: add description + code example to `structuredClone`, `CompressionStream`, `DecompressionStream`

- cli/config_file.rs
- cli/lsp/language_server.rs
- cli/main.rs
- cli/proc_state.rs
- cli/schemas/config-file.v1.json
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/deno.import_map.jsonc
> feat: allow specification of import map in config file

- bench_util/Cargo.toml
- bench_util/benches/utf8.rs
- bench_util/src/js_runtime.rs
Benches for #13749
M1 baseline:
```
test bench_utf8_decode_12_b  ... bench:         204 ns/iter (+/- 13)
test bench_utf8_decode_12_kb ... bench:       3,189 ns/iter (+/- 1,049)
test bench_utf8_decode_12_mb ... bench:   1,430,887 ns/iter (+/- 29,186)
test bench_utf8_encode_12_b  ... bench:         433 ns/iter (+/- 13)
test bench_utf8_encode_12_kb ... bench:       5,786 ns/iter (+/- 693)
test bench_utf8_encode_12_mb ... bench:   4,946,268 ns/iter (+/- 118,515)
```
> bench: core.encode/decode

- cli/lsp/analysis.rs
- cli/lsp/client.rs
- cli/lsp/completions.rs
- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/mod.rs
- cli/lsp/performance.rs
- cli/lsp/registries.rs
- cli/lsp/repl.rs
- cli/lsp/tsc.rs
In #12968 `#[allow(unused)]` was added, but never removed.  Since then there is a significant amount of dead code and other things that have creeped into the whole of the lsp.  This PR cleans all that up.
> refactor: remove dead code from lsp

- cli/tools/upgrade.rs
> fix: move the permission check at the beginning of the upgrade process

- cli/tests/unit/tls_test.ts
- ext/net/02_tls.js
- ext/net/lib.deno_net.d.ts
- ext/net/ops_tls.rs
This PR adds `cert: string` and `key: string` options to `Deno.listenTls` and deprecates `certFile` and `keyFile` options.
You can specify the cert and private key from any source now. The read permission is checked only when `certFile` or `keyFile` is specified
closes #12639
> feat(ext/net): support cert, key options in listenTls

- cli/main.rs
- cli/standalone.rs
- cli/tests/integration/compile_tests.rs
- cli/tests/testdata/standalone_import_map.json
- cli/tests/testdata/standalone_import_map.ts
- cli/tools/standalone.rs
> fix(compile): Support import maps

- cli/tests/testdata/compiler_api_test.ts
- runtime/js/40_compiler_api.js
Noticed that `deno bundle` does seems to support data url:
```ts
PS> deno bundle "data:application/javascript;base64,Y29uc29sZS5sb2coImhlbGxvIHdvcmxkIik7"
Bundle data:application/javascript;base64,Y29uc29sZS5sb2coImhlbGxvIHdvcmxkIik7
// deno-fmt-ignore-file
// deno-lint-ignore-file
// This code was bundled using `deno bundle` and it's not recommended to edit it manually
console.log("hello world");
```
However when using it programmatically with `Deno.emit`, there is a `checkRelative` function which only support http(s)/file protocols, not the data one. It gets converted into a relative path instead of being passed as it.
Should close https://github.com/denoland/deno/issues/11141
> feat(compiler): support data url

- cli/config_file.rs
- cli/flags.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/with_config/deno.jsonc
- cli/tests/testdata/run/with_config/frontend_work.ts
- cli/tests/testdata/run/with_config/server_side_work.ts
This implements the idea proposed in #13744.
This PR disables the config auto-discovery when executing remote scripts (`deno run <remote_script>`)
closes #13744
> fix(cli): disable config discovery for remote script

- .github/workflows/ci.yml
```
google-github-actions/setup-gcloud is pinned at "master". We strongly advise against pinning to "@master" as it may be unstable. Please update your GitHub Action YAML from:
uses: 'google-github-actions/setup-gcloud@master'
to:
uses: 'google-github-actions/setup-gcloud@v0'
Alternatively, you can pin to any git tag or git SHA in the repository.
```
https://github.com/google-github-actions/setup-gcloud#-notices
> chore(ci): pin setup-gcloud to `v0` instead of `master`

- cli/schemas/config-file.v1.json
This PR adds the definition for the `"noImplicitOverride"` compiler option to the `deno.json` config file schema so it can be auto-completed in VS Code.
The definition was taken from http://json.schemastore.org/tsconfig, as mentioned in the original issue #11885. Related issue about possibly enabling `"noImplicitOverride"` by default: #11836.
> chore: Add "noImplicitOverride" to config-file.v1.json

- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
This logs more for #13657.
We're pretty sure that the issue is a closed document's `line_index` is getting out of date. Fixing it would require a bit of an overhaul (I believe it would require keeping filesystem files in memory for the duration of a request if requested), so just want to be sure this is indeed the case.
> chore(lsp): log more for "unexpected positions" lsp error

- cli/bench/deno_common.js
Benchmark for #13838 
M1:
```
base64_roundtrip:       n = 10, dt = 1.224s, r = 8/s, t = 122400000ns/op
```
quite slow...
> bench: add base64 roundtrip

- ext/net/ops.rs
- ext/net/ops_tls.rs
After a first attempt in solving #1195 in #13794, it has been noticed that the **SO_REUSEADDR** option has to be defaulted to true in order to pass the `net` unit tests. In the same PR was proposed to do the porting to Socket2 and the support to the options **SO_REUSEADDR** and **SO_REUSEPORT** in two separate PR. This PR presents the TcpListener implementation based on Socket2.
It is possible to notice that:
1. the **SO_REUSEADDR** option is defaulted to true only for non-windows systems, following the implementation of `TcpListener.bind()` of [std::net](https://github.com/rust-lang/rust/blob/6343edfa11c80ffed02de7e059178d4c1637ecdb/library/std/src/sys_common/net.rs)
2. similarly, the socket type is set to `SOCK_STREAM` and the `backlog` argument of `listen()` is set to 128
These steps …
> feat(ext/net): Use Socket2 crate to create TcpListener

- .github/workflows/ci.yml
- ext/web/05_base64.js
- ext/web/lib.rs
Follow up to https://github.com/denoland/deno/pull/13839, optimizing `base64_roundtrip` ~20x (~125ms => ~6.5ms)
Before:
```
base64_roundtrip:    	n = 100, dt = 12.493s, r = 8/s, t = 124930000ns/op
```
After:
```
base64_roundtrip:    	n = 100, dt = 0.649s, r = 154/s, t = 6490000ns/op
```
> perf(ext/web): optimize atob/btoa

- cli/bench/deno_common.js
```
b64_rt_long:         	n = 10, dt = 0.072s, r = 139/s, t = 7200000ns/op
b64_rt_short:        	n = 1000000, dt = 0.548s, r = 1824818/s, t = 548ns/op
```
> bench(common): base64 short strings

- serde_v8/benches/de.rs
- serde_v8/benches/ser.rs
- serde_v8/src/de.rs
- serde_v8/src/error.rs
- serde_v8/tests/de.rs
Before:
```
test de_bstr_v8_1024_b    ... bench:          67 ns/iter (+/- 1)
test de_bstr_v8_12_b      ... bench:          38 ns/iter (+/- 1)
```
After:
```
test de_bstr_v8_1024_b    ... bench:          50 ns/iter (+/- 2)
test de_bstr_v8_12_b      ... bench:          33 ns/iter (+/- 0)
```
> perf(serde_v8): optimize ByteString deserialization

- serde_v8/src/serializable.rs
For common return types such as String/ZeroCopyBuf/ByteString
This should impact many ops, but here's the delta on b64 from `deno_common.js`:
Before:
```
b64_rt_long:         	n = 100, dt = 0.656s, r = 152/s, t = 6560000ns/op
b64_rt_short:        	n = 1000000, dt = 0.524s, r = 1908397/s, t = 524ns/op
```
After:
```
b64_rt_long:         	n = 100, dt = 0.632s, r = 158/s, t = 6320000ns/op
b64_rt_short:        	n = 1000000, dt = 0.456s, r = 2192982/s, t = 456ns/op
```
> perf(serde_v8): avoid SerializablePkg allocs

- .github/CODEOWNERS
Adding myself as a "code owner" / "default reviewer" to `core/` since I'm familiar with the op-layer and other parts of core.
> chore(CODEOWNERS): add @AaronO on core/

- core/ops.rs
- core/ops_metrics.rs
Relative to #13864
```
Before:
test bench_is_proxy   ... bench:      20,292 ns/iter (+/- 480)
test bench_op_async   ... bench:     385,609 ns/iter (+/- 5,775)
test bench_op_nop     ... bench:      46,042 ns/iter (+/- 1,785)
test bench_op_pi_json ... bench:      49,903 ns/iter (+/- 668)
After:
test bench_is_proxy   ... bench:      20,428 ns/iter (+/- 1,292)
test bench_op_async   ... bench:     386,556 ns/iter (+/- 6,006)
test bench_op_nop     ... bench:      44,772 ns/iter (+/- 1,313)
test bench_op_pi_json ... bench:      48,357 ns/iter (+/- 1,299)
```
Yes, it's only ~1.5ns but that will be 5% of sync-op overhead following #13861
> perf(core): micro-optimize OpsTracker

- Cargo.lock
- cli/Cargo.toml
- runtime/Cargo.toml
- test_util/Cargo.toml
https://blog.rust-lang.org/2022/03/08/cve-2022-24713.html
> chore: update regex to 1.5.5

- cli/ops/testing.rs
- cli/tools/test.rs
Prompted by https://github.com/denoland/deno/pull/13713#discussion_r821825930
> refactor(test): use tokio::sync::mpsc::unbounded_channel

- cli/main.rs
- cli/tests/testdata/041_info_flag.out
- cli/tests/testdata/041_info_flag_location.out
Should fix #13076 so stuff this like:
```
DENO_DIR location: "C:\\Users\\GJZwiers\\AppData\\Local\\deno"
```
becomes:
```
DENO_DIR location: C:\Users\GJZwiers\AppData\Local\deno
```
But I'm not sure how to write a test, because it's using `[WILDCARD]`
> fix(info): print output with unescaped backslashes on windows

- ext/crypto/01_webidl.js
- ext/crypto/lib.deno_crypto.d.ts
as per https://w3c.github.io/webcrypto/#webidl-410131068
currently, universal code referencing the `EcKeyImportParams` interface doesn't work
```
Uncaught TypeError: TS2304 [ERROR]: Cannot find name 'EcKeyImportParams'
```
> fix(ext/crypto): use EcKeyImportParams dictionary

- cli/tests/unit/opcall_test.ts
- cli/tests/unit/ref_unref_test.ts
- cli/tests/unit/test_util.ts
- cli/tests/unit/timers_test.ts
- core/01_core.js
- core/bindings.rs
This PR adds the wrappers of the existing `core.refOp` and `core.unrefOp`, and checks if the given promise ids are valid.
Currently we don't check whether the promise id is valid or not. If a wrong promise id is given to `core.unrefOp`, that id remains in pending_ops vector, and causes the exit condition incorrect (Deno program can exit with valid ops still remaining).
---
This implements the idea by @andreubotella in the comment https://github.com/denoland/deno/pull/12889#discussion_r756966729
> refactor(core): validate promise id in refOp

- Cargo.lock
- cli/Cargo.toml
- test_util/Cargo.toml
The tasks were flaky. Now it's been rewritten to use os pipes so when it writes to stdout it will write directly to that pipe instead of through a series of tokio channels.
> chore(test): fix flaky tasks

- cli/tests/integration/task_tests.rs
- cli/tests/testdata/task/task_exit_code_5.out
- cli/tools/task.rs
Logs task name and associated script with additional args. 
This is disabled if "--quiet/-q" flag is present.
```
// before:
$ deno task exit_code_5 
10
// after:
$ deno task exit_code_5
Task exit_code_5 echo $(echo 10 ; exit 2) && exit 5
10
```
> feat(task): log task script

- Cargo.lock
- ext/fetch/Cargo.toml
- ext/tls/Cargo.toml
I fixed a bug about proxy for reqwest, in addition to v0.11.10 there is also an other fix.
Pr https://github.com/seanmonstar/reqwest/pull/1491 : fix basic-auth for access http over https's proxy
Changelog: https://github.com/seanmonstar/reqwest/blob/master/CHANGELOG.md#v01110
> fix: upgrade reqwest to 0.11.10

- Cargo.lock
- cli/Cargo.toml
- test_util/Cargo.toml
- test_util/src/lib.rs
If the assertion string doesn't contain "[WILDCARD]" then it uses `pretty_assertions::assert_eq` for better output.
> chore(test_util): use pretty_assertions when not pattern matching

- Cargo.lock
- cli/Cargo.toml
- cli/tests/integration/task_tests.rs
- cli/tests/testdata/task/task_exit_code_5.out
- cli/tests/testdata/task/task_non_existent.out
- cli/tools/task.rs
Moving `deno task` to unstable. This will allow us to validate the approach before stabilizing it.
> feat(task): add unstable warning to `deno task`

- cli/bench/deno_common.js
- ext/web/09_file.js
70% faster than Node (24ms)
50% faster than Bun (14ms)
(above numbers taken from https://twitter.com/jarredsumner/status/1503888103227867136)
Before:
```
blob_text_large:     	n = 3, dt = 2.123s, r = 1/s, t = 707666666ns/op
```
After:
```
blob_text_large:     	n = 3, dt = 0.021s, r = 143/s, t = 7000000ns/op
```
Closes #13973
> perf(web): use DOMString for BlobParts

- .github/workflows/ci.yml
We had two successive main branch failures related to this.
- https://github.com/denoland/deno/runs/5566541876?check_suite_focus=true
- https://github.com/denoland/deno/runs/5566531944?check_suite_focus=true
> chore: uploading WPT shouldn't make CI fail

- cli/bench/deno_common.js
- ext/web/09_file.js
```
blob_text_large:     	n = 100, dt = 0.655s, r = 153/s, t = 6550000ns/op
```
> perf(web): optimize Blob.text and Blob.arrayBuffer

- cli/build.rs
Better error message than a confusing runtime error (as seen in https://github.com/denoland/deno/issues/13948 & https://github.com/denoland/deno/issues/4862) until https://github.com/denoland/deno/issues/13948 is solved
> chore(cli): Disallow cross compiling for snapshots

- tools/release/01_bump_crate_versions.ts
- tools/release/02_publish_crates.ts
- tools/release/deno_workspace.ts
- tools/release/deps.ts
Fixes the issue we saw with the last release.
This is the output now:
```
Setting deno to 1.20.1...      
Set version to 1.20.1
Setting deno_core to 0.124.0...
Setting serde_v8 to 0.35.0...
Setting deno_ops to 0.2.0... 
Setting deno_bench_util to 0.36.0...
Setting deno_runtime to 0.50.0...   
Setting deno_webstorage to 0.37.0...
Setting deno_web to 0.73.0...
Setting deno_webidl to 0.42.0...
Setting deno_url to 0.42.0...
Setting deno_websocket to 0.47.0...
Setting deno_tls to 0.29.0...
Setting deno_webgpu to 0.43.0...
Setting deno_net to 0.34.0...
Setting deno_http to 0.36.0...
Setting deno_ffi to 0.29.0...
Setting deno_fetch to 0.65.0...
Setting deno_crypto to 0.56.0...
Setting deno_console to 0.42.0...
Setting deno_broadcast_channel to 0.36.0...
```
Previously (deno_ops missing):
``` …
```
> chore: release script should automatically figure out CLI crate dependencies

- cli/schemas/config-file.v1.json
We accidentally missed this when adding support for having colons.
> fix(config-file): config-file.v1.json schema should allow colons in the task name

- cli/tests/testdata/workers/test.ts
- ops/lib.rs
```
> Deno.core.opSync("op_base64_atob", 1)
Uncaught TypeError: Error parsing args at position 1: serde_v8 error: ExpectedString
at Object.opSync (deno:core/01_core.js:174:38)
at <anonymous>:2:11
```
> chore(ops): include argument position in serde_v8 errors

- core/ops_builtin.rs
Since OpState-like args are optional since: https://github.com/denoland/deno/pull/13954
> cleanup(core): drop op_void_async's state arg

- ext/http/lib.rs
When checking if header matches a "special" header (that impacts our body handling, etc...)
[make_ascii_lowercase](https://doc.rust-lang.org/std/string/struct.String.html#method.make_ascii_lowercase) could also make sense here
Unfortunately there's a lot of variance in our tests and it's not fully formalized but I do observe a 1-3% improvement in throughput (sampled over 3 runs):
```
Before (1.20.1)
Requests/sec: 126285.80
Requests/sec: 127775.95
Requests/sec: 128875.33
After (this PR):
Requests/sec: 130615.10
Requests/sec: 129957.80
Requests/sec: 129056.16
```
> perf(http): avoid per header alloc

- .cargo/config
- .github/workflows/ci.yml
- cli/tests/integration/run_tests.rs
- runtime/ops/signal.rs
Fixes some local development issues that have creeped up over the past few weeks on Windows.
Closes #14014
> chore: fix development issues on Windows

- core/01_core.js
- core/runtime.rs
To allow opcalls with more than 2 generic-args JS-side
> fix(core): variadic opSync/opAsync

- cli/tests/integration/compile_tests.rs
- cli/tests/integration/install_tests.rs
- cli/tools/installer.rs
> fix: do not use global env vars in install tests

- cli/tests/integration/bundle_tests.rs
- cli/tests/integration/coverage_tests.rs
- cli/tests/integration/fmt_tests.rs
- cli/tests/integration/info_tests.rs
- cli/tests/integration/inspector_tests.rs
- cli/tests/integration/install_tests.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/integration/run_tests.rs
- cli/tests/integration/watcher_tests.rs
Didn't bother with other test blocks yet.
> chore: replace `.expect("...")` calls with `.unwrap()` in integration test code

- core/runtime.rs
This note about how `v8::SnapshotCreator::create_blob` must not be called from a `HandleScope` stopped being relevant in #6801, and was now attached to code that had nothing to do with `HandleScope`s.
> chore(core): Remove a note that is no longer relevant.

- cli/compat/esm_resolver.rs
Hey,
I've noticed that `esm_resolver.rs` uses `.collect::<Vec<_>>().join("");` over `.collect::<String>();`, the latter being shorter, clearer and more performant:
```rs
criterion.bench_function("1", |bencher| {
bencher.iter(|| {
let url = "https://google.com".to_owned();
let split_specifier = url.as_str().split(':');
split_specifier.skip(1).collect::<String>();
})
});
criterion.bench_function("2", |bencher| {
bencher.iter(|| {
let url = "https://google.com".to_owned();
let split_specifier = url.as_str().split(':');
split_specifier.skip(1).collect::<Vec<_>>().join("");
})
});
```
```
1                       time:   [61.874 ns 61.959 ns 62.071 ns]                   
Found 14 outliers among 100 measurements (14.00%)
4 (4.00%) high mild
10 (10.00%) high severe
slope  [61.874 ns 62.071 ns] …
```
> fix(compat): Changes an instance of `collect::<Vec<_>>().join("")` to `collect::<String>()`

- ext/http/01_http.js
`main`:
```
Total:	12.3348 secs
Slowest:	0.0204 secs
Fastest:	0.0000 secs
Average:	0.0006 secs
Requests/sec:	81071.3752
Total data:	11000000 bytes
Size/request:	11 bytes
Running 10s test @ http://127.0.0.1:4500
2 threads and 20 connections
Latency   174.66us  304.76us  16.45ms   99.61%
Req/Sec    57.23k     3.04k   59.21k    92.08%
1150126 requests in 10.10s, 120.65MB read
Requests/sec: 113858.76
Transfer/sec:     11.94MB
```
This PR:
```
Total:	12.1141 secs
Slowest:	0.0198 secs
Fastest:	0.0000 secs
Average:	0.0006 secs
Requests/sec:	83548.1332
Total data:	11000000 bytes
Size/request:	11 bytes
Running 10s test @ http://127.0.0.1:4500
2 threads and 20 connections
Latency   161.29us   33.76us …
```
> perf(http): avoid checking promise every request

- ext/http/01_http.js
- ext/http/lib.rs
`main`:
```
Total:	12.3944 secs
Slowest:	0.0216 secs
Fastest:	0.0000 secs
Average:	0.0006 secs
Requests/sec:	80681.7978
Total data:	11000000 bytes
Size/request:	11 bytes
```
This PR:
```
Summary:
Total:	11.8821 secs
Slowest:	0.0116 secs
Fastest:	0.0000 secs
Average:	0.0006 secs
Requests/sec:	84160.5187
Total data:	11000000 bytes
Size/request:	11 bytes
```
JS benchmark: [here](https://perf.link/#eyJpZCI6Inh1Y3V3NW4waGN4IiwidGl0bGUiOiIiLCJiZWZvcmUiOiIvLyBMYXJnZSBudW1iZXIgb2Ygcmlkcy5cbmNvbnN0IHJpZHMgPSBuZXcgU2V0KFsxLDIsMyw0LDUsNiw3LDgsOSwxMCwxMSwxMiwxMywxNCwxNSwxNiwxNywxOCwxOSwyMCwyMSwyMiwyMywyNCwyNSwxLDIsMyw0LDUsNiw3LDgsOSwxMCwxMSwxMiwxMywxNCwxNSwxNiwxNywxOCwxOSwyMCwyMSwyMiwyMywyNCwyNSwxLDIsMyw0LDUsNiw3LDgsOSwxMCwxMSwxMiwxMywxNCwxNSwxNiwxNywxOCwxOSwyMCwyMSwyMiwyMywyNCwyNSwxLDIsMyw0LDUsNiw3LD …
> perf(http): avoid Set.has() when closing connection resource

- ext/fetch/lib.deno_fetch.d.ts
Deno's fetch and lib.dom's fetch have slightly different declarations. (Deno's fetch accept URL as the first arg, but lib.dom's fetch doesn't)
We should align Deno's declaration to lib.dom's (spec defines first arg as `typedef (Request or USVString) RequestInfo` [ref](https://fetch.spec.whatwg.org/#requestinfo)) to reduce the confusion.
This PR tries to deprecate Deno-only signature of fetch function.
With this change, fetch with URL call gets strikethrough style in vscode like the below
> fix: deprecate URL as the first arg of fetch

- Cargo.lock
- ext/webstorage/Cargo.toml
This allows users of deno to use a more recent version.
> chore: update rusqlite

- core/bindings.rs
- core/extensions.rs
`main`:
```
test bench_utf8_decode_12_b  ... bench:         187 ns/iter (+/- 12)
test bench_utf8_decode_12_kb ... bench:       4,589 ns/iter (+/- 676)
test bench_utf8_decode_12_mb ... bench:   1,502,699 ns/iter (+/- 28,120)
test bench_utf8_encode_12_b  ... bench:         450 ns/iter (+/- 42)
test bench_utf8_encode_12_kb ... bench:       5,586 ns/iter (+/- 295)
test bench_utf8_encode_12_mb ... bench:   4,767,425 ns/iter (+/- 9,069)
```
This PR:
```
test bench_utf8_decode_12_b  ... bench:         176 ns/iter (+/- 3)
test bench_utf8_decode_12_kb ... bench:       3,268 ns/iter (+/- 80)
test bench_utf8_decode_12_mb ... bench:   1,441,622 ns/iter (+/- 19,107)
test bench_utf8_encode_12_b  ... bench:         354 ns/iter (+/- 15)
test bench_utf8_encode_12_kb ... bench:       5,401 ns/iter (+/- …
```
> perf: micro-optimize core.encode 

- ext/fetch/lib.deno_fetch.d.ts
#14113 broke https://deno.land/x/download@v1.0.1/download.ts. The overload accepting `URL` should be all-inclusive or it won't accept an argument of type `string | URL`.
cc @kt3k
> fix(lib.deno_fetch.d.ts): Extend deprecated fetch() overload

- Cargo.lock
- cli/Cargo.toml
ref: https://github.com/denoland/deno_task_shell/pull/28
> fix(task): handle `PATHEXT` with trailing semi-colon

- .dprint.json
I changed the interface between the dprint CLI and process plugins in a breaking way, so this will cause Rust files to be formatted automatically in my editor again with the dprint vscode extension and the latest dprint installed.
> chore: update dprint internally to 0.24.1

- cli/main.rs
- cli/tests/integration/compile_tests.rs
- cli/tools/standalone.rs
Moves what this test was originally designed for to a lower level unit test.
Closes #14103
> chore: fix compile_windows_ext test

- cli/config_file.rs
- cli/lsp/capabilities.rs
- cli/lsp/language_server.rs
- cli/lsp/lsp_custom.rs
- cli/tests/integration/lsp_tests.rs
Closes: #13910
This add the `denoConfigTasks` experimental capability which handles a `deno/task` request from the client, which responds with an array of tasks from the current configuration file.
Clients need to implement surfacing them to the user, such as with denoland/vscode_deno#641.
> feat(lsp): support API for config file

- cli/emit.rs
- cli/flags.rs
- cli/main.rs
- cli/ops/runtime_compiler.rs
- cli/proc_state.rs
- cli/tools/bench.rs
- cli/tools/installer.rs
- cli/tools/standalone.rs
- cli/tools/test.rs
Working on https://github.com/denoland/deno/pull/14072 it became confusing to have `CheckFlag` and `CheckFlags`. I believe `TypecheckMode` is a better name than `CheckFlag`. 
Also renamed `Flags.check` to `Flags.typecheck_mode` and `CheckOptions.check` to `CheckOptions.typecheck_mode`.
> refactor(flags): rename CheckFlag to TypecheckMode

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
- cli/lockfile.rs
- cli/lsp/language_server.rs
- cli/tools/coverage/mod.rs
- cli/tools/fmt.rs
- test_util/src/lib.rs
Upgrades to the new API. This actually has some perf improvements and a bug fix that won't matter to most people.
> chore: upgrade dprint-core to 0.54.1

- cli/lsp/language_server.rs
I'll follow up with another PR that adds tests. I'm working on it, but it's a larger change. Just want to fix the flaky CI right now.
https://github.com/denoland/deno/pull/14146#discussion_r837814179
I'm not categorizing this as a "fix" because it doesn't need to be in the release notes.
> chore(ci): fix flaky lsp bench due to notification that was accidentally added

- cli/tests/unit/webgpu_test.ts
WSL doesn't have good support for GPU so we should disable these tests for it.
Closes #14152.
> chore: disable wgpu tests in WSL

- core/extensions.rs
- core/runtime.rs
- ops/lib.rs
`#[op(unstable)]` tags `OpDecl::is_unstable` as `true`, thus allowing op-middleware to then disable said ops
This should make unstable checks less error prone (forgotten or overlooked during review/impl), less verbose and moderately faster (check happens at runtime init vs each call)
> feat(ops): #[op(unstable)]

- ext/url/00_url.js
- ext/url/lib.rs
Get's rid of serde derives and the unwind handler that's no longer needed. No significant improvement in `new URL` performance. 
EDIT: `op_url_reparse` is 10% faster.
> chore(ext/url): cleanup url ops

- ext/webstorage/01_webstorage.js
- ext/webstorage/lib.rs
LLVM lines:
Before:
```
30266 (100%)  1169 (100%)  (TOTAL)
```
After:
```
29252 (100%)  1150 (100%)  (TOTAL)
```
> chore(ext/webstorage): custom arity

- cli/tests/testdata/workers/test.ts
- core/01_core.js
- core/bindings.rs
- core/examples/hello_world.rs
- core/lib.rs
- core/ops.rs
- core/runtime.rs
- ops/lib.rs
Avoiding need for js-visible OpIDs, alternative to https://github.com/denoland/deno/pull/14224
The core idea is that each op is provided with a single pointer providing its relevant rust-side context, what it points to may change (e.g: we might get rid of explicit op_ids and track OpMetrics in the ctx) and how we pass it will likely evolve from using the callback's data to a JS-side External 1st arg for Fast API callables
Moderate improvement of `op_baseline`:
```
Before:
test bench_is_proxy   ... bench:      17,695 ns/iter (+/- 487)
test bench_op_async   ... bench:     277,137 ns/iter (+/- 10,404)
test bench_op_nop     ... bench:      19,595 ns/iter (+/- 1,267)
test bench_op_pi_json ... bench:      23,339 ns/iter (+/- 1,257)
After:
test bench_is_proxy   ... bench:      17,738 ns/iter …
```
> refactor(core): OpCtx

- .github/workflows/cargo_publish.yml
- .github/workflows/version_bump.yml
- tools/cut_a_release.md
- tools/release/01_bump_crate_versions.ts
- tools/release/04_post_publish.ts
Some issues I found along the way. Slowly getting there.
> chore: update release instructions based on 1.20.5 release

- serde_v8/de.rs
- serde_v8/error.rs
- serde_v8/tests/de.rs
Fixes #14128
**Note:** we may want to return out-of-range errors, for now I've preserved the saturating behaviour (which wasn't previously consistent ...)
> fix(serde_v8): more robust number deserialization

- cli/fmt_errors.rs
- cli/source_maps.rs
- core/error.rs
- core/runtime.rs
- ext/web/02_event.js
- runtime/web_worker.rs
Closes #13212. Also adds `message` and `name` fields to make `Deno.core.destructureError()` nicer to use.
> refactor(core/error): Clarify JsError message fields

- cli/Cargo.toml
- cli/lsp/testing/execution.rs
- cli/ops/testing.rs
- cli/tests/integration/mod.rs
- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/steps/output_within.out
- cli/tests/testdata/test/steps/output_within.ts
- cli/tools/test.rs
- core/resources.rs
- runtime/js/40_testing.js
Closes https://github.com/denoland/deno/issues/14192
This commit changes "deno test" to better denote user output coming
from test cases. 
This is done by printing "---- output ----" and "---- output end ----" 
markers if an output is produced. The output from "console" and 
"Deno.core.print" is captured, as well as direct writes to "Deno.stdout"
and "Deno.stderr".
To achieve that new APIs were added to "deno_core" crate, that allow
to replace an existing resource with a different one (while keeping resource
ids intact). Resources for stdout and stderr are replaced by pipes.
> feat(test): format user code output

- cli/ops/bench.rs
- cli/ops/testing.rs
- cli/tests/integration/bench_tests.rs
- cli/tests/integration/test_tests.rs
- cli/tests/testdata/bench/recursive_permissions_pledge.js
- cli/tests/testdata/test/recursive_permissions_pledge.js
This commit fixes and edge case, where testing/benching code could pledge new
permission set before restoring the previous pledge. 
Appropriate panics were added and tests that assert that process is killed
in case of "recursive pledge".
> fix: panic when trying to pledge permissions before restoring previous pledge

- cli/lsp/testing/execution.rs
- cli/tests/testdata/test/aggregate_error.out
- cli/tests/testdata/test/exit_sanitizer.out
- cli/tests/testdata/test/fail.out
- cli/tests/testdata/test/fail_fast.out
- cli/tests/testdata/test/finally_timeout.out
- cli/tests/testdata/test/steps/failing_steps.out
- cli/tests/testdata/test/steps/invalid_usage.out
- cli/tools/test.rs
This commit changes "deno test" to filter out stack frames if it is beneficial to the user.
This is the case when there are stack frames coming from "internal" code
below frames coming from user code.
Co-Authored-By: Nayeem Rahman <nayeemrmn99@gmail.com>
> feat(test): skip internal stack frames for errors

- cli/file_watcher.rs
We need to ensure this works if the `recv()` never completes due to being used in a `tokio::select`
> fix: `--watch` was losing items

- cli/main.rs
- cli/tests/testdata/future_check1.out
It has good intentions, but it is a really terrible user experience. As
such we shouldn't print this warning.
> Remove the DENO_FUTURE_CHECK warning

- .github/workflows/ci.yml
- core/examples/http_bench_json_ops.rs
- core/resources.rs
- ext/fetch/lib.rs
- ext/http/lib.rs
- ext/net/io.rs
- ext/net/ops_tls.rs
- runtime/ops/io.rs
- serde_v8/magic/buffer.rs
Fixes https://github.com/denoland/deno/pull/14284#discussion_r854101629
Comes with a performance penalty but still faster than Deno 1.20.6 and Node:
```
wrk -t8 -c20 -d10s http://localhost:8080/sample.txt
Running 10s test @ http://localhost:8080/sample.txt
8 threads and 20 connections
Latency    16.64ms    1.62ms  39.96ms   83.43%
Req/Sec   120.46      9.53   141.00     76.24%
9695 requests in 10.10s, 47.41GB read
Requests/sec:    959.93
Transfer/sec:      4.69GB
```
> core: introduce `resource.read_return`

- cli/tests/integration/repl_tests.rs
- cli/tools/repl/session.rs
This commit adds a `clear()` function in the REPL which works similar to `console.clear()`.
Fixes: https://github.com/denoland/deno/issues/14226
> feat(repl): add global clear() function

- Cargo.lock
- cli/tests/unit/http_test.ts
- ext/http/Cargo.toml
- ext/http/lib.rs
- serde_v8/magic/buffer.rs
This commit adds support for auto response body compression for
streaming bodies.
Alternative to https://github.com/denoland/deno/tree/compression_stream
that uses `async_compression` and tokio's io traits.
cc @AaronO @satyarohith 
Fixes #13835
> feat(ext/http): stream auto resp body compression

- tools/release/01_bump_crate_versions.ts
The instructions say to do a deno_std release first and then start with the deno release, but when someone doesn't do that make sure the deno_std version gets bumped anyway.
This just now always increments the minor version.
> chore(scripts): allow running version_bump workflow without releasing deno_std yet

- .github/workflows/ci.yml
Will hopefully fix: https://github.com/denoland/deno/runs/6105288097?check_suite_focus=true
Closes #13589
> chore(ci): skip ci cache when doing a release

- cli/tests/integration/bench_tests.rs
- cli/tests/testdata/bench/multifile_summary.out
- cli/tools/bench.rs
This commit fixes previous file benchmarks leaking into the next file benchmarks summary.
fixes #14354
> fix(bench): reset reporter context

- cli/tests/unit/http_test.ts
`curl -I` closes the connection after headers have arrived, but we want it to
also receive the body (even if we don't use it), so the server doesn't encounter
an unexpected EOF. To do this we now use `curl -i`.
> tests: unflake streaming compression tests

- cli/tests/integration/repl_tests.rs
This test doesn't run on the CI so it could only be seen failing locally.
> chore(tests): fix pty_clear_function on Windows

- ext/fetch/22_http_client.js
- ext/fetch/26_fetch.js
- ext/fetch/lib.rs
- ops/lib.rs
LLVM lines:
Before:
```
48968 (100%)  2038 (100%)  (TOTAL)
```
After:
```
48163 (100%)  2018 (100%)  (TOTAL)
```
> chore(ext/fetch): custom arity

- Cargo.lock
- ext/http/lib.rs
- serde_v8/Cargo.toml
- serde_v8/benches/de.rs
- serde_v8/de.rs
- serde_v8/magic/buffer.rs
- serde_v8/magic/string_or_buffer.rs
- serde_v8/ser.rs
- serde_v8/tests/de.rs
```
Before:
test de_sob_buf_16kb      ... bench:         597 ns/iter (+/- 16)
test de_sob_buf_1b        ... bench:          90 ns/iter (+/- 3)
test de_sob_buf_1kb       ... bench:         169 ns/iter (+/- 3)
test de_sob_buf_512kb     ... bench:      23,829 ns/iter (+/- 441)
test de_sob_str_1kb       ... bench:         555 ns/iter (+/- 6)
test de_sob_str_6b        ... bench:          76 ns/iter (+/- 0)
After:
test de_sob_buf_16kb      ... bench:          32 ns/iter (+/- 1)
test de_sob_buf_1b        ... bench:          32 ns/iter (+/- 2)
test de_sob_buf_1kb       ... bench:          32 ns/iter (+/- 1)
test de_sob_buf_512kb     ... bench:          32 ns/iter (+/- 2)
test de_sob_str_1kb       ... bench:         465 ns/iter (+/- 14)
test de_sob_str_6b        ... bench:          48 ns/iter (+/- …
```
> perf(serde_v8): zero-copy StringOrBuffer

- ext/http/lib.rs
Brings back the nice juicy numbers seen in https://github.com/denoland/deno/pull/14284
sample.txt is 5MB
`main`:
```
wrk -t8 -c20 -d10s http://localhost:8080/sample.txt
Running 10s test @ http://localhost:8080/sample.txt
8 threads and 20 connections
Latency    38.43ms    4.80ms  83.32ms   91.27%
Req/Sec    51.87      9.99    60.00     62.87%
4192 requests in 10.10s, 20.53GB read
Requests/sec:    414.91
Transfer/sec:      2.03GB
```
This PR:
```
Running 10s test @ http://localhost:8080/sample.txt
8 threads and 20 connections
Latency    17.58ms    2.53ms  44.05ms   88.56%
Req/Sec   114.07     12.06   141.00     67.20%
9179 requests in 10.10s, 44.87GB read
Requests/sec:    908.86
Transfer/sec: …
```
> perf(ext/http): fast path for uncompressed bodies

- cli/dts/lib.deno.ns.d.ts
- cli/tests/unit/console_test.ts
- ext/console/02_console.js
Implements an option on `Deno.inspect` to set the maximum string size before it is truncated with an ellipsis.
This is required to fix [this issue in denoland/deno_std](https://github.com/denoland/deno_std/issues/2140).
> feat(ext/console): Add string abbreviation size option for "Deno.inspect"

- cli/lsp/analysis.rs
- cli/lsp/code_lens.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/compiler.d.ts
The total size of the assets stored in the TS isolate is 0.7MB. I think it's worth it to store these up front in the Rust code when initializing because it simplifies the code a decent amount.
1. Removes the concept of "cached assets" vs "uncached assets" (reduces the chance of making a mistake as well)
2. Gets rid of a lot of asyncness
> refactor(lsp): store all the assets in Rust when initializing

- Cargo.lock
- ext/http/Cargo.toml
- runtime/Cargo.toml
Bump & release `deno_http` v0.43.1
> chore: deno_http v0.43.1

- runtime/js/40_process.js
- runtime/ops/io.rs
- runtime/ops/process.rs
- runtime/ops/spawn.rs
I was confused by this code while working on piping process output to test output so I refactored it. Makes #14395 a lot easier too.
> refactor(ops/process): add `StdioOrRid` enum

- core/error.rs
- core/modules.rs
- core/runtime.rs
> refactor(core): Remove ErrWithV8Handle

- cli/tests/integration/repl_tests.rs
Needs windows and unix specific assertions.
> chore: fix pty_complete_imports test

- cli/tools/fmt.rs
All links on git.io will stop redirecting after April 29, 2022.
- https://github.blog/changelog/2022-04-25-git-io-deprecation/
> chore: remove git.io

- cli/flags.rs
- cli/lsp/testing/execution.rs
When someone runs:
```
deno task node:test -- test-assert.js
```
It should forward everything after the task name like so:
```
Task node:test deno test --unstable --allow-all node/_tools/test.ts "--" "test-assert.js"
```
Currently it does:
```
Task node:test deno test --unstable --allow-all node/_tools/test.ts "test-assert.js"
```
> fix: `deno task` should forward double hyphens

- cli/dts/lib.dom.d.ts
- cli/dts/lib.dom.extras.d.ts
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/lib_dom_extras.ts
- cli/tests/testdata/lib_dom_extras.ts.out
- cli/tsc.rs
- tools/update_typescript.md
Closes: #12558
Fixes: #14344
This adds the `lib.dom.extras.d.ts` file and modifies the `lib.dom.d.ts` file to include it.  This solves the problem where users use the `lib: ["dom", "deno.ns"]` configuration when compiling their isomorphic TypeScript and the distributed version of the DOM library does not include every web standard API that Deno supports, and therefore causes confusing errors to the user.
This means we do make a one line edit to the distributed `lib.dom.d.ts` to include `lib.dom.extras.d.ts`.  This means that users don't have to explicitly include `"dom.extras"` when using the library, so for most users previous errors will just "go away".
This does establish a pattern now where we can add items Deno supports in advance of the TypeScript distribution supporting it while …
> fix(cli): add dom.extras lib

- cli/flags.rs
It didn't support fowrading a lone double hypen:
```
deno task my_task --
```
> fix(task): support forwarding lone double hyphen

- cli/tests/unit/files_test.ts
- runtime/ops/fs.rs
Fixes #14454, a regression from #14261
This now matches the behaviour of `1.21.0` and below
> fix(runtime): lossy utf8 readTextFile

- cli/tools/vendor/build.rs
- cli/tools/vendor/import_map.rs
I tried to vendor something for debugging purposes today and got a panic with jspm because it had some relative specifiers that looked like this:
```
import _regex2 from './npm:uc.micro@1.0.6/categories/Cc/regex!cjs';
```
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: windows x86_64
Version: 1.21.1
Args: ["C:\\Users\\david\\AppData\\Local\\bvm\\binaries\\denoland\\deno\\1.21.1\\bin\\deno.exe", "vendor", "--force", "_config.ts"]
thread 'main' panicked at 'Could not find local path for …
```
> fix(vendor): do not panic on relative specifier with scheme-like folder name

- .github/workflows/ci.yml
- cli/fmt_errors.rs
- cli/ops/errors.rs
- core/02_error.js
- core/bindings.rs
- core/error.rs
- core/ops_builtin.rs
- runtime/js/40_error_stack.js
- runtime/js/99_main.js
Closes https://github.com/denoland/deno/issues/14464
This commit moves "op_format_location" to "core/ops_builtin.rs"
and removes "Deno.core.createPrepareStackTrace" in favor of
"Deno.core.prepareStackTrace".
> refactor: add core.formatLocationFilename, remove op_format_filename

- Cargo.lock
- cli/Cargo.toml
- cli/dts/lib.deno.ns.d.ts
- cli/tests/integration/mod.rs
- cli/tests/testdata/resolve_dns.ts
- cli/tests/testdata/resolve_dns.ts.out
- ext/net/Cargo.toml
- ext/net/ops.rs
Adding `NS` DNS record using `Name` struct. For resolving name server record to delegates a DNS zone to use the given with [RFC 1035](https://datatracker.ietf.org/doc/html/rfc1035#page-12).
Closes #14355
> feat(ext/net): add `NS` DNS record support

- cli/tests/testdata/compat/test_runner/cjs.out
- cli/tests/testdata/compat/test_runner/esm.out
- cli/tests/testdata/test/aggregate_error.out
- cli/tests/testdata/test/allow_none.out
- cli/tests/testdata/test/exit_sanitizer.out
- cli/tests/testdata/test/fail.out
- cli/tests/testdata/test/fail_fast.out
- cli/tests/testdata/test/fail_fast_with_val.out
- cli/tests/testdata/test/finally_timeout.out
- cli/tests/testdata/test/no_prompt_by_default.out
- cli/tests/testdata/test/no_prompt_with_denied_perms.out
- cli/tests/testdata/test/ops_sanitizer_missing_details.out
- cli/tests/testdata/test/ops_sanitizer_multiple_timeout_tests.out
- cli/tests/testdata/test/ops_sanitizer_multiple_timeout_tests_no_trace.out
- cli/tests/testdata/test/ops_sanitizer_unstable.out
- cli/tests/testdata/test/resource_sanitizer.out
- cli/tests/testdata/test/steps/failing_steps.out
- cli/tests/testdata/test/steps/invalid_usage.out
- cli/tools/test.rs
- runtime/js/40_testing.js
Closes #14481. 
Closes https://github.com/denoland/deno/issues/14190
See https://github.com/denoland/deno/blob/ab5652c35f98ae34a7648eddbc96f53e2e4fdaaf/cli/tests/testdata/test/fail.out for an example, the other fixtures have wildcarded lines/columns.
> feat(cli/tools/test): Show Deno.test() call locations for failures

- cli/proc_state.rs
- cli/standalone.rs
- core/examples/ts_module_loader.rs
- core/modules.rs
- core/runtime.rs
Towards https://github.com/denoland/deno/issues/2552
Towards https://github.com/denoland/deno/pull/14485
> refactor(core): use Box<u8> for ModuleSource.code instead of a String

- cli/dts/lib.deno.shared_globals.d.ts
- cli/tests/unit/performance_test.ts
- ext/web/15_performance.js
- runtime/js/99_main.js
- tools/wpt/expectation.json
Revival of #10843.
Adds the `timeOrigin` property of the Performance API. Closes #10837.
> feat(web): add performance.timeOrigin

- tools/cut_a_release.md
This commit fixes a typo and the test command used in deno_std.
> chore: improve release docs

- cli/lsp/testing/execution.rs
- cli/lsp/testing/lsp_custom.rs
- cli/tests/integration/test_tests.rs
- cli/tests/testdata/compat/test_runner/top_level_fail_cjs.out
- cli/tests/testdata/compat/test_runner/top_level_fail_esm.out
- cli/tests/testdata/test/meta.out
- cli/tests/testdata/test/no_check.out
- cli/tests/testdata/test/uncaught_errors.out
- cli/tests/testdata/test/uncaught_errors_1.ts
- cli/tests/testdata/test/uncaught_errors_2.ts
- cli/tests/testdata/test/uncaught_errors_3.ts
- cli/tests/testdata/test/unhandled_rejection.out
- cli/tools/test.rs
Closes #14449.
```ts
Deno.test("failing test", () => {
throw new Error("message");
});
Deno.test("passing test", () => {});
Deno.test("test with dangling rejection", () => {
Promise.reject(new Error("foo 3 message"));
});
```
> feat(test): Represent uncaught errors

- cli/tests/testdata/test/pass.out
- cli/tests/testdata/test/pass.ts
- cli/tests/testdata/test/steps/output_within.out
- cli/tools/test.rs
Closes https://github.com/denoland/deno/issues/14315
This commit changes test report output to repeat test name before printing
result, but only if there's user output, denoted by markers.
```ts
$ cat foo_test.ts
Deno.test("my test", () => {
console.log("console.log");
console.log("console.error");
});
```
Before:
```
$ deno test foo_test.ts
Check file:///Users/ib/dev/deno/foo_test.ts
running 1 test from ./foo_test.ts
my test ...
------- output -------
console.log
console.error
----- output end -----
ok (6ms)
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (18ms)
```
After:
```
Check file:///Users/ib/dev/deno/foo_test.ts
running 1 test from ./foo_test.ts
my test ...
------- output -------
console.log
console.error
----- output end -----
my test ... ok (6ms)
test …
```
> feat(test): repeat test name if there's user output

- ext/web/15_performance.js
- tools/wpt/expectation.json
This commit fixes a few WPTs related to the recently landed `performance.timeOrigin`.
> fix(ext/web): brand check in `performance.timeOrigin`

- .github/workflows/ci.yml
- ext/net/ops_tls.rs
This commit ensures that the TLS handshake completes before
attempting to close the connection.
Fixes: https://github.com/denoland/deno/issues/14494
This fixes the bug in the linked issue, but creating a reproducible unit test has been... frustrating.
> fix: finish TLS handshake before shutting down

- cli/tools/test.rs
- test_util/src/lib.rs
The zero width space was ending up in the output as sometimes expected, but that made the tests flaky.
It's unfortunate this hack exists, but it makes the output more stable. The fix here is to remove the zero width space when doing the comparison in the test utility.
Closes #14478
> chore: fix flaky steps_output_within - part 2

- ext/http/lib.rs
- serde_v8/magic/bytestring.rs
Facilitates making `op_http_write_headers` sync and thus faster (will do in follow-up, already experimented locally)
> cleanup(ext/http): simpler http write ops

- runtime/ops/io.rs
> refactor: `StdFileResource` - remove unused cancel handle

- cli/tools/test.rs
It would take a bit of setup to get a test for this, so I don't think it's worth it and it probably would be difficult to reproduce it on the CI.
Closes #14537
> fix: do not panic on `TestOutputPipe::flush` when receiver dropped

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/spawn_test.ts
- runtime/js/40_spawn.js
Equivalent of https://github.com/denoland/deno/pull/11579 for the new API
> feat(runtime/spawn): add `AbortSignal` support

- cli/tests/integration/repl_tests.rs
- runtime/ops/fs.rs
- runtime/ops/io.rs
- runtime/ops/process.rs
- runtime/ops/tty.rs
Given:
```ts
const encoder = new TextEncoder();
// stdout
{
console.log("你好，世界");
const size = await Deno.stdout.write(encoder.encode("🦕\n"));
if (size !== 5) {
throw new Error();
}
}
// stderr
{
console.error("你好，世界");
const size = await Deno.stderr.write(encoder.encode("🦕\n"));
if (size !== 5) {
throw new Error();
}
}
```
Before:
```
õ¢áÕÑ¢´╝îõ©ûþòî
­ƒªò
õ¢áÕÑ¢´╝îõ©ûþòî
­ƒªò
```
After:
```
你好，世界
🦕
你好，世界
🦕
```
Closes #6001
Closes #14516
Closes #14545
> fix: stdout and stderr encoding on Windows

- cli/tests/testdata/test/pass.out
- cli/tests/testdata/test/pass.ts
The test output for stdout and stderr gets collected on two separate threads via pipes. Which thread wakes up first (even with flushing) can be somewhat random especially on the CI where there are only two cores.
In order to make this less random, I separated out the stdout and stderr outputs to two separate test steps.
Closes #14570
> chore: fix flaky integration::test::pass test

- ops/lib.rs
To be able to leverage `serde_v8::Value` APIs (as required in #14556)
> feat(ops): allow passing scope handle to sync ops

- core/extensions.rs
- ops/lib.rs
Explicitly tag v8 ops, would allow many/most "bindings" to be converted to `#[op(v8)]`
> experiment(ops): #[op(v8)]

- core/ops_builtin.rs
- ops/lib.rs
Allows ops to be `-> T` instead of `-> Result<T, AnyError>` if they are indeed infallible
NOTE: removed Result returns from infallible ops in `ops_builtin.rs`, but there are likely more in the codebase
> feat(ops): infallible / result-free ops

- .github/workflows/ci.yml
- ops/lib.rs
Rough token-string matching is robust enough and much easier to grok
> cleanup(ops): simpler is_unit_result()

- ops/lib.rs
Minor further improvement on #14586: There's no need to wrap `result` into `Ok(result)` just to match against `Result`.
Additionally, there's no need to create `let ret = ()` for return value-less ops.
> cleanup(ops): Remove dead code from codegen ops

- cli/tests/unit/http_test.ts
- ext/http/lib.rs
Closes #14524.
Half the code in this PR came from [an existing test case](https://github.com/denoland/deno/blob/bcd875030a2774a74051ef006c4a66436d43b3fa/cli/tests/unit/http_test.ts#L1857-L1919).
Half the code in this PR came from [fly-accept-encoding](https://github.com/superfly/accept-encoding/blob/69ef982a8cb6bdfa6c3f32ed028fa812842d4276/src/lib.rs#L86-L101), which understands Deflate.
> fix(ext/http): make serveHttp compress for Accept-Encoding: deflate, gzip

- ext/fetch/23_response.js
- ext/web/00_infra.js
- ext/web/internal.d.ts
- tools/wpt/expectation.json
This commit adds support for the static `Response.json` method.
Spec change: https://github.com/whatwg/fetch/pull/1392
Tests: https://github.com/web-platform-tests/wpt/pull/32825
Closes #13902
> feat(ext/web): implement static `Response.json`

- cli/tests/unit/process_test.ts
- runtime/ops/process.rs
- runtime/ops/signal.rs
This reverts commit c496639d5dc190b107222bc30462d67ddb86c223.
completely forgot that rust doesnt let you convert numbers to enum...
> Revert "refactor(runtime): change from signal_str_to_int function to enum (#14539)"

- core/bindings.rs
- serde_v8/lib.rs
Follow up to serde_v8's #14450
```
Before:
test bench_utf8_decode_12_b  ... bench:         188 ns/iter (+/- 41)
test bench_utf8_decode_12_kb ... bench:       3,480 ns/iter (+/- 2,226)
test bench_utf8_decode_12_mb ... bench:   1,549,520 ns/iter (+/- 210,202)
test bench_utf8_encode_12_b  ... bench:         400 ns/iter (+/- 69)
test bench_utf8_encode_12_kb ... bench:       5,813 ns/iter (+/- 469)
test bench_utf8_encode_12_mb ... bench:   5,149,035 ns/iter (+/- 160,745)
After:
test bench_utf8_decode_12_b  ... bench:         174 ns/iter (+/- 13)
test bench_utf8_decode_12_kb ... bench:       3,780 ns/iter (+/- 688)
test bench_utf8_decode_12_mb ... bench:   1,484,499 ns/iter (+/- 42,377)
test bench_utf8_encode_12_b  ... bench:         345 ns/iter (+/- 22)
test bench_utf8_encode_12_kb ... bench: …
```
> perf(core): optimize encode on large strings

- cli/dts/lib.deno.ns.d.ts
- cli/tests/testdata/resolve_dns.ts
- cli/tests/testdata/resolve_dns.ts.out
- cli/tests/testdata/resolve_dns.zone.in
- ext/net/ops.rs
Add `CAA` record type support for `Deno.resolveDns()`.
> feat(ext/net): add `CAA` DNS record support

- ext/web/02_event.js
- tools/wpt/expectation.json
This commit fixes a failing WPT test by making `EventTarget`'s `addEventListener()` method throw if both the `listener` and the `signal` option are `null`.
Fixes: https://github.com/denoland/deno/issues/14593
Fixes: https://github.com/denoland/deno/issues/14254
> fix(ext/web): throw if listener and signal are null

- Cargo.lock
- cli/tests/integration/mod.rs
- cli/tests/testdata/ip_address_unsafe_ssl.ts
- cli/tests/testdata/ip_address_unsafe_ssl.ts.out
- cli/tests/unit/tls_test.ts
- ext/tls/lib.rs
Fixes #14609.
- rustls was updated to v0.20.5
- `ext/tls/lib.rs` was changed to understand IP-addresses
- TS TLS test of invalid host handling was updated to check truly invalid host
> fix(ext/tls): ability to ignore IP-address certificate errors

- cli/dts/lib.dom.d.ts
- cli/tests/unit/fetch_test.ts
- ext/fetch/lib.deno_fetch.d.ts
Can't add the dom types to `dom.extras`, because `declare var Response` is not open ended, and thus can not be extended.
> fix: add types for `Response.json`

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/spawn_test.ts
- runtime/js/40_spawn.js
will default to SIGTERM.
Since we dont have a `close()` with `Child`, `kill` will be used frequently, and most of the time one doesnt care how, they just want the process to end.
> feat: make Child.kill argument optional

- Cargo.lock
- cli/Cargo.toml
- cli/tests/testdata/bench/group_baseline.out
- cli/tests/testdata/bench/multifile_summary.out
This PR updates a small issue in the benchmark summary output. Previously it would print e.g. `2x times faster` which is a duplication because it would read as `2 times times faster`. It was updated in `mitata` 0.0.7 to `2x faster` instead,
> fix(bench): update typo in bench summary

- cli/tests/unit/permissions_test.ts
- runtime/js/10_permissions.js
This commit improves the permission descriptor validation by
explicitly checking for object types and using optional
chaining when creating error messages in case the descriptor
is not an object.
Fixes: https://github.com/denoland/deno/issues/14675
> fix(runtime): improve permission descriptor validation

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/deno_exit_tampering.ts
- runtime/js/30_os.js
This PR prevents Deno.exit to fail by tampering of dispatchEvent methods.
ref #14648
> fix: prevent tampering of Deno.exit

- cli/dts/lib.deno.unstable.d.ts
Since #14643 the `ChildStatus.signal` changed from `number` to `string` which is great, but a more accurate typing would be `Deno.Signal`
Currently if you try to pass it down to a type/interface which expect a `Deno.Signal`, you must force the type assertion to avoid TypeScript complaining:
Not complaining with assertion:
> fix(cli/dts): change `ChildStatus.signal` from `string` to `Deno.Signal`

- cli/tests/integration/coverage_tests.rs
- cli/tests/testdata/coverage/no_transpiled_lines/expected.lcov
- cli/tests/testdata/coverage/no_transpiled_lines/expected.out
- cli/tests/testdata/coverage/no_transpiled_lines/index.ts
- cli/tests/testdata/coverage/no_transpiled_lines/interface.ts
- cli/tests/testdata/coverage/no_transpiled_lines/repro_test.ts
- cli/tools/coverage/mod.rs
This commit omits files from the coverage report that have no lines of code to report coverage for.
Fixes: https://github.com/denoland/deno/issues/14683
> fix(coverage): do not report transpiled files with no lines 

- Cargo.lock
- cli/Cargo.toml
- cli/tests/integration/task_tests.rs
- cli/tests/testdata/task/deno.json
- cli/tests/testdata/task/task_deno_exe_no_env.out
- cli/tests/testdata/task/task_no_args.out
- cli/tests/testdata/task/task_non_existent.out
- test_util/src/lib.rs
Added an integration test this time.
Has https://github.com/denoland/deno_task_shell/pull/40/files
Closes #14702
> fix: deno task should actually use current exe for `deno` command

- tools/release/01_bump_crate_versions.ts
- tools/release/deno_workspace.ts
Need to use the unstable flag when launching ./tools/format.js
Closes #14739
> fix(scripts/release): add unstable flag when running ./tools/format.js

- cli/dts/lib.dom.extras.d.ts
Add definition of `ErrorConstructor` with `captureStackTrace` method to `lib.dom.extras.d.ts`.
Closes #14512.
> fix(cli/dts): add `captureStackTrace` to `lib.dom.extras`

- core/runtime.rs
This behavior was introduced in #14019 but wasn't properly tested in that PR.
> test(core): Test that sync ops return/throw objects in the right realm

- cli/dts/lib.deno.ns.d.ts
Ref https://github.com/denoland/deno/issues/14745#issuecomment-1140470965
> chore: update deprecated APIs docs

- cli/dts/lib.deno.ns.d.ts
This PR changes the `Deno.run` JSDoc to use a `curl` example that works the same on all the major platforms. Also adds `await p.status` so the program doesn't exit before the output is shown on the terminal.
> chore(docs): use cross-platform example in deno.run jsdoc

- cli/tsc/99_main_compiler.js
This handles errors in `getDiagnostics` request where there are transient errors in getting the diagnostics which cause an output of:
```
ERROR TSLS = {}
```
In the debug console, which is distracting to users and doesn't impact the usage of the extension.  Also, when one specifier causes an issue, all requested specifiers get dropped, which isn't ideal.  This will handle the whole failure of getting diagnostics better.
> fix(lsp): handle get diagnostic errors better

- .devcontainer/Dockerfile
It currently uses Debian 10 (buster) which is out of date
> chore: Update devcontainer to a modern tag

- core/source_map.rs
Removes unnecessary trait bounds for `SourceMapGetter` trait.
> refactor(core): SourceMapGetter doesn't need Send + Sync

- cli/flags.rs
- cli/tests/integration/task_tests.rs
- cli/tests/testdata/task/deno.json
- cli/tests/testdata/task/task_cwd.out
- cli/tests/testdata/task/task_no_args.out
- cli/tests/testdata/task/task_non_existent.out
- cli/tools/task.rs
Fixes #14820
Adds a `--cwd` flag to `deno task` that can control the directory the task will be executed in
> feat(task): add `--cwd` flag for configuring the working directory

- cli/tests/unit/console_test.ts
- ext/console/02_console.js
This commit updates `Deno.inspect()` to pass inspect options and
the current inspect depth to custom inspect functions.
Refs: https://github.com/denoland/deno/issues/8099
Refs: https://github.com/denoland/deno/issues/14171
> feat(console): pass options and depth to custom inspects

- cli/tests/unit/signal_test.ts
- runtime/ops/process.rs
Reverts the `Deno.kill` changes in https://github.com/denoland/deno/pull/14694/files
FYI @GJZwiers - I tried to [add some tests](https://gist.github.com/dsherret/89d05d333bb8dca3475b257d48bec269) for that PR, but got unexpected behaviour due to: https://github.com/denoland/deno/pull/14694/files#r885888645 so I think we should revert the `Deno.kill` changes in that PR for now.
Opened #14866
> refactor(runtime/signal): revert SIGINT and SIGBREAK `Deno.kill` Windows changes

- cli/tests/unit/intl_test.ts
- runtime/js/99_main.js
This is a non-standard API that is mostly replaced by `Intl.Segmenter`.
> BREAKING: remove `Intl.v8BreakIterator`

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/custom_inspect_url.js
- cli/tests/testdata/custom_inspect_url.js.out
- cli/tests/unit/console_test.ts
- ext/console/02_console.js
- ext/url/00_url.js
This PR contains two commits, which I think should land separately (unsquashed):
This commit updates the `Deno.inspect()` logic to use the
(currently unused) `indentLevel` option to control indentation instead
of passing around separate indent/level parameters internally.
Refs: https://github.com/denoland/deno/issues/8099
Refs: https://github.com/denoland/deno/issues/14171
This commit updates the custom inspect function for URL objects
to pass the inspect options through so that the context is
propagated and the resulting indentation is correct.
Fixes: https://github.com/denoland/deno/issues/14171
> fix(url): properly indent when inspecting URLs

- cli/cache.rs
- cli/emit.rs
- runtime/js/40_testing.js
Dead code from `Deno.emit()` removal
> chore(cli/cache): Remove CacheType::Declaration

- ops/lib.rs
Support returning a `Result<impl Future<Output = Result<T, AnyError>> + 'static, AnyError>`. An hybrid op where both sync and async phases are fallible.
> feat(ops): support `Result<impl Future<Output = Result<T, AnyError>> + 'static, AnyError>`

- cli/dts/lib.deno.shared_globals.d.ts
- cli/tests/unit/performance_test.ts
- ext/web/15_performance.js
- tools/wpt/expectation.json
This commit updates the `Performance` global to extend `EventTarget`.
Fixes: https://github.com/denoland/deno/issues/10995
The CI should fail for the same reason (and with the same test failures) as #14548.
> fix: make Performance global an EventTarget

- cli/tests/unit/event_target_test.ts
- ext/web/02_event.js
- ext/web/lib.deno_web.d.ts
- tools/wpt/testharnessreport.js
This commit adds brand checking to `EventTarget`. It also fixes a bug where deno would crash if an abort signal was aborted via the global `addEventListener()`.
Fixes: https://github.com/denoland/deno/issues/12666
> fix(ext/web): add EventTarget brand checking

- cli/lsp/diagnostics.rs
The comments refer to the header `x-deno-warn`, but [the actual header name](https://github.com/denoland/deno/blob/53dac7451bbdd527aa91e01653b678547624fc39/cli/lsp/cache.rs#L142) is `x-deno-warning`.
> docs(lsp): correct header name in comments

- cli/flags.rs
Fixes #14889. Updates help text for `--check` with the new behaviour.
Edit: I changed the spelling to type-check/type-checking which is consistent with what is used over at [typescript](https://www.typescriptlang.org/docs/handbook/2/basic-types.html#static-type-checking).
> fix(docs): update description of `--check` flag

- cli/tests/integration/fmt_tests.rs
- cli/tests/testdata/fmt/fmt_check_parse_error.out
- cli/tests/testdata/fmt/parse_error/parse_error.ts
- cli/tools/fmt.rs
- tools/lint.js
https://discord.com/channels/684898665143206084/832257813492269088/987705741429342218
> fix(fmt): should fail `--check` on parse error

- runtime/worker.rs
I noticed that it's not possible to pass any source code as a string to `execute_main_module`. That means I end up reimplementing the code inside it with slightly different params (passing code to `load_main_module` instead
of None). That's mostly trivial except for `evaluate_module`, which is currently private. Making it public allows to load modules from strings without copying any code.
Alternatively, I might add a param to `execute_main_module` and `preload_module` but that would break backward compat, which is something I wanted to avoid.
Happy to add a test if you think this change is acceptable.
> refactor: make MainWorker::evaluate_module public

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/ffi_test.ts
- ext/ffi/00_ffi.js
- test_ffi/tests/test.js
This commits removes the `Deno.UnsafePointer` 
wrapper around FFI pointers. A pointer is now 
represented as a bigint primitive. 
There still exist the `Deno.UnsafePointer.of`
API to get pointer value for a TypedArray and 
`Deno.UnsafeCallback`.
```ts
const ptr = Deno.UnsafePointer.of(buf);
```
This commit also removes the extra processing for
FFI parameters. Hence, `Deno.UnsafeCallback` must be 
passed as a pointer.
> BREAKING(ext/ffi): Remove `Deno.UnsafePointer` indirection

- cli/cache.rs
- cli/disk_cache.rs
- cli/emit.rs
- cli/lsp/cache.rs
- cli/main.rs
- cli/proc_state.rs
- cli/tools/bench.rs
- cli/tools/test.rs
This PR adds a new `EmitCache` trait to move towards an sqlite database as part of #13302.
> refactor: add `EmitCache` trait

- cli/tests/integration/repl_tests.rs
- cli/tools/repl/editor.rs
This adds a heuristic that allows tabbing, if the user hits tab and the previous character on the line is white space he's most likely asking for an actual tab not completion.
Python repl for example does this.
https://user-images.githubusercontent.com/22427111/174358649-64c58ee3-5670-4583-ba44-44ceb31ac6e0.mov
> fix(repl): Accept tab when previous character is space

- cli/dts/lib.deno.unstable.d.ts
- ext/ffi/lib.rs
- test_ffi/tests/ffi_types.ts
- test_ffi/tests/test.js
This PR simplifies the TypeScript types used for interacting with Deno FFI. The basis is that types are now first grouped into logical wholes, `NativeNumberType`, `NativeBigIntType` etc. These wholes are combined into the `NativeType` and `NativeResultType` general types.
Then, for both "To" and "From" direction (viewed from Deno's point of view), mapper types are set up to convert the type declaration to the actual TypeScript type.
So, as an example for the type declaration `"usize"` the `ToNativeType` result is `number | bigint`, as we'll allow either a number of BigInt to be passed as a usize into FFI. The `FromNativeType` result however is `bigint`, since FFI will only ever return `usize` type values as BigInts from FFI.
**BREAKING:** Additionally, this PR removes the `{ function: { …
> feat(ext/ffi): BREAKING(unstable): Simplify FFI types

- cli/tools/repl/editor.rs
This fixes the test, but adding a tab is a little broken on Windows (the output gets offset). I think it's a rustyline bug... doesn't seem worth tracking though until someone complains because it's cosmetic I think.
> chore: fix pty_tab_handler test on windows

- cli/tests/integration/fmt_tests.rs
- cli/tools/fmt.rs
Closes https://github.com/denoland/deno/issues/4459
> fix(fmt): ignore node_modules directory

- cli/flags.rs
This updates the docs in cli/flags.rs to no longer mention --watch mode as unstable.
> fix(docs): --watch arg is stable

- cli/dts/lib.deno.unstable.d.ts
- test_ffi/tests/ffi_types.ts
Closes #14963
Notes:
- The tuple item mapping method is more efficient than recursion and supports as many iterations as a union can have: ~50,000 parameters instead of the 1,000 that regular tail-end recursion optimized (which the other implementation was not) generics.
- The `FooMap` and `Foo<Key>` method was previously encouraged by Ryan Kavanaugh and it allows TypeScript to inline some types and for composition between things that may want to also check if something is `Foo` via `FooMap`.
> fix(dts/ffi): non-exact types break FFI inference

- runtime/js/40_testing.js
Fixes a typo when running:
```
Deno.test("break during stream read", async () => {                                     
const stream = new ReadableStream({                                                   
start(controller) {                                                                 
controller.enqueue(new Uint8Array([65]));                                         
controller.enqueue(new Uint8Array([66]));                                         
controller.close();                                                               
}                                                                                   
}).pipeThrough(new TextDecoderStream());                                              
for await (const chunk of stream) { …
```
> fix(test): typo ('finsihed') if text decoder not closed during test

- cli/bench/http.rs
- cli/bench/http/bun_http.js
- test_util/src/lib.rs
This commit adds Bun to our HTTP benchmark suite.
> chore(cli/bench): Add bun HTTP server

- ext/ffi/lib.rs
- test_ffi/tests/integration_tests.rs
- test_ffi/tests/test.js
Fixes #14993.
So, it turns out sometimes people create empty buffers and use them as FFI parameters. These sorts of pointers are absolutely not for writing or reading from (doing so is UB in at least C++ and LLVM), but they can serve a useful function as "end of buffer" pointers.
One way or another, these must not crash Deno.
> fix(ext/ffi): Empty buffers error with index out of bounds on FFI

- Cargo.lock
- Cargo.toml
- ext/web/Cargo.toml
- ext/web/lib.rs
resolves #14980 
Related: #13841
> perf(ext/web): use base64-simd for atob/btoa

- runtime/worker.rs
Fixes #15016 
Embeders can now
```rust
let exit_code: ExitCode = Default::default();
...
deno_runtime::ops::os::init(exit_code.clone())
...
```
> fix(runtime/ExitCode default): derive default for deno_runtime::ExitCode

- cli/args/mod.rs
- cli/main.rs
- cli/proc_state.rs
- cli/tests/integration/vendor_tests.rs
- cli/tools/vendor/mod.rs
This ignores an import map specified in the output directory instead of erroring.
Closes #14899
> fix(vendor): ignore import map in output directory instead of erroring

- Cargo.lock
- serde_v8/Cargo.toml
- serde_v8/magic/bytestring.rs
This commit changes Bytestring to use smallvec
internally. This avoids heap allows when deserializing 
strings < 16 chars.
Revives https://github.com/denoland/deno/pull/14204
Co-Authored-by: @AaronO
> perf(serde_v8): smallvec ByteString

- ext/crypto/lib.deno_crypto.d.ts
> fix(ext/crypto): add missing EcdhKeyDeriveParams type to algorithm parameters of SubtleCrypto.deriveKey

- core/ops.rs
- core/ops_metrics.rs
- ops/lib.rs
The current `OpsTracker` is unsound. It may violate the alias rules of rust reference type. Therefore the `SAFETY` comments are **wrong**.
This commit removes all unsafe usages in `core/ops_metrics.rs`.
Related:
+ #15020 
+ #13868
+ #12525
> fix(core): remove unsafe in OpsTracker

- ops/lib.rs
This commits enables optimization for
ops with return type `u8`, `u16`, `u32` 
and `deno_core::ResourceId` (And their
Result wrappers). Only applies to sync
ops that can skip the serde_v8 layer AOT.
Time spent setting a `ReturnValue` is cut
by half. This can also be done for `i32` types.
> perf(ops): fast path for SMI return values

- .github/workflows/cargo_publish.yml
- .github/workflows/version_bump.yml
Reverts #14819 and adds a comment explaining why. This was done purposefully, but not explained by a comment. Obviously rare scenario, but I think the publish scripts should use a known good version in case anything ever goes super wrong with a release of deno such that the latest version breaks publishing (circular problem where we can't publish to fix).
> ci: use a known good version of deno instead of latest in publish scripts

- cli/bench/http/deno_http_ops.js
Useful benchmark to track JS overhead. Interesting to note that this performs
almost similar to deno_http_native.js
> chore(cli/bench): benchmark for raw HTTP ops

- .dprint.json
I changed the internal cache, so want to keep this up-to-date with the latest dprint.
> chore: upgrade to dprint 0.30.2 internally

- cli/fs_util.rs
This corrects the wrong implementation of @dsherret's suggestion.[1]
[1] https://github.com/denoland/deno/pull/15002#discussion_r913016582
> chore(test): fix `test_collect_specifiers` windows path to specifier code

- ext/crypto/Cargo.toml
Fixes publishing.
https://github.com/denoland/deno/runs/7199683659?check_suite_focus=true
> chore: pin aes-gcm to fix cargo publish

- tools/release/04_post_publish.ts
```
Opening PR...
Failed. Please manually open a PR. PermissionDenied: Requires env access to "GITHUB_TOKEN", run again with the --allow-env flag
at Object.opSync (deno:core/01_core.js:170:12)
at Object.getEnv [as get] (deno:runtime/js/30_os.js:77:17)
at getEnvVarOrThrow (https://raw.githubusercontent.com/denoland/automation/0.11.0/github_actions.ts:23:26)
at getGitHubToken (https://raw.githubusercontent.com/denoland/automation/0.11.0/github_actions.ts:19:10)
at createOctoKit (https://raw.githubusercontent.com/denoland/automation/0.11.0/github_actions.ts:14:11)
at forwardReleaseCommitToMain (file:///home/runner/work/deno/deno/tools/release/04_post_publish.ts:65:26)
at async file:///home/runner/work/deno/deno/tools/release/04_post_publish.ts:15:3
```
> chore(ci): fix post publish for forwarding release commit back to main

- core/runtime.rs
Currently almost every `JsRealm` method has a `&mut JsRuntime` argument. This argument, however, is only used to get the runtime's corresponding isolate. Given that a mutable reference to the corresponding `v8::Isolate` can be reached from many more places than a mutable reference to the `JsRuntime` (for example, by derefing a V8 scope), changing that will make `JsRealm` usable from many more places than it currently is.
> refactor(core): Use `&mut Isolate` as an argument in `JsRealm` methods

- ext/url/00_url.js
A line was vulnerable to prototype manipulation due to a missing primordial equivalent.
> fix(ext/url): missing primordial

- Cargo.lock
- core/Cargo.toml
- core/runtime.rs
- ext/ffi/lib.rs
- serde_v8/Cargo.toml
- test_ffi/tests/bench.js
> perf(ext/ffi): leverage V8 Fast Calls

- .github/workflows/ci.yml
- core/runtime.rs
- ext/ffi/00_ffi.js
- ext/ffi/lib.rs
- test_ffi/src/lib.rs
- test_ffi/tests/event_loop_integration.ts
- test_ffi/tests/integration_tests.rs
JsRuntimeState was mistakenly kept borrowed during event loop middleware calls for the purpose of getting a clone of the `Rc<RefCell<OpState>>` even though the cloning removes the need for the borrow to be kept. With this change thread safe FFI callbacks can now safely call ops that themselves access the `JsRuntimeState` such as ops that create Promises etc.
At the same time, FFI callbacks are changed to set the Isolate's MicrotasksPolicy to `Explicit`. This is done in order to allow thread safe callbacks to return before any microtasks queued by it get executed.
As an example, imagine a thread safe callback using this JavaScript callback:
```ts
const callback = () => {
console.log("Sync work");
Promise.resolve().then(() => {
console.log("Async work");
});
};
```
If any JS code were to …
> fix(ext/ffi): Avoid keeping JsRuntimeState RefCell borrowed for event loop middleware calls

- cli/dts/lib.deno.unstable.d.ts
- ext/ffi/lib.rs
- test_ffi/tests/ffi_types.ts
- test_ffi/tests/test.js
Fast API calls must not trigger a GC event or callback into JS. It can happen that an FFI library stores a function pointer to call later, this patch adds a new option to hint this. Opting out seems better than opting in because this is a less common use case.
cc @aapoalas
> fix(ext/ffi): allow opting out of fast ffi calls

- ext/console/02_console.js
Changes `does not exists` to `does not exist`.
This PR does not require any tests as it only changes one string.
> fix(ext/console): Fix a typo in a warning when .timeEnd is called on an unknown timer

- core/ops_builtin_v8.rs
- core/runtime.rs
The `op_event_loop_has_more_work` op, introduced in #14830, duplicates code from `JsRuntime::poll_event_loop`. That PR also added the unused method `JsRuntime::event_loop_has_work`, which is another duplication of that same code, and which isn't used anywhere.
This change deduplicates this by renaming `JsRuntime::event_loop_has_work` to `event_loop_pending_state`, and making it the single place to determine what in the event loop is pending. This result is then returned in a struct which is used both in the event loop and in the `op_event_loop_has_more_work` op.
> chore(core): Deduplicate code related to `op_event_loop_has_more_work`

- core/lib.rs
- ext/web/message_port.rs
This commit uses `DetachedBuffer` instead of `ZeroCopyBuf` in the ops that back `Worker.prototype.postMessage` and `MessagePort.prototype.postMessage`. This is done because the serialized buffer is then copied to the destination isolate, even though it is internal to runtime code and not used for anything else, so detaching it and transferring it instead saves an unnecessary copy.
Towards #15129.
> chore(web, worker): Use `DetachedBuffer` for `postMessage` ops

- .dprint.json
- .gitmodules
- core/runtime.rs
- ext/ffi/README.md
- ext/ffi/build.rs
- ext/ffi/jit_trampoline.rs
- ext/ffi/lib.rs
- ext/ffi/tcc.rs
- test_ffi/tests/bench.js
- test_ffi/tests/integration_tests.rs
- test_ffi/tests/test.js
Pointed out by @aapoalas #15125 introduced a bug in FFI calls. The first parameter of a fast function must be a V8Value receiver. This patch implements a fix by patching symbol calls to ignore the receiver.
> fix(ext/ffi): trampoline for fast calls

- ext/ffi/jit_trampoline.rs
- ext/ffi/lib.rs
Small error slipped through in the 64 bit arguments mapping to C types for the Fast API trampoline functions. i64 and isize parameters were mapped to `uint64_t`.
This PR fixes the mistake, then fixes the test that was written to expect the `isize` to map into `uint64_t` to instead expect `int64_t`. Finally, I added some line breaks to the codegen'ed C output to make them more readable, hoping to avoid any future lapses like this. Now it's a bit more clear that the types wouldn't have matched originally.
> fix(ext/ffi): i64 arg to C mapping was wrong

- ext/net/ops_unix.rs
If a Unix Domain Socket cannot be removed, throw instead of
panicing.
Fixes: https://github.com/denoland/deno/issues/14213
> fix(net): don't panic on failed UDS removal

- cli/cache/check.rs
- cli/main.rs
- cli/proc_state.rs
Resolves a todo I forgot to resolve in #15118.
> fix: fallback to no type checking cache when db file can't be created

- cli/tests/integration/repl_tests.rs
This worked on Windows, but not on linux/mac. Tested on linux and it works now.
Closes #15185
> chore: fix pty_complete_imports test on linux/mac

- cli/tests/unit/files_test.ts
In #15092 I added this extra writeSyncWhileAsyncFails test which is invalid and flaky. It immediately failed once merged to main: https://github.com/denoland/deno/runs/7324003869?check_suite_focus=true This functionality is hard to test so let's just remove this test.
> chore: remove flaky writeSyncWhileAsyncFails test

- cli/emit.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/check_js_points_to_ts/bar.ts
- cli/tests/testdata/run/check_js_points_to_ts/foo.js
- cli/tests/testdata/run/check_js_points_to_ts/test.js
- cli/tests/testdata/run/check_js_points_to_ts/test.js.out
A JS file can still point to a TS file, so we need to expand the roots
in the checkJs case too.
Fixes: #15163
> fix(cli): Expand tsc roots when using checkJs

- cli/dts/lib.deno.shared_globals.d.ts
These constructors have the same signature as all of JavaScript's other builtin errors.
> fix(cli/dts): allow passing arguments to `WebAssembly` error constructors

- ext/ffi/build.rs
We broke Homebrew builds again :^)
At least the fix should be pretty simple this time. We just need to allow using a prebuilt tinycc, since we can't use the submodule in that context.
> fix(ext/ffi): allow setting a custom lib path for libtcc.a

- core/bindings.rs
- core/runtime.rs
This reverts commit 48a7312f3871e3b76c51eb0143ca1c48da43b20c.
It appears this change introduced flakiness into the tests. Reverting it
for now to keep `main` branch green, before I can figure out what the
problem is.
> Revert "fix(core): unhandled rejection in top-level scope (#15204)"

- cli/tests/integration/test_tests.rs
Discovered this while investigating another flaky test. This is done automatically by itest, but wasn't done here.
> chore: fix flaky captured_output

- Cargo.lock
- cli/Cargo.toml
- cli/tools/repl/editor.rs
- runtime/Cargo.toml
Its a small thing but I want to add https://github.com/kkawakam/rustyline/pull/640 , it landed in 10.0.0
This version have some breaking changes https://github.com/kkawakam/rustyline/releases/tag/v10.0.0
Editor now returns a result because rustlyine now tries to setup SIGWINCH signal handler without overriding the previous one if it exists https://github.com/kkawakam/rustyline/issues/606 https://github.com/kkawakam/rustyline/pull/608 I think its ok to just unwrap here.
> chore(repl): update rustyline to 10.0.0

- tools/cut_a_release.md
Shortens the docland and dotland release instructions. We just need to run a workflow then merge the PR now.
> chore: update docland and dotland release instructions

- cli/tests/unit/dom_exception_test.ts
- ext/web/01_dom_exception.js
Fixes #12927.
There were no issues open about the current implementation.
Uses symbolic members for `DOMException`, and applies branding to its getters.
Uses a null prototype for the error string->code mapping object, to avoid prototype access.
Also updates outdated specification links.
> fix(ext/dom_exception): align better with spec

- .github/workflows/ci.yml
To avoid any issues during build in the coming weeks, see https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
> chore(ci): update actions to run on macos-12

- cli/tests/unit/spawn_test.ts
- runtime/js/40_spawn.js
<s>Add `Child.hasRef()` API before landing</s>
> fix: Child.unref() unrefs stdio streams properly

- cli/lsp/tsc.rs
> fix(lsp): remove CompletionInfo.flags

- cli/tsc.rs
- ext/web/timers.rs
- runtime/ops/os.rs
Remove a few unused arguments from ops. These are not used anywhere and are no longer needed in the signature since the ops macro merge.
> chore(ops): Remove unused arguments from ops

- ext/ffi/lib.rs
Previously I got panics in pointer TypedArray handling with empty arrays from slices with byte_offset as zero. I even checked it multiple times.
Somehow, that no longer occurs and these conditional slice handlings are unnecessary.
> chore(ext/ffi): Remove unnecessary byte_offset conditional slicing

- ext/fetch/22_body.js
- ext/url/00_url.js
Adds a converter for `URLSearchParams`, and uses the two missing converters in fetch/body.
> fix(fetch/body): Fix TODOs about WebIDL conversions

- cli/compat/mod.rs
stream/promises uses an mjs extension
https://deno.land/std@0.150.0/node/stream
No test because this is a simple change, it's unstable compat mode, and this code will probably change soon (also, some code I have incoming will hit this code path every time anyway).
> fix(compat): use mjs extension for stream/promises

- cli/cdp.rs
- cli/http_util.rs
Thereby fixing all `cargo doc` warnings of this kind:
```
warning: this URL is not a hyperlink
--> cli/cdp.rs:413:5
|
413 | /// https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-ExecutionContextId
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use an automatic link instead: `<https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#type-ExecutionContextId>`
|
= note: bare URLs are not automatically turned into clickable links
```
> docs: turn bare URLs into clickable links

- cli/cache/common.rs
- cli/emit.rs
Just a clean up that isolates the usages of xxhash to `FastInsecureHasher`.
> refactor: reuse `FastInsecureHasher` in `get_check_hash`

- core/lib.deno_core.d.ts
Resolves #15282.
Unfortunately I was unable to run the format script because `dprint` doesn't work behind my HTTP proxy.
Also, I'm getting an error when I try to run the lint script. It could be related:
```
dlint
error: Uncaught (in promise) Error: gitLsFiles failed
throw new Error("gitLsFiles failed");
^
at getFilesFromGit (file:///home/zicklag/git/other/deno/tools/util.js:23:11)
at async getSources (file:///home/zicklag/git/other/deno/tools/util.js:87:12)
at async dlint (file:///home/zicklag/git/other/deno/tools/lint.js:16:23)
at async main (file:///home/zicklag/git/other/deno/tools/lint.js:149:5)
at async file:///home/zicklag/git/other/deno/tools/lint.js:155:1
```
This is a super small change, that should pass both, I think.
> core: Add types for `Deno.core.print()`

- cli/lsp/language_server.rs
> fix(cli/lsp): remove excessive line breaks

- cli/lsp/completions.rs
- cli/lsp/registries.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/completion_request_response_empty.json
Fixes: #15252
This ensures that `"/"` is only a commit character on incomplete registry creations, not on other ones.
> fix(lsp): use correct commit chars for completions

- .github/stale.yml
Adds two labels that stalebot tries to mark stale that shouldn't go stale.  Have been adding `"bug"` in order to ward the bot off, but should just update the config.
> chore: add perf and needs investigation to stalebot

- cli/tools/vendor/build.rs
- cli/tools/vendor/test.rs
> fix(vendor): error on dynamic imports that fail to load instead of panicking

- cli/tsc/99_main_compiler.js
- runtime/js/99_main.js
As https://github.com/denoland/deno/pull/14864#discussion_r897439077 mentioned, Update comments pointing `Object.prototype.__proto__` in ECMA262
Related ECMA262 PR: https://github.com/tc39/ecma262/pull/2125
> fix: Update `Object.prototype.__proto__` related comments

- .github/workflows/ci.yml
- cli/args/flags.rs
- cli/lsp/testing/execution.rs
- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/parallel_output.out
- cli/tests/testdata/test/parallel_output.ts
- cli/tests/testdata/test/short-pass-jobs-flag-warning.out
- cli/tests/testdata/test/short-pass.out
- cli/tests/testdata/test/steps/output_within.out
- cli/tools/test.rs
Currently you get jumbled output for parallel tests with steps. This introduces a new formatting mode for `--parallel` which outputs self-contained result lines:
I've removed the `TestReporter` trait, it's clear that it couldn't fulfil any purpose since the cli and lsp test runners needed different event loops in the first place.
> fix(test): output parallel test results independently

- Cargo.lock
- ext/fetch/Cargo.toml
Adds socks proxy support by enabling the reqwest feature flag, as mentioned in #11609. No new tests as the issue mentioned that internal discussions OK'ed the change without new tests.
> feat(ext/fetch): Add socks proxy support

- ext/ffi/lib.rs
- test_ffi/src/lib.rs
- test_ffi/tests/test.js
Previous performance work on `op_ffi_cstr_read` was a bit too optimistic about what it can do.
This PR fixes the optimism by properly checking for UTF-8 validity before giving the bytes to V8 for `v8::String` creation.
> fix(ext/ffi): Check CStr for UTF-8 validity on read

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
- runtime/js/10_permissions.js
- doesn't format text in JSX `<pre>` tags anymore
- fixes formatting of markdown task lists
> fix: various formatting fixes

- .github/workflows/start_release.yml
- tools/cut_a_release.md
- tools/release/00_start_release.ts
- tools/release/release_doc_template.md
This reduces the time from a minute and a half to 17 seconds. ~~I need to update the deno bot PAT to make it work first though (to have gist permissions). I will do that and run a test on this branch before merging.~~ Also, it has some fixes to make it actually work.
Example output: https://gist.github.com/denobot/6c9117bd751e4e92434aecb16e9e49ff
> chore: make the start_release workflow go faster

- cli/tests/integration/compat_tests.rs
- ext/node/01_require.js
- ext/node/lib.rs
This function was missing permissions checks in #15362. This won't actually be used until an upcomming PR, so we're going to temporarily disable this.
> chore: temporarily disable `op_require_read_file`

- ext/node/lib.rs
- runtime/build.rs
- runtime/web_worker.rs
- runtime/worker.rs
This code was not using unstable ops and isn't properly permission checked.
Also opened #15437.
> chore: temporarily disable `ext/node` and use unstable ops

- cli/args/flags.rs
Fixes #15290
I decided to slice `args` in `flags_from_vec()`, rather than in `task_parse()`, to avoid passing `task_parse()` more data than is necessary. This makes it easier to see that `task_parse()` doesn't care about the "--quiet" in `deno --quiet task echo`.
Not happy with the way I'm slicing the subcommand's args from `args`. I couldn't find anything in clap to get the index of the subcommand name, or a function like `index_of()` for subcommands. Suggestions are welcome.
> fix(task): subcommand parser skips global args

- cli/tools/repl/editor.rs
This pr adds colors to functions
This is all subjective but I thought its nicer to have more colors in general.
> feat(repl): Add color to functions

- cli/tests/testdata/070_location.ts
- cli/tests/testdata/070_location.ts.out
- cli/tests/testdata/071_location_unset.ts
- cli/tests/testdata/071_location_unset.ts.out
- runtime/js/99_main.js
This mirrors the behavior of Deploy, since it has no `--location` flag, and always allows writing to `globalThis.location`.
> fix: allow setting `globalThis.location` when no `--location` is provided

- Cargo.lock
- cli/Cargo.toml
- cli/fs_util.rs
- cli/main.rs
- cli/npm/cache.rs
- cli/npm/mod.rs
- cli/npm/registry.rs
- cli/npm/resolution.rs
- cli/npm/tarball.rs
- cli/tools/upgrade.rs
- cli/tools/vendor/specifiers.rs
Adds an initial very basic npm client and dependency resolver. It is missing a lot of things (ex. peer dependency support) and differs from npm's cli resolution—we're going to start with this implementation then work on improving it and building it up.
There are no tests for this yet because we're going to test this in integration once the other parts have landed.
> feat: add initial internal npm client and dependency resolver

- cli/main.rs
- runtime/web_worker.rs
- runtime/worker.rs
Boolean parameters to change functionality are not descriptive. This better aligns with the already existing `execute_main_module` and `execute_side_module` methods.
> refactor(runtime): split up `MainWorker` and `WebWorker`'s `preload_module` method into two separate methods

- .cargo/config.toml
- tools/lint.js
Among other things, this allows rust-analyzer to show lint problems without having to run `lint.js` manually, and it makes it possible to use commands like `clippy fix`.
> Move lint rules to cargo config for better editor integration

- cli/args/mod.rs
- cli/lsp/testing/execution.rs
- cli/main.rs
- cli/tools/bench.rs
- cli/tools/test.rs
- cli/worker.rs
This PR consolidates a lot of the `MainWorker` code into a `CliMainWorker` struct with high level methods. The low level details are then within this class.
At the moment, I mostly extracted out this code to this struct, but I think even some more code re-use code occur.
This will allow me to inject some node-compat like stuff into everywhere more easily instead of spreading it around 7ish different places.
> refactor(cli): consolidate most MainWorker related code to the same place

- cli/args/flags.rs
- cli/args/mod.rs
- cli/main.rs
- cli/proc_state.rs
- cli/tests/integration/coverage_tests.rs
- cli/tests/testdata/coverage/complex_test.ts
- cli/worker.rs
Caused by code now being reused in #15459. The coverage directory should be ignored in certain scenarios.
Fixes deno_std.
> fix(coverage): ensure coverage is only collected in certain situations

- cli/npm/cache.rs
Package names are not necessarily all lowercase: https://twitter.com/izs/status/1558114479690223621
> fix(npm): handle storing non-all lowercase package names

- cli/args/flags.rs
This adds `.mts` to the list of file extensions that can be run with `deno test` and `bench`.
Fixes  #15476
> chore(bench,test): list `.mts` under supported file extensions in cli docs

- cli/standalone.rs
- cli/worker.rs
- runtime/examples/hello_runtime.rs
- runtime/ops/worker_host.rs
- runtime/web_worker.rs
- runtime/worker.rs
This is extracted out of #15484. Essentially in there, I need to pre-load the modules in order to get the npm package references, only then can I tell whether I need to initialize the node code in a worker. This pre_execute_module_cb does the initialization of the node code.
> feat(runtime): add pre_execute_module_cb

- cli/dts/lib.deno.ns.d.ts
- cli/dts/lib.deno.shared_globals.d.ts
- cli/dts/lib.deno.unstable.d.ts
- cli/dts/lib.deno.window.d.ts
- cli/dts/lib.deno.worker.d.ts
- cli/dts/lib.deno_webgpu.d.ts
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/completion_resolve_response.json
- ext/broadcast_channel/lib.deno_broadcast_channel.d.ts
- ext/console/lib.deno_console.d.ts
- ext/crypto/lib.deno_crypto.d.ts
- ext/fetch/lib.deno_fetch.d.ts
- ext/net/lib.deno_net.d.ts
- ext/url/lib.deno_url.d.ts
- ext/web/lib.deno_web.d.ts
- ext/websocket/lib.deno_websocket.d.ts
- ext/webstorage/lib.deno_webstorage.d.ts
This adds the `@category` JSDoc tag to the built-in APIs, which will allow us to generate documentation where we can break up our built-in APIs into seperate categories when displaying documentation without having to maintain a list outside of the code.
> docs: add category tag for built-in APIs

- .github/workflows/ci.yml
- ext/flash/sendfile.rs
- tools/lint.js
`RUSTFLAGS` take precedence over `target.<triple>.rustflags`. Therefore, setting the env var globally in CI would always override whatever linter rules are allowed or denied in `.cargo/config.toml`.
With this change, we ensure that problems are detected both in CI and locally, using either `cargo clippy` or `lint.js`.
---
For context, in [#15453](https://github.com/denoland/deno/pull/15453) I moved the lint rules to `.cargo/config.toml`.
This fix would also unblock https://github.com/denoland/deno/pull/15464 by allowing `clippy::derive-partial-eq-without-eq` in CI.
> Fix: Honor linter rules in CI and locally

- cli/tests/unit/flash_test.ts
- ext/flash/01_http.js
- ext/flash/lib.rs
This PR fixes the listening port number when `port: 0` is passed to Deno.serve.
closes #15515
> fix(ext/flash): fix listening port

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/queue_microtask_error.ts
- cli/tests/testdata/queue_microtask_error.ts.out
- cli/tests/testdata/queue_microtask_error_handled.ts
- cli/tests/testdata/queue_microtask_error_handled.ts.out
- core/01_core.js
- runtime/js/99_main.js
- tools/wpt/expectation.json
Adds error event dispatching for `queueMicrotask()`. Consequently unhandled errors are now reported with `Deno.core.terminate()`, which is immune to the existing quirk with plainly thrown errors (#14158).
Fixes #4350.
Fixes #14158.
> feat: `queueMicrotask()` error handling

- cli/tests/unit/flash_test.ts
- ext/flash/lib.rs
Closes https://github.com/denoland/deno/issues/15520
> fix(unstable): better error for invalid hostname in Deno.serve()

- cli/tests/unit/flash_test.ts
- ext/flash/01_http.js
This PR fixes the default onListen callback to use actual port number, and also adds test case for it.
> fix(ext/flash): fix default onListen callback

- cli/dts/lib.deno.ns.d.ts
- cli/dts/lib.deno.shared_globals.d.ts
- cli/dts/lib.deno.unstable.d.ts
- ext/fetch/lib.deno_fetch.d.ts
- ext/net/lib.deno_net.d.ts
- ext/websocket/lib.deno_websocket.d.ts
This is part of the effort to improve our documentation of APIs.
> docs: add permission tags to JSDocs

- core/runtime.rs
This removes a cast to `i32` of a type that is already `i32`.
> refactor(core/runtime): clean up extra type cast

- cli/tests/unit/fetch_test.ts
- ext/fetch/lib.rs
Previously if a user specified a content-length header for an POST
request without a body, the request would contain two `content-length`
headers. One added by us, and one added by the user.
This commit ignores all content-length headers coming from the user,
because we need to have the sole authority on the content-length because
we transmit the body.
Fixes #15545
> fix(ext/fetch): ignore user content-length header

- cli/npm/resolution.rs
Fixes parsing scoped npm specifiers with no version.
> fix: parse scoped npm specifiers with no version

- cli/bench/http/deno_flash_hono_router.js
- cli/bench/http/deno_flash_send_file.js
- cli/bench/http/deno_http_flash.js
- cli/bench/http/deno_reactdom_ssr_flash.jsx
- cli/bench/testdata/deno_upgrade_http.js
- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/flash_test.ts
- ext/flash/01_http.js
This commit changes the `Deno.serve` function signature to be more
versatile and easier to use. It is now a drop in replacement for
std/http's `serve`.
The input validation has also been reworked.
> feat: update `Deno.serve` function signature

- cli/npm/mod.rs
- cli/proc_state.rs
- cli/tests/integration/npm_tests.rs
- cli/tests/testdata/npm/no_unstable/main.out
- cli/tests/testdata/npm/no_unstable/main.ts
To ensure these are locked down, always require `--unstable`. Previously only cjs would use an op that caused `--unstable` to be required.
> fix(npm): always require --unstable flag even for esm

- cli/tests/unit/flash_test.ts
- cli/tests/unit/spawn_test.ts
- ext/flash/01_http.js
This commit fixes "Deno.serve()" API by making sure that
205 and 304 responses end with "\r\n\r\n".
> fix(unstable): finish HTTP response for 205 and 304 responses

- tools/deno.lock.json
- tools/release/deps.ts
This fixes cargo version bumping and publishing for circular dependencies.
Lockfile updated with:
```
deno cache --lock=tools/deno.lock.json --lock-write ./tools/wpt.ts ./tools/upload_wptfyi.js ./tools/release/deps.ts
```
> chore: fix publish for circular dependencies

- serde_v8/magic/bytestring.rs
- serde_v8/magic/transl8.rs
serde_v8 cannot currently be built for 32 bit targets such as armv7-unknown-linux-musleabihf due to the code assuming pointers are 64 bits:
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
--> serde_v8/magic/transl8.rs:108:3
|
108 |   std::mem::transmute(ptr)
|   ^^^^^^^^^^^^^^^^^^^
|
= note: source type: `u64` (64 bits)
= note: target type: `&T` (32 bits)
```
This PR casts the serialized u64 fields to `usize` before transmuting and removes the hardcoded assumption that `size_of::<usize>() == 8`.
> serde_v8: fix pointer size assumptions

- cli/args/config_file.rs
Gets rid of:
```
error: Unable to parse config file JSON Url { scheme: "file", cannot_be_a_base: false, username: "", password: None, host: None, port: None, path: "/V:/dprint-plugin-typescript/deno.json", query: None, fragment: None } because of
```
and instead prints the specifier.
> fix: config file errors should not print specifier with debug formatting

- ext/node/02_require.js
Ref https://github.com/denoland/deno/issues/15642
(doesn't actually fix the problem in the issue above)
> fix(ext/node): better error for importing ES module via require() call

- Cargo.lock
- cli/Cargo.toml
- cli/cache/parsed_source.rs
- cli/main.rs
- cli/tests/integration/bundle_tests.rs
- cli/tests/integration/compile_tests.rs
`deno compile` was panicking essentially every time. The fix was to have eszip parse the source if a `ParsedSource` didn't exist in the parsed source store.
The reason our tests did not catch this was because it would use a fresh cache each time. Updated the tests to check for this scenario, but the new design should not let this happen anymore.
Closes #15612
> fix(compile): panic when running with a populated dep analysis cache

- bench_util/benches/op_baseline.rs
- core/01_core.js
- core/ops_builtin.rs
- core/runtime.rs
- ops/lib.rs
Extracted from #15521 
```
main:
is_proxy               29.26 ns/iter   (27.21 ns ... 33.88 ns)  30.83 ns  31.19 ns  31.32 ns
response_new_headers  911.85 ns/iter (906.53 ns ... 944.67 ns) 912.07 ns 944.67 ns 944.67 ns
this patch:
is_proxy               10.81 ns/iter    (9.57 ns ... 15.75 ns)  12.78 ns  13.22 ns  13.28 ns
response_new_headers  881.89 ns/iter (874.26 ns ... 914.93 ns) 884.52 ns 914.93 ns 914.93 ns
```
> perf: use fast api for `core.isProxy`

- cli/tools/fmt.rs
Oversight where the file path wasn't added to these panic messages.
> fix(fmt): add the file path to the panic messages when formatting is unstable

- ext/web/08_text_encoding.js
- ext/web/lib.rs
Towards #14893 
1.4x improvement in CSV parsing.
```
time deno run --allow-env --allow-read --allow-hrtime deno-csv-CSVReader.ts 500000-Records.csv
Read 500001 lines for 19.435 seconds
________________________________________________________
Executed in   19.50 secs    fish           external
usr time   17.47 secs    9.85 millis   17.46 secs
sys time    3.55 secs    2.47 millis    3.54 secs
```
```
time ../../deno/target/release/deno run --allow-env --allow-read --allow-hrtime deno-csv-CSVReader.ts 500000-Records.csv
Read 500001 lines for 14.889 seconds
________________________________________________________
Executed in   14.99 secs    fish           external
usr time   13.13 secs    7.14 millis   13.13 secs
sys time    3.18 secs    2.50 millis    3.18 secs
```
> perf(ext/web): flatten op arguments for text_encoding

- cli/proc_state.rs
Not an ideal fix, but this is temporary code until it's stabilized. I also didn't add any lsp tests because those will come later once we get better lsp support.
> fix(npm): ignore the unstable error in the lsp

- cli/dts/lib.deno.unstable.d.ts
- test_ffi/tests/ffi_types.ts
Some pointer types were mistakenly using `BigInt` which as the TS type, which doesn't really mean anything.
Also, the `"buffer"` arguments do also accept `null`.
> fix(ext/ffi): Fix pointer types

- serde_v8/de.rs
- serde_v8/tests/de.rs
Allow passing `v8::StringObject` as unit enum variant alongside `v8::String`.
`v8::StringObject` is currently treated as an object and fails due to `LengthMismatch`.
Not sure about using `to_string` instead of `try_from`.
`try_from` fails due to: `BadType { actual: "v8::data::Value", expected: "v8::data::String" }`
> feat(serde_v8): Support StringObject as unit enum variant

- cli/emit.rs
- cli/main.rs
- cli/proc_state.rs
- cli/tools/check.rs
- cli/tools/mod.rs
- cli/tsc.rs
Type checking and emitting are completely separate now, so this PR splits out the check code from emit.rs.
I didn't make any modifications to the logic. This is just a re-organization.
Closes #15535
> refactor: extract out check code from emit

- cli/npm/resolution.rs
- cli/npm/semver/mod.rs
- cli/npm/semver/specifier.rs
- cli/tests/testdata/npm/deno_run_non_existent.out
This broke with the re-write of the npm semver, but should be fixed now.
Will do a follow up PR for latest tag matching.
Closes #15739
> fix(npm): correct exact matching of pre-release versions

- Cargo.lock
- cli/npm/registry.rs
- cli/npm/resolution.rs
- cli/npm/semver/mod.rs
- test_util/Cargo.toml
- test_util/src/npm.rs
We should respect the "latest" dist tag for getting the current version when no version requirement is provided.
Pointed out in #15739
> fix(npm): respect `latest` dist tag for getting current version

- ops/lib.rs
Fix https://github.com/denoland/deno/issues/15764
Use RefCell::borrow instead of state.borrow to avoid clash with std::borrow::Borrow
> fix(ops): use qualified borrow in op macro

- runtime/ops/io.rs
- runtime/ops/utils.rs
Adds back the `TaskQueue` from https://github.com/denoland/deno/pull/15092/commits/724fdd49e86ab69a792df63e5e47ec16aecebb8c#diff-c8dd7698dbd5b1b3e293ad2c98df1903aadbd893d3332fec60b229f8a180ea73
Tokio's sempahore doesn't seem to always give permits out in the order they were requested.
Note that the AsyncRefCell was removed in #15747 and a semaphore was used which caused this issue.
Closes #15771
> chore: fix flaky stdout_write_all test

- cli/tests/testdata/044_bad_resource.ts.out
Fixes #15791. I guess the wildcard is supposed to handle `(in promise)` not definitely being written but there was an extra space.
> test: fix bad resource fixture

- core/01_core.js
Two minor changes to `opAsync`:
1. Ops never return `maybeError` anymore. A type error is thrown directly, whereas synchronous errors from async ops are handled by rejecting the promise. Thus there's no need to check the return value.
2. If the async op throws, it would now leave the promise in the promise ring. We need to try-catch the error, remove the error and rethrow the error.
> fix(core): opAsync leaks a promise on type error

- cli/tests/unit/error_test.ts
- core/02_error.js
This commit makes error objects more resistant to prototype tampering.
This bug was found when updating the deno_std Node compatibility layer to Node 18. The Node test `parallel/test-assert-fail.js` was breaking std's assertion library.
Refs: https://github.com/denoland/deno_std/pull/2585
> fix(core): make errors more resistant to tampering

- cli/Cargo.toml
`cli/tests/testdata/npm/registry/` contains 22MB of data and that causes the error `max upload size is: 10485760` while publishing `deno` crate.
This PR excludes `cli/tests/testdata/npm/registry/` and avoids the upload error.
> chore(cli): exclude npm registry data from crate package

- cli/node/mod.rs
- cli/tests/integration/npm_tests.rs
- cli/tests/testdata/npm/cjs_this_in_exports/main.js
- cli/tests/testdata/npm/cjs_this_in_exports/main.out
- cli/tests/testdata/npm/registry/@denotest/cjs-this-in-exports/1.0.0/index.js
- cli/tests/testdata/npm/registry/@denotest/cjs-this-in-exports/1.0.0/package.json
- cli/tests/testdata/npm/tarball_with_global_header/main.out
- cli/tests/testdata/npm/translate_cjs_to_esm/main.out
- ext/node/02_require.js
> fix(npm): remove export binding to match node

- ext/flash/01_http.js
Removes an unecessary optimization: Apart from the possibility that the cache might explode due to uncertainties of timer callbacks, there is also a megamorphic property access hit which kinda cancels out its usefulness.
1.3x improvement on Linux. No change on OSX.
> perf(ext/flash): remove string->buffer cache

- ext/url/00_url.js
This small change returns early if the url being parsed has no query string. This gives a nice performance improvement when tested on Ubuntu 22.04 docker in unprivileged mode:
I ran wpt tests as follows and all are passing.
```
deno run -A --unstable ./tools/wpt.ts setup
deno run -A --unstable ./tools/wpt.ts run -- url
deno run -A --unstable ./tools/wpt.ts run --
```
I can't bench right now on Mac or Windows so if anyone can verify they can see same thing there, that would be great.
this is my first Deno PR so let me know if i have missed something out.
> perf(url): return early if url has no query string

- ops/README.md
This fixes the typo on `ops` README.
> fix(ops): Fix typo on readme

- cli/module_loader.rs
- cli/node/mod.rs
- cli/tests/testdata/npm/cjs_reexport_collision/main.ts
- cli/tests/testdata/npm/esm_import_cjs_default/main.js
- cli/tests/testdata/npm/esm_import_cjs_default/main.out
Unfortunately, I don't believe there would be any way for us to make the `__esModule`/`default` checks work in a bullet proof way given that we need to analyze named exports ahead of time. Making it work would also probably lead to a lot of complexity that static analysis would fail us on in certain scenarios which would lead to probably requiring exceptions for certain packages. See discussion in #15876.
Closes #15865
> fix(npm): align Deno importing Node cjs with Node esm importing cjs

- cli/tests/unit/flash_test.ts
Fixes https://github.com/denoland/deno/issues/15892
Happening too often in CI. This is to unblock other PRs until we find a solution.
> chore(ext/flash): disable flaky flash test

- runtime/js/12_io.js
> refactor(runtime/io): use primordials

- cli/dts/lib.deno.unstable.d.ts
Reverts denoland/deno#15878
There is no way to tell if an API is stable or unstable in LSP completions now. docland should just ignore this specific comment if it is causing issues there.
Also no way to tell apart stable and unstable APIs in `deno types` output.
> Revert "docs: remove unstable messages"

- Cargo.lock
- cli/Cargo.toml
- cli/tests/integration/doc_tests.rs
- cli/tests/testdata/deno_doc.out
- cli/tools/doc.rs
Depends on https://github.com/denoland/deno_doc/pull/292
This is the same fix that we did with eszip and deno compile.
Closes #15930
> fix(doc): deno doc should parse modules if they haven't been parsed before

- .cargo/config.toml
- cli/args/config_file.rs
- cli/args/flags.rs
- cli/http_util.rs
- cli/tools/bench.rs
- cli/tools/test.rs
- core/error.rs
- ext/crypto/key.rs
- ext/crypto/shared.rs
- ext/flash/lib.rs
- ext/net/ops.rs
- ext/url/lib.rs
- runtime/ops/process.rs
- runtime/permissions.rs
- serde_v8/error.rs
- serde_v8/tests/de.rs
Stop allowing clippy::derive-partial-eq-without-eq and fix warnings about deriving PartialEq without also deriving Eq.
In one case I removed the PartialEq because it a) wasn't necessary, and b) sketchy because it was comparing floating point numbers.
IMO, that's a good argument for enforcing the lint rule, because it would most likely have been caught during review if it had been enabled.
> chore: fix clippy warnings

- cli/args/flags.rs
> perf(cli): avoid `clap::App::clone`

- cli/args/config_file.rs
> perf(cli): avoid `canonicalize_path` if config file does not exist

- core/bindings.rs
Towards https://github.com/denoland/deno/issues/15945
> perf(core): use single ObjectTemplate for ops in `initialize_ops`

- Cargo.lock
- runtime/Cargo.toml
v0.1.3 contains code that will stop working with newer versions of libstd because the layout of some std::net types changed.
Refs: https://github.com/bnoordhuis/netif/pull/10
<hr>
The linked PR is the only code change relative to v0.1.3.
> chore(runtime): upgrade netif crate

- cli/dts/lib.deno_webgpu.d.ts
- ext/webgpu/src/01_webgpu.js
> fix(ext/webgpu): GPUDevice.features should be SetLike.

- cli/tests/unit/os_test.ts
- runtime/ops/os.rs
This PR improves the error message when `Deno.env.get` is called with invalid inputs.
`Deno.env.get` throws an error if the input is an empty string or contains "\0" or "=", but the error message is always `Key contains invalid characters.`. This PR fixes this error message, and gives more information about the invalid inputs.
Partially resolves https://github.com/denoland/deno_std/issues/2665
> fix(runtime): better error message with Deno.env.get/set

- Cargo.lock
- cli/bench/deno_common.js
- core/01_core.js
- core/Cargo.toml
- core/bindings.rs
- ext/web/02_timers.js
- ops/lib.rs
- serde_v8/Cargo.toml
Use `options.data` to get access to the `OpCtx` struct instead of using the `receiver` object (essentially the `this` argument).
This puts fast ops' context access on essentially the same path as "slow ops", ie. both use the `external_data` argument.
I was hoping this would enable removing all or at least some of the `ExternalResource` stuff but that does not seem to be the case, though I do not understand why they're needed now and why they need to be kept out of the snapshot creation.
There might be a very nasty crash hidden in this PR: Once when running the `deno_common` benchmarks my whole computer froze...
I expect I'll need help to polish this PR to a proper level where it can be merged. Especially the `ExternalResource` stuff is something that I'd love to remove one way or another …
> feat(ops): Automatic fast ops creation

- core/examples/panik.rs
Not really an example, I guess a minor PSA/heads-up for embedders
```shell
> RUSTFLAGS='-C panic=abort' cargo run -q --example=panik --
thread 'main' panicked at 'panik !!!', core/examples/panik.rs:24:5
[1]    26553 abort      RUSTFLAGS='-C panic=abort' cargo run -q --example=panik --
> RUSTFLAGS='-C panic=unwind' cargo run -q --example=panik --
thread 'main' panicked at 'panik !!!', core/examples/panik.rs:24:5
fatal runtime error: failed to initiate panic, error 5
[1]    28617 abort      RUSTFLAGS='-C panic=unwind' cargo run -q --example=panik --
```
> examples(core): panik

- cli/tests/integration/inspector_tests.rs
- cli/tools/repl/mod.rs
Allow exiting the REPL by pressing ctrl+c twice consecutively.
For Node compat :^)
> feat: allow exiting on two consecutive ctrl+c presses

- Cargo.toml
Towards #15945
OS | Binary size (-Oz) | Binary size (-O3) 
---|---|---|
MacOS m1 | 91M | **85M** (reduction)
Linux x64 | 96M | **97M** (increase)
> perf(cli): use -O3 instead of -Oz

- cli/tools/standalone.rs
> fix(compile): keep non-exe extension in deno compile output name on Windows

- core/ops.rs
- ops/lib.rs
- ops/tests/compile_fail/unsupported.rs
- ops/tests/compile_fail/unsupported.stderr
Add support for fast ops to fail at any (sync) phase. If a fallible fast op returns an Err variant, the fallback option will be set true and the error gets saved to `OpState`. V8 will immediately, synchronously call the normal binding function, and the `#[op]` macro takes care of injecting a check for saved errors at the top of the binding.
The op macro and especially its fast side is starting to get pretty ugly, and this makes it uglier still. Big points of ugliness and undefined behaviour:
1. In normal op side, the `OpState` borrowing is done several times at worst. There is no combined logic to figure out if `OpState` is needed and if it is needed as shared or unique (mut), thus leading to multiple places needing to borrow it individually.
2. With fast call codegen, the …
> feat(ops): Fallible fast ops

- cli/tests/unit/fetch_test.ts
It was disabled on windows almost 2 years ago (https://github.com/denoland/deno/pull/8987) with a different fetch implementation
> test(ext/fetch): enable null body status test on windows

- cli/npm/cache.rs
- cli/npm/resolvers/common.rs
- cli/npm/resolvers/local.rs
- cli/tests/integration/npm_tests.rs
Slight optimization where this doesn't re-download a package to the global cache if it's already in the local node_modules folder. This might make some CI runs slightly more efficient if people only cache the local node_modules folder. That said, it will still re-download registry information to the global cache if that doesn't exist, so maybe in the future we could solve that part via a lockfile.
> perf: don't re-download package tarball to global cache if local node_modules folder exists for package

- cli/tests/unit/console_test.ts
- ext/console/02_console.js
This PR improves `console.log` performance for `TypedArray`, `Set`, `Map` and `Array` above `iterableLimit`. It also improves performance for sparse arrays.
fixes #14656
```js
console.time('sparse');console.log(new Array(16777216*10));console.timeEnd('sparse');
console.time('typed');console.log(new Uint8Array(16777216*10));console.timeEnd('typed');
```
**Deno**
```
[ <167772160 empty items> ]
sparse: 5445ms
Uint8Array(167772160) [
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
... 167772060 more items
]
typed: 3160ms
```
**Node**
```
[ …
```
> perf(ext/console): break on iterableLimit & better sparse array handling

- runtime/permissions.rs
Currently permission prompt shows 3 lines and clear 4 lines back. This removes one line above the permission prompt.
CURRENT BEHAVIOR
This updates it to clear only 3 lines.
This PR:
> fix(runtime): refresh perm prompt 3 lines instead of 4

- cli/tools/vendor/build.rs
- cli/tools/vendor/import_map.rs
This is my attempt at fixing https://github.com/denoland/deno/issues/15634
Currently deno vendor tries to parse imported json files via deno_ast and swc. This seems to work fine if the json file looks like `{}` or ["data"] . However if it is something like { "a": "b" } then it fails.
This PR fixes the issue by actually skipping trying to parse the json file altogether. json files should not contain any import statement and so there does not seem to be a need to parse them.
> fix(cli/vendor): Handle assert type json during vendoring

- cli/bench/main.rs
`strace` number format depends on `LC_NUMERIC` environment variable.  This PR sets `LC_NUMERIC` to `C` to prevent `strace` from using decimal comma which causes the following line to panic:
https://github.com/denoland/deno/blob/f3dd13730c592b76778fa047a098214bc1934216/test_util/src/lib.rs#L2219
To reproduce (on linux)
```
LC_NUMERIC=es_ES.UTF-8 cargo bench --bench deno_bench -- strace
```
----
Output can be  tested by doing:
```
LC_NUMERIC=es_ES.UTF-8 strace -c -f -o /tmp/strace.out echo "deno"
```
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
0,00    0,000000           0         1           read
0,00    0,000000           0         1           write
------ ----------- ----------- --------- --------- …
```
> fix(cli/bench): strace numeric format

- Cargo.lock
- cli/Cargo.toml
- cli/npm/resolvers/local.rs
Does what pnpm does (https://pnpm.io/faq#does-it-work-on-windows) and what was recommended in the issue.
Closes #16006
> fix(npm): use ntfs junctions in node_modules folder on Windows

- Cargo.lock
- cli/bench/http/deno_http_flash.js
- cli/bench/http/deno_http_flash_ops.js
- cli/bench/http/deno_http_flash_ops_spawn.js
- cli/bench/http/deno_http_flash_spawn.js
- cli/dts/lib.deno.unstable.d.ts
- ext/flash/01_http.js
- ext/flash/Cargo.toml
- ext/flash/lib.rs
Sets `SO_REUSEPORT` on Linux. MacOS and Windows is a nop.
Closes #15719
> feat(ext/flash): add `reuseport` option on Linux

- cli/args/flags.rs
- runtime/ops/permissions.rs
- runtime/permissions.rs
This PR makes sys kind name validation shared between flag validators and permission ops.
> refactor(cli): use shared sys kind parser in flags.rs

- cli/tests/unit/response_test.ts
- ext/fetch/22_body.js
- ext/web/06_streams.js
Fixes an edge case for `.bodyUsed` for static bodies when `.body` getter is called after consuming the body.
```javascript
const response = new Response("body");
await response.text();
console.log(response.bodyUsed); // true
response.body;
console.log(response.bodyUsed); // false
```
> fix(ext/body): .bodyUsed for static body

- ext/net/01_net.js
- ext/web/06_streams.js
- runtime/js/40_spawn.js
Unrefable streams are not immediately compatible with FastStreams,
because it would require all FastStream implementers to support
unref streaming. This is not reasonable at this time, so for now we opt
all unrefable streams out of the FastStreams optimization by removing
the `[_maybeRid]` marker from these `ReadableStream` objects.
> fix(runtime): no FastStream for unrefable streams

- core/ops_builtin.rs
- core/resources.rs
- ext/flash/01_http.js
- ext/flash/lib.rs
- ext/http/01_http.js
- ext/http/lib.rs
- ext/web/06_streams.js
- runtime/js/40_testing.js
We can use Resource::read_return & op_read instead. This allows HTTP
request bodies to participate in FastStream.
To make this work, `readableStreamForRid` required a change to allow non
auto-closing resources to be handled. This required some minor changes
in our FastStream paths in ext/http and ext/flash.
Blocked on #16095
Towards #16046
> refactor(ext/http): remove op_http_read

- ext/crypto/00_crypto.js
When storing public and private keys in the key store, use a different handle for each key so that they can be looked up in the future.
Refs: https://github.com/denoland/deno/pull/14119
Refs: https://github.com/denoland/deno_std/issues/2631
> fix(ext/crypto): use correct handle for public keys

- cli/tests/unit/cache_api_test.ts
- ext/cache/01_cache.js
The following snippet should throw instead of consuming the body
```js
const cacheName = "cache-v1";
const cache = await caches.open(cacheName);
const response = new Response('consumed');
const promise = cache.put(
new Request("https://example.com/"),
response,
);
console.log(await response.text()); // consumed
```
> fix(ext/cache): acquire reader lock before async op

- serde_v8/de.rs
- serde_v8/tests/de.rs
`StructAccess` implements` serde::de::SeqAccess` instead of `serde::de::MapAccess` thus interpreting structs as sequences.
Closes #15920
> fix(serde_v8): Implement MapAccess for StructAccess

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/import_key.rs
fix https://github.com/denoland/deno/issues/15126
> fix(ext/crypto): fix importKey error when leading zeroes

- cli/tests/unit/cache_api_test.ts
- ext/cache/01_cache.js
`cache.put` leaks resources if there's an error while reading.
> fix(ext/cache): close resource on error

- serde_v8/de.rs
- serde_v8/tests/de.rs
Existing implementation builds an intermediate vector of object keys when deserializing using `MapObjectAccess`.
https://github.com/denoland/deno/blob/bac3a1210f9c773112f3d5001305d1cc6a097798/serde_v8/de.rs#L386-L389
This logic is already handled by `SeqAccess` which can be used directly by `MapObjectAccess`.
`SeqAccess` was also simplified.
> chore(serde_v8): Use SeqAccess in MapObjectAccess to avoid intermediate allocation

- ext/fetch/23_request.js
- ext/fetch/23_response.js
> refactor(ext/fetch): avoid extra headers copy in .clone

- cli/node/mod.rs
- cli/npm/resolution.rs
- cli/tests/integration/npm_tests.rs
- cli/tests/testdata/npm/error_version_after_subpath/main.js
- cli/tests/testdata/npm/error_version_after_subpath/main.out
- ext/node/errors.rs
Ref https://github.com/denoland/deno/issues/15960
> fix(npm): better error is version is specified after subpath

- cli/main.rs
- cli/tests/integration/npm_tests.rs
- cli/tests/testdata/npm/deno_cache.out
This commit adds support for npm specifier in "deno cache" subcommand.
```
$ deno cache --unstable npm:vite npm:chalk https://deno.land/std/http/file_server.ts
```
Besides downloading requested npm package(s), it will also download
necessary code from "std/node/".
Ref https://github.com/denoland/deno/issues/15960
> feat(unstable): add support for npm specifier cli arguments for 'deno cache'

- ext/crypto/00_crypto.js
This
- unifies code style for bits from #16128 and #16140
- reverts a bad suggestion of mine to not allow `length` `0` for ECDH and X25519
- fixes the return length for non-byte lengths
> fix(ext/crypto): ECDH and X25519 non byte length and 0 length fixes

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/fix_exotic_specifiers.ts
- cli/tests/testdata/run/fix_exotic_specifiers.ts.out
It's a test that's been flaky for a week, and after offline discussion,
we're no longer sure what it's testing.
> chore: remove 'fix_exotic_specifier' test

- ext/fetch/21_formdata.js
Replaced `.forEach`, `.map`, `.filter`, `.map` with a single `for...of` loop
> refactor(ext/fetch): simplify parseContentDisposition

- ext/fetch/21_formdata.js
- tools/wpt/expectation.json
This PR adds support for empty `FormData` parsing in `Response`/`Request`
```js
new Response(new FormData()).formData()
```
ref: https://github.com/web-platform-tests/wpt/issues/28607
> fix(ext/fetch): support empty formdata

- serde_v8/de.rs
Related:
+ #15020 
+ https://github.com/denoland/rusty_v8/pull/1019
This commit fixes one ocurrence of unsoundness by using the newly added API (`v8::String::write_utf8_uninit`). 
See also [`clippy:uninit_vec`](https://rust-lang.github.io/rust-clippy/master/index.html#uninit_vec).
Note that it is not  actually a bug. Avoiding unsoundness improves our code quality.
> fix(serde_v8): avoid creating unsound slice reference

- ext/fetch/22_body.js
- ext/web/06_streams.js
- tools/wpt/expectation.json
Enabled the following test:
https://github.com/web-platform-tests/wpt/blob/edc428e8e229429acd723efc7a6d41010c94fc41/fetch/api/abort/general.any.js#L185-L201
> fix(ext/fetch): reject immediately on aborted signal

- core/01_core.js
- core/examples/http_bench_json_ops.js
- core/lib.deno_core.d.ts
- core/ops_builtin.rs
- ext/cache/01_cache.js
- ext/fetch/26_fetch.js
- ext/net/01_net.js
- ext/web/06_streams.js
- runtime/js/40_files.js
- runtime/js/40_spawn.js
This commit adds a new op_write_all to core that allows writing an entire chunk in a single async op call. Internally this calls `Resource::write_all`.
The `writableStreamForRid` has been moved to `06_streams.js` now, and uses this new op. Various other code paths now also use this new op.
Closes #16227
> feat(core): add Deno.core.writeAll(rid, chunk)

- cli/tests/unit/headers_test.ts
- ext/fetch/20_headers.js
This PR fixes invalid header parsing which is flaky because `g` flag is being used in the regex, which keeps track of `lastIndex`
```javascript
try {
new Headers([["x", "\u0000x"]]);  // error
} catch(e) {}
new Headers([["x", "\u0000x"]]); // no error
```
This issue affects `Response` & `Request` constructors as well
> fix(ext/fetch): fix illegal header regex

- cli/dts/lib.deno.window.d.ts
- cli/tests/testdata/run/onload/imported.ts
- cli/tests/testdata/run/onload/main.out
- cli/tests/testdata/run/onload/main.ts
- cli/tests/testdata/run/onload/nest_imported.ts
I've been playing with Deno a bit recently (since becoming FUNemployed as a result of layoff) 🥳
In playing around with globalThis and event handlers/listener, I noticed that onbeforeunload wasn't present on the window type definition, resulting in the following warning: 
`Element implicitly has an 'any' type because type 'typeof globalThis' has no index signature.deno-ts(7017)`
The observation is discussed a bit more here in this somewhat related thread: https://github.com/denoland/deno/issues/13390
I figured this presented me with an opportunity to learn a bit more about Deno, so I set out to address this by updating the typings to include onbeforeunload.
Additionally, I've updated the onload integration test to the update update.
Please let me know if I've missed anything.
Thanks!
-Matt
> Chore: Added onbeforeunload to window type definition + updated test

- cli/args/mod.rs
When the config is a local file, added a check for whether the importMap is an absolute URL, and just use that if so, before falling back to the existing behaviour of resolving as a file path.
Added test for an absolute importMap URL in a local config.
Fixes #16193
> fix(core): Allow importMap to be an absolute URL within the deno config file

- ext/ffi/00_ffi.js
- ext/ffi/lib.rs
The return type checking for `"function"` type FFI values was incorrect and presumed that functions were still being registered as objects containing a "function" key.
While here, I also removed the whole return type checking logic as it was needed for optionally creating BigInts on return when needed, but serde_v8 does this automatically now (I think).
> fix(ext/ffi): Invalid 'function' return type check logic, remove U32x2 as unnecessary

- ext/web/06_streams.js
- tools/wpt/expectation.json
Fixes https://github.com/denoland/deno/issues/11252
Harness no longer crashes with this patch
https://wpt.fyi/results/streams/readable-streams/tee.any.html?label=master&product=deno%5Bexperimental%5D&product=chrome&product=firefox&aligned&view=subtest
> fix(ext/web/streams): fix cancelPromise in ReadableStreamTee

- ext/web/06_streams.js
- tools/wpt/expectation.json
If chunk is not a `Uint8Array` a `TypeError` must be thrown.
https://wpt.fyi/results/fetch/api/response/response-stream-bad-chunk.any.html?label=master&product=deno%5Bexperimental%5D&product=chrome&product=firefox&product=safari&aligned&view=subtest
> fix(ext/fetch): throw TypeError on non-Uint8Array chunk

- ext/web/06_streams.js
- tools/wpt/expectation.json
Fixes the following test: 
```
ReadableStream teeing: enqueue() and close() while both branches are pulling
```
https://github.com/web-platform-tests/wpt/blob/88c13c311c7dbfbb08451489b38255383f3a0e0f/streams/readable-streams/tee.any.js#L479
tests blocked by https://github.com/denoland/deno/pull/16266
> fix(ext/web/streams): enqueue to second branch before closing

- cli/Cargo.toml
- cli/lsp/capabilities.rs
- cli/lsp/config.rs
- cli/lsp/language_server.rs
- cli/lsp/repl.rs
- cli/lsp/tsc.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/lsp/initialize_params_no_snippet.json
Fixes #15367
Properly handles detecting if clients support snippet text and sets the snippet text type on completion items where appropriate.
> fix(lsp): properly handle snippets on completions

- cli/tests/unit/webcrypto_test.ts
- ext/crypto/00_crypto.js
fixes #16180
`HMAC`'s `get key length` `op` uses the hash function's block size, not output size.
refs https://github.com/cloudflare/workerd/issues/68#issuecomment-1271189657
> fix(ext/crypto): correct HMAC get key length op

- Cargo.lock
- core/Cargo.toml
- serde_v8/Cargo.toml
This commit fixes startup time regression, caused by update
to rusty_v8 v0.50.0.
```
./third_party/prebuilt/mac/hyperfine --warmup 3 'target/release/deno run a.js' 'deno run a.js'
Benchmark #1: target/release/deno run a.js
Time (mean ± σ):      17.3 ms ±   0.8 ms    [User: 16.3 ms, System: 6.5 ms]
Range (min … max):    15.9 ms …  19.9 ms
Benchmark #2: deno run a.js
Time (mean ± σ):      23.3 ms ±   0.8 ms    [User: 22.2 ms, System: 6.8 ms]
Range (min … max):    22.0 ms …  26.4 ms
Summary
'target/release/deno run a.js' ran
1.35x faster than 'deno run a.js'
```
> chore: upgrade rusty_v8 to 0.53.1

- test_util/src/lib.rs
Fixes https://github.com/denoland/deno/issues/16302
It crashes due to the table border output from `strace`,
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ---------------- # this is skipped correctly
61.27    6.012053         678      8860       637 futex
0.00    0.000000           0         4           geteuid
------ ----------- ----------- --------- --------- ----------------  # this causes the crash
100.00   11.732230                 25552      1205 total
```
It's flaky because that line is not always skipped from the output, for some reason that I've yet to find out. 
https://github.com/denoland/deno/blob/323ddc8c967dc07272d4083f143bd0af1ecb0475/test_util/src/lib.rs#L2201-L2212
> fix(cli/bench): skip strace table border

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/spawn_test.ts
- runtime/js/40_spawn.js
- runtime/ops/spawn.rs
This PR adds `windowsRawArguments` to `SpawnOptions`. The option enables skipping the default quoting and escaping while creating the command on windows.
The option works in a similar way as `windowsVerbatimArguments` in child_process.spawn options in Node.js, and is necessary for simulating it in `std/node`.
closes #8852
> feat(runtime): add windowsRawArguments to SpawnOptions

- ext/web/02_timers.js
- ext/web/timers.rs
Towards #16315 
It created a bunch of Error objects and rejected the promise. This patch changes `op_sleep` to resolve with `true` if it was cancelled.
> perf(ext/web): optimize timer cancellation

- Cargo.lock
- cli/Cargo.toml
- cli/npm/resolution.rs
- cli/npm/semver/mod.rs
- cli/npm/semver/specifier.rs
- cli/tests/testdata/npm/dual_cjs_esm/main.ts
```ts
import ts from "npm:typescript@next";
console.log(ts.version); // 4.9.0-dev.20221015
```
Note: this does not fix dist-tags specified in dependencies
Closes #15753
> feat(unstable/npm): support providing npm dist-tag in npm package specifier

- cli/bench/http.rs
ci / bench release ubuntu-20.04-xl (pull_request) went from 27m to 24m
> bench: run HTTP benches for 10s

- cli/npm/cache.rs
- cli/npm/resolution.rs
- cli/npm/resolvers/common.rs
- cli/npm/resolvers/local.rs
Noticed this wasn't being done.
> perf(npm): parallelize caching of npm specifier package infos

- cli/tests/testdata/run/textproto.ts
- cli/tests/testdata/run/tls_connecttls.js
- cli/tests/testdata/run/tls_starttls.js
- cli/tests/unit/files_test.ts
- cli/tests/unit/flash_test.ts
- cli/tests/unit/http_test.ts
- cli/tests/unit/read_file_test.ts
- cli/tests/unit/read_text_file_test.ts
- cli/tests/unit/test_util.ts
- cli/tests/unit/tls_test.ts
There were some bugs in the previous version we were using that have now been fixed that I need.
> chore: upgrade internal deno_std to 0.160

- cli/tests/unit/webcrypto_test.ts
[`crypto.getRandomValues`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) does not return a Promise.
> test(crypto): update crypto.getRandomValues calls

- .github/workflows/ci.yml
Run benchmarks on a bare metal server. The bot is a webhook on Deno deploy which can provision a spot instance on Equinix Metal. The machine type is `m3.small.x86` running a Ubuntu 22.04.
Commands:
`+bench` - Provision and schedule benchmarks for this PR.
`+bench status <id>` - Get current status of the metal instance.
The bot source is here: https://github.com/denoland/bench_bot
> enable bench bot

- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/proc_state.rs
- cli/tests/integration/lsp_tests.rs
I will test this more directly in a separate PR (related to npm type checking).
> fix(lsp): allow caching deps in non-saved files

- cli/tools/upgrade.rs
I think this code is a bit easier to read. It's revealed to me as well that we constantly print out the latest version each time once it has a new version instead of just once every day (we should resolve that in a separate pr)
> refactor(cli): update checker - use a single option instead of two

- core/bindings.rs
- core/error.rs
- core/ops_builtin_v8.rs
- core/runtime.rs
- ops/lib.rs
This revert has been discussed at length out-of-band (including with @andreubotella). The realms work in impeding ongoing event loop and performance work. We very much want to land realms but it needs to wait until these lower-level refactors are complete. We hope to bring realms back in a couple weeks.
> Revert realms from deno_core

- cli/dts/lib.deno.unstable.d.ts
- test_ffi/tests/ffi_types.ts
Potential fix for type-code mismatch in FFI buffer types. The code supports ArrayBuffers, but types only reflect TypedArray support.
There's also an existing type for this sort of stuff: `BufferSource`. (Although, it uses `ArrayBufferView` which doesn't actually connect with the TypedArray interfaces specifically, but it's just a type inheritance difference and nothing more.)
> fix(ext/ffi): Use BufferSource for FFI buffer types

- cli/dts/lib.deno.unstable.d.ts
There were still remaining bigint usages for pointers. This now finally fixes all of them, there is only the one `type PointerValue = number | bigint;` line that references `bigint` in the unstable type definition file.
> fix(ext/ffi): Use PointerValue in UnsafePointerView and UnsafeFnPointer types

- cli/tsc/compiler.d.ts
- core/01_core.js
- core/README.md
- core/lib.deno_core.d.ts
- ext/flash/01_http.js
- ext/node/02_require.js
This patch removes the last uses of `core.opSync` from Deno.
The new and JIT-friendly way to call sync ops is `core.ops.op_name()`.
> chore(core): remove `core.opSync`

- cli/tsc/99_main_compiler.js
I was using canary and ran into this issue when removing a file while using the lsp. I accidentally used `remove` in the code instead of `delete` in a recent PR.
```
Failed to request to tsserver TypeError: documentRegistrySourceFileCache.remove is not a function
at Object.releaseDocumentWithKey (deno:cli/tsc/99_main_compiler.js:315:39)
at Object.onReleaseOldSourceFile (deno:cli/tsc/00_typescript.js:168037:34)
at Object.createProgram (deno:cli/tsc/00_typescript.js:118701:26)
at synchronizeHostData (deno:cli/tsc/00_typescript.js:167990:26)
at Object.getApplicableRefactors (deno:cli/tsc/00_typescript.js:168996:13)
at serverRequest (deno:cli/tsc/99_main_compiler.js:928:27)
at [deno:cli\lsp\tsc.rs:3427:27]:1:12
```
Tested locally and it's fixed now.
> fix(lsp): regression - error when removing file

- cli/build.rs
This PR fixes a regression that caused deno binaries produced by the CI release workflows to be larger than expected.
**The problem:** The build script will determine whether the linker supports the `--export-dynamic-symbol-list` flag by looking at the glibc version installed on the system. Ubuntu 20.04 ships with glibc 2.31, which does not support this flag. Upon investigation, I discovered that the CI pipeline does not use the gcc compiler provided by the `build-essential` package, and instead uses *clang-14*, which does support the new flag.
**The solution:** Whenever a custom C Compiler is configured, the build script now assumes the compiler supports the `--export-dynamic-symbol-list` flag. This is not always going to be the case (you could use clang-8, for example), but it puts the …
> fix(build) assume a custom compiler will support --export-dynamic-symbol-list linker flag.

- ext/web/08_text_encoding.js
Avoid unnecessary copy in `decode(bytes, encoding)` which is only used in:
https://github.com/denoland/deno/blob/bfc1fb8d68f39b899e544eee66e3a08abfd350b0/ext/web/10_filereader.js#L207
This change increases performance of `reader.readAsText(blob)`
> perf(ext/web/encoding): avoid copy in decode

- cli/tests/unit/http_test.ts
- cli/tests/unit/net_test.ts
- cli/tests/unit/remove_test.ts
- ext/net/ops_unix.rs
When listening on a UNIX socket path, Deno currently tries to unlink
this path prior to actually listening. The implementation of this
behaviour is VERY racy, involves 2 additional syscalls, and does not
match the behaviour of any other runtime (Node.js, Go, Rust, etc).
This commit removes this behaviour. If a user wants to listen on an
existing socket, they must now unlink the file themselves prior to
listening.
This change in behaviour only impacts --unstable APIs, so it is not
a breaking change.
> fix(ext/net): don't remove sockets on unix listen

- cli/proc_state.rs
- cli/progress_bar.rs
fix: https://github.com/denoland/deno/issues/16381
> In REPL, importing a wrong url normally throw an error then indefinitely show download loader without possibility to continue.
`progress_bar.clear` is never called if an error occurs in these codes.
https://github.com/k-nasa/deno/blob/67984e9a314410371b05b2b6f2b701d192e000d3/cli/proc_state.rs#L395-L415
It looks like a simple solution to speed up the timing of clearing.
I confirmed progress bar disappeared.
https://user-images.githubusercontent.com/23740172/197550467-39ca7907-1239-4fa8-af9c-c347d0224cbd.mov
> fix(cli): Fixed bug where the progress bar did not clear

- cli/tests/testdata/npm/esm/main.js
- cli/tests/testdata/npm/esm/test.out
- cli/tools/test.rs
Fixes #16416
The root problem here is that due to a race condition, logging outside the test can sometimes be captured within a test. This is because the output is captured on a separate thread. We should investigate this in the future (as long as it doesn't have performance implications I think). I briefly tried to fix it in this PR, but it caused a deadlock, so I reverted to just fixing the flaky test for now.
> chore: fix flaky esm_module_deno_test test

- Cargo.lock
- cli/Cargo.toml
Updates deno_task_shell with https://github.com/denoland/deno_task_shell/pull/60 by @sigmaSd 
Co-authored-by: sigmaSd <sigmasd@users.noreply.github.com>
> feat(task): support `sleep` suffixes

- ext/web/06_streams.js
Removed "fake detached" logic since it's no longer needed after [#16294](https://github.com/denoland/deno/pull/16294) landed
> refactor(ext/streams): remove fake detached

- cli/tests/integration/check_tests.rs
- cli/tests/testdata/check/export_equals_declaration_file/main.ts
- cli/tests/testdata/check/export_equals_declaration_file/other.d.ts
- cli/tests/testdata/check/export_equals_declaration_file/other.js
> fix(typescript): allow synthetic default imports when using `ModuleKind.ESNext`

- Cargo.lock
- cli/lsp/capabilities.rs
This caused v1.27.0 publishing to fail.
> fix(lsp): add ServerCapabilities::encoding

- cli/tests/integration/npm_tests.rs
- cli/tests/testdata/npm/cjs_module_export_assignment/main.out
- cli/tests/testdata/npm/cjs_module_export_assignment/main.ts
- cli/tests/testdata/npm/cjs_module_export_assignment_number/main.out
- cli/tests/testdata/npm/cjs_module_export_assignment_number/main.ts
- cli/tests/testdata/npm/registry/@denotest/cjs-module-export-assignment-number/1.0.0/index.d.ts
- cli/tests/testdata/npm/registry/@denotest/cjs-module-export-assignment-number/1.0.0/index.js
- cli/tests/testdata/npm/registry/@denotest/cjs-module-export-assignment-number/1.0.0/package.json
- cli/tests/testdata/npm/registry/@denotest/cjs-module-export-assignment/1.0.0/index.d.ts
- cli/tests/testdata/npm/registry/@denotest/cjs-module-export-assignment/1.0.0/index.js
- cli/tests/testdata/npm/registry/@denotest/cjs-module-export-assignment/1.0.0/package.json
Was investigating our behaviour and noticed there wasn't an explicit test for both of these. Everything seems to align with node.
> chore(npm): add explicit tests for `module.exports` assignment with type checking

- Cargo.lock
- cli/Cargo.toml
The "proposed" feature that we depend upon in tower-lsp, turns on the "proposed" feature in lsp-types which has breaking changes in patch releases because it's explicitly unstable. We need to pin it to prevent it breaking cargo publish.
> chore: pin lsp types due to unstable "proposed" feature

- cli/lsp/config.rs
- cli/lsp/tsc.rs
> fix(lsp): correct `parameterNames.suppressWhenArgumentMatchesName` and `variableTypes.suppressWhenTypeMatchesName`

- cli/tests/integration/watcher_tests.rs
This test has hung a lot recently on macOS. I am not sure if this is because
of a bug in the test or because of the macOS runner that is extremely slow
and flaky in general.
> test: disable run_watch_external_watch_files on macOS

- cli/dts/lib.deno.ns.d.ts
This API needs `--allow-sys` permissions nowadays, but the docs still mention `--allow-env` permissions.
```
deno run .\file.ts
⚠️  ┌ Deno requests sys access to "osRelease".
├ Requested by `Deno.osRelease()` API      
├ Run again with --allow-sys to bypass this prompt.
└ Allow? [y/n] (y = yes, allow; n = no, deny) >
```
> fix: update env to sys permission in jsdoc for Deno.osRelease

- cli/lockfile.rs
- cli/npm/mod.rs
- cli/proc_state.rs
This commit changes lockfile to be "additive" - ie. integrity check only fails if
file/package is already specified in the lockfile, but its integrity doesn't match.
If file/package is not present in the lockfile, it will be added to the lockfile and
the lockfile will be written to disk.
> fix(lock): Additive lock file

- cli/npm/resolution.rs
- cli/tests/integration/npm_tests.rs
Co-authored-by: bartlomieju <bartlomieju@users.noreply.github.com>
> fix(lockfile): error if a referenced package id doesn't exist in list of packages

- cli/tests/unit/os_test.ts
- runtime/ops/os/sys_info.rs
This PR tries to fix `Deno.hostname()` issue on windows. This change starts winsocket before calling `GetHostNameW` as suggested in https://github.com/retep998/winapi-rs/issues/296
closes #16527
> fix(runtime): fix Deno.hostname on windows

- cli/tests/unit/http_test.ts
- ext/http/lib.rs
When streaming a resource in ext/http, with compression enabled, we
didn't flush individual chunks. This became very problematic when we
enabled `req.body` from `fetch` for FastStream recently.
This commit now correctly flushes each resource chunk after compression.
> fix(ext/http): flush chunk when streaming resource

- .github/workflows/bench_cron.yml
- .github/workflows/cargo_publish.yml
- .github/workflows/ci.yml
- .github/workflows/version_bump.yml
- .github/workflows/wpt_epoch.yml
1. update actions/checkout to v3
2. update actions/setup-node to v3
3. update actions/setup-python to v4
4. update actions/cache to v3 (Other two instances aren't updated. blocked by https://github.com/actions/cache/pull/489 (or  https://github.com/actions/cache/pull/571))
> chore(ci): update github actions

- core/bindings.rs
- core/runtime.rs
- runtime/worker.rs
- refactor: remove JsRuntime::ensure_objs
- refactor: Replace JsRuntime::grab_global with JsRuntime::eval
> refactor: simplify deno_core's grab_global and ensure_objs

- cli/standalone.rs
- cli/worker.rs
- runtime/examples/hello_runtime.rs
- runtime/worker.rs
This PR makes it possible for applications to create workers from custom snapshots to improve runtime performance (without having to fork/copy `runtime/workers.rs`).
Note: I know that [extensions](https://github.com/denoland/deno/blob/23a04b15c1540a1374bf27c46a7d41adcb8feab0/runtime/worker.rs#L179) depend on the snapshot for core functionality (and more?), so this feature is probably only useful if the custom snapshot is based on the one provided by `js::deno_isolate_init`.
> feat(runtime): support creating workers with custom v8 snapshots

- Cargo.lock
- core/Cargo.toml
- core/runtime.rs
* Use stack allocated array for 16 promises and spill rest to heap. the exact number can change, maybe 128? (tokio's coop budget limit)
* Avoid v8::Global::clone for global context.
* Do not open global opresolve when its not needed.
> perf(core): minimize trivial heap allocations in `resolve_async_ops`

- ext/web/08_text_encoding.js
- ext/web/lib.rs
- ops/lib.rs
https://encoding.spec.whatwg.org/#dom-textdecoder-decode
> Implementations are strongly encouraged to use an implementation strategy that avoids this copy. When doing so they will have to make sure that changes to input do not affect future calls to [decode()](https://encoding.spec.whatwg.org/#dom-textdecoder-decode).
> perf(web): optimize single pass utf8 decoding

- cli/main.rs
- cli/npm/registry.rs
- cli/npm/resolution/graph.rs
- cli/npm/resolution/mod.rs
- cli/tests/testdata/cache/037_fetch_multiple.out
- cli/tests/testdata/npm/deno_cache.out
1. There was a lot of cloning going on with `NpmPackageInfo`. This is now stored in an `Arc<NpmPackageInfo>` and cloning only happens on the individual version.
2. The package cache is now cleared from memory after resolution.
3. This surfaced a bug in `deno cache` and I noticed it can be more efficient if we have multiple root specifiers if we provide all the specifiers as roots.
> perf: more efficient `deno cache` and npm package info usage

- cli/tests/testdata/run/import_meta/main.out
- cli/tests/testdata/run/import_meta/main.ts
- core/bindings.rs
> fix(npm): disable npm specifiers in import.meta.resolve()

- cli/graph_util.rs
- cli/npm/resolution/specifier.rs
- cli/proc_state.rs
- cli/tests/integration/npm_tests.rs
- cli/tests/testdata/npm/remote_npm_specifier/main.out
- cli/tests/testdata/npm/remote_npm_specifier/main.ts
- cli/tests/testdata/npm/remote_npm_specifier/remote.ts
In order to test out and get feedback on the approach in #16602, we're going to keep npm specifiers in remote modules as unstable for a bit longer.
> feat(npm): require --unstable for npm specifiers in remote modules

- .github/workflows/post_publish.yml
Hmmm... not sure where I got that "published" from as I can't find those docs I was looking at anymore, but it seems this is the way to do it: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
> chore: fix post_publish workflow trigger
