denoland/deno

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
This will help give us better insight.
=> ci: output file system space before and after building

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, rust-toolchain.toml
Also prints disk size in release builds.
=> chore: upgrade to Rust 1.68.2

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
Partially reverts https://github.com/denoland/deno/pull/19340
because it causes hangs in some situations.
=> chore(ext/node): revert changes to ClientRequest.onSocket

tools/release/release_doc_template.md
That action is not working properly.
=> chore: update release doc template

Cargo.lock, cli/Cargo.toml
Tests are upstream.
Closes #18446
=> fix(fmt): do not panic formatting json with multiple values

ext/http/00_serve.js
Found this together with @bartlomieju . This leads to a minor 92k -> 96k Req/s improvement
=> perf(serve): hoist repeated condition

ext/http/00_serve.js, ext/node/polyfills/http.ts, ext/webidl/00_webidl.js
Further improves preact SSR and express benches by about 2k RPS.
Ref https://github.com/denoland/deno/issues/19451
=> perf: optimize ByteString checks, hoist server rid getter

ext/http/00_serve.js
Seems to save only a couple of ms of the 10s benchmark, but I guess why not.
=> perf(serve): hoist promise error callback

cli/tests/testdata/assets/lock_target.txt, cli/tests/unit/flock_test.ts
This was not failing, but actually causing other tests to fail
=> chore(core): fix flaky flock_test on windows

cli/tests/unit/websocket_test.ts, ext/websocket/lib.rs
=> fix(ext/websockets): ensure we fully send frames before close

ext/fetch/20_headers.js
Use `Map` to cache validated HTTP headers. Cache
has a capacity of 4096 elements and it's cleared
once that capacity is reached.
In `preactssr` benchmark it lowers the time spent
when adding headers from 180ms to 2.5ms.
=> perf(http): cache verified headers

ext/http/00_serve.js
=> fix(ext/http): Include hostname in onListen argument

Cargo.lock, Cargo.toml
Test is in deno_npm.
Closes #19500
=> fix(compile): some npm dependencies were missing in compiled output

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
=> chore(ext/node): bring back changes to ClientRequest.onSocket

ext/fetch/20_headers.js
This is a small change, mainly to make the code easier to understand, and of course may have improved performance a little。
Relate #19465
=> refactor: improving magic number

cli/tests/unit_node/testdata/child_process_stdio.js, cli/tests/unit_node/testdata/child_process_stdio_012.js, cli/tests/unit_node/testdata/child_process_unref.js, ext/node/polyfills/_fs/_fs_exists.ts, ext/node/polyfills/_fs/_fs_link.ts, ext/node/polyfills/_fs/_fs_readFile.ts, ext/node/polyfills/_fs/_fs_readlink.ts, ext/node/polyfills/_fs/_fs_rename.ts, ext/node/polyfills/_fs/_fs_symlink.ts, ext/node/polyfills/_fs/_fs_truncate.ts, ext/node/polyfills/_fs/_fs_utimes.ts, ext/node/polyfills/_fs/_fs_writeFile.ts, ext/node/polyfills/path/_posix.ts, ext/node/polyfills/path/_win32.ts, ext/node/polyfills/path/mod.ts, ext/node/polyfills/path/posix.ts, ext/node/polyfills/path/win32.ts, ext/node/polyfills/process.ts
- replace all usages of fromFileURL within node/polyfills/path to pathFromURL within ext/web/00_infra.js
- remove fromFileURL within node/polyfills/path
- addresses #18177
=> fix(path): remove fromFileUrl

runtime/tokio_util.rs
Closes https://github.com/denoland/deno/issues/19528
=> chore: add conditional compilation for tokio_unstable feature

cli/napi/js_native_api.rs
with `napi_define_properties`.
=> fix(cli/napi): property with getter/setter always failed

serde_v8/magic/buffer.rs, serde_v8/magic/string_or_buffer.rs
=> refactor(serde_v8): remove ZeropCopyBuf::Temp

core/lib.rs, core/runtime/ops.rs, ops/op2/dispatch_fast.rs, ops/op2/dispatch_slow.rs, ops/op2/generator_state.rs, ops/op2/mod.rs, ops/op2/test_cases/sync/add_options.out, ops/op2/test_cases/sync/result_primitive.out, ops/op2/test_cases/sync/result_primitive.rs, ops/op2/test_cases/sync/result_void.out, ops/op2/test_cases/sync/result_void.rs
=> refactor(ops): op2 supports Result in slow call path

tools/wpt/expectation.json
=> chore: disable /websocket/stream/tentative/close.any.worker.html?wss

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
=> fix(node/http): add setKeepAlive to FakeSocket

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/npm/resolution.rs
https://github.com/denoland/deno_npm/pull/20
=> fix(npm): support siblings that are peer dependencies of each other

cli/tests/unit/kv_test.ts, ext/kv/01_db.ts, runtime/js/90_deno_ns.js
=> fix(ext/kv): expose Deno.AtomicOperation

cli/tests/integration/watcher_tests.rs
Ref https://github.com/denoland/deno/issues/19629
=> test: ignore fmt_check_all_files_on_each_change_test

ext/url/00_url.js, tools/wpt/expectation.json
Round 2 of trying to close #19000.
Trying codespaces to see if it's any faster than local dev.
=> feat(ext/url): URLSearchParams two-argument delete() and has()

cli/lsp/analysis.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs
Closes https://github.com/denoland/vscode_deno/issues/849
Closes #15330
Closes #10951
Closes #13623
=> feat(lsp): support import maps in quick fix and auto-imports

cli/tests/unit_node/_fs/_fs_read_test.ts
Closes https://github.com/denoland/deno/issues/19632
=> tests: deflake _fs_read_test.ts

cli/tests/integration/lsp_tests.rs, cli/tsc/dts/lib.deno.unstable.d.ts, ext/net/lib.deno_net.d.ts, ext/net/ops_tls.rs
Ref https://github.com/denoland/deno/issues/19685
=> feat: stabilize 'alpnProtocols' setting

cli/args/config_file.rs, cli/tools/vendor/build.rs, cli/tools/vendor/import_map.rs, cli/tools/vendor/mod.rs, cli/tools/vendor/test.rs
=> fix(vendor): support import mapped jsxImportSource

cli/cache/http_cache.rs, cli/cache/mod.rs, cli/file_fetcher.rs, cli/lsp/cache.rs, cli/lsp/completions.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/registries.rs, cli/lsp/tsc.rs
This improves the HttpCache to make it being stored on the file system an implementation detail.
=> refactor: abstract away file system to be buried inside HttpCache

cli/cache/common.rs, cli/cache/incremental.rs, cli/cache/node.rs, cli/cache/parsed_source.rs, cli/emit.rs, cli/lsp/config.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/tools/check.rs, cli/tsc/mod.rs
=> refactor(lsp): move config file related code to config.rs

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
=> fix(node/http): allow callback in first argument of end call

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
=> fix(node/http): add destroy to FakeSocket

cli/lsp/diagnostics.rs
Part of https://github.com/denoland/vscode_deno/issues/835
=> refactor(lsp): update diagnostics.rs to use structs instead of records

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs
https://github.com/denoland/deno/assets/1609021/4d00df19-6747-4f16-9c6d-e2e95fad9755
Closes https://github.com/denoland/vscode_deno/issues/835
=> fix(lsp): stop diagnostics flickering

Cargo.lock, Cargo.toml
Hi all,
This very small PR updates three (3) dependencies: log, rusqlite, and percent-encoding. To the latest version (at the time of this PR) as discuss on Discord channel.
Let me know if there any issues or if separate PRs should be open for each dependency.
Thanks
=> chore: update log, percent-encoding, and rusqlite

cli/args/config_file.rs, cli/tools/vendor/build.rs, cli/tools/vendor/import_map.rs, cli/tools/vendor/mod.rs, cli/tools/vendor/test.rs
=> fix(vendor): do not panic vendoring with jsxImportSource and no jsx files

cli/tests/integration/npm_tests.rs, cli/tests/testdata/node/require_esm_error/esm.js, cli/tests/testdata/node/require_esm_error/main.out, cli/tests/testdata/node/require_esm_error/main.ts, cli/tests/testdata/npm/cjs_require_esm_error/main.out, cli/tests/testdata/npm/cjs_require_esm_mjs_error/main.out, ext/node/polyfills/01_require.js
=> fix(node): improve error message requiring non-npm es module

ext/http/http_next.rs, ext/http/lib.rs, ext/node/polyfills/internal_binding/stream_wrap.ts
Fixes https://github.com/denoland/deno/issues/19766 
Fixes https://github.com/denoland/deno/issues/19846
=> fix(ext/node): check if resource can be used with write_vectored

cli/tests/integration/repl_tests.rs, cli/tests/unit/command_test.ts, runtime/ops/process.rs
fix https://github.com/denoland/deno/issues/19400
=> fix(runtime): print process name in case of spawn error

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
=> fix(node/http): call callback after request is sent

cli/lsp/language_server.rs
Just noticed this while I was looking into a different lsp formatting issue. We actually used to have this, but I mistakenly removed it during a large refactor.
=> perf(lsp): format in a blocking task

cli/lsp/config.rs, cli/lsp/language_server.rs, cli/tests/integration/lsp_tests.rs, test_util/src/builders.rs, test_util/src/fs.rs, test_util/src/lsp.rs
Related to https://github.com/denoland/vscode_deno/issues/784
=> fix(lsp): handle watched files events from symlinked config files

ext/node/polyfills/README.md
also I find the trick to make this work on the repl (makes relative require works on my testing)
`const require = createRequire(Deno.mainModule);`
=> chore: update commonjs loading docs

cli/tools/init/templates/main_test.ts
I have fixed the issue where the test cases generated by ﻿`deno init` were referencing a deprecated module.
https://github.com/denoland/deno/issues/19923
=> fix(cli/init): update to `assert/mod.ts`

README.md
=> docs: nitpick README

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
Closes https://github.com/denoland/deno/issues/19927
=> fix(node): add writable and readable fields to FakeSocket

Cargo.lock, cli/Cargo.toml, cli/util/time.rs
Pulled from https://github.com/denoland/deno/pull/19747
=> chore: update chrono dependency

Cargo.lock, cli/Cargo.toml
=> fix(task): ensure quoted strings are maintained mid-word

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/args/package_json.rs, cli/npm/resolution.rs, cli/npm/resolvers/mod.rs, cli/standalone/mod.rs, cli/tests/integration/check_tests.rs, cli/tests/testdata/npm/registry/@denotest/breaking-change-between-versions/1.0.0/index.d.ts, cli/tests/testdata/npm/registry/@denotest/breaking-change-between-versions/1.0.0/index.js, cli/tests/testdata/npm/registry/@denotest/breaking-change-between-versions/1.0.0/package.json, cli/tests/testdata/npm/registry/@denotest/breaking-change-between-versions/2.0.0/index.d.ts, cli/tests/testdata/npm/registry/@denotest/breaking-change-between-versions/2.0.0/index.js, cli/tests/testdata/npm/registry/@denotest/breaking-change-between-versions/2.0.0/package.json, cli/tools/check.rs, cli/tsc/mod.rs, test_util/src/fs.rs
=> fix(check): should bust check cache when json module or npm resolution changes

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/tests/integration/coverage_tests.rs, cli/tests/integration/init_tests.rs, cli/tests/integration/lsp_tests.rs, cli/tests/integration/npm_tests.rs, cli/tools/check.rs, test_util/src/builders.rs, test_util/src/lsp.rs
Closes https://github.com/denoland/vscode_deno/issues/805
=> fix(lsp): handle import mapped `node:` specifier

ext/node/errors.rs, ext/node/resolution.rs
=> fix(node): package path not exported error - add if types resolution was occurring

cli/tests/integration/npm_tests.rs, cli/tests/testdata/npm/file_dts_dmts_dcts/main.out, cli/tests/testdata/npm/file_dts_dmts_dcts/main.ts, cli/tests/testdata/npm/registry/@denotest/file-dts-dmts-dcts/1.0.0/main.d.cts, cli/tests/testdata/npm/registry/@denotest/file-dts-dmts-dcts/1.0.0/main.d.mts, cli/tests/testdata/npm/registry/@denotest/file-dts-dmts-dcts/1.0.0/main.d.ts, cli/tests/testdata/npm/registry/@denotest/file-dts-dmts-dcts/1.0.0/package.json, ext/node/resolution.rs
postcss was importing `./index.js` from `./index.d.mts` where there also existed a `./index.d.ts`.
Closes #19575
=> fix(npm): improve declaration resolution for filename with different extensions

cli/tools/bench/mitata.rs
Ref https://github.com/denoland/deno/pull/19994#discussion_r1281267606
Ref https://github.com/denoland/deno/pull/19994#discussion_r1281243602
=> fix(bench): iter/s calculation

cli/tools/repl/editor.rs
=> fix(repl): highlight from ident in import from or export from

cli/tests/unit_node/process_test.ts, ext/node/polyfills/process.ts
Closes https://github.com/denoland/deno/issues/19777
=> fix(node): polyfill process.title

ext/http/lib.rs
Use brotli's fastest mode rather than default mode
=> fix(ext/http): serveHttp brotli compression level should be fastest

Cargo.lock, Cargo.toml, cli/tests/unit/http_test.ts, tools/wpt/expectation.json
=> chore: use zlib-ng for flate2

cli/tests/unit_node/zlib_test.ts, ext/node/ops/zlib/mod.rs, ext/node/polyfills/_zlib.mjs, ext/node/polyfills/_zlib_binding.mjs, test.mjs
Fixes https://github.com/denoland/deno/issues/19540
=> fix(ext/node): support dictionary option in zlib init

cli/tests/integration/npm_tests.rs, cli/tests/testdata/npm/require_resolve_url/package.json, cli/tests/testdata/npm/require_resolve_url/url_paths.out, cli/tests/testdata/npm/require_resolve_url/url_paths.ts, ext/node/ops/require.rs
=> fix(npm): do not panic providing file url to require.resolve paths

cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
Fixes https://github.com/denoland/vscode_deno/issues/856.
=> fix(lsp): pass fmt options to completion requests

cli/tests/unit_node/http_test.ts, ext/node/polyfills/http.ts
Closes https://github.com/denoland/deno/issues/20186
=> fix(node/http): emit error when addr in use

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, Releases.md, bench_util/Cargo.toml, cli/Cargo.toml, cli/deno_std.rs, cli/napi/sym/Cargo.toml, ext/broadcast_channel/Cargo.toml, ext/cache/Cargo.toml, ext/console/Cargo.toml, ext/crypto/Cargo.toml, ext/fetch/Cargo.toml, ext/ffi/Cargo.toml, ext/fs/Cargo.toml, ext/http/Cargo.toml, ext/io/Cargo.toml, ext/kv/Cargo.toml, ext/napi/Cargo.toml, ext/net/Cargo.toml, ext/node/Cargo.toml, ext/tls/Cargo.toml, ext/url/Cargo.toml, ext/web/Cargo.toml, ext/webidl/Cargo.toml, ext/websocket/Cargo.toml, ext/webstorage/Cargo.toml, runtime/Cargo.toml
Bumped versions for 1.36.1
(Recover the 1.36.1 commit)
=> 1.36.1 (#20117)

Cargo.lock, cli/Cargo.toml, cli/cache/cache_db.rs, cli/tools/upgrade.rs, cli/util/draw_thread.rs, cli/util/file_watcher.rs, runtime/colors.rs, runtime/js/40_tty.js, runtime/ops/tty.rs, runtime/permissions/prompter.rs
Removes a crate with an outstanding vulnerability.
=> chore(cli): remove atty crate

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/args/mod.rs, cli/lsp/documents.rs, cli/tools/task.rs
Skipping for a later follow-up:
- base64: #20266
- notify
- indexmap (will require follow-up in upstream projects)
=> chore(core): bump and trim deps

cli/tests/unit/kv_test.ts, ext/kv/lib.rs
fixes #19741
Impose a limit on the total atomic payload size
=> fix(kv) increase number of allowed mutations in atomic

Cargo.lock, Cargo.toml, cli/file_fetcher.rs, cli/lsp/language_server.rs, cli/napi/js_native_api.rs, cli/npm/resolvers/global.rs, cli/npm/resolvers/local.rs, cli/npm/resolvers/mod.rs, cli/standalone/mod.rs, cli/tests/integration/fmt_tests.rs, cli/tests/integration/lint_tests.rs, cli/tests/integration/lsp_tests.rs, cli/tests/integration/repl_tests.rs, cli/tools/coverage/merge.rs, cli/util/v8.rs, cli/worker.rs, ext/ffi/dlfcn.rs, ext/ffi/static.rs, ext/http/http_next.rs, ext/http/response_body.rs, ext/kv/remote.rs, ext/kv/sqlite.rs, ext/node/global.rs, ext/node/ops/crypto/x509.rs, ext/node/resolution.rs, ext/web/stream_resource.rs, ext/websocket/lib.rs, runtime/ops/process.rs, rust-toolchain.toml, test_util/src/lib.rs
=> chore: update to Rust 1.72

cli/lsp/testing/server.rs, cli/tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/899.
=> fix(lsp): delete test modules with all tests deleted

cli/tests/integration/js_unit_tests.rs, cli/tests/unit/kv_queue_test_no_db_close.ts, cli/tests/unit/kv_test.ts, ext/kv/sqlite.rs
=> fix(ext/kv): don't panic if listening on queues and KV is not closed

cli/napi/threadsafe_functions.rs
Ref https://github.com/denoland/deno/issues/20072
=> fix(napi): ignore tsfn recv error

Cargo.lock, Cargo.toml, tools/wpt/expectation.json
=> chore: bump deno_core to 0.207.0

Cargo.lock, Cargo.toml
Adds import attributes support.
=> chore: upgrade deno_core to 0.208.0

cli/lsp/client.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/repl.rs
This reverts commit c0dcf6a3571ee04b4826c52d1329804e7c2b02c4.
CC @nayeemrmn
=> Revert "feat(lsp): enable via config file detection (#20334)"

Cargo.lock, cli/Cargo.toml, cli/args/mod.rs, cli/lsp/client.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/repl.rs, cli/tools/task.rs
Refs:
- https://github.com/denoland/deno/pull/20334
- https://github.com/denoland/deno/actions/runs/6047722006/job/16411706360
- https://github.com/denoland/deno/pull/20347
- https://github.com/denoland/deno_config/pull/6
=> Reland "feat(lsp): enable via config file detection (#20334)"

cli/tests/unit_node/child_process_test.ts, ext/node/polyfills/internal/child_process.ts
Before submitting a PR, please read https://deno.com/manual/contributing
all steps, but you can add '[ci]' to a commit message to force it to.
fix #20373
=> fix(node/child_process): don't crash on undefined/null value of an env var

tools/util.js
=> chore: pin third_party

cli/tests/integration/test_tests.rs, cli/tests/testdata/test/filtered_out_only.out, cli/tests/testdata/test/filtered_out_only.ts, cli/tools/test/mod.rs
Fixes https://github.com/denoland/vscode_deno/issues/909.
=> fix(test): apply filter before checking for "only"

ext/fs/ops.rs
Port as many of these ops as we can to `op2`. Waiting on a few `deno_core` updates to complete this file.
=> chore(ext/fs): port some ops to op2

cli/lsp/config.rs, cli/lsp/repl.rs
Dead code, ref https://github.com/denoland/vscode_deno/issues/864#issuecomment-1710970751.
=> chore(lsp): remove TestingSettings::enable

Cargo.lock, cli/Cargo.toml, cli/args/mod.rs, cli/tools/bench/mod.rs, cli/tools/coverage/mod.rs, cli/tools/fmt.rs, cli/tools/lint.rs, cli/tools/test/mod.rs, cli/util/fs.rs
=> fix: empty include in config file excludes all

.dprint.json, Cargo.lock, cli/Cargo.toml
Two bug fixes:
* https://github.com/dprint/dprint-plugin-markdown/pull/85
* https://github.com/dprint/dprint-plugin-markdown/pull/84
=> fix(fmt/markdown): improve ignore comment handling

cli/args/flags.rs
=> fix(compile): support providing flags as args

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/npm/resolution.rs, cli/tests/integration/check_tests.rs, cli/tests/integration/npm_tests.rs, cli/tests/integration/run_tests.rs, cli/tests/testdata/lockfile/no_dts/deno.lock.out
Details: https://github.com/denoland/deno_lockfile/pull/8
=> feat: lockfile v3

.github/workflows/ci.yml, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/repl.rs, cli/util/path.rs, test_util/src/lsp.rs
Relands #20388, reverted in #20419.
=> Reland "refactor(lsp): clean up "enablePaths" handling (#20388)"

cli/build.rs, cli/tests/integration/lsp_tests.rs, cli/tests/unit/version_test.ts, cli/tsc/dts/lib.decorators.d.ts, cli/tsc/dts/lib.dom.d.ts, cli/tsc/dts/lib.es2015.collection.d.ts, cli/tsc/dts/lib.es2015.core.d.ts, cli/tsc/dts/lib.es2015.iterable.d.ts, cli/tsc/dts/lib.es2015.symbol.wellknown.d.ts, cli/tsc/dts/lib.es2017.d.ts, cli/tsc/dts/lib.es2017.date.d.ts, cli/tsc/dts/lib.es2020.bigint.d.ts, cli/tsc/dts/lib.es2021.weakref.d.ts, cli/tsc/dts/lib.es2023.array.d.ts, cli/tsc/dts/lib.es2023.collection.d.ts, cli/tsc/dts/lib.es2023.d.ts, cli/tsc/dts/lib.es5.d.ts, cli/tsc/dts/lib.esnext.d.ts, cli/tsc/dts/lib.esnext.decorators.d.ts, cli/tsc/dts/lib.esnext.disposable.d.ts, cli/tsc/dts/lib.webworker.d.ts, cli/tsc/dts/typescript.d.ts
Without `using` declarations or decorator metadata (waiting for that in v8).
=> feat: TypeScript 5.2

ext/node/polyfills/internal_binding/stream_wrap.ts
Fixes performance regression introduced by https://github.com/denoland/deno/pull/20223 and https://github.com/denoland/deno/pull/20314. It's enough to have one "shared" buffer per socket
and no locking mechanism is required.
=> perf(node/net): optimize socket reads for 'npm:ws' package

cli/lsp/config.rs
Fixes https://github.com/denoland/vscode_deno/issues/917. Will do an accompanying change in vscode_deno. It's an edgecase so cross-compat won't matter too much.
=> fix(lsp): match enable_paths by whole path components

cli/tests/unit/file_test.ts, ext/web/09_file.js
Fixes https://github.com/denoland/deno/issues/20414
=> feat(ext/web): Add name to Deno.customInspect of File objects

Cargo.lock, Cargo.toml, cli/util/time.rs
Fixes the last dependabot security warning
=> chore(cli): update chrono to remove broken time dep

cli/tests/unit/fetch_test.ts, cli/tests/unit/serve_test.ts, ext/http/request_body.rs
Fixes #20502 -- ensure that Hyper errors make it through to JS.
=> fix(ext/http): ensure aborted bodies throw

cli/tests/integration/test_tests.rs, cli/tests/testdata/test/fail_fast.out, cli/tests/testdata/test/fail_fast_other.ts, cli/tools/test/mod.rs
=> fix(test): share fail fast tracker between threads

cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs
Closes https://github.com/denoland/vscode_deno/issues/783.
=> feat(lsp): include source in auto import completion label

cli/lsp/completions.rs, cli/tools/bench/mod.rs, cli/tools/lint.rs, cli/tools/test/mod.rs, cli/util/path.rs
=> fix(lsp): include JSON modules in local import completions

cli/build.rs
<https://github.com/denoland/deno/issues/20281>
=> build: add an environment variable to skip cross build check (#20281)

cli/tools/jupyter/mod.rs
Fixes #20534  
An op2 needs to be overloaded by an op2, not an op1.
=> fix(cli): fetch works in Jupyter

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/npm/resolution.rs, cli/npm/tarball.rs
=> fix(npm): properly handle legacy shasum of package

.github/workflows/cargo_publish.yml
Closes https://github.com/denoland/deno/issues/20576
=> ci: install protoc on cargo_publish

tools/release/release_doc_template.md
=> chore: update manual instructions for doing a release

ext/node/polyfills/_process/process.ts
Fixes https://github.com/denoland/deno/issues/20590
=> fix(node): point process.version to Node 18.18.0 LTS

cli/tests/unit/kv_test.ts
=> fix(kv): unflake kv unit tests

cli/lsp/diagnostics.rs, cli/tests/integration/lsp_tests.rs
=> fix(lsp): show related information for tsc diagnostics

ext/node/polyfills/os.ts
`Array.from` has optional second argument. Calling `map` is not required for this case.
=> fix(ext): simplified array.from + map

cli/lsp/language_server.rs, cli/tests/integration/lsp_tests.rs, cli/tests/testdata/import_maps/import_map.json, cli/tests/testdata/import_maps/print_hello.ts, test_util/src/lsp.rs
Fixes https://github.com/denoland/vscode_deno/issues/936.
=> fix(lsp): resolve remote import maps

cli/lsp/README.md
=> docs: fix broken deno manual link

cli/tests/unit/serve_test.ts
Previously could flake on the op sanitizer because the
`await makeTempFile()` promise could leak out of the test. Now we ensure
the request is fully handled before returning.
=> test: unflake serve_test/httpServerTcpCancellation

cli/tools/upgrade.rs
=> fix(upgrade): error instead of panic on unzip failure

cli/tools/upgrade.rs
This is what we do for deno install, so it should be fine here https://github.com/denoland/deno_install/pull/219
Closes https://github.com/denoland/deno/issues/20683
=> fix(upgrade): use tar.exe to extract on Windows

cli/tests/node_compat/test/parallel/test-os.js, ext/node/polyfills/os.ts
Add `os.availableParallelism()`, which is introduced in Node.js v19.4.0 and v18.14.0.
It just wraps `navigator.hardwareConcurrency`.
=> feat(node:os) add availableParallelism

cli/lsp/testing/execution.rs, cli/tools/test/fmt.rs, cli/tools/test/mod.rs, cli/tools/test/reporters/common.rs, cli/tools/test/reporters/dot.rs, cli/tools/test/reporters/pretty.rs, cli/tools/test/reporters/tap.rs
=> refactor(test): support custom writer in PrettyTestReporter

cli/tests/unit/body_test.ts, ext/fetch/21_formdata.js
fixes https://github.com/denoland/deno/issues/20793
=> fix(ext/formdata): support multiple headers in FormData

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, cli/errors.rs, cli/tools/bench/mitata.rs, cli/tools/bench/mod.rs, cli/tools/coverage/merge.rs, cli/tools/jupyter/server.rs, cli/util/fs.rs, ext/node/resolution.rs, rust-toolchain.toml
Update to Rust 1.73
If this PR has any problem, please tell me.
=> chore: update to Rust 1.73

cli/lsp/urls.rs
=> fix(lsp): percent-encode host in deno: specifiers

cli/tests/unit/ffi_test.ts, ext/ffi/repr.rs
=> fix(ext/ffi): use anybuffer for op_ffi_ptr_of

ext/web/06_streams.js, ext/web/lib.deno_web.d.ts, tools/wpt/expectation.json
Fixes https://github.com/denoland/deno/issues/20741
=> feat(ext/web): cancel support for TransformStream

README.md
=> docs: update readme hello world example

.dprint.json, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/lsp/code_lens.rs, cli/lsp/documents.rs, cli/lsp/testing/collectors.rs, cli/module_loader.rs, cli/resolver.rs, cli/tools/bundle.rs, cli/tools/coverage/mod.rs, cli/tools/fmt.rs, cli/tools/repl/editor.rs, cli/tools/repl/session.rs, cli/tools/vendor/build.rs, cli/tools/vendor/import_map.rs, cli/tools/vendor/mod.rs
=> fix: improved using declaration support

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
It's too slow (about 10-15 mins).
=> ci: remove "Test examples debug"

cli/bench/lsp.rs, cli/bench/lsp_bench_standalone.rs
Verified with `cargo test -p deno --bench deno_bench` and `cargo test --bench lsp_bench_standalone`.
=> build: fix lsp benchmark

Cargo.lock, Cargo.toml, cli/auth_tokens.rs, cli/npm/managed/tarball.rs, cli/util/text_encoding.rs, ext/crypto/ed25519.rs, ext/crypto/export_key.rs, ext/crypto/import_key.rs, ext/crypto/lib.rs, ext/http/lib.rs, ext/kv/lib.rs, test_util/src/lib.rs, test_util/src/npm.rs
=> chore: update base64 crate

Cargo.lock, cli/Cargo.toml
=> chore: bump quick-junit to 0.3.5

Cargo.lock, cli/Cargo.toml, cli/tests/testdata/doc/referenced_private_types_lint.out, cli/tests/testdata/doc/use_import_map.out
This will now catch way more scenarios.
=> feat(doc): improve non-exported diagnostic

cli/args/flags.rs
Fixes https://github.com/denoland/deno/issues/21067
Fixes https://github.com/denoland/deno/issues/21070
=> fix(doc): require source files if --html or --lint used

cli/tsc/dts/lib.deno.ns.d.ts
Minor improvements to the documentation for https://deno.com/api
=> docs: improve some JSDoc

cli/tests/integration/npm_tests.rs, ext/node/analyze.rs
=> fix(node): cjs export analysis should probe for json files

cli/tsc/dts/lib.deno.unstable.d.ts
=> fix small Deno.createHttpClient typo in lib.deno.unstable.d.ts

cli/js/40_testing.js
=> chore: remove primordial usage from 40_testing.js

Cargo.lock, ext/node/Cargo.toml, ext/node/ops/crypto/mod.rs
Saves ~40s in fresh debug build:
Before:
After:
=> chore: use pure rust secp256k1 crate

ext/console/01_console.js, ext/node/polyfills/internal/console/constructor.mjs, ext/node/polyfills/internal_binding/util.ts
This reverts commit 0209f7b46954d1b7bf923b4191e5a356ec09622c.
Reverting because it causes failures on `main`: https://github.com/denoland/deno/pull/20720#issuecomment-1809166755
The PR should be reopened and updated to latest `main` branch before merging.
CC @crowlKats @ghosind
=> Revert "fix(ext/console): fix inspecting iterators error. (#20720)"

Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno/issues/21176
=> chore: bump deno_core

cli/tests/unit_node/perf_hooks_test.ts, ext/node/polyfills/perf_hooks.ts
=> fix(ext/node): add APIs perf_hook.performance

cli/tests/integration/npm_tests.rs, cli/tools/run/mod.rs, cli/worker.rs
=> fix(npm): support cjs entrypoint in node_modules folder

Cargo.lock, Cargo.toml, cli/Cargo.toml, ext/http/Cargo.toml
Fix and test is in deno_doc: https://github.com/denoland/deno_doc/pull/398
=> fix(doc): issue discovering re-exports of re-exports sometimes

runtime/Cargo.toml, runtime/build.rs
Porting https://github.com/denoland/deno/pull/21233 to release branch
=> fix(runtime): snapshot options op missing during snapshot

tools/release/release_doc_template.md
https://github.com/denoland/manual was archived in favor of https://github.com/denoland/deno-docs
=> chore(tools): update release_doc_template.md

Cargo.lock, ext/url/Cargo.toml, ext/url/benches/url_ops.rs
=> fix(ext/url): add deno_console dependency for bench

Cargo.lock, cli/Cargo.toml
Removes some unnecessary dependencies.
=> chore: update deno_doc to 0.73.3

cli/tests/unit/tty_color_test.ts, runtime/colors.rs
Closes https://github.com/denoland/deno/issues/21274
=> fix: Deno.noColor should not be true when NO_COLOR is empty string

cli/args/flags.rs
The `deno run` example in the help output uses https://deno.land/std/examples/welcome.ts which no longer exists.
Replacing with https://examples.deno.land/hello-world.ts
=> docs(cli/args/flags.rs): Update dead link for `run` example

cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/repl.rs
=> fix(lsp): force shutdown after a timeout

runtime/web_worker.rs
=> fix(runtime): fix for panic in classic workers

Cargo.lock, Cargo.toml
Fix and test at https://github.com/swc-project/swc/pull/8318
Closes https://github.com/denoland/deno/issues/21258
=> fix(swc): support jsx pragma when hashbang present

tools/release/release_doc_template.md
Remove the need to manually build M1
=> chore: update release_doc_template.md

cli/args/flags.rs
=> fix: correct flag in tar & upload

cli/lsp/completions.rs, cli/lsp/config.rs, cli/lsp/documents.rs, cli/lsp/tsc.rs, cli/lsp/urls.rs, cli/tests/integration/lsp_tests.rs
Part of https://github.com/denoland/deno/issues/21308
=> fix(lsp): handle byonm specifiers in jupyter notebooks

README.md
Update the README to use current links, and link to appropriate external documentation for most information.
=> docs(README): Update README to include more recent links and use external docs

cli/tools/registry/mod.rs, cli/util/import_map.rs
=> fix: use correct import map in tar & upload

cli/tsc/99_main_compiler.js
This commit removes "ThrottledCancellationToken" in favor of "CancellationToken".
Since calling into Rust to check if Tokio's cancellation token has already been
canceled is really cheap, there's no need for us to throttle this check and let
TSC burn up CPU with heavy computation.
=> perf(lsp): remove throttling of cancellation token

cli/tests/integration/run_tests.rs, cli/tests/testdata/run/065_permissions_revoke_net.ts, cli/tests/testdata/run/065_permissions_revoke_net.ts.out, runtime/permissions/mod.rs
=> fix(permissions): fix panics when revoking net permission

cli/tools/registry/mod.rs
=> fix: don't error if a version already published

cli/npm/managed/resolvers/local.rs, cli/tests/integration/npm_tests.rs
Closes https://github.com/denoland/deno/issues/21476
=> fix(npm): do not create symlink for non-system optional dep in node_modules directory

ext/node/polyfills/_util/_util_callbackify.ts, ext/node/polyfills/_util/asserts.ts, ext/node/polyfills/_util/async.ts, ext/node/polyfills/_util/os.ts, ext/node/polyfills/_util/std_asserts.ts, ext/node/polyfills/_util/std_fmt_colors.ts, ext/node/polyfills/_util/std_testing_diff.ts
I will increase primordials little by little
=> fix(ext/node): use primordials in ext/node/polyfills/_util

cli/tests/unit/websocket_test.ts, ext/http/01_http.js, ext/websocket/01_websocket.js
Fixes https://github.com/denoland/deno/issues/15340
=> fix(websockets): server socket field initialization

cli/tests/testdata/npm/imports_package_json/main.js, cli/tests/testdata/npm/imports_package_json/main.out, cli/tests/testdata/npm/registry/@denotest/imports-package-json/1.0.0/main.js, cli/tests/testdata/npm/registry/@denotest/imports-package-json/1.0.0/package.json, ext/node/analyze.rs, ext/node/errors.rs, ext/node/ops/require.rs, ext/node/path.rs, ext/node/polyfill.rs, ext/node/resolution.rs
Closes https://github.com/denoland/deno/issues/21501
=> fix(node): support resolving a package.json import to a builtin node module

cli/napi/async.rs, cli/napi/threadsafe_functions.rs
Pending review items from https://github.com/denoland/deno/pull/21406
=> chore(node-api): reuse SendPtr

ext/net/ops_unix.rs
Fixes https://github.com/denoland/deno/issues/21587
It seems this was missed in https://github.com/denoland/deno/pull/21463. cc @bartlomieju
=> fix(net): remove unstable check for unix socket listen

cli/cdp.rs, cli/tests/integration/inspector_tests.rs, cli/tools/repl/mod.rs, cli/tools/run/hmr.rs
Just removing some duplicated code.
=> refactor: factor out cdp::ExceptionThrown notification

cli/tools/repl/mod.rs
Left behind in #21623 by mistake.
=> fix(repl): remove stray debug log

cli/tests/unit_node/child_process_test.ts, ext/node/polyfills/internal/child_process.ts
Fixes https://github.com/denoland/deno/issues/21630
=> fix(node): child_process kill cancel pending IPC reads

cli/tests/unit/websocket_test.ts, ext/websocket/01_websocket.js
Ref https://github.com/denoland/deno/issues/15340#issuecomment-1872353134
=> fix(ext/http): use arraybuffer binaryType for server websocket 

Cargo.lock, Cargo.toml
Pull in https://github.com/denoland/rustls-tokio-stream/pull/22 to fix https://github.com/denoland/deno/issues/21762
=> chore(ext/net): bump rustls-tokio-stream to fix panic

cli/tests/integration/jupyter_tests.rs, cli/tests/integration/mod.rs, cli/tests/testdata/jupyter/install_command_not_exists.out, cli/tools/jupyter/install.rs
We were failing silently in this scenario.
=> fix(jupyter): error message when install fails due to jupyter command not being on PATH

cli/tests/integration/node_unit_tests.rs, cli/tests/unit_node/dgram_test.ts, ext/net/01_net.js, ext/node/polyfills/internal_binding/udp_wrap.ts
Fixes https://github.com/denoland/deno/issues/20138
Different implementation than https://github.com/denoland/deno/pull/21521 (cc @CosminPerRam)
=> fix(ext/node): UdpSocket ref and unref

cli/tools/coverage/mod.rs
I did not measure this change (O(n) to O(log n)), but mainly this should be slightly more accurate at getting the line number.
=> perf(coverage): faster source mapping

cli/lsp/code_lens.rs
Fixes https://github.com/denoland/vscode_deno/issues/951.
=> fix(lsp): show test code lens for template literal names

ext/node/polyfills/_fs/_fs_appendFile.ts, ext/node/polyfills/_util/std_asserts.ts, ext/node/polyfills/_util/std_fmt_colors.ts, ext/node/polyfills/internal/util/types.ts, ext/node/polyfills/internal_binding/connection_wrap.ts, tools/util.js
=> chore: update deno_lint for CI

cli/cdp.rs, cli/tools/repl/mod.rs, cli/tools/repl/session.rs
Some drive-by cleanup as I'm working through https://github.com/denoland/deno_core/pull/415.
=> refactor(tools/repl): reorganize code

tools/format.js
The PR referenced has been released so we can update this now.
=> chore: update format script

cli/tsc/dts/lib.deno.unstable.d.ts
=> fix(kv): improve .listenQueue types

cli/standalone/binary.rs, cli/standalone/mod.rs, cli/tests/integration/compile_tests.rs, cli/tests/testdata/compile/unstable_features.ts
Fix https://github.com/denoland/deno/issues/21814
=> fix(compile): preserve granular unstable features

ext/io/12_io.js
These functions don't appear to be used anywhere.
=> chore(ext/io): cleanup unused functions

.github/ISSUE_TEMPLATE/config.yml
Fixes https://github.com/denoland/deno/issues/21880
=> chore: fix issue template discord link

cli/build.rs, cli/tests/integration/lsp_tests.rs, cli/tsc/dts/lib.deno.ns.d.ts, ext/fs/30_fs.js, ext/fs/std_fs.rs, ext/net/ops.rs, ext/net/ops_tls.rs, ext/node/ops/os/cpus.rs, ext/node/polyfills/_util/os.ts, ext/node/polyfills/internal_binding/constants.ts, ext/node/polyfills/internal_binding/uv.ts, ext/node/polyfills/os.ts, runtime/ops/os/mod.rs, runtime/ops/os/sys_info.rs
=> fix: android support

Cargo.lock, cli/Cargo.toml
=> fix(fast_check): analyze identifiers in type assertions/as exprs

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs
=> refactor(lsp): store project version on documents

ext/fetch/lib.deno_fetch.d.ts
=> fix: add EventSource typings

cli/module_loader.rs, cli/tests/integration/check_tests.rs, cli/tests/testdata/check/excluded_file_specified/check.out, cli/tests/testdata/check/excluded_file_specified/deno.json, cli/tests/testdata/check/excluded_file_specified/lib/types.d.ts, cli/tools/check.rs
=> fix(check): should not panic when all specified files excluded

cli/tsc/dts/lib.deno.ns.d.ts
=> docs(ns): add a notice on file order returned by readDir

cli/tests/integration/inspector_tests.rs
Ref https://github.com/denoland/deno/issues/21912
=> chore: ignore inspector_port_collision test

cli/tests/testdata/npm/registry/@denotest/child-process-fork/1.0.0/index.js, cli/tests/testdata/test/captured_output.ts
For https://github.com/denoland/deno/pull/21939
=> refactor: change tests to not rely on Deno.run()

cli/tests/unit/command_test.ts, cli/tests/unit/process_test.ts, cli/tests/unit_node/_fs/_fs_ftruncate_test.ts, cli/tests/unit_node/_fs/_fs_truncate_test.ts, cli/tsc/dts/lib.deno.ns.d.ts
=> chore: use `Deno.writeTextFile()` where appropriate

cli/lsp/language_server.rs, cli/lsp/lsp_custom.rs, cli/tests/integration/lsp_tests.rs
=> feat(lsp): include scope uri in "deno/didChangeDenoConfiguration"

cli/args/flags.rs
=> refactor: set removal version for `--ts`/`-T` flags

cli/tests/integration/publish_tests.rs, cli/tests/testdata/publish/invalid_fast_check.out, cli/tests/testdata/publish/javascript_missing_decl_file.out, cli/tests/testdata/publish/unanalyzable_dynamic_import.out, cli/tests/testdata/publish/unanalyzable_dynamic_import/deno.json, cli/tests/testdata/publish/unanalyzable_dynamic_import/mod.ts, cli/tools/registry/diagnostics.rs, cli/tools/registry/graph.rs, cli/tools/registry/mod.rs, cli/tools/registry/tar.rs, cli/util/import_map.rs
=> chore: improve unanalyzable dynamic import diagnostic

Cargo.lock, cli/Cargo.toml, cli/schemas/config-file.v1.json, cli/tests/integration/publish_tests.rs, cli/tools/registry/mod.rs, cli/tools/registry/tar.rs
https://github.com/denoland/deno_config/pull/34
=> feat(publish): exclude and include

Cargo.lock, cli/Cargo.toml
=> chore: update deno_graph

cli/lsp/language_server.rs, cli/tests/integration/lsp_tests.rs
Follow up to https://github.com/denoland/deno/pull/22040.
By mistake I forgot to disable "experimental decorators" in the LSP.
=> fix(lsp): disable experimentalDecorators by default

cli/tests/unit/files_test.ts, ext/fs/30_fs.js, ext/node/polyfills/_fs/_fs_fdatasync.ts, ext/node/polyfills/_fs/_fs_fstat.ts, ext/node/polyfills/_fs/_fs_fsync.ts, ext/node/polyfills/_fs/_fs_ftruncate.ts, ext/node/polyfills/_fs/_fs_futimes.ts, ext/node/polyfills/_fs/_fs_readFile.ts, ext/node/polyfills/_fs/_fs_writeFile.ts, runtime/js/40_process.js, runtime/js/90_deno_ns.js
Regression caused by https://github.com/denoland/deno/pull/22072.
I added a relevant test so we don't regress again.
Fixes https://github.com/denoland/deno/issues/22115
=> fix(fs): instanceof check for Deno.FsFile

bench_util/README.md
fix:Updating grammar errors in readme.md
fix https://github.com/denoland/deno/issues/21491
=> chore(bench_util): fix syntax error in README.md

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Also don't always upload cache - this was a bug I introduced in the CI refactor.
=> ci: upload canary latest to correct path

runtime/js/99_main.js
Trying to come up a way to test that that doesn't require installing 3rd party deps.
Closes https://github.com/denoland/deno/issues/22231
=> fix(jupyter): ensure op is available

cli/tsc/dts/lib.deno.ns.d.ts
=> chore: fix typo in docs

cli/args/flags.rs
=> perf: remove duplicate `env::current_dir` call in package.json search

cli/tests/unit/files_test.ts, cli/tsc/dts/lib.deno.ns.d.ts, ext/fs/30_fs.js
=> feat(unstable): `Deno.FsFile.lock[Sync]()` and `Deno.FsFile.unlock[Sync]()`

runtime/ops/os/sys_info.rs
Fixes https://github.com/denoland/deno/issues/21977
=> fix(os): total and free memory in bytes

cli/lsp/testing/execution.rs, cli/tools/test/mod.rs, cli/tools/test/reporters/common.rs, cli/tools/test/reporters/dot.rs, cli/tools/test/reporters/pretty.rs
Extract zero-risk changes from #22226
=> refactor(cli): Add TestFailureDescription

cli/bench/deno_common.js
Missed in https://github.com/denoland/deno/pull/22277
=> bench: fix benchmark

cli/lsp/diagnostics.rs, cli/tests/integration/lsp_tests.rs
=> fix(lsp): disable no-cache diagnostics for jsr specifiers

Cargo.lock, Cargo.toml, cli/js/40_test.js, cli/tests/unit/ops_test.ts, cli/tests/unit/text_encoding_test.ts, cli/tools/test/mod.rs, ext/fs/30_fs.js, ext/net/01_net.js, ext/web/lib.rs, runtime/js/99_main.js
This update brings number of ops available to user code down to 45.
=> chore: upgrade deno_core to 0.259.0

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
These should be our last node v16 actions.
=> chore: bump action versions

Cargo.lock, cli/Cargo.toml
=> fix: handle non-file scopes in synthetic import map

cli/lsp/completions.rs
Fixes #22325. Adds comprehensive tests for parsing the version segment of the specifier.
=> fix(lsp): complete npm specifier versions correctly

Cargo.lock, Cargo.toml, cli/module_loader.rs, cli/standalone/mod.rs, cli/worker.rs, runtime/web_worker.rs, runtime/worker.rs
- Updates to V8 12.1.285.27
https://github.com/denoland/rusty_v8/pull/1383
- Swaps Box for Rc for `source_map_getter`
=> chore: deno_core bump

cli/tools/registry/tar.rs
=> fix(publish): ignore .DS_Store while publishing

ext/node/polyfills/internal/child_process.ts
Fixes https://github.com/denoland/deno/issues/22299
=> fix(ext/node): unimplemented code when not IPC child_process

ext/node/polyfills/_process/process.ts, tests/testdata/info/with_import_map/deno.lock
IIUC, this fixes #18665
Supercedes #20213
CC @kt3k
=> fix(ext/node): permission prompt for missing `process.env` permissions

cli/tsc/dts/lib.deno.unstable.d.ts
Fixes https://github.com/denoland/deno/pull/22280#discussion_r1499615986
=> chore(cli): swap `CreateHttpClientOptions.{cert,key}` descriptions

ext/io/Cargo.toml, ext/io/winpipe.rs
Investigating https://github.com/denoland/deno/issues/22574
Unable to reproduce with a unit test, but assuming that it's a name collision or create pipe/open pipe race, and adding some additional diagnostics.
=> fix(io): create_named_pipe parallelism

cli/args/flags.rs, cli/tools/registry/mod.rs, tests/integration/publish_tests.rs
Closes https://github.com/denoland/deno/issues/22330
=> fix(publish): error if there are uncommitted changes

cli/tsc/dts/lib.deno.unstable.d.ts
=> fix(unstable): add `Date#toTemporalInstant` type

.github/workflows/ci.yml
Will fix the release:
https://github.com/softprops/action-gh-release?tab=readme-ov-file#permissions
=> ci: fix workflow permissions

cli/tools/test/mod.rs
Fixes flake in load_unload test
=> fix(cli): force flush output after test unloads

cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
Caused by https://github.com/denoland/deno/pull/22553
Closes #22664
=> fix(lsp): regression - caching in lsp broken when config with imports has comments

cli/graph_util.rs, cli/main.rs, cli/tools/repl/editor.rs, cli/tools/test/mod.rs, cli/tools/upgrade.rs, ext/http/http_next.rs, tests/integration/bundle_tests.rs
=> chore: fix typos

cli/jsr.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
Closes https://github.com/denoland/vscode_deno/issues/1081.
=> feat(lsp): include registry url in jsr import hover text

ext/node/polyfills/child_process.ts, tests/unit_node/child_process_test.ts, tests/unit_node/testdata/node_modules/foo/check_argv.js
Fixes https://github.com/denoland/deno/issues/21750
=> fix(ext/node): strip `--enable-source-maps` from argv

Cargo.lock, Cargo.toml, ext/fs/30_fs.js, ext/io/12_io.js, ext/node/polyfills/tty.js, runtime/js/40_tty.js, runtime/ops/tty.rs
=> chore: upgrade deno_core

ext/node/polyfills/internal/util/inspect.mjs
Implements https://github.com/nodejs/node/pull/51850
=> feat(node/util): styleText

cli/factory.rs, cli/graph_util.rs, cli/module_loader.rs, cli/tools/bench/mod.rs, cli/tools/lint/mod.rs, cli/tools/registry/mod.rs, cli/tools/test/mod.rs, tests/integration/publish_tests.rs, tests/testdata/publish/sloppy_imports_not_enabled.out
The graph validation errors were displaying cryptically during publish. This fixes that.
=> fix(publish): properly display graph validation errors

cli/lsp/tsc.rs, tests/integration/lsp_tests.rs, tests/testdata/subdir/exports.ts
Fixes https://github.com/denoland/vscode_deno/issues/1068.
=> fix(lsp): don't apply renames to remote modules

cli/tools/registry/tar.rs, tests/integration/publish_tests.rs
Regression from https://github.com/denoland/deno/pull/22720
=> fix(publish): do not include .gitignore

ext/node/polyfills/worker_threads.ts
Addresses [1] mentioned in https://github.com/denoland/deno/issues/22783
=> refactor(ext/node): use worker ops directly in worker_threads

Cargo.lock, Cargo.toml
https://rustsec.org/advisories/RUSTSEC-2024-0003
https://rustsec.org/advisories/RUSTSEC-2024-0020
=> fix: fix crate vulnerabilities

tests/unit_node/testdata/worker_threads2.mjs, tests/unit_node/worker_threads_test.ts
Follow up to https://github.com/denoland/deno/pull/22815
=> test(ext/node): add worker_threads test for SharedArrayBuffer

runtime/web_worker.rs, runtime/worker.rs
=> chore: explicitly type `state.put` for permissions

tests/specs/mod.rs, tests/util/server/src/assertions.rs, tests/util/server/src/builders.rs, tests/util/server/src/fs.rs
=> chore: improve spec tests output

ext/node/ops/crypto/mod.rs, tests/unit_node/crypto/crypto_key_test.ts
Ref https://github.com/denoland/deno/pull/22511
=> fix(ext/node):  DH (`dhKeyAgreement`) support for `createPrivateKey`

ext/webgpu/01_webgpu.js, tests/util/server/src/lib.rs
=> fix: typo in error from GPUBuffer.prototype.mapAsync

ext/node/ops/crypto/mod.rs, ext/node/polyfills/internal/crypto/diffiehellman.ts, ext/node/polyfills/internal/crypto/types.ts, ext/node/polyfills/internal/crypto/util.ts, tests/unit_node/crypto/crypto_key_test.ts
Towards https://github.com/denoland/deno/issues/22921
=> fix(ext/node): support public key point encoding in ECDH.generateKeys()

ext/node/polyfills/v8.ts, tests/unit_node/v8_test.ts
Fixes https://github.com/denoland/deno/issues/22971
=> fix(node): implement v8 serialize and deserialize

ext/node/polyfills/process.ts, tests/unit_node/process_test.ts
Closes https://github.com/denoland/deno/issues/22992
=> fix(ext/node): add process.setSourceMapsEnabled noop

ext/node/polyfills/_fs/_fs_watch.ts, runtime/js/40_fs_events.js, tests/unit_node/_fs/_fs_watch_test.ts
Fixes https://github.com/denoland/deno/issues/22973
=> fix(ext/node): FsWatcher ref and unref

ext/node/polyfills/_events.mjs, ext/node/polyfills/events.ts, tests/unit_node/events_test.ts
=> fix(ext/node): implement EventEmitterAsyncResource

ext/node/polyfills/internal/timers.mjs, tests/unit_node/timers_test.ts
Fixes https://github.com/denoland/deno/issues/22997
=> fix(ext/node): spread args in setImmediate

runtime/js/99_main.js
Fixes https://github.com/denoland/deno/issues/23004
=> fix: do not memoize `Deno.ppid`

tests/unit_node/zlib_test.ts
Closes https://github.com/denoland/deno/issues/22898
=> chore: ignore flaky brotli test

ext/node/polyfills/crypto.ts
Alias for `crypto.webcrypto.getRandomValues`
=> fix(ext/node): add crypto.getRandomValues

ext/node/polyfills/crypto.ts
Alias for `crypto.webcrypto.subtle`. https://nodejs.org/api/crypto.html#cryptosubtle
=> fix(ext/node): add crypto.subtle

cli/args/flags.rs, cli/lsp/testing/execution.rs, cli/main.rs, cli/mainrt.rs, cli/standalone/binary.rs
=> perf(cli): use args_os

ext/node/polyfills/internal/child_process.ts, tests/unit_node/child_process_test.ts
Fixes https://github.com/denoland/deno/issues/23045
=> fix(ext/node): handle `null` in stdio array

cli/tools/jupyter/jupyter_msg.rs, cli/tools/jupyter/server.rs, tests/integration/jupyter_tests.rs
Fixes https://github.com/denoland/deno/issues/20847
@bartlomieju I couldn't find a way to add tests for this.
Would appreciate some help here, thanks.
=> fix(kernel): Do not increase counter if store_history=false

cli/lsp/analysis.rs, tests/integration/lsp_tests.rs
=> fix(lsp): prefer cache over tsc quick fixes

runtime/js/99_main.js, tests/specs/future/runtime_api/__test__.jsonc, tests/specs/future/runtime_api/main.js, tests/specs/future/runtime_api/main.out
Continues work from #23075. Towards #23089.
=> FUTURE(ext/fs): remove `Deno.FsFile.rid`

ext/node/polyfills/internal/child_process.ts, tests/unit_node/child_process_test.ts
Fixes https://github.com/denoland/deno/issues/23051
=> fix(ext/node): support stdin: "inherit" in node:child_process

ext/node/ops/require.rs
=> fix(node): remove unwrap in op_require_node_module_paths

tests/integration/jupyter_tests.rs
There's a TOCTOU issue that can happen when selecting unused ports for the server to use (we get assigned an unused port by the OS, and between then and when the server actually binds to the port another test steals it). Improve this by checking if the server existed soon after setup, and if so we retry starting it. Client connection can also fail spuriously (in local testing) so added a retry mechanism.
This also fixes a hang, where if the server exited (almost always due to the issue described above) before we connected to it, attempting to connect our client ZMQ sockets to it would just hang. To resolve this, I added a timeout so we can't wait forever.
=> chore: Make jupyter integration tests less flaky and avoid hang

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/issues/420
* https://github.com/denoland/deno_graph/pull/424
=> fix: deno_graph 0.69.10

cli/main.rs, cli/mainrt.rs, cli/standalone/binary.rs, cli/standalone/mod.rs
Was investigating a stack overflow in one of my personal projects and cleaned this up while debugging.
=> refactor: cleanup main entrypoint

Cargo.lock, Cargo.toml
Includes https://github.com/denoland/deno_media_type/pull/7
=> perf: reduce allocations in `MediaType::from_specifier`

cli/lsp/analysis.rs, cli/lsp/completions.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs, tests/util/server/src/builders.rs
=> feat(lsp): respect nested deno.json for fmt and lint config

ext/node/polyfills/worker_threads.ts
=> refactor(ext/node): remove worker_threads dependency on ext:runtime

.gitmodules
This is a particularly large repo and making it shallow improves checkout time.
=> chore: Make WPT repo shallow

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
https://github.com/actions/runner-images/issues/9626
=> chore: try to fix mac runner

runtime/permissions/prompter.rs
Followup to https://github.com/denoland/deno/pull/23184
=> fix(runtime): fix Windows permission prompt

ext/node/polyfills/01_require.js, tests/unit_node/module_test.ts
Fixes https://github.com/denoland/deno/issues/22731
=> fix(ext/node): Add "module" to builtinsModule

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
=> fix(ext/node): hostname is valid IPv4 addr

cli/lsp/config.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs, tests/util/server/src/builders.rs, tests/util/server/src/lsp.rs
=> fix(lsp): respect DENO_FUTURE for BYONM config

cli/tsc/99_main_compiler.js
This reverts commit b74a4f29f20c2435ea7c6d192353c1e99760edb0 (#23258). cc @nathanwhit
This improved heap usage but sometimes caused the entire module graph to be loaded back into the isolate.
=> Revert "perf(lsp): Don't retain `SourceFileObject`s in `sourceFileCache` longer than necessary (#23258)"

cli/lsp/documents.rs, cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js
=> perf(lsp): don't pass remote modules as tsc roots

ext/node/polyfills/worker_threads.ts, ext/web/13_message_port.js, runtime/js/99_main.js, tests/integration/worker_tests.rs, tests/testdata/workers/node_worker_message_port_unref.mjs, tests/testdata/workers/node_worker_message_port_unref.mjs.out
TODO:
Closes https://github.com/denoland/deno/issues/23252
Closes https://github.com/denoland/deno/issues/23264
=> fix(ext/node): implement MessagePort.unref()

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, cli/npm/managed/cache.rs, cli/tools/vendor/build.rs, cli/tools/vendor/test.rs, cli/util/fs.rs, cli/worker.rs, ext/ffi/callback.rs, ext/ffi/dlfcn.rs, ext/http/http_next.rs, ext/http/service.rs, ext/napi/lib.rs, ext/node/ops/vm_internal.rs, ext/web/stream_resource.rs, rust-toolchain.toml, tests/napi/src/promise.rs
update to Rust 1.77.1
If this PR has any problem, please tell me.
=> chore: update to Rust 1.77.2

cli/npm/managed/mod.rs, tests/specs/README.md, tests/specs/npm/local_dir_no_duplicate_resolution/__test__.jsonc, tests/specs/npm/local_dir_no_duplicate_resolution/deno.json, tests/specs/npm/local_dir_no_duplicate_resolution/main.out, tests/specs/npm/local_dir_no_duplicate_resolution/main.tsx, tests/util/server/src/lib.rs
Just needs a test.
Closes https://github.com/denoland/deno/issues/23317
=> fix(npm): local nodeModulesDir was sometimes resolving duplicates of same package

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/435
Closes https://github.com/denoland/deno/issues/23338
=> fix(publish): incorrect type checking error for rest parameter in an overload

cli/build.rs, cli/lsp/documents.rs, cli/tsc/dts/lib.dom.d.ts, cli/tsc/dts/lib.webworker.d.ts, cli/tsc/mod.rs, ext/node/polyfills/internal/util/inspect.mjs, ext/websocket/lib.deno_websocket.d.ts
=> chore: remove repetitive words

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/436
Closes https://github.com/denoland/deno/issues/23334
=> fix(publish): handle definite assignment on ts private properties

Cargo.lock, Cargo.toml, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/440
Closes https://github.com/denoland/deno/issues/23331
=> fix(publish): do not error for param with initializer before required parameter

ext/node/polyfills/async_hooks.ts, tests/unit_node/async_hooks_test.ts
Ref https://github.com/denoland/deno/issues/23263
=> fix(ext/node): add stub for AsyncResource#asyncId()

cli/lsp/analysis.rs
=> fix(lsp): slice strings by byte index in code actions

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Forgot to add the step to clone the new submodule added in #23395 😅.
=> fix(ci): Fix bench job

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/emit.rs, cli/tools/repl/session.rs, runtime/shared.rs
* https://github.com/denoland/deno_graph/pull/446
Closes https://github.com/denoland/deno/issues/23388
=> fix(publish): support import equals

tests/testdata/node/rejection_handled_web_process.ts, tests/testdata/run/rejection_handled.ts
Fixes flakiness for rejection handled tests on Windows (7 failures in the past day).
=> test: deflake tests for rejection handled

cli/napi/js_native_api.rs
Removes `.unwrap()` calls from fallible conversion and replaces
with graceful error returns.
=> fix(ext/node): remove unwraps from fallible conversions

.dprint.json, Cargo.lock, cli/Cargo.toml
https://github.com/dprint/dprint-plugin-typescript/pull/628
Closes https://github.com/denoland/deno/issues/23438
=> fix(fmt): error for more unterminated nodes

tests/specs/README.md, tests/specs/schema.json
This makes writing these tests a little easier.
=> chore: auto-complete for __test__.jsonc file

Cargo.lock, cli/Cargo.toml
Closes https://github.com/denoland/deno/issues/23343
=> chore: update deno_config to 0.16.1

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Closes https://github.com/denoland/deno/issues/23432
=> fix(ext/node): define http.maxHeaderSize

cli/lsp/documents.rs
Instead of splitting it into `&dyn deno_graph::source::Resolver` and `&dyn deno_graph::source::NpmResolver`. This simplifies signatures a lot. Also store `Document::resolver` and `Document::config`. This also simplifies update signatures and would have been helpful for debugging a couple times.
I was working on not storing sources for unopened documents since they should generally only be loaded once for tsc, but it turned out to be not worth the complexity of preventing redundant loads etc. Factored out these changes.
=> refactor(lsp): use CliGraphResolver in documents params

ext/net/02_tls.js, tests/unit/serve_test.ts
=> fix(ext/net): check for TLS using undefined rather than using ReflectHas

cli/Cargo.toml
The `cargo-publish` CI is failing https://github.com/denoland/deno/actions/runs/8830423538/job/24243524040#step:7:5180
=> chore: fix cargo publish CI

tests/util/server/src/npm.rs, tests/util/server/src/servers/mod.rs
Required for https://github.com/denoland/deno/pull/23560
=> test: cleanup npm test registry code

ext/node/polyfills/worker_threads.ts, ext/web/13_message_port.js, tests/specs/node/worker_threads/__test__.jsonc, tests/specs/node/worker_threads/message_port_removelistener.mjs, tests/specs/node/worker_threads/message_port_removelistener.mjs.out
Closes https://github.com/denoland/deno/issues/23564
=> fix(ext/node): add support for MessagePort.removeListener/off

tests/integration/repl_tests.rs
These were both failing for me from time to time locally.
=> chore: make a couple repl tests less flaky

ext/node/polyfills/_process/process.ts, tests/unit_node/process_test.ts
Closes https://github.com/denoland/deno/issues/23641
=> fix(ext/node): support delete process.env.var

cli/lsp/language_server.rs, tests/integration/lsp_tests.rs, tools/lint.js
=> fix(lsp): always cache all npm packages

tests/integration/watcher_tests.rs, tests/util/server/src/fs.rs, tests/util/server/src/lib.rs
=> chore: maybe make watcher tests less flaky

tests/integration/watcher_tests.rs
https://github.com/denoland/deno/actions/runs/8958830735/job/24603538912
=> chore: maybe make fmt_check_all_files_on_each_change_test less flaky

.dprint.json, Cargo.lock, cli/Cargo.toml
* https://github.com/dprint/dprint-plugin-typescript/pull/633
=> fix(fmt/js): `else` was moved to wrong `if` sometimes when formatting minified code

cli/napi/js_native_api.rs, tests/napi/object_test.js, tests/napi/src/lib.rs, tests/napi/src/object.rs
This change makes DuckDB example work: https://github.com/denoland/deno/issues/23656.
=> fix(ext/node): napi_get_element and napi_set_element work with objects

Cargo.lock, cli/Cargo.toml, tests/specs/jsr/import_jsr_via_https/main.check.out, tests/specs/jsr/import_jsr_via_https/main.info.out, tests/specs/jsr/import_jsr_via_https/main.out, tests/specs/jsr/import_jsr_via_https/main.ts
=> fix(jsr): panic when importing jsr package with deps via https

cli/build.rs, cli/tsc/dts/lib.dom.d.ts, cli/tsc/dts/lib.webworker.d.ts, cli/tsc/dts/typescript.d.ts, tests/unit/version_test.ts
https://github.com/denoland/TypeScript/pull/11
=> fix: upgrade TypeScript from 5.4.3 to 5.4.5

ext/fs/std_fs.rs, runtime/permissions/lib.rs, tests/specs/permission/special/main.js
Fixes [23721](https://github.com/denoland/deno/issues/23721)
=> fix(runtime): allow nul device on windows

cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
=> fix(lsp): completions for using decl identifiers

ext/node/analyze.rs, tests/registry/npm/@denotest/cjs-reexport-same-specifier-in-sub-folder/1.0.0/api.js, tests/registry/npm/@denotest/cjs-reexport-same-specifier-in-sub-folder/1.0.0/index.js, tests/registry/npm/@denotest/cjs-reexport-same-specifier-in-sub-folder/1.0.0/package.json, tests/registry/npm/@denotest/cjs-reexport-same-specifier-in-sub-folder/1.0.0/sub/api.js, tests/registry/npm/@denotest/cjs-reexport-same-specifier-in-sub-folder/1.0.0/sub/index.js, tests/specs/node/cjs_reexport_same_specifier_in_sub_folder/__test__.jsonc, tests/specs/node/cjs_reexport_same_specifier_in_sub_folder/main.out, tests/specs/node/cjs_reexport_same_specifier_in_sub_folder/main.ts
=> fix(node): better cjs re-export handling

Cargo.lock, cli/Cargo.toml, tests/Cargo.toml
* https://github.com/denoland/deno_npm/pull/52
Closes https://github.com/denoland/deno/issues/23776
=> fix(npm): handle null fields in npm registry JSON

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/428
* https://github.com/denoland/deno_doc/pull/575
Closes https://github.com/denoland/deno/issues/23276
=> fix(doc/publish): support expando properties

cli/lsp/code_lens.rs, tests/integration/lsp_tests.rs, tests/util/server/src/lsp.rs
Fixes https://github.com/denoland/vscode_deno/issues/1114.
=> fix(lsp): show reference code lens on methods

Cargo.lock, Cargo.toml
Has some explicit resource management fixes.
=> fix: update swc_ecma_parser to 0.114.1

ext/node/polyfills/async_hooks.ts, tests/unit_node/async_hooks_test.ts
Fixes https://github.com/denoland/deno/issues/23397
=> fix(node): stub `AsyncResource.emitDestroy()`

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_doc/pull/576
Closes #23303
=> fix(doc): --lint - private ref diagnostic was displaying incorrect information

Cargo.lock, cli/Cargo.toml, tests/specs/install/future_install_local_deno/install.out, tests/specs/jsr/deps/main.out, tests/specs/jsr/deps/main_info.out, tests/specs/jsr/import_jsr_via_https/main.out, tests/specs/jsr/subset_type_graph/main.check.out
* https://github.com/denoland/deno_graph/pull/471
* https://github.com/denoland/deno_graph/pull/473
=> perf(jsr): download metadata files as soon as possible and in parallel

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_npm/pull/53
Closes https://github.com/denoland/deno/issues/23862
=> fix(npm): regression deserializing JSON for some npm packages

tests/util/server/src/pty.rs
These repl tests are still a bit flaky. Let's try this.
https://github.com/denoland/deno/actions/runs/9176525869/job/25232001263
=> chore(repl): maybe improve repl test flakiness on the CI

ext/webgpu/byow.rs
Both ports for the BSDs include patches to the same effect.
=> feat: ext/webgpu - add compatibility with {Free,Open}BSD

tests/integration/inspector_tests.rs
=> chore: fix flaky inspector_with_ts_files

cli/args/lockfile.rs, cli/lsp/language_server.rs, cli/module_loader.rs, cli/tools/info.rs, cli/tools/installer.rs, cli/worker.rs
Slight perf regression when updating deno_lockfile in https://github.com/denoland/deno/pull/23979
=> chore: set lockfile as having no content changes after write

cli/lsp/language_server.rs
=> fix(lsp): don't discover deno.json in vendor dir

Cargo.lock, cli/Cargo.toml, cli/args/mod.rs, cli/lsp/analysis.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/tools/lint/mod.rs
* https://github.com/denoland/deno_lint/pull/1271
* https://github.com/denoland/deno_lint/pull/1277
=> feat(lint): add `no-boolean-literal-for-arguments` rule and enable `no-unused-vars` for jsx files

tools/release/release_doc_template.md
Use `@here` instead of `@channel` as it pings everyone sleeping too.
=> chore: update release template

cli/args/flags.rs
The PEM file specified by DENO_CERT can contain multiple certificates (see https://github.com/denoland/deno/blob/13924fdb1b75325b9b6116accb800bd9f567f2c1/cli/args/mod.rs#L722-L742).
Given that it took me to reading through the sources to find the answer, I figured I spare others the searching :)
=> docs(console): More clearly indicate the contents of DENO_CERT

tools/cut_a_release.md
=> docs: clarify release instructions

ext/http/00_serve.ts
=> fix(ext/http): print `[]` around ipv6 addresses

ext/web/02_event.js, tests/wpt/runner/expectation.json, tests/wpt/wpt.ts
=> fix(ext/web): correct string tag for MessageEvent

ext/cache/lib.rs
=> fix: don't panic when cache is not available

cli/napi/js_native_api.rs
whoops. also did a drive-by cleanup of `isolate` usage since i noticed it while using `utf8_length(isolate)`
=> fix: node-api get_value_string_utf8 should use utf8_length

ext/webgpu/byow.rs
Fixes https://github.com/denoland/deno/issues/23433
=> fix(ext/webgpu): fix surface creation panic when adapter not initialized

tests/wpt/runner/expectation.json
=> tests: update wpt

Cargo.lock, Cargo.toml
Fixed via the swc upgrade.
Tests here: https://github.com/denoland/deno_graph/pull/499
Closes #23284
=> fix(no-slow-types): handle named type in mapped type

ext/http/00_serve.ts
Ref https://github.com/denoland/deno/issues/22333#issuecomment-1942424802
=> fix(ext/http): actually await `goAhead` promise

cli/tools/doc.rs
=> fix(docs): correctly resolve href for built-ins

cli/lsp/config.rs, tests/integration/lsp_tests.rs
Follow up to #24206 which broke deno_std intellisense. Aligns with CLI behaviour (is that correct?).
=> fix(lsp): use import map from workspace root

ext/node/polyfills/_process/process.ts, ext/node/polyfills/_process/streams.mjs
=> fix(ext/node): use primordials in `ext/node/polyfills/_process/`

ext/node/polyfills/_brotli.js
=> fix(ext/node): use primordials in `ext/node/polyfills/_brotli.js`

ext/node/ops/blocklist.rs
Removes interior mutability. Ref https://github.com/denoland/deno_core/issues/787
=> chore(ext/node): cleanup net blocklist ops

ext/node/ops/blocklist.rs, ext/node/ops/zlib/mod.rs
Ref https://github.com/denoland/deno_core/pull/793
=> Revert `#[cppgc] &mut T` usage

ext/node/polyfill.rs
Fixes https://github.com/jsr-io/jsr-npm/issues/91
=> fix(node): add missing readline/promises module

ext/node/polyfills/internal/buffer.mjs
https://github.com/denoland/deno/pull/24341#discussion_r1655247367
Reverts denoland/deno#24341
=> Revert "perf: improve Buffer.from(buf) by 29x"

ext/node/polyfills/internal/fixed_queue.ts
=> fix(ext/node): make next tick queue resilient to `Array.prototype` tampering

cli/lsp/resolver.rs
The build broke in https://github.com/denoland/deno/pull/24365.
=> fix(lsp): use CliLockfile

ext/web/06_streams.js, ext/web/README.md, ext/web/lib.rs
ref: https://github.com/denoland/deno_core/issues/135
=> fix(ext/web): use primordials of ES2024 ArrayBuffer transfer

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, cli/args/mod.rs, cli/factory.rs, cli/standalone/binary.rs, cli/tools/registry/mod.rs, cli/tools/registry/unfurl.rs, cli/util/logger.rs, tests/specs/publish/byonm_with_package_json/__test__.jsonc, tests/specs/publish/byonm_with_package_json/jsr.json, tests/specs/publish/byonm_with_package_json/package.json, tests/specs/publish/byonm_with_package_json/publish.out, tests/specs/publish/byonm_with_package_json/src/index.ts
Closes https://github.com/denoland/deno/issues/24430
=> fix(publish): unfurling should always be done with the package json

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, Cargo.toml
=> feat: upgrade deno_core to 0.293.0

tests/specs/npm/npmrc_not_next_to_package_json/__test__.jsonc
override home dir so .npmrc on the dev machine doesn't break it
=> fix: test in presence of .npmrc

.dprint.json, .github/workflows/start_release.yml, .github/workflows/version_bump.yml, .github/workflows/wpt_epoch.yml, tools/format.js
Uses https://github.com/g-plane/pretty_yaml courtesy @g-plane
=> chore: format yaml internally

cli/npm/managed/resolvers/local.rs, tests/specs/npm/lifecycle_scripts/__test__.jsonc, tests/specs/npm/lifecycle_scripts/only_warns_first1.out, tests/specs/npm/lifecycle_scripts/only_warns_first2.out
=> fix(npm): only warn about lifecycle scripts not being run when setting up directory

cli/args/flags.rs, tests/specs/run/netlify_edge_bundler_hack/__test__.jsonc, tests/specs/run/netlify_edge_bundler_hack/main.out, tests/specs/run/netlify_edge_bundler_hack/node_modules/@netlify/edge-bundler/deno/config.ts, tests/specs/run/netlify_edge_bundler_hack/node_modules/@netlify/edge-bundler/package.json, tests/specs/run/netlify_edge_bundler_hack/package.json
Hack for a few months until Deno 2.0. See code for details
=> chore: `@netlify/edge-bundler` workaround until Deno 2.0

Cargo.lock, Cargo.toml
Tests are in https://github.com/denoland/deno_config/pull/81
Closes https://github.com/denoland/deno/issues/24531
=> fix(npm): use start directory deno.json as "root deno.json config" in npm workspace

ext/node/polyfills/01_require.js
node-api is fully supported now.
=> fix: unblock fsevents native module

ext/webgpu/01_webgpu.js
=> fix(ext/webgpu): GPUDevice.createRenderPipelineAsync should return a Promise

Cargo.lock, Cargo.toml, cli/args/lockfile.rs, cli/args/mod.rs, tests/specs/npm/workspace_sub_deno_json/__test__.jsonc, tests/specs/npm/workspace_sub_deno_json/member.out, tests/specs/npm/workspace_sub_deno_json/member/main.ts, tests/specs/npm/workspace_sub_deno_json/member/package.json, tests/specs/npm/workspace_sub_deno_json/member_with_deno_json/deno.jsonc, tests/specs/npm/workspace_sub_deno_json/member_with_deno_json/main.ts, tests/specs/npm/workspace_sub_deno_json/member_with_deno_json/package.json, tests/specs/npm/workspace_sub_deno_json/non_member.out, tests/specs/npm/workspace_sub_deno_json/non_member/deno.json, tests/specs/npm/workspace_sub_deno_json/non_member/deno.lock, tests/specs/npm/workspace_sub_deno_json/non_member/main.ts, tests/specs/npm/workspace_sub_deno_json/package.json
=> fix(config): regression - should not discover npm workspace for nested deno.json not in workspace

cli/tools/registry/mod.rs, tests/integration/publish_tests.rs
```
Checking for slow types in the public API...
Uncommitted changes:
?? deno.json
?? main.ts
error: Aborting due to uncommitted changes. Check in source code or run with --allow-dirty
```
=> fix(publish): show dirty files on dirty check failure

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, ext/node/ops/vm_internal.rs
=> chore: upgrade dependencies

tests/specs/npm/lifecycle_scripts/no_deno_json.out
Failed in https://github.com/denoland/deno/actions/runs/9982978127/job/27589707376
=> chore: fix flakey lifecycle scripts test

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_semver/pull/26
Closes https://github.com/denoland/deno/issues/24550
=> fix(npm): handle packages with only pre-released 0.0.0 versions

Cargo.lock, cli/lsp/analysis.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
=> fix(lsp): rewrite import for 'infer return type' action

Cargo.lock, cli/Cargo.toml, cli/tools/doc.rs, tests/testdata/doc/lint_success_json.out
Ref https://github.com/denoland/deno_doc/pull/616
=> perf: update deno_doc

tests/unit_node/http_test.ts
This PR tries to reduce the flakiness of the test case `[node/http] http.request() post streaming body works`.
=> test(ext/node): reduce http_test flakiness

ext/node/polyfills/internal/crypto/_randomFill.mjs, tests/unit_node/crypto/crypto_misc_test.ts
=> fix(ext/crypto): respect offsets when writing into ab views in randomFillSync

ext/console/01_console.js, tests/unit/console_test.ts
=> fix(ext/console): render properties of Intl.Locale

Cargo.lock, Cargo.toml, cli/main.rs, cli/standalone/mod.rs, ext/node/ops/vm.rs
Includes:
- https://github.com/denoland/deno_core/pull/858
- https://github.com/denoland/deno_core/pull/856
Fixes https://github.com/denoland/deno/issues/24782
Fixes https://github.com/denoland/deno/issues/24825
=> fix: regressions around Error.prepareStackTrace

.dprint.json, Cargo.lock, cli/Cargo.toml
=> fix(fmt): handle using stmt in for of stmt

cli/args/flags.rs, cli/cache/cache_db.rs, cli/lsp/diagnostics.rs, cli/tools/compile.rs, cli/tools/registry/pm.rs, cli/tools/repl/session.rs, cli/tsc/99_main_compiler.js, cli/tsc/dts/lib.deno.unstable.d.ts, ext/node/polyfills/internal/crypto/keys.ts, ext/node/polyfills/internal_binding/handle_wrap.ts, runtime/js/99_main.js
This PR fixes various typos I spotted in the project.
=> docs: fix typos

ext/node/polyfills/_brotli.js, ext/node/polyfills/_http_outgoing.ts, ext/node/polyfills/internal/buffer.mjs, ext/node/polyfills/internal_binding/_utils.ts, ext/node/polyfills/string_decoder.ts, ext/web/lib.rs, tests/unit_node/zlib_test.ts
Reverts denoland/deno#24567
Fixes https://github.com/denoland/deno/issues/24841
=> Revert "perf(ext/node): improve `Buffer` from string performance"

ext/node/polyfills/_brotli.js, tests/unit_node/zlib_test.ts
Fixes https://github.com/denoland/deno/issues/24572
=> fix(ext/node): node:zlib coerces quality 10 to 9.5

ext/canvas/lib.deno_canvas.d.ts
This PR documents public Canvas APIs
=> docs(ext/canvas): document public Canvas APIs

Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno/issues/24898
=> fix: errors with CallSite methods

cli/http_util.rs
If the "size hint" does not provide a value, fall back to using a "Content-Length"
header.
=> fix(upgrade): fallback to Content-Length header for progress bar

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Closes https://github.com/denoland/deno/issues/22820
=> fix(ext/node): client closing streaming request shouldn't terminate http server

cli/args/flags.rs, cli/main.rs, tests/specs/clean/general/__test__.jsonc
Closes https://github.com/denoland/deno/issues/3437 (we can follow up with more features later)
Co-authored-by: Satya Rohith <me@satyarohith.com>
=> feat: deno clean

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_semver/pull/30
=> fix(add): better error message providing scoped pkg missing leading `@` symbol

ext/node/polyfills/_brotli.js, tests/unit_node/zlib_test.ts
Fixes https://github.com/denoland/deno/issues/24416
=> fix(ext/node): createBrotliCompress params

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Fixes #24987
Follow-on to https://github.com/denoland/deno/pull/24216/files#r1642188672
=> fix(ext/node): don't concat set-cookie in ServerResponse.appendHeader

cli/tools/upgrade.rs
This commit fixes output of `deno upgrade` subcommand,
by displaying proper version numbers. Before this PR we were
prepending "v" before the canary version hash, which was
obviously wrong.
=> fix(upgrade): use proper version display

cli/args/mod.rs, cli/worker.rs, tests/integration/watcher_tests.rs
=> fix(cli): support --watch when running cjs npm packages

tests/integration/serve_tests.rs
MacOS tends to not distribute evenly, so just don't assert that requests were served by > 1 worker on mac.
Also added a check that all workers start, so we at least check that on macos.
=> chore: Disable part of parallel serve test on macos (flaky)

cli/lsp/completions.rs, tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/1143.
=> fix(lsp): include scoped import map keys in completions

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Closes https://github.com/denoland/deno/issues/25117
=> fix(ext/node): pass content-disposition header as string instead of bytes

cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
=> chore(lsp): use 'install' terminology for jsr and npm packages

ext/websocket/02_websocketstream.js
Fixes https://github.com/denoland/deno/issues/25077
=> fix(ext/websocket): unhandled close rejection in WebsocketStream

Cargo.lock, ext/kv/Cargo.toml, ext/kv/sqlite.rs
This will help with build perf a bit.
=> chore(build): deno_kv - remove dep on deno_node

cli/schemas/config-file.v1.json
* The default value of `"experimentalDecorators"` is set to `false`
* The missing options are added
=> chore: Update config-file.v1.json

cli/npm/managed/resolvers/local.rs, cli/util/fs.rs, tests/specs/install/move_after_install/__test__.jsonc, tests/specs/install/move_after_install/test-project/main.mjs, tests/specs/install/move_after_install/test-project/package.json
Fixes https://github.com/denoland/deno/issues/25161
=> fix(install): Use relative symlinks in deno install

ext/crypto/import_key.rs, tests/unit/webcrypto_test.ts
Fixes https://github.com/denoland/deno/issues/20931
=> fix(ext/crypto): throw DataError for invalid EC key import

ext/fetch/proxy.rs
=> fix(ext/fetch): percent decode userinfo when parsing proxies

tests/wpt/runner/expectation.json, tests/wpt/runner/utils.ts
=> tests: fix wpt_epoch job

Cargo.lock, Cargo.toml, tests/testdata/run/heapstats.js.out
- fix for https://github.com/denoland/deno/issues/25160
- disables pointer compression to fix https://github.com/denoland/deno/issues/24057
- changes needed to land https://github.com/denoland/deno/pull/25140
=> fix: upgrade deno_core to 0.307.0

ext/node/lib.rs, ext/node/polyfills/_next_tick.ts, ext/node/polyfills/async_hooks.ts, ext/web/02_timers.js, tests/unit_node/async_hooks_test.ts
This reverts commit 71ca61e189cca9215982ce4598b7a4da8430c584.
Now uses a shared implementation from deno_core.
=> fix: reland async context

Cargo.lock, cli/Cargo.toml
contains a small fix for docs.deno.com related to descriptions
=> fix: update deno_doc

tests/unit_node/crypto/crypto_key_test.ts, tools/lint.js
I accidentally broke this earlier.
=> chore: fix linting

Cargo.lock, cli/Cargo.toml
Not strictly necessary, but bumping for good measure :))
=> v2.0.0-rc.0

cli/tsc/dts/lib.deno.ns.d.ts, ext/node/polyfills/internal_binding/cares_wrap.ts
Closes https://github.com/denoland/deno/issues/15207
=> fix(BREAKING): make dns record types have consistent naming

ext/console/01_console.js
Aligns the error messages in the console extension to be in-line with the Deno style guide.
=> refactor(ext/console): align error messages

cli/args/flags.rs, tests/integration/test_tests.rs, tests/testdata/test/sanitizer/ops_sanitizer_unstable.out
=> BREAKING: remove `--trace-ops`

ext/web/lib.deno_web.d.ts
Related https://github.com/denoland/deno/pull/24599
=> BREAKING(ext/web): remove remaining web types for compatibility

cli/args/flags.rs, cli/args/mod.rs, cli/tools/test/mod.rs, tests/specs/test/no_files/__test__.jsonc, tests/specs/test/no_files/allow_none.out
=> BREAKING: remove `--allow-none` flag

cli/npm/managed/resolvers/local.rs, cli/resolver.rs, tests/integration/run_tests.rs, tests/specs/npm/lifecycle_scripts/all_lifecycles_not_run.out, tests/specs/npm/lifecycle_scripts/future_install_all_lifecycles_not_run.out, tests/specs/npm/lifecycle_scripts/node_gyp_not_run.out, tests/specs/npm/lifecycle_scripts/only_warns_first1.out, tests/specs/publish/bare_node_builtins/bare_node_builtins.out, tests/testdata/run/node_prefix_missing/feature_enabled.out, tests/testdata/run/node_prefix_missing/main.ts.out_feature_enabled
=> fix: make some warnings more standard

cli/tsc/dts/lib.deno.ns.d.ts, runtime/js/40_tty.js, tests/unit/tty_test.ts
=> chore(tty): soft-remove `Deno.isatty()`

Cargo.lock, cli/Cargo.toml, cli/graph_util.rs
=> chore(cli): remove deno_emit dependency

runtime/ops/process.rs, runtime/permissions/lib.rs, tests/specs/compile/permissions_denied/main.out, tests/specs/permission/path_not_permitted/main.out, tests/specs/permission/path_not_permitted/main.ts, tests/specs/permission/path_not_permitted/sub.ts, tests/testdata/run/089_run_allow_list.ts.out
Regression from https://github.com/denoland/deno/pull/25370
=> fix(regression): do not expose resolved path in Deno.Command permission denied error

ext/crypto/00_crypto.js
Aligns the error messages in the ext/crypto folder to be in-line with the Deno style guide.
=> refactor(ext/crypto): align error messages

cli/tsc/dts/lib.deno.ns.d.ts, ext/fs/30_fs.js, runtime/js/99_main.js, tests/specs/future/runtime_api/main.js, tests/specs/future/runtime_api/main.out, tests/unit/files_test.ts
=> BREAKING(fs): remove `Deno.File`

cli/args/flags.rs, cli/main.rs, cli/tools/installer.rs, tests/integration/install_tests.rs
Close https://github.com/denoland/deno/issues/25457
=> feat(uninstall): alias to 'deno remove' if -g flag missing

cli/tsc/dts/lib.deno.ns.d.ts, ext/fs/30_fs.js
=> BREAKING(fs): disallow `new Deno.FsFile()`

cli/npm/managed/resolvers/local.rs, tests/specs/install/workspace_node_modules_not_exists/__test__.jsonc, tests/specs/install/workspace_node_modules_not_exists/deno.json, tests/specs/install/workspace_node_modules_not_exists/install.out, tests/specs/install/workspace_node_modules_not_exists/package1/package.json, tests/specs/install/workspace_node_modules_not_exists/package2/package.json
Fixes https://github.com/denoland/deno/issues/25493
=> fix(install): Make sure target node_modules exists when symlinking

cli/tsc/dts/lib.deno.ns.d.ts, ext/io/12_io.js, tests/unit/files_test.ts, tests/unit_node/process_test.ts, tests/unit_node/tty_test.ts
=> chore: soft-remove `Deno.{stdin,stderr,stdout}.rid`

Cargo.lock, cli/Cargo.toml, cli/tools/fmt.rs
=> fix(fmt): fix tabs in YAML

tests/unit_node/async_hooks_test.ts
The fix is in https://github.com/denoland/deno_core/pull/888
Fixes: https://github.com/denoland/deno/issues/25275
=> fix: add test ensuring als works across dynamic import

tests/specs/run/workspaces/explicit_import_map/__test__.jsonc, tests/specs/run/workspaces/explicit_import_map/install.out, tests/specs/run/workspaces/explicit_import_map/main.out
=> chore: enable `specs::run::workspaces::explicit_import_map` test

cli/args/flags.rs
closes https://github.com/denoland/deno/issues/11547
=> feat(flags): support user provided args in repl subcommand

runtime/ops/runtime.rs, tests/integration/run_tests.rs
Closes https://github.com/denoland/deno/issues/7315.
=> feat(permissions): `Deno.mainModule` doesn't require permissions

runtime/js/40_fs_events.js
Fixes CI https://github.com/denoland/deno/actions/runs/10892648144/job/30225971485
=> chore: lint `40_fs_events.js`

.dprint.json, Cargo.lock, cli/Cargo.toml, cli/tools/fmt.rs, ext/node/polyfills/_fs/_fs_access.ts, ext/node/polyfills/_fs/_fs_chown.ts, ext/node/polyfills/_fs/_fs_lchown.ts, ext/node/polyfills/child_process.ts, ext/node/polyfills/https.ts, tests/testdata/repl/import_type.ts, tests/testdata/run/import_type.ts
=> feat(fmt): sort type-only named import/exports last

cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, tests/integration/lsp_tests.rs
=> feat(lsp): auto-import types with 'import type'

cli/args/mod.rs, tests/specs/permission/deny_run_binary_absolute_path/main.out, tests/specs/run/allow_run_insecure_warnings/no_allow_list.out, tests/testdata/run/deny_some_permission_args.out
Ref https://github.com/denoland/deno/pull/25215#discussion_r1762064605
=> feat: update warning message for --allow-run with no list

tests/specs/upgrade/canary/__test__.jsonc
=> tests: fix upgrade canary test

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/lsp/config.rs, cli/schemas/config-file.v1.json, cli/tsc/99_main_compiler.js, tests/specs/check/no_implicit_override/__test__.jsonc, tests/specs/check/no_implicit_override/main.out, tests/specs/check/no_implicit_override/main.ts, tests/unit/url_search_params_test.ts
<s>Depends on https://github.com/denoland/deno_config/pull/115.</s>
Closes https://github.com/denoland/deno/issues/11836
Ref https://github.com/denoland/deno/issues/25162
=> feat(check): turn on noImplicitOverride

Cargo.lock, cli/Cargo.toml, tests/specs/lint/node_globals_no_duplicate_imports/__test__.jsonc, tests/specs/lint/node_globals_no_duplicate_imports/lint.out, tests/specs/lint/node_globals_no_duplicate_imports/main.out, tests/specs/lint/node_globals_no_duplicate_imports/main.ts
Ref https://github.com/denoland/deno_lint/commit/6085f0111aa8c1c418a30d1b6f5108e88cb74b80
Closes https://github.com/denoland/deno/issues/25679
=> feat(lint): add `no-process-global` lint rule

.github/workflows/promote_to_release.yml
This CI action was using wrong variable to create release directory.
=> ci: fix 'promote_to_release' script

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
All these changes made CI fail consistently with random exit code 1 after
successful upload.
=> ci: revert changed to canary uploads

ext/web/02_event.js, tests/unit/event_target_test.ts
Fixes https://github.com/denoland/deno/issues/25787
=> fix(ext/web): acknowledge the capture option on EventTarget.removeEventListener

tests/specs/run/no_deno_json/__test__.jsonc, tests/specs/run/no_deno_json/code/install.out, tests/specs/run/no_deno_json/code/sub_dir/main.out
Towards https://github.com/denoland/deno/issues/25241
=> tests: enable auto_discovered tests of run/no_deno_json

ext/node/polyfills/net.ts
Fixes https://github.com/denoland/deno/issues/25844
=> fix(ext/node): fix process.stdin.pause()

cli/graph_util.rs
Uses:
* https://github.com/denoland/deno_graph/pull/528
=> refactor: use ModuleGraph::fill_from_lockfile

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
This reverts commit 0f617be84a8e9edf73803210c24af43f729a97de.
Reverting because it was an experiment.
=> Revert "ci: use macos-14-xlarge on 'main' branch (#25908)"

cli/factory.rs, cli/module_loader.rs, cli/resolver.rs, cli/worker.rs, runtime/examples/extension/main.rs, runtime/web_worker.rs, runtime/worker.rs
First two points on: https://github.com/denoland/deno/issues/25634
=> refactor: cleanup for creating worker structs

Cargo.lock, Cargo.toml, tests/specs/npm/require_type_commonjs/main.out
See https://github.com/denoland/deno_ast/pull/278
Fixes https://github.com/denoland/deno/issues/25810
=> fix: precompile preserve SVG camelCase attributes

tools/release/promote_to_release.ts
Fixes https://github.com/denoland/deno/issues/25940
Forgot to update patchver scripts to latest sui. Ref #25942
=> fix: update patchver to 0.2

Cargo.lock, Cargo.toml, cli/cache/deno_dir.rs, cli/cache/mod.rs, cli/factory.rs, cli/file_fetcher.rs, cli/lsp/cache.rs, tests/integration/jsr_tests.rs, tests/specs/info/flag/041_info_flag.out, tests/specs/info/flag_location/041_info_flag_location.out, tests/specs/info/json/info_json.out, tests/specs/info/json_location/info_json_location.out
Closes https://github.com/denoland/deno/issues/25967
Closes #25968
=> BREAKING: rename "deps" remote cache folder to "remote"

Cargo.lock, Cargo.toml, cli/Cargo.toml
=> fix(workspace): handle when config has members when specified via --config

tests/napi/uv_test.js
Will re-enable once I figure out the issue
=> chore: disable flaky uv_test.js for now

Cargo.toml
Fixes https://github.com/denoland/deno/issues/25922
=> fix: enable `Win32_Security` feature in `windows-sys`

Cargo.lock, Cargo.toml
https://github.com/denoland/deno_npm/pull/70
Fixes https://github.com/denoland/deno/issues/26006
=> fix(npm): root package has peer dependency on itself 

cli/npm/byonm.rs, cli/npm/managed/mod.rs, cli/npm/managed/resolvers/common.rs, cli/npm/managed/resolvers/global.rs, cli/npm/managed/resolvers/local.rs, ext/node/lib.rs, ext/node/ops/require.rs, ext/node/ops/worker_threads.rs, runtime/permissions/lib.rs, runtime/snapshot.rs, tests/unit/permissions_test.ts
Does less work when requesting permissions with `-A`
=> refactor: improve node permission checks

.devcontainer/Dockerfile, .github/workflows/cargo_publish.yml, .github/workflows/ci.generate.ts, .github/workflows/ci.yml
It shouldn't be needed anymore
=> chore: remove protoc dep from CI

ext/console/01_console.js, tests/unit/console_test.ts
Fixes https://github.com/denoland/deno/issues/26047
=> fix(console): missing cause property on non-error objects

ext/node/polyfills/_fs/_fs_read.ts, tests/unit_node/fs_test.ts
Closes https://github.com/denoland/deno/issues/26054
=> fix(ext/node): internal buffer length in readSync

tests/wpt/runner/expectation.json
=> fix: disable same-origin.html WPT

Cargo.lock, Cargo.toml, tests/integration/run_tests.rs
A test is going to fail on windows (I'm not on a windows machine atm, so running the CI to see what fails)
Closes #26080
=> fix: do not panic on wsl share file paths on windows

runtime/js/10_permissions.js, tests/specs/permission/allow_import_worker/__test__.jsonc, tests/specs/permission/allow_import_worker/denied.out, tests/specs/permission/allow_import_worker/main.ts, tests/specs/permission/allow_import_worker/main_denied.ts, tests/specs/permission/allow_import_worker/worker.ts
We only had integration tests for this and not an integration test.
Closes #26074
=> fix(unstable/worker): ensure import permissions are passed

cli/lsp/completions.rs, tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/1176.
=> fix(lsp): relative completions for bare import-mapped specifiers

cli/napi/node_api.rs, tests/napi/src/tsfn.rs
Fixes https://github.com/denoland/deno/issues/26228
=> fix(ext/napi): pass user context to napi_threadsafe_fn finalizers

ext/node/ops/crypto/keys.rs, tests/unit_node/crypto/crypto_key_test.ts
Fixes https://github.com/denoland/deno/issues/26188
=> fix(ext/node): compute pem length (upper bound) for key exports

cli/tools/info.rs, tests/specs/npm/info_chalk_json/cjs_with_deps/main_info_json.out, tests/specs/npm/info_chalk_json_node_modules_dir/cjs_with_deps/main_info_json.out, tests/specs/npm/info_cli_chalk_json/info/chalk_json.out, tests/specs/npm/info_peer_deps_json/peer_deps_with_copied_folders/main_info_json.out, tests/specs/npm/npmrc/__test__.jsonc, tests/specs/npm/npmrc/info.out
=> feat(cli): improve deno info output for npm packages

cli/worker.rs, tests/specs/run/remote_cjs_main/__test__.jsonc, tests/specs/run/remote_cjs_main/output.out, tests/testdata/run/add.cjs
Instead error.
Closes https://github.com/denoland/deno/issues/26258
=> fix: do not panic running remote cjs module

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, cli/lsp/tsc.rs, cli/npm/common.rs, cli/util/fs.rs, runtime/permissions/prompter.rs, rust-toolchain.toml, tests/integration/compile_tests.rs
=> chore: upgrade to rust 1.81.0

.github/workflows/cargo_publish.yml
Fixes https://github.com/denoland/deno/issues/23161
=> chore: Ensure only one cargo publish can run

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_npm/pull/71
Closes #26271
=> fix(install): handle pkg with dep on self when pkg part of peer dep resolution

ext/console/01_console.js
=> fix(ext/console): apply coloring for console.table

runtime/fmt_errors.rs, tests/specs/run/import_common_js/__test__.jsonc, tests/specs/run/import_common_js/exports_error.out, tests/specs/run/import_common_js/require_error.js, tests/specs/run/import_common_js/require_error.out, tests/specs/run/package_json_type/commonjs/main_mix.out, tests/specs/run/package_json_type/none/main_cjs.out
Ref https://github.com/denoland/deno/issues/26225
=> fix: improve suggestions and hints when using CommonJS modules

Cargo.lock, cli/Cargo.toml, cli/main.rs
I've been using dhat for tracking allocations and it might be useful to just have this in the Deno repo?
=> chore: add dhat feature

ext/node/polyfills/child_process.ts, ext/node/polyfills/internal/child_process.ts, tests/unit_node/child_process_test.ts
Closes https://github.com/denoland/deno/issues/25899
=> fix(child_process): map node `--no-warnings` flag to `--quiet`

cli/bench/lsp.rs, cli/bench/lsp_bench_standalone.rs, cli/lsp/capabilities.rs, cli/lsp/client.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/lsp/lsp_custom.rs, tests/integration/lsp_tests.rs
Relands #26215, reverted in #26320. With benches fixed.
=> Reland feat(lsp): deno/didRefreshDenoConfigurationTree notifications

runtime/permissions/lib.rs
=> feat(permissions): expose PromptResponse

ext/node/ops/winerror.rs, ext/node/polyfills/_fs/_fs_readlink.ts
=> fix(ext/node): properly map reparse point error in readlink

ext/node/polyfills/https.ts
Towards https://github.com/denoland/deno/issues/24236
=> fix(ext/node): use primordials in `ext/node/polyfills/https.ts`

cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs, tests/util/server/src/lsp.rs
Closes #26326. Implements ctrl+clickable inlay type hints.
=> feat(lsp): interactive inlay hints

cli/lsp/diagnostics.rs, tests/integration/lsp_tests.rs
=> fix(lsp): import-map-remap quickfix for type imports

Cargo.lock, cli/Cargo.toml, cli/tools/fmt.rs
=> fix(fmt): upgrade formatters

.github/workflows/cargo_publish.yml, .github/workflows/ci.generate.ts, .github/workflows/ci.yml, .github/workflows/promote_to_release.yml, .github/workflows/start_release.yml, .github/workflows/version_bump.yml, .github/workflows/wpt_epoch.yml
https://github.com/denoland/deno/issues/26447
Updated setup-deno.
=> ci: version up setup-deno@1 -> setup-deno@2

Cargo.toml
Fixes https://github.com/denoland/deno/issues/26455
=> fix: unpin tokio version

cli/args/flags.rs, tests/specs/lockfile/frozen_lockfile/__test__.jsonc
Fixes https://github.com/denoland/deno/issues/26391
=> fix(check): support `--frozen` on deno check

cli/schemas/config-file.v1.json
Closes https://github.com/denoland/deno/issues/26510
=> fix: add 'fmt-component' to unstable features in schema file

tests/util/server/src/builders.rs, tests/util/server/src/fs.rs, tests/util/server/src/lib.rs, tests/util/server/src/lsp.rs, tests/util/server/src/npm.rs, tests/util/server/src/pty.rs, tests/util/server/src/servers/hyper_utils.rs, tests/util/server/src/servers/mod.rs, tests/util/server/src/servers/ws.rs
Accidentally added in https://github.com/denoland/deno/pull/26473/files
=> chore: remove print debugging from test server

cli/tools/registry/pm/cache_deps.rs
Temporary fix for #26509, so people don't get errors.
=> fix(install): don't cache json exports of JSR packages (for now)

Cargo.lock, Cargo.toml
Closes https://github.com/denoland/deno/issues/26189
Closes https://github.com/denoland/deno/issues/26575
=> fix: do not panic when failing to write to http cache

ext/node/polyfills/http.ts, ext/node/polyfills/internal/dns/utils.ts, ext/node/polyfills/internal_binding/cares_wrap.ts, ext/node/polyfills/net.ts, tests/unit_node/http_test.ts, tests/unit_node/tls_test.ts
This reverts commit d59599fc187c559ee231882773e1c5a2b932fc3d.
closes #26588 
Merge on approval
=> Revert "fix(ext/node): fix dns.lookup result ordering (#26264)"

ext/node/polyfills/http.ts
Fixes https://github.com/denoland/deno/issues/26642
=> fix(ext/node): return `this` from `http.Server.ref/unref()`

cli/lsp/config.rs, cli/lsp/language_server.rs, cli/lsp/resolver.rs, tests/integration/lsp_tests.rs
=> fix(lsp): include unstable features from editor settings

.dprint.json, Cargo.lock, cli/Cargo.toml
Fix #26245 
Close #26324 
Fix #26508 
Fix #26540 
Fix #26562
=> fix(fmt): fix several HTML and components issues

cli/args/mod.rs, cli/args/package_json.rs, cli/npm/managed/mod.rs, tests/specs/install/invalid_scheme/__test__.jsonc, tests/specs/install/invalid_scheme/install.out, tests/specs/install/invalid_scheme/package.json, tests/specs/run/package_json/invalid_value/add.out, tests/specs/run/package_json/invalid_value/install.out
Related: https://github.com/denoland/deno/issues/26653
=> fix: surface package.json location on dep parse failure

ext/node/polyfills/_fs/_fs_readFile.ts
Fixes the original issue reported in #26404. storybook runs into other errors after this PR (the new errors will be fixed in other PRs).
Some code used by a dependency of storybook does a [string comparison on the error message](https://github.com/chromaui/chromatic-cli/blob/ce30b2be343cb96a0826390b95ea42befb2be547/node-src/lib/getConfiguration.ts#L88-L92) thrown here to check for a file not found error.
=> fix(ext/node): convert errors from `fs.readFile/fs.readFileSync` to node format

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, cli/tools/info.rs, ext/node/ops/crypto/sign.rs, runtime/permissions/prompter.rs, rust-toolchain.toml, tests/napi/src/async.rs, tests/specs/future/unstable_flags/main.js, tests/specs/future/unstable_flags/main.out
Upgrade to rust 1.82 and LLVM 19 . Removes one webusb test because `requestAdapter` not working on new ubuntu 24 runners
=> chore: upgrade to rust 1.82 and LLVM 19

cli/lsp/language_server.rs
=> perf(lsp): don't walk coverage directory

cli/bench/encode_into.js, cli/bench/getrandom.js, cli/bench/op_now.js, cli/bench/secure_curves.js, cli/bench/tty.js, cli/bench/url_parse.js, cli/bench/write_file.js, ext/node/polyfills/_fs/_fs_common.ts, ext/node/polyfills/_fs/_fs_open.ts, ext/node/polyfills/_fs/_fs_readv.ts, ext/node/polyfills/internal/crypto/keygen.ts, ext/node/polyfills/internal/crypto/random.ts, ext/node/polyfills/internal_binding/http_parser.ts, ext/node/polyfills/vm.js, runtime/js/99_main.js, tests/node_compat/test/fixtures/child-process-spawn-node.js, tests/unit/globals_test.ts, tools/lint.js, tools/util.js
related https://github.com/denoland/deno_third_party/pull/126
=> chore: update dlint to v0.68.0 for internal

cli/tools/fmt.rs, tests/specs/fmt/yaml/__test__.jsonc, tests/specs/fmt/yaml/ignore_file.yaml, tests/specs/fmt/yaml/ignore_file2.yaml, tests/specs/fmt/yaml/ignore_file3.yaml, tests/specs/fmt/yaml/ignore_file4.yaml, tests/specs/fmt/yaml/ignore_line.yml, tests/specs/fmt/yaml/wrong_file_ignore.out, tests/specs/fmt/yaml/wrong_file_ignore.yaml
Closes https://github.com/denoland/deno/issues/26712
Also added tests for single line ignores.
=> fix(fmt): ignore file directive for YAML files

ext/node/polyfills/_zlib.mjs, tests/unit_node/zlib_test.ts
Closes https://github.com/denoland/deno/issues/26638
=> fix(node:zlib): gzip & gzipSync should accept ArrayBuffer

runtime/errors.rs
=> fix(ext/webstorage): use error class for sqlite error case

ext/http/http_next.rs
Closes https://github.com/denoland/deno/issues/26813
=> fix(ext/http): prefer brotli for `accept-encoding: gzip, deflate, br, zstd`

runtime/ops/process.rs, tests/specs/run/ld_preload/env_arg.out, tests/specs/run/ld_preload/env_arg.ts, tests/specs/run/ld_preload/set_with_allow_env.out
For https://github.com/denoland/deno/issues/26839
=> fix(permissions): say to use --allow-run instead of --allow-all

Cargo.lock, Cargo.toml
=> chore: update denokv_*

cli/file_fetcher.rs, tests/specs/npm/typo_in_npm/__test__.jsonc, tests/specs/npm/typo_in_npm/main.out, tests/specs/run/unsupported_dynamic_import_scheme/unsupported_dynamic_import_scheme.out, tests/testdata/run/extension_import.ts.out
Not the pretties fix, but does the job.
Closes https://github.com/denoland/deno/issues/26596
=> fix: update message for unsupported schemes with npm and jsr

ext/cache/sqlite.rs
Removes panic reported in https://github.com/denoland/deno/issues/26893
=> fix(ext/cache): gracefully error when cache creation failed

Cargo.lock, cli/Cargo.toml
Closes https://github.com/denoland/deno/issues/26690
Closes https://github.com/denoland/deno/issues/26324
=> fix(fmt): formatting of .svelte files

cli/tools/lint/reporters.rs, tests/specs/lint/json/expected_json.out, tests/specs/lint/stdin_json/expected_from_stdin_json.out, tests/specs/lint/with_report_config_override/with_report_config_override.out
=> feat(lint): Add checked files to JsonLintReporter

Cargo.lock, cli/Cargo.toml
Some crucial fixes have not yet been released, so I forked it for the time being.
=> chore: use forked sqlformat-rs

cli/args/flags.rs
`--recursive` is now implied by `--filter`.
=> fix(task): update --filter flag description

Cargo.lock, tests/Cargo.toml
* https://github.com/denoland/file_test_runner/pull/11
=> chore: update to file_test_runner 0.7.3

cli/util/path.rs
=> fix(lsp): wasm file import completions

Cargo.lock, cli/Cargo.toml, tests/specs/check/jsdoc_import_decl/__test__.jsonc, tests/specs/check/jsdoc_import_decl/check.out, tests/specs/check/jsdoc_import_decl/main.js
* https://github.com/denoland/deno_graph/pull/544
Closes https://github.com/denoland/deno/issues/25516
=> fix(check): support jsdoc `@import` tag

cli/tools/task.rs, tests/specs/task/description/deno.json, tests/specs/task/description/main.out
Closes https://github.com/denoland/deno/issues/27049
=> fix(task): handle multiline descriptions properly

cli/util/fs.rs
=> docs(cli): remove redundant word in comment

tests/unit_node/timers_test.ts
Increases the tolerance of the interval test on the CI.
=> chore(node/tests): increase tolerance of timers test on CI

ext/node/polyfills/_tls_wrap.ts, ext/node/polyfills/http2.ts, ext/node/polyfills/internal_binding/stream_wrap.ts, tests/unit_node/tls_test.ts
Fixes https://github.com/denoland/deno/issues/27087
Fixes https://github.com/denoland/deno/issues/26685
Fixes https://github.com/denoland/deno/issues/26660
=> fix(ext/node): `tls.connect` socket upgrades

Cargo.lock, Cargo.toml, cli/npm/managed/resolution.rs
* https://github.com/denoland/deno_npm/pull/74
=> refactor: upgrade to deno_npm 0.26

Cargo.lock, cli/Cargo.toml
Closes https://github.com/denoland/deno/pull/27187
=> chore: upgrade deno_lint to 0.68.2

cli/task_runner.rs
We don't need to forward the kill signal because ctrl+c events are sent to the process group.
Closes https://github.com/denoland/deno/issues/27266
=> fix(task): do not always kill child on ctrl+c on windows

ext/node/polyfills/v8.ts
Closes https://github.com/denoland/deno/issues/26580
=> fix(ext/node): handle Float16Array in node:v8 module

Cargo.lock, Cargo.toml, cli/tools/registry/pm.rs, tests/specs/add/add_with_subpath/wrong_constraint_jsr.out, tests/specs/add/add_with_subpath/wrong_constraint_npm.out, tests/specs/npm/error_version_after_subpath/error_version_after_subpath/main.out
Closes https://github.com/denoland/deno/issues/27243
=> fix: do not error when specifier subpath has an @ symbol

Cargo.lock, Cargo.toml, cli/util/path.rs, cli/util/progress_bar/renderer.rs, resolvers/npm_cache/tarball_extract.rs, runtime/permissions/Cargo.toml, runtime/permissions/lib.rs
Probably doesn't have much impact. I didn't measure any of these, but reducing allocations should always be good.
=> chore: reduce allocations in a few places

cli/args/flags.rs
Closes https://github.com/denoland/deno/issues/27318
=> fix(lint): do not error providing --allow-import

cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/tsc.rs, cli/tsc/diagnostics.rs, cli/tsc/mod.rs, tests/integration/lsp_tests.rs
=> fix(lsp): respect "typescript.suggestionActions.enabled" setting

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/555
=> fix(publish): infer literal types in const contexts

resolvers/node/analyze.rs, tests/specs/node/cjs_key_escaped_whitespace/__test__.jsonc, tests/specs/node/cjs_key_escaped_whitespace/main.js, tests/specs/node/cjs_key_escaped_whitespace/module.cjs, tests/specs/node/cjs_key_escaped_whitespace/output.out
Closes https://github.com/denoland/deno/issues/27422
=> fix(node): handle cjs exports with escaped chars

ext/node/polyfills/internal/errors.ts, ext/node/polyfills/internal_binding/_timingSafeEqual.ts, tests/unit_node/crypto/crypto_misc_test.ts
Fixes https://github.com/denoland/deno/issues/27214
=> fix(ext/node): RangeError timingSafeEqual with different byteLength

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
See https://github.com/denoland/deno/actions/runs/12563186693/job/35024695065. Broke in #27507.
=> chore: fix windows pre release CI job

cli/tsc/diagnostics.rs, tests/specs/check/message_chain_formatting/__test__.jsonc, tests/specs/check/message_chain_formatting/message_chain_formatting.out, tests/specs/check/message_chain_formatting/message_chain_formatting.ts
=> fix(check): line-break between diagnostic message chain entries

cli/lsp/config.rs, cli/lsp/language_server.rs
Fixes https://github.com/denoland/vscode_deno/issues/1239.
=> fix(lsp): don't skip dirs with enabled subdirs

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/559
Closes #27575
=> fix(no-slow-types): handle rest param with internal assignments

Cargo.lock, cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/562
Closes https://github.com/denoland/deno/issues/27593
=> fix(jsr): Wasm imports fail to load

cli/tsc/dts/lib.deno.window.d.ts
Improves docs for:
- http://docs.deno.com/api/web/~/localStorage
- http://docs.deno.com/api/web/~/sessionStorage
=> docs:Adds examples in JSDocs for localStorage and sessionStorage

cli/tsc/dts/lib.deno.window.d.ts
=> docs: JSDocs examples for prompt, confirm, and alert

ext/telemetry/lib.rs, ext/telemetry/telemetry.ts, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/links.out, tests/specs/cli/otel_basic/links.ts
Currently only links with no attributes.
=> feat(unstable): add basic support for otel trace links

Cargo.lock, tests/wpt/runner/expectation.json
Update yanked crates `bytemuck`, `futures-util`, `pest`, `pest_derive` and `url`.
=> fix(deps): update yanked crates

ext/node/polyfills/zlib.ts, tests/unit_node/zlib_test.ts
Fixes https://github.com/denoland/deno/issues/27774
=> fix(ext/node): reference error in zlib.crc32

cli/lsp/language_server.rs
Alleviates https://github.com/denoland/deno/issues/27778#issuecomment-2607477597.
I think this might be fixed in TS 5.7:
- https://github.com/microsoft/TypeScript/issues/59651
- https://github.com/microsoft/TypeScript/pull/60333
=> fix(lsp): silence debug error for 'move to a new file' action

Cargo.lock, Cargo.toml, cli/factory.rs, cli/lsp/config.rs, cli/lsp/resolver.rs, cli/rt/run.rs, resolvers/deno/factory.rs, resolvers/node/lib.rs, resolvers/node/package_json.rs, resolvers/node/sync.rs
This used to be complicated to do, but is now trivial.
Waiting on https://github.com/denoland/deno_package_json/pull/12
=> refactor: make PackageJsonCache injectable

cli/tsc/dts/lib.deno.ns.d.ts, tests/unit/read_dir_test.ts
=> fix(types): `Deno.readDirSync`'s type returns an `IteratorObject`

tests/integration/lsp_tests.rs
=> chore: remove LSP global symbols count tests

Cargo.lock, Cargo.toml, cli/module_loader.rs, cli/rt/run.rs, cli/tsc/mod.rs
Fixes https://github.com/denoland/deno/issues/27736
=> fix(core): handle dyn imports exceeding call stack size

ext/node/polyfills/_brotli.js, tests/unit_node/zlib_test.ts
Fixes https://github.com/denoland/deno/issues/27729
=> fix(ext/node): fix async variant of brotliDecompress

ext/process/lib.rs, tests/unit/command_test.ts
=> fix(process/windows): correct command resolution when PATH env var not uppercase

Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno/issues/27849
=> fix(core): Fix `create_stack_trace` from empty trace

tests/integration/run_tests.rs
These have been failing locally for some time.
=> chore: fix some broken pty tests on windows

cli/tsc/dts/lib.deno.unstable.d.ts
I noticed that this link lead to a 404 and fixed it. 
Apologies for the title, I wasn't sure what the correct title should be for this.
=> fix: Temporal plaintime docs link

cli/lsp/diagnostics.rs, tests/specs/npm/dynamic_npm_resolution_failure/main.out
Missed a few resolution errors
=> fix(lsp): ignore a few more diagnostics for ambient modules

ext/node/polyfills/_zlib.mjs, ext/node/polyfills/zlib.ts, tests/unit_node/zlib_test.ts
Fixes https://github.com/denoland/deno/issues/27170
=> fix(ext/node): expose brotli stream APIs

Cargo.lock
Every time I run `cargo test` or whatever the lockfile changes to this.
=> chore: fix lockfile on main

ext/node/polyfills/sqlite.ts, tests/unit_node/sqlite_test.ts
https://nodejs.org/api/sqlite.html#sqliteconstants
=> fix(ext/node): expose sqlite changeset constants

ext/telemetry/lib.rs, ext/telemetry/telemetry.ts
Previously they were treated as fractional seconds.
=> fix(otel): custom span start + end times are fractional ms

cli/tools/lint/mod.rs
Ref https://github.com/denoland/deno/issues/28025
=> fix(lint): disable incremental caching if JS plugins are used

cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
=> fix(lsp): include description for auto-import completions

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_config/pull/157
Closes https://github.com/denoland/deno/issues/28110
=> fix(workspace): diagnostic for imports in member with importMap at root

ext/node/polyfills/path/common.ts
Related to https://github.com/denoland/deno/issues/24236
=> fix(ext/node): use primordials in `ext/node/polyfills/path/common.ts`

cli/tools/init/mod.rs
Ref https://github.com/denoland/deno/issues/28148#issuecomment-2663189433
=> fix(init): force --reload if npm or jsr package

cli/tsc/dts/lib.deno.shared_globals.d.ts, cli/tsc/dts/lib.deno_console.d.ts
consolidating jsdocs into one block in the hope it will show up under I/O and not uncategorised,
adding docs to console variable
=> docs(console): update console documentation 

ext/node/ops/crypto/cipher.rs, tests/unit_node/crypto/crypto_cipher_test.ts
Fixes https://github.com/denoland/deno/issues/28208
=> fix(ext/node): decipherIv() range error on invalid final block length

Cargo.lock, Cargo.toml, cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/repl.rs, tests/integration/lsp_tests.rs, tests/util/server/src/lsp.rs
=> fix(lsp): close server on exit notification

cli/js/40_lint.js
We previously failed to lint `./cli/tsc/00_typescript.js` with plugins, because every "next" node would cause a new stack frame to be added.
=> fix(lint): don't recurse infinitely for large ASTs

ext/node/ops/sqlite/mod.rs, ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Fixes https://github.com/denoland/deno/issues/28259
=> fix(ext/node): descriptive sqlite error messages

cli/schemas/config-file.v1.json, cli/schemas/kv-metadata-exchange-response.v1.json, cli/schemas/lint-rules.v1.json, cli/schemas/lint-tags.v1.json, cli/schemas/module-graph.json, cli/schemas/registry-completions.v1.json, cli/schemas/registry-completions.v2.json
Only config-file.v1.json had the latest version of JSON Schema, the other files were 2 versions old.
=> refactor(cli): update JSON schemas versions

ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Fixes https://github.com/denoland/deno/issues/28295
=> fix(ext/node): SQLite reset guards to prevent database locks

ext/node/ops/sqlite/statement.rs
https://github.com/denoland/deno/actions/runs/13526501249/job/37798308222
=> chore: fix linter error on `main`

Cargo.lock, Cargo.toml
Exposes `deno_core/v8_enable_pointer_compression` feature:
https://github.com/denoland/deno_core/commit/d67efcba0ae01d2714573cfd7784fee3532ba653
=> refactor: update deno_core to enable pointer compression

cli/lsp/capabilities.rs
Fixes https://github.com/denoland/vscode_deno/issues/1228. No meaningful way of testing this.
=> fix(lsp): limit languages in semantic tokens provider

cli/args/flags.rs
=> fix(cli): warn when an otel env var has an invalid value

cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
=> perf(lsp): lazily start the ts server

ext/node/polyfills/path/_util.ts
Towards https://github.com/denoland/deno/issues/24236
=> fix(ext/node): use primordials in `ext/node/polyfills/path/_util.ts`

cli/js/40_bench.js, cli/tsc/dts/lib.deno.ns.d.ts
=> fix(bench): lower bench time budget when `n` is specified

ext/net/03_quic.js, ext/web/webtransport.js
Fixes: https://github.com/denoland/deno/issues/28406
=> fix: unhandled rejection from quic

tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/node_http_metric.out, tests/specs/cli/otel_basic/node_http_metric.ts
part of #28329
This adds test case to check `node:http.createServer` is instrumented
=> test(otel): add test of otel integration of node http server

cli/args/flags.rs
=> fix(otel): don't print otel warning when variable is not set

ext/node/polyfills/http.ts, ext/telemetry/util.ts, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/node_http_metric.out, tests/specs/cli/otel_basic/node_http_request.out, tests/specs/cli/otel_basic/node_http_request.ts
part of #28329 
This PR adds tracing to node:http.request
=> feat(unstable/otel): add otel tracing to node:http.request

ext/telemetry/util.ts
=> chore: fix build on main

Cargo.lock, Cargo.toml, cli/cache/module_info.rs, cli/emit.rs, cli/lib/standalone/binary.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/module_loader.rs, cli/rt/binary.rs, cli/tools/compile.rs, cli/tools/coverage/mod.rs, cli/tools/publish/module_content.rs, cli/tsc/mod.rs, cli/type_checker.rs, resolvers/deno/cjs.rs, resolvers/deno/workspace.rs
* https://github.com/denoland/deno_media_type/pull/22
=> refactor: handle deno_media_type having `Html` and `Sql` variants

ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Fixes https://github.com/denoland/deno/issues/28492
=> fix(ext/node): reset statement immidiately in run()

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_doc/pull/706
Closes https://github.com/denoland/deno/issues/23711
Closes https://github.com/denoland/deno/issues/28504
=> fix(doc): do not stack overflow for namespace that exports self or ancestor

cli/tsc/dts/lib.deno.unstable.d.ts
adding jsdocs and examples to Intl category interfaces
=> docs: adding jsdocs for temporalAPI

cli/lsp/diagnostics.rs
For example, if someone has `"$src/": "./src"` in their import map, this will no longer show a diagnostic when someone imports `"./a.ts"` from ./src/b.ts`
Closes https://github.com/denoland/deno/issues/17867
=> fix(lsp): do not show import-map-remap diagnostic when referrer and target are within the entry base

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_npm/pull/87
Closes #26626
=> fix(npm): reduce occurrences of duplicate packages due to peer dep resolution

ext/node/polyfills/_fs/_fs_mkdir.ts, tests/unit_node/_fs/_fs_mkdir_test.ts
Fixes https://github.com/denoland/deno/issues/28604
=> fix(ext/node): `mkdir()` parse file mode

Cargo.lock, Cargo.toml, cli/rt/binary.rs
* https://github.com/denoland/deno_npm/pull/89
Closes https://github.com/denoland/deno/issues/28023
=> fix(npm): improve optional peer dep handling

ext/node/polyfills/_fs/_fs_readv.ts
=> fix(ext/node): use primordials in `ext/node/polyfills/_fs/_fs_readv.ts`

ext/node/polyfills/_fs/_fs_realpath.ts
=> fix(ext/node): use primordials in `ext/node/polyfills/_fs/_fs_realpath.ts`

ext/node/polyfills/_fs/_fs_lstat.ts
=> fix(ext/node): use primordials in `ext/node/polyfills/_fs/_fs_lstat.ts`

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_npm/pull/91/files
Closes https://github.com/denoland/deno/issues/26145
=> fix(npm): reduce duplicate peers by preferring existing nv if nv anywhere in ancestor peers

cli/tsc/dts/lib.deno.unstable.d.ts
=> fix(types): add `Error.isError` type

README.md
deno.land already has 7.3k followers on bluesky---that's pretty cool! maybe we should add a bluesky badge to readme so people can find us there? :)
=> docs(readme): add bluesky badge

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Fixes https://github.com/denoland/deno/issues/28672
=> fix(ext/node): sqlite handle empty blob being NULL

ext/webgpu/surface.rs
=> fix(ext/webgpu): release current texture of surface after present

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_npm/pull/93
Closes https://github.com/denoland/deno/issues/28023#issuecomment-2769944224
=> fix(npm): further reduce duplicates with optional peers

Cargo.lock, Cargo.toml, cli/npm/installer/common/lifecycle_scripts.rs, cli/npm/mod.rs, cli/task_runner.rs, cli/tools/task.rs
* https://github.com/denoland/deno_task_shell/pull/144
* https://github.com/denoland/deno_task_shell/pull/143
=> fix(task): filter empty elements in `xargs`

cli/task_runner.rs
Also adds some unstable flags so more things work.
=> fix(npm): use Deno instead of Node in more cases for lifecycle scripts

ext/telemetry/lib.rs, ext/telemetry/telemetry.ts, tests/specs/cli/otel_basic/main.ts
Implement https://opentelemetry.io/docs/specs/semconv/runtime/v8js-metrics/
=> feat: v8js metrics

cli/tools/test/mod.rs, cli/tools/test/reporters/common.rs, cli/tools/test/reporters/dot.rs, cli/tools/test/reporters/pretty.rs, cli/tools/test/reporters/tap.rs
=> fix(test): ignore write errors in reporter

tools/verify_pr_title.js
Ref https://github.com/denoland/deno/pull/28697
=> ci: improve verify_pr_title script

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Probably caused by copy-pasting from the canary upload job.
=> fix(ci): missing release symcache

ext/node/polyfills/path/_posix.ts
=> fix(ext/node): use primordials in `ext/node/polyfills/path/_posix.ts`

ext/node/polyfills/path/_win32.ts
=> fix(ext/node): use primordials in `ext/node/polyfills/path/_win32.ts`

cli/lib/standalone/virtual_fs.rs, cli/standalone/binary.rs, cli/tools/compile.rs, tests/specs/compile/include/data_files/non_existent.out, tests/specs/compile/node_modules_include/__test__.jsonc, tests/specs/compile/node_modules_include/main.ts, tests/specs/compile/node_modules_include/package.json
Closes https://github.com/denoland/deno/issues/28773
=> fix(compile): do not panic including node_modules directory

ext/canvas/image_ops.rs
fixes https://github.com/denoland/deno/issues/28732
=> fix(ext/canvas): handle integer overflow in `createImageBitmap`

ext/node/polyfills/internal/crypto/cipher.ts, tests/unit_node/crypto/crypto_cipher_test.ts
Fixes https://github.com/denoland/deno/issues/28633
=> fix(ext/node): return `Buffer` from crypto cipher APIs

Cargo.lock, Cargo.toml, ext/node/lib.rs, ext/node/ops/handle_wrap.rs, ext/node/ops/mod.rs, ext/node/polyfills/_process/streams.mjs, ext/node/polyfills/internal_binding/async_wrap.ts, ext/node/polyfills/internal_binding/handle_wrap.ts, ext/node/polyfills/internal_binding/stream_wrap.ts
=> refactor(ext/node): rewrite HandleWrap in Rust

cli/npm/mod.rs
This is where deno_lockfile gets the info for the transform from 4->5. So while we were doing this optimization on new v5 lockfiles, we weren't doing it correctly for ones migrated from earlier versions.
Testing this is kinda hard because our tests don't use the default registry, hmm
=> fix(lockfile): omit tarball url from lockfile if it's the default

tests/node_compat/run_all_test_unmodified.ts
The script currently sometimes exits prematurely on windows because of uncaught error caused by failed kill attempt from abort signal. (See https://github.com/denoland/deno/issues/28882)
This PR avoids using abort signal to work around the issue above.
=> chore(ext/node): fix run_all_test script for windows

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_npm/pull/99
Closes https://github.com/denoland/deno/issues/28890
=> fix(npm): panic when using tag with patched package

ext/node/polyfills/child_process.ts, ext/node/polyfills/internal/util.mjs, ext/node/polyfills/util.ts
Node rewrote this code too in https://github.com/nodejs/node/pull/54836
=> refactor(ext/node): use Promise.withResolvers

cli/args/flags.rs, ext/http/00_serve.ts, ext/http/lib.rs, tests/integration/serve_tests.rs, tests/specs/cli/otel_basic/main.ts
=> fix: support vsock in DENO_SERVE_ADDRESS

cli/tsc/98_lsp.js
=> chore(lsp): fix semantic cache cleanup exemptions

cli/rt/binary.rs, cli/rt/main.rs
We were silently failing on failure here.
Part of https://github.com/denoland/deno/issues/28982 -- This does not fix this issue, but maybe makes the error message better in the future.
=> fix(compile): error when cannot extract binary section

cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
=> fix(lsp): use markup content variant for hover response

Cargo.lock, Cargo.toml, cli/lib/version.rs, cli/npm/mod.rs, cli/rt/binary.rs, cli/tools/pm/outdated/mod.rs, tools/release/promote_to_release.ts
* https://github.com/denoland/sui/pull/40 (this is the fix)
* https://github.com/denoland/sui/pull/39
* https://github.com/denoland/sui/pull/38
Closes https://github.com/denoland/deno/issues/28982
=> fix(compile): read resource name in executable as uppercase on Windows

cli/tsc/dts/lib.dom.d.ts, cli/tsc/dts/lib.dom.iterable.d.ts, cli/tsc/dts/lib.es2015.iterable.d.ts, cli/tsc/dts/lib.es2020.bigint.d.ts, cli/tsc/dts/lib.es2023.array.d.ts, cli/tsc/dts/lib.es5.d.ts, cli/tsc/dts/lib.esnext.d.ts, cli/tsc/dts/lib.esnext.float16.d.ts, cli/tsc/dts/lib.esnext.iterator.d.ts, cli/tsc/dts/lib.esnext.promise.d.ts, cli/tsc/dts/lib.webworker.d.ts, cli/tsc/dts/lib.webworker.iterable.d.ts, cli/tsc/dts/typescript.d.ts, tests/integration/check_tests.rs, tests/specs/run/import_attributes_type_check/type_check.out
* https://github.com/denoland/TypeScript/pull/18
Closes https://github.com/denoland/deno/issues/28711
=> feat: TypeScript 5.8

cli/lib/version.rs, cli/snapshot/shared.rs, tests/unit/version_test.ts
https://github.com/denoland/deno/pull/29041#issuecomment-2831398138
=> fix: correct reported typescript version

cli/args/flags.rs, cli/main.rs, tests/specs/run/bare_run_main/__test__.jsonc, tests/specs/run/bare_run_main/main.out
=> fix: better error message for bare run in file-like case

cli/main.rs
=> fix(otel): only start deno_telemetry thread when needed

ext/node/polyfills/_fs/_fs_opendir.ts
=> fix(ext/node): use primordials in ext/node/polyfills/_fs/_fs_opendir.ts

cli/tools/info.rs, tests/specs/info/flag/041_info_flag.out, tests/specs/info/flag_location/041_info_flag_location.out, tests/specs/info/json/info_json.out, tests/specs/info/json_location/info_json_location.out
=> feat(info): include deno version

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/resolver.rs, cli/npm/installer/mod.rs, cli/npm/installer/resolution.rs, tests/integration/lsp_tests.rs
=> fix(lsp): add npm reqs to installer on resolution

Cargo.lock, Cargo.toml, bench_util/benches/utf8.rs, cli/lsp/tsc.rs, cli/tools/bench/mod.rs, cli/tools/jupyter/mod.rs, cli/tools/lint/plugins.rs, cli/tools/repl/mod.rs, cli/tools/test/mod.rs, cli/tsc/mod.rs, ext/net/ops.rs, ext/node/ops/handle_wrap.rs, ext/os/lib.rs, ext/url/benches/url_ops.rs, ext/web/benches/encoding.rs, ext/web/benches/timers_ops.rs, ext/webidl/benches/dict.rs, runtime/examples/extension/main.rs, runtime/ops/tty.rs, runtime/snapshot.rs, runtime/snapshot_info.rs, runtime/web_worker.rs, runtime/worker.rs, tests/unit/tty_test.ts
- new ops init api
- fix op order
- remove deno_os_worker since extensions must now match the snapshot exactly
- isatty test change
=> feat: deno_core 0.344.0

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, tests/integration/lsp_tests.rs
=> fix(lsp): prefer relative auto-import specifier against import map

cli/args/flags.rs
Closes https://github.com/denoland/deno/issues/29116
=> fix(flags): do not panic parsing invalid --allow-import flag

cli/main.rs, ext/http/00_serve.ts, ext/http/lib.rs, tests/specs/run/unconfigured/main.out, tests/specs/run/unconfigured/main.ts
send an event over the control socket when deno.serve is listening.
=> feat(unstable): notify control sock on serving

ext/process/40_process.js, tests/unit/command_test.ts
Co-authored-by: Divy Srivastava <dj.srivastava23@gmail.com>
Closes https://github.com/denoland/deno/issues/27112
Closes https://github.com/denoland/deno/pull/27641
Closes https://github.com/denoland/deno/pull/27124
=> fix(ext/process): suppress child process kill errors in onAbort handler

ext/node/polyfills/internal/async_hooks.ts
Towards #24236. Replaces `Symbol` as well as `Array` and `Function` methods with their primordial equivalents.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/async_hooks.ts`

cli/lsp/text.rs
Fixes https://github.com/denoland/vscode_deno/issues/1293.
=> perf(lsp): don't diff 10,000+ line files for formatting

cli/lsp/analysis.rs, tests/integration/lsp_tests.rs
=> fix(lsp): discard quick fixes importing /node_modules/ paths

Cargo.lock, Cargo.toml, tests/specs/run/inspector_file_url/__test__.jsonc, tests/specs/run/inspector_file_url/main.out, tests/specs/run/inspector_file_url/main.ts
Fixes: https://github.com/denoland/deno/issues/27003
=> fix: inspector rewrite resource name to url

ext/node/polyfills/process.ts, tests/specs/run/process_env_load/env_file.ts
Fixes https://github.com/denoland/deno/issues/29236
=> fix(ext/node): Fix export loadEnvFile from `node:process`

ext/node/polyfills/_tls_wrap.ts, tests/unit_node/tls_test.ts
Fixes https://github.com/denoland/deno/issues/29229
=> fix(ext/node): use "localhost" as default tls hostname

ext/node/polyfills/internal/fs/handle.ts
Towards #24236. This PR updates JS intrinsics with their primordial equivalents.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/fs/handle.ts`

cli/tools/coverage/mod.rs, cli/tools/coverage/reporter.rs, tests/specs/coverage/all_files_with_ignore_directives/__test__.jsonc, tests/specs/coverage/all_files_with_ignore_directives/lib.ts, tests/specs/coverage/all_files_with_ignore_directives/test.ts, tests/specs/coverage/all_files_with_ignore_directives/test_coverage.out
Closes https://github.com/denoland/deno/issues/29218
=> fix(coverage): don't panic if all covered files are ignored via directive

ext/telemetry/telemetry.ts, runtime/ops/worker_host.rs, runtime/web_worker.rs
Closes https://github.com/denoland/deno/issues/28790
=> fix(otel): don't panic when using worker threads

README.md
Fixes https://github.com/denoland/deno/issues/29253
=> chore: update "Build from source" link in README

cli/lsp/language_server.rs, cli/lsp/lsp_custom.rs, tests/integration/lsp_tests.rs
Ref https://github.com/denoland/deno/issues/29243
=> feat(lsp): add description in TaskDefinition

ext/node/polyfills/internal/timers.mjs
Towards #24236. Replaces JS intrinsics with equivalent primordial versions.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/timers.mjs`

ext/node/polyfills/_tls_wrap.ts, tests/unit_node/tls_test.ts
Fixes https://github.com/denoland/deno/issues/29230
=> fix(ext/node): TLS server unref

ext/node/polyfills/internal/stream_base_commons.ts
Towards #24236. Replaces JS intrinsics with primordial equivalents. Lint "ignore" statements were added for `Readable` stream instances.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/stream_base_commons.ts`

ext/node/polyfills/internal/validators.mjs
Towards #24236. Replaces JS instrinsics with equivalent primordials.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/validators.mjs`

tests/node_compat/slack.ts
This is for internal Slack automation
=> ci: Show percentage diff for Node compat tests

tests/node_compat/slack.ts
This was showing double "minus" (`-`) sign
=> ci: update Slack bot action

cli/lsp/analysis.rs, cli/lsp/jsr.rs, cli/lsp/resolver.rs, tests/integration/lsp_tests.rs
=> fix(lsp): lookup bare workspace specifiers for auto-import

ext/webgpu/queue.rs, tests/unit/webgpu_test.ts
=> feat(ext/webgpu): implement GPUQueue.onSubmittedWorkDone

cli/tools/task.rs
Closes https://github.com/denoland/deno/issues/29341
=> fix(task): wildcard match starts at the beginning

ext/node/polyfills/internal_binding/stream_wrap.ts
Accidental debug code from https://github.com/denoland/deno/commit/28cb8f7011f533e3c79da6832cea098030e35953
=> fix(ext/node): prevent stdin double read

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/29364
=> fix(ext/node): handle `null` ssl options in `node:https`

ext/node/polyfills/internal/errors.ts
Towards #24236. Replaces JS intrinsics with the equivalent primordials.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/errors.ts`

cli/lsp/config.rs, tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/1305.
=> fix(lsp): handle 'deno.config' setting outside of workspace

cli/lsp/analysis.rs, cli/lsp/resolver.rs, tests/integration/lsp_tests.rs
=> fix(lsp): lookup mapped npm specifier resolutions for auto-import

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
=> chore: don't run "test release linux-aarch64" on PRs

cli/lsp/jsr.rs, tests/integration/lsp_tests.rs
=> fix(lsp): lookup patched jsr packages for auto-import

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/rt/Cargo.toml, resolvers/node/errors.rs
blocked on https://github.com/denoland/denokv/pull/119
=> fix: support numerical properties for deno_errors

runtime/permissions/Cargo.toml
See https://github.com/denoland/deno/actions/runs/15331356436/job/43139395190.
=> ci: fix features for nix in permissions/Cargo.toml

Cargo.lock, ext/http/Cargo.toml, ext/http/lib.rs, tests/unit/serve_test.ts
Fixes https://github.com/denoland/deno/issues/29517
=> fix(ext/http): handle vsock streams in `extract_network_stream`

Releases.md
Missed during the release of 2.3.5
=> chore: update Releases.md

ext/node/ops/zlib/mod.rs, tests/unit_node/zlib_test.ts
Fixes https://github.com/denoland/deno/issues/29545.
=> fix(zlib): don't return a smi from crc32

ext/node/ops/sqlite/database.rs, ext/node/ops/sqlite/session.rs, ext/node/ops/sqlite/statement.rs
=> fix(ext/node): return `undefined` instead of `null` in sqlite

resolvers/node/analyze.rs, resolvers/node/errors.rs, resolvers/node/resolution.rs
Extracted out of https://github.com/denoland/deno/pull/29470
Co-authored-by: nathanwhit <nathanwhit@users.noreply.github.com>
=> refactor(node): improve `ResolutionMode::Require` resolution

tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/metric_temporality.ts, tests/specs/cli/otel_basic/metric_temporality_cumulative.out, tests/specs/cli/otel_basic/metric_temporality_delta.out
=> tests(otel): ensure delta temporality is working

ext/node/polyfills/internal/crypto/random.ts
Towards enabling `parallel/test-crypto-primes.js`
=> fix(ext/node): validate prime bigint candidate

ext/node/lib.rs
=> fix(ext/node): `process.loadEnvFile` returns `undefined`

cli/util/draw_thread.rs
Part of https://github.com/denoland/deno/issues/29726
=> fix: do not panic when logging from outside a tokio runtime

cli/args/flags.rs, tests/specs/bundle/allow_imports/__test__.jsonc, tests/specs/bundle/allow_imports/main.ts
=> fix(bundle): parse the allow-import flag, fix example in help text

cli/args/mod.rs, cli/factory.rs, cli/standalone/binary.rs
=> chore: reduce some allocations collecting unstable features

cli/factory.rs, cli/lsp/resolver.rs, cli/npm.rs, cli/tools/bundle/esbuild.rs, cli/tools/compile.rs, cli/tools/installer/bin_name_resolver.rs, cli/tools/installer/mod.rs, libs/npm_cache/registry_info.rs, libs/npm_installer/factory.rs, libs/npm_installer/resolution.rs
Resolves `deno install -g npm:@google/gemini-cli` to `gemini`
=> fix(install/global): resolve bin name from npm packument

libs/resolver/emit.rs, libs/resolver/loader/prepared.rs
Follow-up to https://github.com/denoland/deno/pull/29994
=> perf: skip jsx transpile when disabled

Cargo.lock, ext/telemetry/Cargo.toml, ext/telemetry/lib.rs, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/main.ts
implement new connector which uses either HttpsConnector or VsockStream. will also be easy to add tunnels to this later.
=> feat(otel): support vsock transport for telemetry

cli/tsc/dts/lib.deno.unstable.d.ts
Closes https://github.com/denoland/deno/issues/30071
=> docs: workers inherit permissions by default

Cargo.lock, Cargo.toml, cli/lib/util/logger.rs, cli/main.rs, ext/net/Cargo.toml, ext/net/ops.rs, ext/net/raw.rs, ext/net/tunnel.rs, ext/telemetry/lib.rs, tests/specs/run/tunnel/test.ts
switch to `deno_tunnel` crate for shared code with deploy
=> chore: switch to deno_tunnel crate

cli/lsp/analysis.rs, cli/lsp/completions.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/jsr.rs, cli/lsp/language_server.rs, cli/lsp/lint.rs, cli/lsp/resolver.rs, cli/lsp/tsc.rs
Towards https://github.com/denoland/deno/pull/30048#discussion_r2195988915. I'll help keep that PR merged with main as well
=> refactor(lsp): move workspace_resolver to LspResolver

cli/tools/task.rs, libs/config/workspace/mod.rs, tests/specs/task/filter/deno_all.out, tests/specs/task/filter/deno_exact.out, tests/specs/task/filter/deno_filter_recursive.out, tests/specs/task/filter/deno_recursive.out, tests/specs/task/filter/deno_scoped_exact.out, tests/specs/task/filter/deno_scoped_multi.out, tests/specs/task/filter/deno_workspace_order.out, tests/specs/task/filter/npm_all.out, tests/specs/task/filter/npm_exact.out, tests/specs/task/filter/npm_filter_recursive.out, tests/specs/task/filter/npm_multi.out, tests/specs/task/filter/npm_recursive.out, tests/specs/task/filter/npm_scoped_exact.out, tests/specs/task/filter/npm_scoped_multi.out, tests/specs/task/filter/npm_workspace_order.out, tests/specs/task/recursive_order/task.out
=> fix(task): show package name of task when --recursive

cli/standalone/binary.rs
Part of https://github.com/denoland/deno/issues/30177
=> fix(compile): do not error including npm packages that don't match current system

tests/node_compat/run_all_test_unmodified.ts, tests/node_compat/test.ts
=> test: avoid race condition on node compat test runner

ext/node/polyfills/internal_binding/node_file.ts
Towards #24236. Replaces JS builtins with equivalent primordials.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal_binding/node_file.ts`

ext/net/ops.rs, ext/net/ops_tls.rs, ext/net/raw.rs, ext/node/polyfills/_tls_wrap.ts, ext/node/polyfills/net.ts, runtime/ops/http.rs, tests/unit_node/tls_test.ts
Reverts denoland/deno#30169
Causes issues with playwright's installation of browsers
=> Revert "fix(ext/node): support TLS for unix sockets"

cli/args/flags.rs
Refactored out of some other work I abandoned. I think this is good to keep.
=> refactor: improve getting WatchFlags/WatchFlagsWithPaths

ext/io/12_io.js
Fixes https://github.com/denoland/deno/issues/28867
=> fix(io): do not autoClose stdin readable stream

libs/resolver/graph.rs
=> refactor(resolver): improve and expose details of CouldNotResolveError

cli/module_loader.rs, cli/rt/run.rs, cli/tsc/mod.rs, ext/node/lib.rs, ext/node/ops/require.rs, libs/node_resolver/errors.rs, libs/node_resolver/package_json.rs, libs/node_resolver/resolution.rs, libs/resolver/cjs/mod.rs, libs/resolver/loader/module_loader.rs, libs/resolver/loader/npm.rs, libs/resolver/npm/byonm.rs, libs/resolver/npm/mod.rs
For https://github.com/denoland/deno-js-loader/issues/17
=> refactor: make it easier to get closest package.json files

Cargo.lock, cli/tools/repl/mod.rs, ext/io/Cargo.toml, ext/io/bi_pipe.rs, tests/specs/repl/json/test.out, tests/specs/repl/json/test.ts
- always provide response when run completes
- check fd is valid to satisfy `from_raw_fd` unsafe
Fixes: https://github.com/denoland/deno/issues/30401
=> fix(unstable): fix json repl bugs

ext/node/polyfills/_tls_wrap.js, tests/unit_node/tls_test.ts
Fixes https://github.com/denoland/deno/issues/28543
=> fix(ext/node): TLS emit close event on parent socket

cli/lsp/analysis.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
=> fix(lsp): fix import specifiers in file rename changes

cli/args/flags.rs, tests/registry/npm/@denotest/multiple-arch-deps/1.0.0/package.json, tests/registry/npm/@denotest/multiple-arches-win32-arm64/1.0.0/package.json, tests/registry/npm/@denotest/multiple-arches-win32-x64/1.0.0/package.json, tests/specs/install/deno_install_arch/__test__.jsonc, tests/specs/install/deno_install_arch/package.json, tests/specs/install/deno_install_arch/verify_output.ts
For changing the architecture used for npm install.
=> feat(unstable/install): `DENO_INSTALL_ARCH` env var

tools/deno.lock.json
update tools/deno.lock.json to v5
> ```
> error: Unsupported lockfile version '4'. Try upgrading Deno or recreating the lockfile at 'tools/deno.lock.json'.
> ```
https://github.com/denoland/deno/actions/runs/17169066564/job/48715288781#step:9:25
=> chore: fix wpt_epoch CI

.dprint.json, Cargo.lock, Cargo.toml, cli/tools/lint/mod.rs, cli/tools/publish/module_content.rs, cli/tools/repl/session.rs, libs/resolver/deno_json.rs, libs/resolver/emit.rs, tests/specs/fmt/parse_error/check_parse_error.out, tests/specs/fmt/parse_error/parse_error.out, tests/specs/publish/no_check_surfaces_syntax_error/publish.out, tests/specs/run/error_syntax_empty_trailing_line/error_syntax_empty_trailing_line.mjs.out
* https://github.com/denoland/deno_ast/pull/316
* https://github.com/denoland/deno_ast/pull/313
* https://github.com/denoland/deno_graph/pull/605
* https://github.com/denoland/deno_doc/pull/739
* https://github.com/denoland/deno_lint/pull/1456
* https://github.com/denoland/deno_lint/pull/1455
* https://github.com/dprint/dprint-plugin-typescript/pull/736
* https://github.com/denoland/eszip/pull/225
=> fix: upgrade to swc_ecma_parser 23

Cargo.lock, cli/Cargo.toml, cli/tools/bundle/mod.rs
Fixes https://github.com/denoland/deno/issues/30617
=> fix(bundle): properly display error on invalid config in watch mode

cli/lsp/analysis.rs, tests/integration/lsp_tests.rs
=> fix(lsp): import rewrites in moved file

tests/specs/README.md, tests/specs/mod.rs
`--no-capture` was added in 1.88, with `--nocapture` being soft-deprecated.
https://releases.rs/docs/1.88.0/#libraries
=> fix(tests): Switch from --nocapture to --no-capture

cli/tools/publish/module_content.rs, cli/tools/publish/unfurl.rs
=> fix(publish): unfurl import.meta.resolve calls

cli/lsp/analysis.rs, cli/lsp/resolver.rs, tests/integration/lsp_tests.rs
=> fix(lsp): auto-import dep entries from workspace member import maps

cli/lsp/config.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
=> fix(lsp): don't write lockfile during cache-on-save

cli/lsp/config.rs
=> perf(lsp): don't watch node_modules files

cli/factory.rs, cli/lib/worker.rs, cli/rt/run.rs, cli/tools/coverage/mod.rs, cli/tools/test/mod.rs, cli/worker.rs, runtime/coverage.rs, runtime/lib.rs, runtime/ops/worker_host.rs, runtime/web_worker.rs, tests/integration/coverage_tests.rs, tests/testdata/coverage/worker/expected1.out, tests/testdata/coverage/worker/expected2.out, tests/testdata/coverage/worker/expected3.out, tests/testdata/coverage/worker/main1.js, tests/testdata/coverage/worker/main2.js, tests/testdata/coverage/worker/main3.js, tests/testdata/coverage/worker/worker1.js, tests/testdata/coverage/worker/worker2.js, tests/testdata/coverage/worker/worker3.js
Closes https://github.com/denoland/deno/issues/13206
```
$ deno test -R --coverage
...
ok | 1 passed | 0 failed (75ms)
| File      | Branch % | Line % |
| --------- | -------- | ------ |
| main.ts   |    100.0 |   75.0 |
| All files |    100.0 |   75.0 |
Lcov coverage report has been generated at .../lcov.info
HTML coverage report has been generated at .../html/index.htm
```
```
$ deno test -R --coverage
ok | 1 passed | 0 failed (75ms)
| File      | Branch % | Line % |
| --------- | -------- | ------ |
| main.ts   |    100.0 |   75.0 |
| worker.ts |    100.0 |  100.0 |
| All files |    100.0 |   83.3 |
Lcov coverage report has been generated at coverage/lcov.info
HTML coverage report has been generated at coverage/html/index.htm
```
=> fix(coverage): collect coverage data for workers

ext/fetch/22_http_client.js, ext/fs/30_fs.js, ext/http/00_serve.ts, ext/http/01_http.js, ext/kv/01_db.ts, ext/net/01_net.js, ext/node/polyfills/internal/events/abort_listener.mjs, ext/node/polyfills/internal/fs/handle.ts, ext/process/40_process.js, ext/web/00_infra.js, runtime/js/40_fs_events.js, runtime/js/99_main.js
Follow up to https://github.com/denoland/deno_core/pull/1200
=> chore: use `SymbolAsyncDispose` and `SymbolDispose` primordials

Cargo.lock, Cargo.toml, tests/specs/lint/jsx_runtime_pragma_unknown_value/__test__.jsonc, tests/specs/lint/jsx_runtime_pragma_unknown_value/main.tsx, tests/specs/run/jsx_frag_pragma_null_with_import_source/__test__.jsonc, tests/specs/run/jsx_frag_pragma_null_with_import_source/main.out, tests/specs/run/jsx_frag_pragma_null_with_import_source/main.tsx
=> fix(cli): jsx pragma-related swc panics
