- ext/fetch/26_fetch.js
This adds a missing `cancelHandleRid` field in `op_fetch` return type, see Rust side:
https://github.com/denoland/deno/blob/fdb4953ea460d5c09ac73f3f37dd570d44893155/ext/fetch/lib.rs#L183-L189
> fix(ext/fetch): re-align return type in op_fetch docstring

- cli/tests/unit_node/http_test.ts
- ext/node/polyfills/http.ts
This pr fix #20923
I use the implementation in 02_timers.js.
> fix(ext/node): socket setTimeout

- cli/tests/unit/serve_test.ts
- ext/http/00_serve.js
Fixing this https://github.com/denoland/deno/issues/20947 and #20013
We are not checking the return value of handler passed through Deno.serve and directly passing it to toInnerResponse but thats expecting a Response class . So throwing error if handler return other than Response class. (Btw, its my first PR correct me if im wrong on anything :) )
> fix(ext/http): Throwing Error if the return value of Deno.serve handler is not a Response class

- Cargo.lock
- Cargo.toml
- ext/web/stream_resource.rs
Use our safer typed externals for the external required for resource streams.
> chore(ext/web): migrate to deno_core typed externals

- Cargo.lock
- Cargo.toml
- cli/tests/unit/ref_unref_test.ts
- ext/ffi/00_ffi.js
- ext/http/00_serve.js
- ext/net/01_net.js
- ext/node/polyfills/http2.ts
- ext/web/02_timers.js
- ext/web/06_streams.js
- runtime/js/40_process.js
- runtime/js/40_signals.js
We can move all promise ID knowledge to deno_core, allowing us to better experiment with promise implementation in deno_core.
`{un,}refOpPromise(promise)` is equivalent to `{un,}refOp(promise[promiseIdSymbol])`
> perf: remove knowledge of promise IDs from deno

- cli/tests/unit/kv_test.ts
This PR reduces the time to run `queue persistence with inflight messages` test from 60 seconds down to about 6 seconds. 
The test simulates a crash to ensure that inflight messages are cleaned up and re-queued when the new process starts. Since messages are considered dead after 5 seconds of being queued, reopening the db within 5 seconds does not re-queue the messages on startup (they do get re-queued after 60 seconds, which is the cleanup frequency). By waiting for 5 seconds before reopening the db, the test ensures that the cleanup happens quickly when the db is opened.
> fix(test) reduce queue persistence test time from 60 secs to 6 secs

- Cargo.toml
Fix for https://github.com/Homebrew/homebrew-core/pull/153128
> chore: disable default features for denokv_sqlite

- cli/tests/unit_node/http_test.ts
- ext/node/polyfills/http.ts
- ext/node/polyfills/https.ts
> fix(node/http(s)): export globalAgent

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- ext/node/Cargo.toml
- ext/node/lib.rs
- ext/node/ops/zlib/mod.rs
- ext/node/ops/zlib/mode.rs
- ext/node/ops/zlib/stream.rs
- runtime/Cargo.toml
- test_util/Cargo.toml
We only want one zlib dependency.
Zlib dependencies are reorganized so they use a hidden `__vendored_zlib_ng` flag in cli that enables zlib-ng for both libz-sys (used by ext/node) and flate2 (used by deno_web).
> chore(ext/node): use libz-sys w/`zlib-ng` feature in node

- cli/lsp/language_server.rs
- cli/tests/integration/lsp_tests.rs
> fix(lsp): update tsconfig after refreshing settings on init

- cli/args/flags.rs
- cli/tests/integration/install_tests.rs
- cli/tools/installer.rs
- cli/util/fs.rs
> fix(install): should work with non-existent relative root

- cli/tests/unit/text_encoding_test.ts
> chore(ext/web): use a non-resource stream for textDecoderStreamCleansUpOnCancel

- cli/tests/unit/signal_test.ts
If these tests do eventually break, they'll time out.
> chore(cli): unflake signal test

- cli/tests/unit/webstorage_test.ts
- ext/webstorage/01_webstorage.js
Fixed a bug that webstorage `has` trap that passed `symbol` to `storage.getItem`.
```
> Symbol() in localStorage
Uncaught TypeError: Failed to execute 'getItem' on 'Storage': Argument 1 is a symbol, which cannot be converted to a string
at makeException (ext:deno_webidl/00_webidl.js:88:10)
at Array.converters.DOMString (ext:deno_webidl/00_webidl.js:392:11)
at Storage.getItem (ext:deno_webstorage/01_webstorage.js:58:29)
at Object.has (ext:deno_webstorage/01_webstorage.js:122:24)
at <anonymous>:2:10
```
> fix(ext/web): webstorage has trap for symbol

- cli/tests/unit/tty_color_test.ts
- runtime/js/99_main.js
- runtime/ops/bootstrap.rs
`Deno.noColor` is only based on `NO_COLOR` env var, and `noColor` flag for `console` is based on `NO_COLOR` and `isTty` of stdout. But it seems these were aligned to the latter in #21164.
This PR restores the original handling of `Deno.noColor`
closes #21207
> fix(runtime): fix Deno.noColor when stdout is not tty

- cli/tools/installer.rs
> fix(cli): Allow executable name start with digit

- Cargo.lock
- Cargo.toml
- cli/tests/integration/cert_tests.rs
- cli/tests/testdata/cert/listen_tls_alpn_fail.ts
- cli/tests/testdata/run/websocket_test.ts
- cli/tests/unit/tls_test.ts
- ext/http/http_next.rs
- ext/net/Cargo.toml
- ext/net/ops_tls.rs
- ext/net/raw.rs
- runtime/ops/http.rs
Fixes #21121 and #19498
Migrates fully to rustls_tokio_stream. We no longer need to maintain our own TlsStream implementation to properly support duplex.
This should fix a number of errors with TLS and websockets, HTTP and "other" places where it's failing.
> feat(ext/net): use rustls_tokio_stream

- cli/tests/unit/cron_test.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/cron/01_cron.ts
- ext/cron/local.rs
This PR changes the `Deno.cron` API:
* Marks the existing function as deprecated
* Introduces 2 new overloads, where the handler arg is always last:
```ts
Deno.cron(
name: string,
schedule: string,
handler: () => Promise<void> | void,
)
Deno.cron(
name: string,
schedule: string,
options?: { backoffSchedule?: number[]; signal?: AbortSignal },
handler: () => Promise<void> | void,
)
```
This PR also fixes a bug, when other crons continue execution after one of the crons was closed using `signal`.
> feat(ext/cron) modify Deno.cron API to make handler arg last

- ext/web/Cargo.toml
`cargo build` passes in `ext/web` with this change. cf. https://github.com/denoland/deno/actions/runs/6899828165/job/18772042978
related https://github.com/denoland/deno/pull/21158
> chore(ext/web): fix ext/web build

- cli/tests/integration/run_tests.rs
> ci: fix flaky stdio_streams_are_locked_in_permission_prompt

- cli/lsp/language_server.rs
- cli/tools/upgrade.rs
I was investigating the flaky repl startups in #21187 and thinking it might be related to the upgrade check, but not sure. Anyway, I wanted to modify the upgrade code, but we didn't have any tests for it, so this is a refactor to get the upgrade code unit testable. After this, I'll open a separate PR sometime to add integration tests that use the test server (I realize I'm somewhat doing this backwards from recommended practice--should do integration tests first--but I've done some manually testing), then I'll change the behaviour.
> refactor(upgrade): add unit tests for lsp upgrade check

- cli/tests/unit/rename_test.ts
- cli/tests/unit/test_util.ts
Renaming a directory to a path where a non-empty directory already exists was asserted to always fail with `ENOTEMPTY`
According to glibc manual the function may also fail with `EEXIST` on "some other systems". One such case is using XFS [^1].
This commit handles the EEXIST case.
[^1]: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/fs/xfs/xfs_inode.c?h=v4.18&id=94710cac0ef4ee177a63b5227664b38c95bbf703#n3082
> chore(cli): Fix rename test for XFS

- cli/tests/unit/serve_test.ts
- ext/http/http_next.rs
Fixes #21250
We were attempting to recycle dropped resource responses too early.
> fix(ext/http): fix crash in dropped Deno.serve requests

- Cargo.lock
- Cargo.toml
- ext/http/Cargo.toml
Syncs the changes to main for a deno_http version bump we needed to do. `deno_http` v1.20 was released from the v1.38 branch.
> chore(ext/http): bump version for re-release

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- tools/util.js
This is a prerequisite to automatic code signing.
> chore: add aarch64-apple-darwin builds to ci

- cli/tests/unit_node/process_test.ts
- ext/io/12_io.js
Fixes https://github.com/denoland/deno/issues/21112
Aligns more towards what Node.js does. Closing stdin more than once is a nop.
> fix(ext/node): handle closing process.stdin more than once

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
Fix in https://github.com/dprint/dprint-plugin-typescript/commit/0b44991bb9cbc35999796c9864e68d8e4a0f9245
Closes https://github.com/denoland/deno/issues/21279
> fix(fmt): maintain parens for jsx in member expr

- tools/format.js
- tools/util.js
This will allow this format script to work on more architectures. Also, this upgrade fixes the issue with the unstable incremental cache that's currently on main.
> chore(tools): pull dprint from npm instead of third_party

- test_util/src/pty.rs
This is an attempt to fix this flakiness by increasing the repl test startup timeout:
```
---- integration::repl::assign_underscore stdout ----
deno_exe path /home/runner/work/deno/deno/target/release/deno
command /home/runner/work/deno/deno/target/release/deno repl
command cwd /tmp/deno-cli-testK3YASC
------ Start Full Text ------
""
------- End Full Text -------
Next text: ""
thread 'integration::repl::assign_underscore' panicked at test_util/src/pty.rs:41:11:
Timed out.
stack backtrace:
```
> ci: attempt to make repl tests less flaky at startup on the CI

- cli/tests/unit_node/stream_test.ts
- ext/node/polyfills/_stream.mjs
The current implementation of `Writable` of `node:stream` has an issue in handling `onConstruct` callback. When `writable.write` is called at certain timing near the end of `writable._construct`, that chunk overtakes the chunks that are stored in the internal buffer of `writable`. See examples in #20456 for details.
Node.js had a very similar (probably the same) issue https://github.com/nodejs/node/issues/46765, and it was fixed by https://github.com/nodejs/node/pull/46818.
This PR applies the same fix as https://github.com/nodejs/node/pull/46818, and the original example given in #20456 works as expected.
closes #20456
> fix(ext/node): fix node:stream.Writable

- cli/tests/integration/upgrade_tests.rs
- cli/tools/upgrade.rs
- test_util/src/builders.rs
- test_util/src/lib.rs
1. Adds an upgrade prompt integration test.
1. Adds a test for when the upgrade check takes a long time in the repl.
1. ~~Maybe makes the REPL tests more reliable by disabling the upgrade check in the repl tests.~~ Edit: Nope
> chore: add upgrade prompt integration test

- ext/http/http_next.rs
- ext/http/service.rs
Follow-up to #20822. cc @lrowe 
The `httpServerExplicitResourceManagement` tests were randomly failing on CI because of a race.
The `drain` waker was missing wakeup events if the listeners shut down after the last HTTP response finished. If we lost the race (rare), the server Rc would be dropped and we wouldn't poll it again.
This replaces the drain waker system with a signalling Rc that always resolves when the refcount is about to become 1.
Fix verified by running serve tests in a loop:
```
for i in {0..100}; do cargo run --features=__http_tracing -- test
-A --unstable '/Users/matt/Documents/github/deno/deno/cli/tests/unit/ser
ve_test.ts' --filter httpServerExplicitResourceManagement; done;
```
> fix(ext/http): avoid lockup in graceful shutdown

- cli/tests/integration/upgrade_tests.rs
- test_util/src/lib.rs
Issue was main does canary builds, which broke this test because it didn't handle searching for a canary release. Tested by building as canary locally.
> chore: fix upgrade_prompt test on main

- test_util/src/builders.rs
- test_util/src/pty.rs
Example:
```
---- integration::upgrade::upgrade_lsp_repl_sleeps stdout ----
thread 'integration::upgrade::upgrade_lsp_repl_sleeps' panicked at test_util\src\builders.rs:156:7:
Found deno configuration file at V:\deno.jsonc. The test suite relies on a deno.json not existing in any ancestor directory. Please delete this file so the tests won't auto-discover it.
---- integration::upgrade::upgrade_prompt stdout ----
thread 'integration::upgrade::upgrade_prompt' panicked at test_util\src\builders.rs:156:7:
Found deno configuration file at V:\deno.jsonc. The test suite relies on a deno.json not existing in any ancestor directory. Please delete this file so the tests won't auto-discover it.
```
Closes #21312
Closes …
> chore: provide error message when a deno.json will be auto-discovered by the test suite

- Cargo.lock
- cli/Cargo.toml
Has these two fixes for `deno task`:
* https://github.com/denoland/deno_task_shell/pull/98
* https://github.com/denoland/deno_task_shell/pull/99
> fix(task): use exit code 127 for command not found and parse escaped parens

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- cli/entitlements.plist
- tools/util.js
- Adds a codesigning step to all mac targets
- Adds a new ci-full label to the build to force aarch64 builds on any PR
> chore: start codesigning mac release builds

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
This is to reduce duplicate dependencies for https://github.com/denoland/deno/pull/21310
> chore: bump jsonc-parser and dprint-core dependencies

- cli/tests/unit_node/crypto/crypto_key_test.ts
Ref https://github.com/denoland/deno/issues/21187
On CI we are going to run only fast tests, with an option to
pass `SLOW_TESTS=1` env var to enable more comprehensive tests.
> chore: deflake unit_node/crypto/crypto_key_test.ts

- cli/tests/unit_node/stream_test.ts
This test case is covered by the last case in https://github.com/denoland/deno/blob/5710fffb120eba88e1b261e3ef379cb02575de42/cli/tests/node_compat/test/parallel/test-stream2-transform.js and not necessary anymore.
More context: #21297 https://github.com/nodejs/node/pull/46818 #21328
> chore(ext/node): remove unnecessary test case

- cli/tsc/dts/lib.deno.ns.d.ts
https://github.com/denoland/deno/blob/2941dd7da8a310cb898b4180a4511cde60d5375d/runtime/js/40_process.js#L324-L331
As seen above, what `Deno.ChildProcess` actually implements is `AsyncDisposable`, but the type declaration says it's `Disposable`. This PR fixes the type declaration to match the actual implementation.
> fix(dts): `Deno.ChildProcess` actually implements `AsyncDisposable`

- cli/args/flags.rs
- cli/main.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/unsafe_proto/main.js
- cli/tests/testdata/run/unsafe_proto/main.out
- cli/tests/testdata/run/unsafe_proto/main_with_unsafe_proto_flag.out
- cli/tests/testdata/run/unsafe_proto/worker.js
- cli/worker.rs
- runtime/js/90_deno_ns.js
- runtime/js/99_main.js
Closes https://github.com/denoland/deno/issues/21276
> feat(unstable): --unstable-unsafe-proto

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
- cli/args/flags.rs
- cli/build.rs
- cli/tests/integration/fmt_tests.rs
- cli/tests/testdata/fmt/badly_formatted.ipynb
- cli/tests/testdata/fmt/badly_formatted_fixed.ipynb
- cli/tests/testdata/fmt/expected_fmt_check_verbose_tests_dir.out
- cli/tools/fmt.rs
- resolves #20810
<details><summary>outdated</summary>
changed to using dprint's jupyter plugin
I'm not sure if  `cli/tools/fmt.rs` is the correct place for 4 struct for jupyter notebook definition. Which module should i move the structs to?
not sure which field is the best. currently using
`self.metadata.language_info.name == "typescript"`
I'm suspecting `include_str!` macro is busting incremental build caches.
iterating twice (first: format cells, second: check if changes are identical) sounds inefficient, but i'm slightly against using mutation here.
```
$ cargo run --features __runtime_js_sources -- fmt cli/tests/testdata/fmt/badly_formatted_fixed.ipynb
$ cargo test --features __runtime_js_sources integration::fmt
```
EDIT: fixed by changing from `HashMap` to `BTreeMap`.
related: …
> feat(fmt): Support `.ipynb` extension

- cli/tests/integration/upgrade_tests.rs
- test_util/src/lib.rs
Makes this test less flaky by allowing way more time for the test to occur in.
> ci: make upgrade_lsp_repl_sleeps less flaky

- Cargo.lock
- Cargo.toml
- ext/http/Cargo.toml
- ext/http/service.rs
Rust 1.74 may have made this code temporarily valid in [#113126 Replace old private-in-public diagnostic with type privacy lints](https://github.com/rust-lang/rust/pull/113126), so we didn't catch it at build time.
It fails in 1.73 and +nightly, however.
> chore(ext/http): fix E0446 on some compiler versions

- cli/tests/node_compat/test/parallel/test-stream-duplex-from.js
- ext/node/polyfills/_stream.mjs
This PR re-enables one test case disabled in #21328 by applying the same fix to `duplexify` as https://github.com/nodejs/node/pull/45133
part of #21336 (there are still other cases remaining)
> fix(ext/node): fix duplexify compatibility

- cli/tests/node_compat/config.jsonc
- cli/tests/node_compat/test/parallel/test-buffer-alloc.js
- cli/tests/node_compat/test/parallel/test-buffer-copy.js
- ext/node/polyfills/internal/buffer.mjs
This PR re-enables a test case ignored in #21328. The test case revealed the bug of Buffer#copy implementation, which has been fixed in https://github.com/nodejs/node/pull/47758 in Node.js repo.
closes #21335
> fix(ext/node): fix Buffer.copy when sourceStart > source.length

- Cargo.lock
- Cargo.toml
- ext/web/13_message_port.js
* Depends on: https://github.com/denoland/deno_core/pull/207
NOTE: Remove TMP commit before merging.
> perf(ext/web): Avoid changing prototype by setting hostObjectBrand directly

- cli/tsc/dts/lib.deno.unstable.d.ts
Moving the deprecated `Deno.cron` overload to be the last one.
> fix(cron): move deprecated Deno.cron overload

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
Reported by Luca. Fix is at https://github.com/dprint/dprint-plugin-typescript/pull/589
> fix(fmt): remove trailing comma for single type param in default export in jsx

- cli/tools/installer.rs
Fixes #6408.
This is what the url crate partially does behind the scenes.
> fix(cli/installer): percent decode name

- cli/tests/unit_node/process_test.ts
- ext/node/polyfills/process.ts
Closes https://github.com/denoland/deno/issues/21424
> fix(node): setting process.exitCode should change exit code of process

- cli/tsc/99_main_compiler.js
Our `host.getScriptSnapshot()` had not been populating the `sourceFileCache`.
> perf(lsp): fix redundant serialization of sources

- cli/Cargo.toml
- cli/build.rs
- cli/js/99_main.js
- cli/ops/mod.rs
- cli/worker.rs
- runtime/build.rs
- runtime/snapshot.rs
- runtime/web_worker.rs
- runtime/worker.rs
This commit removes some of the technical debt related 
to snapshotting JS code:
- "cli/ops/mod.rs" and "cli/build.rs" no longer define "cli" extension
which was not required anymore
- Cargo features for "deno_runtime" crate have been unified in "cli/Cargo.toml"
- "cli/build.rs" uses "deno_runtime::snapshot::create_runtime_snapshot" API
instead of copy-pasting the code
- "cli/js/99_main.js" was completely removed as it's not necessary anymore
Towards https://github.com/denoland/deno/issues/21137
> refactor: snapshotting of runtime/ and cli/

- cli/build.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/mod.rs
This commit changes the argument that "op_load" accepts, from
a serde struct to "&str". This should equal to a slightly better performance.
> refactor: faster args for op_load in TSC

- cli/lsp/diagnostics.rs
- cli/lsp/tsc.rs
A lot of requests get cancelled before they get to the front of the queue. This should speed up those cases.
> perf(lsp): check tsc request cancellation before execution

- cli/tests/testdata/bench/no_check.out
- cli/tests/testdata/bench/unhandled_rejection.out
- cli/tests/testdata/bench/unresolved_promise.out
- cli/tools/bench/mod.rs
- cli/tools/bench/reporters.rs
- cli/tools/test/mod.rs
- runtime/web_worker.rs
- runtime/worker.rs
Extracting some refactorings for the module work that will land in https://github.com/denoland/deno_core/pull/359/
> refactor(cli): refactor bench/test for future module changes

- cli/tests/integration/js_unit_tests.rs
- cli/tests/unit/kv_queue_test.ts
- cli/tests/unit/kv_queue_undelivered_test.ts
- ext/kv/01_db.ts
If KV is closed and tries to listen queue should throw an error.
-  https://github.com/denoland/deno/issues/20991
> fix(kv): throw error if already closed

- cli/tools/fmt.rs
I was going over this feature with Andy and noticed this bug. We use `PreferDouble` config for double quotes and so we should do it with single quotes (same thing as prettier).
> fix(fmt): `"singleQuote": true` should prefer single quote—not always use one

- cli/tests/unit/fetch_test.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/fetch/22_http_client.js
This commit adds a method of `Symbol.dispose` to the object returned from `Deno.createHttpClient`, so we can make use of [explicit resource management](https://github.com/tc39/proposal-explicit-resource-management) by declaring it with `using`.
> feat(ext/fetch): allow `Deno.HttpClient` to be declared with `using`

- cli/tests/unit_node/os_test.ts
Now the test case compares the difference of free memory in log scale (It only fails when one value is 10 times bigger or smaller than the other)
closes #21473
> test(ext/node): compare free memory in log scale

- Cargo.lock
- cli/Cargo.toml
- cli/tools/repl/editor.rs
Prerequisite for https://github.com/denoland/deno/pull/18453.
This update also makes it possible to address https://github.com/denoland/deno/issues/8049 by
using https://docs.rs/rustyline/latest/rustyline/struct.Editor.html#method.create_external_printer
> chore: update rustyline to 13.0.0

- cli/factory.rs
- cli/graph_util.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/module_loader.rs
- cli/resolver.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/integration/run_tests.rs
- cli/tools/bench/mod.rs
- cli/tools/test/mod.rs
- cli/tools/vendor/build.rs
For example:
```shellsession
> cat example.ts
import { Example } from "./routes";
console.log(Example);
> ../deno/target/debug/deno run example.ts                          
error: Module not found "file:///V:/scratch/routes". Maybe add a '.ts' extension or run with --unstable-sloppy-imports
at file:///V:/scratch/example.ts:1:25
> ../deno/target/debug/deno run --unstable-sloppy-imports example.ts
Warning Sloppy import resolution (hint: add .ts extension)
at file:///V:/scratch/example.ts:1:25
[class Example]
```
> feat: add suggestions to module not found error messages for file urls

- ext/node/polyfills/_tls_wrap.ts
This PR is an attempt to fix https://github.com/denoland/deno/issues/20293, in which node modules connecting to databases fail due to TLS errors. I ran into this attempting to use [node-postgres](https://github.com/brianc/node-postgres) to connect to a [Neon](https://neon.tech) database.
Investigating via `--inspect-brk` led me to notice that the hostname eventually passed to `Deno.startTls` was null. The hostname is determined by the following code:
https://github.com/denoland/deno/blob/f6b889b43219e3c9be770c8b2758bff3048ddcbd/ext/node/polyfills/_tls_wrap.ts#L87-L89
This logic doesn't appear to be correct. I couldn't find reference to `servername` existing on the `secureContext` in either Node's or Deno's docs. There's a lot of scope here, and it's my first time reading through this …
> fix(node/tls) Fix NotValidForName for host set via socket / servername

- cli/args/flags.rs
part of #21325
This PR adds default value to `--coverage` option. If a user only specifies `--coverage`, it uses `coverage` directory for coverage data output.
This aligns with the convention of existing JS coverage tooling ecosystem (`jest` and `nyc` use the same default directory)
> feat(test): add default to --coverage option

- ext/url/01_urlpattern.js
This significantly optimizes URLPattern in the case where the same
URL is matched against many patterns (like in a router).
Also minor speedups to other use-cases.
---
Bench code:
```ts
const pattern = new URLPattern({ pathname: "/:bar" });
const pattern2 = new URLPattern({ pathname: "/bar" });
const urls = Array.from({ length: 100 }, () => {
return `https://example.com/${crypto.randomUUID()}`;
});
const patterns = urls.filter((_, i) => i % Math.ceil(urls.length / 100) === 0)
.map((url) => new URLPattern({ pathname: new URL(url).pathname }));
console.log(patterns.length);
Deno.bench("one pattern, random url, match", () => {
const res = pattern.exec(`https://example.com/${crypto.randomUUID()}`);
});
Deno.bench("one pattern, random url, no match", () => {
const res = …
```
> perf(ext/url): improve URLPattern perf

- cli/tests/unit_node/http_test.ts
- ext/node/polyfills/http.ts
This commit adds a no-op flushHeaders method to the ServerResponse object. It is a nop because the ServerResponse implementation is based on top of the Deno server API instead of the Node `OutgoingMessage` base.
Fixes #21509
> fix(ext/node): stub ServerResponse#flushHeaders

- cli/tests/unit_node/http_test.ts
- ext/node/polyfills/http.ts
Matches Node's return type.
Next.js check for `if (header === undefined)`:
https://github.com/vercel/next.js/blob/e02fe314dcd0ae614c65b505c6daafbdeebb920e/packages/next/src/server/base-http/node.ts#L93
> fix(ext/node): ServerResponse getHeader() return undefined

- cli/tests/node_compat/config.jsonc
- cli/tests/node_compat/test/parallel/test-buffer-alloc.js
- cli/tests/node_compat/test/parallel/test-buffer-bytelength.js
- cli/tests/node_compat/test/parallel/test-querystring.js
- cli/tests/node_compat/test/parallel/test-util-inspect.js
- cli/tests/node_compat/test/parallel/test-util-promisify.js
- cli/tests/node_compat/test/parallel/test-util-types.js
This PR uncomments Node.js compat test cases which was enabled by the addition of `vm.runInNewContext` https://github.com/denoland/deno/pull/21527
> test(ext/node): enable some compat test cases

- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/mod.rs
Remove some dead code in "99_main_compiler.js". Eagerly start the LSP TSC host,
it was adding some not needed complexity around the TSC thread code.
> perf(lsp): simplify some of the startup code

- Cargo.lock
- cli/Cargo.toml
Upgrades deno_doc for https://github.com/denoland/deno_graph/pull/344
> fix: ignore more paths in dynamic arg module search

- .editorconfig
This PR updates `.editorconfig`. In node compat test cases, they sometimes contain trailing spaces, and it's not desirable for the editor to automatically remove them. This change prevents it
> chore: modify editorconfig settings

- cli/lsp/tsc.rs
- cli/tests/integration/lsp_tests.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/mod.rs
When tsc tries to load types for a module which had failed to resolve (labelled `internal:///missing_dependency.d.ts`), return null instead of a stub module like:
```ts
declare const __: any;
export = __;
```
#20780 fixed a discrepancy between `deno check` and LSP type-checking where that latter was returning null from `op_load()` instead of using the above stub module. After seeing https://github.com/denoland/vscode_deno/issues/895#issuecomment-1850960544 we suspect that this caused a slowdown in projects using node compat. So this PR flips them both the other way.
As far as we know this change only affects the behaviour of doing erroneous `type` imports from untyped modules. These will no longer error and there's no real reason they should.
> perf(lsp): use null types instead of stub modules

- cli/args/flags.rs
- cli/tests/integration/coverage_tests.rs
- cli/tools/coverage/reporter.rs
This PR changes `--pretty` flag of `deno coverage` command to `--detailed` as 'pretty' sounds confusing because the default (summary) output is already in a pretty format.
Note: `--pretty` flag has been landed in https://github.com/denoland/deno/pull/21535 and it's not yet been shipped.
> fix(coverage): rename --pretty to --detailed

- cli/tests/unit/kv_test.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/kv/01_db.ts
- ext/kv/lib.rs
```ts
const kv = await Deno.openKv();
const { versionstamp } = await kv.set(["logs", kv.commitVersionstamp()], "a");
const { value } = await kv.get(["logs", versionstamp]); // value === "a"
```
> feat(unstable): append commit versionstamp to key

- cli/tests/unit_node/zlib_test.ts
- ext/node/polyfills/_zlib_binding.mjs
Fixes https://github.com/denoland/deno/issues/21096
> fix(zlib): handle no flush flag in handle_.write

- cli/tsc/dts/lib.deno.ns.d.ts
This change deprecates `Deno.Reader`, `Deno.ReaderSync`, `Deno.Writer`, `Deno.WriterSync` and `Deno.Closer` in favour of the [Web Streams API](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API). After discussing with Yoshiya, we both thought now might be the right time to deprecate these interfaces with v2 getting closer.
> chore: deprecate `Deno.Reader`, `Deno.ReaderSync`, `Deno.Writer`, `Deno.WriterSync` and `Deno.Closer`

- cli/tests/unit_node/vm_test.ts
- ext/node/polyfills/vm.ts
https://github.com/denoland/deno/issues/20851#issuecomment-1779226106 for `jsdom`
> fix(node): return false from vm.isContext

- Cargo.lock
- ext/http/Cargo.toml
- ext/http/fly_accept_encoding.rs
- ext/http/http_next.rs
- ext/http/lib.rs
Blocks update to Hyper 1.0. It's a really small library, no need to pull it as a dependency.
Blocker for #21583
> refactor(ext/http): fork fly_accept_encodings crate

- cli/lsp/tsc.rs
Fixes #21557.
Fixes #21559.
In some cases tsc's auto-import completions will have the edit in `CompletionItem::text_edit` rather than `CompletionEntryDetails::code_actions`. I can make it happen in the fresh repo but I don't know how to simply reproduce it.
> fix(lsp): apply specifier rewrite to CompletionItem::text_edit

- cli/args/mod.rs
Fixes https://github.com/denoland/deno/issues/21594
I verified locally that this fixes the problem. I'm working on testing 
harness for Jupyter kernel to catch regressions like this and will
add it in a follow up PR.
> fix(jupyter): Deno.test() panic

- cli/args/flags.rs
This PR sets `coverage/` as the default include path for `deno coverage` command.
This default value is aligned with the default value of `--coverage` option of `deno test` command, which was added in https://github.com/denoland/deno/pull/21510
The idea is from https://github.com/denoland/deno/pull/21615#issuecomment-1859164539
related https://github.com/denoland/deno/issues/21325
> feat(coverage): add default coverage include dir

- cli/napi/js_native_api.rs
`napi_open_handle_scope` was returning a bogus handle_scope and we were trying to close it in `napi_close_handle_scope`.
This is a bit of a challenge to test, but the following testcase comes from #21601 and appears to be fixed by this.
```
import { decode } from "https://deno.land/std@0.209.0/encoding/base64.ts";
import sharp from "npm:sharp";
const img = 'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEAAQMAAABmvDolAAAAA1BMVEWq09/P7Lz1AAAAH0lEQVRoge3BAQ0AAADCoPdPbQ43oAAAAAAAAAAAvg0hAAABmmDh1QAAAABJRU5ErkJggg==';
Deno.test("async", async () => {
const id = setTimeout(() => Deno.exit(1), 1000);
await sharp(decode(img)).toBuffer();
await sharp(decode(img)).toBuffer();
clearTimeout(id);
});
```
> fix(ext/napi): don't close handle scopes in NAPI as the pointers are invalid

- cli/tests/unit/console_test.ts
- ext/console/01_console.js
- ext/console/lib.rs
- ext/node/lib.rs
- ext/node/polyfills/internal/console/constructor.mjs
- ext/node/polyfills/internal_binding/types.ts
- ext/node/polyfills/internal_binding/util.ts
- ext/node/polyfills/util.ts
This PR includes the following fixes:
Fixed a bug that `{Set, Map}Iterator`'s `[[Prototype]]` were not displaying properly
current:
```
> Object.getPrototypeOf( new Set([1, 2, 3]).values() )
[Internal Formatting Error] TypeError: Method Set Iterator.prototype.next called on incompatible receiver #<Iterator>
at Set Iterator.next (<anonymous>)
at previewEntries (ext:deno_console/01_console.js:143:21)
at formatIterator (ext:deno_console/01_console.js:1511:41)
at formatRaw (ext:deno_console/01_console.js:1053:14)
at formatValue (ext:deno_console/01_console.js:736:10)
at Object.inspectArgs (ext:deno_console/01_console.js:3128:28)
at <anonymous>:3:55
```
this PR:
```
> Object.getPrototypeOf( new Set([1, 2, 3]).values() )
Iterator [Set Iterator] {}
```
This change also improves inspect, such as …
> fix(console): inspect for `{Set,Map}Iterator` and `Weak{Set,Map}`

- cli/tests/unit_node/internal/_randomBytes_test.ts
- ext/node/polyfills/crypto.ts
Deprecated in Node.js, alias of randomBytes.
Fixes https://github.com/denoland/deno/issues/21632
> fix(node): add crypto.pseudoRandomBytes

- cli/tests/unit/kv_test.ts
- ext/kv/lib.rs
> fix(unstable): kv watch should stop when db is closed

- ext/kv/remote.rs
The [KV Connect specification](https://github.com/denoland/denokv/blob/main/proto/kv-connect.md) says:
> KV Connect compatible backends MUST support HTTP/1.1 and HTTP/2.
So we can default to HTTP/2 in the CLI to maximize performance.
> feat(unstable): only allow http2 for kv remote backend

- cli/ops/jupyter.rs
- ext/fetch/lib.rs
- ext/http/lib.rs
- ext/node/ops/http2.rs
Node HTTP/2 was using the default h2 `Bytes` datatype when we can be making using of `BufView` like we do in `Deno.serve`.
`fetch` and `Deno.serverHttp` can't make use of `BufView` because they are using `reqwest` which is stuck on hyper 0.x at this time.
> chore(ext/node): use BufView natively in http2

- cli/tests/unit_node/http_test.ts
- ext/node/polyfills/http.ts
Fixes https://github.com/denoland/deno/issues/18316
> fix(ext/node): add ClientRequest#setNoDelay

- Cargo.toml
- ext/websocket/Cargo.toml
- ext/websocket/lib.rs
- runtime/Cargo.toml
- runtime/inspector_server.rs
- test_util/Cargo.toml
- test_util/src/servers/ws.rs
We now use only a single version of "fastwebsockets" crate, so we no
longer need to have an alias.
> refactor: fastwebsockets renames

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tests/integration/lsp_tests.rs
- cli/tsc/99_main_compiler.js
For a project containing `deno.json | file1.ts | file2.ts | file3.ts`, when typing a single character in `file1.ts`, with logs set up for tsc requests; `op_project_version()`; `op_script_names()`; `op_load()` and `op_script_version()`, you get the following output:
<details>
<summary>Before (501 lines):</summary>
```
request("getCompletionsAtPosition")
op_script_names()
op_script_version("asset:///lib.es5.d.ts")
op_script_version("asset:///lib.es2015.d.ts")
op_script_version("asset:///lib.es2016.d.ts")
op_script_version("asset:///lib.es2017.d.ts")
op_script_version("asset:///lib.es2018.d.ts")
op_script_version("asset:///lib.es2019.d.ts")
op_script_version("asset:///lib.es2020.d.ts")
op_script_version("asset:///lib.es2021.d.ts")
op_script_version("asset:///lib.es2022.d.ts") …
```
> perf(lsp): use LanguageServiceHost::getProjectVersion()

- cli/tests/testdata/run/import_meta/importmap.json
- cli/tests/testdata/run/import_meta/main.out
- cli/tests/testdata/run/import_meta/main.ts
- runtime/web_worker.rs
- runtime/worker.rs
Closes https://github.com/denoland/deno/issues/21298.
"npm:" specifiers are matched against import map entries
and if no match is found they are passed through.
> fix: allow npm: specifiers in import.meta.resolve

- cli/tests/node_compat/test/internet/test-dns-any.js
- cli/tests/node_compat/test/internet/test-dns.js
These tests started failing on CI on Dec 28th, 2023 returning
ENOTFOUND. It's unclear what's going on, since `dig -x 8.8.8.8.in-addr.arpa`.
It needs a deeper investigation, but I want to unblock main branch
in the meantime.
> chore: disable PTR_HOST dns test for Node compat

- cli/tests/unit_node/zlib_test.ts
- ext/node/polyfills/_brotli.js
This fixes point 2 of #20516 
This adds a conversion from Dataview/Buffer by returning `obj.buffer` which can be converted to a `UInt8Array`.
Question: Regarding point 4 of the mentioned issue would it be appropriate to copy the toU8 helper to the `zlib.mjs` methods?
> fix(node/zlib): cast Dataview and Buffer to uint8

- cli/tests/unit_node/zlib_test.ts
- ext/node/polyfills/_brotli.js
This fixes point 3 of https://github.com/denoland/deno/issues/20516
This PR creates consistency between the sync and async versions of the brotli compress where we will always return a buffer like Node.
> fix(node/zlib): consistently return buffer

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- cli/args/mod.rs
- cli/cache/mod.rs
- cli/lsp/analysis.rs
- cli/lsp/code_lens.rs
- cli/lsp/config.rs
- cli/lsp/testing/collectors.rs
- cli/tests/integration/lsp_tests.rs
- cli/tools/coverage/merge.rs
- cli/tools/coverage/mod.rs
- cli/tools/task.rs
- cli/tsc/mod.rs
- ext/crypto/import_key.rs
- ext/crypto/lib.rs
- runtime/ops/process.rs
- rust-toolchain.toml
chore: update to Rust 1.75
I am not sure `cacheVersion` should be updated.
If this PR has any problem, please tell me.
> chore: update to Rust 1.75

- cli/tests/integration/js_unit_tests.rs
Alternative to #21758 to fix timing out tests on Windows.
> chore: increase unit test timeout to 3m

- ext/node/polyfills/_stream.mjs
Fixes https://github.com/denoland/deno/issues/21644
`next build` works:
```
~/gh/deno/target/debug/deno run -A --unstable-byonm ./node_modules/.bin/next build
Warning: Not implemented: process.on("rejectionHandled")
▲ Next.js 14.0.4
✓ Creating an optimized production build
✓ Compiled successfully
✓ Linting and checking validity of types
Collecting page data  ..Warning: Not implemented: process.on("rejectionHandled")
Warning: Not implemented: process.on("rejectionHandled")
Warning: Not implemented: process.on("rejectionHandled")
Warning: Not implemented: process.on("rejectionHandled")
Warning: Not implemented: process.on("rejectionHandled")
✓ Collecting page data
Generating static pages (0/5)  [    ]Warning: Not implemented: process.on("rejectionHandled")
Warning: Not implemented: …
```
> fix(ext/node): use node:process in _streams.mjs

- cli/tests/integration/lsp_tests.rs
Ref #21770. I thought I fixed the hang before landing but seems not. It works consistently in usage so let's ignore the test for now.
> chore: ignore hanging lsp jsx test

- cli/lsp/code_lens.rs
Fixes https://github.com/denoland/vscode_deno/issues/989.
> fix(lsp): support test code lens for Deno.test.{ignore,only}()

- test_util/src/servers/hyper_utils.rs
Test server was printing a lot of "early eof" messages eg when running
`cargo test integration::npm`. This commit filters out these messages.
> chore: make test server less noisy

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/permission_request_long.ts
- runtime/permissions/prompter.rs
Harden the code that does permission checks to protect against re-opening of stdin.
Code that runs FFI is vulnerable to an attack where fd 0 is closed during a permission check and re-opened with a file that contains a positive response (ie: `y` or `A`). While FFI code is dangerous in general, we can make it more difficult for FFI-enabled code to bypass additional permission checks.
- Checks to see if the underlying file for stdin has changed from the start to the end of the permission check (detects races)
- Checks to see if the message is excessively long (lowering the window for races)
- Checks to see if stdin and stderr are still terminals at the end of the function (making races more difficult)
> fix(cli): harden permission stdio check

- cli/tests/unit_node/console_test.ts
Missed in https://github.com/denoland/deno/commit/b2cd254c35b6b1b128beea0eacdb8e814d91e003#diff-0c2dcdd1ce20382e6ddefe52956cf2f570f18063cf09067f8a7ca44abaf33122
> fix(ci): copyright year for console_test.ts

- cli/args/flags.rs
Fixes https://github.com/denoland/deno/issues/21822
This updates the import-maps help URL to the one mentioned in the issue
> fix(cli): update import map url

- LICENSE.md
- tools/copyright_checker.js
Just noticed this was never updated.
> chore: update LICENSE.md to 2024

- cli/tsc/99_main_compiler.js
Fixes #21558. It's a sporadic error so not sure how to test for it, but it's definitely fixed.
> perf(lsp): use host-owned cache for auto-import completions

- ext/node/analyze.rs
Fixes https://github.com/denoland/deno/issues/21836
> fix: cjs export rewritten to invalid identifier

- cli/tests/integration/task_tests.rs
- cli/tests/testdata/task/package_json_node_modules_dir_false/bin.out
- cli/tests/testdata/task/package_json_node_modules_dir_false/deno.json
- cli/tests/testdata/task/package_json_node_modules_dir_false/package.json
- cli/tools/task.rs
There's no need to auto-install the package.json if the user is not using a node_modules directory.
Closes #21850
> fix(task): do not eagerly auto-install packages in package.json when `"nodeModulesDir": false`

- cli/tests/unit/websocket_test.ts
- ext/websocket/01_websocket.js
- test_util/src/servers/mod.rs
Fixes https://github.com/denoland/deno/issues/21840
The problem was hard to reproduce as its a race condition. I've added a test that reproduces the problem 1/10 tries. We should move the idleTimeout handling to Rust (maybe even built into fastwebsocket).
> fix(ext/websocket): pass on uncaught errors in idleTimeout

- cli/lsp/parent_process_checker.rs
Ensures the Deno process is brought down even when the runtime gets hung up on something.
Marvin found that the lsp was running without a parent vscode around so this is maybe/probably related.
> fix(lsp): use a dedicated thread for the parent process checker

- cli/tsc/99_main_compiler.js
Since #21852 I started seeing this error randomly sometimes for top-level completions:
```
Unable to get completion info from TypeScript: TypeError: host.getGlobalTypingsCacheLocation is not a function
at isNotShadowedByDeeperNodeModulesPackage (ext:deno_tsc/00_typescript.js:132847:41)
at ext:deno_tsc/00_typescript.js:132745:58
at Array.filter (<anonymous>)
at ext:deno_tsc/00_typescript.js:132745:41
at forEachEntry (ext:deno_tsc/00_typescript.js:12975:22)
at Object.search (ext:deno_tsc/00_typescript.js:132740:16)
at ext:deno_tsc/00_typescript.js:159128:22
at resolvingModuleSpecifiers (ext:deno_tsc/00_typescript.js:156655:20)
at collectAutoImports (ext:deno_tsc/00_typescript.js:159118:7)
at getGlobalCompletions (ext:deno_tsc/00_typescript.js:159048:7)
```
Some obscure location where this …
> fix(lsp): implement host.getGlobalTypingsCacheLocation()

- cli/tests/integration/test_tests.rs
- cli/tests/testdata/test/relative_pattern_dot_slash/deno.json
- cli/tests/testdata/test/relative_pattern_dot_slash/output.out
- cli/tests/testdata/test/relative_pattern_dot_slash/test/add.mjs
- cli/tests/testdata/test/relative_pattern_dot_slash/test/add.test.mjs
- cli/util/glob.rs
This is a hacky quick fix. We need to spend more time cleaning up this code and push more stuff down into deno_config.
Closes #21916
> fix(config): regression - handle relative patterns with leading dot slash

- cli/deno_std.rs
I accidentally merged the past PR (wanted to do auto-merge). This fixes it.
> chore: fix 1.39.4 release

- cli/tsc/dts/lib.deno.ns.d.ts
This change sets the removal for `Deno.run()` in v2.
> chore: define removal version for `Deno.run()`

- cli/tsc/dts/lib.deno.ns.d.ts
Sets the removal version for `Deno.metrics()` to be v2.
> chore: define removal version for `Deno.metrics()`

- cli/tests/unit/cache_api_test.ts
- ext/cache/01_cache.js
- ext/cache/lib.rs
- ext/cache/sqlite.rs
We can use `resourceForReadableStream` to ensure that cached resources are implemented more efficiently and remove one more resource special case.
> chore(ext/cache): remove CachePutResource in preparation for resource rewrite

- runtime/colors.rs
Previously every call to `style` would result in a copy of the input value, even if styling is disabled.
Now there are no explicit copies at all anymore, other than the ones in the internals of `std::fmt::Display` (which we already needed to go through anyway).
This net removes one `String` alloc per `style` call.
> perf: don't allocate so much in runtime/colors.rs

- cli/lsp/language_server.rs
- cli/lsp/lsp_custom.rs
- cli/tests/integration/lsp_tests.rs
So the client can be aware of all active `deno.json` files without walking the workspace. This changes the interface of the notification parameter, but it's not read in the extension.
> feat(lsp): send "deno/didChangeDenoConfiguration" on init

- cli/tests/unit_node/http_test.ts
- ext/node/polyfills/http.ts
Update the `req.socket` to be a `net.Socket` from `FakeSocket`
Fixes #21979
> fix(node): update `req.socket` on WS upgrade

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/args/mod.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/tests/integration/lsp_tests.rs
- cli/tools/coverage/mod.rs
- cli/tools/doc.rs
- cli/tools/registry/mod.rs
- cli/tools/vendor/mod.rs
- cli/util/fs.rs
~~Waiting on: https://github.com/denoland/deno_config/pull/31~~
Closes #21971
Closes https://github.com/denoland/vscode_deno/issues/1029
> fix(lsp): regression - formatting was broken on windows

- cli/tests/integration/jupyter_tests.rs
- cli/tests/testdata/jupyter/install_command_not_exists.out
- cli/tools/jupyter/install.rs
- cli/tools/jupyter/mod.rs
This commit removes the requirement for `--unstable` flag in `deno jupyter`
subcommand. The process will no longer exit if this flag is not provided,
however the subcommand itself is still considered unstable and might
change in the future.
Required for https://github.com/denoland/deno/pull/21452
> feat(jupyter): don't require --unstable flag

- ext/node/polyfills/_util/_util_callbackify.ts
> fix(node): remove use of non existing `FunctionPrototypeApply` primordial

- .cargo/local-build.toml
- Cargo.lock
- Cargo.toml
- ext/node/ops/crypto/x509.rs
Introduces the first cppgc backed Resource into Deno.
This fixes the memory leak when using `X509Certificate`
**Comparison**:
```js
import { X509Certificate } from 'node:crypto';
const r = Deno.readFileSync('cli/tests/node_compat/test/fixtures/keys/agent1-cert.pem');
setInterval(() => {
for (let i = 0; i < 10000; i++) {
const cert = new X509Certificate(r);
}
}, 1000);
```
Memory usage after 5 secs
`main`: 1692MB
`cppgc`: peaks at 400MB
> fix(node): use `cppgc` for managing X509Certificate

- cli/tests/unit_node/fs_test.ts
- ext/node/polyfills/fs.ts
- ext/node/polyfills/fs/promises.ts
We were missing the `constants` export in the promise `fs` API which is available in node.
```ts
import { constants, promises } from "node:fs";
import { constants as fsPromiseConstants } from "node:fs/promises";
console.log(constants === promises.constants); // logs: true
console.log(constants === fsPromiseConstants); // logs: true
```
Fixes https://github.com/denoland/deno/issues/21994
> fix(node/fs): promises not exporting fs constants

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/lsp/analysis.rs
- cli/tests/integration/lsp_tests.rs
- cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/dist/entry-a.js
- cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/dist/entry-b.d.ts
- cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/dist/entry-b.js
- cli/tests/testdata/npm/registry/@denotest/types-exports-subpaths/1.0.0/package.json
Extracted out from https://github.com/denoland/deno/pull/22004
Upgrades to the latest deno_semver
> fix(lsp): improved npm specifier to import map entry mapping

- cli/bench/deno_common.js
- cli/tests/unit/files_test.ts
- cli/tests/unit/http_test.ts
- cli/tests/unit/process_test.ts
- cli/tests/unit/serve_test.ts
- cli/tests/unit/utime_test.ts
- cli/tsc/dts/lib.deno.ns.d.ts
- tools/node_compat/setup.ts
This change takes advantage of explicit resources management for `FsFile` instances and tweaks documentation to encourage the use of it.
> chore: use `FsFile[Symbol.dispose]()`

- cli/Cargo.toml
- runtime/Cargo.toml
- runtime/web_worker.rs
- runtime/worker.rs
Fixes #21928.
We have a code path which empties the extension sources because they're expected to be pre-executed in the snapshot. Instead of using conditional compilation for that, we now just check if a snapshot was provided.
Removes the `dont_use_runtime_snapshot` feature. We didn't allow not providing a snapshot unless this feature was provided, now we always do.
Adds the `only_snapshotted_js_sources` feature for us to use in CLI. This asserts that a snapshot is provided and gates the runtime transpilation code so it isn't included in the executable.
Normally we would test this with dedicated example runs in CI but we removed those for performance in #20966.
> fix(runtime): only discard extension sources if a snapshot is provided

- cli/args/flags.rs
- cli/tests/testdata/test/short-pass-jobs-flag-warning.out
For removal in Deno v2. I'm uncertain of the output format but used #21452 as a guide.
Towards #22021
> refactor: set removal version for `--jobs` flag

- cli/tests/unit/serve_test.ts
- cli/tsc/dts/lib.deno.ns.d.ts
- ext/node/polyfills/http.ts
This change sets the removal version for the deprecated `Deno.Server` interface for Deno 2.0.
Towards #22021
> refactor: set removal version for `Deno.Server`

- cli/tests/unit_node/_fs/_fs_readFile_test.ts
- ext/node/polyfills/_fs/_fs_readFile.ts
We use `util.promisify` for creating `fs.promises.readFile`, but that doesn't support the case when it's called with no args (With no arg call, promisify passes the callback as the first arg of `fs.readFile`, and that is not supported). As reported in #21795, [isomorphic-git](https://www.npmjs.com/package/isomorphic-git) uses `fs.promises.readFile()` for checking the availability of `fs.promises`, and that causes an uncaught error.
This PR fixes the above by avoiding to use `promisify`, but using more primitive wrapper structure for creating promise version of `readFile`.
See also the comment https://github.com/denoland/deno/issues/21795#issuecomment-1903901348
closes #21795
> fix(ext/node): fix no arg call of fs.promises.readFile

- cli/tests/unit/cron_test.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/cron/01_cron.ts
This change removes the currently deprecated `Deno.cron()` overload with `options` as a potential last argument.
This might be fine to do now, in a major release, as `Deno.cron()` is an unstable API. I thought of doing this while working on #22021. If this is not ready to remove, I can instead set the removal version of this overload for Deno v2.
Note: this overload was deprecated in Deno v1.38.2 (#21225). So it's been deprecated for over 2 months.
CC @losfair
> BREAKING(unstable): remove `Deno.cron()` overload

- Cargo.lock
- cli/Cargo.toml
- cli/diagnostics.rs
- cli/main.rs
- cli/tests/integration/watcher_tests.rs
- cli/tests/testdata/doc/referenced_private_types_lint.out
- cli/tests/testdata/lint/expected_from_stdin.out
- cli/tests/testdata/lint/expected_from_stdin_json.out
- cli/tests/testdata/lint/expected_quiet.out
- cli/tests/testdata/lint/watch/badly_linted.js.out
- cli/tests/testdata/lint/watch/badly_linted_fixed1.js.out
- cli/tests/testdata/lint/with_config.out
- cli/tests/testdata/lint/with_config_and_flags.out
- cli/tests/testdata/lint/with_config_without_tags.out
- cli/tests/testdata/publish/invalid_fast_check.out
- cli/tests/testdata/publish/javascript_missing_decl_file.out
- cli/tools/doc.rs
- cli/tools/lint.rs
- cli/tools/registry/diagnostics.rs
- cli/tools/registry/graph.rs
- cli/tools/registry/mod.rs
- runtime/colors.rs
This initially uses the new diagnostic printer in `deno lint`,
`deno doc` and `deno publish`. In the limit we should also update
`deno check` to use this printer.
> feat(cli): improved diagnostics printing

- cli/args/flags.rs
- cli/tests/integration/run_tests.rs
It appears the `--prompt` flag has done nothing for some time. Perhaps, since #13650. Classifying this as a dead functionality removal for this reason.
Did this while working on #22021.
> fix(BREAKING): remove dead `--prompt` flag

- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/import_meta/main.out
- cli/tests/testdata/run/import_meta/main.ts
- cli/tests/testdata/run/import_meta/other.ts
- cli/tsc/dts/lib.deno.ns.d.ts
This commit adds `import.meta.filename` and `import.meta.dirname` APIs.
These APIs return string representation of filename and containing dirname.
They are only defined for local modules (modules that have `file:///` scheme).
Example:
```ts
console.log(import.meta.filename, import.meta.dirname)
```
Unix:
```
$ deno run /dev/my_module.ts
/dev/my_module.ts /dev/
```
Windows:
```
$ deno run C:\dev\my_module.ts
C:\dev\my_module.ts C:\
```
> feat: import.meta.filename and import.meta.dirname

- cli/tests/testdata/run/fetch_response_finalization.js
- cli/tests/unit/http_test.ts
- cli/tests/unit/read_file_test.ts
- cli/tests/unit/read_text_file_test.ts
- cli/tests/unit_node/_fs/_fs_appendFile_test.ts
- cli/tests/unit_node/_fs/_fs_close_test.ts
- cli/tests/unit_node/_fs/_fs_open_test.ts
- cli/tests/unit_node/_fs/_fs_rm_test.ts
- cli/tests/unit_node/_fs/_fs_rmdir_test.ts
- cli/tsc/dts/lib.deno.ns.d.ts
- ext/node/polyfills/http2.ts
- runtime/js/99_main.js
- test_ffi/tests/test.js
- test_ffi/tests/thread_safe_test.js
Most uses of `Deno.resources()` within tests, as they previously checked for leaked resources. This is not needed as the test runner does this automatically. Other internal uses of this API have been replaced with the internal `Deno[Deno.internal].core.resources()`.
> feat: deprecate `Deno.resources()`

- cli/js/40_testing.js
- cli/tests/unit/files_test.ts
- cli/tests/unit/utime_test.ts
- cli/tsc/dts/lib.deno.ns.d.ts
- ext/fs/30_fs.js
- ext/node/polyfills/_fs/_fs_fdatasync.ts
This change:
1. Implements `Deno.FsFile.dataSync()` and `Deno.FsFile.dataSyncSync()`.
2. Deprecates `Deno.fdatasync()` and `Deno.fdatasyncSync()` for removal in Deno v2, in favour of the above corresponding methods.
3. Replaces use of `Deno.fdatasync()` and `Deno.fdatasyncSync()` with the above instance methods.
Related #21995
> feat: `Deno.FsFile.dataSync()` and `Deno.FsFile.dataSyncSync()`

- cli/args/flags.rs
- cli/tests/testdata/bundle/shebang_file.bundle.out
- cli/tools/bundle.rs
This change sets the removal version for the `deno bundle` sub-command for Deno v2. The warnings appear when `deno bundle` is run and in the `--help` menu.
> refactor: set removal version for `deno bundle`

- ext/net/lib.deno_net.d.ts
- runtime/js/90_deno_ns.js
> feat: deprecate `Deno.shutdown()`

- cli/tsc/dts/lib.deno.ns.d.ts
- ext/fs/30_fs.js
- runtime/js/90_deno_ns.js
To align with other deprecations.
> chore: update `Deno.{fsync,fsyncSync}()` deprecation notices

- cli/tsc/dts/lib.deno.ns.d.ts
- runtime/js/90_deno_ns.js
> feat: deprecate `Deno.seek()` and `Deno.seekSync()`

- cli/tests/unit_node/tls_test.ts
- cli/tsc/dts/lib.deno.ns.d.ts
- runtime/js/90_deno_ns.js
> feat: deprecate `Deno.read()` and `Deno.readSync()`

- cli/tsc/dts/lib.deno.ns.d.ts
- ext/fs/30_fs.js
- ext/node/polyfills/_fs/_fs_readFile.ts
- ext/node/polyfills/_fs/_fs_writeFile.ts
- runtime/js/90_deno_ns.js
For removal in Deno 2.0. Other deprecations must be merged first.
> feat: deprecate `Deno.FsFile` constructor and `Deno.FsFile.rid`

- cli/tests/unit/sync_test.ts
- cli/tests/unit/truncate_test.ts
- cli/tests/unit_node/_fs/_fs_fsync_test.ts
- cli/tsc/dts/lib.deno.ns.d.ts
- ext/node/polyfills/_fs/_fs_ftruncate.ts
- runtime/js/90_deno_ns.js
> feat: deprecate `Deno.ftruncate()` and `Deno.ftruncateSync()`

- cli/tests/testdata/run/warn_on_deprecated_api/main.out
- runtime/js/99_main.js
Removes weird "frame like" characters and simplifies the output:
```
warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2.
Stack trace:
at file:///Users/ib/dev/deno/foo.js:2:8
hint: Use `stdStream.isTerminal()` instead.
warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2.
Stack trace:
at file:///Users/ib/dev/deno/foo.js:7:8
hint: Use `stdStream.isTerminal()` instead.
```
> feat: Change deprecation warning formatting

- cli/tests/unit/webgpu_test.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- cli/tsc/dts/lib.deno_webgpu.d.ts
- ext/webgpu/webgpu.idl
- changed `Deno.UnsafeWindowSurface` typings from accepting `Deno.UnsafePointerView` to `Deno.PointerValue`
- added width and height to `GPUCanvasConfiguration`
> chore: fix `Deno.UnsafeWindowSurface` typings

- cli/tests/testdata/npm/compare_globals/main.out
- cli/tests/testdata/run/webstorage/logger.ts
- cli/tests/testdata/run/webstorage/serialization.ts
- cli/tests/testdata/run/webstorage/setter.ts
- runtime/js/98_global_scope_window.js
- runtime/js/99_main.js
This reverts commit 930ce2087051b4e45b2026ce7a77c14360a6993f.
This is producing false-positives that are not actionable to users. We're gonna
address this in another release.
> Revert "feat: deprecate `window` global (#22057)"

- cli/args/mod.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/compile/npm_fs/main.ts
- cli/tests/testdata/npm/registry/@denotest/esm-basic/1.0.0/other.mjs
- cli/tests/testdata/package_json/basic/main.info.out
This commit adds automatic expansion of "imports" field in "deno.json" file.
If "npm:" or "jsr:" imports are encountered we automatically try to add a "directory"
remapping.
Previously users had to specify entries for both `foo` and `foo/` to be able to import like
`import { symbol1 } from "foo";` and `import { symbol2 } from "foo/some_file.js"`:
```
{
"imports": {
"foo": "npm:@foo/bar",
"foo/": "npm:/@foo/bar/",
}
```
With this change users can only add entry for `foo`:
```
{
"imports": {
"foo": "npm:@foo/bar",
}
```
The entry for `foo/` will be provided automatically.
Similarly if user provides "directory" remapping explicitly, we will not overwrite it.
> feat: Expand 'imports' section of deno.json

- ext/net/02_tls.js
> fix: use `warnOnDeprecatedApi()` in `Deno.TlsListener.rid`

- ext/net/02_tls.js
- runtime/js/40_fs_events.js
Otherwise, a deprecation warning will be printed.
> fix: don't call `.rid` in `Deno.FsWatcher.close()`

- Cargo.lock
- Cargo.toml
- cli/tests/integration/cert_tests.rs
- ext/net/ops_tls.rs
- ext/websocket/lib.rs
This reverts commit 971eb0e5e836cdeaaefc25b2bab4c6a6a9f8e213.
To unblock v1.40 release.
> Revert "chore: bump rustls-tokio-stream and rustls (#21955)"

- .dprint.json
- Cargo.toml
It now also sorts workspace members and dependencies in Cargo.toml files.
> chore: upgrade dprint-plugin-toml to 0.6.0

- cli/tests/node_compat/test.ts
- ext/fs/30_fs.js
- ext/node/polyfills/_fs/_fs_open.ts
- ext/node/polyfills/internal_binding/stream_wrap.ts
Closes https://github.com/denoland/deno/issues/22116
> fix(node): remove deprecation warnings

- cli/lsp/tsc.rs
- cli/tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/1036.
When you have `"typescript.suggest.completeFunctionCalls": true` and get completions with function parameters, now they are pre-highlighted and you can cycle through them with tab. See https://github.com/denoland/vscode_deno/issues/1036#issuecomment-1911107706 for a demo.
> feat(lsp): complete parameters as tab stops and placeholders

- cli/args/mod.rs
- cli/factory.rs
- cli/standalone/mod.rs
- cli/tests/integration/run_tests.rs
- cli/tests/testdata/run/warn_on_deprecated_api/main.out
- cli/tests/testdata/run/warn_on_deprecated_api/main.verbose.out
- cli/worker.rs
- runtime/js/99_main.js
- runtime/worker_bootstrap.rs
This commit makes deprecation warnings less verbose by default.
Only a single warnings is issued per deprecated API use.
`DENO_VERBOSE_WARNINGS` env var can be provided to enable more detailed
logging for each use of API including a stack trace.
> fix: make deprecation warnings less verbose

- ext/fs/30_fs.js
- ext/net/01_net.js
- ext/net/02_tls.js
Now these props will not show up when inspecting objects in console.
> refactor: make 'rid' properties non-enumerable

- cli/js/40_test.js
- cli/lsp/testing/execution.rs
- cli/ops/testing.rs
- cli/tests/testdata/test/resource_sanitizer.out
- cli/tools/test/fmt.rs
- cli/tools/test/mod.rs
- cli/tools/test/reporters/common.rs
- cli/tools/test/reporters/dot.rs
- cli/tools/test/reporters/pretty.rs
Step 1 of the Rustification of sanitizers, which unblocks the faster timers.
This replaces the resource sanitizer with a Rust one, using the new APIs in deno_core.
> refactor(cli): use new sanitizer for resources

- ext/napi/lib.rs
> fix(ext/node): limit OpState borrow in op_napi_open

- cli/lsp/capabilities.rs
- cli/lsp/code_lens.rs
- cli/lsp/language_server.rs
- cli/tests/integration/lsp_tests.rs
- test_util/src/lsp.rs
Addresses TODOs from https://github.com/denoland/vscode_deno/blob/3.33.3/client/src/extension.ts#L206-L217 partly. These aliases have existed for a long while now.
Also no longer require `"enableBuiltinCommands": true` to enable the server-defined commands. This existed because there used to be an overlap between commands defined on the client and server which would cause an error. That also hasn't been the case for a long while.
> chore(lsp): rename client-side command invocations

- ext/console/01_console.js
- ext/fetch/26_fetch.js
- ext/ffi/00_ffi.js
- ext/fs/30_fs.js
- ext/io/12_io.js
- ext/net/01_net.js
- ext/node/polyfills/01_require.js
- ext/node/polyfills/_util/os.ts
- ext/node/polyfills/child_process.ts
- ext/node/polyfills/http.ts
- ext/node/polyfills/internal/console/constructor.mjs
- ext/node/polyfills/internal/crypto/_randomFill.mjs
- ext/node/polyfills/internal/crypto/diffiehellman.ts
- ext/node/polyfills/internal/crypto/keygen.ts
- ext/node/polyfills/internal/crypto/random.ts
- ext/node/polyfills/internal_binding/constants.ts
- ext/node/polyfills/process.ts
- ext/node/polyfills/tty.js
- ext/node/polyfills/worker_threads.ts
- ext/web/06_streams.js
- ext/webgpu/00_init.js
- runtime/js/40_tty.js
- runtime/js/98_global_scope_shared.js
- runtime/js/98_global_scope_window.js
- runtime/js/98_global_scope_worker.js
Follow up to #22157.
This leaves us with 4 usages of `ensureFastOps()` in `deno` itself. There's also about 150 usages of `Deno.core.ops.<op_name>` left as well.
> refactor: Use virtul ops module

- cli/tests/unit/os_test.ts
- runtime/ops/runtime.rs
> fix(runtime): return number from `op_ppid` instead of bigint

- cli/factory.rs
- cli/tests/integration/run_tests.rs
Closes https://github.com/denoland/deno/issues/22176 (see detail there)
> fix(lockfile): only consider package.json beside lockfile in workspace property

- cli/lsp/language_server.rs
- cli/lsp/lsp_custom.rs
- cli/lsp/mod.rs
- cli/tests/integration/lsp_tests.rs
Fixes #22122. We shouldn't do this normalization because the params to the cache command come from the server's quick-fixes and are never denormalized to client URLs in the first place. It was causing a faulty memoization in the URL mapper.
BTW the fix is a one line change removing the `normalize_url()` call from https://github.com/denoland/deno/blob/v1.40.2/cli/lsp/language_server.rs#L3723. But I cleaned up the param types across the cache command helpers to make it clear that these are actual module specifiers, not client URLs. Also removed some old custom requests that were moved to commands.
> fix(lsp): don't normalize urls in cache command params

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- cli/tools/upgrade.rs
This doesn't actually trigger the arm64 build job nightly yet. I'll do that in a follow up.
> fix: canary for arm64 macos

- test_util/src/servers/mod.rs
Understandably accidentally caused by https://github.com/denoland/deno/pull/22187
> ci: fix failing upgrade_prompt test on main

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
We run these on the free machines now.
Also cleans up some of our os and arch conditional step handling by introducing a new `matrix.os` and `matrix.arch`.
> ci: run macos aarch64 builds on PRs and main

- cli/tests/unit/copy_file_test.ts
- ext/fs/std_fs.rs
Fixes https://github.com/denoland/deno/issues/22211
> fix(fs): copyFile NUL path on macOS

- Cargo.lock
- Cargo.toml
This upgrade includes all the necessary APIs for WASM imports
> chore: upgrade deno_core 0.257.0

- Cargo.lock
- cli/Cargo.toml
Tests are in https://github.com/denoland/deno_config/pull/37 (only ran a manual integration test as I think the tests in deno_config are sufficient).
Closes #22239
> fix(test/regression): handle CLI arg directory using `../` in path

- cli/tests/unit_node/child_process_test.ts
- ext/node/polyfills/child_process.ts
fixes https://github.com/denoland/deno/issues/22261
> fix(ext/node): fix timeout param validation in cp.execFile

- cli/tests/unit/kv_test.ts
- ext/kv/lib.rs
Check that in a `KvListSelector`, `start` and `end` are actually within the keyspace bounds defined by `prefix`, if both are present.
> fix(unstable): validate kv list selector

- cli/js/40_test.js
- cli/ops/testing.rs
- cli/tests/testdata/test/resource_sanitizer.out
- cli/tools/test/fmt.rs
- cli/tools/test/mod.rs
- runtime/lib.rs
- runtime/ops/web_worker.rs
Originally in #22125
Reverted in #22153 because of #22148
Fixed in deno_core https://github.com/denoland/deno_core/pull/538
Test plan: 
1. Check out: https://github.com/poolifier/poolifier-deno.git
2. `PATH=.../deno/target/release/:$PATH deno task test`
3. `ok | 13 passed (188 steps) | 0 failed (18s)`
> Reland refactor(cli): use new sanitizer for resources

- cli/bench/deno_common.js
These are not useful, as we bench them in `deno_core` already.
> chore: remove benchmarks for ops

- cli/bench/deno_common.js
- cli/js/40_test.js
- cli/tests/unit/ops_test.ts
- runtime/js/99_main.js
This commit brings down the number of ops exposed to user
code to 51.
> refactor: don't expose some ops

- cli/tests/integration/js_unit_tests.rs
- cli/tests/unit/symbol_test.ts
- ext/web/00_infra.js
- runtime/js/99_main.js
This commit adds support for "Symbol.metadata" which was 
omitted when adding support for the Decorators Proposal.
Closes https://github.com/denoland/deno/issues/22111
> fix: Support Symbol.metadata

- cli/auth_tokens.rs
Auth tokens may be specified for one of the following:
- `abc123@deno.land`: `deno.land`, `www.deno.land`, etc
- `abc123@deno.land:8080`: `deno.land:8080`, `www.deno.land:8080`, etc
- `abc123@1.1.1.1`: IP `1.1.1.1` only
- `abc123@1.1.1.1:8080`: IP `1.1.1.1`, port 8080 only
- `abc123@[ipv6]`: IPv6 `[ipv6]` only
- `abc123@[ipv6]:8080`: IPv6 `[ipv6]`, port 8080 only
Leading dots are ignored, so `.deno.dev` is equivalent to `deno.dev`.
> fix(cli): Add IP address support to DENO_AUTH_TOKEN

- .github/mtime_cache/action.js
- .github/mtime_cache/action.yml
- .github/workflows/bench_cron.yml
- .github/workflows/cargo_publish.yml
- .github/workflows/ci.generate.ts
- .github/workflows/start_release.yml
- .github/workflows/version_bump.yml
- .github/workflows/wpt_epoch.yml
Upgrades to the following GitHub Actions: `actions/checkout@v4`, `arduino/setup-protoc@v2`, `actions/cache@v4`, `actions/cache/save@v4` and `.github/mtime_cache`.
> chore: upgrade CI workflows to use Node 20

- ext/node/ops/os/cpus.rs
`/proc/cpuinfo` on ARM doesn't have the model name per CPU, so we leave those as "unknown".
> fix(ext/node): Ensure os.cpus() works on arm64 linux

- cli/diagnostics.rs
- cli/tests/integration/publish_tests.rs
Hacky quick fix. The real fix is a lot more work to do (move the `SourceTextInfo` into all the diagnostics in order to make this less error pone). I've already started on it, but it will require a lot of downstream create changes.
Closes #22288
> fix(publish): handle diagnostic outside graph

- cli/tests/integration/run_tests.rs
- cli/tests/unit/ops_test.ts
- runtime/js/99_main.js
This test is not needed because the op is not available to user code anymore.
This brings number of ops exposed to user code down to 15.
> chore: remove op_spawn_child test

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- test_ffi/tests/test.js
This implements officially blessed and tested deno binaries for ARM64. 
Thanks to @LukeChannings for his tireless work in maintaining the deno-arm64 [1] repo, without which this project would have been far more complicated. For those of you requiring support for older GLIBC versions, that repo may still be required for the near future.
Limitations: 
- This initial build is built on Ubuntu 22 using the stock GLIBC, which will limit the utility of these binaries in certain use-cases (eg: early versions of Ubuntu). We will attempt to support earlier versions of ARM64 GLIBC in a later revision.
- Like the stock Linux x64 build, this is not a static build and requires GLIBC. Running on Alpine will require installation of GLIBC.
Fixes #1846, #4862 
[1] …
> feat: ARM64 builds

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
Follow-up from #22298: Use a sysroot to build ARM64 so we work all the way back to Xenial.
We generate a sysroot ahead-of-time in the https://github.com/denoland/deno_sysroot_build project and use that to bootstrap a sysroot here.
> feat: use sysroot for ARM64

- cli/tsc/dts/lib.deno.ns.d.ts
I think this is a properly formatted PR. Not sure it is worth opening an issue for.
Note: I got "Page not found" for https://deno.com/manual/contributing
> docs(cli): add unit info for idleTimeout

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
We don't need to wget `libdl` because we can just copy the one from within the sysroot, saving two network accesses.
This allows amd64 to use the same build strategy as arm64.
> chore: remove wget from amd64 linux sysroot

- .github/workflows/bench_cron.yml
This has been broken for a while, but I think `setup-deno` is all that it needs.
> chore: fix nightly bench

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/tests/Cargo.toml
- cli/tests/integration/cert_tests.rs
- cli/tests/integration/inspector_tests.rs
- cli/tests/integration/js_unit_tests.rs
- cli/tests/integration/node_unit_tests.rs
- cli/tests/integration/run_tests.rs
- cli/tests/integration_tests.rs
- cli/tests/integration_tests_runner.rs
- cli/tests/lib.rs
- ext/tls/Cargo.toml
- ext/tls/lib.rs
- test_util/Cargo.toml
- test_util/src/lib.rs
- test_util/src/spawn.rs
This PR separates integration tests from CLI tests into a new project named `cli_tests`. This is a prerequisite for an integration test runner that can work with either the CLI binary in the current project, or one that is built ahead of time.
Rust does not have the concept of artifact dependencies yet (https://github.com/rust-lang/cargo/issues/9096). Because of this, the only way we can ensure a binary is built before running associated tests is by hanging tests off the crate with the binary itself.
Unfortunately this means that to run those tests, you _must_ build the binary and in the case of the deno executable that might be a 10 minute wait in release mode.
To allow for tests to run with and without the requirement that the binary is up-to-date, we split the integration tests into a …
> refactor: split integration tests from CLI (part 1)

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/file_fetcher.rs
- cli/tests/Cargo.toml
- cli/tests/integration/jsr_tests.rs
- cli/tests/testdata/jsr/version_not_found/main.out
- cli/tools/run/mod.rs
- cli/tools/test/mod.rs
Removes the `FileFetcher`'s internal cache because I don't believe it's necessary (we already cache this kind of stuff in places like deno_graph or config files in different places). Removing it fixes this bug because this functionality was already implemented in deno_graph and lowers memory usage of the CLI a little bit.
> fix: cache bust jsr deps on constraint failure

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- cli/napi/util.rs
- cli/tools/info.rs
- ext/cron/local.rs
- rust-toolchain.toml
Update to Rust 1.76
If this PR has any problem, please tell me.
> chore: update to Rust 1.76

- ext/node/polyfills/process.ts
Fixes https://github.com/denoland/deno/issues/20914
> fix(ext/node): export process.umask

- Cargo.lock
- ext/web/14_compression.js
- ext/web/compression.rs
- tests/unit/streams_test.ts
Based on #21074 and #20741 I was looking for further potential use cases of `TransformStream` `cancel()` method, so here go `CompressionStream` and `DecompressionStream`.
Fixes #14212
> fix(ext/web): Prevent (De-)CompressionStream resource leak on stream cancellation

- Cargo.lock
- Cargo.toml
- cli/build.rs
- cli/js/40_test.js
- cli/tools/test/fmt.rs
- runtime/snapshot.rs
- tests/testdata/test/ops_sanitizer_multiple_timeout_tests.out
- Adding `None` flag for warmup script.
- Modify opcall trace interface to match new Rust implementation
> chore: deno_core bump

- cli/args/mod.rs
- cli/cache/mod.rs
- cli/factory.rs
- cli/lsp/jsr_resolver.rs
- cli/tools/registry/mod.rs
- test_util/src/builders.rs
- test_util/src/lib.rs
- test_util/src/lsp.rs
`DENO_REGISTRY_URL` is from when `jsr:` was `deno:`.
> chore: rename DENO_REGISTRY_URL to JSR_URL

- cli/tsc/dts/lib.deno.ns.d.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
Fixes the stray, uncategorised symbols seen in the left pane menu on https://deno.land/api@v1.40.4.
> docs: add missing `@category` tags

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
deno fmt sometimes had stuff like:
```
NODE: Evaluation
```
...in the output, as pointed out by @kt3k
> fix(fmt): remove debug output when formatting dynamic imports

- cli/tools/test/fmt.rs
- ext/web/02_timers.js
- ext/web/lib.rs
- ext/web/timers.rs
Splitting the sleep and interval ops allows us to detect an interval timer. We also remove the use of the `op_async_void_deferred` call.
A future PR will be able to split the op sanitizer messages for timers and intervals.
> chore(ext/web): refactor timer ops before landing op sanitizer

- cli/js/40_test.js
- cli/ops/testing.rs
- cli/tools/test/fmt.rs
- cli/tools/test/mod.rs
- tests/testdata/test/sanitizer/ops_sanitizer_closed_inside_started_before.out
- tests/testdata/test/sanitizer/ops_sanitizer_multiple_timeout_tests.out
- tests/testdata/test/sanitizer/ops_sanitizer_multiple_timeout_tests_no_trace.out
- tests/testdata/test/sanitizer/ops_sanitizer_unstable.out
- tests/testdata/test/sanitizer/resource_sanitizer.out
- tests/unit/ops_test.ts
The format of the sanitizers will change a little bit:
- If multiple async ops leak and traces are on, we repeat the async op header once per stack trace.
- All leaks are aggregated under a "Leaks detected:" banner as the new timers are eventually going to be added, and these are neither ops nor resources.
- `1 async op` is now `An async op`
- If ops and resources leak, we show both (rather than op leaks masking resources)
Follow-on to https://github.com/denoland/deno/pull/22226
> refactor(cli): move op sanitizer to Rust

- cli/factory.rs
- cli/graph_util.rs
- cli/module_loader.rs
- cli/tools/registry/mod.rs
`ModuleLoader` was doing too much duplicate work.
> refactor: remove module graph setup from ModuleLoader

- Cargo.lock
- Cargo.toml
- cli/build.rs
- runtime/snapshot.rs
Migrations:
- Use the new SnapshotSerializer for TSC/compiler snapshots
> chore: bump deno_core 

- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/fetch/lib.rs
- tests/unit/fetch_test.ts
This change deprecates `Deno.CreateHttpClientOptions.{certChain,privateKey}` in favour of `Deno.CreateHttpClientOptions.{cert,key}`.
Closes #22278
> BREAKING: add `Deno.CreateHttpClientOptions.{cert,key}`

- ext/node/polyfills/internal/util/parse_args/parse_args.js
- tests/unit_node/util_test.ts
fix parseArgs() not working due to missing import of node:process
this commit fixes issue #22363
> fix: util.parseArgs() missing node:process import

- runtime/permissions/prompter.rs
- tests/integration/run_tests.rs
If we strip out unprintable chars, we don't see the full filename being requested by permission prompts. Instead, we highlight and escape them to make them visible.
> feat(core): highlight unprintable chars in permission prompts

- ext/net/01_net.js
As part of ongoing efforts to remove `rid` properties from the public API. Note: this property is undocumented.
> BREAKING(net): remove `Deno.DatagramConn.rid`

- cli/tsc/dts/lib.deno.unstable.d.ts
This will categorise the APIs correctly in https://deno.land/api.
> chore: add missing `@category` tags to runtime APIs

- tests/integration/lsp_tests.rs
- tests/util/server/src/lsp.rs
I think it was occassionally reading the diagnostics from the previous cache command rather than the config update.
Closes #22481
> chore: fix flaky lsp_vendor_dir

- .dprint.json
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/graph_util.rs
Updates dependent crates which includes an investigation fix by @irbull in Deno's LSP when linting code. Huge thanks to Ian for tracking down this issue.
Also includes Divy's deno_graph executor change, which reduces memory usage when loading jsr specifiers and makes them faster.
> perf: linter lsp memory leak fix and deno_graph executor

- .github/workflows/wpt_epoch.yml
Having `|| true` means that the job always executes with a success code, even when it really fails. Credit to Bartek for spotting this possible mistake.
Towards #22257
> chore: fail properly in web platform test

- ext/node/polyfills/process.ts
- tests/unit_node/process_test.ts
Closes https://github.com/denoland/deno/issues/22540
> fix(ext/node): init arch, pid, platform at startup

- cli/args/mod.rs
> fix(compile): add aarch64 linux to `CliOptions::npm_system_info`

- cli/args/mod.rs
I just noticed the message on this was cut off.
> chore: improve not implemented npm system info message

- cli/args/flags.rs
- cli/args/mod.rs
- cli/lsp/testing/execution.rs
- cli/tools/test/fmt.rs
- cli/tools/test/mod.rs
- tests/integration/test_tests.rs
- tests/testdata/test/sanitizer/ops_sanitizer_multiple_timeout_tests_no_trace.out
- tests/testdata/test/sanitizer/ops_sanitizer_unstable.out
As we add tracing to more types of runtime activity, `--trace-ops` is less useful of a name. `--trace-leaks` better reflects that this feature traces both ops and timers, and will eventually trace resource opening as well.
This keeps `--trace-ops` as an alias for `--trace-leaks`, but prints a warning to the console suggesting migration to `--trace-leaks`.
One test continues to use `--trace-ops` to test the deprecation warning.
> chore(cli): rename `--trace-ops` to `--trace-leaks`

- cli/args/flags.rs
- cli/tools/registry/mod.rs
- tests/integration/publish_tests.rs
This reverts commit c2c4e745a5db4f2e53aa70bf22b6c828fa1b4040.
Because it made multiple tests fail on `main`.
> Revert "fix(publish): error if there are uncommitted changes (#22613)"

- cli/lsp/testing/execution.rs
- cli/tools/test/channel.rs
- cli/tools/test/mod.rs
- cli/tools/test/reporters/compound.rs
- cli/tools/test/reporters/dot.rs
- cli/tools/test/reporters/junit.rs
- cli/tools/test/reporters/mod.rs
- cli/tools/test/reporters/pretty.rs
- cli/tools/test/reporters/tap.rs
- tests/integration/run_tests.rs
- tests/testdata/run/websocket_server_idletimeout.ts
- tests/testdata/test/load_unload.out
- tests/testdata/test/load_unload.ts
- tests/util/server/src/macros.rs
Some `deno_std` tests were failing to print output that was resolved after the last test finished. In addition, output printed before tests began would sometimes appear above the "running X tests ..." line, and sometimes below it depending on timing.
We now guarantee that all output is flushed before and after tests run, making the output consistent.
Pre-test and post-test output are captured in `------ pre-test output ------` and `------ post-test output ------` blocks to differentiate them from the regular output blocks.
Here's an example of a test (that is much noisier than normal, but an example of what the output will look like):
```
Check ./load_unload.ts
------- pre-test output -------
load
----- output end -----
running 1 test from ./load_unload.ts
test ...
------- output ------- …
```
> fix(cli): ensure that pre- and post-test output is flushed at the appropriate times

- cli/tools/registry/unfurl.rs
There was a bug here where it was warning about relative imports.
> fix(publish): reduce warnings about dynamic imports

- cli/lsp/diagnostics.rs
- tests/integration/lsp_tests.rs
- tests/testdata/npm/registry/@denotest/monaco-editor/1.0.0/main.js
- tests/testdata/npm/registry/@denotest/monaco-editor/1.0.0/main.types.d.ts
- tests/testdata/npm/registry/@denotest/monaco-editor/1.0.0/package.json
I'm working with monaco-editor in ts-ast-viewer.com and monaco-editor only provides a `"module": "./esm/vs/editor/editor.main.js",` entry in the package.json which also uses esm even though there's no `"type": "module"`, so it errors in Deno (https://www.npmjs.com/package/monaco-editor?activeTab=code). I believe `"module"` is not part of node resolution and in my case this is fine because the code is going to be bundled by a bundler and not run by Deno. Anyway, I was thinking that we could either just resolve the module entry or probably we shouldn't bother surfacing these issues as errors in the lsp and just leave it up to runtime? Not sure what the right solution is here, but erroring less in the lsp seems ok?
Before:
After:
Will write tests for this on Monday.
> fix(lsp): ignore code errors when type passes for non-`@deno-types` reolution

- cli/lsp/diagnostics.rs
- tests/integration/lsp_tests.rs
The diagnostic was incorrect when importing a `.js` file with a corresponding `.d.ts` file with sloppy imports because it would say to change the `.js` extension to `.d.ts`, which is incorrect. We might as well just hide this diagnostic.
> fix(lsp): do not warn about local file "redirects" from .js to .d.ts files

- tests/unit/timers_test.ts
This test was flaky after landing the new timer rewrite.
> chore(tests): update flaky timer test

- ext/node/polyfills/_process/process.ts
The issue seems to be already fixed since we upped to a newer 18.x version string in [another PR](https://github.com/denoland/deno/pull/20366). Updating to latest node LTS version can't hurt though.
Fixes https://github.com/denoland/deno/issues/21515
> fix: update node process version to latest node LTS

- cli/main.rs
- cli/mainrt.rs
- cli/standalone/binary.rs
This was showing up on the flamegraph.
```
14:54 $ hyperfine -S none --warmup 25 '/tmp/deno run /tmp/empty.js' 'target/release/deno run /tmp/empty.js'
Benchmark 1: /tmp/deno run /tmp/empty.js
Time (mean ± σ):      17.2 ms ±   4.7 ms    [User: 11.2 ms, System: 4.0 ms]
Range (min … max):    15.1 ms …  72.9 ms    172 runs
Warning: Statistical outliers were detected. Consider re-running this benchmark on a quiet system without any interferences from other programs. It might help to use the '--warmup' or '--prepare' options.
Benchmark 2: target/release/deno run /tmp/empty.js
Time (mean ± σ):      16.7 ms ±   1.1 ms    [User: 11.1 ms, System: 4.0 ms]
Range (min … max):    15.0 ms …  20.1 ms    189 runs
Summary
'target/release/deno run /tmp/empty.js' ran
1.03 ± 0.29 times faster than '/tmp/deno …
```
> perf(cli): faster standalone executable determination

- cli/js.rs
This test crashes often on windows.
> chore(cli): remove problematic snapshot test

- ext/node/polyfills/async_hooks.ts
- tests/unit_node/async_hooks_test.ts
Fixes https://github.com/denoland/deno/issues/18127 https://github.com/denoland/deno/issues/17248
SvelteKit works now!
```
$ deno run -A npm:create-svelte@latest my-app
create-svelte version 6.0.9
┌  Welcome to SvelteKit!
│
◇  Which Svelte app template?
│  SvelteKit demo app
│
◇  Add type checking with TypeScript?
│  Yes, using JavaScript with JSDoc comments
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!
✔ Type-checked JavaScript
https://www.typescriptlang.org/tsconfig#checkJs
Install community-maintained integrations:
https://github.com/svelte-add/svelte-add
Next steps:
1: cd my-app
2: npm install
3: git init && git add -A && git commit -m "Initial commit" (optional)
4: npm run dev -- --open
To close the dev server, hit Ctrl-C
Stuck? Visit …
```
> fix(node): implement ALS enterWith

- ext/node/polyfills/process.ts
- runtime/shared.rs
This commit adds support for source maps for `ext/` crates that are authored
in TypeScript. As a result any exceptions thrown from eg. `ext/node` will now
have correct stack traces.
This is only enabled in debug mode as it adds about 2Mb to the binary.
> fix: Provide source map for internal extension code

- cli/args/mod.rs
- cli/factory.rs
- cli/jsr.rs
- cli/lsp/jsr.rs
- cli/lsp/language_server.rs
- cli/lsp/npm.rs
- cli/npm/mod.rs
- cli/tools/registry/pm.rs
- tests/integration/pm_tests.rs
Also moves the cache for npm package metadata endpoints from `$DENO_DIR/registries` to the normal http cache like we use for jsr. It's slightly more convenient.
> feat(unstable/pm): support npm packages in 'deno add'

- Cargo.lock
- runtime/shared.rs
Due to bug in `deno_ast` the `source_map` setting is ignored and source map
is always emitted. This is fixed by updating `deno_ast`.
> fix: don't include source maps in release mode

- cli/tools/registry/unfurl.rs
We emitted `import "./` rather than `import "./$NAME"`. This is now fixed.
Also makes a cosmetic change so that `../` imports are now just imported as `../`, not `./../`.
> fix(tools/publish): correctly handle importing from self in unfurling

- ext/node/polyfills/worker_threads.ts
- runtime/js/11_workers.js
- tests/unit_node/worker_threads_test.ts
Implements ref/unref on worker to fix part of #22629
> feat(ext/node): ref/unref on workers

- cli/util/fs.rs
- cli/util/gitignore.rs
- tests/integration/publish_tests.rs
This allows explicitly overriding a .gitignore by specifying files and directories in "include". This does not apply to globs in an include as files matching those will still be gitignored. Additionally, individually gitignored files within an included directory will still be ignored (those can be opted out of being excluded by using a negated glob).
> fix(publish): include explicitly specified .gitignored files and directories

- ext/node/polyfills/02_init.js
- ext/node/polyfills/worker_threads.ts
- runtime/js/99_main.js
This commit changes how we figure out if we're running on main
thread in `node:worker_threads` module. Instead of relying on quirky
"magic variable" for a name to check if we're on main thread, we are
now explicitly passing this information during bootstrapping of the
runtime. As a side effect, `WorkerOptions.name` is more useful
and matches what Node.js does more closely (though not fully).
Towards https://github.com/denoland/deno/issues/22783
> refactor(ext/node): worker_threads.isMainThread setup

- cli/util/fs.rs
- cli/util/gitignore.rs
- tests/integration/publish_tests.rs
This is an unrealistic scenario, but it's still a good thing to fix and have a test for because it probably fixes some other underlying issues with how the gitignore was being resolved for the root directory.
From https://github.com/denoland/deno/pull/22720#issuecomment-1986134425
> fix(publish): ability to un-exclude when .gitignore ignores everything

- cli/util/progress_bar/mod.rs
Uses `Instant` instead of `SystemTime` for `cli/util/progress_bar/mod.rs`. Fixes #22558
> fix(cli): occasional panics on progress bar

- cli/schemas/config-file.v1.json
I was typing in my package name in a deno.json and got confused when it did this suggestion.
Probably best to remove the example and instead replace it with a pattern.
> fix(config): remove pkg name example and add pattern to schema

- ext/node/polyfills/internal/timers.mjs
- ext/node/polyfills/timers.ts
- tests/unit_node/timers_test.ts
Fixes #21660
Adds a basic `Immediate` class to mirror `NodeJS.Immediate`, and changes `setImmediate` and `clearImmediate` to return and accept (respectively) `Immediate` objects.
Note that for now {ref,unref,hasRef} are effectively stubs, as deno_core doesn't really natively support immediates (they're currently modeled as timers with delay of 0). Eventually we probably want to actually implement these properly.
> fix(ext/node): Add Immediate class to mirror NodeJS.Immediate

- ext/node/lib.rs
- ext/node/ops/http2.rs
- ext/node/ops/ipc.rs
- ext/node/ops/require.rs
- ext/node/resolution.rs
- tests/integration/npm_tests.rs
- tests/testdata/npm/cjs_pkg_imports/main.out
- tests/testdata/npm/cjs_pkg_imports/main.ts
- tests/testdata/npm/registry/@denotest/cjs-pkg-imports/1.0.0/index.js
- tests/testdata/npm/registry/@denotest/cjs-pkg-imports/1.0.0/number.js
- tests/testdata/npm/registry/@denotest/cjs-pkg-imports/1.0.0/package.json
- tests/testdata/npm/registry/@denotest/cjs-pkg-imports/1.0.0/sub/dist/crypto.js
- tests/testdata/npm/registry/@denotest/cjs-pkg-imports/1.0.0/sub/dist/crypto.mjs
We fixed pkg json imports for esm packages, but it looks like it was still broken in CJS.
Discovered in https://github.com/denoland/deno/issues/22811
Closes #21502
> fix(node): require of pkg json imports was broken

- cli/tools/registry/mod.rs
- cli/tools/registry/tar.rs
- cli/util/fs.rs
- tests/integration/publish_tests.rs
In https://github.com/denoland/deno/pull/22720/files#diff-d62d85de2a7ffb816cd2fdbaa47e588352f521c7c43d058b75649bbb255e0ae1R70 , I copy and pasted from another area of the code and didn't think about removing how it ignores the vendor folder by default.
> fix(publish): regression - publishing with vendor folder

- tests/unit_node/child_process_test.ts
This test always fails for me because `git -v` is not a flag.
> chore: fix child_process test

- Cargo.lock
- runtime/Cargo.toml
- runtime/ops/signal.rs
- tests/unit/signal_test.ts
- tests/unit_node/process_test.ts
Fixes #22724. Fixes #7164.
This does add a dependency on `signal-hook`, but it's just a higher level API on top of `signal-hook-registry` (which we and `tokio` already depend on) and doesn't add any transitive deps.
> fix(runtime): Restore default signal handler after user handlers are unregistered

- cli/tools/test/mod.rs
Fixes https://github.com/denoland/deno_std/issues/4473
> fix(cli): use Instant for test times

- runtime/permissions/mod.rs
> fix(runtime): negate partial condition for deny flags

- ext/node/ops/crypto/mod.rs
- tests/unit_node/crypto/crypto_key_test.ts
> feat(ext/node): add support for named curves in `crypto.generateKeyPair[Sync]()`

- cli/lsp/config.rs
Closes https://github.com/denoland/vscode_deno/issues/908. Unsupports extension versions < 3.32.0. This is already excluded by the [compat table](https://github.com/denoland/vscode_deno#compatibility), and note that the vscode extension is aggressively auto-updated.
> chore(lsp): remove enablePaths compat path

- cli/worker.rs
- runtime/permissions/lib.rs
Skips the access check if the specific unary permission is in an all-granted state. Generally prevents an allocation or two.
Hooks up a quiet "all" permission that is automatically inherited. This permission will be used in the future to indicate that the user wishes to accept all side-effects of the permissions they explicitly granted.
The "all" permission is an "ambient flag"-style permission that states whether "allow-all" was passed on the command-line.
> perf(permissions): Fast exit from checks when permission is in "fully-granted" state

- cli/graph_util.rs
- cli/module_loader.rs
In addition to the reasons for this outlined by @nayeemrmn in #14877 (which I think are reasons alone to not do this), this simplifies things a lot because then we don't need to implement the following:
1. Need to handle a JSR module dynamically importing a module within it.
2. Need to handle importing an export of a JSR dep then another export dynamically loaded later.
Additionally, people should be running `deno check dynamic_import.ts` instead of relying on this behaviour.
Landing this as a fix because it's blocking people in some scenarios and the current behaviour is broken (I didn't even have to change any tests to remove this, which is bad).
Closes #22852
Closes #14877
Closes #22580
> fix: stop type checking during runtime

- ext/node/ops/fs.rs
> fix(node): add nul byte to statfs path on windows

- cli/tools/test/mod.rs
- tests/specs/test/sanitizer_with_error/__test__.json
- tests/specs/test/sanitizer_with_error/main.js
- tests/specs/test/sanitizer_with_error/main.out
> fix(cli): show asserts before leaks

- ext/node/polyfills/crypto.ts
- ext/node/polyfills/internal/crypto/cipher.ts
- ext/node/polyfills/internal/crypto/util.ts
- tests/unit_node/crypto/crypto_cipher_test.ts
Stub implementation of getCipherInfo(). Good enough for most cases.
Note: We do not support all OpenSSL ciphers (likely never will)
Fixes https://github.com/denoland/deno/issues/21805
> fix(ext/node): crypto.getCipherInfo()

- cli/file_fetcher.rs
- tests/integration/run_tests.rs
Removes this unwrap:
```
> ../deno/target/debug/deno install -Afr jsr:@deno/deployctl
Loading: https://jsr.io/@deno/deployctl/meta.json ReloadAll
NOT MODIFIED: https://jsr.io/@deno/deployctl/meta.json
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.
Platform: windows x86_64
Version: 1.41.2
Args: ["V:\\deno\\target\\debug\\deno.exe", "install", "-Afr", "jsr:@deno/deployctl"]
thread 'main' panicked at cli\file_fetcher.rs:394:16:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` …
```
> fix: handle cache body file not existing when using etag

- cli/tools/coverage/mod.rs
- tests/specs/coverage/no_files_after_filter/__test__.jsonc
- tests/specs/coverage/no_files_after_filter/no_files_in_report.out
- tests/specs/coverage/no_files_after_filter/test.ts
- tests/specs/coverage/no_files_after_filter/test_coverage.out
Fixes #22941.
In that case, the only file with coverage was the `test.ts` file. The coverage reporter filters out test files before compiling its report, so after filtering we were left with an empty set of files. Later on it's assumed that there is at least 1 file to be reported on, and we panic. Instead of panicking, just issue an error after filtering.
> fix(coverage): Error if no files are included in the report

- ext/net/01_net.js
As having mismatched public and private class names may be confusing, without good reason, to those unfamiliar with the codebase.
> chore: rename internal `Datagram` class to `DatagramConn`

- cli/args/mod.rs
Just making sure we read this env var once per process.
> chore: make DENO_FUTURE a singleton

- Cargo.lock
The newer version of both crates provides fallback, non-SIMD implementation of their functions.
Reference:
- https://github.com/simd-lite/value-trait/commit/136603dcc6c6313b437cc42410aa4c85c709ea58
- https://github.com/simd-lite/simd-json/commit/f46dc2ab7ca5eab0d531cb7ad7ae11bcac8c2d06
Fixes #23014.
> chore: bump simd-json and value-trait

- ext/node/polyfills/_process/process.ts
Rust triple for riscv64 is riscv64gc. Although there are no official builds for architectures other than x86_64 and aarch64, Arch Linux RISC-V has managed to package Deno on riscv64: https://github.com/felixonmars/archriscv-packages/blob/master/deno/riscv64.patch
Ref: https://github.com/denoland/deno/issues/18702
> feat(ext/node): add riscv64 in process.arch

- Cargo.lock
- cli/Cargo.toml
* feat: implement exit status var (https://github.com/denoland/deno_task_shell/pull/110)
* feat: support input redirects (https://github.com/denoland/deno_task_shell/pull/106)
* feat: support output fd redirects for stdout and stderr (https://github.com/denoland/deno_task_shell/pull/111)
* feat: support parsing fd redirects (https://github.com/denoland/deno_task_shell/pull/107)
* fix: exit error code on arg parse failure (https://github.com/denoland/deno_task_shell/pull/112)
Closes #22989
> feat: deno_task_shell 0.15

- ext/ffi/dlfcn.rs
- ext/ffi/ir.rs
Removes unnecessary indirection - after creating `serde_v8::Value` it was immediately
unwrapped to `v8::Value` by the caller.
> refactor(ext/ffi): don't go through serde_v8::Value

- ext/ffi/00_ffi.js
- ext/ffi/dlfcn.rs
Follow up to https://github.com/denoland/deno/pull/23034 that removes
another usage of `serde_v8::Value`.
> refactor(ext/ffi): use v8::Value instead of serde_v8::Value

- ext/node/polyfills/02_init.js
- ext/node/polyfills/_process/streams.mjs
- ext/node/polyfills/process.ts
- runtime/js/99_main.js
WIP -- slightly different approach to similar changes in #22386
Note that this doesn't use a warmup script -- we are actually just doing more work at snapshot time.
> perf: warm expensive init code at snapshot time

- cli/js/40_bench.js
- cli/ops/bench.rs
- runtime/js/99_main.js
Internal refactor that changes how we use ops in `deno bench` subcommand.
This brings it in line to what we do in `deno test` subcommand.
> refactor(bench): align ops to testing ops

- cli/tsc/dts/lib.deno.window.d.ts
This has been incorrect since the function adopted its (more intuitive) current behavior in 9268df5f3. The same behavior change was backported to v1.39.3 in 87e954f54.
> docs(dts): Update edge case in `prompt()` docs

- ext/fetch/26_fetch.js
- ext/fetch/27_eventsource.js
This PR fixes all unhandled rejections and resource leaks found while adding a test for #22368.
> fix(ext/fetch): make `EventSource` more robust

- cli/js/40_bench.js
- cli/js/40_test.js
- tests/specs/bench/test_and_bench/__test__.jsonc
- tests/specs/bench/test_and_bench/main.js
- tests/specs/bench/test_and_bench/main.out
- tests/specs/test/test_and_bench/__test__.jsonc
- tests/specs/test/test_and_bench/main.js
- tests/specs/test/test_and_bench/main.out
Fixes regression introduced in https://github.com/denoland/deno/pull/22112 that
removed checks if `Deno.test` or `Deno.bench` are not used in respective subcommands.
Closes https://github.com/denoland/deno/issues/23041
> fix: don't panic in test and bench if ops not available

- tools/verify_pr_title.js
Allows to use `BREAKING` prefix in the PR title.
This change will allow us to land PRs that change behavior with `DENO_FUTURE=1` env var,
and prepare for Deno 2.0 release.
> ci: allow "FUTURE" PR title

- ext/fetch/27_eventsource.js
- tests/integration/js_unit_tests.rs
- tests/unit/event_source_test.ts
Depends on #22493. Closes #22367.
> fix(ext/fetch): do not truncate field value in `EventSource`

- tests/specs/future/runtime_api/__test__.jsonc
- tests/specs/future/runtime_api/main.js
- tests/specs/future/runtime_api/main.out
Add a test that asserts that certain symbols are no longer available
if running with `DENO_FUTURE=1` env var.
Currently only checks `window` global.
> test: add test for DENO_FUTURE=1 runtime API

- cli/tools/lint/mod.rs
- tests/specs/lint/jsr_tag/__test__.jsonc
- tests/specs/lint/jsr_tag/non_package.out
- tests/specs/lint/jsr_tag/non_package/mod.ts
- tests/specs/lint/jsr_tag/non_package/type.ts
- tests/specs/lint/jsr_tag/package.out
- tests/specs/lint/jsr_tag/package/deno.json
- tests/specs/lint/jsr_tag/package/mod.ts
- tests/specs/lint/jsr_tag/package/type.ts
- tests/specs/mod.rs
This automatically opts packages (deno.json's with a name, version, and exports field) into the "jsr" lint tag.
> feat(lint): automatically opt-in packages to `jsr` lint tag

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/tools/jupyter/server.rs
- tests/Cargo.toml
- tests/integration/jupyter_tests.rs
- tests/integration/mod.rs
Before this PR, we didn't have any integration tests set up for the `jupyter` subcommand.
This PR adds a basic jupyter client and helpers for writing integration tests for the jupyter kernel. A lot of the code here is boilerplate, mainly around the message format for jupyter.
This also adds a few basic integration tests, most notably for requesting execution of a snippet of code and getting the correct results.
> chore(tests): Introduce integration tests for `jupyter` subcommand

- cli/args/mod.rs
- cli/lsp/analysis.rs
- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tools/lint/mod.rs
- cli/tsc/99_main_compiler.js
- tests/integration/lsp_tests.rs
Factors out the `ConfigTree` structure from #21029, except it only has one node. Many call sites use scoped methods in advance e.g. `ConfigTree::fmt_options_for_specifier()`. But scopes are not implemented in the ts server, documents or resolvers i.e. they use `ConfigTree::root_xxx()` methods.
> refactor(lsp): unify config file data into ConfigTree

- cli/tools/bench/mod.rs
- cli/tools/bench/reporters.rs
- tests/specs/bench/filter_group_header/__test__.jsonc
- tests/specs/bench/filter_group_header/main.out
- tests/specs/bench/filter_group_header/main.ts
Fixes #23053.
Two small bugs here:
- the existing condition for printing out the group header was broken. it worked in the reproducer (in the issue above) without filtering only by accident, due to setting `self.has_ungrouped = true` once we see the warmup bench. Knowing that we sort benchmarks to put ungrouped benches first, there are only two cases: 1) we are starting the first group 2) we are ending the previous group and starting a new group
- when you passed `--filter` we were applying that filter to the warmup bench (which is not visible to users), so we suffered from jit bias if you were filtering (unless your filter was `<warmup>`)
TLDR;
Running
```bash
deno bench main.js --filter="G"
```
```js
// main.js
Deno.bench({
group: "G1",
name: "G1-A",
fn() {},
});
Deno.bench({
group: …
```
> fix(bench): Fix group header printing logic + don't filter out the warmup benchmark

- cli/tsc/dts/lib.esnext.collection.d.ts
- tests/unit/esnext_test.ts
> feat: type declarations for new Set methods

- cli/tsc/99_main_compiler.js
- tests/specs/check/unstable_suggestion/__test__.jsonc
- tests/specs/check/unstable_suggestion/main.out
- tests/specs/check/unstable_suggestion/main.ts
- tests/specs/check/unstable_suggestion/no_default_lib.out
- tests/specs/check/unstable_suggestion/no_default_lib.ts
> fix(check): do not suggest running with `--unstable`

- cli/lsp/language_server.rs
Otherwise this won't be refreshed when the user runs `Deno: Reload Import Registries Cache` in the command palette and they can't see newer package versions in completions. Testing this would require complex changes to the harness.
> fix(lsp): use registry cache for completion search

- Cargo.lock
- cli/Cargo.toml
- cli/tools/task.rs
Adds cross-platform shebang support (supports using shebangs in `deno task` on Windows)
https://github.com/denoland/deno_task_shell/pull/113
> feat(task): cross-platform shebang support

- Cargo.lock
- cli/Cargo.toml
- cli/args/mod.rs
- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/tsc.rs
- cli/tools/task.rs
- tests/specs/task/doc_comments_incorrect/__test__.jsonc
- tests/specs/task/doc_comments_incorrect/deno.jsonc
- tests/specs/task/doc_comments_incorrect/task.out
- tests/specs/task/doc_comments_no_args/__test__.jsonc
- tests/specs/task/doc_comments_no_args/deno.jsonc
- tests/specs/task/doc_comments_no_args/task.out
Closes #22786.
TLDR;
```jsonc
{
"tasks": {
// Some comment
//
// describing what the task does
"dev": "deno run -A --watch main.ts"
}
}
```
```bash
deno task
```
> feat(task): Task description in the form of comments

- ext/node/polyfills/tty.js
Fixes https://github.com/denoland/deno/issues/23043 https://github.com/denoland/deno/issues/23107
> fix(ext/node): use tty stdin from ext/io

- cli/tsc/99_main_compiler.js
Implements `host.toPath()` and `host.watchNodeModulesForPackageJsonChanges()`.
They're used here: https://github.com/microsoft/TypeScript/blob/v5.4.3/src/server/moduleSpecifierCache.ts#L30-L53.
There's an error for the latter API missing in the logs from #22391 (`toPath()` would apply to more recent versions). The call sites affected by this error (e.g. populating module specifier cache) seem related so it might fix it.
> fix(lsp): implement missing ts server host apis

- cli/lsp/documents.rs
Was investigating a separate stack overflow (that I've now found in the node resolution code) and came across this. We should avoid recursion (this is very old code).
> chore(lsp): remove recursion in recurse_dependents

- cli/lsp/config.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- tests/integration/lsp_tests.rs
> fix(lsp): don't apply preload limit to workspace walk

- cli/tools/check.rs
- cli/tools/registry/mod.rs
- cli/tsc/diagnostics.rs
- tests/specs/jsr/no_unused_params/__test__.jsonc
- tests/specs/jsr/no_unused_params/deno.json
- tests/specs/jsr/no_unused_params/main.out
- tests/specs/jsr/no_unused_params/main.ts
- tests/specs/jsr/no_unused_params/publish.out
Unused locals and parameters don't make sense to surface in remote modules. Additionally, fast check can cause these kind of diagnostics when publishing, so they should be ignored.
Closes #22959
> fix(check): ignore certain diagnostics in remote modules and when publishing

- cli/npm/byonm.rs
- cli/resolver.rs
- ext/node/ops/require.rs
- ext/node/package_json.rs
- ext/node/resolution.rs
Was doing a bit of debugging on why some stuff is not working in a personal project and ran a quick debug profile and saw it cloning the pkg json a lot. We should put this in an Rc.
> perf(node): put pkg json into an `Rc`

- cli/cache/cache_db.rs
- tests/specs/fmt/no_error_deno_dir_not_exists/__test__.jsonc
- tests/specs/fmt/no_error_deno_dir_not_exists/fmt.out
- tests/specs/fmt/no_error_deno_dir_not_exists/main.ts
- tests/specs/mod.rs
- tests/util/server/src/builders.rs
- tests/util/server/src/fs.rs
> fix: prevent cache db errors when deno_dir not exists

- ext/ffi/turbocall.rs
Fix a warning on linux aarch64
> chore(ext/ffi): sym is unused on aarch64 linux

- ext/ffi/turbocall.rs
- runtime/permissions/prompter.rs
- tests/integration/run_tests.rs
- tests/testdata/run/stdio_streams_are_locked_in_permission_prompt/worker.js
- tests/util/server/src/pty.rs
The permission prompt doesn't wait for quiescent input, so someone pasting a large text file into the console may end up losing the prompt. We enforce a minimum human delay and wait for a 100ms quiescent period before we write and accept prompt input to avoid this problem.
This does require adding a human delay in all prompt tests, but that's pretty straightforward. I rewrote the locked stdout/stderr test while I was in here.
> fix(cli): Enforce a human delay in prompt to fix paste problem

- cli/args/mod.rs
- cli/factory.rs
- cli/standalone/binary.rs
- tests/integration/npm_tests.rs
When `DENO_FUTURE=1` env var is present, then BYONM
("bring your own node_modules") is enabled by default.
That means that is there's a `package.json` present, users
are expected to explicitly install dependencies from that file.
Towards https://github.com/denoland/deno/issues/23151
> FUTURE: enable BYONM by default

- ext/node/polyfills/internal/errors.ts
- ext/node/polyfills/internal/util/parse_args/parse_args.js
- ext/node/polyfills/internal/util/parse_args/utils.js
- ext/node/polyfills/internal/validators.mjs
- tests/node_compat/test.ts
Fixes #23179.
Fixes #22454.
Enables passing `{tokens: true}` to `parseArgs` and setting default values for options.
With this PR, the observable framework works with deno out of the box (no unstable flags needed).
The existing code was basically copied straight from node, so this PR mostly just updates that (out of date) vendored code. Also fixes some issues with error exports (before this PR, in certain error cases we were attempting to construct error classes that weren't actually in scope).
The last change (in the second commit) adds a small hack so that we actually exercise the `test-parse-args.js` node_compat test, previously it was reported as passing though it should have failed. That test now passes.
> fix(ext/node): Support returning tokens and option defaults in `node:util.parseArgs`

- tests/unit/tls_test.ts
To avoid the risk of port collisions during tests, we listen on port 0 and use that for both ends of the connections (for any tests we run in this file).
> chore(tests): rewrite tls_test to avoid any hardcoded ports

- cli/lsp/language_server.rs
Fixes #23163.
The client-facing warning doesn't provide any value and is super annoying. We still emit a warning message on the server side for format errors, which should fulfill the same (less intrusive) purpose.
> fix(lsp): Remove client-facing format failure warning

- ext/node/polyfills/worker_threads.ts
- tests/testdata/workers/node_worker_message_port.mjs
- tests/testdata/workers/node_worker_message_port_1.cjs
MessagePort if directly assigned to workerData property instead of embedding it in an object then it is not patched to a NodeMessagePort. This PR fixes that issue.
> fix(ext/node): patch MessagePort if provided as workerData

- ext/web/13_message_port.js
- runtime/js/99_main.js
The patch is expected to let the script from #23199 not exit but to write a integration test we need to introduce messagePort.off as the test should exit (is it possible to have a timeout assertion in itest?). I didn't want do that in the same PR. I'm happy to introduce the same if we need a test.
Closes https://github.com/denoland/deno/issues/23199
> fix(ext/node): count MessagePort message listeners in hasMessageEventListener

- cli/tools/test/channel.rs
The tests would deadlock if we tried to write the sync marker into a pipe that was full because one test streamed just enough data to fill the pipe, so when we went to actually write the sync marker we blocked when nobody was reading.
We use a two-phase lock for sync markers now: one to indicate "ready to sync" and the second to indicate that the sync bytes have been received.
> fix(cli): fix deadlock in test writer when test pipe is full

- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/testing/server.rs
Cached ASTs are used for formatting, linting, code lenses and test collection. None of these are useful for remote modules.
Also fixes a bug where every module in the graph was being walked to collect tests.
> perf(lsp): don't keep remote module ast's in memory

- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/npm/managed/resolution.rs
- tests/integration/lsp_tests.rs
- tests/util/server/src/lsp.rs
This functionality was broken. The series of events was:
1. Load the npm resolution from the lockfile.
2. Discover only a subset of the specifiers in the documents.
3. Clear the npm snapshot.
4. Redo npm resolution with the new specifiers (~500ms).
What this now does:
1. Load the npm resolution from the lockfile.
2. Discover only a subset of the specifiers in the documents and take into account the specifiers from the lockfile.
3. Do not redo resolution (~1ms).
> perf(lsp): use lockfile to reduce npm pkg resolution time

- ext/net/lib.deno_net.d.ts
This currently fails to type-check in deno, but we know that listener is a `Listener<TcpConn>` here and we should be able to improve the typing:
```
let listener = Deno.listen({ port: 0 });
console.log(listener.addr.port);
->
error: TS2339 [ERROR]: Property 'port' does not exist on type 'Addr'.
Property 'port' does not exist on type 'UnixAddr'.
let listener = Deno.listen({ port: 0 }); console.log(listener.addr.port)
```
After:
```
Check file:///tmp/test.ts
```
> fix(ext/net): Improve ts types for network APIs

- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
Flattens `Document` and `DocumentInner` and moves the `Arc` outside. This makes the code a bit easier to navigate.
> refactor(lsp): remove DocumentInner

- cli/tsc/99_main_compiler.js
The TS language service requests source files via [getSourceFile](https://github.com/nathanwhit/deno/blob/7a25fd5ef0a82c2aac76594ccd467e9210e92b80/cli/tsc/99_main_compiler.js#L560). In that function, we [unconditionally add](https://github.com/nathanwhit/deno/blob/7a25fd5ef0a82c2aac76594ccd467e9210e92b80/cli/tsc/99_main_compiler.js#L613-L614) the source file to our sourceFileCache. The issue is that we only remove things from that cache if the source file [becomes out of date](https://github.com/nathanwhit/deno/blob/7a25fd5ef0a82c2aac76594ccd467e9210e92b80/cli/tsc/99_main_compiler.js#L777-L783). For files that don't get changed, we keep them in the cache indefinitely. So sometimes we keep SourceFile objects from being GC'ed because they're retained in our cache, even though TS doesn't …
> perf(lsp): Don't retain `SourceFileObject`s in `sourceFileCache` longer than necessary

- ext/fs/30_fs.js
- runtime/js/99_main.js
- tests/specs/future/runtime_api/main.js
- tests/specs/future/runtime_api/main.out
I'm unsure whether we're planning to make the `Deno.FsFile` constructor illegal or remove `FsFile` from the `Deno.*` namspace in Deno 2. Either way, this PR works towards the former. I'll create a superceding PR if the latter is planned instead.
Towards #23089
> FUTURE(ext/fs): make `Deno.FsFile` constructor illegal

- ext/node/polyfills/_stream.mjs
- tests/unit_node/fs_test.ts
This PR follows this fix (https://github.com/nodejs/node/pull/52005) in Node.js.
Stream's construct callback happens one tick earlier by this change, and it prevents the reordering of the first few chunks in `node:stream.Writable`
closes #20284
> fix(ext/node): out-of-order writes of fs.createWriteStream

- cli/tsc/dts/lib.deno.ns.d.ts
Changes `discreet` in the documentation for `discrete`
"Discreet" means careful to avoid being noticed, "discrete" means separate parts, and is what the documentation refers to.
> docs: Fix typo "discreet" to "discrete"

- cli/lsp/documents.rs
Previously we locked the entire `FileSystemDocuments` even for lookups, causing contention. This was particularly bad because some of the hot ops (namely `op_resolve`) can end up hitting that lock under contention.
This PR replaces the mutex with synchronization internal to `FileSystemDocuments` (an `AtomicBool` for the dirty flag, and then a `DashMap` for the actual documents).
I need to think a bit more about whether or not this introduces any problematic race conditions.
> perf(lsp): More granular locking of `FileSystemDocuments`

- cli/tsc/dts/lib.deno.ns.d.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/fetch/22_http_client.js
- ext/net/02_tls.js
- ext/net/lib.deno_net.d.ts
- tests/unit/tls_test.ts
Removes the certificate options from all the interfaces and replaces them with a new `TlsCertifiedKeyOptions`. This allows us to centralize the documentation for TLS key management for both client and server, and will allow us to add key object support in the future.
Also adds an option `keyFormat` field to the cert/key that must be omitted or set to `pem`. This will allow us to load other format keys in the future `der`, `pfx`, etc.
In a future PR, we will add a way to load a certified key object, and we will add another option to `TlsCertifiedKeyOptions` like so:
```ts
export interface TlsCertifiedKeyOptions =
| TlsCertifiedKeyPem
| TlsCertifiedKeyFromFile
| TlsCertifiedKeyConnectTls
| { key: Deno.CertifiedKey }
```
> refactor(ext/net): extract TLS key and certificate from interfaces

- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- tests/integration/lsp_tests.rs
Currently we evict a lot of the caches on the JS side of things on every request, namely script versions, script file names, and compiler settings (as of #23283, it's not quite every request but it's still unnecessarily often).
This PR reports changes to the JS side, so that it can evict exactly the caches that it needs too. We might want to do some batching in the future so as not to do 1 request per change.
> perf(lsp): Only evict caches on JS side when things actually change

- cli/tsc/99_main_compiler.js
Fixes redundant calls to `op_resolve()` for unchanged modules.
> perf(lsp): replace document registry source cache on update

- cli/lsp/tsc.rs
Fixes the regression described in https://github.com/denoland/deno/pull/23293#issuecomment-2049819724. This affected jupyter notebooks, as the LSP was passing in already denormalized specifiers, while the jupyter kernel was not. We need to denormalize the specifiers to evict the proper keys from our caches.
> fix(lsp): Denormalize specifiers before calling `$projectChanged`

- cli/lsp/config.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/mod.rs
Previously when you edited any import statement, the ts server would re-resolve `jsxImportSource` from all modules in the graph. The resolution would return null because it's not a deno_graph-discovered dependency of those modules. Resolutions that return null are frequently retried. Instead make it resolve to a stub module `internal://missing_dependency.d.ts`.
Also resolve `jsxImportSource` up front using the `deno.json` as the referrer.
> perf(lsp): use a stub module in tsc for failed resolutions

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- Bump `curve25519-dalek` to fix unstable features
- Bump to llvm-17 to match latest minimum
- cargo update to fix all the things that break w/llvm-17
> chore: fix nightly builds

- Cargo.lock
- tests/Cargo.toml
- tests/specs/mod.rs
Extracted out this code to https://github.com/denoland/file_test_runner and added parallelism. This makes these tests run 6 seconds faster on my machine and allows re-using this code in other crates like deno_graph, deno_doc, etc (ex. https://github.com/denoland/deno_graph/pull/437).
> chore(test): use file_test_runner for spec tests

- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
Previously we were deserializing it twice - once to `serde_json::Value`, and then again from the `serde_json::Value` to a concrete type
> perf(lsp): Only deserialize response from `op_respond` once

- ext/node/polyfills/tty.js
This is the same issue as https://github.com/denoland/deno/pull/23044 but in `WriteStream`.
Adding a docusarus test in npm_smoke_tests repo.
> fix(ext/node): use ext/io stdio in WriteStream

- cli/lsp/documents.rs
- cli/lsp/tsc.rs
Instead of using stub modules for null resolutions (#23313), make sure `op_resolve()` doesn't give null resolutions for non-erroneous cases.
- Fallback to using `CliGraphResolver::resolve()` for non-imported dependencies. This affects `jsxImportSource` which tsc will try to resolve from every module.
- Don't return a null resolution for uncached dependencies. These should load a null source instead.
- Don't return a null resolution for `node:` specifiers. Not sure why we were doing this but as far as I can see everything still works.
Fixes #23339.
> refactor(lsp): use fallback resolution in op_resolve()

- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
I'm running into a node resolution bug in the lsp only and while tracking it down I noticed this one.
Fixed by moving the project version out of `Documents`.
> fix(lsp): ensure project version is incremented when config changes

- cli/tools/bench/mod.rs
- cli/tools/test/mod.rs
- cli/worker.rs
- runtime/js/99_main.js
- runtime/worker.rs
This commit moves logic of dispatching lifecycle events (
"load", "beforeunload", "unload") to be triggered from Rust.
Before that we were executing scripts from Rust, but now we
are storing references to functions from "99_main.js" and calling
them directly.
Prerequisite for https://github.com/denoland/deno/issues/23342
> refactor: move lifecycle events dispatch to Rust

- cli/tools/test/mod.rs
- ext/io/winpipe.rs
Due to a terminating NUL that was placed in a `r#` string, we were not actually NUL-terminating pipe names on Windows. While this has no security implications due to the random nature of the prefix, it would occasionally cause random failures when the trailing garbage would make the pipe name invalid.
> fix(ext/io): Fix NUL termination error in windows named pipes

- Cargo.lock
- cli/lsp/documents.rs
- cli/lsp/tsc.rs
- cli/resolver.rs
- cli/tsc/99_main_compiler.js
- tests/Cargo.toml
- tests/integration/lsp_tests.rs
- tests/specs/mod.rs
- tests/specs/npm/cjs_internal_types_default_export/__test__.jsonc
- tests/specs/npm/cjs_internal_types_default_export/main.out
- tests/specs/npm/cjs_internal_types_default_export/main.ts
- tests/specs/npm/cjs_internal_types_default_export/package.json
- tests/testdata/npm/registry/@denotest/cjs-internal-types-default-export/1.0.0/add.d.ts
- tests/testdata/npm/registry/@denotest/cjs-internal-types-default-export/1.0.0/index.d.ts
- tests/testdata/npm/registry/@denotest/cjs-internal-types-default-export/1.0.0/index.js
- tests/testdata/npm/registry/@denotest/cjs-internal-types-default-export/1.0.0/package.json
Our cjs tracking was a bit broken. It was marking stuff as esm that was actually cjs leading to type checking errors.
> fix(lsp): improved cjs tracking

- ext/node/polyfills/worker_threads.ts
- ext/web/13_message_port.js
- ext/web/message_port.rs
- tests/unit_node/worker_threads_test.ts
Closes https://github.com/denoland/deno/issues/23362
Previously we were panicking if there was a pending read on a
port and `receiveMessageOnPort` was called. This is now fixed
by cancelling the pending read, trying to read a message and
resuming reading in a loop.
> fix(ext/node): panic on 'worker_threads.receiveMessageOnPort'

- cli/tools/jupyter/mod.rs
- cli/tools/repl/mod.rs
- cli/tools/repl/session.rs
- cli/tools/test/channel.rs
- cli/tools/test/mod.rs
`TestEventSender` should not be Clone so we don't end up with multiple copies of the same writer FD. This is probably not the cause of the test channel lockups, but it's a lot easier to reason about.
> fix(cli): TestEventSender should be !Clone

- .dprint.json
- .gitmodules
- cli/bench/lsp.rs
- cli/bench/main.rs
- cli/bench/testdata/deco_apps_requests.json
- tests/util/server/src/lsp.rs
This PR adds a benchmark intended to measure how the LSP handles larger repos, as well as its performance on a more realistic workload.
The repo being benchmarked is [deco-cx/apps](https://github.com/deco-cx/apps) which has been vendored along with its dependencies. It's included as a git submodule as its fairly large. The LSP requests used in the benchmark are the actual requests sent by VSCode as I opened, modified, and navigated around a file (to simulate an actual user interaction).
The main motivation is to have a more realistic benchmark that measures how we do with a large number of files and dependencies. The improvements made from 1.42 to 1.42.3 mostly improved performance with larger repos, so none of our existing benchmarks showed an improvement. 
Here are the results for the …
> chore(lsp): Add benchmark for performance on a large real-world repo

- cli/factory.rs
- cli/graph_util.rs
- cli/tsc/mod.rs
- tests/specs/check/css_import/__test__.jsonc
- tests/specs/check/css_import/exists.out
- tests/specs/check/css_import/exists.ts
- tests/specs/check/css_import/exists_and_try_uses.out
- tests/specs/check/css_import/exists_and_try_uses.ts
- tests/specs/check/css_import/exists_dynamic_import.ts
- tests/specs/check/css_import/exists_run_with_check.out
- tests/specs/check/css_import/not_exists.out
- tests/specs/check/css_import/not_exists.ts
This allows people to use imports like:
```ts
import "./app.css";
```
...with `deno check` in systems where there's a bundle step (ex. Vite). This will still error when using it with `deno run` or if the referenced file does not exist.
See test cases for behaviour.
> feat(check): allow using side effect imports with unknown module kinds (ex. css modules)

- Cargo.lock
- cli/Cargo.toml
- cli/tools/test/channel.rs
- tests/specs/test/worker_large_output/__test__.jsonc
- tests/specs/test/worker_large_output/main.js
- tests/specs/test/worker_large_output/main.out
If a worker tried to flush large amounts of data right as the test was ending, it could cause the flush sync marker to get lost.
> fix(cli): Identify and fix a test deadlock

- .github/workflows/wpt_epoch.yml
- tests/wpt/wpt.ts
I went with `--exit-zero`. Happy to change to `--no-exit` if feelings are strong.
Supercedes #23417
> fix: allow WPT to successfully exit using `--exit-zero`

- cli/bench/lsp.rs
So it will actually show up on the [deno benchmarks site](http://deno.com/benchmarks)
> chore(lsp): Include new benchmark in the collected benchmark data

- cli/tsc/dts/lib.deno.ns.d.ts
- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/fetch/22_http_client.js
- ext/net/02_tls.js
- ext/net/lib.deno_net.d.ts
- ext/net/ops_tls.rs
- tests/unit/tls_test.ts
> feat(ext/net): extract TLS key and certificate from interfaces

- cli/tools/registry/pm.rs
- cli/tools/vendor/mod.rs
- tests/integration/pm_tests.rs
- tests/integration/vendor_tests.rs
Avoid "Failed updating config file due to no object" errors for the below commands when existing `deno.json` is empty. Added a test case for each.
- `deno add` (c0f410d50652acf9316fdca52e5cc919770ff419)
- fix #23215
- `deno vendor` (46fdc7f9f46788c0cb384f8dccd50d30b90ecddf)
- not listed in the issue, but errors occur in the same way
> fix(cli): avoid `deno add` and `deno vendor` errors when deno.json is empty

- tests/node_compat/test_runner.rs
It's not clear to me how these tests worked correctly on CI,
but they were failing hard locally because of two problems:
- missing env var that tests URL for fake npm registry
- trying to run a directory that contains native Node.js tests that
require a special harness
> test: fix node_compat_test

- runtime/js/99_main.js
- tests/specs/future/runtime_api/main.js
- tests/specs/future/runtime_api/main.out
> FUTURE: remove `Deno.customInspect`

- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/mod.rs
Going through serde_v8 is slow, so just pass the args separately. `op_resolve` is especially hot, so any speedups are good.
> perf(lsp): Avoid passing struct into op_resolve

- cli/tsc/dts/lib.deno.ns.d.ts
- ext/http/00_serve.js
- tests/unit/serve_test.ts
Adds an `addr` field to `HttpServer` to simplify the pattern `Deno.serve({ onListen({ port } => listenPort = port })`. This becomes: `const server = Deno.serve({}); port = server.addr.port`.
Changes:
- Refactors `serve` overloads to split TLS out (in preparation for landing a place for the TLS SNI information)
- Adds an `addr` field to `HttpServer` that matches the `addr` field of the corresponding `Deno.Listener`s.
> feat(ext/http): Add `addr` to HttpServer

- cli/node.rs
- cli/resolver.rs
- cli/standalone/file_system.rs
- cli/util/gitignore.rs
- ext/fs/in_memory_fs.rs
- ext/fs/interface.rs
- ext/fs/lib.rs
- ext/fs/ops.rs
- ext/fs/std_fs.rs
- ext/io/fs.rs
- ext/node/ops/require.rs
- ext/node/package_json.rs
- runtime/permissions.rs
- runtime/permissions/lib.rs
- runtime/snapshot.rs
- tests/integration/run_tests.rs
- tests/unit/read_dir_test.ts
Embedders may have special requirements around file opening, so we add a new `check_open` permission check that is called as part of the file open process.
> feat(runtime): Allow embedders to perform additional access checks on file open

- cli/lsp/config.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/testing/collectors.rs
- cli/lsp/testing/definitions.rs
- cli/lsp/testing/execution.rs
- cli/lsp/testing/mod.rs
- cli/lsp/testing/server.rs
Most of this is changing the way parsed sources are analyzed for tests. Before we stored ASTs for all `file:` documents so they could be used to do this in the test server. But it's better if we do that immediately after the source is parsed so we don't need to store the AST.
Walking ASTs to collect tests in the document change handler would block the language server and cause a perf regression. Instead we dispatch a task there to collect them in a blocking thread, store the result in `Document::maybe_test_module_fut` and let that be accessed asynchronously.
> perf(lsp): only store parsed sources for open documents

- ext/http/01_http.js
- ext/http/02_websocket.ts
- ext/http/lib.rs
- runtime/js/90_deno_ns.js
Landing part of https://github.com/denoland/deno/pull/21903
This will allow us to more easily refactor `serveHttp` to live on top of `serve` by splitting the websocket code out. There's probably a lot more we could do here but this helps.
> refactor(ext/http): extract 02_websocket.ts from 01_http.js

- ext/node/polyfills/worker_threads.ts
- tests/unit_node/worker_threads_test.ts
Fixes https://github.com/denoland/deno/issues/23455
> fix(ext/node): Support `env` option in worker_thread

- ext/fs/std_fs.rs
- tests/unit_node/_fs/_fs_copy_test.ts
Fixes https://github.com/denoland/deno/issues/20604
> fix(ext/node): `cp` into non-existent parent directory

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
TS uses this argument to avoid computing some refactors if the code action wasn't invoked by the user
> perf(lsp): Pass code action trigger kind to TSC

- ext/cron/01_cron.ts
- ext/node/ops/os/cpus.rs
- tests/testdata/fmt/with_config/subdir/c.md
> fix: Fix some typos in comments

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- tests/integration/lsp_tests.rs
The actual handling of `$projectChanged` is quick, but JS requests are not. The cleared caches only get repopulated on the next actual request, so just batch the change notification in with the next actual request.
No significant difference in benchmarks on my machine, but this speeds up `did_change` handling and reduces our total number of JS requests (in addition to coalescing multiple JS change notifs into one).
> perf(lsp): Batch "$projectChanged" notification in with the next JS request

- cli/args/mod.rs
- cli/schemas/config-file.v1.json
- cli/tsc/99_main_compiler.js
- tests/integration/run_tests.rs
- tests/testdata/jsx/deno-jsx-precompile-skip.jsonc
- tests/testdata/run/jsx_precompile/skip.out
- tests/testdata/run/jsx_precompile/skip.tsx
- tools/lint.js
This PR wires up a new `jsxPrecompileSkipElements` option in `compilerOptions` that can be used to exempt a list of elements from being precompiled with the `precompile` JSX transform.
> feat: add jsx precompile skip element option

- cli/lsp/tsc.rs
Doesn't have a noticeable perf impact from my benchmarking, but theoretically should be better.
> perf(lsp): Call `serverRequest` via V8 instead of via `executeScript`

- cli/args/mod.rs
- cli/factory.rs
- cli/tools/bundle.rs
- cli/tools/compile.rs
- cli/tools/repl/session.rs
- tests/specs/run/invalid_emit_options/__test__.jsonc
- tests/specs/run/invalid_emit_options/deno.json
- tests/specs/run/invalid_emit_options/main.out
> fix(cli): Don't panic on invalid emit options

- cli/main.rs
- ext/node/polyfills/internal/util/types.ts
- ext/web/02_structured_clone.js
- ext/web/06_streams.js
- ext/webidl/00_webidl.js
- tests/wpt/runner/expectation.json
Ref #23490, #23277
* remove `--js-float16array` flag (This flag has already added to deno_core)
* add some `Float16Array` support
> fix: Float16Array support

- tests/integration/npm_tests.rs
- tests/util/server/src/servers/mod.rs
This commit adds a "private npm registry" to the test server. This registry
requires to send an appropriate Authorization header.
Towards https://github.com/denoland/deno/issues/16105
> test: add private npm registry

- ext/node/polyfills/worker_threads.ts
- tests/unit_node/worker_threads_test.ts
Most common argument to `env` option for `worker_threads.Worker` will be `process.env`.
In Deno `process.env` is a `Proxy` which can't be cloned using structured clone algorithm.
So to be safe, I'm creating a copy of actual object before it's sent to the worker thread.
Ref #23522
> fix(ext/node): worker_threads copies env object

- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/http/00_serve.ts
- ext/http/http_next.rs
- ext/http/lib.rs
- ext/http/response_body.rs
- ext/http/service.rs
- ext/node/polyfills/http.ts
- ext/node/polyfills/http2.ts
- runtime/js/90_deno_ns.js
- tests/unit/serve_test.ts
- tools/core_import_map.json
When the response has been successfully send, we abort the `Request.signal` property to indicate that all resources associated with this transaction may be torn down.
> feat(ext/http): Implement request.signal for Deno.serve

- cli/tsc/99_main_compiler.js
Reverts https://github.com/denoland/deno/pull/23515 but adds a comment for why this is ignored
> chore(lsp): revert respect shouldCreateNewSourceFile

- cli/args/flags.rs
- cli/args/mod.rs
- cli/factory.rs
- cli/main.rs
- cli/standalone/mod.rs
- cli/tools/bench/mod.rs
- cli/tools/jupyter/mod.rs
- cli/tools/repl/mod.rs
- cli/tools/run/mod.rs
- cli/tools/test/mod.rs
- cli/worker.rs
- ext/http/00_serve.ts
- runtime/js/99_main.js
- runtime/lib.rs
- runtime/worker_bootstrap.rs
- tests/specs/serve/bad/__test__.jsonc
- tests/specs/serve/bad/main.out
- tests/specs/serve/bad/main.ts
- tests/specs/serve/basic/__test__.jsonc
- tests/specs/serve/basic/main.out
- tests/specs/serve/basic/main.ts
By default, `deno serve` will assign port 8000 (like `Deno.serve`). Users may choose a different port using `--port`.
`deno serve /tmp/file.ts`
`server.ts`:
```ts
export default {
fetch(req) {
return new Response("hello world!\n");
},
};
```
> feat: Add `deno serve` subcommand

- cli/lsp/tsc.rs
Before this PR, there would just be an uninformative "Error occurred" message, after this PR you'll get a stack trace in the LSP output window like this:
```text
Error during TS request "$getSupportedCodeFixes":
Error: i threw an exception
at serverRequest (ext:deno_tsc/99_main_compiler.js:1089:11)
```
> chore(lsp): Print out stack trace if exception occurs in TS request

- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/webgpu/byow.rs
This PR works fine with a [simply modified `deno_sdl2`](https://github.com/chirsz-ever/deno_sdl2/tree/chirsz/support-wayland).
@littledivy How do you think about this?
> feat(ext/webgpu): support create UnsafeWindowSurface on Wayland

- ext/http/00_serve.ts
Fixes a perf regression introduced in https://github.com/denoland/deno/commit/eed2598e6cf1db643b4edd07b5eff94c59eb9408 ([flamegraph](https://profiler.firefox.com/public/83whz7mrfkshk5q6hd6hjmrmw8tgmw67s96m4p0/flame-graph/?globalTrackOrder=0&hiddenLocalTracksByPid=12691-0we&symbolServer=http%3A%2F%2F127.0.0.1%3A3000%2F316cvciry38ippl9i74fmcxrd5q9asfrr28xp02&thread=0&v=10))
this patch:
```
Summary:
Success rate: 100.00%
Total:        10.0007 secs
Slowest:      0.0145 secs
Fastest:      0.0001 secs
Average:      0.0006 secs
Requests/sec: 80341.4816
Total data:   9.19 MiB
Size/request: 12
Size/sec:     941.44 KiB
```
main:
```
Summary:
Success rate: 100.00%
Total:        10.0007 secs
Slowest:      0.0068 secs
Fastest:      0.0002 secs
Average:      0.0009 secs
Requests/sec: 56560.0551
Total …
```
> perf(ext/http): cache abort signal error

- ext/fetch/23_request.js
- ext/fetch/internal.d.ts
- ext/http/00_serve.ts
- ext/http/01_http.js
- ext/web/03_abort_signal.js
Max rps without a signal is unchanged, however we can drastically reduce memory usage by not creating the signal until needed, and we can optimize the rps in the case where the signal is created.
With a quick memory benchmark, it looks like this helps pretty drastically with # of GCs when benchmarking w/wrk:
- 1.42.4: 1763
- canary: 1093
- this patch: 874
This branch:
```
Running 10s test @ http://localhost:8080/
Latency    87.33us  439.95us  20.68ms   99.67%
Req/Sec    66.70k     6.39k   74.11k    83.66%
1340255 requests in 10.10s, 191.73MB read
Requests/sec: 132696.90
Transfer/sec:     18.98MB
cpu: Apple M2 Pro
runtime: deno 1.43.0 (aarch64-apple-darwin)
file:///Users/matt/Documents/scripts/bench_request.js …
```
> perf(ext/http): recover memory for serve and optimize AbortController

- cli/lsp/completions.rs
- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
It has the same fields as `Config`, `Config::snapshot()` was just cloning.
> chore(lsp): remove ConfigSnapshot

- ext/node/polyfills/02_init.js
- ext/node/polyfills/internal/util/debuglog.ts
- ext/node/polyfills/process.ts
- tests/specs/node/node_debug/__test__.jsonc
- tests/specs/node/node_debug/hello.txt
- tests/specs/node/node_debug/main.mjs
- tests/specs/node/node_debug/main.out
Previously we didn't support NODE_DEBUG environment variable due to issues in snapshot process. The issue is solved by initializing the logger during bootstrap which is not included in the snapshot allowing the build to work.
> fix(ext/node): support NODE_DEBUG env

- ext/node/polyfills/internal/streams/destroy.mjs
These lines don't seem used. Instead the vendored version of them (in `ext/node/polyfills/_stream.mjs` https://github.com/denoland/deno/blob/021a0dc9b1063bff67dc295c61d9f4bf787c18fb/ext/node/polyfills/_stream.mjs#L1625 ) seem being used.
This was very confusing while I was working on https://github.com/denoland/deno/pull/23244
> refactor: remove dead code in node stream polyfill

- Cargo.lock
- cli/Cargo.toml
- tests/integration/lsp_tests.rs
This was forgotten to be renabled a while back when we made it optional
> fix: reenable syntax highlighting for doc html generator

- Cargo.lock
- cli/Cargo.toml
- cli/args/mod.rs
- tests/specs/run/import_map_parent_dir/__test__.jsonc
- tests/specs/run/import_map_parent_dir/import_map.json
- tests/specs/run/import_map_parent_dir/info.out
- tests/specs/run/import_map_parent_dir/run.out
- tests/specs/run/import_map_parent_dir/shared/models.ts
- tests/specs/run/import_map_parent_dir/sub/deno.json
- tests/specs/run/import_map_parent_dir/sub/main.ts
* https://github.com/denoland/deno_config/pull/51
Closes https://github.com/denoland/deno/issues/21440
> fix: handle specifying an import map in an ancestor dir of deno.json

- ext/node/polyfills/worker_threads.ts
- tests/unit_node/worker_threads_test.ts
Closes https://github.com/denoland/deno/issues/23561
> fix(ext/node): support multiple message listeners on MessagePort

- Cargo.lock
- cli/Cargo.toml
* https://github.com/denoland/deno_graph/pull/463
Closes #23613
> fix(publish): handle variable declarations with a declare keyword

- cli/lsp/config.rs
- tests/integration/lsp_tests.rs
This was initially a red herring solution added in #23313, the proper fix was #23329. I kept it because it seemed nice but actually it's superfluous -- if tsc wants to resolve the `jsxImportSource` specifier with each module as a referrer then we should align. Plus it was inconsistent with `deno check`.
> chore(lsp): revert import map pre-resolution for jsxImportSource

- cli/ops/jupyter.rs
- cli/tools/jupyter/jupyter_msg.rs
- cli/tools/jupyter/mod.rs
- cli/tools/jupyter/server.rs
Moves the communication methods out of the data structs and onto the `Connection` struct.
Part of https://github.com/denoland/deno/issues/23617
> refactor(jupyter): move communication methods out of data structs

- ext/node/polyfills/01_require.js
- tests/specs/npm/require_resolve_bad_paths_global_cache/__test__.jsonc
- tests/specs/npm/require_resolve_bad_paths_global_cache/main.out
- tests/specs/npm/require_resolve_bad_paths_global_cache/main.ts
- tests/testdata/npm/registry/@denotest/require-resolve/1.0.0/index.cjs
- tests/testdata/npm/registry/@denotest/require-resolve/1.0.0/package.json
Part of #22607 (probably closes it, but I haven't done thorough testing)
Makes it so that `require.resolve` with `paths` specified will fallback to using the global cache when the paths can't be found when using a global cache (not when using a node_modules folder)
> fix(node): require.resolve - fallback to global cache when bare specifier from paths not found

- cli/lsp/analysis.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/resolver.rs
- cli/lsp/tsc.rs
This reverts commit 5cae3439912ad60eb2866f3d4372a5fe4d0de957.
Caused a +3.3s regression in one of the LSP benchmarks at deno.land/benchmarks.
> Revert "refactor(lsp): move fields from Documents to LspResolver"

- Releases.md
Update release notes for 1.43.0. The crate versions have already been bumped in the previous attempt.
> chore: 1.43 release notes

- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
Fixes #23643.
We weren't catching the cancellation exception thrown by TSC on the JS side, so the rust side was catching this exception and then attempting to print out the exception via `toString`. That last bit resulted in a cryptic `[object Object]` showing up in the logs like so:
```
Error during TS request "getCompletionEntryDetails":
[object Object]
```
I'm not 100% sure how we weren't seeing this in the past. My guess is that #23409 and the subsequent PR to improve the exception catching and logging surfaced this, but I'm still not quite clear on it.
My initial fix here returned `null` to rust when a server request was cancelled, but this resulted in a deserialization error when we attempted to deserialize that into the expected response type. So now, as soon as the request's …
> fix(lsp): Catch cancellation exceptions thrown by TSC, stop waiting for TS result upon cancellation

- ext/node/polyfills/http2.ts
The patch fixes grpc deadline example:
```sh
➜deno run -A deadline/client.js
Warning: Not implemented: Http2Session.socket
[1] wanted = OK got = OK
Warning: Not implemented: Http2Session.socket
[2] wanted = DEADLINE_EXCEEDED got = DEADLINE_EXCEEDED
Warning: Not implemented: Http2Session.socket
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'bodyRid')
at node:http2:888:96
at eventLoopTick (ext:core/01_core.js:207:9)
```
Fixed:
```
➜  examples git:(es_examples) denod run -A deadline/client.js
Warning: Not implemented: Http2Session.socket
[1] wanted = OK got = OK
Warning: Not implemented: Http2Session.socket
[2] wanted = DEADLINE_EXCEEDED got = DEADLINE_EXCEEDED
Warning: Not implemented: Http2Session.socket
[3] wanted = OK got = OK
Warning: Not …
```
> fix(ext/node): check resource exists before close

- tests/specs/npm/denotest2_scope/__test__.jsonc
- tests/specs/npm/denotest2_scope/main.js
- tests/specs/npm/denotest2_scope/main.out
- tests/testdata/npm/registry/@denotest2/basic/1.0.0/main.d.mts
- tests/testdata/npm/registry/@denotest2/basic/1.0.0/main.mjs
- tests/testdata/npm/registry/@denotest2/basic/1.0.0/other.mjs
- tests/testdata/npm/registry/@denotest2/basic/1.0.0/package.json
- tests/util/server/src/npm.rs
- tests/util/server/src/servers/mod.rs
This commit updates our testing npm registry to handle
additional `@denotest2` scope in addition to `@denotest`
scope. I might have to update it further in the future to handle
additional scopes, but it's good enough for now.
> test: npm registry handles two test scopes

- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/text.rs
- cli/lsp/tsc.rs
Fixes #23680.
This expectation https://github.com/denoland/deno/pull/10233#discussion_r615946424 ended up not being true. The ts server sometimes provides a token spanning multiple lines. I can't reproduce a case though.
> fix(lsp): handle multiline semantic tokens

- runtime/js/README.md
Refs: https://github.com/denoland/deno/commit/b4aa1530970f7b9cc4e6f2f27e077852c4e178d3
I also removed the note about this being a temporary solution, as it seems fair to assume it's unlikely to change in the foreseeable future, but I might be wrong.
> chore: fix outdated note in `runtime/js/README.md`

- ext/fetch/lib.rs
- runtime/ops/web_worker/sync_fetch.rs
1. We were polling each future in sequence, so this meant it was fetching scripts in sequence.
2. It's not safe to share `reqwest::Client` across tokio runtimes (https://github.com/seanmonstar/reqwest/issues/1148#issuecomment-910868788)
> fix(workers): `importScripts` concurrently and use a new `reqwest::Client` per importScripts

- cli/args/flags.rs
- cli/args/mod.rs
- cli/lsp/testing/execution.rs
- cli/standalone/binary.rs
- cli/standalone/mod.rs
- cli/tools/bench/mod.rs
- cli/tools/installer.rs
- cli/tools/repl/mod.rs
- cli/tools/run/mod.rs
- cli/tools/test/mod.rs
- tests/specs/compile/relative_permissions/__test__.jsonc
- tests/specs/compile/relative_permissions/main.ts
> fix(compile): relative permissions should be retained as relative

- tests/integration/jupyter_tests.rs
A bunch of small things, mostly around timing and making sure the jupyter kernel is actually running and ready to respond to requests. I reproduced the flakiness by running a script to run a bunch of instances of the test in parallel, where I could get failures consistently. After this PR, I can't reproduce the flakiness locally which hopefully means that applies to CI as well
> chore: (Hopefully) make `jupyter_execute_request` test less flaky

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- tests/integration/jupyter_tests.rs
- tests/integration/lsp_tests.rs
- tests/util/server/src/assertions.rs
Fixes the `Debug Failure` errors described in https://github.com/denoland/deno/issues/23643#issuecomment-2094552765 .
The issue here was that we were passing diagnostic codes as strings but TSC expects the codes to be numbers. This resulted in some quick fixes not working (as illustrated by the test added here which fails before this PR).
The first commit is the actual fix. The rest are just test related.
> fix(lsp): Pass diagnostic codes to TSC as numbers

- cli/jsr.rs
- cli/lsp/analysis.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/resolver.rs
- cli/lsp/tsc.rs
Relands #23585. Ref #23626.
The performance issue was caused by `Inner:refresh_documents_config()` being called after the auto-cache for the jsx import source. I replaced the resolver update there with a more granular `JsrCacheResolver::did_cache()`.
> refactor(lsp): reland move resolver fields to LspResolver

- ext/web/stream_resource.rs
Previously it was around 30s to run: `1024*2*15 = 30720ms`
> chore: speed up test_multi_task test on Windows

- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- cli/util/mod.rs
- cli/util/result.rs
- cli/util/v8.rs
- cli/util/v8/convert.rs
- tests/integration/repl_tests.rs
Works, but one failing test left to investigate
> refactor(lsp): Have JS drive TSC event loop in LSP

- runtime/permissions/lib.rs
- tests/specs/permission/proc_self_fd/__test__.jsonc
- tests/specs/permission/proc_self_fd/main.js
- tests/specs/permission/proc_self_fd/reader.ts
`deno run script.ts <(some command)` is a valid use case -- let's allow this to work without `--allow-all`.
Fixes #23703
> fix(runtime): Allow opening /dev/fd/XXX for unix

- Cargo.lock
- Cargo.toml
Includes a Rust 1.78.0 fix: https://github.com/denoland/deno_core/pull/735
Fixes deno homebrew crashes:
#23767
#23766
#23763
and https://github.com/Homebrew/homebrew-core/issues/171317
> fix: bump deno_core to fix unsoundness

- ext/node/polyfills/process.ts
- tests/unit_node/process_test.ts
Fixes https://github.com/denoland/deno/issues/23761
> fix(ext/node): process.uptime works without this

- tests/integration/run_tests.rs
- tests/util/server/src/pty.rs
https://github.com/denoland/deno/actions/runs/9084225162/job/24964698935
```
---- run::file_fetcher_preserves_permissions stdout ----
command /Users/runner/work/deno/deno/target/debug/deno repl --quiet
command cwd /Users/runner/work/deno/deno/tests/testdata
------ Start Full Text ------
"const a = await import('http://localhost:4545/run/019_media_types.ts');\r\n"
------- End Full Text -------
Next text: "\r\n"
thread 'run::file_fetcher_preserves_permissions' panicked at tests/integration/run_tests.rs:4615:15:
Timed out.
```
Closes https://github.com/denoland/deno/issues/23690
Closes https://github.com/denoland/deno/issues/23682
Closes https://github.com/denoland/deno/issues/23625
> chore(tests): increase repl timeout on ci

- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/semantic_tokens.rs
- tests/integration/lsp_tests.rs
- tests/util/server/src/lsp.rs
VScode will typically send a `textDocument/semanticTokens/full` request followed by `textDocument/semanticTokens/range`, and occassionally request semantic tokens even when we know nothing has changed. Semantic tokens also get refreshed on each change. Computing semantic tokens is relatively heavy in TSC, so we should avoid it as much as possible.
Caches the semantic tokens for open documents, to avoid making TSC do unnecessary work. Results in a noticeable improvement in local benchmarking
before:
```
Starting Deno benchmark
-> Start benchmarking lsp
- Simple Startup/Shutdown 
(10 runs, mean: 383ms)
- Big Document/Several Edits 
(5 runs, mean: 1079ms)
- Find/Replace
(10 runs, mean: 59ms)
- Code Lens
(10 runs, mean: 440ms)
- deco-cx/apps Multiple Edits + Navigation
(5 runs, mean: 9921ms) …
```
> perf(lsp): Cache semantic tokens for open documents

- ext/node/polyfills/worker_threads.ts
- tests/unit_node/worker_threads_test.ts
Fixes https://github.com/denoland/deno/issues/23801
> fix(node): wrong `worker_threads.terminate()` return value

- .github/workflows/ci.generate.ts
- .github/workflows/ci.yml
Use the smaller, reproducible sysroot from https://github.com/denoland/deno_sysroot_build
This saves about 50% of the transfer for each sysroot download.
> chore: bump sysroot

- tests/integration/lsp_tests.rs
- tests/util/server/src/lsp.rs
The stderr stream from the LSP is consumed by a separate thread, so it may not have processed the part we care about yet. Instead, wait until you see the measure for the request you care about.
> chore: Fix flaky semantic tokens caching test

- Cargo.lock
- cli/Cargo.toml
Related: https://github.com/denoland/eszip/pull/181
eszip < v0.69.0 hashes all its contents to ensure data integrity. This feature is not necessary in Deno CLI as the binary integrity guarantee is deemed an external responsibility (ie it is to be assumed that, if necessary, the compiled binary will be checksumed externally prior to being executed). 
eszip >= v0.69.0 no longer performs this checksum by default. This reduces the cold-start time of the compiled binaries, proportionally to their size.
> perf(compile): Do not checksum eszip content

- ext/node/polyfills/process.ts
- tests/unit_node/process_test.ts
Fixes https://github.com/denoland/deno/issues/23827
> fix(ext/node): export geteuid from node:process

- ext/node/polyfills/internal/fs/utils.mjs
The `EISDIR` error code is not available as a global variable, but must be accessed through the `osConstants.errno` object.
Fixes https://github.com/denoland/deno/issues/23695
> fix(node): error when throwing `FS_EISDIR`

- cli/lsp/documents.rs
- cli/lsp/tsc.rs
- tests/integration/lsp_tests.rs
Addresses an odd case where you have an unimported JS file in the project (the LSP should still treat unimported files as roots) which has `/// <reference types="..." />` to a file which creates global types, that types file should also be included as a root.
> fix(lsp): respect types dependencies for tsc roots

- Cargo.lock
- cli/args/flags.rs
- cli/args/mod.rs
- cli/worker.rs
- runtime/worker_bootstrap.rs
- tests/Cargo.toml
- tests/integration/mod.rs
- tests/integration/serve_tests.rs
- tests/testdata/serve.ts
Closes https://github.com/denoland/deno/issues/23845
> feat(serve): support `--port 0` to use an open port

- ext/node/polyfills/process.ts
- tests/unit_node/process_test.ts
Popular test runners like Jest instantiate a new `Process` object themselves and expect the class constructor to be callable without the `new` keyword. This PR refactors our `Process` class implementation from a proper ES2015 class to an ES5-style class which can be invoked both with and without the `new` keyword like in Node.
Fixes https://github.com/denoland/deno/issues/23863
> fix(node): instantiating process class without new

- Cargo.lock
- cli/emit.rs
- cli/main.rs
- cli/module_loader.rs
- cli/node.rs
- cli/resolver.rs
- cli/standalone/mod.rs
- ext/node/Cargo.toml
- ext/node/analyze.rs
- tests/integration/inspector_tests.rs
- tests/specs/npm/local_dir_no_duplicate_resolution/__test__.jsonc
- tests/specs/npm/local_dir_no_duplicate_resolution/main.out
- tests/specs/npm/local_dir_no_duplicate_resolution/run_main_sorted_lines.ts
Two main things we can do in parallel:
1. CJS export analysis
1. TypeScript emit
This makes the loader async to make doing this easier.
Deleting the node analysis cache between runs and importing some npm packages (this only makes the first run much faster due to the caches... the second run is the same speed as befroe):
```
Benchmark 1: ../deno/deno_old run -A ts_morph.ts
Time (mean ± σ):     406.1 ms ±   6.5 ms    [User: 358.1 ms, System: 62.2 ms]
Range (min … max):   395.9 ms … 412.9 ms    10 runs
Benchmark 2: ../deno/target/release/deno run -A ts_morph.ts
Time (mean ± σ):     278.2 ms ±   9.3 ms    [User: 411.1 ms, System: 81.4 ms]
Range (min … max):   266.1 ms … 292.9 ms    10 runs
Summary
../deno/target/release/deno run -A ts_morph.ts ran
1.46 ± 0.05 times faster than …
```
> perf: analyze cjs exports and emit typescript in parallel

- cli/tsc/dts/lib.dom.d.ts
- cli/tsc/dts/lib.webworker.d.ts
closes #23891
ref https://github.com/denoland/vscode_deno/issues/1116
> fix: add missing `URL.parse` types

- ext/node/polyfills/worker_threads.ts
- tests/unit_node/worker_threads_test.ts
Our `MessagePort` to Node's `MessagePort` conversion logic was missing the case where a `MessagePort` is sent _inside_ the message. This broke `tinypool` which is used by `vitest` as it relies on some node specific methods on `MessagePort`.
Fixes https://github.com/denoland/deno/issues/23854 , Fixes https://github.com/denoland/deno/pull/23871
> fix(node): patch MessagePort in worker_thread message

- ext/node/polyfills/process.ts
- tests/unit_node/process_test.ts
Some npm libraries like `signal-exit` rely on the length of the listener array returned by `process.listeners("SIGNT")` to be correct to function. We weren't tracking `SIG*` events there, which broke those npm libraries.
Fixes https://github.com/denoland/deno/issues/22892
> fix(node): track `SIG*` listeners in `process.listeners`

- ext/node/polyfills/01_require.js
- tests/unit_node/module_test.ts
This stubs `findSourceMap` in `node:module` by always returning `undefined` as if it never found a source map. This unblocks the `ava` test runner.
Fixes https://github.com/denoland/deno/issues/18666
> fix(node): stub findSourceMap for `ava`

- cli/emit.rs
```
Benchmark 1: ../deno/deno_old cache main.ts
Time (mean ± σ):     225.6 ms ±   6.5 ms    [User: 134.0 ms, System: 80.6 ms]
Range (min … max):   219.2 ms … 237.2 ms    12 runs
Benchmark 2: ../deno/deno_new cache main.ts
Time (mean ± σ):     168.7 ms ±   6.9 ms    [User: 234.3 ms, System: 167.2 ms]
Range (min … max):   156.5 ms … 182.0 ms    16 runs
Summary
../deno/deno_new cache main.ts ran
1.34 ± 0.07 times faster than ../deno/deno_old cache main.ts
% cat main.ts
import "https://deno.land/x/dax@0.22.0/mod.ts";
import "https://deno.land/x/dax@0.23.0/mod.ts";
import "https://deno.land/x/dax@0.24.0/mod.ts";
import "https://deno.land/x/dax@0.25.0/mod.ts";
```
Closes https://github.com/denoland/deno/issues/23860
> perf(cache): compile ts to js in parallel for `deno cache`

- ext/webgpu/command_encoder.rs
- tests/unit/webgpu_test.ts
The current implemention would panic at `op_webgpu_command_encoder_begin_render_pass` with legal JavaScript code, because `GpuRenderPassDepthStencilAttachment` require `depth_clear_value` to always appear.
The current WebGPU specification says[^1]
> (depthClearValue is) Ignored if `depthLoadOp` is not "clear"
[^1]: https://gpuweb.github.io/gpuweb/#dom-gpurenderpassdepthstencilattachment-depthclearvalue
The modification is tiny and easy to understand. Should I open a issue and/or add a unit test?
> fix(ext/webgpu): Allow `depthClearValue` to be undefined when `depthLoadOp` is not "clear"

- cli/tools/coverage/reporter.rs
- tests/integration/coverage_tests.rs
The `name` for the anchors are prefixed with a `L`, but the links are currently missing it so they don't work currently:
> fix(cli/coverage): invalid line id in html reporter

- cli/lsp/documents.rs
- cli/lsp/resolver.rs
- cli/resolver.rs
- tests/integration/lsp_tests.rs
- tests/registry/npm/@denotest/types-nested-js-dts/1.0.0/import.d.mts
- tests/registry/npm/@denotest/types-nested-js-dts/1.0.0/index.d.mts
- tests/registry/npm/@denotest/types-nested-js-dts/1.0.0/package.json
Fixes #23895.
Fixes #23878.
This was a regression in #23764 caused by removing this code block: https://github.com/denoland/deno/pull/23764/files#diff-5edc220fbc0fc6aebb443d977875a955bcb1304beb56fefbebae42925824d49aL1111-L1121. I supposed this was handled by the `CliGraphResolver`. This patch ensures `CliNodeResolver::node_resolve()` is called in `CliGraphResolver::resolve()`. ~~Maybe this was broken in `deno check` as well but no errors are surfaced because it produces a bunch of `any` types.~~ Not sure how to test this.
> fix(cli): use CliNodeResolver::resolve() for managed node_modules

- ext/web/stream_resource.rs
Because the buffers are `MaybeUninit<V8Slice<u8>`, and the owner of the `BoundedBufferChannel` is not obligated to read each and every bit of data, we may find that some buffers were not automatically dropped if unread by the time the `BoundedBufferChannelInner` is dropped. 
Possible repro:
```
Deno.serve(() => new Response(new ReadableStream({ start(controller) { controller.enqueue(new Uint8Array(100_000_000))  } })));
```
```bash
while true; do curl localhost:8000 | dd count=1; done
```
> fix(ext/web): fix potential leak of unread buffers

- cli/lsp/tsc.rs
- tests/integration/lsp_tests.rs
We were wrapping the display string in an unnecessary pair of triple backticks, breaking highlighting
Before:
After:
> fix(lsp): Fix display of JSDoc named examples

- cli/lsp/testing/execution.rs
- cli/tools/test/mod.rs
- cli/tools/test/reporters/compound.rs
- cli/tools/test/reporters/dot.rs
- cli/tools/test/reporters/junit.rs
- cli/tools/test/reporters/mod.rs
- cli/tools/test/reporters/pretty.rs
- cli/tools/test/reporters/tap.rs
- tests/specs/test/slow_test/__test__.jsonc
- tests/specs/test/slow_test/main.js
- tests/specs/test/slow_test/main.out
By default, uses a 60 second timeout, backing off 2x each time (can be overridden using the hidden `DENO_SLOW_TEST_TIMEOUT` which we implement only really for spec testing.
```
Deno.test(async function test() {
await new Promise(r => setTimeout(r, 130_000));
});
```
```
$ target/debug/deno test /tmp/test_slow.ts 
Check file:///tmp/test_slow.ts
running 1 test from ../../../../../../tmp/test_slow.ts
test ...'test' is running very slowly (1m0s)
'test' is running very slowly (2m0s)
ok (2m10s)
ok | 1 passed | 0 failed (2m10s)
```
> feat(cli): Add slow test warning

- tests/testdata/task/npx/non_existent.out
Currently `task::task_npx_non_existent` is consistently failing in CI ([example](https://github.com/denoland/deno/actions/runs/9192958846/job/25282900321#step:43:2772)) due to the output changing slightly
```
-- OUTPUT START --
Task non-existent npx this-command-should-not-exist-for-you
npm ERR! code E404
npm ERR! 404 Not Found - GET http://localhost:4260/this-command-should-not-exist-for-you
npm ERR! 404 
npm ERR! 404  'this-command-should-not-exist-for-you@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in: /Users/runner/.npm/_logs/2024-05-22T17_58_42_473Z-debug-0.log
-- OUTPUT END --
-- EXPECTED START --
Task non-existent npx …
```
> chore: Fix failing `task_npx_non_existent` test

- Cargo.lock
- Cargo.toml
- runtime/js/99_main.js
- tests/testdata/run/heapstats.js.out
v8 12.6 w/pointer compression enabled.
Closes https://github.com/denoland/deno/issues/18935
> feat: enable pointer compression via deno_core bump

- cli/cache/cache_db.rs
While investigating poor cold start performance on my GCP VM (32 cores, 130GB SSD), I found that writing to the various sqlite databases in DENO_DIR was quite slow. The slowness seems to primarily be caused by excessive latency from a number of `fsync()` calls.
The performance difference is best demonstrated by deleting the sqlite databases from DENO_DIR while leaving the downloaded sources in place.
The benchmark (see notes below):
```
piscisaureus@bert-us:~/erofs/source$ export DENO_DIR=./.deno
piscisaureus@bert-us:~/erofs/source$ hyperfine --warmup 3   \
--prepare "rm -rf .deno/*_v1*"                            \
"deno run -A --cached-only demo.ts"                       \
"eatmydata deno run -A --cached-only demo.ts"             \
"~/deno/target/release/deno run -A --cached-only …
```
> perf(startup): use WAL journal for sqlite databases in DENO_DIR

- ext/node/polyfills/perf_hooks.ts
- tests/unit_node/perf_hooks_test.ts
Fixes https://github.com/denoland/deno/issues/23943
> fix(ext/node): add stubs for perf_hooks.PerformaceObserver

- ext/node/ops/http2.rs
- ext/node/polyfills/http2.ts
The flag lets us exit from read loop without throwing an error when
the stream is cancelled.
This fixes gRPC cancellation example.
> fix(ext/node): return cancelled flag in get_response_body_chunk op

- cli/main.rs
- cli/standalone/mod.rs
No longer needed as standalone binaries use `denort`
> chore(cli): remove extract_standalone path from CLI

- cli/tools/coverage/reporter.rs
- tests/integration/coverage_tests.rs
closes #21582
This PR adds tooltip to the execution count part of html coverage report.
> fix(coverage): add tooltip to line count in html report

- cli/tsc/dts/lib.deno.ns.d.ts
- ext/http/02_websocket.ts
Nginx has a default timeout of 60 seconds. I fell down this rabbit hole trying to figure out why WebSockets kept getting closed every 60 seconds in my application. First I found #15430 and assumed ping/pong doesn't work in Deno at all. Then I found #13172 and the discussion in https://github.com/denoland/deno/discussions/13168.
It turns out, there is already an automatic ping/pong in Deno. But it only happens every 120 seconds by default.
So I [set the idleTimeout](https://gitlab.com/soapbox-pub/ditto/-/merge_requests/320) to 30s in my application, and suddenly my problems went away.
It seems to me that the default should be 30s. Otherwise people will continue to have this problem. With 30s it "just works" with common setups.
> fix(ext/websocket): change default idleTimeout to 30s

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
Node sets the default HTTP response status code to 200 on the `ServerResponse`. We initialised it as `undefined` before which caused a problem with 11ty's dev server.
Thanks to @vrugtehagel for reporting this issue and finding the correct fix as well 🎉 
Fixes https://github.com/denoland/deno/issues/23970
> fix(node): set default http server response code 200

- cli/args/mod.rs
- tests/specs/future/unstable_flags/__test__.jsonc
- tests/specs/future/unstable_flags/main.js
- tests/specs/future/unstable_flags/main.out
- tests/specs/future/unstable_flags/worker.js
Closes https://github.com/denoland/deno/issues/23906
> FUTURE(ext/fs): stabilize file system APIs

- cli/tools/coverage/mod.rs
- tests/integration/coverage_tests.rs
`--ignore` pattern is currently matched against the coverage raw data path (`<UUID>.json`) and doesn't work as ignore pattern.
This PR adds the path pattern checks against `url` property of each json object, and excludes the ignored patterns correctly.
closes #23972
> fix(coverage): handle ignore patterns

- ext/node/polyfills/_fs/_fs_lstat.ts
- tests/unit_node/fs_test.ts
We didn't support the `throwIfNoEntry` option for Node's `fs.lstatSync` method. Note that the async variant doesn't have this option.
Fixes https://github.com/denoland/deno/issues/23996
> fix(ext/node): support `throwIfNoEntry` option in `fs.lstatSync`

- runtime/ops/bootstrap.rs
We use the `target` property of the snapshot options to derive `process.platform` and `process.arch` from. This value had an incorrect format when compiled with `__runtime_js_sources` enabled. This PR fixes that so that `process.platform` holds the proper value.
Fixes https://github.com/denoland/deno/issues/23164
> fix: empty `process.platform` with `__runtime_js_sources`

- ext/node/polyfills/internal/fs/handle.ts
- tests/unit_node/_fs/_fs_write_test.ts
- tests/unit_node/fs_test.ts
We didn't honour the `position` options of `fd.read` and `fd.write` because we checked if the buffer is of type `Buffer` instead of just `Uint8Array`. Node does the latter. In doing so I noticed that the file handle id was written to a public property which it definitely shouldn't be. This was probably a typo.
Fixes https://github.com/denoland/deno/issues/23707
> fix(ext/node/fs): `position` argument not applied

- cli/npm/managed/registry.rs
- cli/npm/managed/resolvers/local.rs
The same issue in two different places - doing blocking FS work in an async task, limiting the amount of work that happens concurrently.
- When setting up node_modules, where we try to set up entries concurrently but were blocking other tasks from actually running.
- When loading package info from the npm registry file cache, loading and deserializing is expensive and prevents concurrency. This was especially noticeable when loading an npm resolution snapshot from a lockfile (`snapshot_from_lockfile` in `deno_npm`).
Installing deps in `deno-docs`:
```
❯ hyperfine -i -p 'rm -rf node_modules/' '../d7/deno-main i' '../d7/target/release/deno i'
Benchmark 1: ../d7/deno-main i
Time (mean ± σ):      2.193 s ±  0.027 s    [User: 0.589 s, System: 1.033 s]
Range (min … max):    2.151 s …  2.242 s …
```
> perf(cli): Improve concurrency when setting up `node_modules` and loading cached npm package info

- Cargo.lock
- ext/io/Cargo.toml
- ext/io/lib.rs
- runtime/ops/tty.rs
- tests/integration/run_tests.rs
- tests/testdata/run/process_stdin_unblock.mjs
This patch fixes stdin read hanging on user input when switching tty mode on Windows
Fixes #21111 
On Windows, when switching from line to raw mode:
- Cancel ongoing console read by writing a return keypress to its input buffer. This blocks the main thread until any ongoing read has been cancelled to prevent interference with the screen state.
- On the read thread, restore the cursor position to where it was before writing the enter, undoing its effect on the screen state.
- Restart reading and notify the main thread.
> fix(ext/node): windows cancel stdin read in line mode

- Cargo.lock
- cli/Cargo.toml
- cli/cache/cache_db.rs
- cli/cache/check.rs
- cli/cache/code_cache.rs
- cli/cache/common.rs
- cli/cache/deno_dir.rs
- cli/cache/emit.rs
- cli/cache/fast_check.rs
- cli/cache/incremental.rs
- cli/cache/mod.rs
- cli/cache/module_info.rs
- cli/cache/node.rs
- cli/emit.rs
- cli/lsp/config.rs
- cli/module_loader.rs
- cli/node.rs
- cli/npm/managed/mod.rs
- cli/tools/check.rs
- cli/tsc/mod.rs
- tests/integration/jsr_tests.rs
- tests/integration/run_tests.rs
In https://github.com/denoland/deno/pull/23955 we changed the sqlite db journal mode to WAL. This causes issues when someone is running an old version of Deno using TRUNCATE and a new version because the two fight against each other.
> fix: bump cache sqlite dbs to v2 for WAL journal mode change

- cli/module_loader.rs
- tests/specs/run/dynamic_already_prepared/__test__.jsonc
- tests/specs/run/dynamic_already_prepared/dynamic.ts
- tests/specs/run/dynamic_already_prepared/dynamic2.ts
- tests/specs/run/dynamic_already_prepared/dynamic3.ts
- tests/specs/run/dynamic_already_prepared/main.out
- tests/specs/run/dynamic_already_prepared/main.ts
Real fix instead of https://github.com/denoland/deno/pull/24020
```
Benchmark 1: ../../deno/deno_old run -A repro.ts
Time (mean ± σ):     272.0 ms ±   5.4 ms    [User: 267.9 ms, System: 95.2 ms]
Range (min … max):   267.1 ms … 287.0 ms    11 runs
Benchmark 2: ../../deno/target/release/deno run -A repro.ts
Time (mean ± σ):     237.2 ms ±   2.0 ms    [User: 236.0 ms, System: 93.1 ms]
Range (min … max):   235.6 ms … 243.0 ms    12 runs
Summary
../../deno/target/release/deno run -A repro.ts ran
1.15 ± 0.02 times faster than ../../deno/deno_old run -A repro.ts
```
```
Benchmark 1: ../../deno/deno_old run -A repro2.ts
Time (mean ± σ):     202.2 ms ±   3.4 ms    [User: 233.0 ms, System: 61.3 ms]
Range (min … max):   199.1 ms … 211.7 ms    14 runs
Benchmark 2: ../../deno/target/release/deno run …
```
> perf: avoid building module graph if dynamic specifier already in graph

- cli/lsp/config.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- tests/integration/repl_tests.rs
Fixes #24031. Don't walk the workspace if the workspace capability is `None`. Also refactor client capability storage to use the `lsp_types` field and not parsing it into our own struct. It had some unused fields.
We used to address this by passing `document_preload_limit: 0` from the repl, but the workspace walk was separated from that check as of #23123.
> perf(repl): don't walk workspace in repl language server

- Cargo.lock
- cli/Cargo.toml
- cli/ops/jupyter.rs
- cli/tools/jupyter/install.rs
- cli/tools/jupyter/mod.rs
- cli/tools/jupyter/server.rs
Brings in:
* More fully typed structures (for when we get to implementing more)
* `with_metadata`, `with_buffers`, etc. from https://github.com/runtimed/runtimed/pull/99
> chore: upgrade jupyter runtimelib to 0.11.0

- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/ffi/00_ffi.js
- ext/ffi/dlfcn.rs
- ext/ffi/repr.rs
- ext/ffi/turbocall.rs
- tests/ffi/tests/bench.js
- tests/ffi/tests/ffi_types.ts
- tests/ffi/tests/test.js
- tests/unit/ffi_test.ts
Built ontop of #23981 and should only be merged after it; this sets FFI turbocalls (Fast Call API) to use the BigInt representation.
> BREAKING(ffi/unstable): Use BigInt representation in turbocall

- cli/args/mod.rs
- cli/lsp/config.rs
- tests/integration/lsp_tests.rs
> feat(lsp): support .npmrc

- cli/args/mod.rs
- cli/lsp/config.rs
- tests/integration/lsp_tests.rs
- tests/specs/npm/npmrc/__test__.jsonc
We were initially only adding this to deno_future because it was going to land in a patch release. We can remove this now though.
> feat: do not require `DENO_FUTURE=1` for npmrc support

- cli/args/lockfile.rs
- cli/util/fs.rs
Ran into this running the deno_graph ecosystem tests where many processes writing to the same path at the same time would cause an error.
> fix: retry writing lockfile on failure

- ext/console/01_console.js
Previously it did not exist, so `assert` would crash the wrong way if it failed.
No issue filed but I can create one if needed, a repro to cause this if you want to test is pasting this in REPL: (sorry)
```js
new Proxy({}, { ownKeys: () => ['foo'], getOwnPropertyDescriptor: () => ({ configurable: false }) })
```
> fix(console): add missing AssertionError to js

- cli/lsp/completions.rs
- cli/lsp/language_server.rs
- tests/integration/lsp_tests.rs
Also clean up local file completions for import mapped relative specifiers, this worked in a really weird way: https://github.com/denoland/deno/blob/v1.44.0/cli/lsp/completions.rs#L319-L352. Both of these are now done by first using the resolver to find the actual 1) JSR package or 2) local directory, and applying the current logic to that instead of the raw partial specifier.
Fixes #24050, this is just https://github.com/denoland/deno/blob/v1.44.0/cli/lsp/completions.rs#L377-L382 being in the wrong scope.
> fix(lsp): complete exports for import mapped jsr specifiers

- Cargo.lock
- Cargo.toml
- ext/web/01_dom_exception.js
- tests/testdata/run/eval_context_throw_dom_exception.js.out
- tests/unit/dom_exception_test.ts
This makes `DOMException`'s `stack` property behave the same as native errors' – `stack` is now an own accessor property on every instance, and the getter calls `Error.prepareStackTrace`.
denoland/deno_core#754 depends on this.
> chore(ext/web): use `Error.captureStackTrace` in `DOMException` constructor

- Cargo.lock
- ext/net/Cargo.toml
- ext/net/ops.rs
- tests/Cargo.toml
- tests/integration/run_tests.rs
To avoid duplicate winreg crate in #24056
> chore: upgrade trust-dns-resolver and friends

- cli/npm/managed/resolvers/local/bin_entries.rs
- tests/specs/task/bin_package/__test__.jsonc
- tests/specs/task/bin_package/already-set-up.out
Previously we warned on unix and didn't touch them on windows, now we unconditionally overwrite them. This matches what npm does.
> fix(cli): Overwrite existing bin entries in `node_modules`

- Cargo.lock
- Cargo.toml
- cli/tools/lint/mod.rs
- tests/specs/lint/bom/__test__.jsonc
- tests/specs/lint/bom/mod.out
- tests/specs/lint/bom/mod.ts
> fix: do not panic linting files with UTF-8 BOM

- cli/cache/disk_cache.rs
- cli/cache/mod.rs
- cli/npm/managed/resolvers/local.rs
- cli/util/fs.rs
I was able to reproduce this locally.
```
[error] Failed to execute snippet: 
import { validate } from "@std/uuid";
import { assert, assertFalse } from "@std/assert";
assert(validate("6ec0bd7f-11c0-43da-975e-2a8ad9ebae0b"));
assertFalse(validate("not a UUID"));
Download https://jsr.io/@std/uuid/meta.json
Download https://jsr.io/@std/uuid/1.0.0-rc.1_meta.json
Download https://jsr.io/@std/uuid/1.0.0-rc.1/mod.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/common.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/constants.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/v1.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/v3.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/v4.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/v5.ts
Download https://jsr.io/@std/uuid/1.0.0-rc.1/_common.ts
error: Access …
```
> fix: make writing to the deps cache more reliable

- Cargo.lock
- Cargo.toml
Includes:
- [fix: lossily UTF8 decode module source text](https://github.com/denoland/deno_core/commit/ec38e428c6a887ca240068fd37be8ca0de6c2f18)
- [fix: `ModuleMap` was not dropped if it had pending futures](https://github.com/denoland/deno_core/commit/5d12f510a1b2db2f6c7def8129c92202ad0f91ff)
> chore: upgrade deno_core to 0.287.0

- cli/node.rs
- cli/resolver.rs
- cli/util/gitignore.rs
- ext/fs/interface.rs
- ext/fs/ops.rs
- ext/node/ops/require.rs
- ext/node/package_json.rs
- tests/registry/npm/@denotest/lossy-utf8-module/1.0.0/index.js
- tests/registry/npm/@denotest/lossy-utf8-module/1.0.0/package.json
- tests/registry/npm/@denotest/lossy-utf8-package-json/1.0.0/index.js
- tests/registry/npm/@denotest/lossy-utf8-package-json/1.0.0/package.json
- tests/registry/npm/@denotest/lossy-utf8-script/1.0.0/index.js
- tests/registry/npm/@denotest/lossy-utf8-script/1.0.0/package.json
- tests/specs/npm/lossy_utf8_module/__test__.jsonc
- tests/specs/npm/lossy_utf8_module/main.mjs
- tests/specs/npm/lossy_utf8_module/main.out
- tests/specs/npm/lossy_utf8_package_json/__test__.jsonc
- tests/specs/npm/lossy_utf8_package_json/main.mjs
- tests/specs/npm/lossy_utf8_package_json/main.out
- tests/specs/npm/lossy_utf8_script/__test__.jsonc
- tests/specs/npm/lossy_utf8_script/main.mjs
- tests/specs/npm/lossy_utf8_script/main.out
- tests/specs/npm/lossy_utf8_script_from_cjs/__test__.jsonc
- tests/specs/npm/lossy_utf8_script_from_cjs/main.mjs
- tests/specs/npm/lossy_utf8_script_from_cjs/main.out
- tests/util/server/src/npm.rs
Previously various reads of files in `node_modules` would error on invalid UTF-8. These were cases involving:
- reading package.json from Rust
- reading package.json from JS
- reading CommonJS files from JS
- reading CommonJS files from Rust (for ESM translation)
- reading ESM files from Rust
There are tests for all these cases now.
Fixes #24027
Needs https://github.com/denoland/deno_core/pull/773 to land first.
> fix(ext/node): lossy UTF-8 read node_modules files

- ext/websocket/01_websocket.js
- tests/unit/websocket_test.ts
Previously the asynchronous read of the blob would not block sends that are started later. We now do this, but in such a way as to not regress performance in the common case of not using `Blob`.
Fixes #24074
> fix(ext/websocket): correctly order messages when sending blobs

- cli/npm/byonm.rs
- cli/npm/common.rs
- cli/npm/managed/mod.rs
- cli/npm/managed/resolvers/common.rs
- cli/npm/managed/resolvers/global.rs
- cli/npm/managed/resolvers/local.rs
- cli/resolver.rs
- ext/node/analyze.rs
- ext/node/lib.rs
- ext/node/ops/require.rs
- ext/node/resolution.rs
- tests/specs/npm/check_prefers_non_types_node_pkg/__test__.jsonc
- tests/specs/npm/check_prefers_non_types_node_pkg/main.ts
- tests/specs/npm/check_prefers_non_types_node_pkg/node_modules/@types/lz-string/package.json
- tests/specs/npm/check_prefers_non_types_node_pkg/node_modules/lz-string/index.d.ts
- tests/specs/npm/check_prefers_non_types_node_pkg/node_modules/lz-string/index.js
- tests/specs/npm/check_prefers_non_types_node_pkg/node_modules/lz-string/package.json
- tests/specs/npm/check_prefers_non_types_node_pkg/package.json
I've been meaning to fix this for ages, but I finally ran into it here:
https://github.com/dsherret/ts-ast-viewer/actions/runs/9432038675/job/25981325408
We need to resolve the `@types` package as a fallback instead of eagerly resolving it.
> fix(check): attempt to resolve types from pkg before `@types` pkg

- ext/node/ops/http2.rs
- ext/node/polyfills/http2.ts
We previously ended the http2 stream by sending trailers which should have been only used if waitForTrailers option is set on the http2session. This patch updates it and ends the stream by sending an empty data frame with end_stream flag set or by emitting 'wantTrailers' event if waitForTrailers option is set.
Hard to create an unit test as this requires that a test server needs to ack end of stream flag and then process a request. The example from #24058 works.
Closes https://github.com/denoland/deno/issues/24058
> fix(ext/node): send data frame with end_stream flag on _final call

- cli/tools/jupyter/mod.rs
Fixes #22050.
It seems very unlikely that a user would be intending to enable deno's internal debug logs by setting the DEBUG env var. If they really want that, they can set `RUST_LOG=debug` instead.
> fix(jupyter): Avoid panicking when `DEBUG` env var is set

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
Previously res.setHeader("foo", ["bar", "baz"]) added a single header with a value of `bar,baz`. Really this should add two separate headers. This is visible in `set-cookie` for example.
Fixes #23662
> fix(ext/node): ServerResponse header array handling

- tools/verify_pr_title.js
Too many `chore: upgrade deno_core` PRs have landed that fix issues in the CLI. These PR titles should be descriptive of the bugs they fix.
> ci: error on `chore:` deno_core upgrade pr titles

- cli/lsp/config.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
This stops nested `deno.json`s from being added to the tree before their parents. This would break workspaces for subdirs with names preceding `deno.json`, but it's not observable yet.
> fix(lsp): don't sort workspace files

- cli/napi/js_native_api.rs
- cli/napi/node_api.rs
- cli/napi/util.rs
- ext/napi/function.rs
- ext/napi/lib.rs
- ext/napi/value.rs
- fix a few napi_* types
- clean up env hooks
- implement blocking queue in tsfn
- reduce transmutes
- use new `DataView::new` api from rusty_v8
> fix: clean up some node-api details

- cli/lsp/language_server.rs
- tests/integration/lsp_tests.rs
Closes #23257. Respects and prioritizes the indentation options selected on the VSCode status bar.
> feat(lsp): respect editor indentation options

- cli/lsp/analysis.rs
- tests/integration/lsp_tests.rs
> fix(lsp): strip .js before probing for valid import fix

- cli/module_loader.rs
- tests/specs/install/future_install_node_modules/__test__.jsonc
- tests/specs/install/future_install_node_modules/install_lockfile.out
- tests/specs/npm/npmrc_not_next_to_package_json/main.out
Fixes a regression introduced in https://github.com/denoland/deno/pull/24170, where we wouldn't actually set up the node modules dir on `deno install` if there was an up to date deno lockfile present. 
Previously we were relying on the fact that resolving pending module resolution called `cache_packages` (which sets up the node modules dir). When pending resolutions were removed, and the `resolve_pending` function with it, we also removed the `cache_packages` call needed to set up node modules.
> fix(cli): Explicitly cache NPM packages during `deno install`

- ext/node/lib.rs
- ext/node/ops/v8.rs
- ext/node/ops/vm.rs
Unused; before the recent rewrite of node:vm
> chore(ext/node): remove old vm ops

- runtime/js/90_deno_ns.js
- runtime/lib.rs
> fix(cli): missing flag for `--unstable-process`

- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
Namely `Config::{settings,client_capabilities,workspace_folders}` and some nested `WorkspaceSettings`. These are large and cloned often.
> perf(lsp): store settings in Arc

- Cargo.lock
- cli/Cargo.toml
- cli/args/package_json.rs
- cli/standalone/binary.rs
- tests/specs/npm/npmrc_basic_auth/package.json
- tests/testdata/package_json/invalid_value/error.ts.out
- tests/testdata/package_json/invalid_value/task.out
Includes:
* https://github.com/denoland/deno_semver/pull/23
> fix(npm): use more relaxed package.json version constraint parsing

- cli/napi/js_native_api.rs
- tests/napi/object_wrap_test.js
- tests/napi/src/object_wrap.rs
- tests/napi/tests/napi_tests.rs
Fixes #23493.
What was happening here was that napi-rs was freeing the napi reference ([here](https://github.com/napi-rs/napi-rs/blob/19e3488efcbc601afa1f11a979372eb6c5ea6130/crates/napi/src/bindgen_runtime/mod.rs#L62)) during its finalize callback (which we call [here](https://github.com/denoland/deno/blob/fb31eaa9ca59f6daaee0210d5cd206185c7041b9/cli/napi/js_native_api.rs#L132)). We then were [reading the `ownership` field](https://github.com/denoland/deno/blob/fb31eaa9ca59f6daaee0210d5cd206185c7041b9/cli/napi/js_native_api.rs#L136) of that freed reference.
For some reason on arm macs the freed memory gets zeroed, so the value of `ownership` was `0` when we read it (i.e. it was `ReferenceOwnership::Runtime`). We then freed it again (since we thought we owned it), causing the segfault.
> fix(napi): Read reference ownership before calling finalizer to avoid crash

- Cargo.lock
- Cargo.toml
- tests/integration/inspector_tests.rs
Closes https://github.com/denoland/deno/issues/24196
> fix(inspector): crash on "Debugger.setBlackboxPatterns"

- runtime/permissions/Cargo.toml
Adds 3 new feature flags to `runtime/permissions/winapi` to close issue #24212
> fix(ext/permissions): add correct feature flags to winapi

- cli/lsp/cache.rs
- cli/lsp/code_lens.rs
- cli/lsp/config.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/resolver.rs
- cli/lsp/tsc.rs
- cli/lsp/urls.rs
- tests/integration/lsp_tests.rs
Closes https://github.com/denoland/vscode_deno/issues/787.
Closes https://github.com/denoland/vscode_deno/issues/938.
After this, remaining TODOs are:
- Separate TS type checking environments across deno.json scopes (different global declarations, tsconfigs etc).
- Inheritance of properties in workspace members. This must be fleshed out and implemented in the CLI first.
> feat(lsp): multi deno.json resolver scopes

- ext/node/polyfills/process.ts
- tests/unit/process_test.ts
- tests/unit_node/process_test.ts
Fixes https://github.com/denoland/deno/issues/24233
This is a quick fix. There are some more properties that should be on the object rather than the class, this'll do for now
```
[divy@divy deno]$ target/debug/deno
Deno 1.44.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> import { ClientSecretCredential } from "npm:@azure/identity";
const test = new ClientSecretCredential("a","b","c",);
console.log(test);
ClientSecretCredential {
clientSecret: "c",
tenantId: "a",
additionallyAllowedTenantIds: [],
msalClient: {
getTokenByClientSecret: [AsyncFunction: getTokenByClientSecret],
getTokenByClientAssertion: [AsyncFunction: getTokenByClientAssertion],
getTokenByClientCertificate: [AsyncFunction: …
```
> fix(ext/node): make process.versions own property

- ext/console/01_console.js
- tests/unit/console_test.ts
Fixes https://github.com/denoland/deno/issues/22160
> fix(ext/console): bump default max str lengthto 10_00

- ext/node/analyze.rs
- tests/integration/run_tests.rs
As reported by @igorzi 
We need to ensure the cjs wrapper module has deterministic output so we don't update the code cache each run.
> perf(node): ensure cjs wrapper module has deterministic output

- Cargo.lock
- Cargo.toml
A PR was landed by mistake that used `[patch.crates-io]` instead
of released `deno_core` version: https://github.com/denoland/deno/pull/23842#discussion_r1645170369
> chore: remove deno_core patch

- cli/standalone/virtual_fs.rs
- ext/fs/interface.rs
- ext/fs/std_fs.rs
- ext/node/polyfills/_fs/_fs_dirent.ts
- test.mjs
- tests/unit_node/_fs/_fs_dirent_test.ts
Fixes https://github.com/denoland/deno/issues/24227
Adds `parentPath` field Deno.DirEntry for use in node:fs
> fix(ext/node): Add Dirent.path and Dirent.parentPath

- cli/tsc/dts/lib.deno.ns.d.ts
- runtime/ops/signal.rs
- tests/unit/signal_test.ts
Fixes https://github.com/denoland/deno/issues/24227 on Linux
SIGPOLL is alias for SIGIO
SIGUNUSED is alias for SIGSYS
> fix(ext/node): Add SIGPOLL and SIGUNUSED signals

- ext/node/polyfills/_utils.ts
> fix(ext/node): use primordials in `ext/node/polyfills/_utils.ts`

- cli/napi/js_native_api.rs
- cli/napi/node_api.rs
- ext/napi/lib.rs
- ext/node/polyfills/process.ts
- add fallback impls of external string apis which always copy. after upstream changes to rusty_v8 we can support non-copying api as well.
- `napi_get_buffer_data` needs to work on all TypedArray instances.
- Fixes: https://github.com/denoland/deno/issues/24209
- `target_defaults.default_configuration` is used by some modules to find the corresponding node file from node-gyp
- `node_api_get_module_filename` expects the filename to be a `file:` url.
> fix: more node-api fixes

- Cargo.lock
- cli/Cargo.toml
- cli/tools/task.rs
* https://github.com/denoland/deno_task_shell/pull/120
> fix(task): do not propagate env changes outside subshells

- Cargo.toml
This sorts and re-aligns the `bench` and `release` profiles, notably enabling optimizations for `fastwebsockets` in the released CLI binary.
The goal is to unlock auto-vectorization for ws hotpaths, as noted in https://github.com/denoland/fastwebsockets/blob/0.7.0/src/mask.rs#L22 (contrarily to that comment, disassembling the amd64 `deno` 1.44 binary shows no SIMD instructions in ws-unmasking logic).
> perf(ws): optimize fastwebsockets in release profile

- ext/websocket/01_websocket.js
Improves echo server message throughput by ~40-50% (103k -> 146k msg/sec)
Before: https://share.firefox.dev/3Rzzez2
After: https://share.firefox.dev/3VzXAKn
> perf(ext/websocket): avoid global interceptor overhead

- ext/node/polyfills/_http_common.ts
> fix(ext/node): use primordials in `ext/node/polyfills/_http_common.ts`

- Cargo.lock
- Cargo.toml
- ext/http/Cargo.toml
- ext/http/response_body.rs
- ext/node/ops/zlib/brotli.rs
Avoids issues when using these extensions in a project that also links to the C brotli library. See dropbox/rust-brotli#46.
> refactor(ext): remove use of `brotli::ffi`

- ext/node/polyfills/string_decoder.ts
> fix(ext/node): use primordials in `ext/node/polyfills/string_decoder.ts`

- cli/tsc/dts/lib.deno.ns.d.ts
`import.meta.dirname` behaves correctly, according to [Node's implementation](https://nodejs.org/api/esm.html#importmetadirname). Rather, the documentation simply had a typo.
Closes #24278
> docs(cli): remove trailing slash from `import.meta.dirname` expected output

- ext/node/ops/crypto/mod.rs
- tests/unit_node/crypto/crypto_key_test.ts
> fix(ext/node): don't panic on invalid utf-8 in pem

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/19993
Closes https://github.com/denoland/deno/issues/16679
> fix(ext/node): add ServerResponse#appendHeader

- ext/node/polyfills/testing.ts
> fix(ext/node): use primordials in `ext/node/polyfills/testing.ts`

- ext/node/polyfills/timers.ts
> fix(ext/node): use primordials in `ext/node/polyfills/timers.ts`

- ext/node/polyfills/_fs/_fs_cp.js
> fix(ext/node): use primordials in `ext/node/polyfills/_fs/_fs_cp.js`

- ext/node/polyfills/_fs/_fs_dir.ts
> fix(ext/node): use primordials in `ext/node/polyfills/_fs/_fs_dir.ts`

- ext/websocket/01_websocket.js
- ext/websocket/lib.rs
- tests/unit/websocket_test.ts
> fix(ext/websocket): drop connection when close frame not ack

- ext/node/polyfills/01_require.js
This field is deprecated but still used by the ecosystem, so let's just support it.
> feat: add module.parent

- Cargo.lock
- cli/Cargo.toml
- cli/graph_util.rs
- cli/lsp/diagnostics.rs
- cli/standalone/mod.rs
- cli/tools/compile.rs
No fixes in this to my knowledge. Just an upgrade. The functionality here will be used in a different PR.
> refactor: bump deno_graph to 0.79

- ext/node/polyfills/internal_binding/_utils.ts
Don't try to clean the input unless decoding fails at first. A ~3x improvement for forgiving-base64 conforming input.
```
$ target/release/deno run  -A ./bench.mjs
593.3049169
$ deno run -A ./bench.mjs
1912.209888
$ node bench.mjs
989.406209
```
```js
import { Buffer } from "node:buffer";
const buffer = Buffer.alloc(1024 * 10, "latin1");
const input = buffer.toString("base64");
const start = performance.now();
for (let i = 0; i < 100000; i++) {
Buffer.from(input, "base64");
}
console.log(performance.now() - start);
```
Ref #24323
> perf: optimize Buffer.from("base64") for forgiving-base64 conforming input

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/args/mod.rs
- cli/args/package_json.rs
- cli/factory.rs
- cli/lsp/config.rs
- cli/lsp/language_server.rs
- cli/lsp/resolver.rs
- cli/npm/byonm.rs
- cli/resolver.rs
- cli/standalone/binary.rs
- cli/tools/lint/mod.rs
- cli/tools/registry/pm.rs
- cli/tools/registry/unfurl.rs
- cli/worker.rs
- ext/fs/Cargo.toml
- ext/fs/interface.rs
- ext/fs/lib.rs
- ext/node/Cargo.toml
- ext/node/analyze.rs
- ext/node/lib.rs
- ext/node/ops/require.rs
- ext/node/package_json.rs
- ext/node/polyfills/01_require.js
- ext/node/resolution.rs
- tests/integration/lsp_tests.rs
- tests/integration/npm_tests.rs
~~Waiting on https://github.com/denoland/deno_config/pull/60~~
> refactor: move PackageJson to deno_config

- cli/lsp/code_lens.rs
- cli/lsp/config.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/resolver.rs
- cli/lsp/tsc.rs
- cli/tsc/99_main_compiler.js
- tests/integration/lsp_tests.rs
Closes https://github.com/denoland/vscode_deno/issues/488.
Closes #24293.
> feat(lsp): ts language service scopes

- cli/lsp/cache.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
Fixes #24342. It's very complex to test but I've verified that the repro works and file referrers are allocated correctly.
> fix(lsp): don't use global cache paths for scope allocation

- cli/tsc/dts/lib.deno.unstable.d.ts
- ext/ffi/dlfcn.rs
- ext/ffi/symbol.rs
- ext/ffi/turbocall.rs
- tests/ffi/tests/ffi_types.ts
- tests/ffi/tests/test.js
Closes https://github.com/denoland/deno/issues/22947
This option is no longer needed as fast calls are now allowed to re-enter the isolate
> BREAKING(unstable/ffi): remove callback reentrant flag

- ext/node/polyfills/internal/crypto/keys.ts
As per https://github.com/nodejs/node/pull/46043, this adds Symbol.toStringTag getter to KeyObject.
> fix(ext/node): add Symbol.toStringTag to KeyObject instances

- Cargo.lock
- Cargo.toml
- ext/node/ops/blocklist.rs
- ext/node/ops/crypto/digest.rs
- ext/node/ops/crypto/x509.rs
- ext/node/ops/vm.rs
- ext/node/ops/vm_internal.rs
- ext/node/ops/zlib/mod.rs
- ext/tls/tls_key.rs
- runtime/js/99_main.js
- Symbol.asyncDispose no longer needs to be polyfilled
- assorted updates for cppgc api changes
> feat: upgrade deno_core

- cli/tools/compile.rs
Atomically write `deno compile` output file so we won't get a partially written ELF/PE file, and prevents corrupting running processes.
> fix(compile): atomically write compile output

- cli/ops/jupyter.rs
- cli/tools/jupyter/mod.rs
- cli/tools/jupyter/server.rs
- cli/tools/repl/mod.rs
Moves the ZeroMQ messaging server to a separate thread.
This will allow to run blocking JS code and maintain communication
with the notebook frontend.
Towards https://github.com/denoland/deno/pull/23592
Towards https://github.com/denoland/deno/pull/24250
Closes https://github.com/denoland/deno/issues/23617
> refactor(jupyter): move ZeroMQ server to a separate thread

- ext/crypto/00_crypto.js
- tests/wpt/runner/expectation.json
Updates SubtleCrypto.prototype.deriveBits as per https://github.com/w3c/webcrypto/pull/345
(WPT update in https://github.com/web-platform-tests/wpt/pull/43400)
> feat(ext/crypto): make deriveBits length parameter optional and nullable

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
It's perfectly valid to access `server.address()` before calling `.listen()`. Until a server actively listens on a socket Node will return `null` here, but we threw a "Cannot access property 'port' of undefined" instead.
This was discovered when inspecting failures in Koa's test suite with Deno.
> fix(node/http): don't throw on .address() before .listen()

- cli/args/flags.rs
- cli/args/lockfile.rs
- tests/testdata/lockfile/no_dts/main.cache.out
This commit deprecates `--lock-write` flag by removing it from
the help output and printing a warning message when it's used.
Users should use `--frozen=false` instead which was added
in https://github.com/denoland/deno/pull/24355.
Towards https://github.com/denoland/deno/issues/24167.
> feat: Deprecate --lock-write flag

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/24239
> fix(ext/node): http chunked writes hangs

- cli/Cargo.toml
- cli/build.rs
- cli/js.rs
- runtime/Cargo.toml
- runtime/web_worker.rs
- runtime/worker.rs
Saves some keystrokes and easy to remember
```
cargo b --features hmr
```
> chore: rename `__runtime_js_source` to `hmr`

- ext/node/polyfills/http.ts
Noticed that these private class properties are never used. Maybe a leftover from an earlier implementation.
> chore: remove unused class private properties

- ext/node/polyfills/assert.ts
- tests/integration/node_unit_tests.rs
- tests/unit_node/assert_test.ts
The implementation for `assert.throws()` from `node:assert` didn't work when the expected value was an `Error` constructor. In this case the thrown error should checked if it's an instance of said constructor.
Fixes https://github.com/denoland/deno/issues/24464
> fix(node/assert): throws not checking error instance

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
Implement the missing `.writeHead()` signatures from Node's `ServerResponse` class that we didn't support.
Fixes https://github.com/denoland/deno/issues/24468
> fix(node/http): support all `.writeHead()` signatures

- Cargo.lock
- cli/lsp/resolver.rs
- cli/module_loader.rs
- cli/npm/byonm.rs
- cli/npm/managed/mod.rs
- cli/npm/managed/resolvers/common.rs
- cli/npm/managed/resolvers/global.rs
- cli/npm/managed/resolvers/local.rs
- cli/resolver.rs
- cli/standalone/mod.rs
- cli/tsc/mod.rs
- cli/worker.rs
- ext/fs/interface.rs
- ext/node/Cargo.toml
- ext/node/analyze.rs
- ext/node/errors.rs
- ext/node/lib.rs
- ext/node/ops/require.rs
- ext/node/resolution.rs
- tests/testdata/npm/deno_run_no_bin_entrypoint.out
- tests/testdata/npm/deno_run_no_bin_entrypoint_non_existent_subpath.out
- tests/testdata/npm/imports_package_json/import_not_defined.out
- tests/testdata/npm/imports_package_json/sub_path_import_not_defined.out
This will help clean up some of the code in the CLI because we'll be able to tell how the resolution failed (not part of this PR).
> refactor: use concrete error types for node resolution

- ext/node/global.rs
- ext/web/02_timers.js
- tests/node_compat/test/common/index.js
- tests/unit/globals_test.ts
accessing e.g. `Buffer` in `Mode::Deno` mode should throw, not return undefined.
> fix: do not return undefined for missing global properties

- cli/main.rs
let it bake for a bit before enabling by default
> fix: only use maglev in DENO_FUTURE for now

- cli/npm/managed/resolvers/local.rs
This PR will make vendored dependencies more deterministic. The `node_modules/.deno/.setup-cache.bin` is currently not deterministic because it consists of serialized `HashMap`s which have a random order of elements. By switching them out for `BTreeMap`s, which are sorted in memory, deno generates the same file every time.
According to the Rust documentation `BTreeMap` might provide slightly less performance than `HashMap`, but I wasn't able to reproduce lower performance in deno. I think even for large projects, our maps are way too small for this to have any performance impact.
related issue: #24479
> fix: make .setup-cache.bin in node_modules more reproducible

- cli/tsc/dts/lib.dom.d.ts
- tests/specs/run/dom_extras_dts/__test__.jsonc
- tests/specs/run/dom_extras_dts/deno.json
- tests/specs/run/dom_extras_dts/dom_extras_dts.out
- tests/specs/run/dom_extras_dts/dom_extras_dts.ts
This was changed by mistake in #24326.
Closes https://github.com/denoland/deno/issues/24459.
> fix: restore reference to dom.extras in lib.dom.d.ts

- Cargo.lock
- Cargo.toml
- cli/lsp/config.rs
- cli/schemas/config-file.v1.json
This adds object config for the workspace config:
```json
{
"workspace": {
"members": ["./member-1", "./member-2"]
}
}
```
This is a more verbose version of `"workspace": ["./member-1", "./member-2"]`. Although we don't need it at the moment, it makes the naming of `"workspace"` more clear and leaves the object open for more config in the future.
Closes https://github.com/denoland/deno/issues/24456
> feat(workspace): support object config

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
A request can be destroyed before it was even made in the Node http API. We errored on that.
This issue was discovered in the JSDOM test suite.
> fix(node/http): don't error if request destroyed before send

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
Make sure that already destroyed requests are not actually sent.
This error was discovered in jsdom's test suite.
> fix(node/http): don't send destroyed requests

- ext/node/polyfills/v8.ts
Stubbing a few of Node's `v8` serializer methods makes the `tap` test runner at least start. Previously, it would fail to boot up as some instances of `DefaultSerializer` are constructed eagerly :tada:
Before:
After:
Fixes https://github.com/denoland/deno/issues/24409
> fix(node/v8): stub serializer methods

- ext/node/polyfills/perf_hooks.ts
- tests/unit_node/perf_hooks_test.ts
This PR stubs `perf_hooks.eventLoopUtilization` to make the tests of [hapi](https://github.com/hapijs/hapi) start. Previously, they'd all error because of this function throwing a not implemented error. This brings down the test failures in their suite from 982 to 68 failures.
> fix(node/perf_hooks): stub eventLoopUtilization to make hapi tests work

- cli/npm/managed/resolvers/local.rs
- tests/specs/npm/lifecycle_scripts/all_lifecycles_not_run.out
- tests/specs/npm/lifecycle_scripts/future_install_all_lifecycles_not_run.out
- tests/specs/npm/lifecycle_scripts/node_gyp_not_run.out
Previously when we printed out the packages that skipped install scripts, we didn't prefix them with `npm:`. When you pass `--allow-scripts` though, we require `npm:`, which means you can't just copy paste the package name from the warning message.
> chore: tweak warning message for un-run install scripts

- cli/factory.rs
- cli/lsp/resolver.rs
- cli/lsp/tsc.rs
- cli/npm/byonm.rs
- cli/resolver.rs
- cli/standalone/binary.rs
- cli/standalone/mod.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/mod.rs
- ext/node/resolution.rs
- tests/integration/lsp_tests.rs
- tests/registry/npm/@denotest/cjs-import-dual/1.0.0/index.d.ts
- tests/registry/npm/@denotest/cjs-import-dual/1.0.0/index.js
- tests/registry/npm/@denotest/cjs-import-dual/1.0.0/package.json
- tests/registry/npm/@denotest/dual-cjs-esm/1.0.0/main.d.cts
- tests/registry/npm/@denotest/dual-cjs-esm/1.0.0/main.d.mts
- tests/specs/npm/cjs_import_dual/__test__.jsonc
- tests/specs/npm/cjs_import_dual/check.out
- tests/specs/npm/cjs_import_dual/main.ts
- tests/specs/npm/cjs_import_dual/run.out
> fix(check): CJS types importing dual ESM/CJS package should prefer CJS types

- Cargo.lock
- Cargo.toml
`wgpu-core` version 0.20 was yanked and it caused failure to
publish `deno_webgpu`. I bumped and published locally to
unblock the release.
> build: update wgpu-core to unblock release

- tools/core_import_map.json
This makes the LSP understand `@std/` imports in our tests.
> chore: add std import mapping for tests

- Cargo.lock
- Cargo.toml
- tests/specs/run/workspaces/explicit_import_map/__test__.jsonc
- tests/specs/run/workspaces/explicit_import_map/import_map.json
- tests/specs/run/workspaces/explicit_import_map/main.out
- tests/specs/run/workspaces/explicit_import_map/main.ts
- tests/specs/run/workspaces/explicit_import_map/package.json
This is a temporary fix, which is not perfect - specifying `--import-map`
will break resolution of packages defined in `workspace` setting, but
erroring on `--import-map` currently causes regression in code that
worked fine in v1.44.x.
> fix(workspace): allow using --import-map flag with workspace

- ext/node/resolution.rs
Reverts this change (I'm not sure it causes a bug, but I thought about this in the morning):
https://github.com/denoland/deno/pull/24470/files/18cd4ff3ff5050e18647c781011a2bc3099cab5c..ac3e42eaaecc6cf89300b39c270029da3ecc1e63?diff=split&w=0
Reason is that `e` may contain an invalid package target nested deeply in the returned errors. We should probably add a `.code()` to all errors to make matching easier or make the errors flatter.
> fix(node): revert invalid package target change

- ext/node/ops/blocklist.rs
Ensure that the prefix is properly adjusted when dealing with IPv4 addresses
mapped to IPv6. This fixes inconsistencies in network range calculations for
mapped addresses.
Closes https://github.com/denoland/deno/issues/24525
> fix(ext/node): handle prefix mapping for IPv4-mapped IPv6 addresses

- Cargo.lock
- cli/Cargo.toml
Tests in https://github.com/denoland/deno_graph/pull/504
Closes #24536
> fix: include already seen deps in lockfile dep tracking

- cli/tools/init/mod.rs
This commit fixes the broken link in the sample template provided by the deno init command.
> fix(cli/init): broken link in deno init sample template

- cli/tools/init/mod.rs
- tests/integration/init_tests.rs
- tests/registry/jsr/@std/assert/1.0.0/assert.ts
- tests/registry/jsr/@std/assert/1.0.0/assert_equals.ts
- tests/registry/jsr/@std/assert/1.0.0/fail.ts
- tests/registry/jsr/@std/assert/1.0.0/mod.ts
- tests/registry/jsr/@std/assert/1.0.0_meta.json
- tests/registry/jsr/@std/assert/meta.json
- tests/specs/init/lib/test.out
> fix(init): use bare specifier for `jsr:@std/assert`

- cli/tsc/dts/lib.deno.ns.d.ts
- ext/kv/README.md
- tests/wpt/wpt.ts
Fixing some broken urls found after the docs migration
> fix(docs): fix some deno.land/manual broken urls

- ext/node/ops/http2.rs
- tests/unit_node/http2_test.ts
This PR adds logic to release window capacity after reading the chunks from the stream. Without it, large response (more than `u16::MAX`) may fill up the capacity and the whole response can't be read.
Closes #24552
Closes https://github.com/denoland/deno/issues/24305
> fix(std/http2): Release window capacity back to remote stream

- cli/args/mod.rs
- cli/npm/managed/mod.rs
- cli/npm/managed/resolvers/local.rs
- cli/task_runner.rs
- tests/registry/npm/@denotest/lifecycle-scripts-cjs/1.0.0/package.json
- tests/registry/npm/@denotest/lifecycle-scripts-cjs/1.0.0/preinstall.js
- tests/registry/npm/@denotest/node-lifecycle-scripts/1.0.0/preinstall.js
- tests/specs/npm/lifecycle_scripts/__test__.jsonc
- tests/specs/npm/lifecycle_scripts/no_deno_json.js
- tests/specs/npm/lifecycle_scripts/no_deno_json.out
We would resolve the wrong package.json, resulting in an inability to run CJS (or other node-mode) scripts
> fix(node): Fix `--allow-scripts` with no `deno.json`

- ext/node/polyfills/_http_outgoing.ts
- tests/unit_node/http_test.ts
Closes https://github.com/denoland/deno/issues/24571
> fix(ext/node): http request uploads of subarray of buffer should work

- cli/resolver.rs
- ext/node/errors.rs
- ext/node/package_json.rs
- ext/node/resolution.rs
This makes it easier to tell what kind of error something is (even for deeply nested errors) and will help in the future once we add error codes to the JS errors this returns.
> refactor(node): internally add `.code()` to node resolution errors

- Cargo.lock
- Cargo.toml
- cli/lsp/config.rs
- cli/lsp/resolver.rs
- cli/resolver.rs
- cli/standalone/mod.rs
- cli/tools/registry/unfurl.rs
- cli/tools/vendor/test.rs
- tests/specs/npm/workspace_basic/__test__.jsonc
- tests/specs/npm/workspace_basic/b/main.ts
- tests/specs/npm/workspace_basic/b/main_byonm.out
- tests/specs/npm/workspace_basic/b/main_node_modules_dir.out
- tests/specs/npm/workspace_basic/main.out
- tests/specs/npm/workspace_basic/main.ts
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/__test__.jsonc
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/add/index.js
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/add/package.json
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/package.json
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/publish-subtract.out
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/publish-subtract2.out
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/publish.out
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/subtract-2/deno.json
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/subtract-2/index.ts
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/subtract-2/package.json
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/subtract/deno.json
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/subtract/index.ts
- tests/specs/publish/npm_workspace_jsr_pkg_with_npm_dep/subtract/package.json
This makes bare specifiers for npm packages work when inside a workspace, which emulates the same behaviour as when there's a node_modules directory. The bare specifier can be overwritten by specifying an import map entry or package.json dependency entry.
* https://github.com/denoland/deno_config/pull/88
Closes #24605
> fix(workspace): support resolving bare specifiers to npm pkgs within a workspace

- ext/cron/lib.rs
When a cron name is invalid, it wasn't necessarily clear why. This change-set improves the error message to inform the user of the valid characters in a cron name.
> fix(cron): improve error message for invalid cron names

- ext/node/global.rs
- ext/node/polyfills/worker_threads.ts
- tests/registry/npm/@denotest/globals/1.0.0/index.d.ts
- tests/registry/npm/@denotest/globals/1.0.0/index.js
- tests/testdata/npm/compare_globals/main.out
- tests/testdata/npm/compare_globals/main.ts
This PR hides `self` global in node compat runtime.
closes #23727
> fix(ext/node): do not expose `self` global in node

- .dprint.json
- Cargo.lock
- cli/Cargo.toml
* https://github.com/dprint/dprint-plugin-typescript/pull/651
> fix(fmt): was sometimes putting comments in front of commas in parameter lists

- cli/npm/managed/resolvers/local.rs
- cli/task_runner.rs
- tests/specs/npm/lifecycle_scripts/__test__.jsonc
- tests/specs/task/byonm/__test__.jsonc
Regression from https://github.com/denoland/deno/commit/04f9db5b2217fe06f88e76146aac6362ff0b0b86
Originally I thought to fix the issue in the PR we needed to explicitly pass through the `node-modules-dir` flag, but after applying the correct fix that david pointed out (setting `NPM_PROCESS_STATE`) that wasn't necessary (or correct).
We had a test for deno task with BYONM, but it only tested with `"unstable": ["byonm"]` in deno.json, so it didn't catch this.
> fix(cli): Respect implied BYONM from DENO_FUTURE in `deno task`

- cli/lsp/language_server.rs
> fix(lsp): hang when caching failed

- Cargo.lock
- Cargo.toml
This PR will bump the deno_cache_dir dependency from 0.10.0 to 0.10.2. This will make the cache manifest at manifest.json more deterministic (see denoland/deno_cache_dir#53 )
> fix: make vendor cache manifest more deterministic

- Cargo.lock
- Cargo.toml
- cli/module_loader.rs
- cli/standalone/mod.rs
- cli/worker.rs
- runtime/web_worker.rs
- runtime/worker.rs
- tests/integration/compile_tests.rs
This reverts commit 6c5905dbc354ae701f06c734608af834a0ba844c.
Reverting because of errors like this in CI:
```
#
#
#
#
#FailureMessage Object: 0x7fd5b3ffd9d0
==== C stack trace ===============================
/home/runner/work/deno/deno/target/release/deps/url_ops-e4068c650cedb9fa(+0x1111883) [0x55b8d2107883]
/home/runner/work/deno/deno/target/release/deps/url_ops-e4068c650cedb9fa(+0x1110b6b) [0x55b8d2106b6b]
/home/runner/work/deno/deno/target/release/deps/url_ops-e4068c650cedb9fa(+0x110c6f9) [0x55b8d21026f9]
/home/runner/work/deno/deno/target/release/deps/url_ops-e4068c650cedb9fa(+0x20413cd) [0x55b8d30373cd]
/home/runner/work/deno/deno/target/release/deps/url_ops-e4068c650cedb9fa(+0x2034222) [0x55b8d302a222]
/home/runner/work/deno/deno/target/release/deps/url_ops-e4068c650cedb9fa(+0x202ff …
```
> Revert "fix: CFunctionInfo and CTypeInfo leaks (#24634)"

- cli/lsp/documents.rs
- cli/tsc/99_main_compiler.js
- tests/integration/lsp_tests.rs
Fixes #24608.
Fixes https://github.com/denoland/vscode_deno/issues/1134.
> fix(lsp): scope attribution for asset documents

- cli/tools/registry/diagnostics.rs
- cli/tools/registry/mod.rs
- tests/integration/publish_tests.rs
- tests/specs/jsr/no_unused_params/publish.out
- tests/specs/publish/bare_node_builtins/bare_node_builtins.out
- tests/specs/publish/bare_node_builtins/no_warnings.out
- tests/specs/publish/byonm_dep/deno.jsonc
- tests/specs/publish/byonm_dep/publish.out
- tests/specs/publish/excluded_deno_jsonc/mod.out
- tests/specs/publish/missing_license/__test__.jsonc
- tests/specs/publish/missing_license/deno.json
- tests/specs/publish/missing_license/mod.out
- tests/specs/publish/missing_license/mod.ts
- tests/specs/publish/npm_workspace/publish.out
Part of https://github.com/denoland/deno/issues/24676 , but just a warning for now.
> fix(publish): warn about missing license file

- Cargo.lock
- ext/fetch/Cargo.toml
- ext/fetch/lib.rs
- ext/fetch/proxy.rs
- ext/fetch/tests.rs
Sending ALPN to a proxy, and then when tunneling, requires better juggling of TLS configs. This improves the choice of TLS config in the proxy connector, based on what reqwest does. It also includes some `ext/fetch/tests.rs` that check the different combinations.
Fixes #24632
Fixes #24691
> fix(ext/fetch): use correct ALPN to proxies

- Cargo.lock
- ext/fetch/Cargo.toml
- ext/fetch/lib.rs
- ext/fetch/proxy.rs
- ext/node/ops/http.rs
- tests/unit/fetch_test.ts
This commit fixes handling of "authority" in the URL by properly
sending "Authorization Basic..." header in `fetch` API.
This is a regression from https://github.com/denoland/deno/pull/24593
Fixes https://github.com/denoland/deno/issues/24697
CC @seanmonstar
> fix(ext/fetch): respect authority from URL

- Cargo.lock
- Cargo.toml
- tests/integration/test_tests.rs
Fixes percent-encoded filenames in stack traces:
- https://github.com/denoland/deno_core/pull/759
Closes #18983
> fix: upgrade deno_core to 0.298.0

- cli/tools/registry/mod.rs
- cli/tools/registry/paths.rs
- cli/tools/registry/tar.rs
- tests/specs/publish/workspace/__test__.jsonc
- tests/specs/publish/workspace/foo_dry_run.out
- tests/specs/publish/workspace/workspace_dry_run.out
This includes the license file from the workspace root in the package if the package doesn't have a license file.
This is to support scenarios like deno_std.
> fix(workspaces/publish): include the license file from the workspace root if not in pkg

- .github/workflows/wpt_epoch.yml
This was missed in the previous `std` updates.
> chore: fix WPT epoch

- Cargo.lock
- Cargo.toml
- cli/util/sync/mod.rs
- runtime/fmt_errors.rs
Adds support for `npm:bindings` and `npm:callsites` packages because of changes in
https://github.com/denoland/deno_core/pull/838.
This `deno_core` bump causes us to stop prepending `file://` scheme for locations
in stack traces that are for local files.
Fixes https://github.com/denoland/deno/issues/24462 , fixes https://github.com/denoland/deno/issues/22671 , fixes https://github.com/denoland/deno/issues/15717 , fixes https://github.com/denoland/deno/issues/19130 , fixes https://github.com/WiseLibs/better-sqlite3/issues/1205 , fixes https://github.com/WiseLibs/better-sqlite3/issues/1034 , fixes https://github.com/denoland/deno/issues/20936
> fix: support `npm:bindings` and `npm:callsites` packages

- cli/tools/registry/mod.rs
- cli/tools/registry/paths.rs
- cli/tools/registry/tar.rs
- tests/testdata/publish/successful_provenance.out
Also fixes the issue where we say a package was successfully published before it wasn't.
Bug in https://github.com/denoland/deno/pull/24714
> fix(publish): workspace included license file had incorrect path

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/ops/jupyter.rs
- cli/tools/jupyter/mod.rs
- cli/tools/jupyter/server.rs
- tests/integration/jupyter_tests.rs
> fix: adapt to new jupyter runtime API and include session IDs

- cli/args/mod.rs
Not sure how we can write a test for this. I just did one manually:
```
$ deno run test.ts
error: Error loading .npmrc at /home/david/.npmrc. Permission denied (os error 13)
$ ./target/debug/deno --log-level=debug run test.ts
DEBUG RS - deno::args:597 - Skipping .npmrc in home directory due to permission denied error. Error loading .npmrc at /home/david/.npmrc.
DEBUG RS - deno::args:608 - No .npmrc file found
DEBUG RS - deno::args:893 - Finished config loading.
DEBUG RS - deno::cache::cache_db:168 - Opening cache /home/david/.cache/deno/dep_analysis_cache_v2...
DEBUG RS - deno::cache::cache_db:168 - Opening cache /home/david/.cache/deno/node_analysis_cache_v2...
DEBUG RS - deno::cache::cache_db:168 - Opening cache /home/david/.cache/deno/v8_code_cache_v2...
DEBUG RS - deno::js:10 - Deno …
```
> fix(npmrc): skip loading .npmrc in home dir on permission error

- cli/tsc/dts/lib.dom.d.ts
- cli/tsc/dts/lib.webworker.d.ts
- ext/web/lib.deno_web.d.ts
Fix #24738
Related https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1759#discussion_r1687081249
> fix(types): fix streams types

- ext/node/ops/http2.rs
- tests/unit_node/http2_test.ts
Closes https://github.com/denoland/deno/issues/24678
> fix(ext/node): prevent panic in http2.connect with uppercase header names

- tests/integration/upgrade_tests.rs
> chore: mark upgrade invalid lockfile as flaky

- cli/args/flags.rs
Fixes #24753
The help text for `deno publish` was marked hidden while in preview. This is no longer a preview feature.
> fix(cli): Unhide publish subcommand help string

- Cargo.lock
- cli/args/mod.rs
- ext/node/Cargo.toml
- ext/node/benchmarks/child_process_ipc.mjs
- ext/node/lib.rs
- ext/node/ops/ipc.rs
- ext/node/ops/vm.rs
- ext/node/polyfills/child_process.ts
- ext/node/polyfills/internal/child_process.ts
- runtime/ops/process.rs
- tests/node_compat/runner.ts
- tests/unit_node/child_process_test.ts
Fixes https://github.com/denoland/deno/issues/24756. Fixes https://github.com/denoland/deno/issues/24796.
This also gets vitest working when using [`--pool=forks`](https://vitest.dev/guide/improving-performance#pool) (which is the default as of vitest 2.0). Ref https://github.com/denoland/deno/issues/23882.
---
This PR resolves a handful of issues with child_process IPC. In particular:
- We didn't support sending typed array views over IPC
- Opening an IPC channel resulted in the event loop never exiting
- Sending a `null` over IPC would terminate the channel
- There was some UB in the read implementation (transmuting an `&[u8]` to `&mut [u8]`)
- The `send` method wasn't returning anything, so there was no way to signal backpressure (this also resulted in the benchmark …
> fix(node): Rework node:child_process IPC

- ext/node/polyfills/timers/promises.ts
- tests/unit_node/timers_test.ts
This PR adds the experimental `scheduler` APIs in Node's `timers/promises` module. See https://nodejs.org/api/timers.html#timerspromisesschedulerwaitdelay-options
Fixes https://github.com/denoland/deno/issues/24800
> fix(node/timers/promises): add scheduler APIs

- ext/node/polyfills/_fs/_fs_watch.ts
- tests/unit_node/_fs/_fs_watch_test.ts
The way `fs.watch` works is different in `node:fs/promises` than `node:fs`. It has a different function signature and it returns an async iterable instead, see https://nodejs.org/api/fs.html#fspromiseswatchfilename-options
Fixes https://github.com/denoland/deno/issues/24661
> fix(node/fs/promises): watch should be async iterable

- ext/fetch/22_body.js
```
Running 10s test @ http://localhost:8000
Latency   123.96us   57.25us   3.64ms   96.84%
Req/Sec    41.15k     2.11k   42.76k    95.05%
827087 requests in 10.10s, 125.41MB read
Requests/sec:  81895.64
Transfer/sec:     12.42MB
```
```
Running 10s test @ http://localhost:8000
Latency    66.91us   17.71us   2.03ms   95.91%
Req/Sec    74.43k     2.52k   76.71k    92.57%
1496402 requests in 10.10s, 199.79MB read
Requests/sec: 148170.16
Transfer/sec:     19.78MB
```
Fixes #24766
> perf(ext/fetch): speed up `resp.clone()`

- .dprint.json
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/args/mod.rs
- cli/lsp/code_lens.rs
- cli/lsp/testing/collectors.rs
- cli/tools/compile.rs
- cli/tools/repl/session.rs
Some perf gains in swc (I measured formatting and it was slightly faster).
Includes:
* https://github.com/denoland/deno_graph/pull/508
* https://github.com/denoland/eszip/pull/193
> perf: update deno_ast to 0.41

- Cargo.lock
- Cargo.toml
- ext/fetch/Cargo.toml
- ext/fetch/proxy.rs
- ext/fetch/tests.rs
> fix(ext/fetch): use correct ALPN to socks5 proxies

- Cargo.lock
- Cargo.toml
- cli/module_loader.rs
- cli/standalone/mod.rs
- ext/node/global.rs
- ext/node/lib.rs
- ext/node/ops/vm_internal.rs
- ext/node/polyfills/01_require.js
- ext/node_resolver/resolution.rs
- ext/node_resolver/sync.rs
- tests/node_compat/test/common/index.js
- tests/testdata/run/worker_close_in_wasm_reactions.js.out
- tests/unit/console_test.ts
- upgrade to v8 12.8
- optimizes DataView bigint methods
- fixes global interceptors
- includes CPED methods for ALS
- fix global resolution
- makes global resolution consistent using host_defined_options. originally a separate patch but due to the global interceptor bug it needs to be included in this pr for all tests to pass.
> feat: upgrade V8 to 12.8

- cli/standalone/binary.rs
- tests/integration/compile_tests.rs
> fix(compile): adhoc codesign mach-o by default

- ext/http/00_serve.ts
- tests/unit/serve_test.ts
Prior to this commit, you could return a `Response` created from a string or Uint8Array multiple times.
Now you can't do that anymore.
> fix(ext/http): correctly consume response body in `Deno.serve`

- ext/http/response_body.rs
- ext/http/service.rs
I noticed [`set_response_body`](https://github.com/nathanwhit/deno/blob/ce42f82b5a985e5f1482dff97a7268019a8e79ea/ext/http/service.rs#L439-L443) was unexpectedly hot in profiles, with most of the time being spent in `memmove`.
It turns out that `ResponseBytesInner` was _massive_ (5624 bytes), so every time we moved a `ResponseBytesInner` (for instance in `set_response_body`) we were doing a >5kb memmove, which adds up pretty quickly.
This PR boxes the two larger variants (the compression streams), shrinking `ResponseBytesInner` to a reasonable 48 bytes.
---
Benchmarked with a simple hello world server:
```ts
// hello-server.ts
Deno.serve((_req) => {
return new Response("Hello world");
});
// run with `deno run -A hello-server.ts`
// in separate terminal `wrk -d 10s http://127.0.0.1:8000` …
```
> perf(ext/http): Reduce size of `ResponseBytesInner`

- cli/tsc/dts/lib.deno.unstable.d.ts
- runtime/js/99_main.js
At the TC39 meeting on 2024-06, [it was decided to obsolete several Temporal APIs](https://github.com/tc39/notes/blob/main/meetings/2024-06/june-12.md#temporal-stage-3-update-and-scope-reduction). I have disabled those APIs that had already been removed from the specification.
Ref https://github.com/tc39/proposal-temporal/pull/2895, https://github.com/tc39/proposal-temporal/pull/2914
`Temporal.TimeZone` and `Temporal.Calendar` are also obsoleted, so I will remove them as well when they are removed from the specification.
Ref https://github.com/tc39/proposal-temporal/pull/2925
> BREAKING(temporal/unstable): Remove obsoleted Temporal APIs

- cli/args/flags.rs
- tests/specs/test/no_files/__test__.jsonc
- tests/specs/test/no_files/allow_none.out
- tests/specs/test/no_files/error.out
- tests/specs/test/no_files/permit_no_files.out
> feat(test): rename --allow-none to --permit-no-files

- cli/args/flags.rs
- cli/args/mod.rs
- cli/lsp/language_server.rs
- cli/tools/fmt.rs
- tests/integration/fmt_tests.rs
- tests/integration/upgrade_tests.rs
- tests/specs/fmt/unstable_yaml/__test__.jsonc
- tests/specs/fmt/unstable_yaml/badly_formatted.yml
This moves YAML formatting behind an unstable flag for Deno 1.46. This will make it opt-in to start and then we can remove the flag to make it on by default in version of Deno after that.
This can be specified by doing `deno fmt --unstable-yaml` or by specifying the following in a deno.json file:
```json
{
"unstable": ["fmt-yaml"]
}
```
cc @g-plane - It would be good to do the same for other languages.
Part of #12217
> feat(unstable/fmt): move yaml formatting behind unstable flag

- cli/factory.rs
Not bothering to add a test for this because we're going to change this to be the default in a couple weeks.
> fix(unstable): panic when running deno install with DENO_FUTURE=1

- ext/node/ops/ipc.rs
We were serializing `{ a: undefined }` to `{ a: null }` instead of `{}`
> fix(node): Fix node IPC serialization for objects with undefined values

- cli/tsc/dts/lib.deno.ns.d.ts
- tests/specs/serve/type_check/__test__.jsonc
- tests/specs/serve/type_check/main.out
- tests/specs/serve/type_check/main.ts
- tests/specs/serve/type_check2/__test__.jsonc
- tests/specs/serve/type_check2/main.out
- tests/specs/serve/type_check2/main.ts
Closes https://github.com/denoland/deno/issues/23725
> feat: Add Deno.ServeDefaultExport type

- cli/lsp/config.rs
Stop adding fallback config scopes for workspace folders that don't have a `deno.json[c]` or `package.json`. These were necessary to pass tests while the scopes work was in progress, not anymore.
We still create scopes for workspace folders with settings like `deno.config` and `deno.importMap`.
> perf(lsp): remove fallback config scopes for workspace folders

- ext/web/08_text_encoding.js
- ext/web/lib.rs
Fixes https://github.com/denoland/deno/issues/24878
> fix(ext/web): make TextDecoderResource use cppgc

- cli/args/flags.rs
- cli/main.rs
- cli/standalone/mod.rs
- cli/tools/task.rs
- tests/specs/run/run_task/__test__.jsonc
- tests/specs/run/run_task/deno.json
- tests/specs/run/run_task/main.out
- tests/specs/run/run_task/main.ts
- tests/specs/run/run_task/not_found.out
This PR updates `deno run` to fallback to executing tasks when there is no script with the specified name. If there are both script and a task with the same name then `deno run` will prioritise executing the script.
> feat: deno run <task>

- cli/lsp/completions.rs
- tests/integration/lsp_tests.rs
> feat(lsp): node specifier completions

- cli/tools/upgrade.rs
Additionally some renames in preparation to support "LTS" and "RC" channels.
> refactor(upgrade): make fetching latest version async

- cli/tsc/dts/lib.deno.ns.d.ts
- ext/node/polyfills/_fs/_fs_watch.ts
- runtime/ops/fs_events.rs
- tests/unit/fs_events_test.ts
This PR ensures that we forward a `rename` event in our file watcher. The rust lib we use combines that with the `modify` event.
This fixes a compatibility issue with Node too, which sends the `rename` event as well.
Fixes https://github.com/denoland/deno/issues/24880
> fix: `rename` watch event missing

- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/standalone/binary.rs
- cli/tools/upgrade.rs
- cli/util/archive.rs
- cli/util/mod.rs
Use the `zip` crate instead
Fixes #23988.
> fix: Don't shell out to `unzip` in deno upgrade/compile

- ext/node/polyfills/internal/crypto/keygen.ts
Because public/private key are reassigned, they should be `let` instead of `const`.
```ts
const privateKey = new PrivateKeyObject(privateKeyHandle);  // <- Const here
const publicKey = new PublicKeyObject(publicKeyHandle); // <- Const here
if (typeof options === "object" && options !== null) {
const { publicKeyEncoding, privateKeyEncoding } = options as any;
if (publicKeyEncoding) {
publicKey = publicKey.export(publicKeyEncoding); // <- Reassigned here
}
if (privateKeyEncoding) {
privateKey = privateKey.export(privateKeyEncoding);  // <- Reassigned here
}
}
```
This gives an error:
`ERROR  Assignment to constant variable.`
Related to
- #23471
> fix(node/crypto): Assign publicKey and privateKey with let instead of const

- ext/node/polyfills/util.ts
- tests/unit_node/util_test.ts
Add the missing `node:util.debug` export which is an alias of `node:util.debuglog`, see https://nodejs.org/api/util.html#utildebugsection
> fix(node/util): add missing `debug` alias of `debuglog`

- Cargo.lock
- cli/Cargo.toml
Test and code change in deno_graph.
* https://github.com/denoland/deno_graph/pull/511
Closes https://github.com/denoland/deno/issues/23965
> fix: cache bust jsr meta file when version not found in dynamic branches

- cli/args/flags.rs
This commit adds short CLI flags for following permission flags:
- "-R" for "--allow-read"
- "-W" for "--allow-write"
- "-E" for "--allow-env"
- "-N" for "--allow-net"
- "-S" for "--allow-sys"
> feat: support short flags for permissions

- cli/args/flags.rs
- cli/args/mod.rs
- tests/testdata/eval/env_file_missing.out
- tests/testdata/run/env_file_missing.out
Closes #24528, see comment [here](https://github.com/denoland/deno/pull/24166#issuecomment-2221817406) on Deno 2
- https://github.com/denoland/deno/issues/24528
This pr rename --env to --env-file for several reasons (see issue), but allow --env to keep working as an alias.
I've added 2 unit tests to make sure both --env and --env-file work
> feat(cli): Add --env-file as alternative to --env

- cli/args/flags.rs
removes the necessity for the `run` subcommand to run scripts
fixes #24493
> feat: treat bare deno command with run arguments as deno run 

- cli/tools/init/mod.rs
This moves all package-specific object keys right next to each other.
> chore: change property order in generated `deno.json`

- cli/npm/mod.rs
- tests/specs/add/dist_tag/__test__.jsonc
- tests/specs/install/future_install_add_dist_tag/__test__.jsonc
- tests/specs/install/future_install_add_dist_tag/install.out
> fix(add): Support dist tags in deno add

- ext/node/polyfills/_http_outgoing.ts
For dd-trace tests to succeed, `OutgoingMessage` should be a function instead of a class.
> chore: make node:http.OutgoingMessage a function

- ext/node/polyfills/01_require.js
- tests/unit_node/module_test.ts
This is commonly used to register loading non standard file types. But some libs also register TS loaders which Deno supports natively, like the npm `payload` package. This PR unblocks those.
Fixes https://github.com/denoland/deno/issues/24902
> fix: stub `node:module.register()`

- cli/npm/managed/resolvers/local.rs
- tests/specs/install/future_install_node_modules_tag/__test__.jsonc
- tests/specs/install/future_install_node_modules_tag/install.out
- tests/specs/install/future_install_node_modules_tag/package.json
Fixes https://github.com/denoland/deno/issues/24966.
Fixes https://github.com/denoland/deno/issues/24932.
> fix(install): Properly handle dist tags when setting up node_modules

- cli/main.rs
- cli/tools/installer.rs
- cli/tools/registry/mod.rs
- cli/tools/registry/pm.rs
- tests/specs/add/missing_npm_specifier/__test__.jsonc
> fix(add): Better error message when missing npm specifier

- Cargo.lock
- ext/node/Cargo.toml
- ext/node/ops/crypto/mod.rs
- ext/node/ops/crypto/sign.rs
- ext/node/polyfills/internal/crypto/sig.ts
- tests/unit_node/crypto/crypto_sign_test.ts
Fixes https://github.com/denoland/deno/issues/22919
> fix(ext/node): support ieee-p1363 ECDSA signatures and pss salt len

- cli/lsp/completions.rs
- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
Fixes #24592.
On this line: https://github.com/denoland/deno/blob/v1.45.5/cli/lsp/documents.rs#L1467, the `referrer` won't yield the correct file referrer [later](https://github.com/denoland/deno/blob/v1.45.5/cli/lsp/documents.rs#L1185) if it's a remote specifier which isn't directly the key to a document. Passing around `file_referrer` is the intended solution anyway and seems to work. I don't know how to reproduce this for a test.
> fix(lsp): directly use file referrer when loading document

- runtime/ops/tty.rs
> fix(runtime/windows): fix calculation of console size

- cli/tools/upgrade.rs
Supersedes https://github.com/denoland/deno/pull/25012
This commit fixes errors on CI like this:
```
---- upgrade::upgrade_prompt stdout ----
command /home/runner/work/deno/deno/target/release/deno run --log-level=debug main.js
command cwd /tmp/deno-cli-testqDw5UR
command /home/runner/work/deno/deno/target/release/deno run --log-level=debug main.js
command cwd /tmp/deno-cli-testqDw5UR
------ Start Full Text ------
"DEBUG RS - deno::args:620 - No .npmrc file found\r\nDEBUG RS - deno::args:909 - Finished config loading.\r\nDEBUG RS - deno::cache::cache_db:168 - Opening cache /tmp/deno-cli-testMKnYXP/dep_analysis_cache_v2...\r\nDEBUG RS - deno::cache::cache_db:168 - Opening cache /tmp/deno-cli-testMKnYXP/node_analysis_cache_v2...\r\nDEBUG RS - deno::cache::cache_db:168 - Opening cache …
```
> fix(upgrade): return no RC versions if fetching fails

- cli/tools/registry/diagnostics.rs
- tests/integration/publish_tests.rs
- tests/specs/publish/missing_license/__test__.jsonc
- tests/specs/publish/missing_license/mod.out
Closes https://github.com/denoland/deno/issues/24676
> feat(publish): error on missing license file

- cli/args/mod.rs
This commit changes how system certificates are loaded on startup.
Instead of hard erroring if a certificate can't be decoded, we are now
printing a warning and bumping a hex representation of the certificate
and continue execution.
Ref https://github.com/denoland/deno/issues/24137
> fix(tls): print a warning if a system certificate can't be loaded

- ext/node/polyfills/http.ts
make this http incoming constructor match with node, and also handle arbitrary duplex inputs
> fix: dd-trace http message compat

- ext/node/polyfills/perf_hooks.ts
> fix(ext/node): don't throw when calling PerformanceObserver.observe

- ext/node/polyfills/inspector.ts
- tests/unit_node/inspector_test.ts
There is no constructor code when creating an inspector `Session` instance in Node. Also get rid of some symbols which should've been private properties. This PR doesn't yet add any new implementations though as these are mostly cosmetic changes.
> fix(node/inspector): Session constructor should not throw

- ext/node/polyfills/_fs/_fs_common.ts
- ext/node/polyfills/_fs/_fs_read.ts
- ext/node/polyfills/_fs/_fs_write.mjs
- ext/node/polyfills/internal/fs/utils.mjs
- tests/unit_node/_fs/_fs_read_test.ts
- tests/unit_node/_fs/_fs_write_test.ts
Part of #25028.
Our underlying read/write operations in `io` assume the buffer is a Uint8Array, but we were passing in other typed arrays (in the case above it was `Int8Array`).
> fix(node/fs): node:fs.read and write should accept typed arrays other than Uint8Array

- Cargo.lock
- cli/Cargo.toml
- cli/args/flags.rs
- cli/args/mod.rs
- cli/lsp/language_server.rs
- cli/tools/fmt.rs
- tests/integration/fmt_tests.rs
- tests/specs/fmt/unstable_component/__test__.jsonc
- tests/specs/fmt/unstable_component/badly_formatted.svelte
- tests/specs/fmt/unstable_html/__test__.jsonc
- tests/specs/fmt/unstable_html/badly_formatted.html
- tests/testdata/fmt/badly_formatted.html
- tests/testdata/fmt/badly_formatted.md
- tests/testdata/fmt/badly_formatted.svelte
- tests/testdata/fmt/badly_formatted_fixed.html
- tests/testdata/fmt/badly_formatted_fixed.md
- tests/testdata/fmt/badly_formatted_fixed.svelte
Initially this is a draft PR because there're pending optimizations from markup_fmt. Once I publish a new version of markup_fmt, I will update PR status. While in draft, this PR still can be reviewed.
Close #25015
> feat(fmt): support HTML, Svelte, Vue, Astro and Angular

- cli/lsp/analysis.rs
- tests/integration/lsp_tests.rs
- tests/registry/jsr/@std/url/0.220.1/join.ts
- tests/registry/jsr/@std/url/0.220.1/normalize.ts
Fixes bug reported by @lucacasonato.
> fix(lsp): import map lookup for jsr subpath auto import

- Cargo.lock
- cli/Cargo.toml
- cli/tools/lint/linter.rs
- tests/specs/lint/node_globals_no_duplicate_imports/__test__.jsonc
- tests/specs/lint/node_globals_no_duplicate_imports/error.out
- tests/specs/lint/node_globals_no_duplicate_imports/lint.out
- tests/specs/lint/node_globals_no_duplicate_imports/main.ts
From upgrading `deno_lint`.
Previously if you had a node project that used a bunch of node globals (`process.env`, etc), you would have to fix the errors by hand. This PR includes a new lint that detects usages of node globals (`process`, `setImmediate`, `Buffer`, etc.) and provides an autofix to import the correct value. For instance:
```ts
// main.ts
const _foo = process.env.FOO;
```
`deno lint` gives you
```ts
error[no-node-globals]: NodeJS globals are not available in Deno
--> /home/foo.ts:1:14
|
1 | const _foo = process.env.FOO;
|              ^^^^^^^
= hint: Add `import process from "node:process";`
docs: https://lint.deno.land/rules/no-node-globals
Found 1 problem (1 fixable via --fix)
Checked 1 file
```
And `deno lint --fix` adds the import for you:
```ts
// main.ts
import process …
```
> feat(lint): Add lint for usage of node globals (with autofix)

- ext/node/polyfills/_fs/_fs_read.ts
- ext/node/polyfills/internal/fs/utils.mjs
- tests/unit_node/_fs/_fs_handle_test.ts
- tests/unit_node/_fs/_fs_read_test.ts
- tests/unit_node/_fs/_fs_write_test.ts
My fix in #25030 was buggy, I forgot to pass the `byteOffset` and `byteLength`. Whoops.
I also discovered that fs.read was not respecting the `offset` argument, and we were constructing a new `Buffer` for the callback instead of just passing the original one (which is what node does, and the @types/node definitions also indicate the callback should get the same type).
Fixes #25028.
> fix(node/fs): Use correct offset and length in node:fs.read and write

- cli/args/flags.rs
- cli/shared.rs
- cli/tools/upgrade.rs
- cli/version.rs
Also simplifies handling of various release channels in `deno upgrade` subcommand.
> refactor: show release channel in `deno --version`

- .github/workflows/promote_to_rc.yml
- cli/tools/upgrade.rs
- tools/deno.lock.json
- tools/release/promote_to_rc.ts
This commits add a CI script that allows to promote a certain
canary build to a "Release Candidate" release.
This is done using `libsui` and `patchver` utilities.
> ci: add script to promote to RC release

- ext/node/global.rs
- tests/registry/npm/@denotest/check-worker-globals/1.0.0/index.js
- tests/registry/npm/@denotest/check-worker-globals/1.0.0/package.json
- tests/specs/npm/workers/main.out
- tests/specs/npm/workers/main.ts
- tests/specs/npm/workers/worker4.ts
PrismJS uses `WorkerGlobalScope` and `self` for detecting browser's Web Worker context:
https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/prism.js#L11
Now the detection logic above is broken when it's imported from Deno's Web Worker context because we only hide `self` (Prism assumes when `WorkerGlobalScope` is available, `self` is also available).
This PR fixes the above by also hiding `WorkerGlobalScope` global in Node compat mode.
closes #25008
> fix(ext/node): fix prismjs compatibiliy in Web Worker

- ext/node/polyfills/http.ts
- tests/unit_node/http_test.ts
This PR addresses a regression introduced in https://github.com/denoland/deno/pull/25021 that would cause the `req.url` parameter in Node's http server to always be a single character instead of the expected value. The regression was caused by effectively calling `.indexOf()` on an empty string and thus passing the wrong index for slicing.
```js
"".indexOf("/") // -> -1
request.url.slice(-1) // effectively only giving us the last character
```
Fixes https://github.com/denoland/deno/issues/25080
> fix(node/http): wrong `req.url` value

- cli/tools/registry/pm.rs
Will fix some flaky tests.
```
---- specs::remove::basic ----
command /Users/runner/work/deno/deno/target/debug/deno add @std/assert @std/http
command cwd /var/folders/cy/09t6wxdj6qn64c5q9_kr6czr0000gn/T/deno-cli-testKwb00C
output path /Users/runner/work/deno/deno/tests/specs/remove/basic/add.out
-- OUTPUT START --
Created deno.json configuration file.
Add jsr:@std/http@1.0.0
Add jsr:@std/assert@1.0.0
Download http://127.0.0.1:4250/@std/http/1.0.0_meta.json
Download http://127.0.0.1:4250/@std/assert/1.0.0_meta.json
Download http://127.0.0.1:4250/@std/http/1.0.0/mod.ts
Download http://127.0.0.1:4250/@std/assert/1.0.0/mod.ts
Download http://127.0.0.1:4250/@std/assert/1.0.0/assert_equals.ts
Download http://127.0.0.1:4250/@std/assert/1.0.0/assert.ts
Download …
```
> fix: make `deno add` output more deterministic

- cli/tools/upgrade.rs
This PR addresses a suggestion in issue #21417
**Changes**
Logged out current version when using deno upgrade.
> fix: log current version when using deno upgrade

- cli/tools/upgrade.rs
This commit fixes computation of the latest available version
by taking into account which release channel the current
binary is on.
Before this commit, if user was on "RC" channel, calling
`deno upgrade` would not switch back to the "stable"
channel.
> fix(upgrade): correctly compute latest version based on current release channel

- cli/schemas/config-file.v1.json
This has been considered stable for some time now.
https://docs.deno.com/runtime/manual/basics/vendoring/
> fix: correct JSON config schema to show vendor option as stable

- cli/tools/upgrade.rs
This commit fixes scenarios like:
```
$ deno upgrade --version=v1.46.0-rc.0
Downloading https://github.com/denoland/deno/releases/download/v1.46.0-rc.0/deno-aarch64-apple-darwin.zip
Download could not be found, aborting
```
Now:
```
$ target/debug/deno upgrade --version=v1.46.0-rc.0
Downloading https://dl.deno.land/release/v1.46.0-rc.0/deno-aarch64-apple-darwin.zip
Deno is upgrading to version 1.46.0-rc.0
Upgraded successfully to Deno v1.46.0-rc.0
```
Also some unneeded code was removed.
> fix(upgrade): support RC release with --version flag

- cli/args/flags.rs
- cli/tools/upgrade.rs
This commit changes `deno upgrade` subcommand to accept
a positional argument that can be either a version, release channel
name or a git hash, making invocations of `deno upgrade` much
more concise:
```
$ deno upgrade --version 1.46.0
$ deno upgrade 1.46.0
```
```
$ deno upgrade --canary
$ deno upgrade canary
```
```
$ deno upgrade --canary --version f042c39180c1b345de8e7b5f0dfae5d0a49b161f
$ deno upgrade f042c39180c1b345de8e7b5f0dfae5d0a49b161f
```
Old flags are still supported, but hidden from the help output.
> feat(upgrade): support `deno upgrade 1.46.0`

- ext/node/polyfills/tty.js
- tests/unit_node/tty_test.ts
The check in `tty.WriteStream.prototype.hasColors()` was incorrect leading to the [`yoctocolors`](https://github.com/sindresorhus/yoctocolors) package not printing any colors.
Fixes https://github.com/denoland/deno/issues/24407
> fix(node/tty): fix `tty.WriteStream.hasColor` with different args

- ext/fs/lib.rs
- tests/unit/os_test.ts
fix https://github.com/denoland/deno/issues/25055
> fix: add permission name when accessing a special file errors

- cli/args/flags.rs
- cli/args/lockfile.rs
- cli/lsp/config.rs
- cli/schemas/config-file.v1.json
- cli/tools/installer.rs
- tests/specs/lockfile/frozen_lockfile/__test__.jsonc
> feat(config): Support frozen lockfile config option in deno.json

- ext/node/polyfills/internal/child_process.ts
Missed removing it before committing
> chore: Remove stray `console.error` log in `node:child_process`

- Cargo.lock
- Cargo.toml
v4 is a somewhat lossy format and so we can't actually work with v3 by upgrading to v4 and then downgrading.
* https://github.com/denoland/deno_lockfile/pull/34
> fix: deserialize lockfile v3 straight

- Cargo.lock
- cli/Cargo.toml
- cli/args/flags.rs
- cli/main.rs
- cli/tools/task.rs
- rewrite flag help
- use gray for indentation
- reorganize permission flags and split them up
- make help subcommand act like help flag
- `deno run` outputs list of tasks
- Fixes #25120
error handling for `deno run` in case of no config file being found needs to be improved
> feat(flags): improve help output and make `deno run` list tasks

- ext/node/polyfills/http2.ts
> fix(ext/node): http2session ready state

- cli/auth_tokens.rs
> fix: trim space around DENO_AUTH_TOKENS

- ext/node/Cargo.toml
This commit bumps the minimum required version of `dsa` crate to 0.6.3. This is preferable because `SigningKey::sign_prehashed_rfc6979` function we use in `deno_node` is available from this version.
https://github.com/denoland/deno/blob/e7026c5ee8ac6780391b2169e338ca5fb5bbac70/ext/node/ops/crypto/sign.rs#L127-L138
Ref: [dsa's CHANGELOG.md](https://github.com/RustCrypto/signatures/blob/132b04631409db1ca805aba2f62830c8e359b29f/dsa/CHANGELOG.md#063-2024-01-28)
> chore(ext/node): bump minimum required version of `dsa` to 0.6.3
