ext/node/lib.rs
This commit gets deno_node's customizer to use fixed-length array instead of `Vec` to avoid wrong capacity allocation.
In the previous code we reserve a capacity of 14 for `external_references`. However, after pushing all the necessary `ExternalReference`s, it ends up with a length of 21, not 14. This means another allocation happens even though we reserve some space.
To make sure that there will no longer be extra allocation, it should be a good idea to use fixed-length array here.
=> chore(ext/node): use array instead of Vec to avoid wrong capacity allocation

ext/node/polyfills/cluster.ts, tests/integration/node_unit_tests.rs, tests/unit_node/cluster_test.ts
- Add missing exports to `node:cluster`
- Fix default export not being an instance of `EventEmitter`
- Fix aliasing of properties
- Fix `disconnected` -> `disconnect` export naming
This makes `log4js` work in Deno. `karma` starts too, but somehow the server isn't responding. That looks like a different issue.
Fixes https://github.com/denoland/deno/issues/24858
=> fix(node/cluster): improve stubs to make log4js work

ext/kv/config.rs, ext/kv/lib.rs, runtime/snapshot.rs, runtime/web_worker.rs, runtime/worker.rs
This commit makes various limit parameters in `deno_kv` configurable.
Currently these values are declared as constants and thus can't be modified from outside. However, there may be situations where we want to change it. This commit makes this possible by introducing a new struct `KvConfig` that needs to be given as the 2nd param in `init_ops`.
=> feat(ext/kv): configurable limit params

tests/unit/process_test.ts
Noticed this when working on another PR. The test code predates the addition of our `no-console` rule.
=> chore: ignore lint warning in test

cli/main.rs, cli/standalone/mod.rs, tests/specs/run/run_task/__test__.jsonc, tests/specs/run/run_task/deno.json, tests/specs/run/run_task/main_foo.out
Fix task names containing a colon not being found with `deno run`. We were only checking for a `module not found` error message, but strings containing a colon throw a different error.
Fixes https://github.com/denoland/deno/issues/25232
=> fix(task): support tasks with colons in name in `deno run`

cli/args/flags.rs, cli/args/mod.rs, cli/factory.rs, cli/worker.rs, runtime/lib.rs, runtime/ops/bootstrap.rs
Closes #25210 .
Removed --unstable-http from being displayed on deno run --help=unstable
=> fix: removed unstable-htttp from deno help

tests/specs/mod.rs, tests/specs/schema.json
You can now specify `"ignore": true` for either the whole file,
concrete test, or concrete step.
=> test: add supporting for ignoring spec tests

cli/npm/byonm.rs, cli/resolver.rs, tests/integration/npm_tests.rs, tests/specs/npm/byonm/not_installed.out
Needed for https://github.com/denoland/deno/pull/25213.
With Deno 2, we should suggest using `deno install` instead of `npm install`.
=> fix: replace `npm install` hint with `deno install` hint

ext/node/polyfills/worker_threads.ts, tests/unit_node/worker_threads_test.ts
Fixes #23281. Part of #20613.
We were emitting the `online` event in the constructor, so the caller could never receive it (since there was no time for them to add a listener). Instead, emit the event where it's intended – after the worker is initialized.
---
After this parcel no longer freezes, but still will fail due to other bugs (which will be fixed in other PRs)
=> fix(ext/node): emit `online` event after worker thread is initialized

cli/lsp/analysis.rs, cli/lsp/client.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/repl.rs, cli/lsp/testing/definitions.rs, cli/lsp/testing/execution.rs, cli/lsp/testing/server.rs, cli/lsp/tsc.rs, cli/lsp/urls.rs
Fixes panic at: https://github.com/denoland/deno/blob/7e68cce8159d55fd597f0da3e00f794200b9928f/cli/lsp/urls.rs#L155 Reported by @marvinhagemeister. We don't know how it's reproduced but there is error handling now.
Also get rid of `LspClientUrl`, it's been made redundant by `lsp_types::Uri`. Clean up usage of `uri` / `url` / `specifier` in variable and method names.
=> fix(lsp): panic on url_to_uri()

ext/node/polyfills/01_require.js
It crashes because of NAN usage, we want to trigger the fallback case in ssh2 by throwing an error.
Fixes https://github.com/denoland/deno/issues/25236
=> fix(ext/node): throw when loading `cpu-features` module

Cargo.lock, ext/node/Cargo.toml, ext/node/ops/crypto/cipher.rs, tests/unit_node/crypto/crypto_cipher_gcm_test.ts
Fixes https://github.com/denoland/deno/issues/25260
Fixes https://github.com/denoland/deno/issues/25254
Fixes https://github.com/denoland/deno/issues/23693
Verified that `web-push` GCM decryption works in the browser. See `aead-gcm-stream` changes [here](https://github.com/littledivy/aead-gcm-stream/commit/a9ffd0c07c14e4b566c87bf51a20ff799b9e7f5e)
=> fix(ext/node): update aead-gcm-stream to 0.3

cli/tools/fmt.rs
Unlike in dprint, `single_quote` option is shared between all formatters, so we shouldn't change this option when formatting attributes in components. This PR fixes this.
This problem doesn't affect formatting HTML.
=> fix(fmt): fix incorrect quotes in components

cli/version.rs
We're not gonna use it, but this might help distribution tools like
Homebrew to also release Deno 2.0 RC releases.
=> build: Allow building 'rc' release from source

ext/napi/lib.rs, tests/napi/init_test.js
Part of #20613.
If a node addon is using the legacy `napi_module_register` on ctor approach to module registration, we have to store the registered module so that other threads can load the addon (because `napi_module_register` will only be called once per process).
=> fix(napi): Fix worker threads importing already-loaded NAPI addon

ext/node/global.rs, ext/node/polyfills/01_require.js, ext/node/polyfills/02_init.js, ext/node/polyfills/console.ts, runtime/js/99_main.js, tests/registry/npm/@denotest/cjs-local-global-decls/1.0.0/index.js
Turns out we only virtualized it so one could have a `Console` property, and the other one not. We can just make this `console.Console` available everywhere?
=> refactor: don't virtualize the `console` global for node mode

ext/fetch/26_fetch.js, ext/http/00_serve.ts, ext/node/polyfills/01_require.js, ext/node/polyfills/02_init.js, ext/node/polyfills/_process/process.ts, ext/node/polyfills/internal/util/comparisons.ts, ext/node/polyfills/os.ts, ext/web/00_infra.js, ext/web/06_streams.js, ext/webidl/00_webidl.js
To ensure consistency across the codebase, this commit refactors the code in the `ext` folder to use `throw new Error`` instead of `throw` for throwing errors.
https://github.com/denoland/deno/issues/25270
=> refactor(ext): throw new error instead of throw error

cli/napi/js_native_api.rs
Fixes an incredibly obscure bug that causes parcel's file watcher to not get any file update notifications on macOS.
The issue was that the native addon was calling `napi_resolve_deferred`, but when we resolved the promise, v8 was running microtasks automatically. That executed JS, which called back into the native addon and broke the addon's assumption that the call wouldn't be reentrant.
=> fix(napi): Don't run microtasks in napi_resolve_deferred

Cargo.lock, Cargo.toml, cli/cache/mod.rs
* https://github.com/denoland/deno_cache_dir/pull/59
Reasons listed in that deno_cache_dir PR.
Note: we could make this a bit better by upgrading the cache, but I'm not sure it's worth the effort. We'll see what feedback we get.
=> fix: delete old Deno 1.x headers file when loading cache

tests/testdata/import_attributes/dynamic_import.out, tests/testdata/import_attributes/dynamic_import.ts, tests/testdata/run/025_hrtime.ts, tests/testdata/run/025_reload_js_type_error.js, tests/testdata/run/058_tasks_microtasks_close.ts, tests/testdata/run/078_unload_on_exit.ts, tests/testdata/run/onload/imported.ts, tests/testdata/run/onload/main.ts, tests/testdata/run/onload/nest_imported.ts, tests/testdata/run/rejection_handled.ts, tests/testdata/run/tls_connecttls.js, tests/testdata/run/tls_starttls.js, tests/testdata/run/webstorage/logger.ts, tests/testdata/run/webstorage/serialization.ts, tests/testdata/run/webstorage/setter.ts
Fixes several tests blocking https://github.com/denoland/deno/pull/25213
by replacing `window` global that is gone in Deno 2 with `globalThis`.
Also adjusted a few tests using deprecated `rid` field.
=> test: replace usage of `window` with `globalThis`

tests/integration/node_unit_tests.rs, tests/unit_node/_fs/_fs_appendFile_test.ts, tests/unit_node/_fs/_fs_close_test.ts, tests/unit_node/_fs/_fs_fdatasync_test.ts, tests/unit_node/_fs/_fs_fstat_test.ts, tests/unit_node/_fs/_fs_fsync_test.ts, tests/unit_node/_fs/_fs_ftruncate_test.ts, tests/unit_node/_fs/_fs_futimes_test.ts, tests/unit_node/_fs/_fs_writeFile_test.ts, tests/unit_node/_fs/_fs_write_test.ts
This is blocking https://github.com/denoland/deno/pull/25213.
Turns out a bunch of FS APIs are completely broken because they
use RIDs (resource IDs) instead of FDs (file descriptors).
=> test: run `node_unit_tests` with `DENO_FUTURE=1`

cli/args/mod.rs, tests/specs/npm/exec_file_inside_npm_package/__test__.jsonc
The test is failing if run with `DENO_FUTURE=1` which is blocking
https://github.com/denoland/deno/pull/25213.
=> test: run specs::npm::exec_file_inside_npm_package with DENO_FUTURE=1

cli/emit.rs, tests/specs/cache/json_import/main.ts, tests/specs/run/ts_import_assertions/__test__.jsonc, tests/specs/run/ts_import_assertions/assertion.out, tests/testdata/import_attributes/static_export.out, tests/testdata/import_attributes/static_import.out, tests/testdata/import_attributes/static_import.ts, tests/testdata/import_attributes/static_reexport.ts
This is for Deno 2.0.
Import assertions were deprecated as part of ECMAScript and were replaced with the import attribute standard https://github.com/tc39/proposal-import-attributes
Unfortunately this will affect some code in the wild. This was one of the rare cases when a proposal was [downgraded after hitting Stage 3](https://github.com/tc39/proposal-import-attributes?tab=readme-ov-file#history).
=> feat: deprecate import assertions

runtime/web_worker.rs
=> fix(runtime/web_worker): populate `SnapshotOptions` for `WebWorker` when instantiated without snapshot

tests/unit_node/http_test.ts
This PR adds a test case which checks that the issue #18154 is already resolved in main.
The `hostname` option has more precedence over `host` option in `ClientRequest` options. This behavior was fixed in [this commit](https://github.com/denoland/deno/commit/867a6d303285cdffd060e6bb4b0e97de73925cfe).
closes #18154
=> test(ext/node): check hostname option has precedence over host option

ext/node/polyfills/http2.ts, ext/node/polyfills/internal/errors.ts, tests/unit_node/http2_test.ts
- Fixes #25168 
- Adds tests for #25143
=> fix(ext/node): session close during stream setup

cli/args/flags.rs, cli/tools/upgrade.rs, tests/integration/upgrade_tests.rs
Before:
```
$ deno upgrade v1.xx
error: Invalid version passed
```
After:
```
$ deno upgrade v1.xx
error: Invalid version passed (v1.xx)
Example usage:
deno upgrade | deno upgrade 1.46 | deno upgrade canary
```
Also updates help text to use "shorthand version" without flags, but a positional arg.
=> fix(upgrade): more informative information on invalid version

cli/args/flags.rs, tests/integration/test_tests.rs, tests/testdata/test/short-pass-jobs-flag-warning.out, tools/lint.js
=> BREAKING: remove `--jobs` flag

cli/args/flags.rs
=> BREAKING: remove `--ts` flag

cli/tools/init/mod.rs, tests/integration/init_tests.rs
fix #25305
- adds static folder and asset
- makes the static server test in the template more meaningful
- reorders args in help message
- fixes output to conform to default `deno fmt`
=> fix(cli/tools): correct `deno init --serve` template behavior

cli/util/logger.rs, tests/integration/run_tests.rs
Instead of `RUST_LOG` env var, we now support `DENO_LOG` env var.
This is done to be able to set a setting specific to `deno` that wouldn't impact
other binaries written in Rust.
Ref https://github.com/denoland/deno/issues/10558#issuecomment-2324300211
=> feat: support DENO_LOG env var instead of RUST_LOG

cli/tsc/dts/lib.deno.ns.d.ts, cli/tsc/dts/lib.deno.unstable.d.ts
This significantly simplifies the types for `Deno.serve`.
The following types become generic over the address type:
- ServeHandlerInfo
- ServeHandler
- ServeOptions
- ServeInit
The following types are removed entirely:
- ServeTlsOptions
- ServeUnixOptions
- ServeUnixHandlerInfo
- ServeUnixHandler
Closes #23710
=> BREAKING(dts): improve types for `Deno.serve`

cli/args/flags.rs, runtime/lib.rs
This commit hides following unstable flags:
- `--unstable-ffi` (the API is now stable)
- `--unstable-webgpu` (this API is now stable)
- `--unstable-fs` (no more unstable APIs)
- `--unstable-byonm` (BYONM is on by default)
The flags are still parseable, but they are not used. Concrete cleanup
will be done in a follow up PR.
=> feat: hide several --unstable-* flags

tests/testdata/info/with_import_map/deno.lock
esm.sh provided a fix for `window` not existing in Deno anymore.
=> test: fix info::info_import_map test

cli/tsc/dts/lib.deno.ns.d.ts
Update the docs for `Deno.serve` to reflect that the default hostname is `0.0.0.0`, not `127.0.0.1`.
=> docs(serve): fix default `Deno.serve` hostname

cli/util/fs.rs
Fixes https://github.com/denoland/deno/issues/25333.
We fall back to junctions if the error kind is `PermissionDenied` but the std library actually sets the kind to `Uncategorized` if the symlink fails due to insufficient privileges. This was causing the fallback to not actually fall back in this case.
=> fix(cli): Map error kind to `PermissionDenied` when symlinking fails due to permissions

cli/tsc/dts/lib.deno.ns.d.ts, runtime/js/13_buffer.js, runtime/js/90_deno_ns.js, runtime/js/99_main.js, tests/specs/future/runtime_api/main.js, tests/specs/future/runtime_api/main.out, tests/unit/buffer_test.ts
=> BREAKING(buffer): remove `Deno.writeAll[Sync]()`

cli/js/40_bench.js, cli/js/40_test.js, tests/specs/bench/bench_explicit_start_end/explicit_start_and_end.out, tests/specs/test/exit_code/main.out, tests/specs/test/exit_code2/main.out, tests/specs/test/exit_code3/main.out, tests/testdata/bench/explicit_start_and_end.out, tests/unit/testing_test.ts
Aligns the error messages in the cli/js folder to be in-line with the Deno style guide.
=> refactor(cli/js): align error messages

ext/cache/01_cache.js, ext/cache/lib.rs, ext/canvas/01_image.js, ext/ffi/00_ffi.js, ext/ffi/call.rs, ext/ffi/callback.rs, tests/ffi/tests/integration_tests.rs
Aligns the error messages in the console extension to be in-line with the Deno style guide. This change-set aligns the messages in:
- ext/cache
- ext/canvas
- ext/ffi
=> refactor(ext): align error messages

ext/node/global.rs, ext/node/polyfills/01_require.js, ext/node/polyfills/_events.mjs, ext/node/polyfills/process.ts, runtime/js/98_global_scope_shared.js, tests/node_compat/polyfill_globals.js, tests/registry/npm/@denotest/globals/1.0.0/index.d.ts, tests/registry/npm/@denotest/globals/1.0.0/index.js, tests/specs/lint/node_globals_no_duplicate_imports/__test__.jsonc, tests/specs/lint/node_globals_no_duplicate_imports/error.out, tests/testdata/npm/compare_globals/main.out, tests/testdata/npm/compare_globals/main.ts
What do we do with the TypeScript types?
=> feat(cli): give access to `process` global everywhere

cli/tools/registry/pm.rs, tests/specs/add/add_with_subpath/__test__.jsonc, tests/specs/add/add_with_subpath/add.out, tests/specs/add/add_with_subpath/wrong_constraint_jsr.out, tests/specs/add/add_with_subpath/wrong_constraint_npm.out
These now works:
```
$ deno add @std/dotenv/load
$ deno add npm:preact/hooks
```
Previously we were erroring out, because this is a "package reference" including
a subpath.
Closes https://github.com/denoland/deno/issues/25385
=> feat(add): strip package subpath when adding a package

tests/unit/command_test.ts
Updates windows to resolve the binary from the cwd and based on the provided PATH env var.
This was done in https://github.com/denoland/deno/pull/25370 , but this PR adds a test. Categorizing this as "fix" so it shows up in the release notes.
Closes https://github.com/denoland/deno/issues/25171
=> fix(windows): Deno.Command - align binary resolution with linux and mac

Cargo.lock, cli/Cargo.toml, cli/args/deno_json.rs, cli/args/mod.rs, cli/factory.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/tools/check.rs, cli/tools/compile.rs, tests/integration/run_tests.rs, tests/testdata/run/checkjs.tsconfig.json, tests/testdata/run/decorators/experimental/ts/main.out, tests/testdata/run/no_check_imports_not_used_as_values/hello.ts, tests/testdata/run/no_check_imports_not_used_as_values/main.out, tests/testdata/run/no_check_imports_not_used_as_values/main.ts, tests/testdata/run/no_check_imports_not_used_as_values/preserve_imports.tsconfig.json, tools/lint.js
Deno has been using a deny list, which doesn't make sense because a lot of these options don't even work.
Closes #25363
=> BREAKING(config): make supported compilerOptions an allow list

cli/args/flags.rs, cli/main.rs, cli/tools/installer.rs, tests/specs/install/install_entrypoint/__test__.jsonc, tests/specs/install/install_entrypoint/install.out, tests/specs/install/install_entrypoint/lifecycle.out, tests/specs/install/install_entrypoint/lifecycle.ts, tests/specs/install/install_entrypoint/main.ts, tests/specs/install/install_entrypoint/second.ts
```
deno install --entrypoint one.ts two.ts
```
effectively equivalent to `deno cache`
=> feat(install): deno install with entrypoint

cli/tsc/dts/lib.deno.ns.d.ts, runtime/js/40_fs_events.js, tests/specs/future/runtime_api/main.js, tests/specs/future/runtime_api/main.out
=> BREAKING(fs): remove `Deno.FsWatcher.prototype.rid`

cli/schemas/config-file.v1.json
The property names of the `exports` field in `deno.json` was never validated. The `patternProperties` only validates values, whose property name matches the regex. It doesn't validate the property names themselves. That's what `propertyNames` is for.
Related https://github.com/denoland/deno/issues/25435
=> fix(config): validate export names

cli/graph_util.rs, tests/specs/cache/with_bare_import/095_cache_with_bare_import.ts.out, tests/specs/check/with_bare_import/095_cache_with_bare_import.ts.out, tests/specs/run/bare_specifier_without_import/main.out, tests/testdata/run/error_type_definitions.ts.out, tests/testdata/run/with_package_json/with_stop/main.out
Follow up to https://github.com/denoland/deno/pull/25430
=> fix: update hint for `deno add <package>`

tests/unit/test_util.ts
This PR removes unnecessary use of `--unstable` flag in test util, and reduces the warning during test.
=> chore(tests): reduce the use of `--unstable` flag in test util

ext/node/polyfills/process.ts, tests/unit_node/process_test.ts
This PR adds a stub implementation of `process.cpuUsage()`. This unblocks `npm:elastic-apm-node` package working
closes #23401
=> fix(ext/node): stub `process.cpuUsage()`

Cargo.lock, cli/Cargo.toml, cli/cache/emit.rs, cli/cache/mod.rs, cli/factory.rs, cli/graph_util.rs, cli/lsp/documents.rs, cli/schemas/module-graph.json, cli/tools/info.rs, cli/util/path.rs, tests/integration/info_tests.rs, tests/specs/info/multiple_redirects/main.out, tests/testdata/npm/cjs_with_deps/main_info_json.out, tests/testdata/npm/peer_deps_with_copied_folders/main_info_json.out
The map field has been empty for years now and we don't want the emit file to be exposed so it allows us to iterate on making the cache faster. Additionally, it's racy/unreliable to rely on this information. Instead, people should emit the TS files themselves using tools like deno_emit, typescript, esbuild, etc.
Closes https://github.com/denoland/deno/issues/17703
=> BREAKING: remove "emit" and "map" from deno info output

cli/tsc/dts/lib.deno.ns.d.ts, ext/http/01_http.js, tests/testdata/run/error_for_await.ts, tests/testdata/run/http2_request_url.ts, tests/testdata/run/websocket_server_idletimeout.ts, tests/testdata/run/websocket_server_multi_field_connection_header_test.ts, tests/testdata/workers/http_worker.js, tests/unit/http_test.ts
=> chore(net): soft-remove `Deno.serveHttp()`

ext/http/00_serve.ts, tests/unit/serve_test.ts
This PR fixes an invalid URL being printed when running `deno serve`
Before: invalid URL
```sh
$ deno serve --host localhost
deno serve: Listening on http://::1:8000/
```
After: valid URL
```sh
$ deno serve --host localhost
deno serve: Listening on http://[::1]:8000/
```
=> fix: invalid ipv6 hostname on `deno serve`

cli/args/flags_net.rs, runtime/ops/permissions.rs, runtime/permissions/clippy.toml, runtime/permissions/lib.rs
The `.parse()` calls in permission code are only making it more confusing, verbosity
is encouraged and welcome in this code even at the cost of not being concise.
Left a couple TODOs to not use `AnyError`.
=> refactor(permissions): remove FromStr implementations, add ::parse methods

cli/args/flags.rs
=> fix(jupyter): allow unstable flags

cli/args/flags.rs, cli/tools/registry/pm.rs, tests/specs/add/dev/__test__.jsonc, tests/specs/add/dev/add.out, tests/specs/add/dev/deno.json, tests/specs/add/dev/deno.json.out, tests/specs/add/dev/package.json, tests/specs/add/dev/package.json.out, tests/specs/install/install_add_dev/__test__.jsonc, tests/specs/install/install_add_dev/install.out, tests/specs/install/install_add_dev/package.json, tests/specs/install/install_add_dev/package.json.out
```
deno install --dev npm:chalk
```
Adds to `devDependencies` if a `package.json` is present, otherwise it just adds to `imports` in `deno.json`
=> feat(add/install): Flag to add dev dependency to package.json

ext/node/polyfills/internal_binding/tcp_wrap.ts, tests/unit_node/net_test.ts
A workaround for the issue #25480
`Deno.Listener` can't be closed synchronously after `accept()` is called. This PR delays the `accept` call 2 ticks (The listener callback is called 1 tick later. So the 1 tick delay is not enough), and makes `net.Server` capable of being closed synchronously.
This unblocks `npm:detect-port` and `npm:portfinder`
closes #18301 
closes #25175
=> fix(ext/node): delay accept() call 2 ticks in net.Server#listen

ext/node/polyfills/os.ts, runtime/ops/os/sys_info.rs
Fixes https://github.com/denoland/deno/issues/25497
=> fix(ext/node): report freemem() on Linux in bytes

cli/tsc/dts/lib.deno.unstable.d.ts
=> fix: Float16Array type

cli/main.rs, tests/integration/run_tests.rs, tests/specs/run/unstable/__test__.jsonc, tests/specs/run/unstable/broadcast_channel.out, tests/specs/run/unstable/broadcast_channel.ts, tests/specs/run/unstable/cron.out, tests/specs/run/unstable/cron.ts, tests/specs/run/unstable/http.out, tests/specs/run/unstable/http.ts, tests/specs/run/unstable/http_wss.out, tests/specs/run/unstable/http_wss.ts, tests/specs/run/unstable/kv.out, tests/specs/run/unstable/kv.ts, tests/specs/run/unstable/temporal.out, tests/specs/run/unstable/temporal.ts, tests/testdata/run/unstable_temporal_api/missing_flag.js, tests/testdata/run/unstable_temporal_api/missing_flag.out, tools/lint.js
This commit improves error messages for unstable APIs:
- `--unstable-broadcast-channel`
- `--unstable-cron`
- `--unstable-http`
- `--unstable-kv`
- `--unstable-temporal`
By providing information and hints what went wrong and how the
error can be fixed. It reuses the same infra that was added in 
https://github.com/denoland/deno/pull/21764.
=> feat: Add better error messages for unstable APIs

cli/tsc/dts/lib.deno.ns.d.ts, ext/net/lib.deno_net.d.ts, tests/unit/http_test.ts, tests/unit/serve_test.ts
=> BREAKING(io): remove `Deno.{Reader,Writer}[Sync]` and `Deno.Closer`

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, .github/workflows/wpt_epoch.yml, ext/websocket/autobahn/fuzzingclient.js
This commit removes usages of deprecated `--unstable` flag
from the CI scripts.
=> build: remove --unstable flags from CI

ext/node/ops/require.rs
Mark `op_require_break_on_next_statement` as reentrant and properly release borrow on the `OpState`. This fixes `BorrowMut` assertions when running with inspector + op metrics.
Fixes https://github.com/denoland/deno/issues/25515
=> fix(inspector): Fix panic when re-entering runtime ops

ext/fs/std_fs.rs
=> fix: linux canonicalization checks

ext/node/polyfills/path/_posix.ts, ext/node/polyfills/path/_win32.ts, ext/node/polyfills/path/mod.ts, ext/node/polyfills/path/posix.ts, ext/node/polyfills/path/win32.ts
Apparently `path/posix` and `path/win32` have circular exports. I do not know why.
Additionally there's a deprecated function `_makeLong` which is just `toNamespacedPath`
=> fix(ext/node): Add missing `node:path` exports

ext/node/ops/crypto/cipher.rs, ext/node/ops/crypto/mod.rs, tests/unit_node/crypto/crypto_cipher_test.ts
This PR adds the validation of key and init vector lengths for `createDecipheriv` and `createCipheriv` with 'aes-256-cbc' algorithm.
Currently we don't check the lengths of the inputs and that causes panics at `key.into()` or `iv.into()` calls [here](https://github.com/denoland/deno/blob/1521adf5ed640832755e362abc64b32afd7dcc7d/ext/node/ops/crypto/cipher.rs#L349) (that causes #25279). This PR adds the check of these lengths and throws appropriate errors similar to what Node.js throws.
addresses the first part of #25279
=> fix(ext/node): validate input lengths in `Cipheriv` and `Decipheriv`

ext/node/polyfills/console.ts
Contributing toward #24236
- Swapped `Object.assign` for `ObjectAssign` primordial.
- Removed referencing TODO comment.
Please disregard if no longer desired.
=> fix(ext/node): use primordials in `ext/node/polyfills/console.ts`

ext/node/polyfills/internal_binding/stream_wrap.ts, tests/unit/test_util.ts, tests/unit_node/tls_test.ts
This PR destroys Node.js stream with Deno's original error instead of `UNKNOWN` error from handle object.
In `ext/node/polyfills/internal_binding/stream_wrap.ts`, we try to simulate the system call error when reading from the internal `Deno.Conn`, however when it's used with `tls.connect` and the thrown error is a cert error (like `InvalidData: invalid peer certificate: UnknownIssuer`), then that error can't be mapped using [this list of errors](https://github.com/denoland/deno/blob/c4d088863e93b70fa0729f326ad14376ca90b0a6/ext/node/polyfills/internal_binding/uv.ts) and it becomes `UNKNOWN` error.
This PR stops that mapping to UNKNOWN error (because it just obscures the actual reason and leads to the confusion like #20293), and instead destroys the stream with the Deno's original error …
=> fix(ext/node): avoid showing `UNKNOWN` error from TCP handle

ext/node/polyfills/internal/crypto/cipher.ts, tests/unit_node/crypto/crypto_cipher_test.ts
This PR fixes the case when the `Cipheriv#update()` method is called with string without `inputEncoding` specified.
When the input is string and `inputEncoding` is not specified, the given string is directly passed to `op_node_cipheriv_encrypt`, and the encoding result becomes a wrong value.
This PR fixes it by always converting the input string with `Buffer.from` when the input is string. (ref: Node.js does the same https://github.com/nodejs/node/blob/123bb4cb22e739a039392d83d512601982f40fc0/lib/internal/crypto/cipher.js#L165-L166 )
closes #25279
=> fix(ext/node): fix `Cipheriv#update(string, undefined)`

cli/args/flags.rs, cli/tools/upgrade.rs, tests/specs/upgrade/invalid_version/__test__.jsonc, tests/specs/upgrade/invalid_version/canary.out, tests/specs/upgrade/invalid_version/shorthand.out, tests/specs/upgrade/invalid_version/version.out
When passing a wrong version here's the new message:
Ideas for better coloring are welcome
=> feat(upgrade): better error message on failure

ext/node/polyfills/http2.ts, tests/unit_node/http2_test.ts
Closes https://github.com/denoland/deno/issues/20612
Closes https://github.com/denoland/deno/issues/23326
This makes `qwik` work.
https://github.com/user-attachments/assets/c09df01a-a793-40dd-bdd2-aee21cb1ae11
=> fix(ext/node): export request and response clases from `http2` module

tools/release/release_doc_template.md
Removes `deno-lambda` section that is now deprecated: https://github.com/denoland/deno-lambda/pull/307
=> ci: upgrade release template

ext/node/polyfills/internal/crypto/cipher.ts, tests/unit_node/crypto/crypto_cipher_test.ts
This PR fixes Decipheriv behavior when autoPadding disabled and enabled.
By this change, the example given in [this comment](https://github.com/denoland/deno/issues/20924#issuecomment-2345931295) works in the same way as Node.
closes #20924
=> fix(ext/node): fix Decipheriv when autoPadding disabled

cli/tsc/dts/lib.deno.ns.d.ts, ext/http/00_serve.ts, tests/specs/serve/basic/__test__.jsonc, tests/specs/serve/basic/main.out, tests/specs/serve/basic/main.ts, tests/specs/serve/basic/main_not_win.out, tests/specs/serve/conn_info/__test__.jsonc, tests/specs/serve/conn_info/main.out, tests/specs/serve/conn_info/main.ts
=> feat(serve): Support second parameter in deno serve

cli/tsc/99_main_compiler.js, cli/tsc/mod.rs
Discovered a bug related to this during the TypeScript upgrade and this fixed it.
This is required to do when loading because TypeScript handles and resolves `/// <reference path="..." />` internally.
=> fix(check): move is cjs check from resolving to loading

ext/node/polyfills/wasi.ts
Contributing toward #24236 
- Removed referencing TODO comment.
- Add Error primordial.
More coming; working my way up in comfort with the codebase and contribution flow :)
=> fix(ext/node): use primordials in ext/node/polyfills/wasi.ts

ext/node/polyfills/01_require.js, ext/node/polyfills/02_init.js, ext/node/polyfills/internal/console/constructor.mjs
`kBindStreamsLazy` should be called with `process` during init, but it never was.
=> fix(ext/node): attach console stream properties

cli/tools/task.rs, tests/specs/task/both_no_arg/__test__.jsonc, tests/specs/task/cwd_resolves_config_from_specified_dir/__test__.jsonc, tests/specs/task/doc_comments_no_args/__test__.jsonc, tests/specs/task/no_args/__test__.jsonc, tests/specs/task/package_json_no_arg/__test__.jsonc, tests/specs/task/pre_post/__test__.jsonc, tests/specs/task/workspace/__test__.jsonc
Fixes https://github.com/denoland/deno/issues/25632
Exit code 1 indiciates some sort of failure but `deno task` (without arguments) is used to list available commands.
=> fix(cli): `deno task` exit with status 0

ext/web/06_streams.js, tests/unit/command_test.ts
This fixes the fast path for `readableStreamCollectIntoUint8Array` to only
trigger if the readable stream has not yet been disturbed - because otherwise we
may not be able to close it if the read errors.
Fixes #22621
=> fix(runtime): don't error `child.output()` on consumed stream

cli/tsc/dts/lib.deno.ns.d.ts, ext/net/lib.deno_net.d.ts
Instead of two overloads for `Deno.connectTls` and `Deno.createHttpClient`, there is now just one.
=> fix(types): simplify mtls related types

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_lockfile/pull/39
Closes https://github.com/denoland/deno/issues/25649
=> fix(lockfile): use loose deserialization for version constraints

Cargo.lock, cli/Cargo.toml, tests/specs/npm/dynamic_npm_resolution_failure/main.out
* https://github.com/denoland/deno_npm/pull/68
=> fix(npm): better error handling for remote npm deps

cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
=> fix(lsp): properly resolve jsxImportSource for caching

cli/tsc/dts/lib.deno.shared_globals.d.ts, cli/tsc/dts/lib.deno.unstable.d.ts
This commit stabilizes the `fetch` function declaration for use with `Deno.HttpClient` and moves it from `lib.deno.unstable.d.ts` to `lib.deno.shared_globals.d.ts`.
`Deno.HttpClient` was stabilized in #25569, but the associated override declaration for `fetch` is still marked as experimental. This should also be stabilized now and moved to a different d.ts file.
=> fix(dts): stabilize `fetch` declaration for use with `Deno.HttpClient`

tests/unit/webgpu_test.ts
The reason for disabling on macOS x64 is not relevant for macOS aarch64.
=> tests: re-enable WebGPU tests on macOS aarch64

cli/schemas/config-file.v1.json
Update the config schema to error when adding unsupported `compilerOptions`.
Fixes https://github.com/denoland/deno/issues/25696
=> fix: error on unsupported compiler options

Cargo.lock, Cargo.toml, ext/node/Cargo.toml, ext/node/lib.rs, ext/node/ops/mod.rs, ext/node/ops/tls.rs, ext/node/polyfills/tls.ts, tests/unit_node/tls_test.ts
Closes https://github.com/denoland/deno/issues/25604
Alternative to https://github.com/denoland/deno/pull/25701
---
Co-authored-by: Satya Rohith <me@satyarohith.com>
=> feat(ext/node): add rootCertificates to node:tls

ext/http/00_serve.ts, tests/unit/serve_test.ts
=> fix(ext/http): gracefully handle Response.error responses

cli/schemas/config-file.v1.json
Ref https://github.com/denoland/deno/issues/25380
=> fix: update nodeModulesDir config JSON schema

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Current mac arm canaries are failing to upload because the existing latest commit hash
is more that 5 commits behind and it's not in the git history.
=> ci: bump fetch depth to unblock canary uploads

ext/node/polyfills/process.ts, tests/unit_node/process_test.ts
This PR changes the handling of unsupported signals on windows. Currently it throws an error if `process.on` is called with unsupported signal (ex. SIGHUP) on windows. That causes #25675 for example.
This PR changes it to not throw the error instead let it only print the warning messages.
closes #25675
=> fix(ext/node): don't throw error for unsupported signal binding on windows

ext/webgpu/01_webgpu.js, ext/webgpu/02_surface.js, tests/unit/webgpu_test.ts
Aligns the error messages in the ext/webgpu folder to be in-line with the Deno style guide.
=> refactor(ext/webgpu): align error messages

ext/webidl/00_webidl.js, tests/testdata/run/error_009_extensions_error.js.out
Aligns the error messages in the ext/webidl folder to be in-line with the Deno style guide.
=> refactor(ext/webidl): align error messages

ext/kv/01_db.ts, ext/kv/lib.rs, tests/unit/kv_queue_test.ts, tests/unit/kv_test.ts
Aligns the error messages in the ext/kv folder to be in-line with the Deno style guide.
=> refactor(ext/kv): align error messages

cli/tools/fmt.rs, cli/tools/lint/mod.rs, tests/specs/fmt/default_ts/__test__.jsonc, tests/specs/lint/default_ts/__test__.jsonc
Fixes #25717
When using the `ext` flag, it will still attempt formatting them with the provided extension
=> fix: don't include extensionless files in file collection for lint & fmt by default

tests/specs/test/doc_success/main.out
On Windows some of these steps were taking more than 1s
=> test: make specs::test::doc_success less flaky

ext/node/ops/crypto/keys.rs, tests/unit_node/crypto/crypto_key_test.ts
Fixes https://github.com/denoland/deno/issues/25681
=> fix(ext/node): support x509 certificates in `createPublicKey`

cli/args/flags.rs
=> fix(cli): Only set allow net flag for deno serve if not already allowed all

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Mac aarch64 is failing with timeout after 150 minutes :( we'll address it
after Deno 2 is released but for now just increase the timeout.
=> ci: increase timeout to 180 minutes

cli/args/flags.rs, cli/node.rs, ext/node_resolver/analyze.rs, tests/specs/run/cjs_reexport_non_analyzable/__test__.jsonc, tests/specs/run/cjs_reexport_non_analyzable/deno.json, tests/specs/run/cjs_reexport_non_analyzable/main.ts, tests/specs/run/cjs_reexport_non_analyzable/node_modules/foo.cjs
Fixes rsbuild running in deno.
You can look at the test to see what was failing, the gist is that we were trying to statically analyze the re-exports of a CJS script, and if we couldn't find the source for the re-exported file we would fail.
Instead, we should just treat these as if they were too dynamic to analyze, and let it fail (or succeed) at runtime. This aligns with node's behavior.
=> fix(node): Don't error out if we fail to statically analyze CJS re-export

cli/args/flags.rs, runtime/permissions/lib.rs
Closes https://github.com/denoland/deno/issues/25760
=> fix(flags): properly error out for urls

cli/args/flags.rs
Fixes a regression where we were ignoring `--node-modules-dir` if there was no value passed with it. We should instead default to "auto", to maintain compat with deno 1
=> fix(cli): Default to auto with --node-modules-dir flag

Cargo.lock, Cargo.toml
Upgrades `deno_core`.
Closes https://github.com/denoland/deno/issues/25761
Closes https://github.com/denoland/deno/issues/25738
=> fix: panic when require(esm)

ext/web/15_performance.js, tests/unit/performance_test.ts
This PR optimizes the case when `performance.measure()` needs to find the startMark by name. It is a simple change on `findMostRecent` fn to avoiding copying and reversing the complete entries list.
Adds minor missing tests for:
- `clearMarks()`, general
- `clearMeasures()`, general
- `measure()`, case when the startMarks name exists more than once
```
CPU | AMD Ryzen 7 PRO 6850U with Radeon Graphics
Runtime | Deno 2.0.0-rc.4 (x86_64-unknown-linux-gnu)
benchmark              time/iter (avg)        iter/s      (min … max)           p75      p99     p995
---------------------- ----------------------------- --------------------- --------------------------
worst case measure()            2.1 ms         486.9 (  1.7 ms …   2.4 ms)   2.2 ms   2.4 ms   2.4 ms
```
```
CPU | AMD Ryzen 7 PRO 6850U …
```
=> perf(ext/web): optimize performance.measure()

ext/node/polyfills/internal/child_process.ts
From https://github.com/denoland/deno/commit/18b89d948dcb849c4dc577478794c3d5fb23b59
May have caused the recent flakiness of parallel/test-child-process-ipc-next-tick.js
=> chore: Revert child_process close ordering change

ext/node_resolver/analyze.rs, tests/registry/npm/@denotest/conditional-exports-node/1.0.0/bad.js, tests/registry/npm/@denotest/conditional-exports-node/1.0.0/good.cjs, tests/registry/npm/@denotest/conditional-exports-node/1.0.0/index.js, tests/registry/npm/@denotest/conditional-exports-node/1.0.0/package.json, tests/registry/npm/@denotest/mjs-reexport-cjs/1.0.0/dist/package.cjs.js, tests/registry/npm/@denotest/mjs-reexport-cjs/1.0.0/index.js, tests/registry/npm/@denotest/mjs-reexport-cjs/1.0.0/index.mjs, tests/registry/npm/@denotest/mjs-reexport-cjs/1.0.0/package.json, tests/specs/node/cjs_reexport_node_condition/__test__.jsonc, tests/specs/node/cjs_reexport_node_condition/deno.json, tests/specs/node/cjs_reexport_node_condition/main.ts, tests/specs/node/cjs_reexport_node_condition/package.json
Fixes #25777.
We were missing the "node" condition, so we were resolving to the wrong conditional export, causing our analysis to be incorrect.
=> fix(node): Include "node" condition during CJS re-export analysis

ext/node/ops/os/cpus.rs
* Add a stub implementation of cpu_info() for OpenBSD
Add an implementation of cpu_info() for OpenBSD, that returns a correctly-sized array. Since Rust's libc bindings for OpenBSD do not contain all symbols necessary for a full implementation and it is not planned to add them, this solution at least avoids problems with code that relies on cpu_info() purely for the size of the returned array to derive the number of available CPUs.
This addresses https://github.com/denoland/deno/issues/25621
=> feat(ext/node): Add a stub implementation of cpu_info() for OpenBSD (#2)

runtime/js/99_main.js, tests/specs/run/location/__test__.json, tests/specs/run/location/__test__.jsonc, tests/specs/run/location/location.js, tests/specs/run/location/location.out
This commit changes `globalThis.location` property to be configurable
so that packages wanting to override it (or delete it) work properly.
Towards https://github.com/denoland/deno/issues/23882
This change makes reproduction from https://github.com/denoland/deno/issues/23882#issuecomment-2340783437
pass properly.
=> feat: make 'globalThis.location' a configurable property

tests/specs/cache/package_json/__test__.jsonc, tests/specs/cache/package_json/deno.json, tests/specs/cache/package_json/deno.lock.out, tests/specs/cache/package_json/main.cache.out
Towards https://github.com/denoland/deno/issues/25241
Usage of `deno cache` makes sense when `nodeModulesDir: none` option is used. The test is updated to match the expectation.
=> tests: update specs::cache::package_json

cli/tools/fmt.rs, tests/specs/fmt/njk/__test__.jsonc, tests/specs/fmt/njk/badly_formatted.njk, tests/specs/fmt/vento/__test__.jsonc, tests/specs/fmt/vento/badly_formatted.vto
Fixes #25802
markup_fmt plugin supports some HTML-like formats like Angular, Jinja, Twig, Nunjucks or Vento, that are not supported by `deno fmt`. This PR adds support for the extensions `njk` (Nunjucks) and `vto` (Vento). Angular doesn't have a custom extension (it uses `html` afaik) and Jinja and Twig are template engines written in Python and PHP respectively so it doesn't make sense to be supported by Deno.
=> feat(fmt): support vto and njk extensions

Cargo.lock, cli/Cargo.toml, cli/args/mod.rs, cli/lsp/config.rs, tests/integration/lsp_tests.rs
* https://github.com/denoland/deno_config/pull/116
This is for security reasons for the time being for Deno 2. Details to follow post Deno 2.0 release.
Remote import maps seem incredibly rare (only 2 usages on GitHub from what I can tell), so we'll add this back with more permissions if there's enough demand for it: https://github.com/search?type=code&q=%2F%22importMap%22%3A+%22http%2F
In the meantime, use the `--import-map` flag and `"deno.importMap"` config in the LSP for remote import maps.
=> BREAKING: remove support for remote import maps in deno.json

cli/args/flags.rs
=> fix: error out if a valid flag is passed before a subcommand

Cargo.lock, Cargo.toml
Fixes #25798
This accomplishes the same result as #25800, but not by manually implementing a decompression logic, but by upgrading `tower-http` to incorporate the patch (https://github.com/tower-rs/tower-http/pull/521).
=> perf(ext/fetch): improve decompression throughput by upgrading `tower_http`

Cargo.lock, cli/Cargo.toml, tests/registry/npm/@denotest/non-existent-optional-peer/1.0.0/package.json, tests/specs/install/non_existent_optional_peer/__test__.jsonc, tests/specs/install/non_existent_optional_peer/install.out, tests/specs/install/non_existent_optional_peer/package.json
Partially addresses https://github.com/denoland/deno/issues/25648.
This allows packages that use `crossws` to be installed with `deno install`. `crossws` specifies an optional peer dependency on `uWebSockets`, but `uWebSockets` is not on npm (it is used with `git:` or `github:` specifiers). Previously we would error on this, now we don't error on non-existent optional peer dependencies.
=> fix: Update deno_npm to fix `deno install` with crossws

Cargo.lock, cli/Cargo.toml, cli/graph_util.rs, cli/lsp/language_server.rs, cli/tools/registry/graph.rs, tests/specs/check/dts_importing_non_existent/__test__.jsonc, tests/specs/check/dts_importing_non_existent/check.out, tests/specs/check/dts_importing_non_existent/index.d.ts, tests/specs/check/dts_importing_non_existent/index.js, tests/specs/run/sloppy_imports/__test__.jsonc, tests/specs/run/sloppy_imports/sloppy.out
We weren't surfacing dependency errors in types files of js files.
=> fix(check): properly surface dependency errors in types file of js file

cli/standalone/binary.rs
This was missed previously. There's no problem support RC and LTS releases.
CC @CanadaHonk @irbull
=> fix(compile): support 'deno compile' in RC and LTS releases

cli/graph_util.rs, cli/lsp/language_server.rs, cli/tools/doc.rs, cli/tools/info.rs, tests/specs/permission/allow_import/doc.out
Graph errors were being silently ignored.
=> fix(doc): surface graph errors as warnings

cli/npm/managed/resolvers/common/bin_entries.rs, tests/registry/npm/@denotest/bin/1.0.0/cli-cjs.js, tests/specs/npm/bin_entries_prefer_closer/__test__.jsonc
Fixes https://github.com/denoland/deno/issues/25862.
npm only makes bin entries executable if they get linked into `.bin`, as we did before this PR. So this PR actually deviates from npm, because it's the only reasonable way to fix this that I can think of.
---
The reason this was broken in moment is the following:
Moment has dependencies on two typescript versions: 1.8 and 3.1
If you have two packages with conflicting bin entries (i.e. two typescript versions which both have a bin entry `tsc`), in npm it is non-deterministic and undefined which one will end up in `.bin`.
npm, due to implementation differences, chooses to put typescript 1.8 into the `.bin` directory, and so `node_modules/typescript/bin/tsc` ends up getting marked executable. We, however, choose typescript 3.2, and so we …
=> fix(installl): make bin entries executable even if not put in `node_modules/.bin`

cli/npm/managed/resolvers/common/lifecycle_scripts.rs
`esbuild` can work fine without needing to run post-install script, so to make it easier
on users (especially people using Vite) we are not prompting to run with `--allow-scripts` again.
We only do that for version >= 0.18.0 to be sure.
=> feat: Don't warn about --allow-script when using esbuild

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
We only do `release` build for Mac ARM on `main` branch. It now takes more than 2.5h and sometimes
it even times out after 3h.
Gonna try to use `macos-14-xlarge` runner for a day to evaluate the spending.
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates-for-arm64-powered-larger-runners
=> ci: use macos-14-xlarge on 'main' branch

Cargo.lock, cli/Cargo.toml
Properly apply offset fixup to `LC_DYLD_EXPORTS_TRIE` load commands. This should fix Node-API symbols not resolving in RC releases.
Fixes https://github.com/denoland/deno/issues/25879
Fixes https://github.com/denoland/deno/issues/25940
Ref https://github.com/denoland/sui/commit/2b3a33bb6e1afbb04e2e1d345547e5686894e7f0
=> fix: update sui to 0.4

Cargo.lock, Cargo.toml
Eagerly errors for something like `export * from "jsr:@type/is@";` (previously it would just fail elsewhere because it would consider this as having an empty tag)
* https://github.com/denoland/deno_semver/pull/36
=> fix: eagerly error for specifier with empty version constraint

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Closes https://github.com/denoland/deno/issues/7253
=> chore: include sha256 checksum in release

cli/args/mod.rs, cli/graph_util.rs, tests/specs/info/byonm/__test__.jsonc, tests/specs/info/byonm/deno.json, tests/specs/info/byonm/info.out, tests/specs/info/byonm/package.json
This is for the time being. We need to decide how this should behave.
It was panicking because npm specifier entrypoints aren't resolved anywhere except for `deno run` (it resolves the binary entrypoint).
Closes https://github.com/denoland/deno/issues/25903
=> fix(info): error instead of panic for npm specifiers when using byonm

cli/args/flags.rs
And a few other small content cleanups related to cli command reference generation work in docs
=> fix(flags): move some content from docs.deno.com into help output

cli/args/flags.rs
This PR fixes: https://github.com/denoland/deno/issues/25274
Remove the extra shorthand -S that attached to the --deny-sys.
=> fix: remove the typo in the help message

cli/main.rs, runtime/fmt_errors.rs
This commit adds a suggestion with information and hint how
to resolve situation when user tries to run an npm package
with Node-API addons using global cache (which is currently not supported).
Closes https://github.com/denoland/deno/issues/25974
=> feat: Add suggestion for packages using Node-API addons

ext/node/polyfills/v8.ts
`temporalio` sdk [will try to use](https://github.com/temporalio/sdk-typescript/blob/faa64225a7f57154931a38c1fe612fc6520943b2/packages/worker/src/workflow/vm-shared.ts#L199-L202) promiseHook if it is found. This patch removes the unimplemented stubs.
```ts
if (promiseHooks) {
// Node >=16.14 only
this.stopPromiseHook = promiseHooks.createHook({
init: (promise: Promise<unknown>, parent: Promise<unknown>) => {
```
Fixes https://github.com/denoland/deno/issues/25977
=> fix(ext/node): remove unimplemented promiseHook stubs

cli/npm/managed/resolvers/local.rs, tests/specs/install/workspace_member_with_tag_dep/__test__.jsonc, tests/specs/install/workspace_member_with_tag_dep/install.out, tests/specs/install/workspace_member_with_tag_dep/package.json, tests/specs/install/workspace_member_with_tag_dep/package1/package.json
Fixes #25861.
Previously we were attempting to match the version requirement against the version already present in `node_modules` root, and if they didn't match we would create a node_modules dir in the workspace member's directory with the dependency.
Aside from the fact that this caused the panic, on second thought it just doesn't make sense in general. We shouldn't be semver matching, as resolution has already occurred and decided what package versions are required. Instead, we can just compare the versions directly.
=> fix(install): compare versions directly to decide whether to create a child node_modules dir for a workspace member

cli/args/flags.rs
The exploit `--allow-import` is preventing against requires a compromised host. To make things easier and given its popularity, we're going to have the default `--allow-import` value include `cdn.jsdelivr.net:443`, but this can be overridden by replacing the `--allow-import` value with something else.
=> feat(permissions): allow importing from cdn.jsdelivr.net by default

ext/crypto/x25519.rs, tests/unit/webcrypto_test.ts, tests/wpt/runner/expectation.json
Fixes https://github.com/denoland/deno/issues/25991
=> fix(ext/crypto): fix identity test for x25519 derive bits

Cargo.toml
Release profile is inherited by bench so it doesn't need to be kept in sync
=> chore: remove custom `bench` profile

tests/wpt/runner/utils.ts, tests/wpt/wpt.ts
Closes https://github.com/denoland/deno/issues/26012
```
========================================
failures:
"/WebCryptoAPI/wrapKey_unwrapKey/wrapKey_unwrapKey.https.any.html - Can wrap and unwrap X25519 private key keys as non-extractable using pkcs8 and AES-CTR"
final result: failed. 1 passed; 1 failed; 0 expected failure; total 2 (15646ms)
diff --git a/Users/divy/gh/deno/tests/wpt/runner/expectation.json b/var/folders/ll/ltqsx4nx72v5_r7rlsl36pgm0000gn/T/375d79f1257b05cd
index fb2063935..4449c5d15 100644
--- a/Users/divy/gh/deno/tests/wpt/runner/expectation.json
+++ b/var/folders/ll/ltqsx4nx72v5_r7rlsl36pgm0000gn/T/375d79f1257b05cd
@@ -1531,6 +1531,7 @@
},
"wrapKey_unwrapKey": {
"wrapKey_unwrapKey.https.any.html": [
+        "Can wrap and unwrap X25519 private key keys as non-extractable …
```
=> chore: show expectation diff for wpt tests

Cargo.lock, cli/Cargo.toml
Closes https://github.com/denoland/deno/issues/26005
=> fix(task): use current executable for deno even when not named deno

cli/args/mod.rs, tests/specs/permission/deny_run_binary_absolute_path/main.out, tests/specs/run/allow_run_insecure_warnings/__test__.jsonc, tests/specs/run/allow_run_insecure_warnings/no_allow_list.out, tests/testdata/run/deny_some_permission_args.out
Although using `--allow-run` without an allow list gives basically no security, I think we should remove this warning because it gets in the way and the only way to disable it is via --quiet.
=> Revert "feat: warn when using --allow-run with no allow list"

cli/lsp/analysis.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
=> fix(lsp): exclude missing import quick fixes with bad resolutions

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/lsp/analysis.rs
For https://github.com/denoland/deno_graph/pull/538/files
This was removed because the deserialization was not backwards compatible.
=> refactor: remove usage of full_range

Cargo.lock, cli/Cargo.toml
=> fix: do not panic when using methods on classes and interfaces in deno doc html output

ext/node/polyfills/_process/streams.mjs, tests/unit_node/process_test.ts
Fixes https://github.com/denoland/deno/issues/26123
=> fix(node): make `process.stdout.isTTY` writable

ext/node/polyfills/util.ts, tests/unit_node/util_test.ts
Fixes #26184.
It was added but not publicly exported.
=> fix(node/util): export `styleText` from `node:util`

ext/webgpu/lib.rs
It should be supported according to [this](https://github.com/gfx-rs/wgpu?tab=readme-ov-file#supported-platforms).
Fixes https://github.com/denoland/deno/issues/26144
=> fix(ext/webgpu): allow GL backend on Windows

ext/node/polyfills/_process/streams.mjs, tests/unit_node/process_test.ts
Behave similar to Node.js where modifying `stdout.columns` doesn't really resize the terminal. Ref https://github.com/nodejs/node/issues/17529
Fixes https://github.com/denoland/deno/issues/26196
=> fix(ext/node): allow writing to tty columns

Cargo.lock, Cargo.toml, cli/util/fs.rs, ext/fs/std_fs.rs, ext/node/ops/require.rs, ext/node/ops/worker_threads.rs
=> perf: use fast calls for microtask ops

cli/util/extract.rs
This commit fixes the issue of import name conflict in case the named export and default export have the same name by letting named export take precedence over default export.
Fixes #26009
=> fix(cli): named export takes precedence over default export in doc testing

ext/http/fly_accept_encoding.rs, ext/http/http_next.rs, ext/http/request_properties.rs
Code:
```js
Deno.serve({ port: 8085 }, request => {
return new Response(request.url);
});
```
Before:
```
$ wrk -d60s http://localhost:8085
Running 1m test @ http://localhost:8085
Latency    65.49us   36.05us   5.46ms   96.33%
Req/Sec    75.71k     1.90k   79.44k    78.87%
9053462 requests in 1.00m, 1.36GB read
Requests/sec: 150641.83
Transfer/sec:     23.13MB
```
After:
```
$ wrk -d60s http://localhost:8085
Running 1m test @ http://localhost:8085
Latency    64.72us   38.14us   3.29ms   95.97%
Req/Sec    76.66k     1.85k   80.17k    77.45%
9168694 requests in 1.00m, 1.37GB read
Requests/sec: 152557.21
Transfer/sec:     23.42MB
```
=> perf(http): avoid clone getting request method and url

Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno/issues/26240
Fixes https://github.com/denoland/deno/pull/24985#issuecomment-2365460210
Fix panic when a global interceptor is misconfigured or throws an exception. 
Updates deno_core to 0.313.0
=> fix: panic in `prepare_stack_trace_callback` when global interceptor throws

cli/main.rs, runtime/fmt_errors.rs
Moves code for generating suggestions and hint to `cli/fmt_errors.rs`.
This effectively applies suggestion to any place that format JS errors in terminal,
like `deno test`.
Addresses https://github.com/denoland/deno/pull/26218#issuecomment-2409139055
=> refactor: always apply hint when formatting JsError

ext/node/ops/http2.rs, ext/node/polyfills/http2.ts
Fixes #24845 
Creating standalone tests is difficult since from what I can make out this error is only manifested when talking to C++ grpc servers, but there is a full reproduction described [here](https://github.com/TobyEalden/deno-issue-24845). See also #26234.
=> fix(ext/node): handle http2 server ending stream

ext/node/polyfills/internal/buffer.mjs
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/buffer.mjs`

cli/http_util.rs, cli/npm/managed/cache/registry_info.rs, cli/npm/managed/cache/tarball.rs, cli/standalone/binary.rs, cli/tools/upgrade.rs, cli/util/mod.rs, cli/util/retry.rs
Fixes #26085.
Adds a basic retry utility with some defaults, starts off with a 1ms wait, then 10x for each successive attempt, up to a max of 1 second and 5 attempts.
I've applied the retry in the http client, reusing an existing function, so this also applies to retrying downloads of deno binaries in `upgrade` and `compile`. I can make a separate function that doesn't retry so this doesn't affect `upgrade` and `compile`, but it seemed desirable to have retries there too, so I left it in.
=> fix(install): retry downloads of registry info / tarballs

ext/http/http_next.rs
Code:
```js
Deno.serve({ port: 8085 }, request => {
return new Response(request.url);
});
```
Before:
```
% wrk -d60s http://localhost:8085/path/testing\?testing=5
Running 1m test @ http://localhost:8085/path/testing?testing=5
Latency    56.01us   18.34us   3.28ms   93.84%
Req/Sec    81.80k     3.13k   88.26k    90.77%
9783713 requests in 1.00m, 1.67GB read
Requests/sec: 162789.89
Transfer/sec:     28.41MB
```
After:
```
% wrk -d60s http://localhost:8085/path/testing\?testing=5
Running 1m test @ http://localhost:8085/path/testing?testing=5
Latency    55.44us   15.20us   2.42ms   90.41%
Req/Sec    82.71k     2.92k   88.10k    89.93% …
```
=> perf(http): make heap allocation for path conditional

ext/node/polyfills/internal_binding/_timingSafeEqual.ts, tests/unit_node/crypto/crypto_misc_test.ts
Fixes https://github.com/denoland/deno/issues/26276
=> fix(ext/node): timingSafeEqual account for AB byteOffset

cli/napi/js_native_api.rs, tests/napi/callback_test.js, tests/napi/src/callback.rs
`napi_call_function` should use our equiv of NAPI_PREAMBLE (`&mut Env` instead of `*mut Env`) since it needs to set error codes based on whether the body of the function raised a JS exception.
Fixes: https://github.com/denoland/deno/issues/26282
=> fix: node-api function call should use preamble

ext/node/polyfills/http.ts, ext/node/polyfills/internal/dns/utils.ts, ext/node/polyfills/internal_binding/cares_wrap.ts, ext/node/polyfills/net.ts, tests/unit_node/http_test.ts, tests/unit_node/tls_test.ts
partially unblocks #25470
This PR aligns the resolution of `localhost` hostname to Node.js behavior.
In Node.js `dns.lookup("localhost", (_, addr) => console.log(addr))` prints ipv6 address `::1`, but it prints ipv4 address `127.0.0.1` in Deno. That difference causes some errors in the work of enabling `createConnection` option in `http.request` (#25470). This PR fixes the issue by aligning `dns.lookup` behavior to Node.js.
This PR also changes the following behaviors (resolving TODOs):
- `http.createServer` now listens on ipv6 address `[::]` by default on linux/mac
- `net.createServer` now listens on ipv6 address `[::]` by default on linux/mac
These changes are also alignments to Node.js behaviors.
ref: https://github.com/nodejs/node/pull/39987
=> fix(ext/node): fix dns.lookup result ordering

cli/tools/jupyter/install.rs
This should likely fix https://github.com/denoland/deno/issues/26083.
Moving the kernel icons manually to the `kernels/deno` folder seems to be fixing it when testing locally:
=> fix(jupyter): copy kernels icons to the kernel directory

cli/args/flags.rs
Some `deno add` and `deno install` example usage commands didn't have the `jsr:` or `npm:` prefixes.
=> fix(cli): add prefix to install commands in help

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/26115.
We weren't normalizing the headers to lower case, so code that attempted to delete the `Content-Length` header (but used a different case) wasn't actually removing the header.
=> fix(node/http): normalize header names in `ServerResponse`

ext/node/polyfills/process.ts, tests/unit_node/process_test.ts
Closes #26183.
The warnings are super noisy and not actionable for the user
=> fix: don't warn on ignored signals on windows

ext/http/00_serve.ts, ext/net/01_net.js, ext/node/polyfills/http.ts, ext/node/polyfills/internal_binding/tcp_wrap.ts
Fixes https://github.com/denoland/deno/issues/26341.
We try to call `op_set_nodelay` on an `UpgradeStream`, which doesn't support that operation. When contructing a `TcpConn`,  just store whether or not it's backed by a proper tcp stream.
=> fix(net): don't try to set nodelay on upgrade streams

cli/napi/js_native_api.rs, tests/napi/object_test.js, tests/napi/src/object.rs
=> fix(cli): set napi object property properly

runtime/inspector_server.rs
Every 30 seconds the websocket server will now send a ping frame, so that the TCP socket stays alive.
=> fix(runtime): send ws ping frames from inspector server

runtime/permissions/lib.rs, runtime/permissions/prompter.rs
when defining a custom runtime, it might be useful to define a custom prompter - for instance when you are not relying on the terminal and want a GUI prompter instead
=> feat(permissions): expose PermissionPrompter and set_prompter function

ext/node/polyfills/_fs/_fs_copy.ts, tests/unit_node/fs_test.ts
Fixes #26313.
We were checking for the NotFound error, but still calling the callback with the error / throwing.
=> fix(node/fs): copyFile with `COPYFILE_EXCL` should not throw if the destination doesn't exist

tests/unit_node/fs_test.ts
=> chore: fix flaky COPYFILE_EXCL test

cli/tools/jupyter/server.rs
I don't have a reliable reproduction for it, but it makes it
painful to use the Jupyter kernel with semi-frequent random panics.
The completions don't always work correctly anyway, so I think
it's better to just not panic here for the time being.
Fixes https://github.com/denoland/deno/issues/26340
=> fix(jupyter): fix panics for overslow subtraction

ext/node/polyfills/internal_binding/tcp_wrap.ts
It's not guaranteed that `kStreamBaseField` is not undefined, so
added a check for it.
Closes https://github.com/denoland/deno/issues/26363
=> fix(ext/node): add null check for kStreamBaseField

cli/args/flags.rs
Was notified of one more occurance where we were missing an explicit specifier for a `deno add` call.
See https://github.com/denoland/deno/issues/26295#issuecomment-2421637401
=> fix(help): missing package specifier

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
This reverts commit e22d0e91ef7ce17dca299a44d1ccd292abde34f2.
Reverting because the CI pipeline is actually incorrect.
I intended to only use this self-hosted runner for "release" builds on `main`
branch, but now all PRs are queued waiting for a runner for a "debug" build.
=> Revert "ci: use self-hosted mac arm runner (#26366)"

ext/node/polyfills/_next_tick.ts
Improves HTTP throughput by 8-9k rps on Linux:
this patch
```
Requests/sec: 145001.69
Transfer/sec:     20.74MB
```
main
```
Requests/sec: 137866.61
Transfer/sec:     19.72MB
```
The improvements comes from the reduced number of calls to `op_run_microtask` per request. Returning `true` from a macrotask callback already calls `op_run_microtask` so the extra call was redundant.
Here's `--strace-ops` output for a single request:
main
```
[     4.667] op_http_wait                                       : CompletedAsync Async
[     4.667] op_run_microtasks                                  : Dispatched Slow
[     4.668] op_http_try_wait                                   : Dispatched Slow
[     4.668] op_http_try_wait                                   : Completed Slow
[     4.668] op_http_wait …
```
=> perf: avoid multiple calls to runMicrotask

Cargo.lock, Cargo.toml, ext/fs/Cargo.toml, runtime/ops/tty.rs, tests/util/server/Cargo.toml, tests/util/server/src/pty.rs
Dedupes nix dependency, since `rustyline` depends on a newer version that what we currently use
=> chore: update nix crate

.dprint.json, Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/tools/registry/pm.rs, tests/specs/add/comments_deno_json/__test__.jsonc, tests/specs/add/comments_deno_json/deno.jsonc, tests/specs/add/comments_deno_json/deno.jsonc.out, tests/specs/add/dev/package.json.out, tests/specs/add/existing_deps_singleline/__test__.jsonc, tests/specs/add/existing_deps_singleline/package.json, tests/specs/add/existing_deps_singleline/package.json.out, tests/specs/add/exiting_dev_deps/__test__.jsonc, tests/specs/add/exiting_dev_deps/package.json, tests/specs/add/exiting_dev_deps/package.json.out, tests/specs/install/install_add_dev/package.json, tests/specs/install/install_add_dev/package.json.out, tests/specs/remove/package_json/rm_add_package.json.out
1. Respects the formatting of the file (ex. keeps four space indents or tabs).
2. Handles editing of comments.
3. Handles trailing commas.
4. Code is easier to maintain.
=> fix(install): better json editing

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_semver/pull/38
This adds support for npm packages that have dependencies with `&&` or `,` in their version constraints.
Closes https://github.com/denoland/deno/issues/26168
=> fix(npm): support version ranges with && or comma

ext/console/01_console.js, tests/unit/console_test.ts
=> fix(ext/console): ignore casing for named colors in css parsing

runtime/tokio_util.rs
Fixes #26179.
The original error reported in that issue is fixed on canary, but in local testing on my windows machine, `next build` would just hang forever. 
After some digging, what happens is that at some point in next build, readFile promises (from `fs/promises` ) just never resolve, and so next hangs.
It turns out the issue is saturating tokio's blocking task thread pool. We previously limited the number of blocking threads to 32, and at some point those threads are all in use and there's no thread available for the file reads.
What's taking up all of those threads? The answer turns out to be `tokio::process`. On windows, child process stdio uses the blocking threadpool: https://github.com/tokio-rs/tokio/pull/4824. When you poll the child's stdio on windows, it spawns a blocking task …
=> fix(cli): increase size of blocking task threadpool on windows

ext/node/polyfills/_tls_wrap.ts, tests/unit_node/tls_test.ts
Towards https://github.com/denoland/deno/issues/26127
=> fix(node:tls): set TLSSocket.alpnProtocol for client connections

cli/tools/registry/pm/cache_deps.rs, tests/specs/install/jsr_exports/__test__.jsonc, tests/specs/install/jsr_exports/deno.json, tests/specs/install/jsr_exports/install.out
Fixes #26498.
This was a sort of intentional decision originally, as I wanted to avoid caching extra files that may not be needed. It seems like that behavior is unintuitive, so I propose we cache all of the exports of listed jsr packages when you run a bare `deno install`.
=> fix(install): cache all exports of JSR packages listed in `deno.json`

ext/io/bi_pipe.rs, tests/specs/node/child_process_extra_pipes/main.out, tests/specs/node/child_process_extra_pipes/main.ts, tests/specs/node/child_process_extra_pipes/test-pipe/src/main.rs
Fixes playwright on linux, as reported in https://github.com/denoland/deno/issues/16899#issuecomment-2378268454.
The issue was that we were opening the socket in nonblocking mode, which meant that subprocesses trying to use it would get a `EWOULDBLOCK` error (unexpectedly). The fix here is to only set nonblocking mode on our end (which we need to use asynchronously)
=> fix(ext/node): only set our end of child process pipe to nonblocking mode

ext/node/ops/ipc.rs, ext/node/polyfills/internal/child_process.ts
Fixes the issue described in https://github.com/denoland/deno/issues/23882#issuecomment-2423316362.
The parent was starting to send a message right before the process would exit, and the channel closed in the middle of the write. Unlike with reads, we weren't cancelling the pending writes, which resulted in a `Broken pipe` error surfacing to the user.
=> fix(ext/node): cancel pending ipc writes on channel close

ext/node/polyfills/internal/util/inspect.mjs, tests/unit_node/util_test.ts
We missed adding support for an array of formats being passed to `util.styleText`.
Fixes https://github.com/denoland/deno/issues/26496
=> fix(node/util): support array formats in `styleText`

cli/schemas/config-file.v1.json
Closes #26314. Follow up to https://github.com/denoland/deno_lint/pull/1335. It will work as soon as this lands since the extension links to main: https://github.com/denoland/vscode_deno/blob/3.42.0/package.json#L596.
=> fix(config): schemas for lint rule and tag autocompletion

cli/args/flags.rs
To avoid situations like described in https://github.com/denoland/deno/issues/26402
using `deno fmt` with `--ext` flag now requires to explicitly specify list of files (or
globs) to format.
Closes https://github.com/denoland/deno/issues/26402
=> fix(fmt): --ext flag requires to pass files

ext/fs/Cargo.toml
Hot-fix to unblock `v2.0.3` release
=> build: use 'fs' feature of 'nix' crate in ext/fs

Cargo.lock, Cargo.toml
This is specifically for `deno install`/`deno add` commands.
* https://github.com/dprint/jsonc-parser/pull/49
Closes https://github.com/denoland/deno/issues/26543
=> fix(install): regression - do not panic when config file contains \r\n newlines

cli/tools/upgrade.rs
It's such a PITA on Windows to get the error that you need to run `Stop-Process -name deno` to kill running Deno processes. Most of the time this is just running `deno lsp` commands, so we can safely kill those before replacing the executable.
=> fix(upgrade): stop running `deno lsp` processes on windows before attempting to replace executable

cli/lsp/analysis.rs
Fixes https://github.com/denoland/vscode_deno/issues/1196. Fallback to the original action if import regex match etc. fails. Cleanup and flatten `fix_ts_import_action()` as well. We have no repro for the error, so no test.
=> fix(lsp): make missing import action fix infallible

ext/node/polyfills/internal/crypto/_randomInt.ts
Towards #24236 
used primordials from ext:core to replace usage of built-in functions
=> fix(ext/node): use primordials in ext\node\polyfills\internal\crypto\_randomInt.ts

cli/graph_util.rs
Removes an unwrap that falsely assumed the specifier is a valid
file path.
Fixes https://github.com/denoland/deno/issues/26209
=> fix(watch): don't panic on invalid file specifiers

ext/node/polyfills/https.ts
…s` (#26323)"
This reverts commit afb33b3c2597c9ec943f71218b236486fbc86e23.
Reverting because it caused a regression - https://github.com/denoland/deno/issues/26612.
Closes https://github.com/denoland/deno/issues/26612.
=> Revert "fix(ext/node): use primordials in `ext/node/polyfills/https.ts` (#26323)"

ext/node/ops/fs.rs
Ports for both BSDs contain patches to the same effect.
See https://github.com/freebsd/freebsd-ports/blob/main/www/deno/files/patch-ext_node_ops_fs.rs and https://github.com/openbsd/ports/blob/8644910cae24458306b6a7c4ef4ef7811bc3d1f5/lang/deno/patches/patch-ext_node_ops_fs_rs
=> feat(ext/node): Add compatibility with {Free,Open}BSD

ext/napi/lib.rs
The two BSD ports are reusing the Linux code here.
=> feat(ext/napi): Export dynamic symbols list for {Free,Open}BSD

cli/args/mod.rs, tests/integration/watcher_tests.rs
closes #26618 
**Changes**
- Supported watch flag in order to take files and dirs specified when pairing it with serve subcommand.
- Added a test to practice the change.
=> fix: support watch flag to enable watching other files than the main module on serve subcommand

ext/node/ops/require.rs
I don't see the need for this? It's just joining paths?
=> fix: remove permission check in op_require_node_module_paths

Cargo.lock, Cargo.toml, ext/node/ops/crypto/mod.rs, runtime/inspector_server.rs, runtime/worker.rs
Fixes https://github.com/denoland/deno/issues/26480
Ref https://github.com/denoland/deno_core/commit/d2945fb65bca56ebfa7bb80556a4c8f4330d2315
=> fix: clamp smi in fast calls by default

ext/node/ops/require.rs, ext/node/polyfills/01_require.js, tests/registry/npm/@denotest/cjs-multiple-exports/1.0.0/package.json, tests/registry/npm/@denotest/cjs-multiple-exports/1.0.0/src/add.js, tests/registry/npm/@denotest/cjs-multiple-exports/1.0.0/src/index.js, tests/specs/node/require_export_from_parent_with_no_filename/__test__.jsonc, tests/specs/node/require_export_from_parent_with_no_filename/main.cjs, tests/specs/node/require_export_from_parent_with_no_filename/package.json
Fixes https://github.com/denoland/deno/issues/26505
I'm not exactly sure how this case comes about (I tried to write tests for it but couldn't manage to reproduce it), but what happens is the parent filename ends up null, and we bail out of resolving the specifier in package exports.
I've checked, and in node the parent filename is also null (so that's not a bug on our part), but node continues to resolve even in that case. So this PR should match node's behavior more closely than we currently do.
=> fix(ext/node): resolve exports even if parent module filename isn't present

cli/tools/registry/pm.rs, tests/specs/add/package_json_and_deno_json/__test__.jsonc, tests/specs/add/package_json_and_deno_json/subdir/deno.json, tests/specs/add/package_json_and_deno_json/subdir/prefer_if_closer_deno.json.out
Fixes https://github.com/denoland/deno/issues/26653
=> fix(add): only add npm deps to package.json if it's at least as close as deno.json

cli/tsc/99_main_compiler.js, tests/integration/lsp_tests.rs
Fixes #25999. Asset documents at https://github.com/denoland/deno/blob/2c8a0e791732ab00907ca11c3a4918ad26ead03f/cli/tsc/mod.rs#L162-L164 were not being loaded properly.
=> fix(lsp): scope attribution for lazily loaded assets

.dprint.json, Cargo.lock, cli/Cargo.toml
* https://github.com/dprint/dprint-plugin-typescript/pull/681
Closes https://github.com/denoland/deno/issues/26681
=> fix(fmt): do not panic for jsx ignore container followed by jsx text

ext/node/polyfills/01_require.js
Next.js 15.0.4 tries to use this and errors out
=> fix(ext/node): add `findSourceMap` to the default export of `node:module`

tests/integration/watcher_tests.rs
It's been failing a ton lately, it looks like the test is just incorrectly using TS syntax in a JS file https://github.com/denoland/deno/actions/runs/11672972415/job/32502710624?pr=26724#step:43:2791
It also turned out that the test was missing updates to files often because it wasn't waiting for the watcher to be ready after each restart.
=> chore: fix serve_watch_all test

Cargo.lock, Cargo.toml
Upgrade deno_core to 0.318.0
Fixes https://github.com/denoland/deno_core/issues/951
Fixes https://github.com/denoland/deno/issues/26468
=> fix: op_run_microtasks crash

cli/npm/managed/resolvers/local.rs, cli/util/fs.rs
Fixes #26116.
Handle the new error and treat is as lacking permission to make symlinks, but also to make this more robust, just always fall back to junctions no matter what the actual error is. Instead, warn if the error isn't one we've handled, but go on to attempt creating the junction
=> fix(install): handle invalid function error, and fallback to junctions regardless of the error

Cargo.lock, cli/Cargo.toml
Fixes https://github.com/denoland/deno/issues/26701
Ref https://github.com/denoland/sui/commit/69e491353fb82ce15a861376ee8dc68f183e0486
=> fix: panic_hook hangs without procfs

cli/tools/fmt.rs, tests/specs/fmt/html/well_formatted.html
Closes https://github.com/denoland/deno/issues/26748
=> fix(fmt): don't use self-closing tags in HTML

Cargo.lock, ext/net/Cargo.toml, ext/net/ops.rs, tests/Cargo.toml, tests/integration/run_tests.rs
This PR replaces the unmaintained and rebranded `trust-dns` to `hickory` for resolver in `deno_net`.
=> refactor(ext/net): Use hickory dns instead of unmaintained trust-dns

tests/unit/command_test.ts
Failure seen in https://github.com/denoland/deno/actions/runs/11677467362/job/32515407003
If the timing was bad, the subprocess could read the file after it's created but before it was written to, and exit with a status code of 0. To avoid that, protect the file with a lock
=> chore: make commandWithCwdIsAsync test less flaky

ext/cache/lib.rs, ext/cache/sqlite.rs
Wire up errors to JS instead of panicking.
Fixes https://github.com/denoland/deno/issues/26775
=> fix(ext/cache): don't panic when creating cache

ext/fetch/23_request.js, ext/http/00_serve.ts, ext/http/http_next.rs, ext/http/lib.rs, ext/http/service.rs, tests/unit/serve_test.ts
```js
Deno.serve(async (req) => {
const { promise, resolve } = Promise.withResolvers<void>();
req.signal.addEventListener("abort", () => {
resolve();
});
await promise;
return new Response("Ok");
});
```
=> feat(ext/http): abort event when request is cancelled

cli/ops/bench.rs, ext/web/02_timers.js, ext/web/15_performance.js, ext/web/lib.rs, ext/web/timers.rs, runtime/js/99_main.js
`performance.timeOrigin` was being set from when JS started executing, but `op_now` measures from an `std::time::Instant` stored in `OpState`, which is created at a completely different time. This caused `performance.timeOrigin` to be very incorrect. This PR corrects the origin and also cleans up some of the timer code.
Compared to `Date.now()`, `performance`'s time origin is now consistently within 5us (0.005ms) of system time.
=> fix: performance.timeOrigin

tests/node_compat/test.ts
Some node compat test cases (for example `test-dns-any.js`) have entries in both `ignore.*` and `test.*` in `tests/node_compat/config.jsonc`, and those files are currently run twice in CI. This PR prevents it by removing the duplicates in test case list.
=> test(ext/node): prevent running the same test cases twice

ext/websocket/01_websocket.js, tests/unit/websocket_test.ts, websocket.js
Fixes https://github.com/denoland/deno/issues/26216
Not required by the spec but Discord.js depends on it, see https://github.com/denoland/deno/issues/26216#issuecomment-2466060306
=> fix(ext/websocket): initialize `error` attribute of WebSocket ErrorEvent

cli/lsp/analysis.rs
Fixes #26777. No reproduction that works for me, so just improving fail-safeness without a test.
=> fix(lsp): skip code action edits that can't be converted

runtime/permissions/lib.rs
Fixes https://github.com/denoland/deno/issues/26809. 
`op_inspector_open` checks for "inspector" as one of the allowed sys value.
=> fix(ext/node): handle `--allow-sys=inspector`

cli/npm/managed/resolvers/common/bin_entries.rs, cli/npm/managed/resolvers/common/lifecycle_scripts.rs, cli/npm/managed/resolvers/local.rs, tests/registry/npm/@denotest/bin-created-by-lifecycle/1.0.0/install.mjs, tests/registry/npm/@denotest/bin-created-by-lifecycle/1.0.0/package.json, tests/specs/npm/bin_entry_created_by_lifecycle/__test__.jsonc, tests/specs/npm/bin_entry_created_by_lifecycle/all_at_once_install.out, tests/specs/npm/bin_entry_created_by_lifecycle/install_warn.out, tests/specs/npm/bin_entry_created_by_lifecycle/install_warn_windows.out, tests/specs/npm/bin_entry_created_by_lifecycle/package.json, tests/specs/npm/bin_entry_created_by_lifecycle/run_testbin.out
Fixes #26677
Some packages (like supabase) declare bin entries that don't exist until lifecycle scripts are run. For instance, the lifecycle script downloads a binary file which serves as a bin entrypoint.
Unfortunately you can't just defer setting up the bin entries until after lifecycle scripts have run, because the scripts may rely on them.
I looked into this, and PNPM just re-links bin entries after running lifecycle scripts. I think that's about the best we can do as well.
Note that we'll only re-setup bin entries for packages whose lifecycle scripts we run. This should limit the performance cost, as typically a given project will not have many lifecycle scripts (and of those, many of them probably don't have bin entries to set up).
=> fix(install): re-setup bin entries after running lifecycle scripts

ext/node/polyfills/01_require.js, ext/node/polyfills/process.ts, tests/unit_node/process_test.ts
Closes https://github.com/denoland/deno/issues/26832
=> fix(ext/node): process.getBuiltinModule

cli/util/extract.rs, tests/specs/test/doc_ts_expect_error/__test__.jsonc, tests/specs/test/doc_ts_expect_error/mod.out, tests/specs/test/doc_ts_expect_error/mod.ts, tests/specs/test/markdown_ts_expect_error/__test__.jsonc, tests/specs/test/markdown_ts_expect_error/main.md, tests/specs/test/markdown_ts_expect_error/main.out
This commit makes comments in code snippets in JSDoc or markdown preserved when they are executed as tests. In particular, this is needed to get TypeScript special comments such as `@ts-ignore` or `@ts-expect-error` to work correctly.
Fixes #26728
=> fix(cli): preserve comments in doc tests

Cargo.lock, cli/Cargo.toml
Upgrades the `runtimelib` crate. Of utility for users and library authors is the support for binary buffers on messages, especially for comms. cc @manzt @bartlomieju
=> chore: upgrade runtimelib (jupyter) to 0.19

ext/fetch/22_body.js, ext/fetch/lib.deno_fetch.d.ts, ext/web/06_streams.js, ext/webidl/00_webidl.js, ext/webidl/internal.d.ts, tests/integration/node_unit_tests.rs, tests/unit/fetch_test.ts, tests/unit/streams_test.ts, tests/unit_node/fetch_test.ts, tests/wpt/runner/expectation.json
Reland of #24623, but with a fix for `String` objects.
Fixes https://github.com/denoland/deno/issues/21454
Closes https://github.com/denoland/deno/issues/24849
Closes https://github.com/denoland/deno/issues/26667
=> feat(fetch): accept async iterables for body

cli/tools/installer.rs, cli/tools/registry/mod.rs, cli/tools/registry/pm.rs, tests/integration/install_tests.rs
closes #26545
Shows a hint when a package is installed globally, otherwise fallbacks to the existing implementation.
=> fix(cli): add prefix hint when installing a package globally

tests/unit_node/timers_test.ts
Fixes tests added in https://github.com/denoland/deno/pull/26703 by increasing
tolerance due to noisy CI machines.
=> fix(ext/node): increase tolerance for interval test

ext/webgpu/01_webgpu.js
Hi, while trying to do performance tests for TypeGPU we encountered a problem when using Timestamp Queries.
Converter for `GPUComputePassTimestampWrites` uses converter for `GPUQuerySet` before it is defined making it impossible to use. This PR simply reorders converter creation to resolve this issue. Logging the `GPUQuerySet` still fails (as mentioned in #26769) but it is now usable inside pass descriptors and works when used.
=> fix(ext/webgpu): Create GPUQuerySet converter before usage 

ext/fetch/lib.rs, ext/fetch/tests.rs, ext/kv/remote.rs
This commit makes HTTP client parameters used in `fetch` API configurable on the extension initialization via a callback `client_builder_hook` that  users can provide.
The main motivation behind this change is to allow `deno_fetch` users to tune the HTTP/2 client to suit their needs, although Deno CLI users will not benefit from it as no JavaScript interface is exposed to set these parameters currently.
It is up to users whether to provide hook functions. If not provided, the default configuration from hyper crate will be used.
Ref #26785
=> feat(ext/fetch): Make fetch client parameters configurable

cli/module_loader.rs, resolvers/node/resolution.rs, tests/registry/npm/@denotest/specifier-two-slashes/1.0.0/index.js, tests/registry/npm/@denotest/specifier-two-slashes/1.0.0/other.js, tests/registry/npm/@denotest/specifier-two-slashes/1.0.0/package.json, tests/specs/npm/specifier_two_slashes/__test__.jsonc, tests/specs/npm/specifier_two_slashes/main.ts
The issue was this package had an import like: `".//index.js"` and we resolved that as specified, but node normalizes it to `"./index.js"` so we have to copy node.
Closes https://github.com/denoland/deno/issues/26903
Closes https://github.com/denoland/deno/issues/25532
=> fix(node): handle resolving ".//<something>" in npm packages

cli/tools/task.rs, tests/specs/task/dependencies_root_not_cycle/__test__.jsonc, tests/specs/task/dependencies_root_not_cycle/deno.json, tests/specs/task/dependencies_root_not_cycle/member/deno.json, tests/specs/task/dependencies_root_not_cycle/task.out, tests/specs/task/dependencies_shadowed_root_name/__test__.jsonc, tests/specs/task/dependencies_shadowed_root_name/deno.jsonc, tests/specs/task/dependencies_shadowed_root_name/member/deno.jsonc, tests/specs/task/dependencies_shadowed_root_name/member_depending_root_and_member.out, tests/specs/task/dependencies_shadowed_root_name/root_dependending_root.out
We were accidentally looking up dependencies in the member.
=> fix(task): ensure root config always looks up dependencies in root

cli/args/flags.rs, tests/integration/flags_tests.rs
Added completions, lsp and types to the list of subcommands in the deno --help command. Also fixed small typo.
Issue: https://github.com/denoland/deno/issues/26096
=> fix(cli): Fixed missing subcommands and typo in deno --help

cli/util/file_watcher.rs
Closes https://github.com/denoland/deno/issues/26970
=> fix(watch): don't panic if there's no path provided

cli/args/flags.rs
This PR enhances the deno cli documentation for the deno add command to provide additional clarity on its usage. Seems that the docs file are generated through `deno json_reference`. So updated the source code.
This PR is in reference to [this PR in the docs repository](https://github.com/denoland/docs/pull/1150)
- Enhanced the command reference for the add command with additional details.
=> docs(cli/add): add clarification to add command

cli/args/flags.rs
Remove extraneous comma in `--eval` help text on `deno task` subcommand.
=> fix(cli): remove extraneous comma in task --eval help

cli/standalone/code_cache.rs
=> chore(compile): log code cache file path

cli/tools/fmt.rs, tests/specs/fmt/sql/__test__.jsonc
Similar with https://github.com/denoland/deno/pull/25848, we need to make `format_sql` to return `None` so we do not flag well formatted sql files as being wrong.
=> fix(fmt): Return `None` if sql fmt result is the same

ext/http/00_serve.ts, runtime/js/telemetry.ts, runtime/ops/otel.rs, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/basic.out, tests/specs/cli/otel_basic/main.ts
Add basic trace to Deno.serve. Also updates a bit of the testing infra to make it easier to deal with.
=> feat: Instrument Deno.serve

cli/standalone/binary.rs, cli/standalone/file_system.rs, cli/standalone/mod.rs, cli/standalone/virtual_fs.rs, tests/specs/compile/include/self/__test__.jsonc, tests/specs/compile/include/self/main.ts, tests/specs/compile/include/self/output.out
=> fix(compile): handle TypeScript file included as asset

cli/standalone/virtual_fs.rs, tests/specs/compile/include/symlink_twice/__test__.jsonc, tests/specs/compile/include/symlink_twice/setup.js
Closes https://github.com/denoland/deno/issues/27012
=> fix(compile): do not error embedding same symlink via multiple methods

cli/lsp/language_server.rs, cli/lsp/lsp_custom.rs, cli/lsp/mod.rs, tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/1211. Requires client-side change as well so 'Open task definition' works: https://github.com/denoland/vscode_deno/pull/1214. Also remove some old compat paths.
=> fix(lsp): support task object notation for tasks request

ext/fetch/22_body.js, tests/unit/serve_test.ts
Fixes https://github.com/denoland/deno/issues/27083
=> fix(ext/fetch): don't throw when `bodyUsed` inspect after upgrade

ext/node/polyfills/_fs/_fs_stat.ts, tests/unit_node/_fs/_fs_stat_test.ts, tests/unit_node/fs_test.ts
We didn't validate the `path` argument that's passed to `fs.stat()` and `fs.statSync()` which lead to wrong errors being thrown. The `@rollup/plugin-node-resolve` code calls it with `undefined` quite a lot which lead to `nitro` and `nuxt` failing.
Fixes https://github.com/denoland/deno/issues/26700
=> fix(node/fs): add missing stat path argument validation

cli/tools/task.rs, tests/integration/task_tests.rs
Strip out ansi codes and ASCII control characters when
printing the commands, descriptions and dependencies
of tasks.
=> fix(task): strip ansi codes and control chars when printing tasks

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
We didn't respect casing when checking if a HTTP header is present in Node's `ServerResponse.hasHeader()`. This lead to us returning incorrect results when the header was present. Koa assumed that the `Content-Type` header wasn't present when it actually was and defaulted to a different `Content-Type` value.
Fixes https://github.com/denoland/deno/issues/27101
=> fix(node/http): casing ignored in ServerResponse.hasHeader()

tests/node_compat/runner/TODO.md
Seems due to merging this: https://github.com/denoland/deno/actions/runs/12052779514/job/33606893423
=> chore: fix lint step due to node compat test changes

cli/tools/init/mod.rs
The naming scheme for create npm packages varies depending on whether they are scoped or not. We only supported unscoped packages prior to this PR. This PR adds support for all the following cases which npm supports:
- `foo` -> `create-foo`
- `@foo/bar` -> `@foo/create-bar`
- `@foo` -> `@foo/create`
- `@foo@2.0.0` -> `@foo/create@2.0.0`
- `@foo/bar@2.0.0` -> `@foo/create-bar@2.0.0`
See https://docs.npmjs.com/cli/v8/commands/npm-init#description
Fixes https://github.com/denoland/deno/issues/27127
=> fix(init): support scoped npm packages

ext/node/polyfills/timers.ts, tests/unit_node/timers_test.ts
As pointed out in https://github.com/denoland/deno/issues/27126 we used a variable which could potentially be of type `number` instead of the `Timeout` class instance. Ensure that we're always setting `_destroyed` on the class instead instead.
Fixes https://github.com/denoland/deno/issues/27126
=> fix(node/timers): error when passing id to clearTimeout/clearInterval

cli/tools/registry/mod.rs, tests/specs/publish/missing_name/__test__.jsonc, tests/specs/publish/missing_name/deno.json, tests/specs/publish/missing_name/mod.ts, tests/specs/publish/missing_name/publish.out
This PR improves the error output on publish when the `name` filed is missing:
```json
{
"exports": "./mod.ts",
"version": "0.0.1"
}
```
Before:
```sh
deno publish --dry-run
error: You did not specify an entrypoint in file:///Users/marvinh/dev/test/deno-pkg-timers/deno.json. Add `exports` mapping in the configuration file, eg:
{
"name": "@scope/name",
"version": "0.0.0",
"exports": "<path_to_entrypoint>"
}
```
After:
```sh
deno publish --dry-run
error: Missing 'name' field in 'file:///Users/marvinh/dev/test/deno-pkg-timers/deno.json'.
```
Fixes https://github.com/denoland/deno/issues/27116
=> fix(publish): error on missing name field

tests/node_compat/runner/setup.ts
This will allow others to consume how far Deno is from a compatibility-perspective.
Here's a discussion: https://github.com/denoland/deno/discussions/26745
From that, I made this site: https://ffmathy.github.io/is-deno-compatible-yet/
But it is showing the wrong calculations. Exposing these fields would make it easy for me to "piggyback" on the right numbers.
=> refactor: export variables for better consumption from the outside

tests/specs/npm/cjs_with_deps/__test__.jsonc, tests/specs/npm/cjs_with_deps/main_info.out
It was creating a node_modules directory.
=> chore: fix cjs_with_deps test to use a temp dir

ext/node/polyfills/_fs/_fs_readdir.ts, tests/unit_node/_fs/_fs_readdir_test.ts
We didn't support the `recursive` option of `fs.readdir()/fs.readdirSync()`.
Fixes https://github.com/denoland/deno/issues/27175
=> fix(node/fs): support `recursive` option in readdir

cli/tools/task.rs, tests/specs/task/dependencies/__test__.jsonc, tests/specs/task/dependencies/arg_task_with_deps.out, tests/specs/task/dependencies/arg_task_with_deps/deno.json
When we run `deno task` with args like `deno task foo arg` the argument should only be passed to the root task, not to its dependencies.
Fixes https://github.com/denoland/deno/issues/27206
=> fix(task): only pass args to root task

tests/unit_node/http_test.ts
This partially addresses #27154 (https://github.com/denoland/deno/issues/27154#issuecomment-2513347521 )
This PR reduces the race condition in unit_node test case `[node/http] client closing a streaming request doesn't terminate server`.
This now resolves the deferred when the server received the error, which is the required condition for the next assertion after `await deferred1.promise`. This should be more correct than resolving it using timer.
=> test(ext/node): reduce race condition in test case

ext/telemetry/telemetry.ts, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/context.ts
`SafeMap` treats its argument as an object with a "length" and index properties, rather than a generic iterator, so every time we cloned it, it was dropping all the data.
=> fix(unstable): otel context with multiple keys

cli/args/flags.rs
Ref #27025.
it does nothing (it's the default behavior) but it doesn't hurt to allow it
=> fix(outdated): allow `--latest` without `--update`

cli/file_fetcher.rs, cli/lsp/resolver.rs
This was doing an allocation for reparsing the specifier. Might as well do `.join` here and it means I can extract out this file fetcher code to deno_cache_dir more easily.
=> refactor: remove usages of `deno_core::resolve_import` for resolving redirects

Cargo.lock, ext/fetch/Cargo.toml, ext/fetch/lib.rs, runtime/errors.rs
I tried adding a test, but it's not possible due to a debug assertion in the url crate (https://github.com/servo/rust-url/issues/505)
Closes https://github.com/denoland/deno/issues/27258
=> fix: do not panic when fetching invalid file url on Windows

cli/lsp/completions.rs, ext/node/polyfill.rs, ext/node/polyfills/_http_common.ts
Fixes https://github.com/denoland/deno/issues/27289
We exported these but forgot to add them to the list of builtins used by the resolver, so we weren't resolving bare imports of some modules (e.g. `"_http_common"`)
Also adds a missing export of `HTTPParser` from `_http_common`
=> fix(node): update list of builtin node modules, add missing export to _http_common

cli/standalone/virtual_fs.rs
Extracted out of https://github.com/denoland/deno/pull/27296/files
It's hard to test for this, but a test for this is in that other PR.
=> fix(compile): correct read length for transpiled typescript files

cli/tools/registry/pm/outdated.rs, tests/specs/update/deno_json/outdated.out, tests/specs/update/deno_json/outdated_compatible.out, tests/specs/update/mixed_workspace/print_outdated/member_a.out, tests/specs/update/mixed_workspace/print_outdated/member_b.out, tests/specs/update/mixed_workspace/print_outdated/recursive.out, tests/specs/update/mixed_workspace/print_outdated/root.out, tests/specs/update/package_json/outdated.out, tests/specs/update/package_json/outdated_compatible.out
Show command to update dependencies based on the output
of "deno outdated" command.
Closes https://github.com/denoland/deno/issues/27256
=> fix(outdated): show a suggestion for updating

cli/standalone/virtual_fs.rs
Noticed this while working on another issue.
=> perf(compile): improve FileBackedVfsFile

cli/standalone/binary.rs, cli/standalone/virtual_fs.rs, cli/tools/compile.rs, cli/tools/info.rs, cli/util/display.rs, tests/integration/compile_tests.rs, tests/specs/compile/env_vars_support/compile.out, tests/specs/compile/package_json_type/compile.out, tests/testdata/compile/node_modules_symlink_outside/main_compile_file.out, tests/testdata/compile/node_modules_symlink_outside/main_compile_folder.out
I think it's probably ok to merge this as a fix because it helps serve as a diagnostic tool?
Closes https://github.com/denoland/deno/issues/27021
=> fix(compile): output contents of embedded file system

cli/args/flags.rs, cli/args/mod.rs, cli/main.rs, cli/mainrt.rs, cli/standalone/binary.rs, cli/util/logger.rs, cli/worker.rs, ext/telemetry/lib.rs, ext/telemetry/telemetry.ts, runtime/worker_bootstrap.rs, tests/specs/cli/otel_basic/main.ts
split up otel config into user configurable and runtime configurable parts. user configurable part is now set via env vars parsed according to the otel spec. otel is now enabled via `OTEL_DENO=true`, and `--unstable-otel` only acts as a guard.
Fixes: https://github.com/denoland/deno/issues/27273
=> refactor(unstable): otel configuration

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
We can have 2 concurrent runs now, so
it's worth trying it out on `main`.
=> ci: use self-hosted mac arm runner only on main branch

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
This reverts commit 3ddbea62c25891f832354134a2b24e738c45fe10.
Looks like VMs are now slightly different than before and require additional
setup. Reverting for now to unblock `main` branch.
=> Revert "ci: use self-hosted mac arm runner only on main branch (#27347)"

cli/lsp/documents.rs, tests/integration/lsp_tests.rs, tests/util/server/src/lsp.rs
Server-side changes for https://github.com/denoland/deno/discussions/27173#discussioncomment-11422766. Alongside https://github.com/denoland/vscode_deno/pull/1223.
=> fix(lsp): sql and component file formatting

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
I think this makes more sense. We'll see if it makes it faster. It was taking 1m 22s to install rust.
=> ci: restore cargo home cache before rust install

cli/standalone/virtual_fs.rs, tests/integration/compile_tests.rs, tests/specs/compile/env_vars_support/compile.out, tests/specs/compile/global_npm_cache_implicit_read_permission/compile.out, tests/specs/compile/include/symlink_twice/compile.out, tests/specs/compile/npm_fs/compile.out, tests/specs/compile/package_json_type/compile.out, tests/testdata/compile/node_modules_symlink_outside/main_compile_file.out, tests/testdata/compile/node_modules_symlink_outside/main_compile_folder.out
Merging as a fix so that LTS gets this as it's a useful diagnostic tool.
The 1MB unique is because we deduplicate files that we store (ex. some packages have the same file multiple times so we store that once).
Closes #27338
=> fix(compile): display embedded file sizes and total

Cargo.lock, cli/Cargo.toml
upgrades itoa requirement to `1.0.14`. needed for #27308
=> fix: upgrade deno_doc to 0.161.3

cli/tools/task.rs, tests/specs/task/workspace_regex_match/__test__.jsonc, tests/specs/task/workspace_regex_match/deno.json, tests/specs/task/workspace_regex_match/root.out, tests/specs/task/workspace_regex_match/subdir/deno.json
This commit fixes `deno task` by checking if the provided
task name actually has a wildcard char ("*").
Previously, if the "--recursive" flag was passed, the task name
was treated as a regex, which lead to a situation where exact task
name resulted in a regex that matched all tasks with the specific prefix.
This commit fixes it, by checking if the provided task name, is an exact
name, or is it a wildcard match.
Closes https://github.com/denoland/deno/issues/27370
Closes https://github.com/denoland/deno/issues/27401
Closes https://github.com/denoland/deno/issues/27408
=> fix(task): properly handle task name wildcards with --recursive

Cargo.lock, Cargo.toml, ext/node/ops/os/cpus.rs, runtime/ops/os/mod.rs, runtime/sys_info.rs
need to do this for quic and they deprecated this method in libc without actually providing an alternative so :/
=> chore: upgrade libc

Cargo.lock, Cargo.toml, cli/http_util.rs, cli/tools/registry/mod.rs, ext/fetch/Cargo.toml, ext/fetch/lib.rs, ext/fetch/tests.rs, ext/kv/remote.rs, runtime/ops/web_worker/sync_fetch.rs
This brings some of the HTTP/2 retry behavior from reqwest to `ext/fetch`. It will retry very specific HTTP/2 errors once, if the body is able to be used again.
cc #27332
=> fix(ext/fetch): retry some http/2 errors

cli/lsp/analysis.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, tests/integration/lsp_tests.rs
=> fix(lsp): rewrite imports for 'Move to a new file' action

Cargo.lock, cli/tsc/99_main_compiler.js, ext/net/03_quic.js, ext/net/Cargo.toml, ext/net/lib.deno_net.d.ts, ext/net/lib.rs, ext/net/quic.rs, ext/web/06_streams.js, runtime/fmt_errors.rs, runtime/js/90_deno_ns.js, tests/integration/js_unit_tests.rs, tests/unit/quic_test.ts
Implements a QUIC interface, loosely based on the WebTransport API (a future change could add the WebTransport API, built on top of this one).
[quinn](https://docs.rs/quinn/latest/quinn/) is used for the underlying QUIC implementation, for a few reasons:
- A cloneable "handle" api which fits quite nicely into deno resources.
- Good collaboration with the rust ecosystem, especially rustls.
- I like it.
=> feat(unstable): Implement QUIC

resolvers/node/errors.rs, resolvers/node/package_json.rs
This is no longer required because we now store everything in the file system for deno compile instead of in an eszip.
Before:
```
Timer precision: 41 ns
bench          fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ resolution  217.7 µs      │ 715.5 µs      │ 227.2 µs      │ 233.4 µs      │ 1000    │ 1000
```
After:
```
Timer precision: 41 ns
bench          fastest       │ slowest       │ median        │ mean          │ samples │ iters
╰─ resolution  191.1 µs      │ 768.7 µs      │ 198.2 µs      │ 205.4 µs      │ 1000    │ 1000
```
(My system is noisy, not doing a proper bench, but it removes some fs operations so going to be faster)
=> perf: remove now needless canonicalization getting closest package.json

ext/fs/30_fs.js
=> fix(ext/fs): do not throw for bigint ctime/mtime/atime

ext/fetch/22_body.js, tests/unit/body_test.ts
fixes #27132
When the body resource is unavailable when start reading it, the error message is `Bad Resource ID` and that doesn't tell what's wrong very well.
This PR changes that error message to `Cannot read body as underlying resource unavailable`
=> fix(ext/fetch): better error message when body resource is unavailable

cli/js/40_lint.js, cli/js/40_lint_selector.js, cli/js/40_lint_types.d.ts, cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/ts_estree.rs, cli/worker.rs, tests/integration/js_unit_tests.rs, tests/unit/lint_plugin_test.ts, tests/unit/lint_selectors_test.ts, tools/core_import_map.json
This PR adds support for using selectors in the JS linting plugin API. Supported at the moment are:
- `Foo Bar` (descendant)
- `Foo > Bar` (child combinator)
- `Foo + Foo` (next sibling)
- `Foo ~ Foo` (subsequent sibling)
- `[attr]`, `[attr=value]` (attribute selectors, supported operators: `=`, `!=`, `<`, `>`, `<=`, `>=`)
- `:first-child`
- `:last-child`
- `:nth-child(2)`, `:nth-child(2n + 1)`
=> feat(unstable): support selectors in JS lint plugins

runtime/sys_info.rs
Fixes https://github.com/denoland/deno/issues/27435
For some reason this was dividing by 1024 (as if the unit was KB, and we wanted bytes) but the page size is already in bytes.
=> fix: incorrect memory info free/available bytes on mac

ext/node/ops/crypto/cipher.rs, ext/node/polyfills/internal/crypto/util.ts, tests/unit_node/crypto/crypto_cipher_test.ts
Currently we only supports 7 ciphers (`aes-(128|192|256)-ecb` and `aes-(128|256)-(cbc|gcm)`) in `node:crypto`, but `crypto.getCiphers` returns other supported cipher names. That confuses `npm:openpgp` package and causes https://github.com/denoland/deno/issues/26875.
This PR makes `getCiphers` return actually supported cipher names.
With this change, the example given in #26875 can create private and public key files.
closes #26875
=> fix(ext/node): make getCiphers return supported ciphers

cli/js/40_lint.js, cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/ts_estree.rs, tests/unit/lint_plugin_test.ts
When running selectors for JS linting plugins we would error when encountering an unknown attribute name:
```js
// selector
Foo[non-existant]
// error
Error: Missing string id: <number>
```
This was caused by using `0` as the invalid marker, but also overloading `0` with an actual node type. So the fix is to reserve `0` as the invalid marker and move the property type to the next index.
=> fix(unstable): don't error on non-existing attrs or type attr

ext/node/polyfills/_brotli.js, tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/27029
Fixes https://github.com/denoland/deno/issues/26086
=> fix(ext/node): convert brotli chunks with proper byte offset

ext/fs/std_fs.rs
```
> cat main.mjs
import { cpSync, rmdirSync } from "node:fs";
for (let i = 0; i < 100_000; i++) {
cpSync("folder", "other", {
force: true,
recursive: true
});
rmdirSync("other");
}
> Measure-Command { node main.mjs }
32313.49
> Measure-Command { deno run -A main.mjs }
27379.9646
> Measure-Command { ../deno/target/debug/deno run -A main.mjs } # notice this is debug--i'm too lazy to check release
11628.361
```
=> perf(node/fs/copy): reduce metadata lookups copying directory

cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/swc.rs, cli/tools/lint/ast_buffer/ts_estree.rs
Addresses the review feedback in https://github.com/denoland/deno/pull/27416 .
- Hoist the buffer max size variable to make it less confusing
- Remove manual AST field counter in favour of an explicit "commit schema" step which writes the actual field count.
=> chore(lint): remove manual AST field counter

ext/node/polyfill.rs, tests/integration/lsp_tests.rs, tests/unit_node/inspector_test.ts
Add missing `inspector/promises` in node builtin module list, that causes types checking error
=> fix(node): Add missing `inspector/promises`

ext/fs/std_fs.rs
Even debug is way faster:
```
> cat main.cts
for (let i = 0; i < 100_000; i++) {
Deno.statSync("b.txt");
}
> Measure-Command { deno run -A main.cts } | Select-Object -Property TotalMilliseconds    
2684.68
> Measure-Command { ../deno/target/debug/deno run -A main.cts } | Select-Object -Property TotalMilliseconds
988.55
```
=> perf(fs/windows): stat - only open file once

cli/npm/managed/resolvers/local.rs
The tags were being sorted in a random order due to the package_reqs hashmap
=> fix(npm): deterministically output tags to initialized file

Cargo.lock, Cargo.toml, cli/npm/managed/resolvers/local.rs, cli/standalone/file_system.rs, cli/standalone/virtual_fs.rs, cli/sys.rs, cli/util/fs.rs
This is in preparation for extracting out these functions from the CLI crate.
A side benefit is these functions will now work in Wasm.
=> refactor: update some fs_util functions to use sys_traits

Cargo.lock, Cargo.toml, ext/node/Cargo.toml, ext/node/ops/os/mod.rs, runtime/permissions/lib.rs
The two places mentioned in the issue are now consolidated.
Closes https://github.com/denoland/deno/issues/24385
=> refactor: remove use of home crate

tests/unit/serve_test.ts
To make sure the servers are torn down when they throw an error during test execution.
=> refactor: Use 'await using' in serve_test

cli/tsc/dts/lib.deno.unstable.d.ts, ext/kv/01_db.ts, tests/unit/kv_test.ts
=> fix(kv): improve backoff error message and inline documentation

ext/http/00_serve.ts, ext/web/06_streams.js, tests/unit/serve_test.ts
This PR improves the error message when reading request body in `Deno.serve` and the underlying resource is unavailable.
The error message is currently `Bad Resource ID`. This PR change it to `Cannot read request body as underlying resource unavailable`
closes #27133
=> fix(ext/http): improve error message when underlying resource of request body unavailable

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
With https://github.com/denoland/deno/pull/27507 landed we need to do two
builds that don't really share much codegen units.
This should be reverted once we move to self-hosted runner on `main`
(https://github.com/denoland/deno/pull/27568)
=> ci: increase timeout to 240 minutes

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.toml
Also reverts #27518
The reason is that it takes too long to build these two
binaries on Mac ARM runners as it stands.
We're gonna try to reland this next week, after sorting out
situation with these runners.
=> Revert "perf: build denort with panic = "abort" for releases (#27507)"

ext/node/polyfills/_fs/_fs_open.ts, ext/node/polyfills/internal/fs/handle.ts, tests/unit_node/_fs/_fs_handle_test.ts
Add the chmod method to the FileHandle class in node compat as part of #25554
=> feat(node/fs): Add a chmod method to the FileHandle class

cli/js/40_lint_selector.js, tests/unit/lint_selectors_test.ts
The selector splitting code that's used for JS linting plugins didn't properly account for selectors being a single character. This can happen in the case of `*`.
Instead of comparing against the length, we'll now check if the remaining string portion is not empty, which is more robust. It also allows us to detect trailing whitespace, which we didn't before.
=> fix(lint): fix single char selectors being ignored

ext/node/ops/os/cpus.rs
Populate `speed` using current scaling frequency and fix times multiplier.
Fixes https://github.com/denoland/deno/issues/27555
<table>
<tr>
<th>Node.js</th>
<th>Deno</th>
</tr>
<tr>
<td>
```
> os.cpus()
[
{
model: 'AMD Ryzen 5 7530U with Radeon Graphics',
speed: 1396,
times: {
user: 1769930,
nice: 20,
sys: 525630,
idle: 41325700,
irq: 110060
}
},
```
</td>
<td>
```
> os.cpus()
[
{
model: "AMD Ryzen 5 7530U with Radeon Graphics",
speed: 1630,
times: [Object: null prototype] {
user: 1795620,
nice: 20,
sys: 537840,
idle: 41589390,
irq: 111230
}
},
```
</td>
</tr>
</table>
=> fix(ext/node): Fix `os.cpus()` on Linux

Cargo.lock
Fixes #27534
This PR updates the `moka` crate in `Cargo.lock` from v0.12.7 to v0.12.10 (by running `cargo update -p moka`). This should prevent potential panic in `Deno.resolveDns` on some laptops with Ryzen CPU.
No test case, as the changes does not affect the behavior of Deno itself.
Deno v2.1.4 started using the `moka` crate via the `hickory-resolver` crate. When `Deno.resolveDns` is called, `hickory-resolver` uses `moka` to cache DNS lookup results in memory. However, `moka` v0.12.8 or older may panic on some laptops with Ryzen CPUs when using some specific features of `moka`. Deno v2.1.4 uses `moka` v0.12.7.
The latest version of the `moka` crate (v0.12.10) has a fix for this problem.
The root cause of the problem is that some laptops with Ryzen CPUs seem to have a problem with the …
=> fix(ext/net): update moka cache to avoid potential panic in `Deno.resolveDns` on some laptops with Ryzen CPU

cli/factory.rs, cli/lsp/resolver.rs, cli/npm/managed/mod.rs, cli/npm/mod.rs, cli/standalone/mod.rs, resolvers/deno/Cargo.toml, resolvers/deno/npm/managed/common.rs, resolvers/deno/npm/managed/mod.rs, resolvers/deno/npm/mod.rs, resolvers/deno/sync.rs
As title. Will allow consumers to create this struct and use our behaviour.
Closes #27409
=> refactor(npm): move `InNpmPackageChecker` code to deno_resolver

cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc/mod.rs, tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/deno/issues/25762. Note that some of the things in that issue are not resolved (vite/client types not working properly which has other root causes), but the wildcard module augmentation specifically is fixed by this.
We were telling TSC that files with unknown media types had an extension of `.js`, so the ambient module declarations weren't applying. Instead, just don't resolve them, so the ambient declaration applies.
=> fix(lsp/check): don't resolve unknown media types to a `.js` extension

cli/lsp/language_server.rs, cli/lsp/urls.rs, tests/integration/lsp_tests.rs
Fixes https://github.com/denoland/vscode_deno/issues/1207. `untitled:Untitled-1` was being converted to `file://Untitled-1/` instead of `file:///Untitled-1`.
=> fix(lsp): handle pathless untitled URIs

ext/node/polyfills/internal/fs/handle.ts, tests/unit_node/_fs/_fs_handle_test.ts
Added utimes method to the FileHandle class, part of #25554 
✔ cargo test
✔ tools/format
✔ tools/lint
=> fix(node/fs): add utimes method to the FileHandle class

cli/js/40_lint.js, cli/js/40_lint_selector.js, cli/js/40_lint_types.d.ts, cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/swc.rs, cli/tools/lint/ast_buffer/ts_estree.rs, tests/unit/__snapshots__/lint_plugin_test.ts.snap, tests/unit/lint_plugin_test.ts
This PR changes the underlying buffer backed AST format we use for JavaScript-based linting plugins. It adds support for various new types, makes traversal code a lot easier and is more polished compared to previous iterations.
Here is a quick summary (in no particular order):
- Node prop data is separate from traversal, which makes traversal code so much easier to reason about. Previously, it was interleaved with node prop data
- spans are in a separate table as well, as they are rarely needed.
- schema is separate from SWC conversion logic, which makes 
- supports recursive plain objects
- supports numbers
- supports bigint
- supports regex
- adds all SWC nodes
Apologies, this is kinda a big PR, but it's worth it imo.
_Marking as draft because I need to update some tests tomorrow._
=> feat(unstable): refactor js lint plugin AST

ext/node/polyfills/_tls_wrap.ts, ext/node/polyfills/net.ts
Similarly to #27639, this PR applies the same workaround to `playwright-core` package.
Confirmed `playwright install` command work with this fix:
```
$ debug_deno run -A "npm:playwright@1.49.1" install chromium-headless-shell
Downloading Chromium Headless Shell 131.0.6778.33 (playwright build v1148) from https://playwright.azureedge.net/builds/chromium/1148/chromium-headless-shell-mac-arm64.zip
77.5 MiB [====================] 100% 0.0s
Chromium Headless Shell 131.0.6778.33 (playwright build v1148) downloaded to /Users/kt3k/Library/Caches/ms-playwright/chromium_headless_shell-1148
Downloading FFMPEG playwright build v1010 from https://playwright.azureedge.net/builds/ffmpeg/1010/ffmpeg-mac-arm64.zip
1.1 MiB [====================] 100% 0.0s
FFMPEG playwright build v1010 downloaded to …
```
=> fix(ext/node): fix playwright http client

tests/specs/info/import_map/__test__.jsonc, tests/specs/info/import_map/deno.json, tests/specs/info/import_map/deno.lock, tests/specs/info/import_map/with_import_map.out
This was using the lockfile and esm.sh changed breaking the lockfile. We could pin to a specific esm.sh version, but ideally we shouldn't have the test suite dependent on remote servers.
=> chore: fix ci by removing remote server dependent test

ext/node/polyfills/internal/fs/handle.ts, tests/unit_node/_fs/_fs_handle_test.ts
Add a chown method to the FileHandle class #25554.
This is my first PR. if there is anything missing, please let me know so I can fix it.
=> fix(node/fs): add a chown method to the FileHandle class

cli/lsp/tsc.rs, cli/tools/check.rs, tests/integration/lsp_tests.rs, tests/registry/npm/@denotest/augments-global/1.0.0/index.d.ts, tests/registry/npm/@denotest/augments-global/1.0.0/other.d.ts, tests/registry/npm/@denotest/augments-global/1.0.0/package.json, tests/specs/check/compiler_options_types/__test__.jsonc, tests/specs/check/compiler_options_types/deno.json, tests/specs/check/compiler_options_types/main.ts, tests/specs/check/compiler_options_types/set_node_modules_dir.ts, tests/util/server/src/lsp.rs
Fixes https://github.com/denoland/deno/issues/27062
In the LSP we were passing `npm` specifiers to TSC as roots, but TSC needs fully resolved specifiers (like the actual file path).
In `deno check` we were often excluding the specifiers entirely from the roots.
In both cases, we need to resolve the specifiers fully and then pass them to tsc
=> fix(check/lsp): correctly resolve compilerOptions.types

cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, tests/integration/lsp_tests.rs, tests/registry/npm/@denotest/augments-global/1.0.0/import-meta.d.ts, tests/registry/npm/@denotest/augments-global/1.0.0/package.json, tests/registry/npm/@denotest/augments-global/1.0.0/real-import-meta.d.ts, tests/specs/check/import_meta_no_errors/__test__.jsonc, tests/specs/check/import_meta_no_errors/deno.json, tests/specs/check/import_meta_no_errors/main.ts, tests/specs/check/import_meta_no_errors/set_node_modules_dir.ts, tests/specs/check/type_reference_import_meta/__test__.jsonc, tests/specs/check/type_reference_import_meta/deno.json, tests/specs/check/type_reference_import_meta/main.ts, tests/specs/check/type_reference_import_meta/set_node_modules_dir.ts, tests/specs/check/type_reference_import_meta/types.d.ts
Fixes #26224.
Fixes #27042.
There were three bugs here:
- we were only resolving `/// <reference types` directives starting with `npm:`, which meant we failed to resolve bare specifiers (this broke the `/// <reference types="vite/client">` directive in most of the vite templates)
- the `$node_modules` workaround caused us to fail to read files for tsc. For instance tsc would construct new paths based on specifiers containing `$node_modules`, and since we hadn't created those we weren't mapping them back to the original (this broke some type resolution within `vite/client`)
- our separation of `ImportMeta` across node and deno globals in tsc meant that npm packages couldn't augment `ImportMeta` (this broke `vite/client`'s augmentation to add `import.meta.env` and others)
After this, the …
=> fix(check/lsp): fix bugs with tsc type resolution, allow npm packages to augment `ImportMeta`

cli/tools/registry/pm/outdated.rs, tests/specs/update/deno_json/filtered/deno.json.out, tests/specs/update/deno_json/update_latest/deno.json.out, tests/specs/update/deno_json/update_latest/deno.lock.out, tests/specs/update/external_import_map/import_map.json.out, tests/specs/update/mixed_workspace/filtered/member_b_package.json.out, tests/specs/update/mixed_workspace/update_latest/subdir/member_a_deno.json.out, tests/specs/update/mixed_workspace/update_latest/subdir/member_b_package.json.out, tests/specs/update/package_json/update_latest/deno.lock.out, tests/specs/update/package_json/update_latest/package.json.out
Fixes https://github.com/denoland/deno/issues/27697
If it's a strict bound (e.g. `1.0.0` as opposed to `^1.0.0` or other), retain the strictness when we update
=> fix(outdated): retain strict semver specifier when updating

cli/tools/registry/pm/deps.rs, tests/specs/update/latest_not_pre_release/__test__.jsonc, tests/specs/update/latest_not_pre_release/package.json
Fixes https://github.com/denoland/deno/issues/27696.
Just a `>` that should've been a `>=`. Also made sure to filter out deprecated versions.
=> fix(outdated): Use `latest` tag even when it's the same as the current version

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
This addresses the 2nd part of #27670
Currently if socket errors with DNS error, then there's no way to handle it and it becomes uncaught error. This PR propagate it to ClientRequest object and the error can be handled with 'error' event listener on it.
=> fix(ext/node): propagate socket error to client request object

README.md, tools/release/npm/build.ts
- www.deno.com -> deno.com
- ipa-reader.xyz -> ipa-reader.com
As for ipa-reader, due to the redirect, query parameters are not carried over and the pronunciation cannot be easily checked.
=> docs(readme): update redirected links

ext/node/polyfills/internal/util/debuglog.ts, tests/specs/node/node_debug/main.out
Currently `%s` placeholders in debug logs in node compat js code are not handled correctly. This PR fixes it.
BEFORE
AFTER
=> fix(ext/node): fix formatting of debug logs

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Decreases binary size by ~15MB on Linux
```
$ du -h ./deno # full LTO
122M	./deno
$ du -h $(which deno) # thin LTO, canary
137M	/usr/bin/deno
```
=> perf: full LTO in sysroot

cli/snapshot/Cargo.toml, runtime/Cargo.toml, runtime/lib.rs, runtime/snapshot.rs, runtime/transpile.rs, runtime/web_worker.rs, runtime/worker.rs
=> chore: fix hmr build

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/args/import_map.rs, cli/file_fetcher.rs, cli/lsp/documents.rs, cli/lsp/urls.rs, cli/tools/fmt.rs
This was moved from deno_graph to deno_media_type.
=> refactor: use DataUrl from deno_media_type

cli/tools/registry/unfurl.rs
Fixes a bug discovered while trying to publish a package with .js + .d.ts with sloppy imports.
=> fix(publish): unfurl sloppy imports in d.ts files and type imports

cli/cache/cache_db.rs, cli/cache/module_info.rs
=> fix: do not log cache creation failure on readonly file system

cli/lsp/tsc.rs
This commit adds a simple HashMap cache to completion requests.
On a test project the time to compute completions went from 1200ms
to 75ms and the cache contained ~300 entries when 8000 completion
items were produced by the TSC.
This is a short-lived cache and is discarded once the completion
request is finished. In a follow up commits we could make it persist
between requests.
=> perf(lsp): cache completion item resolution during request

ext/node/ops/crypto/mod.rs, ext/node/polyfills/internal/crypto/scrypt.ts, tests/unit_node/crypto/crypto_scrypt_test.ts
Throws an error instead of panic. Ref https://github.com/denoland/deno/issues/27716
=> fix(ext/node): scrypt panic when `log_n` > 64

ext/node/ops/crypto/cipher.rs, tests/unit_node/crypto/crypto_cipher_gcm_test.ts
Fixes https://github.com/denoland/deno/issues/27807
=> fix(ext/node): fix panic when invalid AES GCM key size

ext/node/polyfills/crypto.ts, tests/unit_node/crypto/crypto_hash_test.ts
Implement [`crypto.hash`](https://nodejs.org/api/crypto.html#cryptohashalgorithm-data-outputencoding) - one-shot version of `createHash`
Fixes #24945
=> fix(ext/node): implement `crypto.hash`

cli/tools/init/mod.rs
Was wrong:
```
Task dev deno test --watch mod.ts
Watcher Test started.
running 0 tests from ./mod.ts
ok | 0 passed | 0 failed (2ms)
Watcher Test finished. Restarting on file change...
```
=> fix(init): correct dev task for --lib

cli/lsp/diagnostics.rs, cli/lsp/tsc.rs, cli/tsc/98_lsp.js, tests/integration/lsp_tests.rs
This makes it so imports of ambient modules (e.g. `$app/environment` in svelte, any virtual module in vite, or other module provided by a bundler) don't error in the LSP.
The way this works is that when we request diagnostics from TSC, we also respond with the list of ambient modules. Then, in the diagnostics code, we save diagnostics (produced by deno) that may be invalidated as an ambient module and wait to publish the diagnostics until we've received the ambient modules from TSC.
The actual ambient modules you get from TSC can contain globs, e.g. `*.css`. So when we get new ambient modules, we compile them all into a regex and check erroring imports against that regex. Ambient modules should change rarely, so in most cases we should be using a pre-compiled regex, which executes in …
=> fix(lsp): ignore errors on ambient module imports

ext/node/ops/crypto/digest.rs, ext/node/ops/crypto/digest/ring_sha2.rs
Currently we are using the pure rust backend of `sha2`, which has subpar performance compared to asm implementations. We already depend on `ring`, so just use that instead of `sha2` for sha256/sha512 digests.
This also speeds up things like S3 uploads, which calculate sha digests of the uploaded objects. On my local machine, this speeds up uploading a 100MB file (to a localhost s3 provider via`@aws-sdk/client-s3`) by about 2x
<details>
<summary>Benchmark:</summary>
```ts
import { createHmac } from "node:crypto";
for (
const size of [1, 10, 100, 1_000, 10_000, 100_000, 1_000_000, 10_000_000]
) {
const input = "a".repeat(size);
Deno.bench({
name: `sha256-${size}`,
fn() {
const _hash = createHmac("sha256", input).update(input).digest();
},
});
Deno.bench({
name: `sha512-${size}`,
fn() { …
```
=> perf(crypto): use ring for asm implementations of sha256/sha512

ext/node/polyfills/process.ts, tests/unit_node/process_test.ts
Fixes `gcp-metadata@6.1.1`
```
% deno eval "import 'npm:gcp-metadata@6.1.1'" # main
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GOOGLE_SDK_NODE_LOGGING')
at Object.log (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/google-logging-utils/0.0.2/build/src/logging-utils.js:356:36)
at Object.<anonymous> (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/gcp-metadata/6.1.1/build/src/index.js:52:20)
at Object.<anonymous> (file:///Users/divy/Library/Caches/deno/npm/registry.npmjs.org/gcp-metadata/6.1.1/build/src/index.js:409:4)
at Module._compile (node:module:745:34)
at loadMaybeCjs (node:module:770:10)
at Object.Module._extensions..js (node:module:755:12)
at Module.load (node:module:662:32)
at Function.Module._load …
```
=> fix(ext/node): set process.env as own property

ext/node/ops/http.rs, ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
closes #27692
This PR add support of proxy http request to `node:http.request`.
Passing the full url in `path` seems causing proxy http request in Node.js (ref: https://stackoverflow.com/questions/3862813/how-can-i-use-an-http-proxy-with-node-js-http-client ), and `axios` seems using this feature as pointed in #27692 (strangely I couldn't find a native test case that tests this feature though..)
This PR enhances `op_node_http_request_with_conn` to accept extra `request_path`. If it's passed, it overwrites the default uri of `Request` struct and causes proxy request to the server.
=> fix(ext/node): support proxy http request

cli/lib/args.rs
Fixes https://github.com/denoland/deno/issues/27528
Can't really trigger the panic myself hence no test.
=> fix(cli): Fix panic in `load_native_certs`

cli/lsp/language_server.rs
This reverts commit 7b11670e13810187463169a09c3f7618020189fc (#27780).
This workaround is no longer necessary. Ref https://github.com/denoland/deno/issues/27778#issuecomment-2628581697.
=> Revert "fix(lsp): silence debug error for 'move to a new file' action (#27780)"

ext/node/ops/sqlite/database.rs, ext/node/ops/sqlite/mod.rs, tests/unit_node/sqlite_test.ts
require RW permission on the database path except when using in-memory mode.
=> fix(ext/node): enforce -RW perms on `node:sqlite`

cli/args/flags.rs
=> fix(publish): correct coloring in --help

ext/node/polyfills/process.ts
Ref https://github.com/denoland/deno/pull/27891#issuecomment-2626286689
```
% deno eval 'console.log(Object.getOwnPropertyNames(process))'
[
"_events",
"_eventsCount",
"_maxListeners",
"versions",
"stdin",
"stdout",
"stderr"
]
% target/debug/deno eval 'console.log(Object.getOwnPropertyNames(process))'
[
"_events",
"_eventsCount",
"_maxListeners",
"release",
"arch",
"report",
"title",
"argv",
"argv0",
"chdir",
"config",
"cpuUsage",
"cwd",
"env",
"execArgv",
"exit",
"abort",
"reallyExit",
"_exiting",
"exitCode",
"mainModule",
"nextTick",
"dlopen",
"pid",
"ppid",
"platform",
"setSourceMapsEnabled",
"hrtime",
"_kill",
"kill",
"memoryUsage",
"stderr",
"stdin",
"stdout",
"version",
"versions",
"emitWarning",
"binding",
"umask",
"getgid",
"getuid",
"getegid",
"geteuid",
"getBuiltinModule", …
```
=> fix(ext/node): set process fields on own instance

ext/node/ops/sqlite/database.rs, tests/unit_node/sqlite_test.ts
Implements the `readOnly` option for `DatabaseSync`.
Permissions:
`--allow-read=test.db --allow-write=test.db` => all works
`--allow-read=test.db` => only `readOnly` dbs work, cannot create new db
=> fix(ext/node): support read-only database in `node:sqlite`

ext/fetch/23_request.js
The issue like #27715 is harder to debug because of the shared error instance which is created at the top-level of the file (and therefore it doesn't show any stacktrace when thrown).
This change it to create each instance of AbortError in each code path.
(Question: Is this in this way because of the perf concern?)
Maybe related to #23559
=> refactor(ext/fetch): do not share error instance

ext/node/polyfills/http.ts, test.mjs, tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/27091
Don't perform a WS upgrade on non-ws upgrades by checking the value.
=> fix(ext/node): handle non-ws upgrade headers

ext/napi/node_api.rs, tests/napi/src/typedarray.rs, tests/napi/typedarray_test.js
use correct type check
Fixes: https://github.com/denoland/deno/issues/27951
=> fix(ext/napi): napi_is_buffer tests for ArrayBufferView

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/args/flags.rs, cli/tools/registry/pm/deps.rs, cli/tools/registry/pm/outdated.rs, cli/tools/registry/pm/outdated/interactive.rs
interactively select which packages to upgrade. a future improvement could be to add a way to select the version as well, though not sure how valuable that would be.
=> feat(outdated): interactive update

ext/node/ops/sqlite/database.rs, ext/node/ops/sqlite/mod.rs, tests/unit_node/sqlite_test.ts
https://nodejs.org/api/sqlite.html#databaseapplychangesetchangeset-options
```js
const sourceDb = new DatabaseSync(':memory:');
const targetDb = new DatabaseSync(':memory:');
sourceDb.exec('CREATE TABLE data(key INTEGER PRIMARY KEY, value TEXT)');
targetDb.exec('CREATE TABLE data(key INTEGER PRIMARY KEY, value TEXT)');
const session = sourceDb.createSession();
const insert = sourceDb.prepare('INSERT INTO data (key, value) VALUES (?, ?)');
insert.run(1, 'hello');
insert.run(2, 'world');
const changeset = session.changeset();
targetDb.applyChangeset(changeset);
// Now that the changeset has been applied, targetDb contains the same data as sourceDb. 
```
=> fix(ext/node): implement `DatabaseSync#applyChangeset()`

ext/node/ops/crypto/keys.rs, tests/unit_node/crypto/crypto_key_test.ts
Fixes https://github.com/denoland/deno/issues/27972
=> fix(ext/node): fix missing privateKey.x in curve25519 JWK

cli/schemas/config-file.v1.json
Not sure what our handling of unstable properties in `deno.json` is. This PR adds it to the config schema.
=> feat(unstable): add `lint.plugins` to config schema

tests/specs/lint/lint_plugin_lifecycle/__test__.jsonc, tests/specs/lint/lint_plugin_lifecycle/a.ts, tests/specs/lint/lint_plugin_lifecycle/deno.json, tests/specs/lint/lint_plugin_lifecycle/lint.out, tests/specs/lint/lint_plugin_lifecycle/plugin.ts
Noticed that we didn't test the `destroy()` hook of lint plugins. This PR adds a test for that.
=> feat(unstable): add test for lint plugin destroy hook

tests/unit_node/tls_test.ts
It will be moved to `npm_smoke_tests` repo instead
=> test: remove one of 'node_unit_tests::tls_test' tests

cli/tsc/dts/lib.deno.unstable.d.ts
- Add type definition for all TSEstree AST nodes in the JS lint plugin system
~~- Fix deviations from TSEStree~~
Decided to split this PR up into two ones so that this one only has the type changes. The TSEStree fixes are here https://github.com/denoland/deno/pull/27996
=> feat(unstable): add lint plugin ast types

cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/swc.rs, cli/tools/lint/ast_buffer/ts_estree.rs, tests/unit/__snapshots__/lint_plugin_test.ts.snap, tests/unit/lint_plugin_test.ts
This PR fixes deviations in our AST format compared to TSEStree. They are mostly a leftover for when I first started working on it and based it off of babel instead.
One of the key changes why the changeset is a bit bigger is that TSEStree uses `undefined` instead of `null` as the empty value for type nodes. This is likely influenced by `tsc` which use `undefined` everywhere. The rest of the nodes use `null` though. It's a little weird, but for now it might be better to align.
(extracted from https://github.com/denoland/deno/pull/27977)
=> feat(unstable): align lint ast with TSEStree

cli/standalone/binary.rs
Not sure if this will help https://github.com/denoland/deno/issues/27988 but it's better anyway.
=> perf(compile): use bytes already in memory after downloading executable

cli/tools/lint/ast_buffer/swc.rs
Noticed that the LSP might panic during serialization when working on a file with a syntax error.
This PR changes the serialization so that invalid nodes are simply serialized to the invalid node `0`. The plugin code treats the node with id `0` as an invalid node and will ignore it during visiting.
I'm not sure how to write a test for the LSP.
=> fix: panic with js lint plugins and invalid js syntax

cli/tsc/dts/lib.deno.unstable.d.ts
This PR strongly types the JS plugin visitor.
```ts
export default {
name: "foo",
rules: {
bar: {
create(ctx) {
return {
// Plain ast node visitor
Identifier(node) {},
// Exit visitor
"Identifier:exit"(node) {},
// Custom selectors, `node` needs to be typed manually
"FunctionDeclaration > Identifier"(node: Deno.lint.Identifier) {}
}
}
}
}
}
```
Follow up to https://github.com/denoland/deno/pull/27977
=> feat(unstable): type lint plugin visitor

cli/ops/lint.rs, cli/tools/lint/plugins.rs
This clears the diagnostics whenever a file is about to run. For example, what could previously occur is an error and the diagnostics would be leftover from the previous run.
=> fix(lint): clear plugin diagnostics on each lint file run

cli/tools/lint/plugins.rs
This commit fixes racy condition in lint plugins
that could have caused diagnostics for another
file to be printed for completely unrelated file.
With this change, a oneshot channel is used
to receive diagnostics for a file, which ensures
that the caller will receive diagnostics for itself.
=> fix(lint): out of order diagnostics for plugins

cli/tsc/dts/lib.deno.ns.d.ts
`readFile` and `readFileSync` rejects/throws an error when reading directories since v1.1.0. This PR updates jsdocs to reflect that.
(Note: this was pointed in https://github.com/denoland/std/pull/6394 )
---
Side note: This seems changed between 1.0.5 and 1.1.0, but I couldn't find relevant commit/discussion about it:
```
$ deno1.0.5
Deno 1.0.5
exit using ctrl+d or close()
> Deno.readFileSync(".")
Uint8Array(0) []
> 
$ deno1.1.0
Deno 1.1.0
exit using ctrl+d or close()
> Deno.readFileSync(".")
Uncaught Error: Is a directory (os error 21)
at unwrapResponse ($deno$/ops/dispatch_minimal.ts:63:11)
at Object.sendSyncMinimal ($deno$/ops/dispatch_minimal.ts:118:10)
```
=> docs(cli): update description of readFile and readFileSync

cli/tsc/dts/lib.deno.unstable.d.ts, runtime/js/99_main.js, tests/specs/lint/lint_plugin_runtime_api/__test__.jsonc, tests/specs/lint/lint_plugin_runtime_api/main.ts, tests/specs/lint/lint_plugin_runtime_api/run.out, tests/specs/lint/lint_plugin_runtime_api/test.out
This commit changes `Deno.lint.runPlugin` to throw
in non-`deno test` subcommand, instead of returning
`undefined`.
=> fix(lint): `Deno.lint.runPlugin` throws in `deno run`

Cargo.lock, Cargo.toml, cli/Cargo.toml, cli/bench/lsp.rs, cli/lib/util/logger.rs, cli/lsp/completions.rs, cli/lsp/config.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/registries.rs, cli/lsp/repl.rs, cli/lsp/trace.rs, cli/lsp/tsc.rs, cli/tsc/97_ts_host.js, cli/tsc/98_lsp.js, cli/tsc/dts/typescript.d.ts, tests/specs/lint/lint_plugin/__test__.jsonc
adds tracing and opentelemetry exporting to the LSP.
enable it in `.vscode/settings.json` (or wherever you configure the LSP), like
```
{
"deno.tracing": true
}
```
which will by default export opentelemetry traces to `localhost:4317`
or
```
{
"deno.tracing": {
// all fields optional
"collector": "openTelemetry" (default) | "logging" (output in lsp log window)
"collectorEndpoint": "http://localhost:4318" (for opentelemetry)
"enable": true | false,
"filter": "info" // defaults to "info", but can be any span filter
}
}
```
---
a full working setup would be 
1: Run jaeger (an opentelemetry collector with a nice UI):
```
docker run --rm -p 16686:16686 -p 4317:4317 jaegertracing/jaeger
```
2. Enable in .vscode/settings.json
```
{
"deno.tracing": true
}
```
3. Restart LSP (right now it only …
=> perf(lsp): add built-in tracing support for the LSP

cli/args/flags.rs, cli/factory.rs, cli/tools/check.rs, cli/tsc/mod.rs
In particular this helps startup of the TSC isolate because `00_typescript.js` can use the code cache.
Overall, this offsets a fair bit of the hit we took when we removed the TSC snapshot.
```
❯ hyperfine --warmup 5 -p "rm -rf ~/Library/Caches/deno/check_cache_v2" "./deno-this-pr check main.ts" "./deno-no-snapshot check main.ts" "./deno-with-snapshot check main.ts"
Benchmark 1: ../../deno/target/release-lite/deno check main.ts
Time (mean ± σ):     145.7 ms ±   3.6 ms    [User: 347.6 ms, System: 36.9 ms]
Range (min … max):   142.2 ms … 155.9 ms    19 runs
Benchmark 2: ./deno-no-snapshot check main.ts
Time (mean ± σ):     195.4 ms ±   3.3 ms    [User: 397.7 ms, System: 34.9 ms]
Range (min … max):   192.1 ms … 206.0 ms    15 runs
Benchmark 3: ./deno-with-snapshot check main.ts
Time (mean ± …
```
=> perf(check): use v8 code cache for extension sources in `deno check`

cli/args/flags.rs, tests/specs/bundle/removed/bundle_help.out, tests/specs/vendor/removed/vendor_help.out
Untested because I am not on a windows machine atm. 
Closes #28092
=> fix(completions): remove problematic character for powershell

cli/build.rs, cli/tsc/mod.rs
So you can edit (e.g.) 00_typescript.js and not have to recompile during dev
=> refactor: support hmr feature for lsp files

cli/js/40_lint.js, cli/tools/lint/ast_buffer/swc.rs, cli/tools/lint/ast_buffer/ts_estree.rs, cli/tsc/dts/lib.deno.unstable.d.ts, tests/specs/lint/lint_plugin_multiple_fixes/main.ts, tests/specs/lint/lint_plugin_source_code/__test__.jsonc, tests/specs/lint/lint_plugin_source_code/deno.json, tests/specs/lint/lint_plugin_source_code/log.out, tests/specs/lint/lint_plugin_source_code/main.ts, tests/specs/lint/lint_plugin_source_code/plugin.ts
This PR adds a part of the `SourceCode` API in eslint (see https://eslint.org/docs/latest/extend/custom-rules#applying-fixes) . It's used to get the text of the current node, etc.
=> feat(unstable): add js lint plugin source code helpers

Cargo.lock, cli/Cargo.toml, tests/specs/lockfile/auto_discover_lockfile/main.out, tests/specs/lockfile/cache_bust_integrity_failure/__test__.jsonc, tests/specs/lockfile/cache_bust_integrity_failure/deno.json, tests/specs/lockfile/cache_bust_integrity_failure/deno.lock, tests/specs/lockfile/cache_bust_integrity_failure/main.out, tests/specs/lockfile/cache_bust_integrity_failure/main.ts, tests/specs/lockfile/cache_bust_integrity_failure/update.ts, tests/specs/lockfile/no_lock/fail.out, tests/specs/run/wasm_module/integrity_check_failed/main.out, tests/util/server/src/assertions.rs
Cache busts the http cache when the lockfile integrity doesn't match what's in the cache. This will help when someone's lockfile is in line with the remote server, but their local cache isn't.
* https://github.com/denoland/deno_graph/pull/567
=> fix: cache bust http cache on lockfile integrity mismatch

.github/workflows/ci.generate.ts, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, cli/main.rs, ext/ffi/Cargo.toml, ext/ffi/turbocall.rs, ext/napi/js_native_api.rs, ext/node/global.rs, ext/web/lib.rs, tests/ffi/tests/test.js, tests/specs/run/v8_jitless/main.out, tests/specs/run/wasm_unreachable/wasm_unreachable.out, tools/memfd_create_shim.c
- upgrade v8 to 13.4
- turbocall conversion for arraybuffers is now much more complex, so use cranelift
- misc updates for deprecated fns
- v8 default stack size is too small now, causing stack overflow exceptions in some tests
- add syscall shim to support new syscall in old sysroot
=> feat: Upgrade V8 to 13.4

cli/tsc/dts/lib.deno.unstable.d.ts
Added this so that we only export exports from `Deno.lint`. Required to pass DefinitelyTyped's linting.
=> chore: fix dts file for DefinitelyTyped linting

cli/ops/lint.rs, tests/specs/lint/lint_plugin_no_fixer/__test__.jsonc, tests/specs/lint/lint_plugin_no_fixer/a.ts, tests/specs/lint/lint_plugin_no_fixer/deno.json, tests/specs/lint/lint_plugin_no_fixer/lint.out, tests/specs/lint/lint_plugin_no_fixer/plugin.ts
A vector with fixes was always created, even if there were no
applicable fixes.
=> fix(lint): don't mark plugin diagnostic as fixable, if it's not

ext/node/ops/sqlite/database.rs, ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Fixes https://github.com/denoland/deno/issues/28130
=> fix(ext/node): implement StatementSync#iterate

cli/lib/util/logger.rs, ext/ffi/call.rs, ext/ffi/dlfcn.rs, ext/ffi/ir.rs, ext/ffi/symbol.rs, ext/ffi/turbocall.rs, tests/ffi/tests/test.js
Now that ArrayBuffer/ArrayBufferView is a generic Value type, we have to handle it being passed any value. To do this, thread FastApiCallbackOptions through the function, and add error raising logic.
If we run conversion and the value is not valid, we return `isize::MAX`, and then in cranelift we use this value to know that we should branch to the error logic.
An example compilation looks like this:
```rust
extern "C" fn print_buffer(ptr: *const u8, len: usize);
```
```clif
function %print_buffer_wrapper(i64, i64, i64, i64) system_v {
sig0 = (i64, i64) system_v
sig1 = (i64) -> i64 system_v
sig2 = (i64) system_v
block0(v0: i64, v1: i64, v2: i64, v3: i64):
v4 = iconst.i64 0x6525_9198_2d00 ; turbocall_ab_contents
v5 = call_indirect sig1, v4(v1)
v6 = iconst.i64 0x7fff_ffff_ffff_ffff
v7 = icmp …
```
=> fix: handle all values for buffers in turbocall codegen

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_cache_dir/pull/73
=> feat: support XDG_CACHE_HOME for deno dir on macos

cli/graph_util.rs, cli/tools/check.rs, cli/tsc/diagnostics.rs, resolvers/node/analyze.rs, tests/specs/check/module_not_found_in_npm_pkg/__test__.jsonc, tests/specs/check/module_not_found_in_npm_pkg/check.out, tests/specs/check/module_not_found_in_npm_pkg/main.ts, tests/specs/check/module_not_found_in_npm_pkg/node_modules/package/package.json, tests/specs/check/module_not_found_in_npm_pkg/package.json, tests/specs/node/cjs_analysis_multiple_errors/main.out
Closes https://github.com/denoland/deno/issues/27188
=> fix(check): npm resolution errors to tsc diagnostics

cli/tools/registry/mod.rs, cli/tools/registry/module_content.rs, cli/tools/registry/tar.rs, cli/tools/registry/unfurl.rs
Adds a `ModuleContentProvider`. Will use this in a future PR to do more than specifier unfurling (JSX support).
=> refactor(publish): create ModuleContentProvider

cli/lsp/analysis.rs, cli/lsp/language_server.rs, cli/lsp/resolver.rs, cli/tsc/mod.rs, resolvers/deno/npm/mod.rs, resolvers/node/errors.rs, resolvers/node/lib.rs, resolvers/node/resolution.rs, tests/integration/lsp_tests.rs, tests/registry/npm/@denotest/index-export-no-types/1.0.0/index.js, tests/registry/npm/@denotest/index-export-no-types/1.0.0/package.json, tests/registry/npm/@types/denotest__index-export-no-types/0.5.0/index.d.ts, tests/registry/npm/@types/denotest__index-export-no-types/0.5.0/package.json, tests/registry/npm/@types/denotest__index-export-no-types/1.0.0/index.d.ts, tests/registry/npm/@types/denotest__index-export-no-types/1.0.0/package.json, tests/specs/check/definitely_typed/__test__.jsonc, tests/specs/check/definitely_typed/deno.json, tests/specs/check/definitely_typed/main.ts, tests/specs/check/definitely_typed/set_node_modules_dir.ts, tests/specs/check/definitely_typed/ts_types.ts, tests/specs/check/definitely_typed/ts_types_mismatch.out, tests/specs/check/definitely_typed/type_mismatch.out, tests/util/server/src/npm.rs
Fixes https://github.com/denoland/deno/issues/27569.
Fixes https://github.com/denoland/deno/issues/27215.
This PR makes it so type resolution falls back to looking for definitely typed packages (`@types/foo`) if a given NPM package does not contain type declarations.
One complication is choosing _which_ version of the `@types/*` package to use, if the project depends on multiple versions. The heuristic here is to try to match the major and minor versions, falling back to the latest version. So if you have
```
@types/foo: 0.1.0, 0.2.0, 3.1.0, 3.1.2, 4.0.0
foo: 3.1.0
```
we would choose `@types/foo@3.1.2` when resolving types for `foo`.
---
Note that this only uses `@types/` packages if you _already_ depend on them. So a follow up to this PR could be to add a diagnostic and quickfix to …
=> fix(check/lsp): fall back to `@types/*` packages if npm package doesn't have types

ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Use `v8::Number` instead of `v8::Integer` to handle > i32::MAX.
Fixes https://github.com/denoland/deno/issues/28187
=> fix(ext/node): Fix handling of sqlite large integers

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tsc/dts/lib.deno.shared_globals.d.ts, cli/tsc/dts/lib.deno_fetch.d.ts, cli/tsc/mod.rs, tests/specs/check/instability_fetch/__test__.jsonc, tests/specs/check/instability_fetch/main.ts
Also reduces memory usage.
Closes #28201
=> fix(check): remove instability in loading lib files

tests/specs/cli/otel_basic/http_metric.out, tests/specs/cli/otel_basic/http_metric.ts
The bucket counts can vary run to run. Also don't hardcode the port
=> chore: fix otel test flakiness

cli/js/40_lint.js, tests/unit/lint_plugin_test.ts
The `:exit` selectors were called at the wrong time during visiting.
They need to be called when going upwards and a node and all its children have been fully visited. Instead we called it when the node + all its sibling were visited which is wrong.
Fixes https://github.com/denoland/deno/issues/28227
=> fix(unstable): lint plugin `:exit` called at wrong time

Cargo.lock, Cargo.toml, resolvers/node/resolution.rs
Should be slightly faster too because it no longer heap allocates.
=> refactor(resolver/node): use `deno_path_util::is_relative_specifier`

cli/tools/coverage/mod.rs, cli/tools/coverage/reporter.rs
Prerequisite for #28218 
This PR simplifies the CoverageReporter trait. Now `file_reports: Vec<(CoverageReport, String)>` are created outside the reporter class. This enables multiple reporters using the same reports, and reduces the memory usage when implementing #28218
=> refactor(coverage): simplify CoverageReporter trait

cli/npm/installer/local.rs
Speeds up the caching part of this arbitrary `"nodeModulesDir": "auto"` project by about 22%
We write the tags associated with a given npm package to the `.initialized` file, so that byonm can correctly resolve tags. When setting up the node modules dir, we read that file to see if we need to update the tags.
If we don't have any tags associated with the package though, we can just check for existence (which is a fair bit faster than trying to `open` + `read` a file).
```
❯ hyperfine --warmup 3 "deno check src/**/*.ts" "../deno/target/release-lite/deno check src/**/*.ts"
Benchmark 1: deno check src/**/*.ts
Time (mean ± σ):     369.9 ms ±   5.5 ms    [User: 286.9 ms, System: 128.9 ms]
Range (min … max):   361.7 ms … 377.7 ms    10 runs
Benchmark 2: ../deno/target/release-lite/deno check …
```
=> perf(install): only read initialized file if we care about the tags

tests/specs/test/worker_large_output/__test__.jsonc
Maybe this might be covering up a bug, but it fails too often with "operation failed to complete synchronously".
=> chore: mark worker_large_output as flaky

cli/args/flags.rs, tests/integration/fmt_tests.rs, tests/specs/fmt/njk/__test__.jsonc, tests/specs/fmt/vento/__test__.jsonc
I can use this to rework formatting in the extension so they don't have to go through the LSP.
Towards https://github.com/denoland/vscode_deno/issues/1228.
=> fix(fmt): support "--ext vto" and "--ext njk"

cli/tools/lint/mod.rs, tests/specs/lint/lint_plugin_empty_tags/__test__.jsonc, tests/specs/lint/lint_plugin_empty_tags/deno.json, tests/specs/lint/lint_plugin_empty_tags/log.out, tests/specs/lint/lint_plugin_empty_tags/main.ts, tests/specs/lint/lint_plugin_empty_tags/plugin.ts
When all Rust-based rules where filtered out we were bailing out early instead of checking if there are plugin rules we need to run. This meant we errored out with a "No lint rules to run" message, even though plugin rules were active.
Fixes https://github.com/denoland/deno/issues/28267
=> fix(lint): plugins ignored when no rust rule active

Cargo.lock, Cargo.toml, cli/lsp/resolver.rs, tests/integration/lsp_tests.rs
Towards #28300. The slowness will still occur on init and config changes, but not on every edit.
=> perf(lsp): don't set resolver npm reqs if unchanged

cli/tsc/dts/lib.deno_net.d.ts, ext/net/01_net.js, ext/net/ops.rs, ext/node/polyfills/internal_binding/tcp_wrap.ts
This PR will address the node compatibility issue where, the callback socket object in net.createServer is missing a fd in socket._handle
Modified this PR to use internal symbol to expose fd instead of exposing it via lib.deno.d.ts
https://github.com/denoland/deno_core/pull/1061
fixes: https://github.com/denoland/deno/issues/27788
=> fix(ext/node): node compatibility issue missing fd in createServer callback socket object

cli/tools/lint/plugins.rs
Ref https://github.com/denoland/deno/issues/28258
This commit forces lint plugins to run with `--no-prompt` flag,
bringing parity between running plugins in the LSP and via
`deno lint`.
There's no agreement how to handle permissions in the lint
plugins yet, so it's better to make both subcommands behave
identically for the time being.
=> fix(lint): run with --no-prompt

Cargo.toml, ext/http/Cargo.toml, ext/http/lib.rs, runtime/snapshot.rs, runtime/snapshot_info.rs, runtime/web_worker.rs, runtime/worker.rs
results on my machine (Macbook pro w/ M3 Max)
canary (hello world):
```
❯ oha -c 125 -n 4000000 --no-tui --disable-compression http://localhost:8000
Summary:
Success rate: 100.00%
Total:        31.0160 secs
Slowest:      0.0083 secs
Fastest:      0.0005 secs
Average:      0.0010 secs
Requests/sec: 128965.6454
Total data:   49.59 MiB
Size/request: 13 B
Size/sec:     1.60 MiB
```
this PR (hello world):
```
❯ oha -c 125 -n 4000000 --no-tui --disable-compression http://localhost:8000
Summary:
Success rate: 100.00%
Total:        28.4050 secs
Slowest:      0.0085 secs
Fastest:      0.0001 secs
Average:      0.0009 secs
Requests/sec: 140820.2060
Total data:   49.59 MiB
Size/request: 13 B
Size/sec:     1.75 MiB
```
---
Two changes here:
- use `opt-level` 3 for some of hyper's deps, since profile …
=> perf(http): instantiate generic functions in `deno_http`, increase opt-level for some more hyper deps

cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
=> fix(lsp): include prefix and suffix for rename edits

cli/js/40_lint_selector.js, tests/unit/lint_plugin_test.ts
The code to support regex matching on attribute values was already there. I just forgot to wire it up properly in the selector matching code.
Fixes https://github.com/denoland/deno/issues/28336
=> fix(unstable): lint plugin regex attribute selector not working

cli/js/40_lint.js, cli/js/40_lint_selector.js, cli/js/40_lint_types.d.ts, tests/unit/lint_plugin_test.ts, tests/unit/lint_selectors_test.ts
This PR adds support for field selectors (`.<field>`) in the lint plugin API. This is supported in ESLint as well, but was missing in our implementation.
```css
/* Only search the test expression of an IfStatement */
IfStatement.test
```
Fixes https://github.com/denoland/deno/issues/28314
=> feat(unstable): lint plugins support field selectors

cli/js/40_lint.js, cli/tsc/dts/lib.deno.unstable.d.ts
Noticed that we have two interfaces describing the same thing: `Fix` and `FixData`. This PR removes the `FixData` one.
=> fix(unstable/lint): remove duplicated `Fix` vs `FixData` interface

cli/tools/lint/ast_buffer/swc.rs, tests/unit/__snapshots__/lint_plugin_test.ts.snap, tests/unit/lint_plugin_test.ts
Fixes inconsistencies with `ObjectPattern` node to match TSESTree.
Fixes one issue reported in https://github.com/denoland/deno/issues/28355
=> fix(unstable): lint plugin `ObjectPattern` inconsistencies

cli/tsc/dts/lib.deno.unstable.d.ts
The `PropertyDefinition` node also allows `PrivateIdentifier` as a type for the `key`. Example:
```ts
class Foo {
#foo = 2;
}
```
Fixes one issue reported in https://github.com/denoland/deno/issues/28355
=> fix(unstable): Missing `PrivateIdentifier` type for `PropertyDefinition` key

cli/tools/lint/ast_buffer/swc.rs, tests/unit/__snapshots__/lint_plugin_test.ts.snap
The `source` and `exported` property were swapped for the `ExportAllDeclaration` node.
Fixes one issue reported at https://github.com/denoland/deno/issues/28355
=> fix(unstable): lint plugin swapped exported and source for ExportAllDeclaration

ext/node/polyfills/01_require.js, tests/specs/node/require_esm_module_exports/__test__.jsonc, tests/specs/node/require_esm_module_exports/main.cjs, tests/specs/node/require_esm_module_exports/main.out, tests/specs/node/require_esm_module_exports/string.mjs, tests/specs/node/require_esm_module_exports/undefined.mjs
* https://github.com/nodejs/node/pull/54563
Closes https://github.com/denoland/deno/issues/28352
=> fix(node): require esm should prefer `module.exports` export

cli/js/40_lint.js, cli/js/40_lint_selector.js, tests/unit/lint_plugin_test.ts
Internally, we use a group node for array-like children, which is hidden from the user. When we're asking for a parent of a node we need to take group nodes into account and walk over them.
Fixes one issue reported in https://github.com/denoland/deno/issues/28355
=> fix(unstable): lint plugin child combinator not working with groups

cli/js/40_lint.js, cli/js/40_lint_selector.js, cli/js/40_lint_types.d.ts, tests/unit/lint_plugin_test.ts, tests/unit/lint_selectors_test.ts
This PR adds support for `:has/:is/:where()` and `:not()`. The latter was already present, but found a bunch of issues with it and I'd say that it didn't really work before this PR.
Fixes https://github.com/denoland/deno/issues/28335
=> fix(unstable): lint plugin fix `:has()`, `:is/where/matches` and `:not()` selectors

cli/lsp/capabilities.rs, cli/lsp/language_server.rs
We handle semantic tokens for Deno-disabled files because we register the provider per language ID. You can see this by `Deno` being highlighted as a namespace in such files even though it's untyped. No other request is used for Deno-disabled files.
This PR delays that provider registration at least until a Deno-enabled specifier is opened for the first time.
This will allow us to, for example, lazily spin up the TS server upon first use in an Deno-enabled file (whereas previously that wouldn't work because the TS server was immediately used for semantic tokens even in a Deno-disabled file). This will reduce idle memory usage of the LSP in Node projects. I'll handle this in a follow up PR.
=> perf(lsp): register semantic tokens provider upon opening enabled doc

cli/tools/lint/ast_buffer/swc.rs, tests/unit/__snapshots__/lint_plugin_test.ts.snap
That's an emberassing typo. The `!==` operator was wrongly converted to `!=`.
Fixes https://github.com/denoland/deno/issues/28397
=> fix(unstable): lint plugin `!==` wrongly parsed as `!=`

cli/lsp/language_server.rs
These errors can be unpredictably caused by assertion failures in the TS isolate, and `codeAction/resolve` is called more eagerly by VSCode when using live share. Let's print them silently in the output panel instead of having an error popup.
If a user hits these errors normally, they'll notice via refactor changes not taking effect and can still report it. The error popup doesn't contain useful info anyway.
Ref https://github.com/denoland/deno/issues/27778#issuecomment-2607477597, #27780, #27903.
=> fix(lsp): silence errors from "codeAction/resolve"

Cargo.lock, cli/factory.rs, cli/lsp/resolver.rs, cli/rt/run.rs, resolvers/deno/factory.rs, resolvers/node/Cargo.toml, resolvers/node/lib.rs, resolvers/node/resolution.rs, tests/specs/node/types_req_export/__test__.jsonc, tests/specs/node/types_req_export/check.out, tests/specs/node/types_req_export/main.ts, tests/specs/node/types_req_export/node_modules/package/index.js, tests/specs/node/types_req_export/node_modules/package/package.json, tests/specs/node/types_req_export/node_modules/package/types-4.8.d.ts, tests/specs/node/types_req_export/node_modules/package/types-expected.d.ts, tests/specs/node/types_req_export/node_modules/package/types-fallback.d.ts, tests/specs/node/types_req_export/package.json
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html#exports-is-prioritized-over-typesversions
Part of https://github.com/denoland/deno/issues/27861
=> fix(check): support `types@` export conditions

cli/args/flags.rs
Full top missing from help text of config
=> docs: adding a missing full stop to context help text

Cargo.lock, Cargo.toml, resolvers/node/Cargo.toml, resolvers/node/resolution.rs, tests/specs/node/types_versions/__test__.jsonc, tests/specs/node/types_versions/check.out, tests/specs/node/types_versions/main.ts, tests/specs/node/types_versions/node_modules/package/index.js, tests/specs/node/types_versions/node_modules/package/package.json, tests/specs/node/types_versions/node_modules/package/sub-types.d.ts, tests/specs/node/types_versions/node_modules/package/types-4.8.d.ts, tests/specs/node/types_versions/node_modules/package/types-expected.d.ts, tests/specs/node/types_versions/package.json
Follow up to https://github.com/denoland/deno/pull/28450
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
Closes https://github.com/denoland/deno/issues/27861
=> fix(check): support `typesVersions` in npm dependencies

tools/update_typescript.md
Asynciterable as singular means it adds the concept of AsyncIterable to DOM instead of providing multiple AsyncIterable instances.
=> docs: fixed a typo in update_typescript.md

ext/fetch/26_fetch.js, ext/telemetry/util.ts, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/fetch.out, tests/specs/cli/otel_basic/fetch.ts
closes #28377
This updates the tracing of `fetch` when it resulted in an error state.
=> fix(otel/unstable): trace error cases of fetch

ext/fetch/lib.rs
Currently, there is no way to implement `FetchPermissions` without importing `FsError` from `deno_fs` directly. This PR aims to re-export the `FsError` from `deno_fetch` itself to allow it.
=> chore(ext/fetch): re-export FsError to implement FetchPermissions

ext/node/polyfills/_http_server.ts
Matches Node.js `http.STATUS_CODES` values now. Deno is currently exporting an enum directly, which 1) adds keys like `BadRequest` and 2) ships the status-text strings as non-space-delimited values (eg, `'BadRequest`` instead of `'Bad Request'`)
Current `deno repl -A` snapshot:
=> fix(ext/node): correct `STATUS_CODES` strings

cli/tsc/dts/lib.deno.shared_globals.d.ts, ext/node/polyfills/assertion_error.ts
When upgrading to Deno 2.x from 1.x I noticed that my project began to get the below error from deno-ts:
>Property 'stackTraceLimit' does not exist on type 'ErrorConstructor'.deno-ts(2339)
Looking through the deno codebase I saw that there wasa todo item to add this field, which is why I have opened this pull-request
=> fix: add stackTraceLimit to ErrorConstructor interface and removed ErrorWithStackTraceLimit interface

ext/telemetry/lib.rs, ext/telemetry/telemetry.ts, tests/specs/cli/otel_basic/__test__.jsonc, tests/specs/cli/otel_basic/events.out, tests/specs/cli/otel_basic/events.ts
Partially fixes https://github.com/denoland/deno/issues/27917: there is no attribute support, they are silently dropped and counted, not much worse that current links support.
=> feat(otel): basic event recording

ext/os/Cargo.toml
This pr explicitly enables the `sysinfoapi` feature flag on `winapi` in `deno_os`, so that `deno_os` and other deno crates that rely on it can be built independently outside of the workspace on Windows. (Closes #28557)
=> fix(ext/os): explicitly enable `sysinfoapi` feature on `winapi` dependency

ext/console/01_console.js, ext/cron/01_cron.ts, ext/http/00_serve.ts, ext/kv/01_db.ts, ext/web/06_streams.js, runtime/js/99_main.js, runtime/ops/runtime.rs, tests/specs/cli/otel_basic/http_propagators.out, tests/specs/run/045_proxy/proxy_test.ts.out, tests/specs/run/serve/__test__.jsonc, tests/specs/run/serve/ipv6_hostname.out, tests/specs/run/serve/ipv6_hostname.ts, tests/specs/run/serve/on_listen_default.out, tests/specs/run/serve/on_listen_default.ts, tests/unit/serve_test.ts
`import.meta.log` enables basic log filtering through `env_logger`/`DENO_LOG`. Log levels are supported, and filenames can also be used. for example: `DENO_LOG=ext:deno_http::00_serve.ts=warn`
=> refactor: internal logging utility

ext/node/ops/sqlite/database.rs, ext/node/ops/sqlite/mod.rs, ext/node/ops/sqlite/session.rs, ext/node/ops/sqlite/statement.rs
Improves SQLite error reporting by including  `err_code`, `err_str`, matching Node.js behavior.
Fixes #28289
=> fix(ext/node): Add SQLite error details (#28289)

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
closes #28530
In the current `http.request` implementation, we don't use underlying `Socket` class in normal way (We pass the rid (TcpConn/TlsConn) of it to hyper, and let hyper directly use it).
Because of that, 'close' event is never emitted on socket. That causes the socket leak in http agent, and that prevents some http agent for creating more sockets than `maxSockets` number (`maxSockets` is `Infinity` by default though).
`@npmcli/agent` (the agent of npm cli) is one of such agent, affected by this bug. It sets 15 to `macSockets` (ref: https://github.com/npm/agent/blob/3c71f9adb0cce1ec228c2de0ce420e4c86f7fe46/lib/options.js#L14 ), and it caused the issue #28530 
This PR fixes the above issue by propagating 'close' event from `IncomingMessage(ForClient)` to underlying `Socket` object.
=> fix(ext/node): propagate 'close' event of IncomingMessage to Socket

Cargo.lock, Cargo.toml, cli/npm/installer/resolution.rs, tests/registry/npm/@denotest/peer-dep-specific-constraint/1.0.0/index.js, tests/registry/npm/@denotest/peer-dep-specific-constraint/1.0.0/package.json, tests/specs/install/peer_dep_specific_constraint/__test__.jsonc, tests/specs/install/peer_dep_specific_constraint/install.out, tests/specs/install/peer_dep_specific_constraint/lock.out, tests/specs/install/peer_dep_specific_constraint/package.json
This improves peer dependency resolution to be more relaxed and resolve non-version matching ancestors similar to pnpm rather than introducing duplicate dependencies. Deno will warn when this occurs. In the future, we should look into introducing an option to have Deno error in this scenario.
* https://github.com/denoland/deno_npm/pull/88
Closes https://github.com/denoland/deno/issues/17263
Closes https://github.com/denoland/deno/issues/26841
=> fix(npm): resolve non-version matching peer deps and warn instead

cli/util/fs.rs
Ref https://github.com/denoland/deno/issues/26928.
This was originally a warning so potential bugs would be visible.  Now that the code has been working for a while without issues, and since the warning can be triggered in a valid case (as in the issue above, where the warnings also hid the real diagnostic), let's downgrade this from a warning to a debug log.
=> chore: downgrade warning to debug log on clonefile failure

resolvers/npm_cache/registry_info.rs
Fixes #28517.
The npm package info gets requested a bunch of times by deno_npm. Before this PR, we were loading it from the FS and parsing it each and every time. With a lot of dependencies (and large `registry.json` files), this can lead to massive blowups in install times.
From the repro in #28517
before this PR:
```
Command being timed: "deno i"
User time (seconds): 538.54
System time (seconds): 56.49
Percent of CPU this job got: 198%
Elapsed (wall clock) time (h:mm:ss or m:ss): 4:59.45
Maximum resident set size (kbytes): 378976
```
this PR:
```
Command being timed: "deno-this-pr i"
User time (seconds): 1.29
System time (seconds): 1.56
Percent of CPU this job got: 68%
Elapsed (wall clock) time (h:mm:ss or m:ss): 0:04.16
Maximum resident set size (kbytes): 500864
```
So roughly an …
=> perf(install): keep parsed npm package info in memory cache

.github/workflows/node_compat_test.yml
This PR fixes the below in node_compat_test workflow:
- The config file for testing isn't specified in `deno run` command
- git submodules are not fetched
- CI name is not aligned with the rest of workflows (`node-compat-test` -> `node_compat_test`)
=> ci: fix node_compat_test workflow

tests/node_compat/run_all_test_unmodified.ts
Currently `run_all_test_unmodified.ts` script is killed in linux CI for non obvious reason. I guess this could be caused by too much load to the cpu by using the concurrency of `navigator.hardwareConcurrency * 2`. This PR reduces it to `navigator.hardwareConcurrency`
---
CI run: https://github.com/denoland/deno/actions/runs/14097513475/job/39488256550
Error:
```
/home/runner/work/_temp/9373fec9-14cb-4227-875e-007fc328ab71.sh: line 1:  2301 Killed                  deno -A --config tests/config/deno.json tests/node_compat/run_all_test_unmodified.ts
```
=> ci: reduce the concurrency number of parallel runs to navigator.hardwareConcurrency

tests/node_compat/run_all_test_unmodified.ts
`node_compat_test` workflow currently fails on linux because of being killed by OOM killer.
The issue seems happening [here](https://github.com/nodejs/node/blob/186bbf7dfdce4e8b5963fce1ab9567ba0ce04488/test/common/index.js#L88-L116) in `test/common/index.js`, where it checks the flags given to Node.js CLI and respwan the runtime with corrected set of flags if wrong ones are given. This correction of flags doesn't work for Deno because we [map](https://github.com/denoland/deno/blob/2b4de21ea0904148dfa7c28d4e77c7b3838322f8/ext/node/polyfills/internal/child_process.ts#L1064-L1111) node.js flags to Deno's, and this leads to the infinite loop of respawning for some cases.
This PR avoid the above situation by passing `NODE_SKIP_FLAG_CHECK` env var, which skips the above re-spawn behavior.
=> ci: set NODE_SKIP_FLAG_CHECK=1 in node_compat_test workflow

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
- Fix `strip` after `codesign` on macOS pre-release step.
- Fix cwd assumption in windows pre-release step.
=> chore: fix pre-release CI for macOS and Windows

cli/lsp/language_server.rs, cli/lsp/urls.rs, tests/integration/lsp_tests.rs
Server-side change for https://github.com/denoland/vscode_deno/issues/1206. Coupled with https://github.com/denoland/vscode_deno/pull/1278.
=> fix(lsp): format vscode-userdata schemed documents

tests/specs/test/doc_duplicate_identifier/main.out, tests/specs/test/doc_failure/main.out, tests/specs/test/doc_only/main.out, tests/specs/test/doc_permission_respected/main.out, tests/specs/test/doc_ts_declare_global/lib.d.ts.out, tests/specs/test/doc_ts_expect_error/mod.out, tests/specs/test/doc_ts_namespace_decl/lib.d.ts.out, tests/specs/test/markdown_ts_expect_error/main.out
These tests were failing on the CI when it took longer than 1s.
=> chore: fix flaky tests checking for ms

tests/node_compat/run_all_test_unmodified.ts
This PR adds some metadata to node compat test result JSON file, which is necessary to show the report page better.
```json
{
"date": "2025-04-03",
"denoVersion": "2.2.5+d07b7ea",
"os": "darwin",
"arch": "aarch64",
"nodeVersion": "23.9.0",
"runId": "123456789",
"total": 3900,
"pass": 1500,
"results": {
"parallel/test-assert-async.js": [true]
"parallel/test-assert.js": [false, { "message": "error" }],
...
}
}
```
---
FYI The current prototype of the report page:
=> chore: add metadata to node compat test report

cli/util/sync/async_flag.rs
This fixes desyncs/errors/panics that can happen in the LSP if the user makes edits while `initialized` is still being handled, due to the unblocked notifications from `LanguageServer::init_flag: AsyncFlag` being resumed in the wrong order. Hard to test.
Changing the flag implementation from `CancellationToken::cancel()` to `Semaphore::close()` seems to do the job.
=> fix(lsp): preserve notification order after init flag is raised

cli/npm/installer/local.rs
We were keying on package id instead of nv.
Noticed this while looking into a bug:
```
Warning The following packages are deprecated:
┠─ npm:@aws-cdk/cloud-assembly-schema@1.204.0 (AWS CDK v1 has reached End-of-Support on 2023-06-01.
This package is no longer being updated, and users should migrate to AWS CDK v2.
For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html)
┠─ npm:@aws-cdk/cx-api@1.204.0_@aws-cdk+cloud-assembly-schema@1.204.0 (AWS CDK v1 has reached End-of-Support on 2023-06-01.
This package is no longer being updated, and users should migrate to AWS CDK v2.
For more information on how to migrate, see https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html)
┠─ npm:@aws-cdk/region-info@1.204.0 (AWS CDK v1 has reached …
```
=> fix(install): remove duplicate deprecated messages

tests/unit/serve_test.ts
This PR reduces the flakiness of the case `req.body.getReader().read() throws the error with reasonable error message`.
The case tries to cause BadResource error by premature disconnection from the client, but it sometimes completes the request when the reading of tcp data happens quickly. This PR tries to prevent that scenario by adding some delays when reading & writing http messages.
=> test(ext/http): reduce flakiness of serve_test

cli/lsp/capabilities.rs
Fixes https://github.com/denoland/vscode_deno/issues/1280.
It seems if you explicitly list a document filter in some capability configuration, it will override (not intersect) the document filter specified by the client.
=> fix(lsp): filter scheme in semantic tokens registration options

cli/lsp/analysis.rs, cli/lsp/completions.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/resolver.rs, cli/lsp/tsc.rs
Reduces some repeat hashmap lookups by exposing the `LspScopedResolver` (renamed from `LspScopeResolver` because that made me think it was resolving the scope)
=> refactor(lsp): internally expose and use `LspScopedResolver`

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Fixes #28757.
We need to retain the napi symbols in the binary. `strip` with no flags on macos strips all symbols out of the binary (including global symbols).
Only strip out the local and debug symbols from the binary, retaining the global symbols (which include the napi ones)
=> fix: only strip local and debug symbols from macOS binary

ext/node/polyfills/internal/fs/handle.ts, tests/unit_node/_fs/_fs_handle_test.ts
This PR implements the missing support for `createReadStream` and `createWriteStream` on the `FileHandler` class (as outlined in #25554)
Notably, it does so by building on top of #27591 which was presumably abandoned
=> fix(ext/node): add a createReadStream & createWriteStream methods to the FileHandle class

.github/workflows/post_publish.yml, tools/release/version_greater_latest.ts
This is for LTS releases. We'll update that txt file manually.
=> chore: skip updating release-latest.txt when current version not greater than latest version

tests/specs/bench/explicit_start_and_end_low_precision/__test__.jsonc, tests/specs/mod.rs
=> chore: skip explicit_start_and_end_low_precision test on ci

cli/task_runner.rs
`node scripts/postinstall` was not running with Deno anymore and it previously was.
Closes https://github.com/denoland/deno/issues/28780
=> fix(install): regression where Deno not used when postinstall script ran script without file extension

.github/workflows/node_compat_test.yml, tests/node_compat/.gitignore, tests/node_compat/add_day_summary_to_month_summary.ts, tests/node_compat/run_all_test_unmodified.ts
This PR adds `summary` job in `node_compat_test` workflow.
The job runs after 'test' jobs completed, downloads the daily reports for all platforms, extracts the metadata from them, and adds those metadata (summary) to monthly summary data.
The summary json data is uploaded to `dl.deno.land/node-compat-test/summary-YYYY-MM.json.gz`, which will be used by Node test result viewer tool.
The script outputed something like the below when tested locally:
```shellsession
$ deno -A --config tests/config/deno.json tests/node_compat/add_day_summary_to_month_summary.ts
fetching 2025-04
fetching 2025-04-07 windows
fetching 2025-04-07 linux
SyntaxError: Unterminated string in JSON at position 319468 (line 1 column 319469)
at parse (<anonymous>)
at eventLoopTick (ext:core/01_core.js:178:7)
at async …
```
=> chore: create monthly summary of node test runs

ext/node/ops/perf_hooks.rs
Fixes https://github.com/denoland/deno/issues/28767
Don't love the `RefCell`, but don't really see a (safe) way around it.
=> fix(node): add reset method to event loop delay histogram

.github/workflows/node_compat_test.yml
Currently the job `summary` is failing because the git submodule `tests/util/std` is unavailable. This PR fixes the checkout config in workflow's yaml.
https://github.com/denoland/deno/actions/runs/14324275694/job/40147206838#step:6:27
=> chore: fix node_compat_test workflow summary job

Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno/issues/26400. Correctly handle multi-icon icos in `deno compile --icon`.
Ref https://github.com/denoland/sui/commit/bf318ea9c847810b79d6a34a4e744b7b09630ddb
Icons in PE are very sensitive to resource table ordering. Here's what works:
We can't use `editpe`'s builtin `set_icon` because it lays out `Icon` and `Icon Group` together before/after the `RCData`. Instead, we need a custom implementation that places RCData between the icon entries. 
This means we defer `Icon Group` to always happen during `PortableExecutable::build`. After the fix:
=> fix(compile): multi icon ordering on windows

cli/tsc/dts/lib.deno.unstable.d.ts
Noticed that the `.parent` type was missing for AST nodes for our JS lint API. Whenever possible I've only specified the limited possibilities of parent types, but when it's too complex I defaulted to just `Node`.
=> fix(unstable): add parent types to lint ast nodes

cli/factory.rs, tools/lint.js
These both were >20KB. Also added `clippy::large_futures` to `lint.js` so we catch this
=> chore: box some more large futures

ext/node/polyfills/internal/child_process.ts, ext/process/40_process.js, ext/process/lib.rs, tests/unit_node/child_process_test.ts
closes #28784 
This PR adds support of `input` option in `spawnSync` API in `node:child_process`, which passes the given input as stdin of the spawned process.
=> fix(ext/node): support input option in spawnSync

.github/workflows/ci.generate.ts, .github/workflows/ci.yml
Fixes https://github.com/denoland/deno/issues/24614
=> fix: dont strip n-api symbols in `denort` on mac

tests/node_compat/slack.ts
This simplifies the chat message to something like `Linux 34.27% / Windows 34.27% / Darwin 34.63% (Full report)`
Also this uses the local copy of summary.json instead of downloading it from cloud storage (cloud storage returns from cache for 1 hour and the reported data is one day older with the current implementation).
=> chore: simplify node compat chat message

cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/swc.rs, cli/tools/lint/ast_buffer/ts_estree.rs, tests/unit/__snapshots__/lint_plugin_test.ts.snap, tests/unit/lint_plugin_test.ts
Support for decorators in the lint plugin AST was a bit half baked. This PR goes through all the places where decorators can be set in TS and supports these.
Fixes https://github.com/denoland/deno/issues/28830
=> fix(unstable): add missing decorators nodes in lint ast

cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs, tests/registry/npm/@denotest/reexport-from-non-export/1.0.0/index.d.ts, tests/registry/npm/@denotest/reexport-from-non-export/1.0.0/index.mjs, tests/registry/npm/@denotest/reexport-from-non-export/1.0.0/package.json
=> fix(lsp): exclude unmapped npm cache paths from auto-imports

tests/node_compat/config.jsonc
This test case seems flaky on darwin on CI. I suggest we should skip it on darwin for now.
ref https://github.com/denoland/deno/actions/runs/14343397447/job/40207971728
=> test(ext/node): skip running test-http-agent-maxtotalsockets.js on darwin

ext/node/polyfills/testing.ts, tests/specs/node/node_test_module/test.js
Currently the pattern below is not supported. This PR fixes it.
```js
const { test } = require('node:test');
```
towards #28837
=> fix(ext/node): export test as property of default export

ext/node/polyfills/testing.ts, tests/specs/node/node_test_module/test.js, tests/specs/node/node_test_module/test.out
This PR adds basic support of suite/describe in `node:test`
closes #27406
towards #28837
=> fix(ext/node): add basic support of suite/describe in node:test

cli/tsc/dts/lib.deno.ns.d.ts
These notes seem added by mistake? (ref https://github.com/denoland/deno/pull/22234 )
The release post didn't mention the stability of them https://deno.com/blog/v1.41
=> docs: fix stability note of isTerminal and setRaw

cli/npm/installer/common/lifecycle_scripts.rs, cli/npm/installer/common/mod.rs, cli/npm/installer/local.rs, tests/registry/npm/@denotest/extra-info/1.0.0/package.json, tests/specs/install/package_extra_nmd/__test__.jsonc
Fixes #28891
We were checking if the node_modules entry for the package was present, but then reading from the global cache.
Instead, read from the package.json in node_modules. As a fallback(which in theory should only really happen if the node_modules dir is somehow messed up), take the more expensive (but likely to work) path of reading from the registry.json.
=> fix(install): read extra package info from node_modules and fallback to registry

.github/workflows/cargo_publish.yml
This should make the "forward release commit" CI job actually work. The issue was that actions/checkout by default does a shallow clone (fetch-deptg == 1), so then when we tried to cherry-pick it would fail due to missing the history. That's why the cherry-pick would work fine locally, but fail every time in CI
=> chore: don't shallow clone in publish job

tests/node_compat/common.ts, tests/node_compat/run_all_test_unmodified.ts
This PR checks if the node test script uses `node:test` module, and changes the command from:
```
deno -A --quiet --unstable-bare-node-builtins --unstable-node-globals <test-file>
```
to:
```
deno test -A --quiet --unstable-bare-node-builtins --unstable-node-globals --no-check <test-file>
```
when it's used.
Note: Currently about 130 test files (3.3%) seem using `node:test` module.
=> chore: use 'deno test' command when 'node:test' is imported in run_node_test script

ext/node/polyfills/internal/webstreams/adapters.js, tests/unit_node/stream_test.ts
Fixes https://github.com/denoland/deno/issues/28905
=> fix(ext/node): Fix `Writable.toWeb()`

cli/args/flags.rs
This PR implements the suggestion given in the comment https://github.com/denoland/deno/issues/28455#issuecomment-2734956368
Now `deno check` without arguments maps to `deno check .`
=> feat(cli): `deno check` maps to `deno check .`

ext/node/polyfills/testing.ts, tests/specs/node/node_test_module/test.js, tests/specs/node/node_test_module/test.out
towards #28837 
This PR adds `assert` property of test context object, which mirrors the APIs from `node:assert`
=> fix(ext/node): add `assert` property to test context object

cli/args/flags.rs
This PR documents DENO_COVERAGE_DIR in `deno test --help` message.
related https://github.com/denoland/deno/pull/28291
=> docs(test): document DENO_COVERAGE_DIR in help message

cli/npm/installer/mod.rs
With `nodeModulesDir: auto` (and `none`, to a lesser extent), we frequently repeatedly try to cache npm packages during resolution. On a (private) fresh project, I counted that `sync_resolution_with_fs` was called 478 times over the course of a fresh build. This reduces the number of calls to 8, and doing so speeds things up substantially.
```
❯ hyperfine --warmup 2 -N "deno task build" "../deno/target/release-lite/deno task build"
Benchmark 1: deno task build
Time (mean ± σ):      3.652 s ±  0.042 s    [User: 3.285 s, System: 2.399 s]
Range (min … max):    3.587 s …  3.712 s    10 runs
Benchmark 2: ../deno/target/release-lite/deno task build
Time (mean ± σ):      1.356 s ±  0.007 s    [User: 1.961 s, System: 1.108 s]
Range (min … max):    1.345 s …  1.372 s    10 runs
Summary …
```
=> perf(npm): don't try to cache npm packages we've already cached

tests/specs/install/package_extra_nmd/__test__.jsonc
These tests are failing randomly on Windows at the moment. The PR that added them was released in Deno v2.2.10 and users haven't reported any problems so far. So temporarily ignoring these tests to unblock another patch release.
=> test: temporarily ignore `specs::install::package_extra_nmd` test

cli/npm/installer/local.rs, tests/specs/npm/deprecation_warnings_no_repeat/__test__.jsonc, tests/specs/npm/deprecation_warnings_no_repeat/main.ts, tests/specs/npm/deprecation_warnings_no_repeat/warn.out
Fixes https://github.com/denoland/deno/issues/28933.
This was a regression from the packument refactor.
=> fix(npm): only print deprecation warnings on first install

cli/lsp/diagnostics.rs, tests/integration/lsp_tests.rs
=> fix(lsp): show a diagnostic for managed npm non-existent subpaths

cli/tools/coverage/reporter.rs, cli/tools/coverage/style.css
Excuse the oversized screenshots. They were taken when scrolled to the right on a small screen. @kt3k
=> fix(coverage): improve responsiveness of HTML reporter on small screens

ext/http/00_serve.ts, ext/http/http_next.rs, ext/http/request_properties.rs, ext/http/service.rs, tests/unit/serve_test.ts
- preserve authority from protocol
- reject some invalid combinations of request lines (e.g. `GET *`)
- modify rendering of OPTIONS and CONNECT so that they don't cause `new URL` to raise.
=> fix: fix bugs with rendering of authority in serve urls

ext/node/polyfills/_fs/_fs_common.ts, ext/node/polyfills/_fs/_fs_readFile.ts, tests/unit_node/fs_test.ts
This fix allow abort signal to be correctly supported by node readFile.
Related to #28887
=> fix(ext/node): fix handling of abort signal in readFile

.github/workflows/version_bump.yml, tools/release/01_bump_crate_versions.ts
Also fixes the script for other version updates that was missed in https://github.com/denoland/deno/pull/29018.
=> chore: update "version_bump" action to allow for RC bumps

runtime/features/build.rs
Prevents the files having its modification date changed.
=> chore: stop deno_features rebuilding on each cargo build

ext/node/polyfills/_util/std_asserts.ts, tests/unit_node/assert_test.ts
closes https://github.com/denoland/deno/issues/28037
=> fix(ext/node): fix deepStrictEqual(-0, 0)

ext/node/polyfills/http.ts
This PR reduces unnecessary `.end()` call on `ServerResponse` object, and improves the http server performance of `node:http`.
- main: 13.786 kRPS
- this PR: 50.32 kRPS
=> perf(ext/node): improve node:http createServer performance

ext/node/polyfills/internal/hide_stack_frames.ts
Towards #24236. This PR replaces `Object.defineProperty` with its primordial `ObjectDefineProperty`.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/hide_stack_frames.ts`

ext/node/polyfills/http.ts
Continued from #29069
This PR improves the http server performance of `node:http` by lazily bind to abort signal of `Response` object.
main: 50.32k RPS
this PR: 85.83k PRS
server script used:
```js
import http from "node:http";
const server = http.createServer((req, res) => {
res.end("hi");
});
server.listen(3000, () => console.log("listening"));
```
wrk command:
```
wrk -t12 -c400 -d10s http://localhost:3000
```
related #28601
=> perf(ext/node): lazily listen to the abort signal of request object

ext/os/lib.rs
Since `Deno.noColor` exists, it makes sense to allow accessing
`NO_COLOR` env var without `--allow-env` permission.
=> feat: Allow access to NO_COLOR env var without --allow-env

cli/args/mod.rs, cli/main.rs, cli/standalone/binary.rs, tests/specs/compile/default_v8_flags/__test__.jsonc, tests/specs/compile/default_v8_flags/compile.out, tests/specs/compile/default_v8_flags/main.out, tests/specs/compile/default_v8_flags/main.ts
Fixes #29029
Changes:
- Passes default v8 flags alongside with other flags when compiling
=> fix(compile): pass default v8 args during compile

cli/tools/repl/mod.rs, cli/tools/repl/session.rs
Closes #28959 
At least it didn't panic
=> fix(repl): panic when user `delete globalThis.globalThis`

tests/registry/npm/@denotest/no-shasums/1.0.0/main.js, tests/registry/npm/@denotest/no-shasums/1.0.0/package.json, tests/specs/npm/no_shasums/__test__.jsonc, tests/specs/npm/no_shasums/deno.lock.out, tests/specs/npm/no_shasums/main.js, tests/specs/npm/no_shasums/package.json, tests/util/server/src/npm.rs
This was actually fixed via the deno_npm and lockfile updates, but it would be good to have an explicit entry for this in the release notes so labeling this as a "fix"
Closes https://github.com/denoland/deno/issues/27758
=> fix(npm): support registries that have no shasums or integrity

ext/node/polyfills/internal/http.ts
Towards #24236. This PR replaces `Date`, `Date` methods, and `Symbol`s with their primordial versions.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/http.ts`

Cargo.lock, Cargo.toml, cli/npm/installer/resolution.rs, cli/npm/mod.rs, tests/specs/lockfile/frozen_lockfile/frozen_package_json_changed.out, tests/specs/lockfile/frozen_lockfile/frozen_package_json_changed_install.out, tests/specs/lockfile/jsx_import_source_and_types/deno.lock.out, tests/specs/outdated/deno_json/update_latest/deno.lock.out, tests/specs/outdated/package_json/update_latest/deno.lock.out, tests/specs/run/lazy_dynamic_imports/lock.out
Lockfile v5 hasn't stabilized yet, so going to do this breaking change in order to make the property names shorter.
* https://github.com/denoland/deno_lockfile/pull/49
=> fix: break unstable lockfile v5 to remove "has" from property names

cli/main.rs, cli/rt/run.rs
Issue #20602
Builds on top of #29064
For now it is just looking at the DENO_SINGLE_THREADED env var. When set it adds `--single-threaded` to the default v8 flags and runs `init_platform` with `v8::Platform::new_single_threaded(true)`.
Enabling could rely on just the v8 flags `--single-threaded` but I guess it should probably be a cli flag as there are other deno features that rely on threads and these should likely be either disabled or run from the main thread when in single threaded mode.
=> feat(cli): support `--single-threaded` v8 flag

Cargo.lock, Cargo.toml, cli/args/flags.rs, cli/factory.rs, cli/file_fetcher.rs, cli/lsp/language_server.rs, cli/lsp/registries.rs, cli/main.rs, cli/npm/installer/local.rs, cli/npm/installer/mod.rs, cli/tools/clean.rs, cli/tools/installer.rs, cli/tools/pm/mod.rs, cli/tools/pm/outdated/mod.rs, resolvers/deno/factory.rs, tests/specs/clean/entrypoint/__test__.jsonc, tests/specs/clean/entrypoint/jsr_http1.ts, tests/specs/clean/entrypoint/jsr_http2.ts, tests/specs/clean/entrypoint/jsr_http_cleaned.out, tests/specs/clean/entrypoint/jsr_http_init.out, tests/specs/clean/entrypoint/npm_clean_dry_run.out, tests/specs/clean/entrypoint/npm_cleaned.out, tests/specs/clean/entrypoint/npm_init.out, tests/specs/clean/entrypoint/print-dir.ts, tests/specs/clean/entrypoint/rewrite.ts, tests/specs/clean/entrypoint/vendor1.ts, tests/specs/clean/entrypoint/vendor2.ts, tests/specs/clean/entrypoint/vendor_clean_output.out, tests/specs/clean/entrypoint/vendor_cleaned.out, tests/specs/clean/entrypoint/vendor_init.out
Closes https://github.com/denoland/deno/issues/27229.
TODO:
=> feat(clean): `deno clean --except <paths>`, remove all cache data except what's needed to run `paths`

ext/http/00_serve.ts, ext/node/polyfills/http.ts, tests/specs/node/wrapped_http_response/__test__.jsonc, tests/specs/node/wrapped_http_response/main.ts, tests/specs/node/wrapped_http_response/response.ts, tests/unit_node/http_test.ts
Fixes https://github.com/denoland/deno/issues/28022
Will circle back to add a test + clean up a bit.
Basically drizzle-kit studio uses hono with the node-server adapter. That creates wrapper objects for responses that forward property getters to the underlying response (the one we provided). However, in deno.serve we were assuming that the response was actually the same response we initially gave and crashed when it wasn't. instead, just call the property getters if we can't find the inner response.
The raw headers bug is that we were exposing the `rawHeaders` field on `Incoming` as a `Headers` object, instead it's supposed to be a flat array of the header keys + values. I.e. `["Content-Type:", "application/json", "Host:", "http://localhost"]`
=> fix(ext/node): work correctly with wrapper Response objects, use correct `rawHeaders` structure

cli/schemas/config-file.v1.json, tests/specs/check/erasable_syntax_only/__test__.jsonc, tests/specs/check/erasable_syntax_only/deno.json, tests/specs/check/erasable_syntax_only/error.out, tests/specs/check/erasable_syntax_only/main.ts
Only when using `--check` or `deno check`. Doesn't have this hooked up as part of the swc emit.
* https://github.com/denoland/deno_config/pull/166 (deno_config upgrade happened in a separate PR)
Finishes adding it to the json schema and adds a test to ensure it continues to work.
Closes https://github.com/denoland/deno/issues/28936
=> feat(check): support erasableSyntaxOnly for type checking

ext/http/00_serve.ts, ext/http/lib.rs, tests/integration/serve_tests.rs
if `duplicate` is passed in DENO_SERVE_ADDRESS, use its value to create a second listener instead of overriding the options the user passed.
=> feat: DENO_SERVE_ADDRESS duplicate option

cli/tsc/97_ts_host.js, tests/integration/lsp_tests.rs
Fixes part of https://github.com/denoland/vscode_deno/issues/1288.
=> fix(lsp): ignore 'for await' diagnostics in jupyter cells

Cargo.lock, Cargo.toml, cli/args/mod.rs, resolvers/deno/factory.rs
Test is in:
* https://github.com/denoland/deno_cache_dir/pull/78
This removes the `moduleGraphX` data from the `<version>_meta.json` files for jsr packages when copying from the global cache to the local one. This property is not really useful to vendor because it's just a performance optimization when downloading the files and someone may be changing the data in the files leading to the `moduleGraph` data to be out of date.
Closes #28427 (I don't believe there's anything else we could or should strip)
=> fix(vendor): strip jsr version meta module graph data

Cargo.lock, Cargo.toml
* https://github.com/denoland/deno_npm/pull/102
Closes https://github.com/denoland/deno/issues/29128
=> fix(npm): handle global cache missing version in pkg info of pkg existing in npm snapshot

ext/node/polyfills/internal/options.ts
Towards #24236. This PR replaces `Map` and `String` methods with their primordial versions.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/options.ts`

tests/specs/cli/v8_single_threaded/__test__.jsonc, tests/specs/cli/v8_single_threaded/main.ts
Tests for #29066.
These only run on linux since they get thread names from /proc.
=> test(cli): test support --single-threaded v8 flag

resolvers/npm_cache/lib.rs, resolvers/npm_cache/registry_info.rs
Noticed we missed doing this when looking through this code.
```sh
> cat package.json
{
"dependencies": {
"dax-sh": "^0.43.0",
"next": "^15.3.1",
"ts-morph": "^25.0.1"
}
}
> hyperfine --warmup=1 "V:\deno\target\release\deno_main.exe install --no-lock" "V:\deno\target\release\deno.exe install --no-lock"                                
Benchmark 1: V:\deno\target\release\deno_main.exe install --no-lock
Time (mean ± σ):     198.5 ms ±   3.2 ms    [User: 166.8 ms, System: 38.6 ms]                                                                                                                                                                                                                             
Range (min … max):   192.7 ms … 203.3 ms    14 runs
Benchmark 2: V:\deno\target\release\deno.exe …
```
=> perf(npm): deserialize cached npm packuments on blocking task

resolvers/npm_cache/tarball_extract.rs
Seems https://github.com/denoland/deno/pull/29138 broke https://github.com/dsherret/ts-ast-viewer/pull/167
I don't see anything else in that PR that could have caused this strange error, so going to try this change. I'm also not able to reproduce locally.
=> chore: try reverting tarball unpack change

cli/tsc/dts/lib.deno.ns.d.ts
`Deno.env.get` returns undefined when the environment variable is not present. I initially interpreted this doc string to indicate that it would return the string literal `"undefined"`, which isn't right.
Could use backticks here as above, but a little confusing in a JS context where this also indicates a (template) string literal.
=> docs: remove quotes around `undefined` in Deno.env.get example

cli/main.rs, cli/tools/serve.rs
Support the unconfigured runtime when using `deno serve`.
=> feat: support unconfigured runtime in serve subcommand

cli/main.rs, tests/specs/run/unconfigured/main.out
these should be newline terminated
=> fix: terminate control sock event with newline

ext/node/polyfills/_process/streams.mjs, tests/unit_node/process_test.ts
Fixes https://github.com/denoland/deno/issues/28605
Fixes https://github.com/denoland/deno/issues/29175
` ../deno/target/debug/deno run -A npm:create-vue@latest DIR` works now
=> fix(ext/node): `getColorDepth` for writable stdio streams

ext/node/polyfills/_fs/_fs_mkdtemp.ts
=> fix(ext/node): use primordials in ext/node/polyfills/_fs/_fs_mkdtemp.ts

Cargo.lock, Cargo.toml
Fixes https://github.com/denoland/deno_ast/pull/304 .
This only affects actual string literals in the source code inside a JSX expression.
=> fix(precompile): escape string literal jsx children

cli/factory.rs, cli/lsp/resolver.rs, cli/resolver.rs, resolvers/deno/factory.rs, resolvers/deno/graph.rs, resolvers/deno/lib.rs
1. Renames `DenoResolver` to `RawDenoResolver`
2. Renames `DenoGraphResolver` to `DenoResolver`
3. Shifts down creation of `DenoGraphResolver` and `HasPackageJsonDepFlag` to `ResolverFactory`
=> refactor: move more code into ResolverFactory

ext/node/ops/http.rs, ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
Co-authored-by: Divy Srivastava <dj.srivastava23@gmail.com>
Closes https://github.com/denoland/deno/issues/20255
=> fix(ext/node): support http over unix sockets

ext/node/polyfills/http.ts, tests/unit_node/http_test.ts
This PR sets `ServerRsposne.req` properly. See https://github.com/nodejs/node/blob/e38ce27f3ca0a65f68a31cedd984cddb927d4002/lib/_http_server.js#L201
Fixes https://github.com/denoland/deno/issues/29209
=> fix(node:http): `ServerResponse.req` not set

cli/js/40_lint.js, cli/js/40_lint_types.d.ts, cli/tools/lint/ast_buffer/buffer.rs, cli/tools/lint/ast_buffer/swc.rs, cli/tools/lint/ast_buffer/ts_estree.rs, cli/tsc/dts/lib.deno.unstable.d.ts, tests/specs/lint/lint_plugin_comments/__test__.jsonc, tests/specs/lint/lint_plugin_comments/comments.out, tests/specs/lint/lint_plugin_comments/deno.json, tests/specs/lint/lint_plugin_comments/main.ts, tests/specs/lint/lint_plugin_comments/plugin.ts
This PR adds support for comments in the AST for lint plugins.
- The `Program` node has a `comments` field pointing to an array of all comments.
- `SourceCode.getAllComments()`: Returns all comments (same as `program.comments`)
- `SourceCode.getCommentsBefore(node)`: Get all comments before this Node
- `SourceCode.getCommentsAfter(node)`: Get all comments after this Node
- `SourceCode.getCommentsInside(node)`: Get all comments inside this Node
ESLint docs:
- https://eslint.org/docs/latest/extend/custom-rules#accessing-the-source-code
- https://eslint.org/docs/latest/extend/custom-rules#accessing-comments
=> feat(unstable): support comments in lint plugin

tests/node_compat/run_all_test_unmodified.ts
Will actually show test error instead of "error: Test failed"
=> test: Capture output of failing node compat tests

cli/args/flags.rs
Adds support for the --env-file flag, allowing environment variables such as DENO_AUTH_TOKENS to be loaded from a file.
=> fix(cache): added support for the --env-file flag

ext/node/ops/sqlite/database.rs, ext/node/ops/sqlite/session.rs, ext/node/ops/sqlite/statement.rs, tests/unit_node/sqlite_test.ts
Deterministic close and releases file lock on Windows.
Fixes https://github.com/denoland/deno/issues/29033
=> fix(ext/node): hold weak reference to sqlite database in instances

cli/tools/coverage/style.css
This PR adds `color-scheme: light dark` support for the HTML coverage report. It uses `light-dark(#fff, #000)` to provide colors for each color scheme.
- There's been [one other change to `coverage/style.css` file before](https://github.com/denoland/deno/commit/66185e0d1d6d52761fdebdd6b89016eaf82a6e28), so is it fine to to change this file more or should this file stay close to Istanbul original code?
- I don't think there's any existing tests for the styles, so I could not see any easy way to add unit tests for these changes
- IMO these changes work without a theme toggle, but I could try adding one [with some `<head>` script](https://github.com/denoland/deno/blob/main/cli/tools/coverage/reporter.rs/#L533) and a button in the navbar if required to land this PR
<details> …
=> feat(coverage): add dark-mode to HTML coverage report

ext/node/polyfills/assert.ts, tests/unit_node/assert_test.ts
#29226 added CallTracker via default export of `node:assert`. This PR adds it as named export of `node:assert` as well.
=> fix(ext/node): export CallTracker as named export

ext/node/polyfills/internal/querystring.ts
Towards #24236. Replaces JS intrinsics with equivalent primordial versions.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/querystring.ts`

ext/node/polyfills/internal/crypto/util.ts, tests/unit_node/crypto/crypto_cipher_test.ts
Fix https://github.com/denoland/deno/issues/29047
=> fix(ext/node): add AES CTR to supported ciphers list

cli/tsc/97_ts_host.js, cli/tsc/99_main_compiler.js, tests/specs/check/check_non_normalized_specifier/__test__.jsonc, tests/specs/check/check_non_normalized_specifier/main.ts
Fixes #29247.
Removes machinery added in #9357. That fix wasn't in effect anymore because `normalizedToOriginalMap` was duplicated in some refactor and one of them was dead code. And I doubt the underlying loading issue affecting `Deno.emit()` still exists.
=> fix(check): don't assert unique normalized specifiers

cli/tools/upgrade.rs
In Deno 2.3.0, the version was accidentally released as `2.4.0`. This was fixed in 2.3.1. Now anyone who upgraded to 2.3.0 can't run `deno upgrade` to upgrade to 2.3.1 because of this upgrade behaviour. It would be better to just always go to the latest remote specified version when someone runs `deno upgrade`.
This also fixes a bug outlined in https://github.com/denoland/deno/issues/29016
Closes https://github.com/denoland/deno/issues/29016
=> fix(upgrade): skip version comparison when upgrading

Cargo.lock, Cargo.toml
Upgrades to swc_ecma_parser 13 and deno_ast 0.47.
* https://github.com/denoland/deno_ast/pull/306
Second attempt doing this as v8 bug has been fixed.
Closes https://github.com/denoland/deno/issues/29031
=> fix: use v8 instead of swc for explicit resource management

ext/node/polyfills/internal/normalize_encoding.mjs
Towards #24236. Replaces the `.toLowerCase` method with its equivalent primordial method.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/normalize_encoding.mjs`

tools/release/release_doc_template.md
We're gonna be cutting patch release from `main` branch from now on.
=> ci: Update release doc template

Cargo.toml, cli/tools/run/mod.rs, ext/telemetry/lib.rs
This commit adds "boot_failure" and "uncaught_exception"
events that are sent when a worker crashes during `deno run`.
=> feat(otel): add events for boot failure and uncaught error

ext/node/polyfills/internal/net.ts
Towards #24236. Replaces `Symbol`, `RegExp` and its instance method, `.test()`, with primordial equivalents.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/net.ts`

cli/tsc/dts/lib.deno.ns.d.ts
I noticed these typos by accident, and it is easy to fix. So, I directly made a PR for it.
=> docs(dts): fix typos in API docs

cli/args/flags.rs, cli/lib/worker.rs, runtime/web_worker.rs, runtime/worker.rs
This commit adds a signal handler for SIGUSR2 that helps reduce the memory usage of both main worker and web worker by:
1. Triggering `malloc_trim(0)` to release memory back to the system
2. Invoking V8 isolate's `low_memory_notification` function
This is only available on Linux and enabled when `DENO_USR2_MEMORY_TRIM` env var is specified.
=> feat(runtime): add SIGUSR2 handler for low memory notifications

cli/lsp/testing/execution.rs, cli/tools/test/mod.rs, tests/integration/lsp_tests.rs
fix https://github.com/denoland/vscode_deno/issues/1297
This displays the LSP errors in the correct line instead of displaying them in the `Deno.test` line. This gives us a much nicer user experience when a test has multiple assertions.
I originally wanted to hook up the `expected` and `actual` reporters of the LSP as well, but decided against it, since that functionality can also be mimiced by having a smarter `assertEquals` function in the Deno standard library https://github.com/denoland/std/issues/6645
=> feat(lsp): display JsErrors at their original line

ext/node/polyfills/testing.ts
Ref https://github.com/denoland/deno/issues/29360 and https://github.com/denoland/deno/issues/28837. Needed for `node:sqlite` tests
=> fix(ext/node): implement `before` and `after` hooks in `node:test`

cli/main.rs, tests/testdata/coverage/complex_test.ts
This was missed in https://github.com/denoland/deno/pull/28291
This PR fixes the env var set when code coverage is enabled.
This prepares for supporting coverage from child process https://github.com/denoland/deno/issues/16440
=> fix(coverage): pass DENO_COVERAGE_DIR env var correctly

cli/tsc/dts/lib.deno.unstable.d.ts, ext/webgpu/byow.rs, ext/webgpu/surface.rs
In the WebGPU specification, we can find that when the canvas resizes, the WebGPU context would reconfigure automatically[^resize].
When using wgpu, when the window size changes, the surface should be reconfigured with the appropriate width and height[^wgpu-resize].
After comprehensive consideration, I chose this solution, adding a `resize` method to `UnsafeWindowSurface` to automatically reconfigure the surface or canvas when invoked.
The following are questions you may ask:
> Why not put this method on `GPUCanvasContext` or adding optional `width` and `height` members to `GPUCanvasConfiguration`?
- To be consistent with the specification, `GPUCanvasConfiguration` in the specification does not have `width` and `height` members;
- To be consistent with the `present` method. Prestation and …
=> feat(UNSTABLE/byow): add resize method for UnsafeWindowSurface

tests/node_compat/run_all_test_unmodified.ts
`run_all_test_unmodified.ts` missed running `.mjs` test scripts in Node test cases. This PR fixes it.
Note: There are 196 .mjs test cases in vendored node test cases. This seems affecting node compat result in a negative way (I got the number `1482/4125 (35.93%)` from the local run)
Note: There seems no `.ts` or `.cjs` test cases (They only appear in fixtures), but I also added them just in case.
=> test(ext/node): run .mjs test files

cli/args/flags.rs
Fixes a typo in the description of the DENO_EMIT_CACHE_MODE help description.
closes: #29394
=> fix(cli): Correct a small typo in help output

ext/node/ops/require.rs, tests/registry/npm/@denotest/require-non-existent/1.0.0/index.cjs, tests/registry/npm/@denotest/require-non-existent/1.0.0/package.json, tests/specs/node/global_cache_node_modules_perm_checks/__test__.jsonc, tests/specs/node/global_cache_node_modules_perm_checks/main.js, tests/specs/node/global_cache_node_modules_perm_checks/main.out
This change specifically allows op_require_stat to stat node_module directories without having to go through the permission system.
Closes https://github.com/denoland/deno/issues/20484
=> fix(node): do not require permission checks for require's node_modules stats

tests/integration/check_tests.rs, tests/specs/run/_017_import_redirect/017_import_redirect.ts, tests/specs/run/_017_import_redirect/017_import_redirect.ts.out, tests/specs/run/_017_import_redirect_check/017_import_redirect.ts, tests/specs/run/_017_import_redirect_check/017_import_redirect.ts.out, tests/specs/run/_017_import_redirect_info/017_import_redirect.ts, tests/specs/run/_017_import_redirect_info/017_import_redirect_info.out, tests/specs/run/_017_import_redirect_vendor_dir/017_import_redirect.ts, tests/specs/run/_017_import_redirect_vendor_dir/017_import_redirect.ts.out, tests/testdata/run/017_import_redirect.ts
Fix #29396
As a quick workaround, I quit using `gist.githubusercontent.com` and switched to `docs.deno.com`.
cc: @dsherret
=> chore(tests): use docs.deno.com in tests to prevent GitHub rate limits

cli/module_loader.rs, ext/node/lib.rs, ext/node/ops/require.rs
It doesn't make sense for the global resolver to search for npm packages because the structure of the folder there doesn't do node_resolution.
Also fixes https://github.com/denoland/deno/issues/20484
Probably doing this in addition to https://github.com/denoland/deno/pull/29397 would be good.
=> fix(node): do not look up node_module paths when using global resolver

rust-toolchain.toml, tests/unit/rename_test.ts
Rust 1.85.1 releases: https://github.com/rust-lang/rust/releases/tag/1.85.1
Rust 1.85.1 releases log has `std::fs::rename` fix PR
`Deno.renameSync` API error with CI test, Perhaps it is caused by this PR, when I try to upgrade `Rust 1.86.0` or `Rust 1.87.0`
Here use CI to test.
=> chore: Rust 1.85.1

ext/node/polyfills/internal/util.mjs
Towards #24236. Replaces JS builtins with equivalent primordials.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/util.mjs`

Cargo.lock, Cargo.toml, cli/tools/fmt.rs, tests/specs/fmt/external_formatter/badly_formatted.in, tests/specs/fmt/external_formatter/syntax_error_in_css.out, tests/specs/fmt/external_formatter/well_formatted.out, tests/specs/fmt/external_formatter/well_formatted_unstable_sql.out, tests/specs/fmt/external_formatter/well_formatted_use_tabs.out
fixes https://github.com/denoland/deno/issues/29337
This PR allows expressions in css template literals to be used as key-value pair replacement.
~~depends on https://github.com/dprint/dprint-plugin-typescript/pull/712~~ published
=> fix(fmt): allow expressions used as key-value pair in css template literals

ext/node/polyfills/internal/child_process.ts
Unavailability of these flags cause many errors in node compat test (See https://node-test-viewer.deno.dev/results/2025-05-26/linux.errors.txt ). This unblocks those failures
=> fix(ext/node): ignore some Node.js specific flags

ext/node/global.rs
Handle other contexts gracefully instead of panicking.
Fixes: https://github.com/denoland/deno/issues/29482
=> fix: don't unwrap in global interceptor

ext/telemetry/lib.rs
This commit adds signal handlers that flush telemetry data
before the process is terminated.
=> fix(otel): flush data when terminating signal is received

tools/release/release_doc_template.md
Changes URL of GH release - the one used previously doesn't
work correctly, since GH uses something like 
`<org>/<repo>/releases/tag/untagged-<hash>` for draft releases. 
AFAICT it's too cumbersome to figure this hash programatically.
=> ci: update release template

ext/node/polyfills/internal/errors.ts, tests/node_compat/test/common/index.js
Fixes `parallel/test-buffer-from.js` in daily Node compat tests runs. The test was already enabled in CI but that used a different helper than the daily Node compat tests runners - updated now.
```
divy@divy-macbook deno % deno -A ./tools/node_compat_tests.js -f parallel/test-buffer-from
Found 0 sequential tests and 1 parallel tests
Running 1 tests
1 FAIL parallel/test-buffer-from.js
FAIL parallel/test-buffer-from.js
exit code: 1
error: Uncaught (in promise) AssertionError: Values are not equal:
[Diff] Actual / Expected
-   The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received type function ([Function (anonymous)])
+   The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an …
```
=> fix(ext/node): fix function error message in `invalidArgTypeHelper`

ext/node/ops/sqlite/database.rs
Extracted from https://github.com/denoland/deno/pull/29404
=> fix(ext/node): make DatabaseSync `readOnly` optional

Cargo.toml, ext/process/lib.rs
The rust standard library has a fast path for process spawning, where it will use `posix_spawn` instead of `fork` + `exec`. In order to take that fast path, you can't have a `pre_exec` hook and you have to pass an absolute path for the program path.
We were already resolving the program path, but we were unconditionally doing a `pre_exec` hook. This PR makes the `pre_exec` hook conditional, which lets us take the fast path in most cases.
**Results**
on an m3 max
canary:
```
took 318755.68ms
```
this PR:
```
took 17184.64ms
```
So an improvement from 318.76 seconds to 17.18 seconds, or about 18.5x faster
**Benchmark**:
```js
import { fileURLToPath } from "node:url";
const performance = globalThis.performance;
const __filename = fileURLToPath(import.meta.url);
async function spawn() {
const …
```
=> perf(process): make sure we can take process spawning fast path on unix

Cargo.lock, Cargo.toml
This is a revert
* https://github.com/denoland/deno_graph/pull/589
=> fix: revert back to prefering highest previously resolved version for a req

cli/tools/bundle/mod.rs, tests/specs/bundle/multiple_entries/__test__.jsonc, tests/specs/bundle/multiple_entries/src/bar/helper.ts, tests/specs/bundle/multiple_entries/src/bar/main.ts, tests/specs/bundle/multiple_entries/src/foo/helper.ts, tests/specs/bundle/multiple_entries/src/foo/main.ts
=> fix(bundle): fix handling of multiple entrypoints

cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs
This moves a bunch of work from outside to inside the request handlers in `cli/lsp/tsc.rs`.
This is partially towards https://github.com/denoland/deno/pull/20695#issuecomment-2954142098, which relates to the TODO at: https://github.com/denoland/deno/blob/b575a6bfb147d18f33288c977ec38a2143138c28/cli/lsp/tsc.rs#L4374-L4377 i.e. making more module metadata available where `denormalize()` is called without adding each thing to every tsc request signature.
=> refactor(lsp): pass module parameters to tsc requests

cli/util/extract.rs
fixes https://github.com/denoland/deno/issues/29629
skips wrapping code snippet in `Deno.test` if it already has one.
`````md
```ts
import { assertEquals } from "@std/assert/equals";
Deno.test("add", () => {
assertEquals(1 + 2, 3);
});
```
`````
this feature is useful when doctest itself uses `Deno.test` inside the snippet, such as https://docs.deno.com/examples/mocking_tutorial/.
known issues: will false-positive on `Deno.test` inside multiline comments but such cases would be rare
=> fix(test): handle snippet containing `Deno.test` in doc test 

Cargo.lock, tests/specs/fmt/external_formatter/badly_formatted.in, tests/specs/fmt/external_formatter/well_formatted.out, tests/specs/fmt/external_formatter/well_formatted_unstable_sql.out, tests/specs/fmt/external_formatter/well_formatted_use_tabs.out
closes #29686
If a semicolon is omitted after the last statement expression (`${SOME_STYLE}` in below) in a block in CSS template literal:
```js
css`
a {
${SOME_STYLE}
}
`;
```
This currently results in parse error of css and can't be formatted.
The root cause of this is fixed in upstream css parser raffia (https://github.com/g-plane/raffia/issues/11). This PR upgrades raffia to the latest and avoids the above issue.
Note: The example above now formats to the below:
```js
css`
a {
${SOME_STYLE};
}
`;
```
=> fix(fmt): allow omission of semicolon in certain cases in css template

ext/node/polyfills/_fs/_fs_watch.ts, tests/unit_node/_fs/_fs_watch_test.ts
The condition was not working correctly because it compared two Date objects directly, which always results in false even if they represent the same timestamp. The fix uses .getTime() to compare numeric values instead.
Ref: #29421
=> fix(ext/node): fix fs.watchFile trigger

tests/unit_node/_fs/_fs_watch_test.ts
A test case in `tests/unit_node/_fs/_fs_watch_test.ts` seems flaky after landing #29659 
This PR tries to fix it
=> test(ext/node): reduce flakiness of _fs_watch_test.ts

Cargo.lock, cli/tsc/dts/lib.deno.ns.d.ts, ext/fetch/22_http_client.js, ext/fetch/Cargo.toml, ext/fetch/lib.rs, ext/fetch/proxy.rs, ext/tls/lib.rs, runtime/snapshot_info.rs, tests/unit/fetch_test.ts
This commit adds support for using [vsock](https://man7.org/linux/man-pages/man7/vsock.7.html) transport in fetch API on Linux and macOS.
Similar to #29154, a vsock transport can be specified in the `proxy` field when calling `Deno.createHttpClient`.
```ts
const client = Deno.createHttpClient({
proxy: {
transport: "vsock",
cid: 2,
port: 80,
},
});
await fetch("http://localhost/ping", { client });
```
=> feat(ext/fetch): add support for fetch on vsock sockets

ext/node/polyfills/internal/crypto/cipher.ts, ext/node/polyfills/internal/crypto/sig.ts
This PR replaces deprecated `new Buffer` call with `new FastBuffer` in internal code.
=> refactor(ext/node): use FastBuffer in internal code

tests/unit_node/_fs/_fs_watch_test.ts
This test was added in https://github.com/denoland/deno/pull/29659 and
an attempt to make it more stable was done in https://github.com/denoland/deno/pull/29699.
Unfortunately it's still very flaky. Ignoring for now.
CC @kt3k
=> test: disable _fs_watch_test.ts test case

ext/http/http_next.rs, ext/http/request_properties.rs
See https://github.com/denoland/deno/issues/29268 for the related discussion. @devsnek @marvinhagemeister
These are two patches I missed with the initial PR (https://github.com/denoland/deno/pull/29354)
=> fix: support virtio vsock only on systems on which it is available (remainder)

ext/napi/js_native_api.rs
See https://github.com/napi-rs/napi-rs/issues/2708#issuecomment-2963957944 for the context.
In current implementation, the Weak `Reference` is created with `v8::Weak::with_finalizer`, but there is no guarantee as to *when* or even *if* the finalization callback: https://github.com/denoland/rusty_v8/blob/v137.2.0/src/handle.rs#L623-L627. It may cause the memory leak if Node-API caller want to do some cleanup jobs in the finalization callback.
=> fix(ext/napi): ensure the finalizer callback will be called

cli/tools/installer.rs
Quite common, for example:
- @slidev/cli
- @vue/cli
- @nestjs/cli
- @angular/cli
- @expo/cli
came across this while opening https://github.com/slidevjs/slidev/pull/2201
=> fix(install): infer name from @scope/cli pattern

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, tests/integration/lsp_tests.rs
Fixes part of #21079. It doesn't address the issue in the kernel specification that prevents you from selecting TSX as a cell type in the first place (I brute-forced by editing the `.ipynb` JSON to test this).
=> fix(lsp): respect media type for tsx jupyter cells

runtime/ops/bootstrap.rs
Currently broken on main due to `SnapshotOptions` not being in op state
=> chore: fix internal hmr feature

ext/node/global.rs, ext/node/polyfills/01_require.js, runtime/js/99_main.js, tests/registry/npm/@denotest/check-worker-globals/1.0.0/inverse.js, tests/registry/npm/@denotest/check-worker-globals/1.0.0/package.json, tests/specs/npm/compare_globals/main.out, tests/specs/npm/workers/main.out, tests/specs/npm/workers/main.ts, tests/specs/npm/workers/worker4.mjs, tests/specs/npm/workers/worker5.mjs
Follow up to https://github.com/denoland/deno/pull/29543 that does
the same for `self` global. Unfortunately this omission led to a problem
described in https://github.com/denoland/deno/issues/29726 where
packages started thinking that they are being run in a web worker
context (because they are!) but the expected "self" global is not
there.
=> fix: remove `self` from global middleware

ext/node/polyfills/internal/crypto/cipher.ts
Part 1 towards enabling `parallel/test-crypto-authenticated.js`
Ref https://github.com/denoland/deno/issues/29637
=> fix(ext/node): throw invalid state from `getAuthTag`

tests/util/server/Cargo.toml
`win32job` doesn't declare `windows` as a target specific dependency
https://github.com/ohadravid/win32job-rs/blob/main/Cargo.toml
=> fix: move win32job under windows dependencies in tests/util/server

ext/node/polyfills/internal/event_target.mjs
Towards #24236. Replaces JS builtins with equivalent primordials.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal/event_target.mjs`

Cargo.lock, cli/Cargo.toml, tests/Cargo.toml
The tests crate doesn't have a dependency on deno_core.
Amendment to https://github.com/denoland/deno/pull/29794
=> chore: move unsafe_use_unprotected_platform feature to cli dev dep

Cargo.lock, cli/args/flags.rs, cli/lib/Cargo.toml, cli/lib/args.rs
This allows loading a base64 encoded cert directly from arg/env by prefixing it with `base64:`
=> feat: allow base64 ca cert in args

cli/tools/bundle/mod.rs, cli/tools/bundle/transform.rs, tests/specs/bundle/import_meta_main/__test__.jsonc, tests/specs/bundle/import_meta_main/a.ts, tests/specs/bundle/import_meta_main/b.ts, tests/specs/bundle/import_meta_main/main.ts
For entrypoints, it remains untouched. For non-entrypoints it becomes `false`.
=> fix(bundle): transform import.meta.main

cli/args/flags.rs, cli/factory.rs, cli/lib/worker.rs, cli/rt/run.rs, runtime/js/99_main.js, runtime/worker_bootstrap.rs, tests/specs/serve/auto_serve/__test__.jsonc, tests/specs/serve/auto_serve/main.ts, tests/specs/serve/auto_serve/main_not_win.out
This commits adds `DENO_AUTO_SERVE` env var, that when specified
makes `deno run` behave like `deno serve` if the entrypoint satisfies the
`Deno.ServeDefaultExport` interface.
=> feat: add `DENO_AUTO_SERVE` env var

tests/node_compat/run_all_test_unmodified.ts
There are 19 tests in `test/known_issues` dir in node compat test. They are not expected to pass even in Node.js. See https://github.com/nodejs/node/commit/32e1f9d0b54fa7c90077b41d763ffd8d0532a0a1
This change excludes them from the test target.
=> chore(ext/node): exclude known_issues dir from test targets

cli/args/flags.rs, cli/lib/args.rs, cli/main.rs, tests/specs/node/unstable_detect_cjs/no_type_field/__test__.jsonc, tests/specs/run/node_prefix_missing/__test__.jsonc, tests/specs/run/sloppy_imports/__test__.jsonc
This commit adds the `DENO_COMPAT` env var, that
when specified enables several features:
- --unstable-bare-node-builtins
- --unstable-detect-cjs
- --unstable-sloppy-imports
With Deno v2.3.x, it is a common situation where these 3 flags have to specified
to run an existing Node.js project, causing a friction that many users experience.
The idea is that this env var could be "set and forget" for many people, that should
provide better DX for running Node.js projects.
It is necessary to note that using this env var _impacts performance_ - especially startup
time.
=> feat: add `DENO_COMPAT` env var

cli/tools/bundle/mod.rs, tests/integration/watcher_tests.rs, tests/specs/bundle/import_meta_main/__test__.jsonc, tests/specs/bundle/import_meta_main/import_meta_main.out, tests/specs/bundle/main/__test__.jsonc, tests/specs/bundle/main/json_import.out, tests/specs/bundle/main/jsr_specifier.out, tests/specs/bundle/main/npm_specifier.out, tests/specs/bundle/main/npm_specifier_with_import_map.out, tests/specs/bundle/main/requires_node_builtin.out, tests/specs/bundle/main/sloppy_imports.out, tests/specs/bundle/multiple_entries/__test__.jsonc, tests/specs/bundle/multiple_entries/multiple_entries.out, tests/specs/bundle/sourcemap/__test__.jsonc, tests/specs/bundle/sourcemap/sourcemap_external.out, tests/specs/bundle/sourcemap/sourcemap_inline.out, tests/specs/bundle/sourcemap/sourcemap_linked.out
We were trying to do the hack of replacing the esbuild require shim on every output file, regardless of whether it was js/ts.
This fixes that.
In addition, this spruces up the output of deno bundle a bit.
before:
after:
=> fix(bundle): only replace require shim in js files, spruce up output

cli/args/mod.rs, cli/tools/run/mod.rs, tests/node_compat/config.toml, tests/registry/jsr/@denotest/bin/1.0.0/mod.ts, tests/registry/jsr/@denotest/bin/1.0.0_meta.json, tests/specs/run/import_map_bare_specifier/__test__.jsonc, tests/specs/run/import_map_bare_specifier/absolute_unix.out, tests/specs/run/import_map_bare_specifier/absolute_windows.out, tests/specs/run/import_map_bare_specifier/deno.jsonc, tests/specs/run/import_map_bare_specifier/direct_file.out, tests/specs/run/import_map_bare_specifier/jsr_specifier.out, tests/specs/run/import_map_bare_specifier/local_file.out, tests/specs/run/import_map_bare_specifier/npm.out, tests/specs/run/import_map_bare_specifier/relative_mapping.out, tests/specs/run/import_map_bare_specifier/src/app.ts
Closes https://github.com/denoland/deno/issues/29897.
Closes https://github.com/denoland/deno/issues/14066.
Closes https://github.com/denoland/deno/issues/19955.
With this PR we'll attempt to resolve bare specifiers passed to `run` or `serve` with the workspace resolver. This means you can run specifiers that are defined in your import map/package.json.
If the specifier looks like a path (starts with `.`, or is an absolute path) then we won't try to resolve it via the import map.
This does have the potential to break someone, in the case that you have something like
```
{
"imports": { "foo.ts": "./bar.ts" }
}
```
and you have a file named `foo.ts`, previously `deno run foo.ts` would run `./foo.ts`, now we would run `./bar.ts`. I can't see a way around that without doing an extra stat to …
=> feat(run): resolve main module with workspace resolver

cli/factory.rs, cli/lsp/config.rs, cli/module_loader.rs, cli/rt/run.rs, cli/standalone/binary.rs, ext/node/lib.rs, ext/node/ops/require.rs, libs/config/deno_json/mod.rs, libs/resolver/cache/parsed_source.rs, libs/resolver/deno_json.rs, libs/resolver/emit.rs, libs/resolver/factory.rs, libs/resolver/loader/prepared.rs
This is for the internal library code only. It has no affect on the Deno CLI.
I now have the loader working with deno-js-loader after these changes.
=> refactor(emitter): ability to not transpile and specify a source map base

runtime/js/98_global_scope_shared.js, tests/unit/globals_test.ts
Closes https://github.com/denoland/deno/issues/30012
Makes `global` global a writeable property.
=> fix: `global` global should be writeable

cli/clippy.toml
Part of https://github.com/denoland/deno/issues/29886
=> chore: disallow usage of `clap::Arg::env` method

cli/tools/lint/linter.rs
We had logic to handle this, but it wasn't good enough for when there was more than 2 overlapping.
=> fix(lint): do not panic for many overlapping lint fixes

Cargo.lock, Cargo.toml, cli/main.rs, ext/net/tunnel.rs, ext/telemetry/lib.rs
tunnels now automatically reconnect and migrate. also use `shutdown` in telemetry instead of `flush` because it times out after 5s, which is important if the tunnel connection is hanged for some reason.
=> chore: update deno_tunnel

cli/lsp/documents.rs, cli/lsp/tsc.rs, cli/tsc/97_ts_host.js, cli/tsc/mod.rs, tests/integration/lsp_tests.rs
Also actually goes to the file now when doing "go to definition" on the specifier.
=> fix(lsp): improve renaming a file with bytes or text imports

tests/node_compat/config.toml, tests/node_compat/run_all_test_unmodified.ts, tests/node_compat/test.ts
This commit updates test harness for Node.js compat tests to
allow marking certain tests as flaky. 
This is done by adding `flaky = true` to dict entries in
the `tests/node_compat/config.toml` file.
=> test: add ability to mark Node compat tests as flaky

Cargo.lock, Cargo.toml, cli/main.rs
send hostname and entrypoint when connecting to tunnel
=> feat(unstable): add useful metadata to tunnel

Cargo.lock, Cargo.toml, cli/graph_util.rs, cli/lib/util/result.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/tools/doc.rs, libs/resolver/graph.rs, libs/resolver/lib.rs, tests/integration/lsp_tests.rs, tests/specs/cache/with_bare_import/095_cache_with_bare_import.ts.out, tests/specs/check/ambient_modules/bare_specifier.out, tests/specs/check/bare_specifier_not_found/__test__.jsonc, tests/specs/check/bare_specifier_not_found/check_import_map.out, tests/specs/check/bare_specifier_not_found/check_no_import_map.out, tests/specs/check/bare_specifier_not_found/deno.jsonc, tests/specs/check/bare_specifier_not_found/main.ts, tests/specs/check/with_bare_import/095_cache_with_bare_import.ts.out, tests/specs/run/bare_specifier_without_import/main.out, tests/specs/run/error_type_definitions/error_type_definitions.ts.out, tests/specs/run/package_json_auto_discovered_for_local_script_arg_with_stop/main.out
We were not surfacing module not found errors by accident in too many cases.
* https://github.com/denoland/deno_graph/pull/599
* Adds back surfacing https://github.com/denoland/deno/pull/29926 without doing it for side effect imports.
Closes https://github.com/denoland/deno/issues/30116
=> fix(check): ensure module not found errors are surfaced

Cargo.lock, Cargo.toml, cli/main.rs, ext/net/tunnel.rs, ext/telemetry/lib.rs, tests/specs/run/tunnel/test.out, tests/specs/run/tunnel/test.ts
fix issue with tunneling vite, which spawns subprocesses, where the subprocess runs a server.
=> fix: tunnels in processes that don't listen

cli/standalone/binary.rs, tests/specs/compile/npm_pkgs_lockfile_unused/__test__.jsonc, tests/specs/compile/npm_pkgs_lockfile_unused/compile.out, tests/specs/compile/npm_pkgs_lockfile_unused/deno.json, tests/specs/compile/npm_pkgs_lockfile_unused/main.ts
Closes https://github.com/denoland/deno/issues/30177 (along with https://github.com/denoland/deno/pull/30188)
=> fix(compile): do not include managed npm deps when graph does not have any npm pkgs

cli/factory.rs, cli/module_loader.rs, cli/rt/run.rs, cli/worker.rs, libs/resolver/npm/mod.rs, runtime/permissions/lib.rs, tests/node_compat/config.toml, tests/specs/run/bytes_and_text_imports/dynamic/__test__.jsonc, tests/specs/run/bytes_and_text_imports/dynamic/main.ts, tests/specs/run/bytes_and_text_imports/dynamic/main_missing_permissions.out, tests/specs/run/bytes_and_text_imports/static/__test__.jsonc, tests/specs/run/bytes_and_text_imports/static/main_missing_permissions.out
This reverts commit 147bbcf8dd7075dd98e47fd123f5600f65e969c5.
(Partial revert actually because i kept some of the refactoring I liked)
Reason for the revert is this is an established security principle:
> The initial static module graph can import local files without restrictions: All files that are imported in the initial static module graph can be imported without restrictions, so even if an explicit read permission is not granted for that file. This does not apply to any dynamic module imports.
https://docs.deno.com/runtime/fundamentals/security/#key-principles
=> Revert "fix(unstable): always require --allow-read permissions for raw imports (#30184)"

.github/CONTRIBUTING.md
Hello, I was reading the CONTRIBUTING.md and found a broken link.
It seems like the file it was linking to does not exist anymore.
I figured the correct place to send the user now might be the docs website, wdyt?
=> fix(docs): Fix broken Getting Started link in CONTRIBUTING.md

cli/factory.rs
Fixes #30187.
If you're using --node-modules-dir=manual we should respect that, since resolution may not work with the managed resolver
=> fix(bundle): don't force managed npm resolution

ext/node/polyfills/_fs/_fs_fdatasync.ts, ext/node/polyfills/_fs/_fs_fsync.ts, tests/node_compat/config.toml
Also addresses `prefer-primordials` lint rule. This allows [parallel/test-fs-fsync.js](https://github.com/denoland/node_test/blob/8846b5392f4ebd3d4e995b9bed61c23c0192d806/test/parallel/test-fs-fsync.js) test to pass.
Towards #29972, #24236.
=> fix(ext/node): validate `fd` is integer on `fsync` and `fdatasync`

Cargo.lock, Cargo.toml, cli/lib/util/result.rs, ext/http/http_next.rs, libs/resolver/graph.rs, runtime/web_worker.rs
Handles more error cases when tunnels close. this logic got super nasty to do as nested if statements, so i added recursion >:)
https://github.com/denoland/deno_core/pull/1170
https://github.com/denoland/deno_error/pull/17
=> fix(http): catch more tunnel close errors

Cargo.lock, Cargo.toml
This was a recent regression caused by:
* https://github.com/denoland/deno/pull/30211
Fixed by:
* https://github.com/denoland/deno_path_util/pull/18
PR marked as chore because it's not worth including in the release notes because the bug hasn't hit any releases yet.
=> chore: regression where excluded path stopped being excluded

ext/node/polyfills/internal_binding/pipe_wrap.ts
Towards #24236. Replaces JS builtins with equivalent primordials.
=> fix(ext/node): use primordials in `ext/node/polyfills/internal_binding/pipe_wrap.ts`

ext/web/02_structured_clone.js, ext/web/13_message_port.js
This PR builds on top of https://github.com/denoland/deno_core/pull/1167 that provided 16%
perf improvement for structured clone algorithm by avoid round-trip serialization and
deserialization.
This was applied to the internal `structuredClone` helper, as well as for `MessagePort.postMessage`
which is what Web worker and `node:worker_thread` APIs are using.
=> perf: Use more efficient structuredClone API

ext/node/polyfills/internal/fs/utils.mjs, tests/node_compat/config.toml, tests/unit_node/_fs/_fs_appendFile_test.ts
This allows [parallel/test-fs-internal-assertencoding.js](https://github.com/nodejs/node/blob/v23.9.0/test/parallel/test-fs-internal-assertencoding.js) to pass.
Towards #29972
=> fix(ext/node): incorrect `ERR_INVALID_ARG_VALUE` constructor arguments position

ext/node/ops/fs.rs, ext/node/polyfills/_fs/_fs_common.ts, ext/node/polyfills/_fs/_fs_open.ts, tests/node_compat/config.toml, tests/unit_node/_fs/_fs_open_test.ts
Fixes #30299 
I decided to build the `OpenOptions` on the Rust side, because it's cheaper to pass integers to the op function and we can enable the fast op call. Also the tests that I added to the `config.toml` were already passing before this PR.
=> fix(ext/node): parse fs open options correctly

cli/lsp/completions.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/schemas/config-file.v1.json, libs/resolver/deno_json.rs, tests/integration/lsp_tests.rs, tests/specs/check/skip_lib_check/__test__.jsonc, tests/specs/check/skip_lib_check/deno.json, tests/specs/check/skip_lib_check/types.d.ts
Follow up to #30242 as proposed there.
=> fix(lsp): use referrer compiler options for node_modules files

cli/tools/publish/mod.rs, tests/specs/publish/workspace_root_package/__test__.jsonc, tests/specs/publish/workspace_root_package/deno.json, tests/specs/publish/workspace_root_package/mod.ts, tests/specs/publish/workspace_root_package/package-b/deno.json, tests/specs/publish/workspace_root_package/package-b/mod.ts
Blocking fresh release.
Fixes https://github.com/denoland/deno/issues/30332
=> fix(publish): remove incorrect `relative-package-import` diagnostic when root of workspace is package

ext/node/ops/buffer.rs, ext/node/polyfills/internal/buffer.mjs, ext/node/polyfills/string_decoder.ts, tests/node_compat/config.toml, tests/unit_node/buffer_test.ts
Previously, Deno throws error when creating `Buffer.allocUnsafe` or `Buffer.allocUnsafeSlow` with size of `2**31` where that's not the case with Node.js. 
The changes allow these tests to pass:
- [test-buffer-large-size-buffer-alloc-unsafe-slow.js](https://github.com/nodejs/node/blob/v24.2.0/test/pummel/test-buffer-large-size-buffer-alloc-unsafe-slow.js)
- [test-buffer-large-size-buffer-alloc-unsafe.js](https://github.com/nodejs/node/blob/v24.2.0/test/pummel/test-buffer-large-size-buffer-alloc-unsafe.js)
- [test-string-decoder-large-buffer.js](https://github.com/nodejs/node/blob/v24.2.0/test/pummel/test-string-decoder-large-buffer.js)
=> fix(ext/node): handle large buffer correctly

Cargo.lock, Cargo.toml, ext/node/ops/handle_wrap.rs
ref https://github.com/denoland/deno_core/pull/1175
=> fix: upgrade deno_core to 0.355.0

ext/node/polyfills/os.ts, tests/node_compat/config.toml
These only occurs when importing using `require('os')`, since ES module imports already make it non-writeable. Changes are based on Node.js original implementation [here](https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/lib/os.js#L333-L356). This allows [test-os-eol.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-os-eol.js) to pass.
=> fix(ext/node): make some `os` exported properties read only

Cargo.lock, Cargo.toml, cli/main.rs
event handling is now passed as an argument so they can be emitted before the connect call returns. also adds a "reason" to reconnect to show exactly what error caused it.
=> fix(unstable): update deno_tunnel for better reconnect errors

tests/specs/compile/code_cache/cleanup.ts
This has been causing failures on multiple PRs.
=> fix(tests): use correct path separator on unix for code_cache cleanup.ts

cli/js/40_lint.js, tests/unit/lint_plugin_test.ts
This makes npm libraries that traverse the ESTree format like `zimmerframe` or `periscopic` work with our lint ast.
=> fix(unstable): lint node properties should be enumerable

ext/node/polyfills/net.ts
Rewritten `net.Socket` and `net.Server` to use ES5 class instead of ES6. There
are Node tests that depend on this (as well as packages in the wild).
=> refactor(ext/node): rewrite net.Socket and net.Server to use ES5 class

tests/node_compat/run_all_test_unmodified.ts
Allows tests to resolve path correctly, such as this one https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/test/parallel/test-fs-cp.mjs#L35
=> fix(test): set cwd when running node compatibility tests

cli/lsp/language_server.rs
=> fix(lsp): silence tsc debug failures for inlay hints

ext/net/tcp.rs
This change increases default socket backlog from 128 to 512.
Towards https://github.com/denoland/deno/issues/30388.
=> perf(ext/net): change the default TCP backlog to 512

libs/npm_installer/global.rs, tests/specs/mod.rs, tests/specs/npm/peer_deps_with_copied_folders_and_lockfile/__test__.jsonc, tests/specs/schema.json
Looked and we already do this for the local npm install.
Kind of annoying to test this one, so not going to bother to.
Closes https://github.com/denoland/deno/issues/30457
=> fix(npm): do not error on failure to write warned script file

tests/node_compat/config.toml
Related to https://github.com/denoland/node_test/pull/5. This allows several node tests to pass on Windows.
=> chore(test): preserve node test fixtures line endings

ext/node/polyfills/path/_posix.ts, ext/node/polyfills/path/_win32.ts, tests/node_compat/config.toml
Changes are based on Node.js' implementation https://github.com/nodejs/node/tree/v24.2.0/lib/path.js.
It allows this tests to pass:
- [parallel/test-path-makelong.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-path-makelong.js)
- [parallel/test-path-resolve.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-path-resolve.js)
=> fix(ext/node): `fs.path`' `makelong` and `resolve` compatibility

cli/rt/file_system.rs, ext/fs/interface.rs, ext/fs/std_fs.rs, ext/node/polyfills/_fs/_fs_exists.ts, tests/node_compat/config.toml, tests/unit_node/_fs/_fs_exists_test.ts
Closes #30506
Other changes:
- Emit deprecation warning.
- Allows [parallel/test-fs-exists.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-exists.js) to pass.
- Allows [test-fs-symlink-dir-junction.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-symlink-dir-junction.js) to pass. Previously it always fail due to invalid assertion using `existsSync`.
=> fix(ext/node): `fs.exists` and `fs.existsSync` compatibility

cli/main.rs, runtime/web_worker.rs, runtime/worker.rs
we can just flip this flag at runtime
=> fix(unstable): support unstable-raw-imports when prewarmed

ext/node/polyfills/path/_util.ts, ext/node/polyfills/path/_win32.ts, tests/node_compat/config.toml
Forked from Node.js implementation:
- https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/lib/path.js#L76
- https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/lib/path.js#L1231
This allows `parallel/test-path-normalize.js` test to pass.
=> fix(ext/node): path.normalize compatibility

cli/args/mod.rs, ext/fs/lib.rs, runtime/permissions/lib.rs
Removes the `all` state and instead derives the state from the other permissions.
=> refactor(permissions): remove `all` state in permissions

cli/tools/fmt.rs, tests/testdata/fmt/with_config/subdir/a.ts
Hi Deno folks!
I stumbled over an issue during formatting a project that I'm moving to Deno, where curly braces would be handled inconsistently by `deno fmt`, and thought this would make for a nice first contribution.
This lets spacing in named import/export lines follow the config for objects. Spaces would always be added before, which looked odd in projects that otherwise used no spaces for object syntax.
There is no change for users who leave `spaceSurroundingProperties` at the default value (on).
Config:
```json
{
"fmt": {"spaceSurroundingProperties": false}
}
```
Old formatting:
```ts
// spaces always added here:
import { foo } from "bar";
const baz = {a: 1};
```
New formatting with this PR applied:
```ts
import {foo} from "bar";
const baz = {a: 1};
```
With this change, the behavior …
=> feat(fmt): apply object spacing to import/export lines

cli/args/flags.rs
Specify multple files separately, `--preload p1.js --preload p2.js` instead of `--preload p1.js,p2.js`. Closes #30543.
=> fix(cli): support data urls in preload by not splitting on comma.

cli/ops/testing.rs, cli/tools/repl/session.rs, cli/tools/test/mod.rs, cli/tools/test/sanitizers.rs
There are no functional changes in the code, it's just a refactor that moves
code around to make it easier to land https://github.com/denoland/deno/pull/30504
=> refactor: reorganize `tools/test` module

cli/tsc/dts/lib.deno_fetch.d.ts
This patch updates the `Response` interface type declarations to correctly specify `ArrayBuffer` as the backing buffer type for the `encode()` method, aligning with the spec and addressing the change introduced in TypeScript 5.7 about making `ArrayVBufferLike` a default buffer type behind `Uint8Array`.
In fact, [TypeScript's dom.d.ts got a similar change](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/fad434be5961529bee396efab03cce2a1bc333e2/baselines/dom.generated.d.ts#L4563-L4580), and now it looks like:
```ts
interface Body {
/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Request/body) */
readonly body: ReadableStream<Uint8Array<ArrayBuffer>> | null;
/** [MDN Reference](https://developer.mozilla.org/docs/Web/API/Request/bodyUsed) */
readonly bodyUsed: …
```
=> fix(types): specify `ArrayBuffer` as a backing buffer type for `Response.body` and `Response.bytes`

cli/args/flags.rs
Discovers the config file based on the arguments to `deno cache` and `deno install -e <entrypoint>`
=> fix(install/cache): better discovery for config file based on entrypoint

Cargo.lock, Cargo.toml, cli/schemas/lint-rules.v1.json, tests/integration/lsp_tests.rs, tests/specs/lint/no_import_prefix/non_workspace/main.ts, tests/specs/lint/no_import_prefix/workspace/lint.out, tests/specs/lint/no_import_prefix/workspace/main.ts
Bans using npm/jsr imports without specifying a version requirement.
It's bad to not specify a version requirement because without a lockfile Deno will always pull in the latest version of a package, which could cause your code to stop working if the package ever publishes a breaking change.
* https://github.com/denoland/deno_lint/pull/1362
=> feat(lint): no-unversioned-import rule

tests/unit_node/_fs/_fs_close_test.ts
Test from #30720 is flaky because sometimes the resource ID is not fully closed and caused some CI failures.
=> chore(test): fix `node:fs.close` test flakiness

ext/fs/std_fs.rs, ext/io/Cargo.toml, ext/io/lib.rs, tests/node_compat/config.toml
Towards #29972
- Also fixes `node:fs.fstat` because it was incorrectly showing the file mode on windows, which is needed by the node compat test.
- Moves the `stat_extra` function from `ext/fs/std_fs.rs` (deno_fs) into `ext/io/lib.rs` (deno_io), because it's more convenient to export it from there letting us to use the function on `deno_fs` and `deno_io`, and currently `deno_fs` had already used `deno_io` as a dependency.
- Allows [parallel/test-fs-chmod-mask.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-chmod-mask.js) and [parallel/test-fs-chmod.js](https://github.com/nodejs/node/blob/v24.2.0/test/parallel/test-fs-chmod.js) tests to pass.
=> fix(ext/node): implement `fchmod` on windows

tests/unit/net_test.ts
This test is very flaky and needs to be rewritten, it depends on a race condition between the timeout and `Deno.connect`.
=> chore: disable flaky `netTcpWithAbortSignal`

ext/node/polyfills/internal_binding/_timingSafeEqual.ts, tests/integration/node_unit_tests.rs, tests/unit_node/crypto/crypto_timing_safe_equal_test.ts
Fixes #30759
The buffer validation is based on Node.js implementation: https://github.com/nodejs/node/blob/591ba692bfe30408e6a67397e7d18bfa1b9c3561/src/crypto/crypto_util.h#L467-L472
=> fix(ext/node): accept ArrayBuffer on crypto.timingSafeEqual

cli/schemas/config-file.v1.json, libs/resolver/deno_json.rs, libs/resolver/lib.rs, libs/resolver/workspace.rs, tests/specs/check/compiler_options_paths_and_sloppy_imports/__test__.jsonc, tests/specs/check/compiler_options_paths_and_sloppy_imports/deno.json, tests/specs/check/compiler_options_paths_and_sloppy_imports/main.ts, tests/specs/check/compiler_options_paths_and_sloppy_imports/unmapped.out, tests/specs/check/compiler_options_paths_and_sloppy_imports/unmapped.ts
- https://www.typescriptlang.org/tsconfig/#paths
This field is defined for convenience in many framework templates, e.g. in the svelte-kit demo: https://github.com/sveltejs/kit/blob/%40sveltejs%2Fkit%402.42.1/packages/kit/src/core/sync/write_tsconfig.js#L101-L104
Also implements [`compilerOptions.baseUrl`](https://www.typescriptlang.org/tsconfig/#baseUrl). For us it's only used for resolving bare specifier entries in `compilerOptions.rootDirs` and `compilerOptions.paths`. If undefined these fall back to using the parent path of the tsconfig, which is what we were doing previously for `rootDirs`. For tsc it's also used for `compilerOptions.typeRoots` which we don't support and for resolving unmapped bare specifiers in code imports.
All of these fields only apply to type-only imports.
=> fix(check): support "compilerOptions.paths"

cli/lsp/config.rs, libs/config/workspace/discovery.rs, libs/config/workspace/mod.rs, libs/node_resolver/package_json.rs, libs/package_json/lib.rs
This is useful for single pass resolvers, like `@deno/loader`. There the probe overhead is so large that package.json probing accounts for up to 90% of readfile calls in a large project.
=> perf: support negative caching of package.json

cli/tsc/dts/lib.deno.unstable.d.ts, cli/tsc/dts/lib.deno_webgpu.d.ts, tools/deno.lock.json, tools/generate_types_deno.ts
See https://github.com/microsoft/TypeScript/pull/62496#issuecomment-3340761035
=> fix(dts): update some GPU types to not cause errors in upcoming DOM type declarations

cli/main.rs, runtime/permissions/broker.rs, runtime/permissions/ipc_pipe.rs, runtime/permissions/lib.rs, tests/integration/run_tests.rs, tests/testdata/run/permission_broker/broker.ts
```powershell
> $env:DENO_PERMISSION_BROKER_PATH="\\.\pipe\deno-permission-broker" ; deno run script.ts
```
=> feat(unstable): support named pipes on Windows for the permission broker

cli/schemas/permission-broker-response.v1.json, runtime/permissions/broker.rs, runtime/permissions/lib.rs, tests/integration/run_tests.rs, tests/testdata/run/permission_broker/broker.ts
This allows changing the error message displayed in Deno for errors by providing a "reason" property when denying a permission.
=> feat(unstable): permission broker - support custom error messages

ext/node/ops/zlib/mod.rs, tests/unit_node/zlib_test.ts
=> fix(ext/node): omit `smi` from `zlib.crc32` op function

tests/unit/process_test.ts
Currently most TS tests use `Deno.execPath()` to identify where `deno` lives
In the event deno is not on the `$PATH` these tests will fail.
If deno is on the `$PATH` you can end up testing the wrong instance of `deno`.
=> test: use `Deno.execPath()` instead of `deno`
