denoland/deno

msg.proto
timers.go
timers.ts

Just remove the comments: `TODO DRY with setTimeout`. And BTW in MDN, as the parameter of delay:
> If this parameter is less than 10, a value of 10 is used
So I just corrected the value in `timers.go` :)

optimize the timer ts impl, and correct the duration if less than 10

---

Makefile

Makefile: deno.ts

---

README.md

Even though the readme told me there was going to be an error, I was still confused about this error, as it looked unrelated to fetching the sources.
To clarify this update the readme to spell out the expected error.
Fixes #109

📝 Update install instructions around known error

---

main.ts
timers.ts

Use object destructing to reduce some redundant codes.

Use object destructing

---

timers.ts

delete timer in the Map(timers) when call clearTimer

delete timer in the Map(timers) when call clearTimer

---

runtime.ts

Remove unnecessary 'undefined'

---

deno_dir.go

Change a little typo in comment

fix comment typo

---

main.go

I've found that with the current implementation the main loop isn't tracked. With this tweak we could inspect `Fetch` and any other internal calls:
We could get more useful information if we extend this, I've also added memory profiling and modified the flags in order to allow both. Previously:
```
% deno -goprof cpu -allow-net hello.ts
```
After this tweak:
```
% deno -cpuprof cpu.out -memprof mem.out -allow-net hello.ts
```

Extend profiling

---

fetch.ts

[fetch.ts] avoid duplicate import about `util`.

fetch: Avoid duplicate import about util

---

deno_dir.go
main.go
os.go

Use path.Join instead of +

---

README.md

Seems like that should be more prominent to keep people like me at bay. :)

Added contents of 'too much noise' to the readme

---

deno2/deno.cc
deno2/js/mock_runtime.js
deno2/mock_runtime_test.cc

Emailed V8 people about it: https://groups.google.com/d/topic/v8-users/JpNdd8OfnmU/discussion

Fix snapshot bug.

---

src/js/run_node.py

Fixing continued travis problems: https://travis-ci.com/ry/deno/builds/77060862

run_node.py don't error if symlink exists

---

.gclient
.gitignore
tools/lint.sh

Add cpplint to third_party

---

js/main.ts
js/package.json
js/yarn.lock
tools/lint.sh
tslint.json

Add tslint

---

tools/build_third_party.py
tools/format.sh

Clean up build_third_party.py

---

js/console.ts
js/deno.ts
js/dispatch.ts
js/fetch.ts
js/globals.ts
js/main.ts
js/os.ts
js/runtime.ts
js/tests.ts
js/text-encoding.d.ts
js/timers.ts
js/types.ts
js/util.ts
js/v8_source_maps.ts
src/binding.cc
src/main.cc
tsconfig.json
tslint.json

Also adds some throw-away C++ for better debugging exceptions.
I'm doing this as a separate pull request so that #334 will be more readable after the import.

Import TS from prototype without changes.

---

js/msg_generated.ts

I forgot to commit this file in 8a17db8.

Regenerate msg_generated.ts

---

.gitignore
.gitmodules
.travis.yml
README.md
gclient_config.py
tools/build_third_party.py
tools/run_hooks.py
tools/util.py

Depends on #371 
Addresses #312

Add deno_third_party as submodule

---

src/handlers.rs
tools/check_output_test.py

Makes test.py pass on windows.

Test fixes

---

tools/build.py
tools/format.py
tools/run_hooks.py
tools/sync_third_party.py
tools/third_party.py
tools/util.py

* Make sync_third_party work in general
* Un-break build.py and run_hooks.py on windows
* Partially fix format.py on windows
* Reduce code duplication between run_hooks and sync_third_party

Clean up and fix tools

---

tools/lint.py

Ignore any generated TypeScript files

---

BUILD.gn
README.md
js/assets.ts
js/lib.deno.d.ts
js/runtime.ts
package.json
rollup.config.js
tsconfig.json
yarn.lock

Update to TypeScript 3.0.1

---

README.md

Thanks for this interesting project!
A quick broken link fix with this PR.
Ref: https://github.com/ry/deno/pull/330

Update protobuf link to flatbuffer

---

BUILD.gn
build_extra/rust/BUILD.gn
build_extra/rust/rust.gni

0c6aeb3 Remove the 'cfg' variable from rust templates.
514303c Remove 'rust_staticlib' build template
98e8b10 Fix test_cc build dependencies

Build tweaks

---

src/main.rs

https://github.com/denoland/deno/issues/498
Currently Deno::drop is not being called due to Deno::new not returning an owned type.

Change Deno::new to return an owned Box

---

js/main.ts
js/util.ts
src/flags.rs
src/handlers.rs
src/main.rs
src/version.rs

Depends on #514 
Previous attempts: #441 #401 
Fixes #376
cc @robbym

Command line flag parsing

---

js/fetch.ts
js/os.ts
js/runtime.ts
js/util.ts

Fixes #534 
This is my first try at Deno. I am not sure if I do everything correctly, but running `./tools/test.py` passes.

add notImplemented and notReachable util functions

---

.travis.yml
src/version.rs

Releasing on every commit doesn't work so well - at least with the default settings. It results in a bunch of tags prefixed with "untagged". That's ugly. So this only does release on explicit tags. I've tested it by bumping the version to v0.0.2 and it's working: https://github.com/denoland/deno/releases

Travis deploy

---

src/version.rs

Bump version to v0.0.3

---

js/deno.ts
js/os.ts
js/unit_tests.ts
src/fs.rs
src/handlers.rs
tools/test.py

Implements writeFileSync

---

js/fetch.ts
src/deno_dir.rs
src/errors.rs
src/fs.rs
src/handlers.rs
src/main.rs
src/msg.fbs
src/net.rs
tests/006_url_imports.ts
tests/006_url_imports.ts.out
tools/check_output_test.py

This is mostly @NewLunarFire's work. I've rebased and made clean ups.
Continued from #519.
Depends on #518
Fixes #416

HTTP imports #2

---

src/version.rs

https://github.com/denoland/deno/milestone/1 complete

Bump version to v0.1.0

---

js/compiler.ts
js/compiler_test.ts

Integrate ScriptSnapshot into ModuleMetaData

---

BUILD.gn
build_extra/toolchain/validate.gni
build_extra/toolchain/win/BUILD.gn
build_extra/toolchain/win/mods.gni
tools/setup.py

Also auto-detect the availability of sccache in setup.py.

Build: make it possible to use ccache/sccache on windows

---

js/console.ts
js/unit_tests.ts

Fixed printing strings in arrays & objects without quotes

---

src/version.rs

Wait to land until #599 is in.

Bump v0.1.1

---

README.md
tools/install.py
tools/install_test.py
tools/test.py

- Added windows as a platform detection option
- Handle extraction of .zip file
Solves #615

Work on making installer cross platform

---

tools/install.py

cc #639 @mirkojotic @ry
Tested both python 2 and 3.
Tested stubbing in the windows filename (on osx), it unzips correctly.

Avoid using temporary directory in install.py

---

BUILD.gn
js/assets.ts
js/compiler.ts
js/compiler_test.ts
js/lib.globals.d.ts
rollup.config.js

Remove lib.globals.d.ts

---

js/v8_source_maps.ts

Make the code with same style and read clearly

Refactor code to be same style

---

src/main.rs

* Using the log_level variable
* Fix indent

Minor code refactoring

---

js/deno.ts
js/os.ts
js/os_test.ts
src/handlers.rs
src/msg.fbs

Implements mkdirSync

---

src/flags.rs

Removes eval flag. It needs further consideration - the way it was implemented didn't execute the `denoMain` function - meaning that many handlers wouldn't be setup - stack traces wouldn't be displayed properly - setTimeout wouldn't work, etc.

Better flag parsing - rebase #595

---

js/compiler.ts
js/compiler_test.ts
js/main.ts
js/os_test.ts
src/flags.rs
src/handlers.rs
src/msg.fbs

Initial work on getting --deps flag to print module dependencies.
I was just wondering if I'm heading in the right direction ( and I could always use some advice ).
I'm positive that my messing around in `getModuleDependencies` wasn't right so any pointers around that would be greatly appreciated.
No tests so far :( ( also I would appreciate some advice as to where to place them )
Solves #630 ( well it doesn't yet :D )

Add --deps flag

---

js/fetch.ts
js/fetch_test.ts
src/handlers.rs

Check allow-net in fetch

---

js/os.ts

* Add readFileSync comment
* Add writeFileSync comment
* Edit env comment

Add and edit comments

---

tools/format.py

tools/format: don't format files in third_party on Windows

---

tools/third_party.py

tools/setup: on windows, make env vars not affect gn gen output

---

js/compiler.ts
js/deno.ts
js/errors.ts
js/fbs_util.ts
js/fetch.ts
js/fetch_test.ts
js/main.ts
js/os.ts
js/os_test.ts
js/timers.ts
src/deno_dir.rs
src/errors.rs
src/handlers.rs
src/main.rs
src/msg.fbs
tests/error_004_missing_module.ts.out
tests/error_005_missing_dynamic_import.ts.out

Better NotFound error handling in CodeFetch

---

.appveyor.yml
BUILD.gn

Be more rigorous about bundle dependencies

---

js/fetch.ts
js/fetch_test.ts
js/util.ts

It resolves the second item in #522.

Make fetch.blob() work

---

BUILD.gn
js/assets.ts
js/dom_types.ts

This PR bundles the `dom_types` into the `global.d.ts` which better manages the types inlined in deno.

Improve integration of dom_types

---

js/stat.ts

The example code does not work.

Fix comments in stat.ts file

---

build_extra/rust/rust.gni
src/flags.rs
src/handlers.rs

build: properly rebuild rust crates when their deps change

---

.gn
build_extra/rust/BUILD.gn
build_extra/rust/rust.gni

Suppress remaining rust warnings, treat warnings as errors where possible

---

js/stat.ts

change FileInfo to interface

---

.gitignore
.travis.yml
tools/benchmark.py
tools/format.py
website/app.js
website/index.html

Add benchmarks & publish travis linux results

---

.travis.yml

[Land on approval]
Fix travis CI condition
CI for this pull request won't tell if this fixes the build. This CI run should provide better insight: https://github.com/denoland/deno/compare/master...aef3d065996f

travis: fix github pages deploy condition

---

README.md
Roadmap.md

Update README and Roadmap.

---

.travis.yml

According to [this test run](https://travis-ci.com/denoland/deno/jobs/147342348), this actually fixes the mac build.
[land on approval]

travis: fix the build, attempt 2

---

js/unit_tests.ts
website/app.js
website/app_test.js
website/index.html

This PR starts the unit testing of website's script (using deno as runtime). Closes #812.
---
I found #811 after creating this one. I'm glad to update this PR if #811 merged first.

Start unit testing of website script

---

js/compiler.ts
js/compiler_test.ts
js/main.ts
src/flags.rs
src/handlers.rs
src/msg.fbs

First attempt to solve #790. It's quite hacky but it does the job and forces compilation.
Don't know yet how to test it. Feedback welcome.
EDIT: typo

Add flag --recompile

---

tools/benchmark.py
website/app.js
website/app_test.js
website/index.html

Also plot cold start time.

---

tools/benchmark.py
tools/benchmark_test.py
tools/test.py
website/app.js
website/app_test.js

Reverts denoland/deno#830
Broke the build.

Revert "Expand binary size benchmark"

---

BUILD.gn
src/handlers.rs
src/main.rs

This doesn't attempt to convert all of the handlers, just tries to establish the pattern.

First pass at making blocking I/O calls in thread pool.

---

tools/benchmark.py
tools/benchmark_test.py
tools/test.py
website/app.js
website/app_test.js

Resubmitting without change 8c7416b3f666c62327a2306e955ec59823b1f239 / #830

Expand binary size benchmark (#830)

---

js/compiler.ts

Makes it seem like we have better startup time.

Print 'Compiling' when compiling TS.

---

README.md

Better build instructions for windows

---

tools/util.py

tools: define ERROR_INVALID_PARAMETER in utils.py

---

js/dom_types.ts
js/fetch_test.ts
tools/benchmark.py
website/app.js

@kevinkassimo please review if you have the time and inclination.

Add syscall count bench

---

.appveyor.yml
.travis.yml
js/copy_file_test.ts
js/deno.ts
js/dispatch.ts
js/timers.ts
js/timers_test.ts
src/handlers.rs
src/isolate.rs
src/msg.fbs
website/app_test.js

Reimplement timers in javascript

---

.prettierrc.json
README.md
Roadmap.md
js/testing/testing.ts
tools/format.py
website/README.md

Format markdown files with prettier

---

tools/lint.py

tslint warning supress

---

js/timers.ts
js/timers_test.ts

Land timers fix from #942 and add test

---

src/http.rs

Re-enable test_fetch_sync_string

---

js/testing/testing.ts

@ry  Sorry for my bad, pull request #923 again.

Add counts for ignored , measured, filtered

---

src/isolate.rs

Clean up Isolate::event_loop with utility function.

---

Roadmap.md

It'd be better if there are links of issues for convenience.

Add links of issues in Roadmap.md

---

BUILD.gn
js/deno.ts
js/metrics.ts
js/metrics_test.ts
js/unit_tests.ts
src/isolate.rs
src/msg.fbs
src/ops.rs
tools/http_server.py

Add deno.metrics()

---

.gn

The Jumbo build is the Chromium implementation of a Unity build system
aimed at dramatically lowering the compilation times. It can be easily
enabled with `use_jumbo_build=true`.
When you enable this, the biggest problem is that name conflicts can
occur between multiple c++ files merged, which is no problem for Deno.
Because the V8's Jumbo build is managed in upstream, and Deno will
just pick up a stable build V8.
So, this patch enables Jumbo build by default. After this patch, the
total number of build objects are halved. (1014 -> 493)
FYI, the following results are tested in my local environment.
- IMAC 5K, i5 4-cores, 24GB, 512GB SSD
Test result1: No use ccache
|   |Jumbo build without ccache|Normal build without ccache|
|---|--------------------------|---------------------------|
| 1 …

Improve build performance by using jumbo build

---

package.json
tests/error_003_typescript.ts.out
tools/ts_library_builder/build_library.ts
tools/ts_library_builder/test.ts

Resolves: #969
Requires: denoland/deno_third_party#14

Update to TypeScript 3.1 and ts-simple-ast 17

---

js/main.ts
src/flags.rs
src/msg.fbs
src/ops.rs
src/version.rs

`deno -v` should report typescript version

---

tools/http_server.py

Interrupt http_server.py by ctrl + c

---

tools/testdata/travis_benchmark.json
website/app.js
website/app_test.js

The script in benchmark page now fetches 2 APIs sequentially. This PR changes it to load them in parallel.
And this PR also fixes the test case of `getTravisData` (//webapp/app.js) by using the mock API data.

perf(webapp): improve performance of benchmark page and fix test

---

js/metrics_test.ts
src/isolate.rs

@ry this PR fixes problem described in #965

Fix logic for Metrics

---

js/dom_types.ts
js/fetch.ts
js/fetch_test.ts
js/unit_tests.ts
js/util.ts
js/util_test.ts

 Make fetch header compliant with the current spec 

---

build_extra/rust/BUILD.gn

Disable warning on linux.

---

Docs.md

fix some typos in Docs.md

---

build_extra/rust/rust.gni

build: clean up the gn template for rust targets a bit

---

website/app.js

Closes #1035
Dropped all style changes from #1036

Fix benchmark page y label

---

BUILD.gn

Windows: don't use ts-node symlinked path

---

.appveyor.yml
.gn
gclient_config.py

Upgrade V8 to 7.1.302.4

---

.appveyor.yml
.travis.yml
Docs.md
gclient_config.py
tools/format.py
tools/test_format.py

CI should fail when code isn't formatted.

---

.appveyor.yml
tools/sync_third_party.py
tools/third_party.py
tools/util.py

Bundle pywin32 in third_party

---

gclient_config.py
tools/format.py
tools/third_party.py

third_party: install yapf with pip

---

tests/http_bench.ts
tools/http_benchmark.py
tools/node_tcp.js

Add node_tcp target to http_benchmark.

---

src/eager_unix.rs
src/main.rs
src/resources.rs

Factor out eager_read_tcp to it's own function

---

tools/benchmark.py

Add error_001.ts to execution time benchmarks.

---

.gn
build_extra/rust/BUILD.gn

Turn on treat_warnings_as_errors

---

Docs.md

1. Fixed a few typos. Most importantly, there was a **code error in the second example**. 
2. Improved a little grammatical and presentational style and consistency.

Minor text fixes and improvements to Docs.md

---

tools/setup.py

Disable treat_warnings_as_errors on windows when sccache is in use

---

BUILD.gn

build: snapshot blob is an input for the snapshot object

---

.appveyor.yml
.travis.yml

Attempt to fix rust version in CI.

---

js/fetch.ts
src/msg.fbs
src/ops.rs
tools/format.py

Small clean ups

---

Docs.md

add  update command for third_party modules

---

src/main.rs

add backtrace on panic

---

js/compiler.ts

This PR fixes the performance regression introduced in #1065 
It appears that trying to "trick" the compiler by swapping compiler options caused TypeScript to do a whole load of reallocation of internals, etc.  Just ignoring the "invalid" error appears to be a better scenario.
My local benchmarks:
|Benchmark|0fbee30 (Before #1065)|6345b60 (Current Master)|eb7104d (This PR)|
|--|--|--|--|
|Cold 002|1.337s|1.895s|1.320s|
|Cold 003|1.396s|2.089s|1.427s|

Fix performance regression with JSON Modules

---

Docs.md

To document it better I added another example which shows how easy it is to use a online resource directly in deno. If it is not required please tell where should it be added otherwise.
This closes issue [#1105](https://github.com/denoland/deno/issues/1105).

Add documentation as per #1105

---

src/deno_dir.rs
src/errors.rs
src/flags.rs
src/isolate.rs
src/msg.fbs
src/msg.rs
src/ops.rs
src/permissions.rs
src/repl.rs
src/resources.rs
src/version.rs

Fix most of the clippy::pedantic warnings

---

.travis.yml

let build fail when lint or test_forma fail #1104

---

tools/docs.py
tools/upload_website.py
website/app.js
website/index.html
website/rustdoc
website/typedoc

typedoc is very bad - but it's better than nothing.
Website is at http://deno.land/

Add script for generating docs

---

js/fetch.ts
js/fetch_test.ts
js/util.ts
src/ops.rs

Does not yet support streaming, only strings and TypedArrays for now.
Needed to support #1123
Fixes #522

Support uploading data from fetch()

---

Docs.md
README.md

Use short install links.

---

Docs.md

Add update to Changelog

---

js/buffer.ts
js/buffer_test.ts

This PR adds test that was marked as TODO in Buffer implementation.

Add test for Buffer edge case

---

tools/repl_test.py

Alphabetization is a little bit churny, but there was an existing test called `test_settimeout` vs the new one `test_set_timeout` from #1233. If they collided only the last defined would have run.
The main change is to allow a sleep kwarg to input (see `test_set_timeout_interlaced`).
cc @kevinkassimo

Cleanup setTimeout repl test and alphabetize

---

BUILD.gn
build_extra/rust/BUILD.gn
libdeno/BUILD.gn
libdeno/deno.gni
tools/format.py

Just for better namespacing.
Fixes #1244

Move libdeno build config to libdeno/BUILD.gn

---

tools/repl_test.py

Fix flaky REPL test.

---

build_extra/rust/get_rustc_info.py
tools/benchmark.py
tools/deno_dir_test.py
tools/gcloud_upload.py
tools/http_server.py
tools/lint.py
tools/permission_prompt_test.py
tools/repl_test.py
tools/setup.py
tools/setup_test.py
tools/sha256sum.py
tools/sync_third_party.py
tools/test_format.py
tools/third_party.py
tools/throughput_benchmark.py
tools/unit_tests.py
tools/util.py
tools/util_test.py

Use pylint.

---

build.rs

Currently gn builds into "target/debug"
however cargo tells gn to build into
"target/debug/build/deno-26d2b5325de0f0cf/out"
This patch changes it so that they both build into "target/debug".

Cargo and GN should build into same directory.

---

js/console.ts
js/console_test.ts

feat: Support for bigints in console

---

.gitattributes

improve .gitattributes

---

tools/third_party.py

third_party: symlink //third_party/v8/build => //build

---

.gitattributes
.travis.yml
libdeno/api.cc
libdeno/deno.h
libdeno/internal.h
libdeno/libdeno_test.cc
tools/memory

Fixes leaks in libdeno and adds minimal LSAN build to travis. There's a long road ahead towards getting an LSAN clean build.
Fixes #1264

Add LSAN build to Travis

---

libdeno/api.cc
libdeno/binding.cc
libdeno/deno.h
libdeno/internal.h
libdeno/libdeno_test.cc
libdeno/snapshot_creator.cc
src/isolate.rs
src/libdeno.rs

In preperation for adding other features to libdeno.

Simplify API for libdeno isolate creation.

---

.gitmodules

Track the master branch of the chromium_build repo

---

Docs.md

Some discoveries myself when trying to profile and debug deno. I believe it might also be useful for others

Add more profiling and debugging guides

---

src/fs.rs
src/ops.rs
src/tokio_util.rs

Resolve a TODO item in source code.

Replace blocking! macro by generic function

---

js/os.ts
src/deno_dir.rs
src/msg.fbs
src/ops.rs

Minor cleanups in deno_dir.rs

---

src/msg.fbs

I changed default value `Base.bool` in src/msg.fbs.

Change default to false Base.bool

---

.travis.yml

travis: remove use_sysroot

---

js/errors.ts

Fix a typo in errors.ts JSDoc

---

BUILD.gn
build_extra/rust/get_cargo_info.cmd
build_extra/rust/get_cargo_info.py
build_extra/rust/run.py
build_extra/rust/rust.gni
src/version.rs

Read the version from Cargo.toml using an `env!()` macro

Read version from Cargo.toml

---

tests/001_hello.test

fix typo for tests

---

website/index.html
website/style.css

Add examples to website.

---

build.rs
src/js_errors.rs
src/snapshot.rs

build: fix RLS-invoked 'cargo check' build

---

js/testing/util.ts
js/testing/util_test.ts

Improve handling of non-coercable objects in assertEqual

---

js/form_data.ts
js/form_data_test.ts
js/headers.ts
js/headers_test.ts
js/mixins/dom_iterable.ts

related issue #1390 
rewrite `set` method to make it follow the specification https://xhr.spec.whatwg.org/#dom-formdata-set

check runtime `FormData` and `Headers` params

---

BUILD.gn
js/dom_file.ts
js/form_data.ts

Rename file.ts to dom_file.ts

---

website/index.html
website/style.css

Might be nicer to just render our README.md as the website... but for now let's continue maintaining it.

Add CI badges to website

---

src/deno_dir.rs

resolve_module: handle "." and ".." referrers

---

Docs.md

docs: update testing module url

---

Docs.md

See [https://github.com/denoland/deno_install/issues/3#issuecomment-451669042](https://github.com/denoland/deno_install/issues/3#issuecomment-451669042).

Add Scoop installation command to Docs.md

---

README.md

See [https://github.com/denoland/deno_install/issues/3#issuecomment-451669042](https://github.com/denoland/deno_install/issues/3#issuecomment-451669042).

Add Scoop installation command to README.md

---

js/deno.ts
js/main.ts
js/os.ts
js/os_test.ts
src/msg.fbs
src/ops.rs

Add deno.pid

---

tools/repl_test.py

Fix flaky REPL test

---

libdeno/binding.cc
libdeno/libdeno_test.cc

Closes #1410
See comments on the code.

Prevent segfault when eval throws an error

---

.prettierignore
libdeno/binding.cc
libdeno/libdeno_test.cc
src/js_errors.rs
tests/async_error.ts.out
tests/error_008_checkjs.js.out
tests/error_syntax.js
tests/error_syntax.js.out
tests/error_syntax.test

Better exceptions (particularly for syntax errors)

---

js/unit_tests.ts

This seems simply passing now.

Restore the test of website/app.js

---

website/index.html

Fix links on website [merge on approval]

---

js/net_test.ts
src/errors.rs
src/main.rs
src/ops.rs
src/resolve_addr.rs

Properly parse network addresses.

---

src/compiler.rs
src/deno_dir.rs
src/flags.rs
src/isolate.rs
src/js_errors.rs
src/main.rs
src/msg.rs
src/ops.rs
src/repl.rs
src/resolve_addr.rs
src/resources.rs
src/workers.rs

Clippy fixes (also fixes build with nightly)

---

.gn

Remove symbol_level=1 override [merge on approval]

---

js/net_test.ts

No longer assume the order of which accept would succeed first (since there is no guarantee about task poll order)

Unflake test netConcurrentAccept

---

js/mkdir.ts
js/mkdir_test.ts
js/read_link_test.ts
js/rename_test.ts
js/symlink_test.ts
src/deno_dir.rs
src/fs.rs
src/msg.fbs
src/ops.rs

mkdir should not be recursive by default

---

js/console.ts
js/console_test.ts

It is a part of #1351.
This is related to before pr(#1360).

Add console clear

---

Docs.md
website/index.html

Add shell installer guide

---

package.json

This commit was cauing a still problem described here:
https://github.com/denoland/deno/issues/1259
This reverts commit d0dc4deaad858babcb612b181986db254db64dfa.

Revert "Upgrade tslint and friends (#1571)"

---

website/index.html
website/manifest.json

Add manifest for Progressive web app

Add PWA manifest to website

---

.editorconfig

Create `.editorconfig` file for easy editor configuration. @ry Please check all properties, maybe they're wrong.

Create .editorconfig file

---

README.md

Replace deprecated 🐍 installer with shell one

Replace 🐍 installer with shell one

---

README.md
website/index.html

Update description in README.md

---

js/repl.ts
tools/repl_test.py

Replace "dot-commands" by functions

Use functions for exit and printing help instead of "dot-commands"

---

tools/benchmark.py
website/app.js

The new snapshot was added in #1566

Add snapshot_compiler.bin to binary size benchmark

---

libdeno/BUILD.gn
libdeno/api.cc
libdeno/binding.cc
libdeno/deno.h
libdeno/exceptions.cc
libdeno/exceptions.h
libdeno/internal.h
libdeno/libdeno_test.cc
libdeno/test.cc
libdeno/test.h
tests/async_error.ts.out
tests/error_004_missing_module.ts.out
tests/error_006_import_ext_failure.ts.out
tests/error_007_any.ts.out
tests/error_008_checkjs.js.out
tests/error_009_missing_js_module.js.out
tests/error_syntax.js.out
tools/lint.py

Moves exception handling out into new file. Adds MessageCallback in preparation for some errors encountered during module resolution in #1579.

libdeno: improve exception handling

---

.appveyor.yml

appveyor: Remove dead code

---

libdeno/BUILD.gn
libdeno/api.cc
libdeno/binding.cc
libdeno/deno.h
libdeno/internal.h
libdeno/libdeno_test.cc
libdeno/modules.cc
libdeno/modules_test.cc
libdeno/snapshot_creator.cc
src/deno_dir.rs
src/errors.rs
src/isolate.rs
src/libdeno.rs
src/main.rs
tests/circular1.js
tests/circular1.js.out
tests/circular1.test
tests/circular2.js
tests/error_009_missing_js_module.js.out
tests/imports_meta.js
tests/imports_meta.js.out
tests/imports_meta.test
tests/imports_meta2.js

Modules refactor try #2

---

js/unit_tests.ts
tools/format.ts
tools/http_benchmark.py
tools/ts_library_builder/test.ts

Upgrade deno_std to bef7ba

---

.github/CONTRIBUTING.md

This adds requiring tests covering the change as a pre-req before raising a PR.

Add item to CONTRIBUTING.md about needing tests

---

src/isolate.rs
src/tokio_util.rs

src: simplify rust code

---

libdeno/api.cc
libdeno/binding.cc
libdeno/deno.h
libdeno/internal.h
libdeno/libdeno_test.cc
libdeno/modules.cc
libdeno/snapshot_creator.cc
src/isolate.rs
src/libdeno.rs

libdeno cleanups / bug fix

---

src/errors.rs
src/isolate.rs
src/js_errors.rs
src/main.rs
tests/error_009_missing_js_module.js.out
tests/error_010_nonexistent_arg.out
tests/error_010_nonexistent_arg.test
tools/integration_tests.py

Better error message on nonexistent CLI argument

---

src/main.rs

Avoid --info crash on missing filename

---

.prettierignore
src/flags.rs
src/main.rs
tests/badly_formatted.js
tests/badly_formatted_fixed.js
tools/fmt_test.py
tools/prefetch_test.py
tools/test.py
tools/util.py

Support --fmt

---

Docs.md
website/index.html
website/style.css

web design

---

website/index.html

Refactor markup of the site

---

js/console_test.ts
js/read_dir_test.ts

I deleted unnecessary permission code.

Fixed test code

---

Docs.md

Add statement about browser compatibility to docs.

---

BUILD.gn
src/ansi.rs
src/js_errors.rs
src/main.rs
tests/async_error.ts.out
tests/error_003_typescript.ts.out
tests/error_004_missing_module.ts.out
tests/error_006_import_ext_failure.ts.out
tests/error_008_checkjs.js.out
tests/error_syntax.js.out
tools/integration_tests.py

Color exceptions

---

.github/CONTRIBUTING.md

I think better to write in this way is that it is more friendly :)

fix: format command in contribution guide

---

libdeno/binding.cc
libdeno/internal.h
libdeno/libdeno_test.cc
libdeno/libdeno_test.js

Shared buffer fixes

---

src/permissions.rs
tools/permission_prompt_test.py
tools/permission_prompt_test.ts

'Deno requests' message were being duplicated.

Fix read permission message

---

js/compiler.ts
js/compiler_test.ts
rollup.config.js

Respect NO_COLOR in TypeScript output

---

js/repl.ts

Fix REPL formatting due to updates of formatting in #1732 .

Fix REPL formatting

---

src/deno_dir.rs

Include deno version in source_code_hash

---

website/benchmarks.html
website/manual.html
website/manual.md
website/style_guide.html

More web design work

---

gclient_config.py
libdeno/api.cc

This is to have access to this fix:
https://bugs.chromium.org/p/v8/issues/detail?id=8838
necessary for v8_postmortem_support.

Upgrade V8 to 7.4.158

---

website/manual.md

To make it clearer how people should indicate that are contributing to Deno.

Update contribution guidelines

---

.gn
gclient_config.py
libdeno/api.cc

So we can use https://github.com/nodejs/llnode/

Turn on v8_postmortem_support

---

tools/benchmark.py
tools/prebuilt.py

Prebuilt hyperfine

---

website/index.html
website/manual.html
website/manual.md
website/style.css
website/style_guide.html

Closes #1753
Apply to all pages on the website.
Add in-line code style.
#1768 repeated this work, but did not seem to follow up.
This pr modifies what ry says.

Syntax highlighting on the website paegs

---

website/benchmarks.html
website/index.html
website/manual.html
website/style_guide.html

The icon is cute, felt like it should be used as the tab icon.
Before & after:

Added website icon link

---

Releases.md
website/index.html
website/manual.md

Update installation documentation (Fixes #1786)

---

website/index.html

Fix http server example in homepage

---

website/manual.md

Closes #1715 
Depends on denoland/deno_std#196

Add example of starting subprocess to docs

---

website/index.html

Revert example changes since https://github.com/denoland/deno_std/pull/188 was reverted (https://github.com/denoland/deno_std/commit/57c9176b19bf4f4580466e088c249cbe9b145119).

fix: revert http server example on the homepage

---

website/manual.html
website/manual.md
website/style.css

Add section explaining resources and metrics to the manual

---

README.md
tools/upload_website.py
website/index.html

Improve readme [merge on approval

---

js/console_table.ts

Fixes https://github.com/denoland/deno/issues/1831

Fix copyright header [merge on approval]

---

website/index.html
website/manual.html
website/manual.md
website/style_guide.html

Use the SVG logo everywhere. Add logo links to manual.

---

src/flags.rs
website/manual.md

Add NO_COLOR to CLI usage

---

.travis.yml

Upgrade Node to v10 on Travis

---

gclient_config.py

upgrade V8 to 7.4.238

---

website/manual.md

Fix example in manual [MoA]

---

website/manual.md

Just a nitpick after changes in #1835

manual - import.meta.main

---

README.md
website/manual.md

Improve tagline in README [merge on approval]

---

website/manual.md

Fix website manual link

---

.gitmodules
js/test_util.ts
js/unit_tests.ts
src/main.rs
tests/fetch_deps.ts
tools/fmt_test.py
tools/http_benchmark.py
website/index.html
website/manual.md

xlink https://github.com/denoland/registry/issues/70

Replace deno.land/x/std with deno.land/std

---

js/build.ts
js/build_test.ts

Rename Deno.build.gnArgs to Deno.build.args

---

js/build.ts
js/deno.ts

See discussion in #1909
cc @kitsonk @kevinkassimo @zekth

Make some renames in js/build.ts

---

core/http_bench.rs

allow v8 cli flags on deno_core_http_bench

---

tools/setup.py

For HomeBrew
https://github.com/Homebrew/homebrew-core/pull/35645

Add --no-binary-download option to setup.py

---

js/text_encoding.ts
js/text_encoding_test.ts

Fix TextDecoder for SharedArrayBuffer backed TypedArray

---

core/isolate.rs
core/shared_queue.js
core/shared_queue.rs
core/shared_queue_test.js

core: remove reset() from SharedQueue API

---

website/manual.md

There may be a more appropriate fix for the error in the manual so feel free to close and I will create an issue.

Fix a missing import in manual.md example for testing

---

website/style_guide.md

Typo fix in styleguide

---

tools/test.py

Re-enable permissions prompt tests

---

tools/build.py
tools/write_gn_args.py
website/manual.md

Instead use: tools/build.py --release

Deprecate DENO_BUILD_MODE=release

---

cli/deno_dir.rs
cli/http_util.rs

async modules are necessary to properly move to the current_thread runtime.

Minor renames and shims to prepare for async modules 

---

cli/cli.rs
cli/compiler.rs
cli/isolate_state.rs
cli/ops.rs
cli/resources.rs
cli/workers.rs

Left over from before 71023d821606ae777d75f9a9023673cb09e3b995?
cc @ry

Remove old Buf definition in cli.rs

---

cli/deno_dir.rs
cli/isolate.rs
cli/ops.rs

Async modules4

---

js/metrics.ts
website/index.html
website/manual.md

Add console.table(Deno.metrics()) example

---

.appveyor.yml
.travis.yml
cli/cli_behavior.rs
cli/compiler.rs
cli/deno_dir.rs
cli/global_timer.rs
cli/ops.rs
cli/permissions.rs
cli/resources.rs

Run Clippy in lint.py

---

README.md
tools/docs.py
website/index.html
website/style.css

Website updates

---

js/custom_event.ts

Check `CustomEvent` constructor params

---

cli/compiler.rs
cli/deno_dir.rs
cli/js_errors.rs
cli/startup_data.rs
core/isolate.rs

Clippy fixes

---

cli/compiler.rs
cli/deno_dir.rs
cli/flags.rs
cli/isolate.rs
cli/isolate_state.rs
cli/modules.rs
cli/ops.rs
tests/023_no_ext_with_mime.test
tests/024_import_no_ext_with_mime.test
tests/025_reload_js_type_error.js
tests/025_reload_js_type_error.test
tools/benchmark.py
tools/fmt_test.py
tools/unit_tests.py
website/manual.md

Ref https://github.com/denoland/deno/issues/1044#issuecomment-462964006
Fixes https://github.com/denoland/deno/issues/1044

Merge the --recompile and --reload flags

---

js/buffer.ts
js/process.ts
js/process_test.ts
website/manual.md

Came up during discussion in #1811

Buffer process stderr

---

cli/build.rs
core/build.rs
tools/format.py
tools/gn.rs
tools/hyper_hello.rs

Call ninja directly from build.rs

---

Cargo.lock
build_extra/rust/BUILD.gn
cli/BUILD.gn
cli/Cargo.toml

Add rust crate 'clap'

---

website/manual.md

Update `deno -h` output in manual

---

website/manual.md

add scoop in the install

---

core/Cargo.toml
core/README.md
core/isolate.rs
website/manual.md

Improve docs in core

---

cli/compiler.rs
cli/isolate.rs

compile_async

---

Releases.md

fix v0.3.6 Releases.md  date error

---

tools/docs.py

Fix tools/docs.py [merge on approval]

---

js/console.ts
js/console_test.ts
js/globals.ts

fix `console instanceof Console`

---

core/isolate.rs

Also use a VecDeque to store pending ops to avoid exponential time complexity
when removing completed ops from the list.

core: poll ops round robin

---

cli/compiler.rs
cli/deno_dir.rs
cli/flags.rs
cli/http_util.rs
cli/ops.rs
cli/permissions.rs
cli/startup_data.rs

Fix clippy warnings and an issue with the check-only build

---

cli/worker.rs

better wait for removed_from_resource_table_on_close test

---

tools/benchmark.py
tools/benchmark_test.py
tools/testdata/time.out
website/app.js
website/benchmarks.html

Add RAM benchmark for max RAM usage during running `deno tests/002_hello.ts --reload`
Resolves #783

RAM benchmark

---

cli/deno_dir.rs
cli/flags.rs
cli/ops.rs
cli/state.rs
cli/tokio_util.rs
cli/worker.rs
core/examples/http_bench.rs
core/js_errors.rs
core/modules.rs

Fix clippy warnings

---

tools/benchmark.py
tools/http_benchmark.py

benchmarks: fix max_memory and clean up

---

js/timers_test.ts
tests/010_set_interval.test
tests/010_set_interval.ts
tests/010_set_interval.ts.out

Fix flaky tests

---

tools/benchmark.py
tools/benchmark_test.py

benchmarks: improve syscall and thread count

---

cli/worker.rs
core/modules.rs

This PR is a quick patch for redirection problems with async load. (using the aliasing logic I added in a previous fix that got deleted in the async load PR)
~~No intention to get this merged. Hope someone else can take on this change and continue working on it.~~
Serves as a reference if this does not sound like the best way to fix it

Fix redirects under async load

---

core/modules.rs

Improve test slow_never_ready_modules

---

website/style_guide.md

- Improve clarity of the text by adding missing `it` word to it.

docs: improve clarity of the text

---

Cargo.lock
build_extra/rust/BUILD.gn
cli/Cargo.toml

third_party: upgrade rust crates

---

.appveyor.yml
.travis.yml

Upgrade CI to Node v12

---

js/symlink_test.ts

Fix symlinkSyncNotImplemented

---

js/url_search_params.ts
js/url_search_params_test.ts

`get` should method should return string
------
PS: I build a website for Deno's Web-Platform-Tests https://deno.dev/wpt/

`URLSearchParams` deleting appended multiple

---

cli/flags.rs
cli/main.rs
tools/fetch_test.py
tools/prefetch_test.py
tools/test.py
website/manual.md

Rename deno prefetch to deno fetch

---

cli/main.rs

compile lib.deno_runtime.d.ts into executable

---

core/modules.rs

re: https://github.com/denoland/deno/issues/2096

build in deps.to_json() and test

---

js/url_search_params.ts
js/url_search_params_test.ts

wpt: https://github.com/web-platform-tests/wpt/blob/master/url/urlsearchparams-constructor.any.js#L1-L10

URLSearchParams init with itself

---

website/benchmarks.html
website/manual.html

Use alt logos on benchmarks and manual page

---

cli/flags.rs

disable --version flag from deno version

---

cli/resources.rs
cli/tokio_util.rs
js/net_test.ts

- recovered changes from https://github.com/denoland/deno/pull/1517
- I don't know why these changes were deleted in 44773c9 , this fix looks fine for me
- cc @kevinkassimo

recover:  #1517 Kill all pending accepts when TCP listener is closed

---

js/text_encoding_test.ts

fix test description for `atob`

---

js/process_test.ts

Disable flaky assert in killSuccess

---

cli/flags.rs
cli/main.rs

Rewrite flags.rs::parse_flags

---

cli/flags.rs

flags: fix merge error

---

.gn
gclient_config.py

Upgrade V8 to 7.6.53

---

website/app.js

Fix max_latency benchmark on zero value

---

tools/ts_library_builder/ast_util.ts

Make error in ast_util more informative.

---

.travis.yml
BUILD.gn
cli/BUILD.gn
core/libdeno/BUILD.gn
core/libdeno/file_util_test.cc
tools/test.py

Rename test targets

---

js/net.ts
js/net_test.ts

Async iterator for listener

---

cli/ops.rs
cli/state.rs
core/examples/http_bench.rs
core/isolate.rs

I'll wait for #2238 to land first

core: express op as enum

---

core/libdeno/api.cc

This patch provides a work-around for an apparent V8 bug where
initializing multiple isolates concurrently leads to a crash on
Windows.
At the time of writing the cause of this crash is not exactly
understood, but it seems to be related to the V8 internal
function win64_unwindinfo::RegisterNonABICompliantCodeRange(),
which didn't exist in older versions of V8.

Work around Windows-only V8 concurrent initialization crash

---

.appveyor.yml
.travis.yml
cli/main.rs
cli/ops.rs
core/isolate.rs
core/modules.rs
core/shared_queue.rs

fix clippy warnings, run clippy in CI

---

js/body_test.ts

cleanup for tests disabled in #2268

fix body formData tests

---

cli/deno_dir.rs
cli/flags.rs
cli/ops.rs
cli/worker.rs

Working on CLI I took a stab at #1581. It still needs work, but wanted to get momentum going

add --no-fetch CLI flag to prevent remote downloads

---

js/console.ts
js/console_test.ts

Closes #2276
Added special handling code in js/console.ts

fix: display "-0" for -0

---

Docs.md
website/manual.md

Minor doc edits

---

core/libdeno/api.cc
core/libdeno/buffer.h

core: make PinnedBuf::Raw -> PinnedBuf conversion actually a move

---

website/benchmarks.html

Reorder benchmark page

---

core/README.md

Deno core typo

---

website/manual.md

Fix a typo

---

cli/flags.rs

Fix command in docs

---

website/style_guide.md

Fixes a small typo in the style guide.

Fix typo in style guide

---

build_extra/rust/rust.gni
cli/BUILD.gn
tools/format.py

Misc. fixes

---

website/benchmarks.html

website: fix workers benchmark links

---

Cargo.lock
Releases.md
cli/Cargo.toml
core/Cargo.toml
core/README.md

Bump v0.6.0

---

website/index.html
website/style_guide.md

website: update http example

---

cli/ops.rs
tools/complex_permissions_test.py
tools/complex_permissions_test.ts

This reverts commit 7219787894f13b1920b3b6b49203cdcb8f672c00.

Revert "Fix permissions for dial and listen (#2373)"

---

website/manual.md

Fix permissions example to add new TextEncoder()

---

cli/flags.rs

Improve CLI help

---

cli/ops.rs
tools/complex_permissions_test.py
tools/complex_permissions_test.ts

re-fix permissions for dial and listen

---

website/manual.md

Use shellsession for consistency with the commands above.

Add brew install deno to manual

---

cli/main.rs

Add module and line no for Rust logger

---

tools/complex_permissions_test.py
tools/permission_prompt_test.py
tools/setup_test.py
tools/test.py
tools/util_test.py

chore: Port Python tests to unittest

---

website/index.html

Add 'brew install deno' to homepage

---

js/fetch.ts
js/fetch_test.ts

This is a short term fix for #2433.
#2332 will have a more robust fix + cleanup for some reduntant stuff in fetch.

use body when Request instance is passed to fetch (fixes #2433)

---

cli/flags.rs

This PR adds `--stdout` option to `deno fmt`, which outputs the formated code to stdout.
```shellsession
$ cat tests/badly_formatted.js 
console.log(
"Hello World"
)
$ ./target/debug/deno fmt --stdout tests/badly_formatted.js 
console.log("Hello World");
$ cat tests/badly_formatted.js 
console.log(
"Hello World"
)
$ ./target/debug/deno fmt tests/badly_formatted.js 
Formatting tests/badly_formatted.js
$ cat tests/badly_formatted.js 
console.log("Hello World");
```
closes #2090

Add deno fmt --stdout option

---

.appveyor.yml
tools/benchmark_test.py
tools/complex_permissions_test.py
tools/deno_dir_test.py
tools/fetch_test.py
tools/fmt_test.py
tools/integration_tests.py
tools/is_tty_test.py
tools/permission_prompt_test.py
tools/repl_test.py
tools/setup_test.py
tools/target_test.py
tools/test.py
tools/test_util.py
tools/unit_tests.py
tools/util.py
tools/util_test.py

Follow up to #2414
There are still some things I want to cleanup before merging

chore: finish tests refactor

---

js/compiler.ts
tests/error_003_typescript2.test

Fixes https://github.com/denoland/deno/issues/2436

Compiler exit before emit if preEmitDiagnostics found

---

core/libdeno/binding.cc
core/libdeno/deno.h
core/libdeno/internal.h
core/libdeno/libdeno_test.cc
core/libdeno/modules.cc
core/libdeno/modules_test.cc
core/libdeno/snapshot_creator.cc

Towards https://github.com/denoland/deno/issues/1789. It still needs to be surfaced in core.

libdeno: expose dynamic import

---

cli/flags.rs

One character edit, but still a contribution 😛

✏️ Fixing CLI help typo

---

website/style.css

website: use pre-wrap

---

cli/BUILD.gn
core/libdeno/binding.cc
gclient_config.py

Upgrade V8 to 7.7.37

---

tools/test.py

Move TestFmt to end of tests

---

cli/main.rs
cli/state.rs
cli/worker.rs

Move Modules to ThreadSafeState

---

js/dom_types.ts
js/globals.ts

Small cleanup for `Request` global type.

makes global request type an interface

---

js/fetch.ts
js/globals.ts

Ref: #2108
Response was not exposed on `window`

expose window.Response

---

cli/dispatch_minimal.rs
cli/errors.rs
cli/msg.fbs
cli/ops.rs
cli/state.rs
core/core.d.ts
core/examples/http_bench.js
core/examples/http_bench.rs
core/isolate.rs
core/libdeno.rs
core/libdeno/api.cc
core/libdeno/deno.h
core/libdeno/libdeno.d.ts
core/libdeno/libdeno_test.cc
core/shared_queue.js
core/shared_queue.rs
js/dispatch.ts
js/dispatch_minimal.ts

Due to performance regression:
https://github.com/denoland/deno/commit/dc60fe9f300043f191286ef804a365e16e455f87#commitcomment-33943711

Revert "Refactor dispatch handling (#2452)"

---

cli/flags.rs

fix: deno install 

---

cli/flags.rs

Upgrade INSTALLER_URL to include fixes

---

website/app.ts
website/benchmarks.html
website/style.css

Also fixes a couple of typos and css positioning of spinner.
https://github.com/denoland/deno/issues/2508

Fixes benchmark page spinner not hiding on Edge #2508

---

js/globals.ts
js/timers.ts
js/timers_test.ts

fix function name

---

cli/Cargo.toml

Change cargo deps sync tool path in comment

---

js/text_encoding.ts
js/text_encoding_test.ts

TextEncoder.encodeInto

---

cli/msg.fbs
cli/ops.rs
js/deno.ts
js/os.ts
js/os_test.ts

Add userHomeDir to Deno namespace

---

website/manual.md

Fixes https://github.com/denoland/deno/issues/1898

manual: adjust windows build instructions

---

tools/ts_library_builder/README.md

ts_library_builder: update README

---

cli/deno_error.rs
cli/msg.fbs
core/lib.rs
core/module_specifier.rs
tests/error_011_bad_module_specifier.ts.out
tests/error_012_bad_dynamic_import_specifier.ts.out

core: return useful error when import path has no prefix like ./

---

.rustfmt.toml
cli/deno_dir.rs
cli/flags.rs
cli/import_map.rs
core/module_specifier.rs

Miscellaneous small improvements

---

website/index.html
website/manual.md

See https://github.com/denoland/deno_install/issues/70
cc @ry

Fix denoland/deno_install#70

---

cli/flags.rs
website/index.html
website/style_guide.md

Update deno.land links v0.11

---

cli/deno_error.rs
tools/repl_test.py

Fix REPL when it receives EOF

---

js/console.ts
js/globals.ts

cc @bartlomieju in https://github.com/denoland/deno/pull/2073#discussion_r303401539

rewirte console constructor

---

website/manual.md

Edits to manual

---

website/index.html

Improve example on homepage

---

cli/deno_dir.rs

Remove unnecessary required function from SourceFileFetcher

---

cli/compiler.rs
cli/deno_dir.rs
cli/deno_error.rs
cli/msg.fbs

save headers for all intermediate redirects

---

core/isolate.rs
core/libdeno.rs
core/libdeno/deno.h
core/libdeno/exceptions.cc
core/libdeno/exceptions.h
core/libdeno/internal.h
core/libdeno/modules.cc
core/libdeno/modules_test.cc

Add error handling for dynamic imports to libdeno

---

cli/flags.rs
website/manual.md

cli: unify deno -h options

---

cli/flags.rs
tests/version_long_flag.test
tests/version_short_flag.test

cli: handle deno -v and deno --version

---

js/unit_test_runner.ts

As [deno_std/#545](https://github.com/denoland/deno_std/pull/545)

Make shebangs Linux compatible

---

js/os.ts

Per https://github.com/denoland/deno/pull/2743#pullrequestreview-271642563
cc @nayeem-rahman

Fix small execPath issues

---

cli/ops.rs
tests/026_workers.ts
tests/039_worker_deno_ns.ts
tests/039_worker_deno_ns/has_ns.ts
tests/039_worker_deno_ns/no_ns.ts
tests/workers_round_robin_bench.ts
tests/workers_startup_bench.ts

ref #2475
I figure this is preferable, since it solves #2475 and when/if we add main module to `import.meta` this should be very predictable.

Resolve worker specifiers relative to main module of host.

---

Cargo.lock
build_extra/rust/BUILD.gn
cli/Cargo.toml

build: enable 'derive' feature of 'serde' crate

---

website/manual.md

update `deno help` output

---

js/timers.ts
js/timers_test.ts

clearTimeout's params should not be bigint

---

website/manual.md

fix list style

---

.travis.yml
cli/BUILD.gn
cli/compilers/ts.rs
cli/file_fetcher.rs
cli/worker.rs
tools/target_test.py
tools/test_util.py

Run tests after "cargo build" on travis

---

core/libdeno/BUILD.gn

build: on windows, don't pass -glldb to clang

---

js/fetch.ts
js/fetch_test.ts
js/test_util.ts

This PR implements bodyUsed property of fetch response. Closes #1605.

fetch: implement bodyUsed

---

Cargo.lock
cli/Cargo.toml

feat: use trust-dns-resolver in HTTP client

---

website/manual.md

Fixes #2882 
small general improvement to manual.md to fix general readability

docs: improve readability

---

js/body_test.ts
js/globals.ts
js/lib.deno_runtime.d.ts

Expose the DOM Body interface globally

---

tools/docs.py
tools/sync_rust_crates.py
tools/third_party.py

Minor fixes in tools/

---

tools/target_test.py

Remove error message mentioning build.py

---

tools/benchmark.py
tools/benchmark_test.py
tools/complex_permissions_test.py
tools/format.py
tools/http_benchmark.py
tools/lint.py
tools/permission_prompt_test.py
tools/setup.py
tools/setup_test.py
tools/test_format.py
tools/third_party.py
tools/throughput_benchmark.py
tools/util_test.py

depot_tools is removing pylint from its distribution so we must maintain
our own copy.

Maintain our own copy of pylint

---

cli/deno_error.rs
core/any_error.rs
js/fetch_test.ts

fix: panic during fetch

---

cli/Cargo.toml

Remove old comment about gn build

---

.eslintrc.json
.prettierignore
tools/complex_permissions_test.py
tools/complex_permissions_test.ts
tools/deno_http_proxy.ts
tools/lint.py
tools/node_tcp_promise.js
tools/permission_prompt_test.ts
website/app.ts
website/app_test.ts
website/showdown_toc.js

Fix and enable linting of deno_typescript, tools, website dirs

---

cli/diagnostics.rs
cli/tests/error_003_typescript.ts
cli/tests/error_003_typescript.ts.out
deno_typescript/lib.rs
js/diagnostics.ts
package.json

Update to TypeScript 3.6.3

---

.github/workflows/build.yml
.github/workflows/lint.yml
tools/target_test.py
tools/test.py

Try github actions

---

.github/workflows/build.yml
.github/workflows/lint.yml

Run github actions on all pull requests

---

.appveyor.yml
.travis.yml

Remove the target directory from cache (as is done successfully in GH actions)

Add RUSTC_WRAPPER to appveyor and travis

---

website/style.css

fix #2992 
Changed color of benchmark chart in dark mode.

fix chart color in dark mode

---

cli/compilers/ts.rs

This PR fixes the loading of the config file. PathBuf.canonicalize returns err when the path doesn't exist, but it wasn't handled.
The command in #2975 show the following error in this branch:
```console
$ ./target/debug/deno -Acli/tests/001_hello.js
Could not find the config file: /path/to/deno/li/tests/001_hello.js
```
closes #2975

Fix handling of config file

---

cli/ops/timers.rs
js/timers.ts

Fix abrupt exit when global timer fires early

---

Cargo.lock
cli/Cargo.toml
cli/ops/mod.rs
cli/ops/tls.rs
cli/resources.rs
js/deno.ts
js/dispatch.ts
js/lib.deno_runtime.d.ts
js/net.ts
js/tls.ts
js/tls_test.ts
js/unit_tests.ts

Co-authored-by: Bartek Iwańczuk <biwanczuk@gmail.com>

feat: Add Deno.dialTLS()

---

cli/tests/043_xeval_delim2.test
cli/tests/044_bad_resource.test
cli/tests/044_bad_resource.ts
cli/tests/integration_tests.rs

fix: run all integration tests

---

Cargo.lock
cli/Cargo.toml
cli/ops/mod.rs
cli/ops/os.rs
js/deno.ts
js/dispatch.ts
js/lib.deno_runtime.d.ts
js/os.ts
js/os_test.ts

Add Deno.hostname()

---

.github/workflows/build.yml
.github/workflows/lint.yml
.travis.yml

Gh actions benchmark2

---

deno_typescript/README.md

fix typo in deno_typescript readme

---

README.md
website/index.html

Use github action badges

---

core/libdeno/.gn
gclient_config.py

Upgrade V8 to 7.9.218

---

website/manual.md

Fix some examples in the manual

---

std/prettier/vendor/index.d.ts

Moved from https://github.com/denoland/deno_std/pull/628
Close https://github.com/denoland/deno_std/issues/626

std: update prettier type definition

---

cli/flags.rs
website/index.html
website/manual.md

Update various links to deno_std

---

cli/flags.rs

Closes #2405
This PR adds functionality to expand host passed to `--allow-net`. If you pass "bare port" then it will be expanded to: `0.0.0.0:port`, `127.0.0.1:port` and `localhost:port`.

feat: support --allow-net=:4500

---

.github/workflows/build.yml
cli/tests/tty_tests.rs
gclient_config.py

Upgrade V8 to 7.9.304

---

std/flags/bool_test.ts

std(flags): Add test for multiple boolean flags

---

tools/docs.py

Fix tools/docs.py

---

cli/js/timers.ts
cli/js/timers_test.ts

Fixes #3142 
Bug introduced in 93b7acf99d6456e6e194c03f024b788ce5adf20e

Fix clearTimer bug

---

std/examples/README.md
std/examples/curl.ts
website/manual.md

Adds a simple curl example with a reference in the manual.
Closes: https://github.com/denoland/deno/issues/3145

Closes: Issue #3145 curl.ts example with reference in manual

---

cli/tests/util/mod.rs

Fix build warning

---

tools/permission_prompt_test.ts

I've cleanup it for consistency with other code.

Small cleanups in perrmission_prompt_test.ts

---

cli/ops/net.rs
cli/ops/tls.rs
cli/permissions.rs
cli/resolve_addr.rs
cli/state.rs
core/modules.rs

refactor DenoPermissions.check_net & resolve_addr

---

std/examples/welcome.ts

welcome.ts

---

std/manual.md
std/style_guide.md

cc @dshubhadeep 
ref https://github.com/denoland/deno_website2/pull/32

change magic table of contents thing

---

.github/workflows/build.yml

Use windows-2019 image in Github Actions

---

CONTRIBUTING.md

Fixes: https://github.com/denoland/deno/issues/3214

chore: update contribution guide link

---

std/manual.md

- updating links for `deno types`
- updating link for `--v8-options`
- fixing broking link testingifcurrentfileisthemainprogram -> testing-if-current-file-is-the-main-program
- updating images link to denoland website 
- updating style guide link

Updating broken links

---

.github/workflows/ci.yml
README.md

just to satisfy my obsessive compulsive disorder and align this table...

Rename Github Actions workflow

---

cli/js/files.ts

Use top-level await in typedoc

---

cli/js/rbtree.ts
cli/js/timers.ts

Fixes #2615 
This is nothing more than a line-by-line replacement of dueMap with dueTree, a red-black tree. No timer implementation logic is changed.
The red-black tree implementation is copied from https://github.com/vadimg/js_bintrees/blob/master/lib/rbtree.js , with types annotated.

Replace timer dueMap with rbtree to avoid apocalypse

---

cli/js/body.ts
cli/js/fetch.ts

Something happened that caused max latency for "deno_proxy" to go to 0. Very difficult to see because the color selection of the yellow is so bright 
cc @lucacasonato (regarding color)
cc @nstott (regarding revert)

Revert "reduce redundancies in the fetch code (#3249)"

---

cli/tests/integration_tests.rs

https://github.com/denoland/deno/issues/3269

Disable flaky tests

---

.github/workflows/ci.yml

Exclude prebuilt from deno_src release

---

std/manual.md

manual: add chocolatey install instructions

---

std/http/server.ts

Fix jsdoc in std/http/server.ts

---

.github/workflows/ci.yml
cli/compilers/ts.rs

Upgrade to Rust 1.39.0

---

cli/tests/integration_tests.rs
core/libdeno/api.cc
core/libdeno/exceptions.cc
core/libdeno/internal.h
core/libdeno/modules.cc
tools/gclient_config.py

This upgrade includes a small fix to V8's BUILD.gn file: https://github.com/denoland/deno_third_party/commit/989bc2a0309782d3ce5c23d945a952ee610e15af
Also review the rebased build patch: https://github.com/denoland/chromium_build/commit/b3fe5cb48e9399765ec103ca0c14057f77cf9fc3. Note the additional `$coverage_wrapper` in the commands compared to [previous versions of the patch](https://github.com/denoland/chromium_build/commit/6af664c48ed657b89e99a9a8692dc15d7f7a6d9c).

upgrade: V8 8.0.192

---

std/manual.md

executed in PS:
```
PS> git config --global core.symlinks=true
error: invalid key: core.symlinks=true
```

fix manual

---

cli/flags.rs

flags: bump std to v0.23.0

---

cli/js/url.ts
cli/js/url_test.ts

```bash
> new URL(“about:blank”)
```
expected:
```
{ href: “about:blank”, protocol: “about:”, origin: “null”, ... }
```
actual:
```
{ href: “about://blank”, protocol: “about:”, origin: “about://”, ... }
```
___
```bash
> new URL(“0.0.0.0:8080”)
```
expected: Error
actual:
```
{ href: “0.0.0.0://8080”, ... }
```

fix js/url

---

cli/test_util.rs
cli/tests/integration_tests.rs

This reverts commit dbf861f8a02f4a90ef68a4e2741b973becc53438.
This didn't fix the problem https://github.com/denoland/deno/runs/302044357

Revert "tests: share http server between tests (#3336)"

---

std/manual.md

Add wasm example to manual

---

core/examples/http_bench.rs

fix: deno_core_http_bench

---

cli/flags.rs

feat: add --check for deno fmt

---

std/http/README.md
std/manual.md

chore: improve examples

---

cli/js/realpath_test.ts
cli/ops/fs.rs

fix realpath behavior in windows

---

cli/ops/net.rs
cli/ops/tls.rs
core/isolate.rs

Temporarily disabling eager polling for ops to help transition to Tokio 0.2 and further worker refactors
CC @ry

disable eager polling for ops

---

cli/ops/plugins.rs
test_plugin/tests/test.js

Wrap plugin ops in ThreadSafeState.core_op

---

core/libdeno/binding.cc
core/libdeno/buffer.h

Ref: https://docs.google.com/document/d/1sTc_jRL87Fu175Holm5SV0kajkseGl2r8ifGY76G35k/edit
Ref: https://chromium-review.googlesource.com/c/v8/v8/+/1859628
Ref: https://github.com/nodejs/node/pull/30339

Replace deprecated GetContent with GetBackingStore

---

test_plugin/tests/integration_tests.rs

Ref https://github.com/denoland/deno/pull/3474
cc @afinch7

Disable flaky plugin test on windows

---

std/http/file_server.ts
std/http/file_server_test.ts

(std/file_server): add help & switch to flags

---

std/http/file_server.ts
std/http/file_server_test.ts

(std/file_server): add utf8

---

cli/file_fetcher.rs
cli/global_state.rs
cli/tests/lock_check_err.out
cli/tests/lock_check_err2.out

Use async-await at few places, fix spelling mistake

---

std/fs/empty_dir.ts
std/fs/empty_dir_test.ts
std/fs/testdata/empty_dir.ts
std/fs/testdata/empty_dir_sync.ts

fix permission errors are swallowed by fs.emptyDir

---

cli/js/deno.ts
cli/js/lib.deno_runtime.d.ts
cli/js/os.ts
cli/js/os_test.ts
cli/ops/os.rs

Reduce all directory functions to Deno.dir()

---

std/manual.md

Just a small code example fix.

Fix code example on /std/manual.md#resources

---

cli/ops/io.rs

Remove unnecessary use of Pin, use ready!

---

cli/js/custom_event.ts
cli/js/custom_event_test.ts
core/isolate.rs
core/libdeno/modules.cc
core/modules.rs
core/shared_queue.rs
tools/format.py

Add missing year ranges to copyright notices

---

Cargo.lock
cli/Cargo.toml

chore: disable default reqwest features

---

cli/compilers/js.rs
cli/compilers/json.rs
cli/compilers/ts.rs
cli/compilers/wasm.rs
cli/disk_cache.rs
cli/file_fetcher.rs
cli/global_state.rs
cli/ops/compiler.rs
cli/ops/dispatch_minimal.rs
cli/ops/net.rs
cli/ops/process.rs
cli/ops/workers.rs
cli/state.rs
cli/worker.rs

Use async at places, use &self instead of self: &Self

---

core/libdeno.rs

Removes `UserDataScope` and replaces it with two explicit fields: `resolve_context_` and `core_isolate_`.
<s>This is a bit more code, but now we can clearly see what's passed around.</s>

libdeno: remove UserDataScope

---

core/isolate.rs
core/libdeno.rs

libdeno: don't pass pointers between core::Isolate and libdeno

---

Cargo.lock
cli/Cargo.toml
core/Cargo.toml
deno_typescript/Cargo.toml
test_plugin/Cargo.toml
tools/hyper_hello/Cargo.toml
tools/hyper_hello/hyper_hello.rs

Upgrade rust crates and modernize hyper_hello

---

std/manual.md

doc: Add glib2.0 as a build prerequisite

---

cli/js/lib.deno_runtime.d.ts
cli/js/mkdir.ts
cli/js/mkdir_test.ts
std/fs/empty_dir.ts
std/fs/ensure_dir.ts
std/fs/ensure_dir_test.ts
std/fs/ensure_file_test.ts
std/fs/ensure_link_test.ts
std/fs/ensure_symlink_test.ts
std/fs/move_test.ts
std/fs/walk_test.ts
std/io/util.ts

fix: Deno.mkdir should conform to style guide

---

cli/flags.rs

Upgrade subcommands to 0.28.1

---

Cargo.lock
core/Cargo.toml

Upgrade rusty_v8 to 0.0.24

---

cli/flags.rs

This PR fixes #3658.
ref: #3628

flag: upgrade std to v0.29.0

---

tools/http_benchmark.py

benchmarks: extend HTTP bench to 20s

---

std/examples/README.md
std/examples/curl.ts

fix: examples/curl.ts
Related: #3621 #3628

fix: examples/curl.ts

---

cli/http_util.rs

- fixed: #3656 
- This PR just reverts 011d485 
- I don't know what is going on, but works fine now...

fix: process hangs when fetch called

---

std/node/README.md
std/node/module.ts
std/node/timers.ts

Also added an overview of supported builtins.

feat(std/node/timers): Added node timers builtin

---

std/manual.md

doc: fix spaces of code in list

---

.github/workflows/ci.yml

fix(ci) setup-python

---

cli/flags.rs
cli/ops/permissions.rs

fix: Resolve read/write whitelists from CWD

---

cli/js/dispatch.ts
cli/js/dispatch_json.ts
cli/js/dispatch_minimal.ts
cli/js/os.ts
cli/js/plugins.ts
core/examples/http_bench.js
core/isolate.rs
core/shared_queue.js
deno_typescript/lib.deno_core.d.ts

This should make moving `dispatch_json` to core much easier.

feat: support individual async handler for each op

---

test_plugin/tests/integration_tests.rs

Fix warnings on windows build

---

Cargo.lock
cli/Cargo.toml

Upgrade crate deps

---

cli/js/compiler.ts
cli/js/compiler_api.ts
cli/js/lib.deno_runtime.d.ts

fixes #3624
fixes #3702 
cc @kitsonk

Fix compile and bundle api types

---

.github/workflows/ci.yml
tools/cargo_publish.py

Auto cargo-publish on tags

---

std/fs/empty_dir_test.ts
std/http/README.md
std/http/server.ts
std/http/server_test.ts

Towards #3689 
Default encode UTF8.

std/http: allow response body to be string

---

tools/benchmark.py

Debug strace issue

---

cli/lib.rs
deno_typescript/lib.rs
deno_typescript/ops.rs

Maybe solves https://github.com/denoland/deno/issues/3712

Fix "cargo publish deno" by reverting asset change

---

Cargo.lock
core/Cargo.toml
core/bindings.rs
core/es_isolate.rs
core/isolate.rs
core/shared_queue.rs

Upgrade to rusty_v8 v0.1.1

---

.github/workflows/ci.yml
cli/Cargo.toml
cli/build.rs
cli/js/compiler_bootstrap.ts
cli/js/compiler_host.ts
cli/js/compiler_util.ts
deno_typescript/lib.rs
deno_typescript/ops.rs

refactor: snapshotting

---

cli/js/lib.deno_runtime.d.ts

Mark signal APIs as unstable

---

std/node/util_test.ts

Adding some tests to test isSymbol in util.ts

Tests for isSymbol in std/node/util_test.ts

---

cli/lib.rs
cli/ops/worker_host.rs
cli/worker.rs
core/any_error.rs
core/bindings.rs
core/es_isolate.rs
core/isolate.rs

Refactor error tracking and scope juggling in deno_core

---

cli/colors.rs
cli/shell.rs

Remove dead code in cli/shell.rs

---

Cargo.lock
core/Cargo.toml
core/shared_queue.rs

Upgrade rusty_v8

---

cli/build.rs

Try to fix docs.rs for cli crate

---

Cargo.lock

Upgrade Rust crates

---

cli/lib.rs
cli/tokio_util.rs

Depends on https://github.com/denoland/deno/pull/3830

Use #[tokio::main]

---

std/examples/tests/xeval_test.ts
std/examples/xeval.ts

Per request https://github.com/denoland/deno/pull/3630#issuecomment-580003391

examples: bring back examples/xeval.ts

---

.github/workflows/ci.yml
tools/hyper_hello/hyper_hello.rs

upgrade: rust 1.41.0

---

cli/build.rs

Add NO_BUILD_SNAPSHOTS to speed up incremental builds

---

cli/file_fetcher.rs
cli/http_util.rs

Use tokio::test for some of cli's unit tests

---

Cargo.lock
cli/Cargo.toml
cli/fmt.rs

ref https://github.com/denoland/deno/issues/3873

upgrade: dprint 0.3.0-alpha.6

---

cli/tests/integration_tests.rs

installer: reenable tests

---

std/ws/mod.ts
std/ws/test.ts

- `WebSocket.send()` should write frames serially even if called in concurrent.
- Added basic mutex executor to `WebSocketImpl` for each websocket frame.
- Each `send()` / `ping()` call waits for resolution of queued calls.
- fixes #3880

fix: #3880 make WebSocket.send() exclusive

---

std/path/glob.ts
std/path/glob_test.ts
std/path/globrex.ts
std/path/globrex_test.ts

Maybe of interest to @terkelg.

fix(std/path/globrex.ts): Use non-capturing groups in globrex()

---

cli/compilers/js.rs
cli/compilers/json.rs
cli/compilers/ts.rs
cli/compilers/wasm.rs
cli/global_state.rs
cli/tests/integration_tests.rs

Fixes 015_duplicate_parallel_import
ref https://github.com/denoland/deno/issues/3876

Prevent TS compiler from running in parallel

---

cli/compilers/ts.rs
cli/compilers/wasm.rs
cli/global_state.rs
cli/lib.rs
cli/state.rs
cli/worker.rs

Rename ThreadSafeGlobalState to just GlobalState

---

cli/lib.rs

Fix deno types | head

---

cli/ops/dispatch_json.rs
cli/tokio_util.rs

Enable thread pool for blocking ops

---

Cargo.lock
cli/ops/io.rs
cli/ops/net.rs
cli/ops/plugins.rs
cli/ops/process.rs
cli/ops/repl.rs
cli/ops/signal.rs
cli/ops/tls.rs
core/Cargo.toml
core/examples/http_bench.js
core/examples/http_bench.rs
core/resources.rs
tools/http_benchmark.py

Make http_bench single-threaded

---

cli/ops/dispatch_json.rs
core/isolate.rs
core/shared_queue.rs

no longer require aligned buffer for shared queue

---

std/node/fs.ts
std/node/fs_test.ts

Add readlink, readlinkSync for std/node/fs.ts
Add readlink'test, readlinkSync'test for std/node/fs_test.ts

Add readlink, readlinkSync for std/node/fs.ts

---

Cargo.lock
cli/Cargo.toml

fixes https://github.com/denoland/deno/issues/3883

upgrade: dprint-plugin-typescript 0.5.0

---

std/ws/README.md
std/ws/example_client.ts

Update ws client example

---

.github/workflows/ci.yml
Cargo.lock
cli/Cargo.toml
cli/fmt.rs
cli/fs.rs
cli/lib.rs
cli/test_runner.rs

[WIP] deno test dirs 2

---

std/examples/tests/xeval_test.ts
std/examples/xeval.ts
std/io/bufio.ts
std/io/bufio_test.ts

Continues from #3497.
cc @bartlomieju @kevinkassimo 
https://github.com/denoland/deno/blob/72bac705e675ecb55d0f08886b3fb33de4f1382e/std/io/bufio.ts#L533-L537
https://github.com/denoland/deno/blob/72bac705e675ecb55d0f08886b3fb33de4f1382e/std/io/bufio.ts#L592-L596
https://github.com/denoland/deno/blob/72bac705e675ecb55d0f08886b3fb33de4f1382e/std/io/bufio.ts#L604-L607

feat(std/io): Export readDelim(), readStringDelim() and readLines() from bufio.ts

---

Cargo.lock
cli/Cargo.toml

upgrade: dprint 0.6.0

---

cli/compilers/compiler_worker.rs
cli/compilers/ts.rs
cli/compilers/wasm.rs
cli/ops/worker_host.rs
cli/state.rs
cli/web_worker.rs

Refactored to do the loop inside `WebWorker::poll`

refactor: remove run_worker_loop

---

Cargo.lock
cli/Cargo.toml

upgrade: dprint 0.6.1

---

cli/compilers/compiler_worker.rs
cli/js/unit_tests.ts
cli/js/workers_test.ts
cli/tests/subdir/fetching_worker.js
cli/web_worker.rs

fix: add io ops to worker to fix fetch

---

std/examples/README.md

Because it not worked well. :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/denoland/deno/4076)

Fix example doc

---

Cargo.lock
cli/Cargo.toml
cli/http_util.rs
cli/tests/053_import_compression.out
cli/tests/053_import_compression/main.ts

closes https://github.com/denoland/deno/issues/3650

support brotli for fetch op

---

cli/permissions.rs

This PR introduces the mutex guard for the test cases which depends on the permission prompt mocking utility. `permission_request` test cases depend on the mocked (dummy) value of the permission_prompt result. The value is stored at `static STUB_PROMPT_VALUE: AtomicBool` and these test cases share this value. So we should lock at the start of these test cases.
Before this change `cargo test permission` failed 6 times out of 20. After this change, 0 times out of 20 (on my mac).
---
closes #4051

test: add mutex guard for permission request tests

---

std/examples/chat/server_test.ts

Ref https://github.com/denoland/deno/issues/4108
Temporarly disabling `std/examples/chat` tests for Windows as CI on `master` went red because of it.

disable std/examples/chat tests for windows

---

Cargo.lock
cli/Cargo.toml
cli/colors.rs
cli/js/os_test.ts
cli/lib.rs
cli/permissions.rs
std/encoding/testdata/cargo.toml
std/encoding/toml_test.ts

https://github.com/denoland/deno/issues/4112#issuecomment-590545385
cc @jsouto18

Revert removal of ansi_term

---

cli/compilers/js.rs
cli/compilers/json.rs
cli/compilers/mod.rs
cli/compilers/ts.rs
cli/compilers/wasm.rs
cli/file_fetcher.rs
cli/global_state.rs
cli/http_util.rs
cli/lib.rs
cli/ops/compiler.rs
cli/ops/runtime_compiler.rs

Remove _async from method names since _sync are gone

---

cli/flags.rs
cli/global_state.rs
cli/installer.rs
cli/lib.rs
cli/permissions.rs
cli/tests/integration_tests.rs
cli/worker.rs

DenoFlags -> Flags

---

Cargo.lock
core/Cargo.toml
core/bindings.rs
core/es_isolate.rs
core/isolate.rs

Upgrade to rusty_v8 v0.3.3

---

cli/ops/io.rs

remove Read/Write futures, use poll_fn instead

---

.github/workflows/ci.yml
tools/lint.py

Add clippy to /tools/lint.py

---

cli/ops/net.rs
cli/ops/process.rs
cli/ops/tls.rs

replace impl Future with poll_fn for net.rs, process.rs, tls.rs

---

std/examples/colors.ts
std/fs/empty_dir_test.ts
std/fs/exists_test.ts
std/http/file_server_test.ts
std/io/util_test.ts
std/uuid/tests/isNil.ts

misc: reduce unnecessary stdout output on tests (Part2)

---

cli/fmt.rs
cli/tests/integration_tests.rs

Return non-zero exit code on malformed stdin fmt

---

cli/js/workers_test.ts
core/es_isolate.rs
core/isolate.rs

Merge mod_evaluate() and mod_evaluate_dyn_import() methods

---

cli/test_util.rs

This reverts commit e6167c78134182c45689bda7bcb12af05009349c.

Revert "chore: share HTTP server between tests (#3966)"

---

Cargo.lock
core/Cargo.toml

upgrade: rusty_v8 0.3.4 (attempt2)

---

cli/js/files.ts

docs: fix broken example

---

core/bindings.rs
core/isolate.rs

Refactor exception handling, remove message listener callback

---

cli/fs.rs
cli/js/chmod.ts
cli/js/chown.ts
cli/js/copy_file.ts
cli/js/dir.ts
cli/js/file_info.ts
cli/js/files.ts
cli/js/io.ts
cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.shared_globals.d.ts
cli/js/link.ts
cli/js/make_temp.ts
cli/js/mkdir.ts
cli/js/read_dir.ts
cli/js/read_file.ts
cli/js/read_link.ts
cli/js/remove.ts
cli/js/rename.ts
cli/js/stat.ts
cli/js/stat_test.ts
cli/js/symlink.ts
cli/js/truncate.ts
cli/js/utime.ts
cli/js/write_file.ts
cli/ops/fs.rs

This is the first of a series of smaller PRs towards #4017.
(I had earlier created #4192, #4193, #4195, #4196, but those were too bloated. Am trying to break them into smaller standalone pieces. However, the later PRs in the sequence are non-trivial to merge with this one. So am pushing this first for review, and once it's merged into master, will base the rest on top of it.)

Cleanup comments and internal variables

---

cli/js/lib.deno.ns.d.ts
cli/js/metrics.ts
cli/js/metrics_test.ts
cli/metrics.rs
cli/ops/runtime.rs
cli/state.rs

Opening separate PR as requested in https://github.com/denoland/deno/pull/4209#pullrequestreview-367296350

feat: update metrics to track different op types

---

cli/tests/integration_tests.rs

Ref https://github.com/denoland/deno/issues/4049

Disable flaky and broken tests

---

cli/js/errors.ts
cli/js/lib.deno.ns.d.ts

Remove Deno.errors.Other

---

cli/js/event_target_test.ts

fix: event target tests

---

std/manual.md

Further to my cargo build issues the other day, this PR updates the manual with a few actions which can be taken to recover.

Provide more info on how to recover from cargo build errors

---

cli/tests/integration_tests.rs

Fix flaky test test_permissions_net_listen_allow_localhost

---

cli/tests/integration_tests.rs

disable test_raw_tty

---

cli/js/deno.ts
cli/js/dispatch_minimal_test.ts
cli/js/files.ts
cli/js/net.ts
cli/js/ops/io.ts
cli/js/ops/permissions.ts
cli/js/ops/plugins.ts
cli/js/ops/process.ts
cli/js/ops/signal.ts
cli/js/ops/timers.ts
cli/js/ops/web_worker.ts
cli/js/ops/worker_host.ts
cli/js/permissions.ts
cli/js/plugins.ts
cli/js/process.ts
cli/js/runtime_worker.ts
cli/js/signals.ts
cli/js/timers.ts
cli/js/web/fetch.ts
cli/js/workers.ts

reorg: move JS ops implementations to cli/js/ops/, part 2

---

Cargo.lock
cli/Cargo.toml

upgrade: dprint 0.8.0

---

cli/js/ops/dispatch_json.ts
cli/js/ops/dispatch_minimal.ts

This PR addresses GC problems with `deno_tcp.ts`
Benchmark:
```
$ deno --allow-net tools/deno_tcp.ts
$ wrk -d 10 --latency http://127.0.0.1:4500
```
this PR
```
Running 10s test @ http://127.0.0.1:4500
Latency   135.29us   41.03us   3.14ms   97.11%
Req/Sec    36.23k     1.34k   37.46k    96.53%
50%  131.00us
75%  133.00us
90%  137.00us
99%  287.00us
727913 requests in 10.10s, 35.40MB read
Requests/sec:  72072.56
Transfer/sec:      3.51MB
```
`master`
```
Running 10s test @ http://127.0.0.1:4500
Latency   197.70us  398.18us   5.68ms   96.89%
Req/Sec    34.59k     2.38k   38.25k    85.15%
50% …
```

perf: use Object instead of Map for promise table

---

cli/fmt.rs

Improve dprint config

---

cli/js/runtime.ts
cli/js/runtime_main.ts
cli/js/runtime_worker.ts

reorg: globals initialization

---

cli/tests/std_tests.rs

Enable std tests in debug mode

---

.github/workflows/ci.yml
cli/ops/permissions.rs

upgrade: Rust 1.42.0

---

.github/workflows/ci.yml

ci: Use Azure blob storage for sccache 

---

std/node/_fs/_fs_appendFile.ts
std/node/_fs/_fs_chmod.ts
std/node/_fs/_fs_chmod_test.ts
std/node/_fs/_fs_constants.ts
std/node/fs.ts

This PR:
* Adds chmod Node polyfill
* Begins building fs constants

feature: add chmod Node polyfill and related file system constants

---

Cargo.lock
core/Cargo.toml

Upgrade to rusty_v8 0.3.5 / v8 8.2.308

---

std/encoding/csv_test.ts
std/examples/catj.ts
std/examples/chat/server_test.ts
std/examples/tests/xeval_test.ts
std/fs/walk_test.ts
std/http/server_test.ts
std/node/_fs/_fs_chmod_test.ts
std/node/_fs/_fs_chown_test.ts
std/node/fs_test.ts
std/textproto/reader_test.ts

refactor(std): Uncomment disabled tests, use skip option

---

cli/http_util.rs
cli/ops/io.rs

refactor: remove an unsafe and some boxing

---

cli/js/tests/unit_test_runner.ts
cli/tests/integration_tests.rs

try to handle ConnectionReset error in windows CI for unit tests

---

.github/workflows/ci.yml
Cargo.lock
cli/Cargo.toml
core/Cargo.toml
std/manual.md

Upgrade to rusty_v8 0.3.7 and use binary builds

---

.github/workflows/ci.yml

Removed in https://github.com/denoland/deno/commit/0ef99ac970729dac0de8ccb78eed8c1c74fcd350

Fix benchmarks

---

.github/workflows/ci.yml
cli/js/tests/os_test.ts

Now that we have a binary V8... maybe it's faster to not use sccache at all

test removing sccache

---

cli/js/tests/test_util.ts
cli/js/tests/unit_test_runner.ts

Fix unit test runner ConnectionReset bug

---

cli/js/lib.deno.ns.d.ts

Next up for more user friendly API documentation:  chmod

Chmod API documentation improvements

---

cli/tests/integration_tests.rs

Fix cafile_install_remote_module

---

cli/tests/integration_tests.rs

Clean up installer tests

---

std/http/io.ts
std/http/server_test.ts
std/testing/asserts.ts

fix(std/http): Fix respond error test on Windows

---

std/http/server_test.ts

This should prevent rare error: https://github.com/denoland/deno/runs/520656981.
@bartlomieju Please check that the test is still valid.

fix(std/http): Properly await ops in a server test

---

std/http/server.ts

refactor(std/http/server): Remove bad error handling

---

.github/workflows/ci.yml
cli/tests/integration_tests.rs
core/examples/http_bench.rs
std/manual.md
tools/benchmark.py
tools/target_test.py
tools/util.py

Also remove outdated docs related to ninja/gn.

Remove DENO_BUILD_MODE and DENO_BUILD_PATH

---

.github/workflows/ci.yml
.gitignore

Optimize github cache usage, remove sccache

---

cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.shared_globals.d.ts

These have no function and are not tested, probably incorrect in many
situations.

Remove @url comments from d.ts files

---

std/examples/tests/curl_test.ts

fix(std/examples/curl): re-enable a test

---

.github/workflows/ci.yml

ci: releases should all use zip and standard target triples

---

cli/js/lib.deno.ns.d.ts

API documentation improvements number 3. This PR includes documentation updates to the following APIs:
* chown()
* close()
* compile()
* connect()

doc: API improvements to chown, close, compile and connect

---

.cargo/config
.github/workflows/ci.yml
.gitignore

Ref https://github.com/denoland/deno/issues/4468

Statically link the C runtime library on Windows

---

cli/js/tests/fs_events_test.ts
cli/op_error.rs

Closes #4485
Add cast code. Add a basic error test.

errors: add fsEvent notify::Error casts

---

Cargo.lock
cli/Cargo.toml
cli/fmt.rs

upgrade: dprint 0.9.4

---

.github/workflows/ci.yml
Cargo.lock
core/Cargo.toml
std/manual.md

upgrade: rusty_v8 to v0.3.9

---

cli/tests/integration_tests.rs

Ignore flaky test cafile_info

---

tools/http_benchmark.py
tools/http_server.py

Add check to fail the benchmark test on server error

---

cli/js/tests/blob_test.ts
cli/js/web/blob.ts

Fix invalid blob type

---

.github/workflows/ci.yml

deno_install scripts were updated in
https://github.com/denoland/deno_install/commit/b635b525846d28d09fba1f6e88cccf1b5e66d499

Remove old release files

---

cli/flags.rs

fix(#4554): use --inspect in repl & eval

---

std/http/cookie.ts
std/http/cookie_test.ts

fix(#4550): setCookie should append cookies

---

cli/js/lib.deno.ns.d.ts
cli/js/ops/io.ts

Minor API changes to improve name of parameters.

refactor: better named parameters

---

Cargo.lock
core/Cargo.toml

upgrade: v0.3.10

---

cli/js/web/workers.ts

Closes https://github.com/denoland/deno/issues/4586

make Worker.poll private

---

cli/disk_cache.rs

This PR contains:
- DiskCache::new() checks if given location exists if not creates it 
- Unit Tests
Attending #4616

Check if location is dir at disk_cache.rs

---

std/testing/format.ts
std/testing/format_test.ts

std/testing/format: bigint

---

std/http/server.ts
std/http/server_test.ts

In the server this time. cc @ry
ref #4551 #4593

feat(std/http/server): Respond with 400 on request parse failure (2)

---

cli/flags.rs
cli/lib.rs
cli/tests/045_proxy_test.ts
cli/tests/integration_tests.rs
cli/tests/lock_write_fetch.ts
std/manual.md

Rename deno fetch subcommand to deno cache

---

cli/js/lib.deno.shared_globals.d.ts

Remove __textEncoding and __performanceUtil namespaces

---

cli/js/lib.deno.shared_globals.d.ts

Remove __io namespace

---

cli/js/lib.deno.shared_globals.d.ts

Remove extra copy of URLSearchParams

---

cli/js/lib.deno.shared_globals.d.ts

Remove __blob and __console namespaces

---

Cargo.lock
cli/Cargo.toml
cli/signal.rs
core/Cargo.toml
deno_typescript/Cargo.toml
tools/hyper_hello/Cargo.toml

upgrade: rust crates

---

cli/js/lib.deno.shared_globals.d.ts
cli/js/tests/event_target_test.ts

Remove __event, __eventTarget, __customEvent namespaces

---

std/node/_fs/_fs_mkdir.ts

Fix build - 2becae broke CI

---

std/signal/test.ts

See https://github.com/denoland/deno/pull/4696#discussion_r406776356.
The diff is difficult to read, but there are only 2 small changes here:
* Removed `if (Deno.build.os !== "win") {` and used `ignore: Deno.build.os === "win",` in each test instead
* Remove `await delay(10);` from the end of the two tests

test: remove unnecessary delay and use standard ignore

---

cli/installer.rs

`deno install` currently sets the provided permission and cert flags on the installed script. It would be nice to be able to set the log level on installed scripts too.

cli install write quiet and log level flags to installed script

---

cli/js/lib.deno.ns.d.ts

docs: highlight NO_COLOR

---

cli/js/lib.deno.ns.d.ts

Convert ProcessStatus to a tagged union

---

cli/js/lib.deno.shared_globals.d.ts
cli/js/lib.deno.worker.d.ts
cli/js/web/workers.ts

Ref #4708, instead of one big PR, I'm gonna split it into bite-sized chunks

workers: update postMessage and location types

---

cli/js/lib.deno.worker.d.ts
cli/js/runtime_worker.ts
cli/tests/subdir/event_worker_scope.js
cli/tests/workers_test.out
cli/tests/workers_test.ts

Closes https://github.com/denoland/deno/issues/4344

feat: implement EventTarget for worker scope

---

cli/js/globals.ts
cli/js/tests/form_data_test.ts
cli/js/web/blob.ts
cli/js/web/body.ts
cli/js/web/dom_file.ts
cli/js/web/dom_types.d.ts
cli/js/web/fetch.ts
cli/js/web/form_data.ts

dedup FormData

---

cli/js/errors.ts
cli/js/lib.deno.ns.d.ts
cli/js/tests/read_file_test.ts
cli/op_error.rs
cli/ops/dispatch_minimal.rs
cli/ops/fs.rs
cli/ops/io.rs
cli/ops/process.rs
cli/ops/tty.rs
cli/state.rs
core/ops.rs

Fixes #4717 (need to verify / add test)

Make writeSync, readSync, seekSync, openSync, isatty proper synchronous syscalls

---

cli/ops/net.rs
cli/ops/tls.rs

remove futures::executor::block_on in net interfaces

---

std/io/bufio.ts
std/io/bufio_test.ts
std/io/util.ts

This PR:
* Introduces a new synchronous buffered writer
* Refactors the asynchronous buffered writer to have more meaningful variable names (no functional changes)
* Adds JSDoc to `copyBytes`

feature: synchronous buffered writer

---

cli/js/deno.ts
cli/js/lib.deno.ns.d.ts
cli/js/ops/tls.ts
cli/js/tests/tls_test.ts
cli/js/tls.ts
cli/ops/io.rs
cli/ops/net.rs
cli/ops/tls.rs
core/resources.rs

add startTLS

---

cli/js/lib.deno.ns.d.ts

fix(doc): Group ID

---

std/node/_fs/_fs_exists_test.ts

fix(std): existsFile test

---

cli/ops/dispatch_json.rs
cli/ops/dispatch_minimal.rs
cli/state.rs
core/es_isolate.rs
core/examples/http_bench.rs
core/isolate.rs
core/ops.rs
core/plugins.rs
deno_typescript/lib.rs
deno_typescript/ops.rs
test_plugin/src/lib.rs

Fix Op definitions

---

Cargo.lock
cli/Cargo.toml
cli/fmt.rs

The API has changed in preparation for parallelization (swc sets some global state that should be shared across formats when parallelizing).
Edit: Apologies for the multiple CI failures.... long day :)

upgrade: dprint 0.13.0

---

cli/tests/error_022_stack_custom_error.ts
core/js_errors.rs

fix(core/js_errors): Get error's name and message from JS fields

---

std/node/README.md
std/node/module.ts
std/node/module_test.ts

The underscore is no longer required.

std/node: require_ -> require

---

cli/js/lib.deno.ns.d.ts

Add comment distinguishing Deno.Buffer from Node's Buffer

---

cli/js/lib.deno.ns.d.ts

Add comments in Reader/SyncReader about iter/iterSync

---

.github/workflows/ci.yml
Cargo.lock
cli/js.rs
cli/startup_data.rs
core/Cargo.toml
core/bindings.rs
core/es_isolate.rs
core/isolate.rs
core/shared_queue.rs

Upgrade to rusty_v8 v0.4.0

---

.github/workflows/ci.yml
cli/doc/tests.rs

upgrade: Rust 1.43.0

---

cli/fmt.rs

fix clippy

---

std/bytes/README.md

create doc [std/bytes]

---

cli/js/deno.ts
cli/js/lib.deno.ns.d.ts
cli/js/ops/fs_events.ts
cli/js/tests/fs_events_test.ts
std/manual.md

BREAKING CHANGE: rename Deno.fsEvents() to Deno.watchFs()

---

cli/js/io.ts
cli/js/lib.deno.ns.d.ts
cli/js/tests/files_test.ts

stabilize Deno.iter() and Deno.iterSync()

---

cli/js/testing.ts

feat: add help messages to test sanitizers

---

cli/js/files.ts
cli/js/lib.deno.ns.d.ts
cli/js/web/console.ts

change type of stdio handles in JS api

---

cli/js/lib.deno.ns.d.ts
cli/js/tests/dir_test.ts
cli/ops/fs.rs

chdir should require --allow-write

---

cli/js/lib.deno.ns.d.ts

BREAKING CHANGE: change return type of Deno.resources()

---

core/bindings.rs
core/es_isolate.rs
core/modules.rs

add id field to RecursiveModuleLoad

---

std/io/ioutil.ts
std/io/ioutil_test.ts
std/io/readers_test.ts
std/io/writers_test.ts
std/mime/multipart.ts

reorder copyN arguments to match Deno.copy

---

std/node/_fs/_fs_mkdir.ts
std/node/_fs/_fs_mkdir_test.ts

fix [this problem](https://github.com/denoland/deno/blob/128dce0d8a2ae062d0d85918da841a6f6aa2198a/std/node/_fs/_fs_mkdir.ts#L23)
and add tests for `node/_fs_mkdir.ts`

add tests for node/fs/mkdir

---

std/util/sha1.ts
std/util/sha1_test.ts
std/uuid/_common.ts
std/uuid/mod.ts
std/uuid/test.ts
std/uuid/tests/v5/generate.ts
std/uuid/tests/v5/validate.ts
std/uuid/v5.ts
std/ws/mod.ts

feat(std/uuid): Implement uuid v5

---

cli/js/tests/console_test.ts
cli/js/web/console.ts

refactor: decouple Console implementation from stdout

---

cli/doc/class.rs
cli/doc/interface.rs
cli/doc/module.rs
cli/doc/namespace.rs
cli/doc/parser.rs
cli/lib.rs
cli/swc_util.rs

Prerequisite for #4744
Prerequisite for #4781

refactor: factor out AstParser from DocParser

---

cli/ops/runtime_compiler.rs
cli/tests/integration_tests.rs

Make runtime compile ops unstable

---

cli/js/lib.deno.ns.d.ts
cli/ops/os.rs

Make Deno.dir unstable

---

cli/ops/tty.rs

Make Deno.setRaw and Deno.isatty unstable

---

cli/tests/integration_tests.rs
core/es_isolate.rs

fix(core): fix top-level-await error handling

---

cli/ops/signal.rs

signal APIs should require --unstable

---

std/http/io.ts
std/http/io_test.ts

Improve std/http/io.ts parseHTTPVersion

---

cli/js/lib.deno.ns.d.ts
cli/ops/net.rs

Make unix sockets require allow-write

---

cli/ops/fs.rs

make utime unstable

---

cli/ops/tls.rs

mark Deno.startTls as unstable

---

cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.shared_globals.d.ts
cli/js/web/console.ts

refactor: change InspectOptions, make Deno.inspect stable

---

Cargo.lock
cli/Cargo.toml
cli/fmt.rs

Fix stdin not formatting JSX

---

cli/js/deno.ts
cli/js/lib.deno.ns.d.ts
cli/js/ops/fs/read_dir.ts
cli/js/ops/fs/read_link.ts
cli/js/ops/fs/real_path.ts
cli/js/tests/read_dir_test.ts
cli/js/tests/read_link_test.ts
cli/js/tests/real_path_test.ts
cli/js/tests/test_util.ts
cli/js/tests/unit_tests.ts
std/fs/copy.ts
std/fs/empty_dir.ts
std/fs/walk.ts
std/http/file_server.ts
std/node/_fs/_fs_dir.ts
std/node/_fs/_fs_readlink.ts
std/node/module.ts

make camel case readDir, readLink, realPath

---

std/node/_fs/_fs_chmod.ts
std/node/_fs/_fs_copy.ts
std/node/_fs/_fs_mkdir.ts

Minor cleanup on some `node/fs` functions.

Cleanup std/node/fs functions

---

core/module_specifier.rs

This is a cleaner version of #4983

adding missing test cases for <unknown> base

---

std/examples/chat/server.ts
std/examples/chat/server_test.ts
std/fs/expand_glob_test.ts

after #4993 landed,
closes #4647,closes #4108
> a cleaner version of #4648 ( was my mistake to merge request from master branch )

fix fromFileUrl use cases

---

std/manual.md

fix: manual(related #4885)

---

std/node/README.md
std/node/process.ts

std/node: make process global

---

cli/doc/class.rs
cli/doc/interface.rs
cli/doc/tests.rs
cli/doc/ts_type.rs
cli/doc/variable.rs

fix(doc): better repr for object literal types

---

std/fs/README.md

-  put the **writeJson** function under the **readJson** function（Make them closer）
- The return value type of the **readFileStr** function is string

fix: fs mod README.md 

---

std/style_guide.md

small typo fix

---

std/http/file_server.ts
std/http/io.ts
std/http/io_test.ts

fix(std/http): avoid directly modifying the headers object

---

std/fs/walk.ts

Fix Deno.walk example

---

cli/fmt_errors.rs
cli/tests/error_025_tab_indent
cli/tests/error_025_tab_indent.out
cli/tests/integration_tests.rs
core/js_errors.rs

fix misaligned error reporting on tab char

---

cli/js/web/decode_utf8.ts

Fixes https://github.com/denoland/deno/issues/5028
cc @qwerasd205

Correct copyright in cli/js/web/decode_utf8.ts

---

cli/js/lib.deno.ns.d.ts
cli/js/tests/dir_test.ts
cli/ops/fs.rs

Deno.chdir should require allow-read not allow-write

---

std/examples/gist.ts

Add hint on how to install gist program

---

cli/fmt_errors.rs

```
NO_COLOR=1 deno eval "throw new Error()"
```
currently has colourful stack frames.

fix(cli/fmt_errors): Respect NO_COLOR for stack frames

---

std/util/sha1.ts

Just was looking at a std module and made a quick update to align it to current best practices.

Move std/util/sha1.ts to ES private fields

---

cli/js/tests/console_test.ts
cli/js/web/console_table.ts

fix: formatting misalignment on console.table

---

cli/global_state.rs
cli/ops/worker_host.rs
cli/permissions.rs
cli/state.rs

Rename DenoPermissions, add abs path asserts

---

cli/js/deno.ts
cli/js/deno_unstable.ts
cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.unstable.d.ts
cli/js/tests/dir_test.ts
cli/ops/fs.rs
cli/tests/integration_tests.rs
std/http/file_server_test.ts

stabilize Deno.cwd and require --allow-read

---

Cargo.lock
Releases.md
cli/Cargo.toml
core/Cargo.toml
deno_typescript/Cargo.toml

v1.0.0-rc1

---

std/manual.md

fix: manual(related #5026)

---

cli/js/lib.deno.ns.d.ts

Simplify ProcessStdio

---

cli/tests/inspector2.js
cli/tests/integration_tests.rs

Clean up 'inspector_break_on_first_line' test and fix its flakiness

---

Cargo.lock
cli/Cargo.toml
core/Cargo.toml
deno_typescript/Cargo.toml
tools/hyper_hello/Cargo.toml

Upgrade crates

---

cli/js/compiler.ts

This is just preparation for rewriting `processImports()` in Rust - I really needed to untangle it a bit and understand the logic.
@kitsonk PTAL

refactor(ts): make processImports logic more verbose

---

cli/js/lib.deno.ns.d.ts
cli/js/tests/os_test.ts
cli/ops/os.rs
cli/tests/integration_tests.rs
tools/target_test.py

BREAKING: execPath should require allow-read

---

.github/workflows/ci.yml
Cargo.lock
cli/inspector.rs
core/Cargo.toml

Upgrade to rusty_v8 0.4.2 / V8 8.4.300

---

std/node/_fs/_fs_writeFile_test.ts
std/node/_fs/promises/_fs_writeFile_test.ts

I don't care about testing not implemented failures

Remove flaky and useless tests

---

cli/file_fetcher.rs
cli/state.rs
cli/tests/integration_tests.rs
cli/tests/unsupported_dynamic_import_scheme.out

Closes #5048
This is a temporary fix; more holistic solution is related to #4781

fix(imports): fix panic on unsupported scheme

---

cli/flags.rs

feat(bundle): add --config flag

---

cli/repl.rs

Remove REPL/Windows hack

---

docs/getting_started/first_steps.md

doc: fix typo on first_steps.md

---

.github/workflows/ci.yml

Don't publish cli when tag name starts with 'std/'

---

docs/getting_started/first_steps.md
docs/getting_started/typescript.md

doc: fix typos in docs/getting_started/*.md

---

docs/contributing.md

Link to code of conduct

---

cli/js/repl.ts
cli/tests/integration_tests.rs

Add hint on how to exit REPL

---

cli/js/deno.ts
cli/js/deno_unstable.ts
cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.unstable.d.ts
cli/ops/os.rs

BREAKING: make Deno.hostname unstable

---

cli/installer.rs

fix(cli/installer): Fix concurrent env handling in tests

---

std/node/README.md

doc: fix typo in std/node/README.md

---

tools/benchmark.py

fix: worker benchmarks

---

docs/getting_started/first_steps.md

fix typoes: get rid of a redandunt `from`

---

README.md

Fix style guide link

---

cli/tsc.rs

This commit changes handling of source maps by settings proper
file URLs for "file" and "sources" fields in the source map.

fix: source maps in inspector for local files

---

docs/runtime/workers.md

doc: fix typo in workers.md

---

docs/runtime/compiler_apis.md

docs: Added unstable message to compiler api docs

---

docs/examples/os_signals.md

Sample TypeScript codes in https://deno.land/manual/examples/os_signals is not highlighted by this.

doc: specify language of code block

---

docs/tools/debugger.md

Small typo fix to one of the doc file.

Fix small typo in the docs

---

std/http/file_server_test.ts

Fix flakiness in std file_server tests

---

docs/getting_started/first_steps.md

Remove extra dollar sign

---

docs/getting_started/setup_your_environment.md

Fixes a minor grammatical error in the docs

Fix grammar

---

docs/examples/os_signals.md

Fix small typo in docs example: OS Signals.

Fix typo in docs example OS Signals

---

std/ws/README.md

It's just a small change in the example.

Save a few lines

---

std/fmt/TODO

Related issue: #5440
Fixed few typos in std fmt TODO

Fixed Typo std fmt TODO

---

std/hash/_fnv/fnv32.ts
std/hash/_fnv/fnv64.ts
std/hash/_fnv/util.ts
std/hash/_fnv/util_test.ts
std/hash/fnv.ts
std/hash/fnv_test.ts

This PR implements fnv32/fnv32a/fnv64/fnv64a hash algorithms

Add fnv hash

---

docs/contributing.md

Add link to JSDoc website

---

cli/ops/fs.rs
cli/swc_util.rs

fix some clippy warning

---

std/fmt/README.md

Fix typo in fmt docs

---

std/examples/chat/index.html

Just wanted to change this so it is less cumbersome to have multiple tabs open with the chat example.

chore: Add an 'Enter' event handler for the chat example

---

docs/introduction.md

Hey, started learning about Deno by reading manual.
This is my first tiny contribution :)
Awesome stuff! Thanks for innovating.

Fix JavaScript spelling;

---

Releases.md
cli/js/lib.deno.shared_globals.d.ts
cli/js/lib.deno.unstable.d.ts
cli/tsc.rs
std/fmt/TODO
std/node/events_test.ts

After all, it's really fashionable nowadays.

Fix a bunch of spelling errors

---

std/fs/ensure_dir.ts

Fix spelling mistake on permission

---

std/fs/empty_dir_test.ts

Fixed Typo

---

core/README.md
std/fs/copy.ts
std/fs/empty_dir.ts
std/fs/ensure_dir.ts
std/fs/ensure_file.ts

Fix spelling mistakes

---

cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.shared_globals.d.ts
cli/js/lib.deno.unstable.d.ts

Fix examples formatting in declaration file

---

core/module_specifier.rs

Simplify fmt::Display for ModuleResolutionError

---

cli/flags.rs
cli/js/lib.deno.ns.d.ts
cli/js/lib.deno.unstable.d.ts
core/isolate.rs
docs/getting_started/setup_your_environment.md
docs/runtime/program_lifecycle.md
std/fmt/README.md
std/fs/README.md
std/fs/empty_dir.ts
std/http/cookie.ts
std/io/ioutil.ts
std/manual.md
std/path/README.md

#5291, #5292, #5456, #5494, #5496, #5499, #5517, #5519, #5523, #5526, #5541

Roll-up of proposed spelling & cosmetic fixes

---

docs/linking_to_external_code.md
docs/linking_to_external_code/import_maps.md
docs/linking_to_external_code/proxies.md
docs/linking_to_external_code/reloading_modules.md
docs/runtime/compiler_apis.md
docs/runtime/program_lifecycle.md
docs/runtime/stability.md
docs/runtime/workers.md

General edits to the Runtime and Linking to External Code sections.

Update Runtime and Linking sections of the Manual

---

cli/js/lib.deno.ns.d.ts

Mark Deno.pid and Deno.noColor as const

---

docs/contributing/development_tools.md

docs: fix url data.json

---

cli/doc/printer.rs
cli/doc/tests.rs

Fixes https://github.com/denoland/deno/issues/5614

fix(doc): crash on formatting type predicate
