- std/node/_fs/_fs_readFile.ts
- std/node/_fs/promises/_fs_readFile.ts
- std/node/_fs/promises/_fs_readFile_test.ts
- std/node/_fs/promises/mod.ts
> feat(std/node) - Add fs.promises.readFile

- std/io/bufio_test.ts
> fix: compilation error introduced by #4543

- std/node/_fs/_fs_writeFile_test.ts
> std/node: Remove duplicated test

- std/fmt/README.md
- std/fmt/mod.ts
- std/fmt/printf.ts
- std/fmt/printf_test.ts
Plus miscellaneous  clean ups in the module itself.
> Move std/fmt/sprintf.ts to std/fmt/printf.ts

- cli/module_graph.rs
- cli/state.rs
- cli/tests/disallow_http_from_https.js
- cli/tests/disallow_http_from_https.ts
- cli/tests/disallow_http_from_https_js.out
- cli/tests/disallow_http_from_https_ts.out
- cli/tests/error_local_static_import_from_remote.js.out
- cli/tests/error_local_static_import_from_remote.ts.out
- cli/tests/integration_tests.rs
> fix: disallow http imports for modules loaded over https

- cli/flags.rs
- cli/main.rs
- cli/tests/integration_tests.rs
merging this into v1.1 branch instead of master
fixes https://github.com/denoland/deno/issues/3696
> feat: deno eval -p

- docs/tools/dependency_inspector.md
> docs: add entry for 'deno info'

- std/http/file_server.ts
- std/http/file_server_test.ts
> fix(std/http): file_server's target directory

- cli/state.rs
- cli/tests/inspector4.js
- cli/tests/integration_tests.rs
Closes https://github.com/denoland/deno/issues/5664
> fix: --inspect flag working like --inspect-brk

- cli/js/web/text_encoding.ts
> atob throw DOMException

- Releases.md
this PR remove this link when you click in this link appears error 404.
> remove Link in Releases.md

- cli/js/web/streams/internals.ts
Simplify `isFiniteNonNegativeNumber` by using `Number.isFinite`
> stream: simplify isFiniteNonNegativeNumber

- docs/examples/permissions.md
> docs: update permissions example

- std/encoding/base64.ts
- std/encoding/base64_test.ts
This PR adds base64 encoding APIs.
These APIs are actually wrappers for `window.btoa` and `window.atob` that will help users to work with binary data.
> feat(std/encoding): add base64

- cli/js/web/body.ts
- cli/js/web/fetch.ts
- cli/js/web/util.ts
Move duplicated functions to `utils.ts`
> refactor: Move getHeaderValueParams & hasHeaderValueOf to utils.ts

- cli/js/web/fetch.ts
- cli/tests/unit/fetch_test.ts
> fix(web/fetch) - Allow ArrayBuffer as fetch request body

- docs/getting_started/setup_your_environment.md
- docs/tools/debugger.md
JetBrains just released a Deno plugin that can be used with their IDEs as per [this comment](https://youtrack.jetbrains.com/issue/WEB-41607#focus=streamItem-27-4160152.0-0)
> [Manual] Add JetBrains environment support

- docs/runtime.md
- docs/runtime/program_lifecycle.md
- docs/runtime/stability.md
- docs/runtime/workers.md
This PR updates the "Runtime" section of the manual with numerous small improvements.
> doc: various runtime doc updates

- docs/getting_started/setup_your_environment.md
https://github.com/denoland/vscode_deno/issues/4#issuecomment-634104345
> doc: official denoland extension

- Cargo.lock
- cli/Cargo.toml
Closes https://github.com/denoland/deno/issues/5848
**merge on approval**
> upgrade: dprint to 0.19.0

- std/http/server.ts
Improve documentation on the back of issue #5763
> doc: improve documentation for consuming request body

- docs/getting_started/setup_your_environment.md
> Add instructions for using Deno with Emacs

- std/log/handlers_test.ts
> fix(std): Fix FileHandler test with mode 'x' on non-English systems

- std/testing/README.md
- std/testing/bench.ts
- std/testing/bench_example.ts
- std/testing/bench_test.ts
> Return results in benchmark promise

- cli/inspector.rs
- cli/main.rs
- cli/ops/dispatch_json.rs
- cli/ops/dispatch_minimal.rs
- cli/ops/fetch.rs
- cli/ops/fs.rs
- cli/ops/fs_events.rs
- cli/ops/io.rs
- cli/ops/net.rs
- cli/ops/net_unix.rs
- cli/ops/plugin.rs
- cli/ops/process.rs
- cli/ops/repl.rs
- cli/ops/resources.rs
- cli/ops/signal.rs
- cli/ops/tls.rs
- cli/ops/tty.rs
- cli/ops/web_worker.rs
- cli/ops/worker_host.rs
- cli/state.rs
- cli/web_worker.rs
- cli/worker.rs
- core/bindings.rs
- core/core_isolate.rs
- core/es_isolate.rs
- core/examples/http_bench.rs
- core/lib.rs
- core/modules.rs
- core/ops.rs
- deno_typescript/lib.rs
rebased from https://github.com/denoland/deno/pull/5716
> refactor: Split isolate and state using safe get_slot()

- std/uuid/README.md
> Fixing Standard Lib UUID Readme: #5947

- Cargo.lock
- cli/Cargo.toml
- cli/ops/fs.rs
- core/Cargo.toml
- deno_typescript/Cargo.toml
- test_plugin/Cargo.toml
- tools/hyper_hello/Cargo.toml
> upgrade: crates

- cli/js/lib.deno.shared_globals.d.ts
Add docs for
* add/remove EventListener
* dispatchEvent
* atob, btoa
* set/clear Interval/Timeout
* fetch
* queueMicrotask
> doc: add/update jsdoc for global functions

- cli/swc_util.rs
- cli/tests/es_private_fields.js
- cli/tests/es_private_fields.js.out
- cli/tests/integration_tests.rs
This problem was introduced in #5817; I mistakenly
set config for private fields to false. 
Fixed and added a test case.
Fixes https://github.com/denoland/deno/issues/5960
> fix: ES private fields parsing in SWC

- cli/ops/fs.rs
- cli/tests/unit/remove_test.ts
> fix(#4850): Deno.remove() fails to remove unix socket

- std/http/http_status.ts
As per [RFC 8470 5.2](https://tools.ietf.org/html/rfc8470#section-5.2)
> feat(std/http): add TooEarly status code

- cli/file_fetcher.rs
- cli/tests/cjs_imports.ts
- cli/tests/cjs_imports.ts.out
- cli/tests/commonjs.cjs
- cli/tests/integration_tests.rs
Fixes https://github.com/denoland/deno/issues/5878
> fix: media type for .cjs and application/node

- std/encoding/csv_test.ts
This PR follows up to #4520 and #4543.
> chore(std/encoding/csv): enable the "HugeLines" test case

- cli/js/lib.deno.ns.d.ts
> fix Deno.iterSync() Deno.write() Deno.writeSync() jsDoc

- cli/main.rs
> add human size function in cli/main.rs

- cli/main.rs
- cli/worker.rs
> clean up create_main_worker

- cli/source_maps.rs
- cli/startup_data.rs
> Remove unused check-only feature

- cli/tests/integration_tests.rs
- core/bindings.rs
> Fix REPL BorrowMutError panic

- std/testing/asserts.ts
- std/testing/asserts_test.ts
> fix(std/testing/asserts): Format values in assertArrayContains()

- std/testing/README.md
- std/testing/bench_test.ts
> doc: benchmarking

- std/testing/bench.ts
- std/testing/bench_test.ts
> Fix clock assertions without --allow-hrtime

- Cargo.lock
- cli/Cargo.toml
> upgrade: swc_ecma_parser 0.24.5

- cli/fmt.rs
- cli/main.rs
- cli/tests/bundle.test.out
This reverts commit 93cf3bd5341d5985201ea0905280082d5a3310f9.
Alternative to https://github.com/denoland/deno/pull/6063
cc @kt3k
> Revert "feat: format deno bundle output (#5139)"

- docs/tools/documentation_generator.md
For Issue #5338 
This PR adds initial use documentation for the documentation generator, but more is on the way.
> Create initial doc generator documentation

- .github/workflows/ci.yml
- cli/swc_util.rs
- cli/tests/integration_tests.rs
- cli/tsc.rs
> ci: upgrade to Rust 1.44.0, use actions/cache@v2

- cli/installer.rs
- cli/upgrade.rs
$HOME is meaningless on Windows. It may be set by users or by third
party software, but it is non-standard and should not be relied upon.
Likewise, $USERPROFILE is meaningless on other platforms.
Fixes: #6109
> Fix windows issues with 'deno upgrade' and home dir detection

- cli/flags.rs
- cli/fmt.rs
- cli/test_runner.rs
- docs/testing.md
Also fmt
Related PR
https://github.com/denoland/deno/pull/6122
> added mjs files for default fmt

- std/io/README.md
**This is sample document for io module. Just to guide developer that it exist.**
> added documentation with sample for std/io mod

- Cargo.lock
- cli/Cargo.toml
- cli/colors.rs
- cli/diff.rs
- cli/flags.rs
- cli/fmt.rs
- cli/main.rs
- cli/tests/integration_tests.rs
These patches have already been reviewed - this is just for rebasing them into master
> v1.1 rebased

- std/examples/tests/xeval_test.ts
- std/io/bufio_test.ts
- std/io/ioutil_test.ts
- std/io/readers.ts
- std/io/util.ts
- std/textproto/test.ts
> Fix StringReader implementation

- std/hash/README.md
Added basic document for hash module with sample example
Added mod.ts to easy access to all hash classes.
> added documentation with sample for std/hash mod, added mod.ts

- docs/getting_started/setup_your_environment.md
> [DOCS] vim/neovim settings for editors and ide's support

- std/http/cookie.ts
- std/http/cookie_test.ts
> rename delCookie to deleteCookie

- docs/getting_started.md
- docs/getting_started/command_line_interface.md
- docs/getting_started/installation.md
- docs/toc.json
Closes #5450, ref https://github.com/denoland/deno/issues/5450#issuecomment-630788747. There is already a page on permissions.
> doc: Add a CLI section

- std/http/server_test.ts
Test from https://github.com/denoland/deno/pull/6155 is a bit flaky on Windows.
It seems there's a race condition with the TLS server from this test:
https://github.com/denoland/deno/blob/0bf952bb49e79ad2bab312a4d4daa3dd51344597/std/http/server_test.ts#L397-L409
Replaced with a server in a different port and it's working fine (installed Windows 10 on a VM to test)
> fix(http/server): flaky test on Windows

- docs/examples/unix_cat.md
Changed the example to be consistent with the rest of the document.
First PR here, not sure if I have to create a new issue for this as there is no code change with any impact.
> Update example from let to const

- std/testing/README.md
- std/testing/bench.ts
- std/testing/bench_test.ts
> Make bench progress callback async

- CODE_OF_CONDUCT.md
- tools/format.py
Closes #6205.
@bartlomieju Should the formatted CoC be part of this PR?
> Fix prettier formatting

- docs/examples/file_server.md
- docs/getting_started/permissions.md
- docs/standard_library.md
- docs/tools/script_installer.md
> fixed double prompt in manual

- docs/linking_to_external_code/import_maps.md
> Updated command to fix typo

- std/node/README.md
> Doc: Node buffer is now supported

- std/node/buffer_test.ts
Buffer from std/node does not have tests. I got some bandwidth and added tests to the static methods.
I am also working on the other methods but I thought it was worth a PR as I am not sure I will have some time this weekend to complete them.
> added tests for static methods of Buffer class

- cli/file_fetcher.rs
- cli/flags.rs
- cli/global_state.rs
- cli/permissions.rs
- docs/contributing/style_guide.md
- docs/getting_started/command_line_interface.md
- docs/getting_started/permissions.md
Closes #6281 
Also added link to Chromiums' `Inclusive code` guide to the style guide.
> Move to allowlist and blocklist

- cli/global_state.rs
- cli/tests/integration_tests.rs
- cli/tests/jsx_import_from_ts.App.jsx
- cli/tests/jsx_import_from_ts.ts
- cli/tests/jsx_import_from_ts.ts.out
Ref https://github.com/denoland/deno/issues/6057#issuecomment-643634290
Closes #6057 (again)
> fix(compiler): JSX compilation and provide better error message

- std/async/mux_async_iterator.ts
- std/async/mux_async_iterator_test.ts
> MuxAsyncIterator throws muxed errors

- docs/getting_started/setup_your_environment.md
> minor grammar fix

- docs/getting_started/setup_your_environment.md
added autocompletion example for zsh as recommended here: 
https://github.com/denoland/deno/issues/3310#issuecomment-643736682
> DOCS: added autocompletion example for zsh

- cli/flags.rs
> Fix DENO_DIR docs

- cli/file_fetcher.rs
Closes https://github.com/denoland/deno/issues/5062
> fix(cache): apply redirection limit for cached files

- cli/fmt.rs
- cli/tests/fmt_check_tests_dir.out
- cli/tests/integration_tests.rs
> chore: move fmt test to integration tests

- docs/testing/assertions.md
- docs/toc.json
Adds Assertions documentation to a new Testing section of the documentation.
This is a first stab at the assertions documentation, which hopes to provide developers with a basic overview of the built in assertions functionality currently available. 
Can be improved over time.
> Feature testing assertions documentation

- std/fmt/README.md
- Fix the example's numbers for accuracy
- Updated formatting for consistency
> Update sprintf documentation typo

- cli/js/util.ts
- cli/tests/unit/path_from_url_test.ts
> decode path properly on win32

- cli/js/compiler.ts
- cli/tests/bundle.test.out
- cli/tests/compiler_api_test.ts
- deno_typescript/README.md
- deno_typescript/lib.rs
- deno_typescript/system_loader.js
- deno_typescript/system_loader_es5.js
> Re-land #6328

- cli/js/web/body.ts
cleaned up code by using `isTypedArray` method
> refactor(cli/web): use isTypedArray method

- cli/tests/integration_tests.rs
- cli/tests/unit/console_test.ts
- cli/tests/unit/dispatch_json_test.ts
- cli/tests/unit/dispatch_minimal_test.ts
- cli/tests/unit/fetch_test.ts
- cli/tests/unit/globals_test.ts
- cli/tests/unit/streams_transform_test.ts
- cli/tests/unit/test_util.ts
- cli/tests/unit/unit_test_runner.ts
> Include cli/tests/unit in cli/tests/integration_tests

- cli/js/testing.ts
- cli/tests/deno_test_no_color.ts
- cli/tests/integration_tests.rs
> fix(#6368): "deno test" should respect NO_COLOR=true

- Cargo.lock
- core/Cargo.toml
> upgrade: v8 to 8.5.104 (rusty_v8 0.5.1)

- docs/introduction.md
this will land soon https://github.com/denoland/deno_website2/pull/1181
> Remove logos from introduction -> deno.land/artwork

- docs/contributing.md
Updated `tools/format.py` to `./tools/format.py` for consistency with the linting example: `./tools/lint.py`
> Update contributing.md for consistency

- cli/file_fetcher.rs
> Clean up some fetch_remote_source tests

- docs/contributing/building_from_source.md
- docs/contributing/development_tools.md
> doc: add info on installing wasm32-wasi target

- cli/tests/unit/symlink_test.ts
This removes a stale comment left over from this commit 6072755eadb7342a409f43260e5a17b956703a1c
> Remove stale comment left over from #5533

- test_util/src/lib.rs
This reverts commit 70147ee56418c3d67a29070c01746a44d353e855.
> Revert "chore: share HTTP server between tests (#6362)"

- cli/js/compiler.ts
- cli/tests/integration_tests.rs
This PR restores the generation of stats in debug mode when compiling/checking in Deno.
> Restore stats for incremental compile

- cli/ops/process.rs
- cli/tests/unit/process_test.ts
> fix: panic when process stdio rid is 0 or invalid

- cli/tests/unit/process_test.ts
ref https://github.com/denoland/deno/commit/4102a195851033a21c4a23daac4c78ed2329f61f
This makes the CI red
> (fix) remove duplicate identifier [process_test.ts]

- std/testing/asserts_test.ts
> refactor(std/testing): Remove unuseful statement

- cli/tests/integration_tests.rs
- cli/tsc.rs
> Omit buildinfo when --reload passed

- Cargo.lock
- cli/inspector.rs
- cli/ops/tty.rs
- core/Cargo.toml
- core/bindings.rs
- core/core_isolate.rs
- core/errors.rs
- core/es_isolate.rs
- core/zero_copy_buf.rs
> Scopes refactor update

- test_util/src/lib.rs
> Create new DENO_DIR for each test

- cli/tests/037_fetch_multiple.out
- cli/tests/error_012_bad_dynamic_import_specifier.ts.out
- cli/tests/integration_tests.rs
- cli/tests/single_compile_with_reload.ts.out
- cli/tests/ts_decorators.ts.out
- cli/tests/ts_type_imports.ts.out
- cli/tests/tsx_imports.ts.out
- cli/tests/type_definitions_for_export.ts.out
- cli/tests/type_directives_redirect.ts.out
- cli/tsc.rs
- test_util/src/lib.rs
> 'Compile' messages changed to 'Check' messages

- cli/js/lib.deno.ns.d.ts
- cli/js/process.ts
> fix(cli/js/process): Fix conditional types for process sockets

- cli/js/buffer.ts
- cli/tests/unit/buffer_test.ts
> fix(cli): Buffer.bytes() ArrayBuffer size

- std/node/buffer_test.ts
> test(std/node): Add Buffer tests

- std/io/README.md
- std/io/mod.ts
missed to export `streams.ts` in `io/mod.ts` in #5789  and added some docs
> fix(std/io): export streams.ts & added docs

- docs/contributing/building_from_source.md
> docs(contributing): update macOS dependencies of building V8 from source

- std/wasi/README.md
- std/wasi/snapshot_preview1.ts
- std/wasi/testdata/std_fs_file_metadata.rs
This implements fd_filestat_get as a mapping to Deno.fstat.
> feat(std/wasi) implement fd_filestat_get

- std/http/server.ts
- std/http/server_test.ts
https://github.com/denoland/deno/issues/5261
> Support ipv6 parsing

- cli/global_state.rs
- cli/main.rs
- cli/state.rs
- cli/tsc.rs
Resolves #6473 
There are also a few other improvements and refactors to clean up some of the APIs.
> Improvements to TsCompiler

- std/http/cookie.ts
> Update std/http/cookie types

- cli/flags.rs
- cli/global_state.rs
- cli/lockfile.rs
- cli/main.rs
- cli/tests/integration_tests.rs
- cli/tests/lock_check_err.json
- cli/tests/lock_dynamic_imports.json
- cli/tests/lock_dynamic_imports.out
- cli/tests/lock_write_fetch.ts
- cli/tests/lock_write_requires_lock.out
Fixes #4790
Fixes https://github.com/denoland/deno/issues/5231
Fixes https://github.com/denoland/deno/issues/6108
Fixes https://github.com/denoland/deno/issues/6183
> refactor: lock file

- Cargo.lock
- cli/Cargo.toml
- cli/lint.rs
Fixes https://github.com/denoland/deno/issues/6477
> upgrade: dprint-typescript-plugin 0.19.5, deno_lint 0.1.15

- cli/js/web/timers.ts
- cli/tests/unit/timers_test.ts
https://github.com/denoland/deno/issues/6040
> Update timers to ignore Date Override

- cli/tests/echo_server.ts
- tools/http_benchmark.py
> fix(tools): command line args parsing bug, unused function parameter

- cli/js/web/body.ts
Reduced memory usage of `body.arrayBuffer()` by using `Deno.Buffer` instead of pushing to an `Array`
| Type | Body Size | RSS
| ------------- | ------------- | ------------- |
| Buffer | 100MB  | **313.94MB** |
| Array | 100MB  | 358.89MB |
| Buffer | 500MB  | **1065.02MB** |
| Array | 500MB  | 1696.13MB |
| Buffer | 1800MB  | **3733.58MB** |
| Array | 1800MB | 6029.67MB |
Measured using `/usr/bin/time --verbose deno run script.ts`
---
Depends on #6568 or #6570 in order to work for body sizes > 2gb
> refactor(cli/body): use Deno.Buffer in bufferFromStream

- std/wasi/README.md
- std/wasi/snapshot_preview1.ts
- std/wasi/testdata/std_fs_read_dir.rs
This implements fd_readdir as a mapping to Deno.readDirSync.
> feat(std/wasi) implement fd_readdir

- tools/benchmark.py
> Remove test_server dependency from benchmarks

- cli/Cargo.toml
- core/Cargo.toml
- test_util/Cargo.toml
This is to avoid building tokio multiple times.
> Only use one set of tokio features

- std/hash/md5.ts
> Fix scope in std/md5

- cli/tests/044_bad_resource.ts.out
- test_util/src/lib.rs
> share HTTP server between threads (attempt 2)

- cli/js/lib.deno.shared_globals.d.ts
- std/path/posix.ts
- std/path/win32.ts
Attempt 2. See #5521 and #5564.
> Fix definition of URL constructor

- cli/js/lib.deno.ns.d.ts
- cli/js/process.ts
> fix(cli/js/process): Fix process socket types

- cli/flags.rs
- cli/main.rs
- cli/tests/integration_tests.rs
- cli/tests/lock_check_err_with_bundle.json
- cli/tests/lock_check_err_with_bundle.out
- cli/tsc.rs
fix #6491
Not only fixing the flag parser, I also needed to add these lines to validate lockfile.
I'm not sure that this is a right way to do that.
https://github.com/TETRA2000/deno/blob/b35471a76f88dfef030142c13eaa049fec53a2f8/cli/main.rs#L415-L424
Could you give me some advice?
> feat: add lockfile support to bundle (#6491)

- docs/contributing/development_tools.md
> Improve v8-flags docs

- std/http/server.ts
- std/http/server_test.ts
> fix(std/http): properly return port 80 in _parseAddrFromStr

- cli/js/buffer.ts
- cli/tests/unit/buffer_test.ts
fixes #6543. 
This is an alternative implementation of #6568
> fix(cli/buffer): allow Buffer to store MAX_SIZE bytes (ALT)

- cli/tests/045_proxy_test.ts
- cli/tests/cafile_info.ts.out
- cli/tests/integration_tests.rs
Closes https://github.com/denoland/deno/issues/4512
> chore: reenable ignored integration tests

- cli/tsc.rs
Fixes https://github.com/denoland/deno/issues/6419
> fix: harden pragma and reference parsing in module analysis

- cli/tests/unit/performance_test.ts
> fix: more tolerant performance.measure unit tests

- cli/js/web/fetch.ts
- cli/tests/unit/fetch_test.ts
- cli/tests/unit/url_test.ts
- test_util/src/lib.rs
> fix(cli/fetch): fix relative redirect

- cli/ops/dispatch_json.rs
- cli/ops/dispatch_minimal.rs
- cli/ops/plugin.rs
- cli/state.rs
- core/core_isolate.rs
- core/lib.rs
- core/ops.rs
- deno_typescript/lib.rs
> refactor: Make OpDispatcher a trait

- cli/ops/dispatch_json.rs
- cli/ops/mod.rs
- cli/ops/plugin.rs
- cli/ops/web_worker.rs
- cli/state.rs
- core/ops.rs
Similar to #6736 but for json ops
> refactor: new trait JsonOpDispatcher

- cli/build.rs
- cli/js.rs
- cli/startup_data.rs
> refactor(cli): Remove dead code

- .github/workflows/ci.yml
> chore: update Rust to 1.45.0

- std/bytes/README.md
> doc(std/bytes): Fix wrong import in the example code (copyBytes)

- tools/benchmark.py
- tools/benchmark_test.py
Introduced in fa61956f03491101b6ef64423ea2f1f73af26a73
> fix benchmark_test

- cli/js2/22_form_data.js
Removes duplicate code and allow filename overwrite for DomFile.
> FormData cleanup

- tools/lint.py
The command line length is limited in windows, so...
> fix(tools/lint): Support win10

- cli/js2/22_form_data.js
Fixes #6828
Sorry about this silly mistake.
> Fix lastModified for DomFile in FormData

- cli/build.rs
> clean up set_binary_metadata

- cli/js2/README.md
> Add web APIs to cli/js2/README.md

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- test_util/Cargo.toml
To avoid building deps multiple times.
> Align cargo dependency features

- .gitattributes
> fix: make typescript.js as vendored

- .github/workflows/ci.yml
> Remove deno_typescript references from ci

- Cargo.lock
- cli/Cargo.toml
- cli/tests/fmt_check_tests_dir.out
> upgrade: deno_lint v0.1.17

- std/fs/README.md
- std/fs/write_json.ts
- std/fs/write_json_test.ts
* Finish `writeJson` output with a newline character
* Update unit tests
Closes #6810
> Add newline at the end of json files

- cli/doc/parser.rs
- cli/op_error.rs
- cli/swc_util.rs
- cli/tests/compiler_api_test.ts
- cli/tsc.rs
Fixes https://github.com/denoland/deno/issues/6908
> fix: downcast from SwcDiagnosticBuffer to OpError

- std/path/from_file_url_test.ts
- std/path/posix.ts
- std/path/win32.ts
> fix(std/path): Percent-decode in fromFileUrl()

- Cargo.lock
> upgrade: swc_ecmascript

- cli/disk_cache.rs
- cli/tests/049_info_flag_script_jsx.out
- cli/tests/054_info_local_imports.out
- cli/tests/055_info_file_json.out
- cli/tests/import_file_with_colon.ts
- cli/tests/import_file_with_colon.ts.out
- cli/tests/integration_tests.rs
- cli/tests/subdir/file_with_:_in_name.ts
- test_util/src/lib.rs
> feat: hash file names in gen cache

- docs/tools/linter.md
> Fix grammatical error in Linter documentation

- docs/contributing/style_guide.md
The example code was invalid before.
> Add comma between function arguments

- std/encoding/toml.ts
- std/encoding/toml_test.ts
Adds boolean support to toml's stringify method.
> feat(std/encoding/toml): Add boolean support to stringify

- cli/dts/lib.deno.ns.d.ts
> Removed unnecessary `await`

- docs/contributing.md
> Fixed benchmarks URL

- cli/main.rs
> refactor: remove repeated code in main.rs

- cli/dts/lib.deno.shared_globals.d.ts
> fix: MDN attribution

- cli/flags.rs
- cli/tests/031_info_no_check.out
- cli/tests/031_info_no_check.ts
- cli/tests/integration_tests.rs
> fix(deno info): Never type check

- Cargo.lock
- cli/Cargo.toml
Prerequisite for https://github.com/denoland/deno/pull/6940
> upgrade: deno_lint v0.1.21

- .github/workflows/ci.yml
- op_crates/web/README.md
> Add README for deno_web

- cli/file_fetcher.rs
- cli/http_cache.rs
- cli/http_util.rs
- cli/module_graph.rs
- cli/permissions.rs
- cli/tests/integration_tests.rs
- cli/worker.rs
- test_util/src/lib.rs
> Remove unnecessary drop calls

- cli/dts/lib.deno.unstable.d.ts
> remove unnecessary `await`

- .gitattributes
> remove unused git attributes

- core/core_isolate.rs
Follow-up on #6914 
I realized it was missing the removal of a previously registered callback.
> Remove previous heap limit callback when registering

- docs/getting_started/typescript.md
- std/log/logger.ts
- std/log/mod.ts
- std/node/global.ts
- std/tsconfig_test.json
> fix: Make std work with isolatedModules

- cli/op_fetch_asset.rs
- cli/ops/compiler.rs
- cli/ops/dispatch_json.rs
- cli/ops/dispatch_minimal.rs
- cli/ops/mod.rs
- cli/ops/plugin.rs
- cli/ops/web_worker.rs
- cli/state.rs
- core/core_isolate.rs
- core/lib.rs
- core/ops.rs
This reverts commit f83d672ffad7afb1473bd4f9b9c645539064c620.
This reverts commit d51972377c1325076704d9faec2eee6f0e024496.
@bartlomieju Does this help?
cc @95th
> Undo JsonOpDispatcher and OpDispatcher traits

- std/http/file_server.ts
- std/http/file_server_test.ts
> feat(std/http): file_server support flag to disable dir listings

- cli/build.rs
- cli/dts/README.md
> upgrade: TypeScript to 3.9.7

- Cargo.lock
- cli/Cargo.toml
- cli/swc_util.rs
> upgrade: swc, deno_lint, dprint

- cli/lint.rs
Nightly clippy flags a bit of code in master that can be optimised.
> chore: nightly clippy refactor in lint.rs

- docs/tools/debugger.md
See details in https://github.com/denoland/vscode_deno/issues/12#issuecomment-658957984
> docs: update VS Code debugging options for 1.47

- std/datetime/README.md
- std/datetime/formatter.ts
- std/datetime/mod.ts
- std/datetime/test.ts
- std/datetime/tokenizer.ts
- generalise parser to parse ```string``` to ```date``` with custom format
- rename ```parseDate``` and ```parseDateTime``` functions to ```parse```
- add tokenizer
- add formatter to format a ```date``` to ```string``` with custom format
- update readme
> feat(std/datetime): generalise parser, add formatter

- docs/contributing/development_tools.md
- docs/contributing/style_guide.md
- docs/examples/file_system_events.md
- docs/getting_started/typescript.md
- docs/runtime/compiler_apis.md
- docs/tools/debugger.md
- docs/tools/linter.md
this is combine of #7014 , #7066 , #7076 and other typo
> Fix typo in docs

- cli/rt/20_blob.js
- cli/tests/unit/blob_test.ts
Blocks #7051 
Also, shouldnt arrayBuffer be async?
> Blob.arrayBuffer returns uint8array

- cli/doc/module.rs
- cli/doc/namespace.rs
- cli/doc/node.rs
- cli/doc/parser.rs
> refactor(doc): add helper functions for DocNode

- cli/tests/unit/permissions_test.ts
> test(cli): use assertThrowsAsync for permission tests

- docs/contributing/architecture.md
Link to @ry’s talk about deno structure from Israel meetup https://www.youtube.com/watch?v=1b7FoBwxc7E
> docs(contributing/artchitecture): Add Deno conference youtube link

- cli/rt/24_body.js
- cli/tests/unit/body_test.ts
This modifies the body mixin to create streams from any supported body source.
fixes #6752
> Create .body stream from any valid bodySource

- cli/tests/unit/chown_test.ts
> test(cli): use assertThrows and assertThrowsAsync for chown tests

- cli/http_util.rs
- cli/module_graph.rs
- cli/ops/dispatch_minimal.rs
- cli/ops/fs.rs
- cli/ops/io.rs
- cli/ops/net.rs
- cli/ops/net_unix.rs
- cli/ops/tls.rs
- cli/signal.rs
- core/errors.rs
A small follow-up fix to finish the job.
> Remove some more unnecessary 'to_string()' calls

- .gitmodules
> Use https instead of ssh for wasi-test-suite submodule

- std/testing/README.md
- std/testing/asserts.ts
- std/testing/asserts_test.ts
#6773 Add an assertNotMatch function for std/testing/asserts.ts
> feat(std/testing): add assertNotMatch

- cli/flags.rs
- cli/installer.rs
- docs/tools/script_installer.md
> fix(cli/installer): Strip "@..." suffixes from inferred names

- tools/build_benchmark_jsons.py
> fix benchmark publish

- tools/build_benchmark_jsons.py
> fix benchmark publish again

- cli/rt/11_url.js
- cli/tests/unit/url_test.ts
> fix(URL): Add missing part assignment

- Cargo.lock
- core/Cargo.toml
- core/es_isolate.rs
Supersedes https://github.com/denoland/deno/pull/7227
> upgrade: rusty_v8 0.9.1 / V8 8.6.334

- .github/workflows/ci.yml
> upgrade: rust 1.46.0

- std/wasi/snapshot_preview1.ts
> chore(std/wasi): fix no-inner-declarations lints

- cli/tokio_util.rs
> set maximum size of thread pool to 31

- core/lib.rs
- core/modules.rs
- op_crates/web/lib.rs
> Remove unused crate_modules feature

- cli/build.rs
- cli/rt/00_bootstrap_namespace.js
- op_crates/web/lib.rs
Depends on https://github.com/denoland/deno/pull/7311
> Simplify deno_web initialization

- Cargo.lock
- cli/Cargo.toml
- op_crates/web/Cargo.toml
> deno_web 0.6.0

- Cargo.lock
- cli/Cargo.toml
- cli/swc_util.rs
Fixes https://github.com/denoland/deno/issues/7321
> upgrade: swc, deno_doc, deno_lint, dprint

- docs/contributing/building_from_source.md
Not sure if this is a typo, though.
> docs: use the rightwards arrow symbol uniformly

- Cargo.lock
- cli/Cargo.toml
- cli/tsc.rs
<s>Waiting on https://github.com/swc-project/swc/pull/1023 and new SWC release </s> (Actually can do that next week)
Closes #7247
> refactor: use dependency analyzer from SWC

- cli/http_util.rs
- test_util/src/lib.rs
Fixes https://github.com/denoland/deno/issues/7341
> Handle bad redirects more gracefully

- cli/dts/lib.deno.ns.d.ts
> docs: fix anchor link

- Cargo.lock
- cli/Cargo.toml
Removes duplicated rustls crate
> run cargo update

- cli/colors.rs
fixes #7358 
Thanks for review
> fix(cli/colors): colors mismatch

- Cargo.lock
- cli/Cargo.toml
Fix https://github.com/denoland/deno/issues/7361
> upgrade: deno_doc to 0.1.5

- cli/Cargo.toml
- cli/inspector.rs
> fix(cli): suppress 'WSANOTINITIALIZED' error on Deno exit

- cli/main.rs
- cli/tsc.rs
As discussed with @bartlomieju.
> refactor: Improve placeholder module names

- cli/diagnostics.rs
- cli/tests/integration_tests.rs
> chore: add systemMemoryInfo unstable diagnostic

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- test_util/Cargo.toml
> Upgrade Rust crates, pin 'webpki-roots' to version 0.19.0

- cli/tests/https_import.ts
- cli/tests/integration_tests.rs
- cli/tests/lock_write_fetch.ts
- cli/tests/print_hello.ts
fixes this TODO comments
> // TODO Use https://localhost:4555/ but we need more infrastructure to
> // support verifying self-signed certificates.
> test(cli/tests/https_import): use ts file in localhost instead of remote

- cli/tests/integration_tests.rs
- cli/tests/ts_decorators.ts.out
> test: reenable TS decorator test

- cli/ast.rs
Minor change to add some traits to `Location` and `ParsedModule`.
> chore: add some traits to ast.rs

- cli/tests/ts_decorators.ts.out
> Remove unnecessary wildcard from ts_decorators test

- cli/ops/mod.rs
- cli/ops/worker_host.rs
- cli/state.rs
- cli/tsc.rs
- cli/web_worker.rs
- cli/worker.rs
> Rename deno::state::State to deno::state::CliState

- docs/testing.md
> docs(testing): describe coverage blackboxing rules

- cli/inspector.rs
- core/bindings.rs
- core/lib.rs
- core/modules.rs
- core/runtime.rs
Fixes https://github.com/denoland/deno/issues/7482
> Make JsRuntimeState private

- docs/tools/linter.md
> docs(lint): ignore diagnostic in whole file

- std/datetime/mod.ts
- std/datetime/test.ts
> (std/datetime): fix timezone bug

- cli/ast.rs
- cli/errors.rs
- cli/file_fetcher.rs
- cli/global_state.rs
- cli/info.rs
- cli/lint.rs
- cli/main.rs
- cli/media_type.rs
- cli/module_graph.rs
- cli/tsc.rs
- core/error.rs
> minor clean ups (cli/msg.rs -> cli/media_type.rs) 

- cli/ops/fetch.rs
- cli/state.rs
- cli/worker.rs
> Remove http_client from CliState, lazily load it

- std/testing/asserts.ts
- std/testing/asserts_test.ts
> fix(std/testing): assertion diff color

- cli/rt/99_main.js
> simplify global properties

- std/wasi/snapshot_preview1_test.ts
> test(std/wasi): add wasi_sched_yield test

- cli/ops/fetch.rs
- cli/rt/11_streams.js
- cli/rt/26_fetch.js
- std/http/file_server_test.ts
> make fetch use op_fetch_read instead of op_read

- cli/rt/23_multipart.js
> fix: Use Buffer.writeSync in MultipartBuilder

- cli/main.rs
Fixes https://github.com/denoland/deno/issues/6641
> fix: disable rustyline logs

- cli/rt/02_console.js
- cli/tests/unit/console_test.ts
- std/fmt/printf_test.ts
- std/node/assertion_error_test.ts
- std/testing/asserts.ts
> fix(cli/console): always quote and escape inspected strings

- cli/rt/02_console.js
- cli/tests/unit/console_test.ts
> fix(cli/console): quote object string keys that are invalid identifiers

- .github/workflows/ci.yml
- cli/main.rs
- op_crates/fetch/Cargo.toml
- op_crates/fetch/README.md
- op_crates/fetch/lib.rs
> publish deno_fetch during CI

- cli/flags.rs
Restructures flag helpers and applies them consistently.
Adds:
- `deno bundle --no-remote`
- `deno eval --importmap`
- `deno eval --no-remote`
- `deno eval --config`
- `deno eval --no-check`
- `deno eval --reload`
- `deno eval --lock`
- `deno eval --lock-write`
- `deno eval --cached-only`
- `deno eval --seed`
- `deno repl --importmap`
- `deno repl --no-remote`
- `deno repl --config`
- `deno repl --no-check`
- `deno repl --reload`
- `deno repl --lock`
- `deno repl --lock-write`
- `deno repl --cached-only`
- `deno repl --seed`
> feat(bundle, eval, repl): Add missing flags

- .github/workflows/ci.yml
> ci: fix publishing the 'deno_fetch' crate

- std/http/file_server_test.ts
Ref #https://github.com/denoland/deno/issues/7540
> chore: reenable disabled test in std/

- cli/flags.rs
> fix(cli/flags): Make --unstable a global flag

- cli/flags.rs
- cli/main.rs
> fix(cli/installer): Don't reload by default

- cli/global_state.rs
> refactor: remove GlobalState::compile_lock

- cli/coverage.rs
This makes use of a oneshot channel to await for the protocol message result to be resolved for a given call_id.
Closes #7581
> refactor(cli/coverage): await for inspector message response

- cli/flags.rs
- cli/tests/065_import_map_info.out
- cli/tests/integration_tests.rs
> feat(cli): add --importmap option for info subcommand

- std/wasi/snapshot_preview1_test.ts
> test(std/wasi): add fd_renumber test

- docs/testing.md
> typo(docs/testing): V8 is a engine not a runtime

- cli/build.rs
- cli/js.rs
- cli/source_maps.rs
- core/error.rs
- core/examples/http_bench_bin_ops.rs
- core/examples/http_bench_json_ops.rs
- core/modules.rs
- core/runtime.rs
- op_crates/fetch/lib.rs
- op_crates/web/lib.rs
> refactor(core): support error stack, remove js_check

- core/lib.rs
- core/runtime.rs
Somehow accidentally omitted from #7629
> Actually remove js_check

- tools/README.md
this blocks don't contain bash specific code
> mark shell code blocks as sh instead of bash

- cli/dts/lib.deno.shared_globals.d.ts
> fix(lib.deno.shared_globals): Change Console class to interface

- cli/op_fetch_asset.rs
> Simplify op_fetch_asset signature

- std/datetime/README.md
- std/datetime/formatter.ts
- std/datetime/test.ts
- std/datetime/tokenizer.ts
> (std/datetime): 12 and 24 hour support

- cli/rt/02_console.js
- cli/tests/unit/console_test.ts
> fix(cli): customInspect works on functions

- std/async/delay_test.ts
Added a unit test for the delay async function. Fixes https://github.com/denoland/deno/issues/7654
> test(std): unit test for async/delay

- .dprintrc.json
- cli/dts/lib.deno.shared_globals.d.ts
- op_crates/fetch/lib.deno_fetch.d.ts
This dramatically improves docs:
1.4
This PR
cc @kitsonk
> refactor: class instead of var+interface in d.ts

- std/datetime/test.ts
> (std/datetime): add timezone to test date strings

- cli/tests/unit/timers_test.ts
> refactor: clean timers tests

- std/async/README.md
- std/signal/README.md
Resolves #7608 
Added a readme for both std/async and std/signal
> Issue 7608 docs async and signal readme

- .github/workflows/ci.yml
> simply github actions yaml

- cli/ops/fs.rs
- cli/ops/mod.rs
- cli/ops/net.rs
- cli/ops/os.rs
- cli/ops/plugin.rs
- cli/ops/process.rs
- cli/ops/runtime_compiler.rs
- cli/ops/signal.rs
- cli/ops/tls.rs
- cli/ops/tty.rs
- cli/ops/worker_host.rs
Cosmetic change to better contain usage of "GlobalState" in various ops
> refactor: factor out check_unstable op helper

- cli/rt/30_net.js
- cli/tests/unit/net_test.ts
fixes #7697
quite a small change and added test case too
> fix: net listen crashes on explicit undefined hostname

- cli/graph.rs
- cli/tests/ignore_require.js
- cli/tests/integration_tests.rs
> fix: no check recognizes require

- cli/inspector.rs
This signals a graceful shutdown of the inspector server and waits for the server thread to join when an InspectorServer is dropped.
> fix(cli/inspector): shutdown server gracefully on drop

- docs/runtime/permission_apis.md
Fixes https://github.com/denoland/deno/issues/7731
> docs: use const assertion for PermissionDescriptor

- docs/getting_started/debugging_your_code.md
- docs/introduction.md
- docs/linking_to_external_code/import_maps.md
- docs/linking_to_external_code/reloading_modules.md
Follow-up to https://github.com/denoland/deno/pull/7722
> docs: end sentences with a period in docs

- cli/global_state.rs
- cli/specifier_handler.rs
- cli/tests/integration_tests.rs
> fix(cli): use global_state file_fetcher when using SpecifierHandler

- Cargo.lock
- cli/Cargo.toml
- cli/build.rs
- op_crates/fetch/Cargo.toml
- op_crates/fetch/lib.rs
- op_crates/web/Cargo.toml
- op_crates/web/lib.rs
Change deno_fetch::init to take parameter indicating
buildtime.
Add default implementation for FetchPermissions
> refactor: update deno_fetch interface

- std/uuid/_common.ts
- std/uuid/mod.ts
- std/uuid/v1.ts
- std/uuid/v4.ts
- std/uuid/v5.ts
Added JSdocs for the std/uuid module requested by #7487
> docs(std/uuid): Added JSdocs for the std/uuid module

- cli/lockfile.rs
@kitsonk  I have added some tests.  Feedback welcome.
fixes #7653
> chore: add lockfile tests

- core/runtime.rs
Prerequisite for https://github.com/denoland/deno/pull/7672
This commit does reorganization of "JsRuntime::poll" to allow fixing of top-level-await bug.
> refactor(core): JsRuntime::poll

- .github/PULL_REQUEST_TEMPLATE.md
- docs/contributing.md
> chore: update contributing.md and PR template

- docs/contributing/style_guide.md
- docs/examples/read_write_files.md
Let me see if I can fit anything else in here to justify the PR :P
Closes #7841
> Fix deno.land/manual example and add documentation for linting with ESLint inside deno code

- README.md
> docs(README): Use Typescript extension in code block

- Cargo.lock
- core/Cargo.toml
> upgrade: rusty_v8 0.11.0, V8 8.7.220.3

- std/encoding/README.md
> docs(std/encoding/csv): Update the usage of ParseOptions

- cli/fs.rs
It feels easier to read a boolean expression in my opinion
> fix(cli/fs) Small change in filter expression

- cli/dts/lib.deno.shared_globals.d.ts
- cli/dts/lib.deno.worker.d.ts
- cli/tests/subdir/worker_types.ts
- cli/tests/unit/unit_tests.ts
- cli/tests/unit/worker_types.ts
> fix: update worker types to better align to lib.dom.d.ts

- .github/workflows/ci.yml
> upgrade: Rust 1.47.0

- cli/tests/unit/body_test.ts
- cli/tests/unit/request_test.ts
- op_crates/fetch/26_fetch.js
> fix(op_crates/fetch): Stringify and parse Request URLs

- .github/workflows/ci.yml
> invalidate GHA cache

- docs/contributing/architecture.md
> docs: add Deno internals talk from Paris Deno

- cli/tests/unit/url_search_params_test.ts
- op_crates/web/11_url.js
> fix(op_crate/web): Add padding on URLSearchParam

- std/encoding/testdata/inlineArrayOfInlineTable.toml
- std/encoding/toml.ts
- std/encoding/toml_test.ts
Closes [#6394](https://github.com/denoland/deno/issues/6394)
> fix(std): Parsing inline arrays of inline tables in toml

- cli/module_graph2.rs
- cli/specifier_handler.rs
This cleans up the emits in the specifier handler by using an enum with fields for the emit, instead of separate values.  It also renames `build_info` to `ts_build_info` in `SpecifierHandler` and `ModuleGraph2` for clarity purposes.
> refactor(cli): use Emit enum and rename ts_build_info

- cli/tests/023_no_ext_with_headers.headers.json
> Remove dead code

- cli/tests/unit/console_test.ts
This PR fixes the test cases of the inspection of functions.
---
Fixes https://github.com/denoland/deno/issues/7962
> test(console): fix the test cases of function inspections

- Cargo.lock
- cli/Cargo.toml
- cli/tests/lint/expected_from_stdin_json.out
- cli/tests/lint/expected_json.out
- cli/tests/lint/expected_quiet.out
- cli/tests/unit/console_test.ts
- std/archive/tar.ts
> upgrade: deno_doc, deno_lint, dprint, swc

- cli/repl.rs
This extracts is closing into a function so that it can easily be used as the condition for the loop slimming down the body of the loop.
> refactor(cli/repl): extract is_closing to a function

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
> deno_core 0.64.0

- docs/tools.md
- docs/tools/repl.md
This adds a section on the repl with the keybindings that we support out of the box
> docs(tools): add repl section

- std/archive/tar.ts
- std/archive/tar_test.ts
Fixes https://github.com/denoland/deno/issues/8008
> fix(std/tar): fix constant condition

- docs/getting_started/webassembly.md
Fixes #7556 (prematurely closed)
> docs(getting_started): fix WebAssembly example

- cli/ops/worker_host.rs
- cli/rt/11_workers.js
- cli/rt/99_main.js
- cli/tests/073_worker_error.ts
- cli/tests/073_worker_error.ts.out
- cli/tests/074_worker_nested_error.ts
- cli/tests/074_worker_nested_error.ts.out
- cli/tests/integration_tests.rs
- cli/tests/subdir/worker_error.ts
- cli/worker.rs
- op_crates/web/03_global_interfaces.js
- op_crates/web/lib.rs
> fix(cli/worker): Print error stacks from the origin Worker

- README.md
> fix: codesnippet in README contains $STD_VERSION

- Cargo.lock
- cli/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
> bump versions for op crates

- std/datetime/test.ts
Link to issue : https://github.com/denoland/deno/issues/8067
This PR adds tests for the following constants in the datetime module : 
* SECOND
* MINUTE
* HOUR
* DAY
* WEEK
> test(std/datetime): test datetime constants

- std/path/README.md
> docs(std/path): Fix typo in globToRegExp docs

- cli/fmt.rs
> Update link to dprint-plugin-typescript

- cli/rt/99_main.js
- core/core_test.js
- core/modules.rs
- core/normalize_path.rs
- core/ops.rs
> fix(core-cli): fix typos

- cli/flags.rs
- cli/main.rs
- cli/tests/068_cache_test_type_error.out
- cli/tests/integration_tests.rs
- cli/tests/test_type_error/foo_test.ts
- core/module_specifier.rs
> feat(cli/main): Add deno cache --test and --worker

- cli/flags.rs
- cli/main.rs
- cli/tests/068_cache_test_type_error.out
- cli/tests/integration_tests.rs
- cli/tests/test_type_error/foo_test.ts
- core/module_specifier.rs
This reverts commit be15cf285dbf3a7b3025d34cb80e87e54a55dd93.
CC @ry @nayeemrmn
> Revert "feat(cli): Add deno cache --test and --worker (#7920)"

- core/bindings.rs
With recent improvements to REPL implementation,
Deno.core.formatError() API is no longer needed.
> refactor(core): remove Deno.core.formatError()

- cli/main.rs
- cli/module_graph2.rs
- cli/program_state.rs
- cli/tsc2.rs
Closes https://github.com/denoland/deno/issues/8065
> refactor: use of lock file in ModuleGraph2

- cli/flags.rs
Implements #8096 
Allows for script arguments to be passed when running `deno test`.
For example:
`$ deno test test_file.ts -- arg1 arg2`
`Deno.args` will contain `["arg1", "arg2"]`.
> feat(cli): Pass script args for test command

- std/datetime/test.ts
> Remove timezone dependent tests

- std/node/buffer.ts
- std/node/buffer_test.ts
Also added tests that represent the expected behaviour from Node
> fix: std/node/buffer - Buffer.copy doesn't work as expected

- cli/disk_cache.rs
- cli/http_cache.rs
- cli/main.rs
> fix: Use -rw-r--r-- for cache files

- cli/permissions.rs
- cli/program_state.rs
- cli/specifier_handler.rs
- cli/tests/error_worker_permissions_local.ts
- cli/tests/error_worker_permissions_local.ts.out
- cli/tests/error_worker_permissions_remote.ts
- cli/tests/error_worker_permissions_remote.ts.out
- cli/tests/integration_tests.rs
- cli/tsc.rs
> fix(cli): restore permission check on workers

- std/http/file_server.ts
- std/http/file_server_test.ts
> fix: path traversal in std/http/file_server.ts

- cli/tests/empty_typescript.out
- cli/tests/integration_tests.rs
- cli/tsc/99_main_compiler.js
> fix(cli): do not throw on empty typescript files

- cli/module_graph2.rs
- cli/tests/integration_tests.rs
- cli/tests/redirect_cache.out
- cli/tests/subdir/redirects/a.ts
- cli/tests/subdir/redirects/b.ts
Fixes #8154 
~This is working but I need to create some tests.  I suspect the fix is easier than the tests TBH.~
> fix(cli): module graph handles redirects properly

- cli/main.rs
This cleans up TODO in `cache_command`. Flamegraph shows that we spend a lot of time starting up V8.
> refactor: don't spin up V8 for `deno cache`

- cli/ast.rs
- cli/tests/integration_tests.rs
- cli/tests/ts_decorators_bundle.out
- cli/tests/ts_decorators_bundle.ts
Fixes https://github.com/denoland/deno/issues/8166
Need to come up with test
> fix: panic in bundler

- docs/examples/subprocess.md
> docs(docs/examples/subprocess): add missing "`"

- cli/ast.rs
- cli/module_graph2.rs
- cli/tests/integration_tests.rs
- cli/tests/no_check_decorators.ts
- cli/tests/no_check_decorators.ts.out
- cli/tests/subdir/more_decorators.ts
- cli/tests/ts_decorators_bundle.out
- cli/tests/ts_decorators_bundle.ts
> fix(cli): inject helpers when transpiling via swc

- docs/toc.json
> docs(docs/toc.json): add repl

- std/fs/README.md
> Fix typo in std/fs README.md

- cli/dts/lib.esnext.d.ts
TypeScript 4.0.5 release notes https://github.com/microsoft/TypeScript/releases/tag/v4.0.5
TypeScript upgrade steps followed from https://github.com/denoland/deno/blob/master/cli/dts/README.md
> feat: bump TypeScript to 4.0.5

- tools/test_util.py
- tools/third_party.py
- tools/util.py
- tools/util_test.py
> chore: remove dead Python code

- cli/module_graph.rs
- cli/tests/integration_tests.rs
- cli/tests/subdir/worker_unstable.ts
- cli/tests/unstable_worker.ts
- cli/tests/unstable_worker.ts.out
> fix(cli): correct libs sent to tsc for unstable worker

- std/node/url.ts
Added JSDocs docstring for std/node/url
Ref #7487 
Signed-off-by: bhumijgupta <bhumijgupta@gmail.com>
> docs(std/node/url): Added JSDocs for std/node/url

- std/node/util.ts
I added JSdoc for std/node/util.ts (#7487)
> docs: add JSdoc for std/node/util.ts (#7487)

- std/fmt/colors.ts
- std/fmt/printf.ts
- std/io/streams.ts
- std/log/mod.ts
- std/path/posix.ts
> docs(std): Add missing jsdoc

- docs/contributing/style_guide.md
After #8176 style guide became a bit outdated.
> docs: Update style guide

- cli/module_graph.rs
- cli/tests/module_graph/file_tests-b-mod.js
- cli/tests/module_graph/file_tests-importremap.ts
- cli/tests/module_graph/https_deno.land-x-a-mod.ts
> fix(cli): allow remapping to locals for import map

- std/fmt/colors.ts
- std/fmt/printf.ts
Add missing JSDoc for `std/fmt/colors.ts` and `std/fmt/printf.ts`
Related to #7487
> docs(std/fmt): add missing JSDoc

- .github/workflows/ci.yml
This enables full color logs in GitHub Actions.
> build: full color ci logs

- cli/module_graph.rs
- cli/tests/fix_emittable_skipped.js
- cli/tests/fix_emittable_skipped.ts.out
- cli/tests/integration_tests.rs
- cli/tests/subdir/emittable.d.ts
- cli/tests/subdir/polyfill.ts
> fix(cli): ensure that transitory dependencies are emitted

- cli/tests/permission_test.ts
> refactor: rewrite permission_test to not depend on Python

- cli/upgrade.rs
Should I remove the `test_compose_url_to_exec` test? cant see much use for it
> fix(cli/upgrade): Auto detect target triples for upgrade

- cli/global_timer.rs
- cli/main.rs
- cli/ops/runtime.rs
- cli/rt/99_main.js
- cli/tests/subdir/test_worker_basic.js
Removing random dead code I found
> chore: remove dead code

- op_crates/web/02_abort_signal.js
- op_crates/web/abort_controller_test.js
This fixes the nasty bug described in https://github.com/denoland/deno/pull/8230#issuecomment-722945098 
cc @kitsonk
> fix(op_crates/web): handler order when reassign

- cli/media_type.rs
- cli/module_graph.rs
- cli/tests/module_graph/file_tests-a.mjs
- cli/tests/module_graph/file_tests-b.ts
- cli/tsc.rs
> fix(cli): allow root modules be .mjs/.cjs

- cli/module_graph.rs
- cli/tests/module_graph/file_tests-dynamicimport.ts
> tests(cli): check ignores dynamic import errors

- std/fs/ensure_symlink.ts
> styled(std): remove unnecessary if else block

- cli/upgrade.rs
Resolves issue #8304 
Per issue comment thread, I removed the `test_compose_url_to_exec` test.
> fix(cli/upgrade) Remove an unnecessary test 

- cli/main.rs
Some code refactoring for the cli/main macro calls.
> refactor(cli/main): removed extra code

- cli/rt/40_performance.js
- cli/rt/40_permissions.js
- cli/tests/unit/globals_test.ts
- cli/tests/unit/performance_test.ts
- cli/tests/unit/permissions_test.ts
- op_crates/web/02_abort_signal.js
- op_crates/web/03_global_interfaces.js
- op_crates/web/abort_controller_test.js
Another small PR for web compatibility.
> fix(op_crates/web) fix window constructor length

- cli/flags.rs
- cli/lint.rs
- cli/main.rs
> feat(lint): support --rules --json

- std/async/README.md
Hi! Just a quick typo fix.
Cheers!
> docs(std/async): Fix a couple typos in README

- std/fs/walk.ts
#7487 
Add missed JSDocs to `std/fs/walk.ts`.
> docs(std/fs/walk): add JSDoc

- std/log/logger.ts
- std/log/logger_test.ts
> feat(std/log): Log error stack

- std/io/streams_test.ts
> build: fix linting problems

- .github/workflows/ci.yml
> build: upgrade Rust to 1.48.0

- Cargo.lock
- cli/tests/error_no_check.ts.out
- core/Cargo.toml
> upgrade: rusty_v8 0.13.0, v8 8.8.278.2

- std/http/cookie.ts
> refactor(std/http): Rename validateCookieName param name & JSDoc

- std/node/_errors.ts
- std/node/_stream/async_iterator.ts
- std/node/_stream/async_iterator_test.ts
- std/node/_stream/buffer_list.ts
- std/node/_stream/duplex.ts
- std/node/_stream/end-of-stream.ts
- std/node/_stream/from.ts
- std/node/_stream/readable.ts
- std/node/_stream/readable_test.ts
- std/node/_stream/stream.ts
- std/node/_stream/symbols.ts
- std/node/_stream/writable.ts
- std/node/_stream/writable_test.ts
- std/node/_util.ts
- std/node/_utils.ts
- std/node/assertion_error.ts
- std/node/net.ts
> feat(std/node/stream): Add node Readable Stream / Writable Stream / errors support

- cli/flags.rs
- cli/main.rs
- cli/ops/worker_host.rs
- cli/tests/067_test_no_run_type_error.out
- cli/tests/integration_tests.rs
- cli/tests/test_type_error/foo_test.ts
- core/module_specifier.rs
> feat(unstable): Add deno test --no-run

- std/http/cookie.ts
- std/http/cookie_test.ts
> feat(std/http): Validate cookie path value

- cli/tests/075_import_local_query_hash.ts
- cli/tests/075_import_local_query_hash.ts.out
- cli/tests/integration_tests.rs
- cli/tsc/99_main_compiler.js
Fixes regression: https://discord.com/channels/684898665143206084/688040863313428503/780074126073266178.
cc @kitsonk
> fix(cli/tsc): Disable tsc's file extension allowlist

- .github/workflows/ci.yml
You can download binaries from https://dl.deno.land/. The latest commit hash can be found at https://dl.deno.land/canary-latest.txt.
> build: upload canary releases to GCS

- std/node/_errors.ts
> feat(std/node): Port most of node errors

- cli/dts/lib.deno.unstable.d.ts
> docs: Add missing closing parenthesis

- cli/tsc_config.rs
> BREAKING(cli/tsc_config): Make isolatedModules non-configurable

- docs/runtime.md
- docs/runtime/web_platform_apis.md
- docs/toc.json
> docs: document the spec deviations in web apis

- .dprintrc.json
Closes https://github.com/denoland/deno/issues/8491
> build: upgrade dprint to 0.10.0

- cli/ops/websocket.rs
> fix(websocket): set User-Agent header

- cli/tests/integration_tests.rs
Closes https://github.com/denoland/deno/issues/8316
> fix(watch): fix flaky tests for watcher

- cli/tests/integration_tests.rs
> fix flaky tests by using exec in PTY tests

- cli/build.rs
> fix: don't unconditionally build canary

- cli/flags.rs
Fixes #8538. Allow `deno eval` to take cli arguments.
Before:
```
$ deno eval -p Deno.args my_arg
error: Found argument 'my_arg' which wasn't expected, or isn't valid in this context
USAGE:
deno eval <code> --print
For more information try --help
```
After:
```
$ ./target/debug/deno eval -p Deno.args my_arg
[ "my_arg" ]
```
> fix(cli): support passing cli arguments under `deno eval`

- docs/contributing/release_schedule.md
- docs/toc.json
> docs: add info about release schedule

- docs/contributing/release_schedule.md
> fix release dates

- cli/tools/repl.rs
Closes https://github.com/denoland/deno/issues/8338
> fix(repl): close calls sometimes prints results

- Cargo.lock
- cli/Cargo.toml
Also unpins version in `Cargo.toml`
CC @lucacasonato 
Fixes #7288
Fixes #8481
Fixes #8486
Fixes #8530
Fixes #8545
> upgrade: swc_bundler 0.17.3

- std/archive/tar.ts
I just put the default value on function arguments
> style: add default value on argument

- docs/tools/linter.md
This PR does the following two things:
- updates available rule list
- adds a link to the deno_lint documentation site
> docs(lint): Update available rules & add link to doc site

- std/wasi/snapshot_preview1.ts
- std/wasi/snapshot_preview1_test.ts
This adds an exitOnReturn option to context making it possible to unwind the stack on the exit(2) syscall instead of delegating to it directly.
Node has a similar option, https://nodejs.org/api/wasi.html#wasi_wasi_initialize_instance and my web implementation of WASI unwinds by default.
Use case is being able to treat WASI execution contexts as children that don't kill the parent on exit.
> feat(std/wasi): add return on exit option

- Cargo.lock
- cli/Cargo.toml
- cli/tests/bundle/fixture02.out
Fixes #8573
Fixes #8574
Fixes #8584
> upgrade: swc_bundler 0.17.5

- core/runtime.rs
> docs(runtime): Fix typo in load_module's docstring

- std/node/global.d.ts
- std/node/global.ts
- std/node/global_test.ts
> feat(std/node): Add `setImmediate` and `clearImmediate` to global scope

- std/bytes/README.md
- std/bytes/mod.ts
- std/bytes/test.ts
- std/io/bufio.ts
- std/io/bufio_test.ts
- std/mime/multipart.ts
- std/ws/test.ts
Issue: #8610 
I'm just going to drop the code here. Feel free to let me know what else we can do to improve
> modify(std/bytes): Rename functions, Update docs, Modify bytes.concat, bytes.indexOf, and bytes.lastIndexOf

- docs/examples.md
- docs/toc.json
The examples for Permissions and Testing If Main no longer exist.
> docs(examples): Synchronize links in TOC and index

- cli/ops/websocket.rs
- cli/ops/worker_host.rs
- cli/web_worker.rs
- cli/worker.rs
> refactor(cli): Reorganize worker code, use stronger memory ordering

- cli/module_loader.rs
- cli/web_worker.rs
- cli/worker.rs
> refactor(cli): Simplify choosing type lib in CliModuleLoader

- cli/rt/01_web_util.js
- cli/rt/99_main.js
- cli/tests/034_onload/main.ts
- docs/runtime/program_lifecycle.md
Getting setup and recovering - starting with [small things](https://github.com/denoland/deno/pull/8376#issuecomment-734350503) I promised.
This just deduplicates the code a little here, adds a note and a test to make sure there is no future regression :]
I'll hopefully get to the rust stuff on the weekend :D
> fix(crates/rt) deduplicate code

- cli/flags.rs
> chore(cli): unhide lsp command from CLI

- core/runtime.rs
> refactor(core): change script name for core.js

- Cargo.lock
- cli/Cargo.toml
> Upgrade ring to support arm64

- Cargo.lock
- core/Cargo.toml
> upgrade rusty_v8 to 0.14.0

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/crypto/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
> chore: release crates

- cli/lsp/tsc.rs
> fix: pull .d.ts files from js mod

- cli/tests/integration_tests.rs
> Remove dead code: itest_ignore

- .github/workflows/ci.yml
- core/async_cell.rs
- core/resources2.rs
> build: fix doctests, run cargo publish --dry-run

- .github/workflows/ci.yml
> build: remove cargo publish --dry-run

- cli/file_fetcher.rs
- cli/lsp/sources.rs
> fix(lsp): only resolve sources with supported schemas

- std/wasi/snapshot_preview1.ts
> docs(std/wasi): add a basic description of Context

- std/wasi/snapshot_preview1.ts
> docs(std/wasi): document ContextOptions

- Releases.md
- cli/dts/README.md
- cli/tests/DenoWinRunner.cs
- cli/tests/echo_server.ts
- cli/tests/tls/README.md
- core/Cargo.toml
- docs/contributing/release_schedule.md
- docs/contributing/style_guide.md
- docs/examples/import_export.md
- docs/runtime/workers.md
- docs/tools/linter.md
- op_crates/fetch/11_streams.js
- op_crates/fetch/20_headers.js
- op_crates/web/03_global_interfaces.js
- std/datetime/mod.ts
- std/datetime/test.ts
- std/encoding/README.md
- std/encoding/_yaml/example/inout.ts
- std/encoding/_yaml/loader/loader.ts
- std/encoding/_yaml/type/float.ts
- std/encoding/ascii85.ts
- std/encoding/ascii85_test.ts
- std/encoding/binary.ts
- std/encoding/csv_stringify.ts
- std/encoding/hex.ts
- std/encoding/toml.ts
- std/node/_stream/readable.ts
The test fails #8556
I only change the comment, doc and local variable name
> chore: fixed typo

- docs/getting_started/setup_your_environment.md
> docs(tools): add documentation for the deno lsp command

- cli/flags.rs
> fix(cli): zsh completions

- cli/build.rs
- core/build_util.rs
- core/lib.rs
- runtime/build.rs
> Factor out common code into core/build_util.rs

- cli/build.rs
- runtime/build.rs
> Fix docs.rs detection

- Cargo.lock
- cli/Cargo.toml
- runtime/Cargo.toml
> chore: release deno_runtime 0.2.0

- Releases.md
> fix std version

- Cargo.lock
- cli/Cargo.toml
- cli/http_util.rs
- runtime/Cargo.toml
> refactor: remove dead code

- cli/dts/lib.es5.d.ts
TypeScript 4.1.3 release notes https://github.com/microsoft/TypeScript/releases/tag/v4.1.3
TypeScript upgrade steps followed from https://github.com/denoland/deno/blob/master/cli/dts/README.md
> feat: bump TypeScript to 4.1.3

- runtime/permissions.rs
I found a so tiny typo. This PR just fixes it.
> chore(runtime): fix typo

- Cargo.lock
- cli/Cargo.toml
- runtime/Cargo.toml
Closes https://github.com/denoland/deno/issues/8777
> upgrade: rustyline 7.1.0

- Cargo.lock
- cli/Cargo.toml
> upgrade: swc_ecmascript 0.15.1

- cli/lsp/language_server.rs
- cli/tests/lsp/did_open_notification_unstable.json
- cli/tests/lsp/initialize_request_unstable.json
The lsp now respects the `deno.unstable` flag in settings.
> feat(lsp): support the unstable setting

- cli/tests/unit/fetch_test.ts
- op_crates/fetch/26_fetch.js
This implements using `ReadableStream` as a `fetch` body.
> fix: implement readable stream fetch body

- .github/workflows/ci.yml
> ci: setup latest version of Node

- Cargo.lock
- cli/tests/unit/fetch_test.ts
- core/Cargo.toml
- op_crates/fetch/lib.rs
> fix(fetch): Fetch bad URL will not panic!

- Cargo.lock
- core/Cargo.toml
- core/runtime.rs
Closes https://github.com/denoland/deno/issues/8449
> upgrade: rusty_v8 0.15.0, v8 8.8.294

- docs/testing.md
Added the missing import line to make the example work
> docs(testing): Add import line to test example

- docs/contributing/release_schedule.md
> docs: update release schedule dates

- cli/lsp/diagnostics.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tests/integration_tests.rs
- cli/tsc/99_main_compiler.js
- cli/tsc/compiler.d.ts
> fix(lsp): handle ts debug errors better

- cli/module_graph.rs
- cli/tests/info_missing_module.out
- cli/tests/integration_tests.rs
> fix(cli): info does not panic on missing modules

- cli/tests/unit/fetch_test.ts
> chore(cli/tests): fix typo in test failure message

- docs/linking_to_external_code/proxies.md
related issue: #7048
I forgot to fix the documentation about NO_PROXY ..
> docs: add note about NO_PROXY env variable

- .github/workflows/ci.yml
- cli/module_graph.rs
- cli/standalone.rs
- core/async_cancel.rs
- runtime/ops/fs.rs
> upgrade: Rust 1.49.0

- .github/workflows/ci.yml
> ci: don't install python

- cli/tests/unit/fetch_test.ts
CI failures:
- https://github.com/denoland/deno/runs/1639623609
- https://github.com/denoland/deno/runs/1640673594
- https://github.com/denoland/deno/runs/1643404212
> chore: disable flaky test on Windows

- std/wasi/snapshot_preview1.ts
- std/wasi/snapshot_preview1_test.ts
Closes https://github.com/denoland/deno/issues/8623
> feat(std/wasi): allow stdio resources to be specified

- std/wasi/snapshot_preview1.ts
This makes the implementation details of the Context class private, making the public interface much more bare-bones and aligns it closer to what Node exposes which is only the exports.
> BREAKING(std/wasi): make implementation details private

- cli/bench/main.rs
> Add swc size benchmark

- Cargo.lock
- cli/Cargo.toml
- cli/tests/bundle/fixture03.out
> upgrade: deno_doc, deno_lint, dprint, swc_ecmascript, swc_bundler

- cli/tests/wpt.jsonc
- runtime/js/40_performance.js
> fix: align Performance API to spec using WPT

- .github/stale.yml
> enable stale bot

- .github/stale.yml
> chore: exempt tests and build labels from stalebot

- .github/stale.yml
> chore: exempt docs label from stalebot

- cli/tests/integration_tests.rs
- docs/getting_started/first_steps.md
- std/examples/welcome.ts
- std/examples/welcome_test.ts
fixes https://github.com/denoland/deno/issues/8356
> Remove emoji from welcome script so it looks better on windows

- .gitmodules
> chore: checkout submodules with shallow=true

- cli/tests/wpt.jsonc
> test(cli): enable web platform timer tests

- cli/main.rs
- cli/tests/integration_tests.rs
> fix: don't error on version and help flag

- cli/bench/main.rs
> Add cargo_deps to benchmarks

- std/log/README.md
> docs(std/log): add default values description

- Cargo.lock
- cli/Cargo.toml
- cli/tests/bundle.test.out
- cli/tests/bundle/fixture02.out
- cli/tests/bundle/fixture08.out
- cli/tests/bundle/fixture09.out
- cli/tests/bundle/fixture10.out
- cli/tests/bundle/fixture11.out
- cli/tests/bundle/fixture14.out
- cli/tests/bundle/fixture15.out
- Fixes #8970
- Fixes #8978
- Fixes #8224
- Fixes #8725
- Fixes #8943
- Fixes #9055
- Fixes #9076
> upgrade: swc_bundler 0.19.2

- core/runtime.rs
> Move comment to correct place

- runtime/ops/tls.rs
> feat(runtime/tls): add global tls session cache

- cli/tests/integration_tests.rs
- cli/tests/wpt_testharnessconsolereporter.js
> tests: disable logging of `ok` wpt

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/crypto/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
- op_crates/websocket/Cargo.toml
- runtime/Cargo.toml
I have already published these. Please merge on approval.
> Bump crate versions

- runtime/ops/crypto.rs
> chore: Fix copyright in runtime/ops/crypto.rs

- std/datetime/README.md
The current code throws multiple errors
> docs(datetime): Fix an issue with the parse's code

- std/bytes/README.md
> docs(std): Fix typo within the copy's code example

- Cargo.lock
- cli/Cargo.toml
> upgrade: deno_lint to 0.2.16

- cli/tests/070_location.ts
- cli/tests/071_location_unset.ts
- cli/tests/workers_test.ts
> upgrade: dlint in third_party/

- cli/dts/lib.deno.shared_globals.d.ts
fix(ts): Make arrow function correct.
> fix(ts): Make arrow function correct.

- cli/build.rs
Fixes https://github.com/denoland/deno/issues/9137
> fix: incremental build for deno declaration files

- cli/build.rs
- cli/tools/upgrade.rs
- cli/version.rs
> fix: full commit hash in canary compile download

- cli/flags.rs
- cli/main.rs
> fix: panic during `deno compile` with no args

- cli/flags.rs
> chore(compile): add aarch64-apple-darwin target

- docs/toc.json
The sections it interrupts should be adjacent.
> docs(contributing): Move release schedule section

- Cargo.lock
- core/Cargo.toml
- core/bindings.rs
- runtime/inspector.rs
> upgrade rusty_v8 to 0.16.0 (alternative for #9161)

- cli/tests/unit/net_test.ts
- runtime/ops/net.rs
> fix(cli): actually stabilize Deno.shutdown()

- docs/typescript/runtime.md
> docs: Fix typos in TypeScript section of the manual

- std/fmt/README.md
Adds example usage of colors.ts to `std/fmt` README.
> docs(std/fmt): README example colors.ts usage.

- std/encoding/csv_stringify.ts
Ref. https://github.com/denoland/deno/pull/8691/commits/875852bd47c53a5f9fd1c5c01c69916969fd8696
> chore(std/encoding/csv_stringify): Revert typo introduced in #8691

- cli/tests/wpt.jsonc
- op_crates/fetch/11_streams.js
> fix(op_crates/fetch): fix ReadableStream.pipeThrough()

- test_plugin/README.md
- test_plugin/tests/integration_tests.rs
- test_plugin/tests/test.js
This is my first time to make a PR for deno. If this PR has some thing wrong, please to tell me.
fix(test_plugin): Add README.md
fix(test_plugin): Make function has same data.
> fix(test_plugin): Add README.md and make function has same data.

- cli/tools/lint.rs
> chore: fix typo in lint.rs

- docs/tools/compiler.md
New features about compiler in v1.7 haven't been documented. This PR adds them.
> docs(tools/compiler): add for new features in 1.7

- cli/module_graph.rs
- cli/tests/integration_tests.rs
> fix(cli): correctly determine emit state with redirects

- cli/module_graph.rs
- cli/tests/error_missing_module_named_import.ts
- cli/tests/error_missing_module_named_import.ts.out
- cli/tests/integration_tests.rs
- cli/tsc.rs
> fix(cli): early abort before type checking on missing modules

- cli/bench/main.rs
> bench: remove custom error types

- docs/contributing/web_platform_tests.md
- tools/wpt.ts
[Hate to be that guy but 😔]: **~conigured~** ▸ **configured**
> chore: fix typo in wpt cli output

- cli/tests/integration_tests.rs
> test: fix lock_write_fetch test

- docs/contributing/web_platform_tests.md
- docs/toc.json
- op_crates/fetch/21_blob.js
- op_crates/fetch/26_fetch.js
- op_crates/fetch/internal.d.ts
- op_crates/fetch/lib.deno_fetch.d.ts
- op_crates/fetch/lib.rs
- runtime/js/99_main.js
- tools/wpt/expectation.json
- tools/wpt/utils.ts
~Depends on #9305.~ Merged.
This PR contains a rewritten `Blob` implementation that follows the spec at https://w3c.github.io/FileAPI/#blob-section. This implementation passes all Blob related web platform tests.
This is the first of multiple PRs to rewrite the `fetch` implementation and its dependencies to match the specifications and pass WPT.
> refactor: rewrite Blob implementation

- .github/workflows/ci.yml
> cargo publish is done manually now

- Cargo.lock
- cli/Cargo.toml
> chore: upgrade swc

- cli/dts/lib.deno.ns.d.ts
> docs: update example for Deno.Process

- op_crates/fetch/21_file.js
- op_crates/fetch/26_fetch.js
- op_crates/fetch/internal.d.ts
- op_crates/fetch/lib.rs
- runtime/js/99_main.js
- tools/wpt/expectation.json
This PR contains a rewritten `File` implementation that follows the spec at https://w3c.github.io/FileAPI/#file-section. This implementation passes all relevant File related web platform tests.
> refactor: rewrite File implementation

- Cargo.lock
- cli/Cargo.toml
- op_crates/fetch/26_fetch.js
- op_crates/fetch/Cargo.toml
- runtime/Cargo.toml
> fetch optimizations

- cli/lsp/language_server.rs
- cli/module_graph.rs
- cli/tests/bundle_jsx.out
- cli/tests/integration_tests.rs
Closes #9308
Closes #9023 
Closes #8993
> fix(cli/lsp): fix using jsx/tsx when not emitting via tsc

- cli/tests/integration_tests.rs
- cli/tools/repl.rs
Fixes https://github.com/denoland/deno/issues/9398
> fix(repl): prevent symbol completion panic

- .github/workflows/ci.yml
> ci: fix release process

- Cargo.lock
- core/Cargo.toml
- core/bindings.rs
Just an upgrade, actual plumbing for import assertions will be done
in a follow up PR.
> upgrade: rusty_v8 0.17.0, v8 9.0.123

- core/lib.deno_core.d.ts
> chore: fix typo in lib.deno_core.d.ts

- cli/tools/repl.rs
> refactor(cli/tools/repl): merge highlighter into helper

- cli/import_map.rs
- cli/tests/integration_tests.rs
> fix(cli): import maps handles data URLs

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/crypto/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
- op_crates/websocket/Cargo.toml
- runtime/Cargo.toml
- test_util/Cargo.toml
> chore: update dependencies

- Cargo.lock
- cli/Cargo.toml
- cli/ast.rs
> chore: upgrade crates

- .github/workflows/ci.yml
Ref https://github.com/denoland/deno/issues/9484
> fix github actions to ubuntu-18.04

- tools/wpt/expectation.json
> test(cli): enable microtask-queue tests

- runtime/ops/mod.rs
- runtime/ops/web_worker.rs
Extension of #9423 for runtime
> feat(runtime/ops): Strongly typed deserialization of JSON ops

- cli/ast.rs
RwLock should only be used in circumstances where it has some benefit.
Multiple concurrent readers is usually an undesirable design.
> refactor: use Mutex for ErrorBuffer

- cli/tests/085_dynamic_import_async_error.ts
- cli/tests/085_dynamic_import_async_error.ts.out
- cli/tests/delayed_error.ts
- cli/tests/integration_tests.rs
- core/runtime.rs
> fix(core): Make dynamic import async errors catchable

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- README.md
- core/README.md
- docs/contributing/building_from_source.md
- docs/contributing/release_schedule.md
- docs/runtime.md
- docs/runtime/stability.md
- docs/standard_library.md
- tools/wpt.ts
> chore: rename default branch to main

- Cargo.lock
- Releases.md
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/crypto/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
- op_crates/websocket/Cargo.toml
- runtime/Cargo.toml
> Bump v1.7.5

- cli/tests/086_dynamic_import_already_rejected.ts
- cli/tests/086_dynamic_import_already_rejected.ts.out
- cli/tests/integration_tests.rs
- core/runtime.rs
Fixes #6259 (I checked with the user-given repro this time).
Includes #9544.
> fix(core/runtime): Fix dynamic imports for already rejected modules

- cli/tests/error_005_missing_dynamic_import.ts.out
- cli/tests/error_012_bad_dynamic_import_specifier.ts.out
- cli/tests/error_014_catch_dynamic_import_error.js.out
- cli/tests/error_015_dynamic_import_permissions.out
- core/bindings.rs
> fix(core/bindings): Add stacks for dynamic import resolution errors

- cli/tests/integration_tests.rs
- cli/tools/repl.rs
Fixes https://github.com/denoland/deno/issues/9547
> fix(repl): filter out symbol candidates

- docs/getting_started/setup_your_environment.md
> chore: update docs for coc

- cli/tests/integration_tests.rs
> chore: disable flaky test

- Releases.md
> releases v1.7.5

- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
This uses generics to serialize and deserialize values better in the LSP.
> reafactor(lsp): use generics with JSON values

- cli/dts/lib.deno.ns.d.ts
- cli/tests/unit/read_dir_test.ts
- runtime/ops/fs.rs
> fix(runtime): do not panic on irregular dir entries

- cli/flags.rs
- cli/main.rs
> Improve 'deno lsp' help text

- cli/main.rs
> fix: typo in coverage exit_unstable

- cli/lsp/tsc.rs
> fix(lsp): improve exception handling on tsc snapshots

- docs/testing/assertions.md
Adding `assertExists` example to the documentation
> docs(testing): Add assertExists example

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/crypto/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/web/Cargo.toml
- op_crates/webgpu/Cargo.toml
- op_crates/websocket/Cargo.toml
- runtime/Cargo.toml
> Bump crate versions (pre-release)

- cli/Cargo.toml
> Pin lspower, because it made semvar incompatible patch release

- cli/tests/integration_tests.rs
> test(cli): move lint command tests into a module

- cli/tests/workers/test.ts
> fix(cli/tests): Fix flaky worker test

- .github/workflows/ci.yml
Will save people some time. https://discord.com/channels/684898665143206084/684911491035430919/817351410944573481
> chore(ci): move fmt before lint

- docs/contributing/release_schedule.md
> Update release schedule

- docs/runtime/permission_apis.md
Fixes denoland/deno_website2#1698
> chore(manual): remove unstable from permission

- cli/ast.rs
- cli/module_graph.rs
- cli/tests/087_hello.ts
- cli/tests/087_no_check_imports_not_used_as_values.ts
- cli/tests/087_no_check_imports_not_used_as_values.ts.out
- cli/tests/integration_tests.rs
- cli/tests/preserve_imports.tsconfig.json
- cli/tsc_config.rs
> fix(cli/ast): Pass importsNotUsedAsValues to swc

- runtime/README.md
> chore: fix spelling of descendents in runtime readme

- cli/dts/lib.deno.window.d.ts
- cli/dts/lib.deno.worker.d.ts
- cli/tests/unit/globals_test.ts
- cli/tests/workers/test.ts
- cli/tests/workers/worker_globals.ts
- runtime/js/99_main.js
> fix(runtime/js): Add navigator interface objects

- op_crates/web/00_webidl.js
- op_crates/web/internal.d.ts
- op_crates/webgpu/02_idl_types.js
This commit makes the WebIDL input validation more robust.
> fix(webgpu): add webidl records and simple unions

- .github/workflows/ci.yml
- Cargo.toml
> ci: Remove sccache, use better cargo cache

- Cargo.lock
- core/Cargo.toml
- core/runtime.rs
> upgrade: rusty_v8 0.21.0

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/console/Cargo.toml
- op_crates/crypto/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/url/Cargo.toml
- op_crates/web/Cargo.toml
- op_crates/webgpu/Cargo.toml
- op_crates/webidl/Cargo.toml
- op_crates/websocket/Cargo.toml
- runtime/Cargo.toml
> chore: bump crates

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/webgpu/Cargo.toml
- op_crates/websocket/Cargo.toml
- runtime/Cargo.toml
- test_util/Cargo.toml
This upgrades Tokio to the latest version 1.3.0.
> chore: upgrade to tokio 1.3.0

- cli/tests/workers/worker_crypto.js
- runtime/web_worker.rs
Fixes https://github.com/denoland/deno/issues/9772
> fix(runtime): do not require deno namespace in workers for crypto

- README.md
- docs/getting_started/installation.md
- Add Scoop installation method
- Update cargo install command (add `--locked`)
> docs: match install section with website

- Cargo.lock
- cli/Cargo.toml
- runtime/Cargo.toml
> chore: Upgrade rustyline to 8.0.0

- docs/testing/assertions.md
While Deno comes with powerful [assertions modules](https://deno.land/std@$STD_VERSION/testing/asserts.ts)  but
there is always something specific to the project you can add. Creating `custom assertion function` can improve readability and reduce the amount of code.
> docs(testing): Add custom test example

- docs/examples/subprocess.md
> feat(doc): update example for sub processes

- op_crates/fetch/lib.rs
- runtime/ops/fs.rs
- runtime/ops/net.rs
- runtime/ops/net_unix.rs
- runtime/ops/process.rs
- runtime/ops/signal.rs
- runtime/ops/tls.rs
- runtime/ops/tty.rs
In some places rids are i32 and cast to u32
> refactor: normalize rids to u32

- docs/examples/import_export.md
> docs(typo): Fix minor typo in documentation

- op_crates/webgpu/01_webgpu.js
- op_crates/webgpu/lib.rs
- runtime/ops/webgpu.rs
> feat(op_crates/webgpu): create instance only when required

- Cargo.lock
- cli/Cargo.toml
- core/Cargo.toml
- op_crates/fetch/Cargo.toml
- runtime/Cargo.toml
- test_util/Cargo.toml
> upgrade: tokio 1.4.0

- docs/linking_to_external_code/import_maps.md
> docs(import_maps): Fix example for project-relative absolute specifiers

- .github/workflows/ci.yml
> build: disable CI cache

- docs/getting_started/setup_your_environment.md
unlike other system config file, in windows `$profile` file is a common config file of powershell , just use `>` will overried the user config file , which is terrible. This change use append instead of override which is more reasonable
> docs(getting_started/setup_your_environment.md)

- .github/workflows/ci.yml
> Remove other unrelated CI build things

- cli/tests/integration_tests.rs
> fix(cli): re-add dom.asynciterable lib

- Cargo.lock
- core/Cargo.toml
- serde_v8/Cargo.toml
- serde_v8/README.md
cc @AaronO 
https://crates.io/crates/serde_v8
> chore: publish serde_v8, bump version

- docs/help.md
- docs/toc.json
> docs: Add help community section 

- docs/getting_started/installation.md
> docs(getting_started/installation): Add the Nix pkg manager to install options

- docs/typescript/faqs.md
> Fix typo in faqs.md

- docs/introduction.md
Minor copyedit changes to the introduction.
> docs(introduction): copyedit for clarity

- core/runtime.rs
> refactor: don't call Context::Global in async_op_response

- docs/getting_started/setup_your_environment.md
> docs(getting_started/setup_your_environment.md)  Kakoune LSP example configuration #9988

- docs/contributing/architecture.md
Updates fields for `Deno.metrics()` example in the docs.
> docs(architecture): update Deno.metrics() table data

- docs/getting_started/setup_your_environment.md
I made an extension that uses deno's language server in the Atom editor.
https://github.com/ayame113/atom-ide-deno
I would like to add documentation on this.
> docs: Added documentation about Atom Editor

- cli/tests/unit/blob_test.ts
- cli/tests/unit/response_test.ts
> chore: update std submodule

- cli/lsp/tsc.rs
> fix(lsp): folding range adjustment panic

- cli/lsp/language_server.rs
> fix(lsp): don't error on tsc debug failures for code actions

- op_crates/file/02_filereader.js
- op_crates/web/00_infra.js
- op_crates/web/01_mimesniff.js
- op_crates/web/08_text_encoding.js
- op_crates/web/internal.d.ts
- op_crates/web/lib.rs
- tools/wpt/expectation.json
This adds some algorithms from the whatwg mimesniff, whatwg infra, and
whatwg encoding specs that FileReader needs to use internally.
This adds some TODOs that need to be resolved in follow ups (related
to "queue a task" algorithm in HTML spec).
> fix: enable FileReader wpt and align to spec

- cli/tests/unit/read_file_test.ts
- cli/tests/unit/read_text_file_test.ts
- runtime/js/40_read_file.js
> fix(runtime/readFile*): close resources on error during read

- Cargo.lock
- cli/Cargo.toml
- cli/tests/integration_tests.rs
- core/Cargo.toml
- op_crates/fetch/Cargo.toml
- op_crates/url/Cargo.toml
- op_crates/web/Cargo.toml
- op_crates/webgpu/Cargo.toml
- op_crates/websocket/Cargo.toml
- op_crates/websocket/lib.rs
- runtime/Cargo.toml
- serde_v8/Cargo.toml
- test_util/Cargo.toml
Update all the deps.
Closes #10066
> chore: update deps

- .github/workflows/ci.yml
main branch seems to be messed up
https://github.com/denoland/deno/runs/2299255730
> Clear CI cache

- README.md
Adjusted the language used to describe the links pointing to more information
> chore(readme): Improve link descriptions

- docs/examples/fetch_data.md
> docs: fix typo in fetch example

- cli/bench/deno_http_native.js
- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/http_test.ts
- runtime/js/40_http.js
- runtime/js/90_deno_ns.js
> API change: Deno.startHttp -> Deno.serveHttp

- cli/tests/unit/dispatch_bin_test.ts
- core/core.js
- core/ops_json.rs
Fixes this regression caused by #9719:
> fix(core): Connect async op error stacks with user code

- cli/lsp/registries.rs
This introduces more validations from the old v2 branch, and adds the tests from
that branch.
> chore: improve lsp registry validations

- core/runtime.rs
> core: let embedders plug in their own V8 platform

- .github/workflows/ci.yml
- Cargo.lock
- cli/tests/wasm_unreachable.out
- core/Cargo.toml
- serde_v8/Cargo.toml
> upgrade: rusty_v8 0.22.0 (V8 9.1.269.2)

- .github/workflows/ci.yml
- Cargo.lock
- core/Cargo.toml
- serde_v8/Cargo.toml
> upgrade: rusty_v8 0.22.1 (V8 9.1.269.5)

- core/gotham_state.rs
Include the type name in the error message so you know what to look for.
> fix(core): better "missing type" GothamState error

- cli/flags.rs
> improve help text

- cli/lsp/sources.rs
> fix(#10031): lsp handles x-typescript-types header on type only imports properly

- cli/tests/workers/http_worker.js
- cli/tests/workers/test.ts
- runtime/web_worker.rs
Closes https://github.com/denoland/deno/issues/10192
> fix(runtime): include HTTP op in WebWorker

- .github/workflows/ci.yml
- Cargo.lock
- cli/Cargo.toml
> chore: upgrade deno_doc, deno_lint

- cli/lsp/language_server.rs
Fixes incorrect performance mark in `document_symbol`
cc @kitsonk
> Fix(lsp): document symbol performance mark

- docs/getting_started/installation.md
Users want docker guidance.
https://github.com/denoland/deno/issues/3356
Provide it.
> docs: advise docker support

- .github/workflows/ci.yml
> Use Node 16 in CI

- cli/tests/unit/response_test.ts
- op_crates/fetch/23_response.js
> fix(fetch): Response inspect regression

- .github/workflows/ci.yml
> Clean cache

- cli/tests/workers/http_worker.js
- cli/tests/workers/test.ts
> fix(#10302): flaky worker test

- cli/fmt_errors.rs
Fixes #10292
Before and after:
cc @nayeemrmn
> fix(#10292): Don't gray-out internal frames

- op_crates/websocket/01_websocket.js
- op_crates/websocket/lib.rs
Fixes #10300
No tests because WPT is blocked by https://github.com/denoland/deno/issues/10312.
> fix: parse websocket messages correctly

- .github/workflows/ci.yml
- cli/lsp/language_server.rs
> Use ubuntu-latest-xl on more CI jobs

- .github/workflows/ci.yml
- cli/lsp/language_server.rs
depends on https://github.com/denoland/deno/pull/10322
> Key CI cache on build profile

- core/README.md
> docs(core/README.md): updated example link

- cli/tools/upgrade.rs
Closes #10291
Cursor movement needs some fixing.
https://user-images.githubusercontent.com/13135287/115950129-bbc46180-a4d9-11eb-9d82-91ca8ef2d6a5.mov
Personally I don't think we need this and shouldn't be adding it
> feat(cli/upgrade): add download progress

- cli/lsp/completions.rs
Closes https://github.com/denoland/deno/issues/10362
> fix(lsp): enable import completions on export statements

- cli/dts/lib.deno.ns.d.ts
> fix: incorrect JSDoc for `Deno.noColor`

- .github/workflows/ci.yml
- cli/main.rs
- cli/main_runtime.rs
- cli/tests/integration_tests.rs
- core/runtime.rs
- op_crates/crypto/lib.rs
- op_crates/fetch/lib.rs
- op_crates/webgpu/lib.rs
- runtime/lib.rs
> ci: error on warnings

- cli/dts/lib.deno.ns.d.ts
> fix: invalid return types for asynchronous and synchronous `File#truncate`

- docs/tools/compiler.md
> Remove --lite from docs

- cli/dts/lib.deno.ns.d.ts
This PR documents how to stop the file watcher.
closes #9399
> docs: document how to stop file watcher

- .github/workflows/ci.yml
- core/runtime.rs
> ci: error on warning

- cli/ops/testing.rs
- cli/tests/test/allow_all.out
- cli/tests/test/allow_none.out
- cli/tests/test/deno_test.out
- cli/tests/test/deno_test_fail_fast.out
- cli/tests/test/deno_test_only.ts.out
- cli/tests/test/deno_test_unresolved_promise.out
- cli/tests/test/exit_sanitizer_test.out
- cli/tests/test/quiet_test.out
- cli/tests/test/test_finally_cleartimeout.out
- cli/tools/test_runner.rs
Closes https://github.com/denoland/deno/issues/4644
> feat(cli): print test origins

- cli/lsp/tsc.rs
- extensions/console/lib.deno_console.d.ts
> fix(extensions/console): Remove `console.timeStamp` from types

- cli/dts/lib.deno.ns.d.ts
> docs: use `Deno.openSync` in `Deno.ftruncateSync` example

- cli/ops/runtime_compiler.rs
- cli/program_state.rs
- cli/tests/compiler_api_test.ts
- cli/tests/error_import_map_unable_to_load.out
- cli/tests/integration_tests.rs
> fix(cli): give context when failed to load import map

- docs/examples/unix_cat.md
Getting rid of those imperative for loops...
> docs(examples): simplify unix cat

- cli/dts/lib.deno.ns.d.ts
> docs: explicitly import assert in examples

- cli/dts/lib.deno.ns.d.ts
> docs: fix env examples

- cli/dts/lib.deno.ns.d.ts
> docs: add missing awaits

- cli/dts/lib.deno.ns.d.ts
> docs(cli/dts): env.get will return `undefined` if not exist

- extensions/fetch/20_headers.js
Closes https://github.com/denoland/deno/issues/10520
> perf(headers): improve iterator complexity to O(2n)

- cli/tests/integration_tests.rs
- runtime/permissions.rs
> Switch grant/deny prompt to yes/no

- Cargo.lock
- core/Cargo.toml
- serde_v8/Cargo.toml
> upgrade: rusty_v8 0.22.2

- cli/dts/lib.deno.ns.d.ts
> docs: fix Deno.run example

- cli/dts/lib.deno.ns.d.ts
> docs: fix Deno.seek and Deno.seekSync examples

- cli/dts/lib.deno.ns.d.ts
> docs: fix Deno.watchFs example

- cli/tests/integration_tests.rs
> disable test_watch integration test

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): fix `Deno.applySourceMap` example

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): fix worker net permissions example

- .github/workflows/ci.yml
Note that Rust 1.51.1 adds extra verification to avoid miscompiles, so it
is possible that this PR causes build failures on CI, in which case it
needs to be reverted.
See https://blog.rust-lang.org/2021/05/10/Rust-1.52.1).
> ci: force enable incremental compilation

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): fix missing std/testing/asserts.ts imports in examples

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): use `Deno.stdin.rid` in `Deno.setRaw` example

- cli/config_file.rs
- cli/lsp/language_server.rs
> fix(lsp): remove duplicate cwd in config path

- cli/ops/testing.rs
> refactor(cli/ops): don't pass testing ops through json

- docs/runtime/web_storage_api.md
- docs/toc.json
> docs(runtime): add WebStorage API

- docs/tools/linter.md
`no-deprecated-deno-api` and `no-unused-vars` has been added, and `no-undef` has been disabled.
The document page didn't catch up with it, so just updated it.
> docs(lint): update available rules

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): remove stray new operators in examples

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): fix http server example

- cli/dts/lib.deno.ns.d.ts
- cli/tests/unit/real_path_test.ts
- runtime/js/30_fs.js
> feat(runtime): support URL overloads for `Deno.realPath` and `Deno.realPathSync`

- cli/tests/dynamic_import/permissions_blob_local.ts
- cli/tests/dynamic_import/permissions_blob_local.ts.out
- cli/tests/dynamic_import/permissions_data_local.ts
- cli/tests/dynamic_import/permissions_data_local.ts.out
- cli/tests/workers/permissions_blob_local.ts
- cli/tests/workers/permissions_blob_local.ts.out
- cli/tests/workers/permissions_data_local.ts
- cli/tests/workers/permissions_data_local.ts.out
- cli/tests/workers/permissions_dynamic_remote.ts.out
> tests: fix broken tests on main

- Cargo.lock
- Releases.md
- bench_util/Cargo.toml
- cli/Cargo.toml
- core/Cargo.toml
- extensions/console/Cargo.toml
- extensions/crypto/Cargo.toml
- extensions/fetch/Cargo.toml
- extensions/file/Cargo.toml
- extensions/timers/Cargo.toml
- extensions/url/Cargo.toml
- extensions/web/Cargo.toml
- extensions/webgpu/Cargo.toml
- extensions/webidl/Cargo.toml
- extensions/websocket/Cargo.toml
- extensions/webstorage/Cargo.toml
- runtime/Cargo.toml
This PR should be rebased in, not squashed.
> 1.10.2 into main

- .github/workflows/ci.yml
> ci: make rustc deny warnings on all platforms

- Cargo.lock
- Cargo.toml
> chore: add/update crates listed in workspace

- cli/tsc/99_main_compiler.js
This PR significantly reduces the number of ops per tsc LSP request, as tsc requests the version of the script some times 20x in a single request.
> refactor(lsp): memoize script versions per tsc request

- cli/lsp/diagnostics.rs
- cli/lsp/sources.rs
- cli/tests/integration_tests_lsp.rs
> feat(lsp): provide X-Deno-Warning as a diagnostic

- core/core.js
> cleanup(core.js): make op wrapper arg names generic

- cli/config_file.rs
- cli/lsp/language_server.rs
Before:
```
Failed to load configuration file
```
After:
```
Could not find the config file: /Users/sr/p/deno_lsp/tsconfig.json
```
Closes https://github.com/denoland/deno/issues/10646
> fix(lsp): make failed to load config error descriptive

- docs/typescript/faqs.md
> docs(typescript/faqs): Fix typo in faqs.md

- docs/testing.md
> docs(testing): Fix typo in testing.md

- cli/tools/installer.rs
- cli/tools/test_runner.rs
Closes https://github.com/denoland/deno/issues/10556
> fix(deno_install): support `file:` scheme URLs

- cli/lsp/diagnostics.rs
- cli/tests/integration_tests_lsp.rs
- cli/tests/lsp/diagnostics_deno_deps.json
> fix(#10695): deps diagnostics include data property

- cli/tests/unit/http_test.ts
- runtime/js/40_http.js
> fix(runtime/js/http): Expose nextRequest() errors in respondWith()

- bench_util/Cargo.toml
> chore: publish deno_bench_util crate

- cli/dts/lib.deno.ns.d.ts
> fix(dts): `NotSupported` error class not in types #10701

- bench_util/README.md
Tried releasing the crate but it was missing `README.md`
> chore: add README to bench_util/

- .github/workflows/ci.yml
- cli/tests/integration_tests_lsp.rs
- cli/tests/lsp/code_action_params_deadlock.json
- test_util/src/lsp.rs
> chore(lsp): provide test for lsp deadlock issue

- cli/dts/lib.deno.ns.d.ts
> fix(docs): rename read to readSync

- cli/tools/upgrade.rs
> Put `downloaded percentage`  number to the middle, and remove the leading zero(s) of `downloaded size`

- cli/lsp/analysis.rs
- cli/lsp/diagnostics.rs
- cli/module_graph.rs
- cli/tests/integration_tests_lsp.rs
- cli/tests/lsp/diagnostics_deno_types.json
- cli/tests/lsp/did_open_params_deno_types.json
Fixes #9823
~Still need to add specific tests.~
> feat(lsp): diagnostics for deno types and triple-slash refs

- cli/dts/lib.deno.unstable.d.ts
> docs(cli/dts): tag test permission example as typescript

- test_plugin/tests/test.js
Just a tiny code quality boost.
> cleanup(test_plugin): use else if statement

- cli/config_file.rs
> fix(tsconfig): empty tsconfig.json file does not cause error

- docs/getting_started/permissions.md
> docs(permissions): Fix grammatical error in permissions docs

- Cargo.lock
- extensions/web/Cargo.toml
- runtime/Cargo.toml
> chore: release web extension@0.38.0

- cli/lsp/analysis.rs
- cli/lsp/language_server.rs
- cli/lsp/tsc.rs
- cli/tests/integration_tests_lsp.rs
- cli/tests/lsp/code_action_params_imports.json
- cli/tests/lsp/code_action_resolve_params_imports.json
- cli/tests/lsp/code_action_resolve_response_imports.json
- cli/tests/lsp/code_action_response_imports.json
> fix(#10765): lsp import fixes include extensions

- docs/contributing/release_schedule.md
> Update release dates

- cli/main.rs
Fixes https://github.com/denoland/deno/issues/10788
Merge on approval
> fix: running subcommand with coverage collection

- cli/dts/lib.deno.unstable.d.ts
- cli/tests/unit/utime_test.ts
- runtime/js/30_fs.js
> feat(cli): support URL overloads for `Deno.utime` and `Deno.utimeSync`

- tools/wpt/expectation.json
> chore: update wpt

- Releases.md
> docs(releases): remove doc changes

- .github/workflows/ci.yml
- tools/wpt.ts
- tools/wpt/utils.ts
WPT results will be collected as JSON and uploaded to https://dl.deno.land/wpt/$COMMIT_HASH.json for commits to the main branch.
> build: collect wpt results as json

- cli/lsp/diagnostics.rs
- cli/lsp/documents.rs
- cli/lsp/language_server.rs
- cli/tests/integration_tests_lsp.rs
> fix(#10775): diagnostics update on dependency changes

- cli/dts/lib.deno.ns.d.ts
- cli/tests/unit/rename_test.ts
- runtime/js/30_fs.js
> feat(runtime): support URL overloads for `Deno.rename` and `Deno.renameSync`

- cli/dts/lib.deno.ns.d.ts
- runtime/js/30_fs.js
> feat(cli): support URL overload for `Deno.chdir`

- Cargo.lock
- extensions/crypto/01_crypto.js
- extensions/crypto/Cargo.toml
- extensions/crypto/lib.deno_crypto.d.ts
- extensions/crypto/lib.rs
- tools/wpt/expectation.json
> feat(extensions/crypto): implement randomUUID

- tools/wpt.ts
- tools/wpt/expectation.json
- tools/wpt/testharnessreport.js
See https://github.com/denoland/deno/pull/10760#issuecomment-855260776
> test: fix wpt runner expected test file failures

- Cargo.lock
- extensions/crypto/01_crypto.js
- extensions/crypto/Cargo.toml
- extensions/crypto/lib.rs
- extensions/web/lib.rs
- extensions/webstorage/Cargo.toml
- extensions/webstorage/lib.rs
- runtime/errors.rs
https://github.com/denoland/deno/pull/10853#discussion_r645999483
> refactor(extensions/crypto): throw max bytes exceeded domexception from rust

- extensions/web/08_text_encoding.js
> fix: typo in validator for TextEncoder#encode

- extensions/web/08_text_encoding.js
- extensions/web/lib.deno_web.d.ts
- runtime/js/99_main.js
- tools/wpt/expectation.json
> feat(web): Implement TextDecoderStream and TextEncoderStream

- extensions/fetch/11_streams.js
- extensions/fetch/22_body.js
- extensions/fetch/23_request.js
- extensions/fetch/23_response.js
- extensions/fetch/26_fetch.js
- extensions/fetch/internal.d.ts
- extensions/fetch/lib.rs
- extensions/web/03_abort_signal.js
- runtime/js/40_http.js
- tools/wpt/expectation.json
This commit introduces fetch aborting via an AbortSignal.
Closes #5471
> feat(fetch): implement abort

- extensions/crypto/01_crypto.js
- extensions/fetch/20_headers.js
- extensions/fetch/21_formdata.js
- extensions/fetch/23_request.js
- extensions/fetch/23_response.js
- extensions/file/01_file.js
- extensions/file/02_filereader.js
- extensions/web/01_dom_exception.js
- extensions/web/03_abort_signal.js
- extensions/web/08_text_encoding.js
- extensions/webidl/00_webidl.js
- extensions/webidl/internal.d.ts
- tools/wpt/expectation.json
Fixes some WPT test cases, and removes some LOC.
> refactor: clean up webidl protype configuration

- .github/workflows/ci.yml
- tools/upload_wptfyi.js
For an example of what this does, view the status checks on https://github.com/denoland/deno/commit/3b3be024fa1895a9a1df0a2e67fe93aa888b198e
> tests: upload WPT reports to wpt.fyi

- Cargo.lock
- cli/Cargo.toml
> chore: upgrade deno_lint 0.6.1

- Cargo.lock
- core/Cargo.toml
> upgrade: rusty_v8 0.22.3

- cli/main.rs
> refactor: use join instead of format!

- docs/getting_started/permissions.md
> docs: fix typo

- cli/tests/integration_tests.rs
- cli/tools/repl.rs
> fix(repl): Complete declarations

- extensions/web/06_streams.js
- tools/wpt/expectation.json
As the title says. Just minor fixes and refactors.
> fix: pass some more WHATWG streams WPT

- docs/runtime/web_storage_api.md
This PR aims to give more examples of how to use the `localStorage` API.
> docs(runtime): Add localStorage API example

- extensions/console/02_console.js
- tools/wpt/expectation.json
Fixes the last failing tests: https://staging.wpt.fyi/results/console/idlharness.any.html?label=master&product=deno
> fix: some more console spec compliance

- Cargo.lock
- extensions/fetch/20_headers.js
- extensions/url/00_url.js
- extensions/url/Cargo.toml
- extensions/url/benches/url_ops.rs
- extensions/webidl/00_webidl.js
- tools/wpt/expectation.json
> fix: align URL / URLSearchParams to spec

- cli/main.rs
- cli/module_graph.rs
- cli/program_state.rs
- cli/tests/single_compile_with_reload.ts
- cli/tests/single_compile_with_reload.ts.out
- cli/tests/single_compile_with_reload_worker.ts
- core/modules.rs
- core/runtime.rs
> fix(core/modules): Prepare modules only once per runtime

- cli/tests/unit/globals_test.ts
- runtime/js/06_util.js
- runtime/js/99_main.js
> feat: Deno namespace configurable and unfrozen

- cli/diagnostics.rs
- cli/module_graph.rs
- cli/ops/runtime_compiler.rs
- cli/tests/compiler_api_test.ts
> fix(#10761): graph errors reported as diagnostics for `Deno.emit()`

- tools/cut_a_release.md
Add instructions for the release process of `deno_std` and `deno_docker` repos.
> chore: update release instructions

- extensions/webstorage/lib.rs
Increate localstorage from `5MB` to `10MB`.
Closes https://github.com/denoland/deno/issues/10557
> fix(extensions/webstorage): Increase localstorage to 10MB

- .github/workflows/ci.yml
> ci: fix pushing benchmark results to gh-pages

- extensions/url/00_url.js
- extensions/webidl/00_webidl.js
- tools/wpt/expectation.json
> fix(extensions/url): Allow arbitrary USVStrings in the URLSearchParams constructor

- cli/lsp/language_server.rs
- cli/tests/integration_tests_lsp.rs
- cli/tests/lsp/initialize_params_bad_config_option.json
> fix(lsp): handle invalid config setting better

- tools/wpt/runner.ts
> fix(wpt): Clean up temporary files created by the WPT test runner

- .github/workflows/ci.yml
- Cargo.lock
- cli/tests/wasm_unreachable.out
- core/Cargo.toml
- core/runtime.rs
> Upgrade rusty_v8 (V8 9.2)

- Cargo.lock
- core/Cargo.toml
> chore: upgrade serde_v8

- cli/tests/unit/message_channel_test.ts
- core/bindings.rs
- extensions/web/13_message_port.js
Fixes #11102
~~Blocked on https://github.com/denoland/rusty_v8/pull/712 and a rusty_v8 release.~~
> fix: MessagePort in message for postMessage transfers

- cli/tests/unit/http_test.ts
- runtime/ops/http.rs
> fix(runtime/http): Encode and decode headers as byte strings in the HTTP server

- Cargo.lock
- bench_util/Cargo.toml
- cli/Cargo.toml
- core/Cargo.toml
- core/lib.rs
- extensions/broadcast_channel/Cargo.toml
- extensions/console/Cargo.toml
- extensions/crypto/Cargo.toml
- extensions/fetch/Cargo.toml
- extensions/timers/Cargo.toml
- extensions/url/Cargo.toml
- extensions/web/Cargo.toml
- extensions/webgpu/Cargo.toml
- extensions/webidl/Cargo.toml
- extensions/websocket/Cargo.toml
- extensions/webstorage/Cargo.toml
- runtime/Cargo.toml
> chore: release deno_core

- cli/tools/repl.rs
- runtime/worker.rs
> Get rid of REPL timeout

- .github/workflows/ci.yml
> ci: don't set DENO_CANARY when releasing

- cli/tests/unit/fetch_test.ts
- extensions/fetch/lib.rs
> fix: panic in request body streaming

- Cargo.lock
- cli/Cargo.toml
> upgrade: swc 0.44.0

- .github/workflows/ci.yml
- .github/workflows/wpt_epoch.yml
- tools/upload_wptfyi.js
> build: switch to wpt.fyi prod

- .github/workflows/ci.yml
> ci: don't set DENO_CANARY when releasing, attempt 2

- Cargo.lock
- Releases.md
- cli/Cargo.toml
- extensions/broadcast_channel/Cargo.toml
- extensions/console/Cargo.toml
- extensions/crypto/Cargo.toml
- extensions/fetch/Cargo.toml
- extensions/timers/Cargo.toml
- extensions/url/Cargo.toml
- extensions/web/Cargo.toml
- extensions/webgpu/Cargo.toml
- extensions/webidl/Cargo.toml
- extensions/websocket/Cargo.toml
- extensions/webstorage/Cargo.toml
- runtime/Cargo.toml
> Add 1.11.3 release commit into main

- cli/flags.rs
> docs(cli/flags): use deno instead of target/debug/deno

- extensions/fetch/22_body.js
Fixes #11211.
---------------
The tests for this PR are in web-platform-tests/wpt#29552.
> fix(extensions/fetch): A consumed body with a non-stream source should result in a disturbed stream

- extensions/web/lib.rs
The current implementation of `op_encoding_encode_into` UTF-8 encodes each individual code point in the input string into the output buffer. But after the ops binding, the input is a Rust `String`, so the UTF-8 bytes can simply be copied to the output. This would improve this API's performance.
Part of #10978.
> refactor(extensions/web): Improve performance for TextEncoder.prototype.encodeInto()

- extensions/url/00_url.js
> refactor: use primordials for extensions/url

- core/00_primordials.js
- core/internal.d.ts
- extensions/webidl/00_webidl.js
> refactor: use primordials for extensions/webidl

- .github/workflows/ci.yml
- Cargo.lock
- core/Cargo.toml
> chore: upgrade rusty_v8 and serde_v8

- core/internal.d.ts
> chore: add TypedArray to primordials typings

- extensions/broadcast_channel/01_broadcast_channel.js
> refactor: use primordials for extensions/broadcast_channel

- extensions/net/01_net.js
- extensions/net/03_http.js
> refactor: use primordials in extensions/net/

- extensions/net/01_net.js
> fix: primordials in extensions/net

- extensions/web/01_dom_exception.js
- tools/wpt/expectation.json
> fix: align DOMException to webidl spec

- extensions/net/01_net.js
- runtime/js/99_main.js
> fix: primordials in extensions/net and runtime/js

- cli/tests/test/exit_sanitizer.out
- cli/tests/test/fail.out
- cli/tests/test/fail_fast.out
- cli/tests/test/finally_timeout.out
- runtime/js/40_testing.js
This removes a couple of duplicated lines in the test runner.
> refactor(runtime): reduce duplication in test runner
