Cargo.lock, core/Cargo.toml, core/lib.rs, core/module_specifier.rs
Also re-export serde from deno_core, since its now a dependency.
=> Implement Serialize for ModuleSpecifier

cli/dts/lib.deno.ns.d.ts, cli/rt/02_console.js, cli/tests/unit/console_test.ts
This makes evaluation of getters an explicit option called `getters` exposed via InspectOptions.
This option defaults to false fixing the current bad behaviour of inspecting getters which has the potential to cause side effects, when it is false a getter is simply reported as `[Getter]` or `[Getter/Setter]` if its a get/set pair.
Fixes https://github.com/denoland/deno/issues/7153
=> fix(cli/console): only inspect getters with option

cli/rt/02_console.js, cli/tests/unit/console_test.ts
This PR fixes the inspection of functions. The current implementation gets the name of the type of the function from `f.__proto__.constructor.name`, and it throws when the prototype is set to null as described in #7633. This PR checks the prototype before accessing its constructor name and uses the generic name 'Function' if the prototype is not available.
fixes #7633
=> fix(cli/rt/console): fix inspection of Function

cli/dts/lib.deno.window.d.ts, cli/dts/lib.deno.worker.d.ts, cli/rt/99_main.js, cli/tests/subdir/worker_globals.ts, cli/tests/unit/globals_test.ts, cli/tests/workers_test.ts
- `Window`
- `DedicatedWorkerGlobalScope`
- `WorkerGlobalScope`
---
Matches browsers.
Window `globalThis` prototype chain: `Window` -> `EventTarget` -> `Object`.
Worker `globalThis` prototype chain: `DedicatedWorkerGlobalScope` -> `WorkerGlobalScope` -> `EventTarget` -> `Object`.
```ts
console.log(globalThis);
// Before:
// { ... }
// After:
// Window { ... }
```
Use the following to [detect a web worker environment](https://stackoverflow.com/questions/7931182/reliably-detect-if-the-script-is-executing-in-a-web-worker#answer-18002694):
```ts
if (globalThis.WorkerGlobalScope && globalThis instanceof WorkerGlobalScope) {
// ...
}
```
=> fix(cli/rt/main): Add global interface objects

cli/info.rs, cli/main.rs, cli/media_type.rs, cli/module_graph2.rs, cli/specifier_handler.rs, cli/tests/022_info_flag_script.out, cli/tests/049_info_flag_script_jsx.out, cli/tests/054_info_local_imports.out, cli/tests/055_info_file_json.out, cli/tests/cafile_info.ts.out, cli/tests/info_recursive_imports_test.out
This PR moves `deno info` over to the new module graph.
A couple of minor behavioural changes:
* The ordering of dependencies when displayed was not deterministic, as it relied upon the insertion in the module graph, which varied with the two.  Sort dependencies are not sorted.
* There is a line between the module information and the display of the tree. I can revert it, but I found it a lot clearer when viewing the display.
* The JSON serialisation now is ordered with the fields alphabetically, instead of the arbitrary order.
* Type only dependencies are reflected in the dependency tree (things such a `@deno-types`, `X-TypeScript-Types` and the triple slash types reference in JS files), as these are present in "natively" in the new module graph and are required to type check the code.
=> refactor(cli): move info subcommand over to new module graph

cli/colors.rs, cli/disk_cache.rs, cli/flags.rs, cli/http_cache.rs, cli/http_util.rs, cli/main.rs, cli/media_type.rs, cli/module_graph.rs, cli/ops/io.rs, cli/ops/tty.rs, cli/permissions.rs, cli/worker.rs
I noticed that several modules in `cli/main.rs` where `pub` when we don't currently expect anyone to consume the cli crate at the moment.  Removing those public modules resulted in exposing a lot of dead code that was be obfuscated by the public modules.  That code has been removed in this PR.
=> chore(cli): remove dead code

cli/dts/lib.deno.shared_globals.d.ts, cli/dts/lib.deno.window.d.ts, cli/rt/41_prompt.js, cli/rt/99_main.js, cli/tests/066_prompt.ts, cli/tests/066_prompt.ts.out, cli/tests/integration_tests.rs
This PR adds `alert`, `confirm`, and `prompt` functions from [web standards](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#user-prompts).
You can write simple interaction script like the below with this change.
```ts
const name = prompt('What is your name?');
console.log(`Hello ${name}!`);
```
```console
$ ./target/debug/deno run test.ts
What is your name? John
Hello John!
```
Maybe these features are not so important for advanced users, but I think these could be very helpful for beginners of Deno or learners of the language.
---
closes #4257
=> feat: add alert, confirm, and prompt

cli/tests/unit/url_test.ts, op_crates/web/11_url.js
Moves this step to `encodePathname()` so it affect the setter as well. I'm solidifying this encoder before I look at #7929.
=> fix(op_crates/web/url): Apply backslash replacement to the pathname setter

cli/checksum.rs, cli/diagnostics.rs, cli/js.rs, cli/main.rs, cli/media_type.rs, cli/module_graph.rs, cli/module_graph2.rs, cli/tests/tsc2/file_main.ts, cli/tests/tsc2/https_deno.land-x-a.ts, cli/tests/tsc2/https_deno.land-x-b.ts, cli/tests/tsc2/https_deno.land-x-mod.ts, cli/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc2.rs, core/error.rs
This is the last of the "new" infrastructure that will unblock being able to move everything over.
I will do a subsequent PR based on this to actually move something else over the requires the TS compiler.
=> refactor(cli): add tsc2

cli/repl.rs
This extracts prelude injection into a helper function and moves the prelude string literal into a top level static string to help trim some of the fat out of the run function.
=> refactor(cli/repl): clean up prelude injection

cli/test_runner.rs, cli/tests/deno_test_unresolved_promise.out, cli/tests/integration_tests.rs, cli/tests/test_unresolved_promise.js
This commit fixes test runner by awaitning "Deno.runTests()" call,
which ensures proper error is returned when there's an unresolved
promise that's being awaited.
Fixes https://github.com/denoland/deno/issues/7088
=> fix(test): return error when awaiting unresolved promise

cli/dts/lib.deno.ns.d.ts
Fixes some copy & paste typos in the definition of `readTextFile` and `readTextFileSync`
=> fix(types): typos in descriptions of readTextFile(Sync)

cli/rt/01_colors.js, cli/rt/02_console.js, cli/rt/40_testing.js
This PR adds the ability for users to inspect items stylized with ANSI colors regardless of the value of `Deno.noColor` - for example,
```js
// Assumes that Deno.noColor is "true"
// Old behavior
Deno.inspect({ that: "is a object" }, { colors: true }) // { that: "is a object" }
// New behavior
Deno.inspect({ that: "is a object" }, { colors: true }) // { that: \x1b[32m"is a object"\x1b[39m }
```
Considerations:
=> feat(cli/console): inspect with colors regardless of Deno.noColor

cli/repl.rs, cli/rt/01_colors.js, cli/rt/02_console.js, cli/rt/40_testing.js
Originally landed in https://github.com/denoland/deno/pull/7778
Reverted in #7973
Fix from #7975
=> Reland feat(cli/console): inspect with colors regardless of Deno.noColor

cli/file_fetcher.rs, cli/module_graph2.rs, cli/specifier_handler.rs, cli/tests/017_import_redirect_info.out, cli/tests/integration_tests.rs
Fixes issues where both `--no-check` and `deno info` do not currently handle redirects.
=> fix(cli): ModuleGraph2 properly handles redirects

cli/dts/lib.deno.unstable.d.ts, cli/ops/timers.rs, cli/rt/11_timers.js, cli/rt/90_deno_ns.js, cli/tests/unit/timers_test.ts
As discussed in the Discord server, this adds the `sleepSync` op to the `Deno` namespace.
=> feat(cli/ops): add the sleep_sync op

core/lib.rs, core/runtime.rs
Make JSRuntime::new() accept a custom v8::CreateParams object to tune
the v8::Isolate it creates.
Subsumes the functionality of HeapLimits, which I therefore removed.
=> refactor(core): more control over isolate creation

cli/lint.rs, cli/tests/lint/expected_quiet.out
After upgrading deno_lint to 0.2.4, there are hints in some rules that should be displayed alongside the error.
Ref https://github.com/denoland/deno_lint/pull/411
CC @magurotuna
=> refactor(lint): show hint for lint errors

std/io/ioutil_test.ts
This replaces a case of a temp file in the working tree with a tempfile in a real temporary directory avoiding cwpollution of the working directory.
Closes https://github.com/denoland/deno/issues/8018.
=> test(std/io): use a real tempdir

cli/repl.rs, cli/tests/integration_tests.rs
This writes all evaluaton results to stdout regardless if the result is an error or not.
This matches the behavior of other read-eval-print-loops like Node.
Resolves https://github.com/denoland/deno/issues/7849
=> fix(cli/repl): write all results to stdout

cli/repl.rs
This changes the behavior of keyboard interrupts (ctrl+c) to continue, clearing the current line instead of exiting.
Exit can still be done with ctrl+d or by calling close().
=> fix(cli/repl): keyboard interrupt should continue

std/datetime/README.md
This PR adds the documents of `toIMF`, `isLeap`, `difference`, and constants to `std/datetime/README.md`.
=> docs(std/datetime): document toIMF, isLeap, difference, and constants

std/path/mod.ts, std/path/posix.ts, std/path/to_file_url_test.ts, std/path/win32.ts
=> feat(std/path): Add toFileUrl()

cli/dts/lib.deno.ns.d.ts
I believe this description was erroneous. Correct me if I'm wrong.
=> fix(docs): readTextFile / readTextFileSync throws when reading directory

cli/tests/unit/fetch_test.ts, op_crates/fetch/26_fetch.js
Currently Body.body is implemented as `ReadableStream<ArrayBuffer>` but according to spec it should be `ReadableStream<Uint8Array>`. This fixes that. This error would have likely been caught by TypeScript (of tsc using JSDoc).
=> fix(op_crates/fetch): Body.body should be stream of Uint8Array

cli/repl.rs, cli/tests/integration_tests.rs
This ignores brace pairs until a literal sequence has been finished when validating readline input.
Fixes #7978 
Fixes #8034
=> fix(cli/repl): ignore pair matching inside literals

cli/tests/unit/text_encoding_test.ts, op_crates/web/08_text_encoding.js, op_crates/web/text_encoding_test.js
Throw the same error type as Chromium does.
Discussed in #8003.
=> fix(op_crates/web): Change TypeError to RangeError

cli/dts/lib.deno.ns.d.ts, cli/rt/30_files.js
This changes the rid of Deno.stdin, Deno.stdout, Deno.stderr from a mutable property into a getter to match the rid semantics of Deno.File.
=> fix(cli): use rid getter for stdio

cli/tests/unit/text_encoding_test.ts, op_crates/web/08_text_encoding.js, op_crates/web/text_encoding_test.js
Instead of modifying input, return error message with original input.
Edited original test case for TextDecoder a little.
Closes #8003
=> fix(op_crates/web): TextEncoder error message with original input

std/wasi/snapshot_preview1_test.ts
This fast-forwards wasi-test-suite a couple of commits.
- Removed duplicate, or near duplicate tests with not much additional value.
- Other tests have been merged to reduce the number of modules to make tests topical to the syscall that is being tested.
=> test(std/wasi): reduce test duplication

cli/flags.rs, cli/fmt.rs, cli/lint.rs, cli/main.rs
There was not really a need for this PR but it was a pain to work with files with `String`s as you have to convert them every time you need to use them. So I went ahead and replaced the `String`s with `PathBuf`s (for the Lint and Fmt subcommands)
=> refactor(cli): use PathBuf instead of String for lint and fmt subcommands

std/testing/README.md, std/testing/asserts.ts, std/testing/asserts_test.ts
This add supports for a new assertion function `assertObjectMatch` which allows to test an `actual` object against an `expected` object subset (i.e. inclusivity, not equality)
**Why ?**
It's often useful to test an object partly without testing the remaining properties (like for web api response, where you might want to only check a few fields).
This function filters out `actual` object with `expected` object subsets keys before calling `assertEquals` (so it's actually a wrapper which acts as a syntaxic sugar).
```ts
const a  = {
foo: true,
bar: true,
baz: {
qux: true
}
}
// Simple assertions
assertObjectMatch(a, {foo: true})  // OK 
assertObjectMatch(a, {bar: true})  // OK
assertObjectMatch(a, {foo: false}) // KO 
// Nested assertions
assertObjectMatch(a, {baz: {qux: true}}) // OK …
```
=> feat(std/testing): Add support for object assertion against object subset 

std/uuid/v5.ts
Another thing: couldn't we be doing `===` for comparing the `typeof value == "string"` and `typeof namespace == "string"` in the `if` statements of the `generate` function?  I was testing out behavior for if it was just to catch fallback for if they were actual string objects like `new String("foo")`, but it's not.
=> typo(jsdoc): `creat` -> `create`

cli/ops/websocket.rs, cli/rt/27_websocket.js
This PR fixes #7935 . The `WebSocket` will only add the header if it's not empty.
=> fix(cli/rt/websockets): Only add Sec-WebSocket-Protocol if it's not empty

docs/getting_started/debugging_your_code.md, std/http/README.md
https://github.com/denoland/deno/pull/5226 changed `std/http/file_server.ts` default port value from `4500` to `4507`.
https://github.com/denoland/deno/blob/23df1c563efee65e6d549308ed0671a9e2933c05/std/http/file_server.ts#L326
This PR fixes `curl` command example [here](https://deno.land/manual@v1.4.6/getting_started/debugging_your_code#chrome-devtools) and `stdout` output in [std/http/README.md](https://github.com/denoland/deno/tree/master/std/http#file-server)
=> fix: command examples use outdated default file_server port

cli/flags.rs, cli/main.rs, cli/tests/integration_tests.rs, docs/tools/linter.md
This commit stabilizes "deno lint" by removing
the need to pass --unstable flag.
--unstable is still required when using --json flag.
Closes #7983
=> feat(lint): stabilize "deno lint" subcommand

cli/module_graph2.rs, cli/tsc.rs, cli/tsc_config.rs
Closes #7326.
Closes #7947, as code written for stable is once again compatible with `--unstable`. Discussion: I strongly feel we should maintain this property, even if it means going straight to stable for future changes like this. Code written for `--unstable` is by design incompatible with stable -- having incompatibilities going the opposite way as well splits the ecosystem in half, generating a lot of headache and noise. Better to have everyone adapt at once.
=> BREAKING(cli/tsc): Enable isolatedModules by default

cli/main.rs, cli/module_graph2.rs, cli/tests/bundle.test.out, cli/tests/bundle_dynamic_import.ts, cli/tests/integration_tests.rs, cli/tests/lock_check_err_with_bundle.out, cli/tsc.rs, cli/tsc/99_main_compiler.js
Currently builds on #7996, will rebase once that is landed.
=> refactor(cli): move bundle check to new infrastructure

std/wasi/snapshot_preview1.ts, std/wasi/snapshot_preview1_test.ts
Disallow path_open to open paths outside of the dirfd that is being accessed.
=> fix(std/wasi): disallow path_open outside of pre-opened dirfd

std/wasi/README.md
This marks sched_yield as implemented, it is a no-op but will probably always be and we have passing tests for it.
=> docs(std/wasi): mark sched_yield as implemented

cli/tests/tsc2/file_exportc.ts, cli/tests/tsc2/file_reexports.ts, cli/tests/tsc2/https_deno.land-x-c.d.ts, cli/tests/tsc2/https_deno.land-x-c.js, cli/tsc2.rs
Adds a test which verifies that #5935 is fixed.
=> test(cli): ensure modules can export typed JS files

cli/main.rs, cli/module_graph2.rs
This commit changes how "deno run --watch" is implemented
by migrating to use ModuleGraph2.
Closes https://github.com/denoland/deno/issues/8080
=> refactor(run): use new module graph for run --watch

cli/module_graph2.rs, cli/tests/cache_extensionless.out, cli/tests/cache_random_extension.out, cli/tests/integration_tests.rs, cli/tests/subdir/no_js_ext, cli/tsc2.rs, test_util/src/lib.rs
tsc doesn't like "extensionless" root modules (or ones with extensions that aren't what it expects).  So when a module is a root module, we have to compare it resolved media type with what the media type looks like just based on its string value, and if they don't match, we have to remap it to something `tsc` won't complain about.
This partially fixes #8024 and #8106, but exposes two other problems.  One is already raised with #8111 and I will raise another (which is that if don't have `checkJs` on, `tsc` does not emit further dependencies that are emittable, and result in the file being not emitted).
=> fix(cli): properly handle roots with extensions that don't match media types

cli/tests/044_bad_resource.ts, cli/tests/044_bad_resource.ts.out, cli/tests/073_worker_error.ts.out, cli/tests/074_worker_nested_error.ts.out, cli/tests/async_error.ts.out, cli/tests/compiler_js_error.ts.out, cli/tests/error_012_bad_dynamic_import_specifier.ts.out, core/runtime.rs, std/examples/xeval_test.ts
Closes #4879.
```ts
Promise.reject(new Error("foo"));
// Before:
// Uncaught Error: foo
// ...
// After:
// Uncaught (in promise) Error: foo
// ...
```
=> fix(core/runtime): Indicate exceptions in promises

cli/flags.rs, cli/main.rs, cli/tests/integration_tests.rs, docs/tools/linter.md
This reverts commit c5c48f845a4d25f064c4388fcdd4295317edf155.
Reverts #8075, after further discussion we've decided that linter shouldn't be stabilised yet. We'll try to stabilise it for `1.6.0`.
=> Revert "feat(lint): stabilize "deno lint" subcommand (#8075)"

std/http/file_server.ts, std/http/file_server_test.ts
=> fix(std/http/file_server): File server should ignore query params

cli/tests/unit/request_test.ts, op_crates/fetch/26_fetch.js
Ensure `Request.method` to be the default value (`GET`) if `init.method` is not defined, which follows browser's behavior.
Originally sindresorhus/ky#292
```ts
// Before this PR
console.log(new Request('', { method:undefined }).method) // undefined
// After this PR
console.log(new Request('', { method:undefined }).method) // 'GET'
```
=> fix(op_crates/fetch): ensure Request.method to use the default value if not defined

std/wasi/snapshot_preview1_test.ts
This brings in revised tests for clock_time_get from upstream and re-enables them.
This revision of these tests allow for lower precision clocks (we only provide millisecond precision, and that is conformant but my previous tests for this in the upstream test suite were a bit more aggressive).
=> test(std/wasi): re-enable clock_time_get tests

cli/bench/main.rs, test_util/src/lib.rs
This adds a `deno bundle --no-check` benchmark that can be compared with the `bundle` benchmark.
=> chore: add bundle_no_check benchmark

cli/rt/27_websocket.js, cli/tests/unit/event_test.ts, op_crates/web/01_event.js
Fixes #8073 
New output using the example in the issue:
```js
ErrorEvent {
bubbles: false,
cancelable: false,
composed: false,
currentTarget: null,
defaultPrevented: false,
eventPhase: 0,
target: null,
timeStamp: 1603532762591,
type: "error",
message: "",
filename: "",
lineno: 0,
colno: 0,
error: null
}
```
=> fix(op_crates/web): Expose event properties in console output

cli/rt/30_fs.js, cli/tests/unit/mkdir_test.ts
fixes #8036 
Ensure paths created by `URL('../path')` are handled in `mkdir`.
=> fix(cli/rt): handle URL paths in mkdir

cli/diagnostics.rs, cli/main.rs, cli/module_graph2.rs, cli/op_fetch_asset.rs, cli/program_state.rs, cli/tests/tsc2/file_libref.ts, cli/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc2.rs
=> fix(cli): restore tripleslash lib refs support

std/wasi/snapshot_preview1.ts
A stray `console.log` call made it into path_open which should have been reverted in #8078 , it was only meant for debugging on the CI.
=> fix(std/wasi): remove stray console.log call

cli/repl.rs, cli/tests/integration_tests.rs
Fixes #8150
Previously, entering a single ']' would cause repl to forever accepting new lines, due to that `ValidationResult::Invalid` would actually be consumed by the editor itself while continue building the lines. Instead we should mark it as `Valid` and send the bad input for evaluation to get the proper error from V8.
* Before:
```
> ]
(you can keep entering new line here, and it will never consume input
until you Ctrl-C)
```
* After:
```
> ]
Uncaught SyntaxError: Unexpected token ']'
>
```
=> fix(repl): don't hang on unpaired braces

cli/rt/41_prompt.js, cli/tests/066_prompt.ts, cli/tests/066_prompt.ts.out, cli/tests/integration_tests.rs
Fixes issue #8146
The test case seems to check the Windows EOL "\r\n", however this is an illusion because somehow the test runner already translates the Windows into Unix EOL. Have tested the functionality interactively and had to remove the `isatty` return null to do so.
=> fix(prompt): prompt works with windows eol and eof (#8146)

cli/fmt.rs, cli/fs.rs, cli/installer.rs, cli/ops/fs.rs, cli/tsc.rs, cli/tsc_config.rs
Fixes https://discord.com/channels/684898665143206084/689420767620104201/770329467436400710.
We strip this prefix for `Deno.realPath()`, no reason not to do it for pretty diagnostics.
=> fix(cli/fmt): Strip "\\?\" prefix when displaying Windows paths

cli/rt/90_deno_ns.js
These APIs were stabilized in 1.5.0, but were
never added to the "stable" Deno namespace. This
commit fixes that.
Fixes https://github.com/denoland/deno/issues/8185
CC @caspervonb
=> fix: make Deno.fsync(), Deno.fdatasync() stable

core/error.rs, core/runtime.rs
The display is for debug primarily, not writing to a file or something.
=> fix(core/error): Remove extra newline from JsError::fmt()

cli/permissions.rs
Remove unused/illogical `From` implementations on `PermissionState`. It also seems like `UnaryPermissions::global_state` was mistakenly renamed to `program_state`.
=> refactor(cli/permissions): Cleanup Flags to Permissions conversion

cli/tests/unit/text_encoding_test.ts, op_crates/web/08_text_encoding.js
Make TextEncoder behave like the browser's TextEncoder if the user passed a non-string and add a test for it, uses the fix 
suggested by @kitsonk
Fixes: https://github.com/denoland/deno/issues/8201
As with https://github.com/denoland/deno/pull/8205 please be "brutal" with me and give me any feedback that will make future contributions easier from the project's side :]
=> fix(encoding): make textencoder work with forced non-strings

cli/build.rs, cli/flags.rs, cli/version.rs
This PR adds the git commit hash and build target to long version output (`--version`) as suggested in #6037. The output now looks like the below:
```shellsession
$ ./target/debug/deno --version
deno 1.4.6 (0dcdc5e)
target x86_64-apple-darwin
v8 8.7.220.3
typescript 4.0.3
```
---
fixes #6037
=> feat(cli): add commit hash and target to long_version output

cli/tests/unit/event_target_test.ts, op_crates/web/01_event.js
Lint, format and test passes.
This is my first attempt since the rewrite/refactor to contribute code to Deno 🎉 
I want to contribute most of the tests I've been adding in Node and work on some other stuff.
Note that I've found the behaviour of running tests pretty confusing:
- I couldn't find a document explaining how to run the tests and had to look in CI, clicking "contributing" points to the style guide.
- When running a single test it failed with an error - it would _probably_ make sense for the deno binary built to add `--unstable` automatically to the unit tests somehow? In Node we have a mechanism where the first line of the file can be a comment indicating what flags to pass like `// --expose-internals`
- Running the linter/formatter resulted in a weird "OSError: [Errno 2] No such …
=> tests(cli): add event target tests

std/wasi/README.md, std/wasi/snapshot_preview1.ts, std/wasi/snapshot_preview1_test.ts, std/wasi/snapshot_preview1_test_runner.ts
This adds a start method to the Context to make starting a command less tedious and yield consistent errors.
Manually setting the memory is still valid for more complex scenarios, just undocumented for the time being (haven't decided yet if it will be public or not).
=> feat(std/wasi): add start method to Context

cli/main.rs, cli/program_state.rs, cli/worker.rs
This commit removes ProgramState::permissions field.
Having permissions parsed from CLI flags stored on globally
accessible state object made it easy to mistakenly use these
permissions in situations which required "runtime" permissions.
CC @kitsonk
=> refactor(cli): remove ProgramState::permissions

op_crates/web/02_abort_signal.js, op_crates/web/abort_controller_test.js
Currently, `AbortSignal` implements `onabort` in a non spec-compliant way 
.
This causes a timing bug as event listeners can be added in arbitrary orders.
This PR reuses the existing listeners machinery rather than the ad-hoc event handler process - fixing the timing bug.
I have included a test - though the tests for AbortController are weird and in a different format from the EventTarget tests.
(I have a few more ideas of things to fix, but I'll try to take this a few at a time - since the first two PRs I made were merged and the promise hooks one will probably take a bit since it's bigger - I figured I'd follow up with 1-2 more at a time :])
=> fix(web): make onabort event handler web compatible

cli/rt/41_prompt.js, core/bindings.rs
`Deno.stdout.writeSync(new TextEncoder().encode(str))` doesn't seem working for non-ascii characters on windows, but `Deno.core.print(str)` does seem working. See the comment https://github.com/denoland/deno/issues/8179#issuecomment-719431130 .
So this causes the issue #8179.
This PR replaced the use of `Deno.stdout.writeSync` in prompt with `Deno.core.print` and avoided the issue.
I checked the fix on window server 2019 machine.
fixes #8179
=> fix(prompt): fix prompt output of non-ascii characters on windows

std/node/querystring.ts
Add missing JSDoc for `std/node/querystring.ts`
Related: #7487
=> docs(std/node/querystring): add missing JSDoc

cli/repl.rs
this pull request fixes syntax highlighting by doing so:
1. doesn't highlight numbers between letters like `Uint8Array`
1. highlight binary numbes like `0b10001` and don't highlight invalid ones
1. highlight octal numbes like `0o707` and don't highlight invalid ones
1. highlight hexadecimal numbes like `0xfff` and don't highlight invalid ones
1. highlight keywords `this`, `NaN` & `Infinity`
before:
after:
=> fix(cli/repl): Fixing syntax highlighting

core/ops.rs, core/resources.rs, core/runtime.rs
A while ago I started using `deno_core` and struggled with the lack of documentation. Fortunately I got excellent explanations from the developers on Discord, so I thought it might be a good time to contribute back.
I focused the documentation on the parts that I considered important to get a basic example in `deno_core` working. So there are still more APIs to be documented, but at this time I don't have enough knowledge to do that.
There are probably quite a few concepts that can be worded/explained better, so feel free to give feedback!
-----
By the way, I had some trouble running the Python scripts `format.py` and `lint.py` on Windows.
<details>
<summary>Python</summary>
First issue:
```
Traceback (most recent call last):
File "format.py", line 89, in <module>
sys.exit(main())
File …
```
=> docs(core): concepts around runtime, ops and resources

docs/getting_started/permissions.md
Conference website: https://speakeasyjs.com/
Markdown: https://github.com/trivikr/deno/blob/add-speakeasy-js-conf-link/docs/getting_started/permissions.md
=> docs: add Deno security model conference video link

op_crates/web/02_abort_signal.js, op_crates/web/abort_controller_test.js
Currently, AbortSignal implements onabort in a non spec-compliant way
Event handlers need to be defined on the protoype, this is also applies to other event handlers in Deno (like workers/sockets onmessage/messageerror etc).
I tried extracting the logic to a function so it's easier to reuse in the future, but I have no idea how to `import` things into the file (init makes a snapshot of these but in that flow web_util doesn't load first), I noticed other code is simply duplicated and decided I am not familiar enough in the code to change how JS loads :D 
So I just fixed this in AbortSignal (and added a test).
cc @kitsonk :]
=> fix(op_crates/web): define abort event handler on prototype

std/node/buffer.ts, std/node/global.ts, std/node/process.ts
This updates the Node.js `process` and `Buffer` shims to only define their global names when importing `std/node/global`.
This makes it possible to import these libraries without causing global mutations.
I have left the `import './global.ts'` in `module.ts` though as that makes sense to keep for the `createRequire` use cases for now and to avoid a breaking change for those use cases.
This is a breaking change for importers that only import buffer or process though.
=> feat: only define Node.js globals when loading std/node/global

tools/README.md
This adds a quick little note about using cargo run to run deno, which I believe would be the preferred way in most cases to ensure up to date linting rules etc.
=> docs(tools): add a little note about cargo run

cli/module_graph.rs, cli/tests/module_graph/file_tests-c-mod.ts, cli/tests/module_graph/file_tests-diag.ts
=> fix(cli): do not write tsbuildinfo when diagnostics are emitted

.gitmodules
`third_party/` is a git submodule pointing to `deno_third_party` repository. The git history of that repo is quite heavy as it historically contained `typescript`, `node_modules` and `python_packages` directories, but now there are only 11 binaries in there. Setting this attribute should speed up fresh clones.
=> build: use shallow clone of third_party

cli/module_graph.rs
This allows for `Deno.compile()` to have the option `{ declaration: true }` to work.
Fixes #8289
=> fix(cli): allow declaration emits for Deno.compile()

cli/dts/lib.deno.unstable.d.ts, cli/tests/compiler_api_test.ts
=> fix(cli): allow setting of importsNotUsedAsValues in Deno.compile()

.dprintrc.json, tools/format.js
Explicitly pass path to config while when invoking `dprint` in `tools/format.js`.
This is completely cosmetic change. Done because `.dprintrc.json` wasn't
referenced anywhere, unlike `.rustfmt.toml` which can also be picked up
automatically.
=> chore: reference dprint config file in format script

std/fs/eol.ts
I replaced `filter` with `some`.
We don't need to investigate all of the items in array
=> refactor(std): improve performance by using some instead filter method

cli/rt/01_web_util.js, cli/rt/27_websocket.js, cli/tests/websocket_test.ts, op_crates/web/02_abort_signal.js
This fix is similar to https://github.com/denoland/deno/pull/8230 but for `WebSocket`, just like `AbortSignal`s websocket's `onmessage/onclose/onerror/onopen` are HTML "event handlers" which means they have very particular order requirements.
Before this PRs event handlers were always fired before event listeners. Now they are fired in the correct order according to the spec and a test was added to ensure that for `onmessage`. I am happy to add more tests if you want but I didn't want to add lots of I/O causing tests.
I'm trying to keep my PRs small - but I'd like to follow up on this with a similar fix for workers and with unit tests for `web_utils`.
=> fix(websocket) correct DOM handler order

cli/rt/11_workers.js, cli/tests/workers_test.ts
Hey again :]
This is a similar fix to https://github.com/denoland/deno/pull/8320 and https://github.com/denoland/deno/pull/8264 for Workers.
After this - I want to add more tests and find something small to contribute that will force me to write a bit of rust (which as you can probably tell from https://github.com/denoland/deno/pull/8209 I am not great at).
I also want to add some AbortSignal improvements we have in node that improve developer experience and I have some safety concerns regarding cancellation (related to the email we talked in @ry) - though I want to wait for TC39 to meet next week and see if we have something from them first.
=> fix(web/worker) define event handlers in DOM order

op_crates/web/01_event.js, op_crates/web/event_test.js
Basically, I wanted to ask myself "What is the most esoteric spec-required property of Event that I know?" and then fixed it in Deno.
Props goes to user Exe-Boss who found this bug in Node (in another, unrelated PR I did) ^^
(Added a test, ran in master and it fails, ran linter formatter etc)
=> fix(op_crates/web) make isTrusted not constructable

cli/tests/unit/filereader_test.ts, op_crates/web/21_filereader.js
Just like AbortSignal, WebSocket and Worker the event handler order of `FileReader` is currently incorrect in Deno.
This is the same fix as https://github.com/denoland/deno/pull/8334 but for FileReader's events :]
As a bonus, FileReader objects are now smaller (though I doubt FileReader is Deno's performant File API anyway :])
=> fix(op_crates/web) correct filereader event handler order

cli/fmt.rs, cli/lint.rs
=> fix(cli): don't walk the subdirectory twice when using the `--ignore` flag

core/bindings.rs, core/runtime.rs
This commit changes how pending promise exceptions are stored
in JsRuntime by using global handle to promise instead of its
identity hash.
Ref https://github.com/denoland/deno/issues/7969
=> refactor(core): don't depend on get_identity_hash for promises

std/http/_io.ts
Fixes #8339.
`writeChunkedBody` requires flushing the writer after each written chunk. This was not possible with the previous function signature that required a `Deno.Writer` which does not have a `.flush` method. Since `writeChunkedBody` was called with a `BufWriter` (which implements `Deno.Writer`), the function signature was updated to require a `BufWriter` instead. It is also no longer necessary to wrap the existing `BufWriter` `w` in another `BufWriter` `writer = BufWriter.create(w)`.
A minimal reproduction may be found here: https://github.com/denoland/deno/issues/8339#issuecomment-725601429
=> fix(std): Flush individual chunks in HTTP chunked encoding

std/fs/copy.ts
By the Deno [style guide](https://github.com/denoland/deno/blob/master/docs/contributing/style_guide.md)
I moved 4th arg of `ensureValidCopy` and `ensureValidCopySync` to options arg
=> refactor(std): moved isCopyFolder to options

std/_util/os.ts, std/fs/copy.ts, std/fs/ensure_symlink.ts, std/fs/expand_glob.ts, std/node/_url.ts, std/node/module.ts, std/path/_constants.ts, std/path/glob.ts, std/path/mod.ts, std/path/separator.ts
We had a lot of `const isWindows = Deno.build.os === "windows";` so I removed all and use `os` util
=> feat: os util

cli/fmt.rs, cli/fs.rs, cli/lint.rs, cli/test_runner.rs
Fixes #8374 
~~I'll fix more and add tests, so WIP for now.~~ Done
=> fix(fmt, lint): Make sure that target paths are not directory

cli/dts/lib.deno.ns.d.ts
I noticed that the `Version` interface was not exported. Thus, https://doc.deno.land/builtin/stable#Deno.version would not show its properties.
Since the interface `Version` is only used a single time, I inlined the properties - similar to [`Deno.build`](https://doc.deno.land/builtin/stable#Deno.build).
Also added documentation for the properties.
=> Improve Deno.version type declaration

std/_util/deep_assign.ts
PR title is clear :) 
`assert.ts` is a sibling of `deep_assign.ts`
=> fix: remove unnecessary back direction for import

std/node/events.ts, std/node/events_test.ts
Previous implementation caused an extensability issue in which classes that inherited from EventEmitter and overwrote the method `on` and `addListener` would get stuck in an infinite loop since `on` calls `addListener` internally instead of being an alias for it.
Long story short, this is fixed.
=> [fix]: std/node/events - Fix event extendability

cli/tests/permission_test.ts
See #8397.
There's no `printf.exe` on Windows (nor `echo.exe` - `echo` is a built-in command in `cmd.exe` and an alias for the `Write-Output` cmdlet in `powershell.exe`).
=> fix(cli/tests): Execute Windows binary in run permission test

std/io/streams.ts, std/io/streams_test.ts
we should also rename `fromStreamWriter` & `fromStreamReader` to `writerFromStreamWriter` & `readerFromStreamReader`.
Going to add tests later
=> feat(std/io): ReadableStream from AsyncIterator & WritableStream from Writer

cli/fmt_errors.rs, cli/ops/worker_host.rs, cli/source_maps.rs, cli/worker.rs
This commit renames "fmt_errors::JsError" to "PrettyJsError"
to avoid confusion with "deno_core::JsError".
Consequently "CoreJsError" aliases to "deno_core::JsError"
were removed.
Additionally source mapping step has been removed from
"PrettyJsError::create" to better separate domains.
=> refactor(cli): rename fmt_errors::JsError to PrettyJsError

std/http/file_server.ts, std/testing/_diff.ts, std/testing/asserts.ts
includes:
- http/file_server.ts
- testing/_diff.ts
- testing/asserts.ts
Relates to #7487
=> docs(std): add missing jsdoc comments to exported functions

cli/ops/worker_host.rs
This commit simplifies code responsible for serialization
of web worker events. Instead of using "PrettyJsError"
it's enough to downcast to "deno_core::JsError", making
the code less specific to cli/ implementation.
=> refactor(cli): worker event serialization

std/examples/cat_test.ts, std/examples/catj_test.ts, std/examples/chat/server_test.ts, std/examples/colors_test.ts, std/examples/curl_test.ts, std/examples/echo_server_test.ts, std/examples/test.ts, std/examples/welcome_test.ts, std/examples/xeval_test.ts, std/fs/empty_dir_test.ts, std/fs/exists_test.ts, std/fs/expand_glob_test.ts, std/http/file_server_test.ts, std/http/racing_server_test.ts, std/http/server_test.ts
This commit makes output of std/ tests less noisy
by passing "--quiet" flag to Deno subprocesses run
as part of test suite.
=> test(std): make test output less noisy

cli/worker.rs, core/runtime.rs
This commit adds "get_error_class_fn" field to "RuntimeOptions"
struct in order to unify configuration of "JsRuntime".
=> refactor(core): accept get_error_class_fn in RuntimeOptions

std/path/posix.ts, std/path/win32.ts
Add missing JSDoc for std/path/posix.ts and std/path/win32.ts
Related to #7487
=> docs(std/path): add JSDoc

cli/flags.rs, cli/tests/integration_tests.rs, docs/testing.md
=> chore(cli/flags): Rename --failfast to --fail-fast

Cargo.lock, cli/module_graph.rs, cli/tests/bundle/file_tests-fixture15.ts, cli/tests/bundle/fixture15.out
Fixes #8161
(Or actually will fix when https://github.com/swc-project/swc/issues/1188 is fixed, this is a test case to help ensure it is fixed at the moment)
=> tests(cli): add test for improper unicode encoding

cli/tests/unit/fetch_test.ts, op_crates/fetch/26_fetch.js
This intentionally breaks from spec (but aligns to other server side implementations of `fetch` like Cloudflare Workers).
Closes #8351
Closes #4389
=> fix(op_crates/fetch): `redirect: "manual"` fetch should return `type: "default"` response

cli/tests/test_coverage.out, cli/tests/test_coverage.ts, cli/tools/coverage.rs
Places a newline between non-consecutive lines to improve readability.
Goes towards #7652.
=> feat(test): separator between disjoint lines for coverage report

std/ws/mod.ts
[#7487](https://github.com/denoland/deno/issues/7487)
=> docs(std): add some missing JSDoc ws/mod.ts

cli/lockfile.rs
This commit removes unnecessary conversion into BTreeMap. The value
that gets converted into BTreeMap is _originally_ BTreeMap, so this
conversion is just superfluous.
Additionally, a test is added so that we can make sure the keys in the
emitted lockfile are sorted alphabetically.
=> refactor(cli): Remove unnecessary conversion into BTreeMap

std/encoding/README.md
Ref: https://github.com/denoland/deno/pull/8408#issuecomment-733755022:
> > assuming [05e0760](https://github.com/denoland/deno/commit/05e07600b7b4f3a21052fad89d1655acd489e6a1) is the proper result
> 
> @dsherret @bartlomieju It is not the proper result.
> 
> It breaks the code blocks (includes literal triple ticks in the code bocks), and also improperly nests some code blocks in unrelated list items.
> 
> Visually compare [the intended version](https://github.com/denoland/deno/blob/703aed6a8059646504c17c428cc1cd68d53731be/std/encoding/README.md#stringify) ([703aed6](https://github.com/denoland/deno/commit/703aed6a8059646504c17c428cc1cd68d53731be)) to [the auto-formatted version](https://github.com/denoland/deno/blob/05e07600b7b4f3a21052fad89d1655acd489e6a1/std/encoding/README.md#stringify …
=> fix(std/encoding/csv) Correct readme formatting due to dprint issues

cli/tests/unit/net_test.ts, cli/tests/unit/performance_test.ts, cli/tests/unit/signal_test.ts, cli/tests/unit/test_util.ts, cli/tests/unit/timers_test.ts, cli/tests/unit/tls_test.ts, cli/tests/websocket_test.ts, cli/tests/workers_round_robin_bench.ts, cli/tests/workers_test.ts
Currently we use `createResolvable` which is defined in multiple places instead of importing `deferred` from std.
There are 2 more instances of a `createResolvable` function being created: `cli/rt/06_util.js` & `core/examples/http_bench_bin_ops.js`. Should i rename those to `deferred` for consistency?
=> refactor(cli/tests): replace createResolvable with deferred

cli/tests/integration_tests.rs
Fixes https://github.com/denoland/deno/issues/4262
=> re-enable test_raw_tty

std/http/file_server.ts, std/http/file_server_test.ts
Fix path traversal problem when the "request-URI" does not have a leading slash.
This is possible in some http clients such as curl:
curl --path-as-is localhost:4705 --request-target ../../../..
The file server now returns HTTP 400 when requests lack the leading slash, and are not
absoluteURIs (see https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html).
=> fix(std/http): prevent path traversal

Cargo.lock, cli/Cargo.toml, cli/tests/integration_tests.rs
On OSX and linux I can reproduce the hang reliably by running:
while true; do cargo test -p deno  tty -- --nocapture; done
Sometimes you have to wait a bit, but it shows up eventually.
I never see the hang when running
while true; do cargo test -p deno test_raw_tty  -- --nocapture; done
Therefore I think its related to fork / test runner.
Edit: working now.
Closes #4262
=> fix test_raw_tty hang

docs/linking_to_external_code/import_maps.md
Update docs to reflect current behavior. If trailing slash is not provided, `deno run` will throw error: `Package address targets must end with "/"`.
=> docs(import_maps): Add trailing slash to ./src example

cli/ops/net.rs, cli/tests/unit/net_test.ts
=> fix(cli/ops/net): add write permissions for unixpackets datagrams & unix socket

cli/tests/unit/net_test.ts
Fixes a brittle test that was identified in #8511 after it was merged.
=> chore(tests): fix brittle network permission test

cli/module_graph.rs, cli/tests/076_info_json_deps_order.out, cli/tests/076_info_json_deps_order.ts, cli/tests/integration_tests.rs, core/module_specifier.rs
changed the HashSet used to build the ModuleInfoMap for a BTreeSet to keep the items sorted
Fixes #8458
=> fix(cli): make output of deno info --json deterministic

.github/workflows/ci.yml
This commit updates CI script to publish only "deno"
crate on tags.
Following crates are not automatically published anymore:
- deno_core
- deno_web
- deno_fetch
- deno_crypto
Before this commit creating a new release required to bump
version on all above crates even though in practice they
rarely change.
=> build: publish only "deno" crate on tags

cli/version.rs
Currently canary versioning is described using a `-` between semver & hash. That's incorrect as `-` is for pre releases whereas `+` is for build metadata (as described on the semver spec), which would be more appropriate for canaries.
=> fix(cli/version): canary change pre-release to metadata

std/fs/walk.ts, std/fs/walk_test.ts
=> feat(std/fs): Re-enable "followSymlinks" option in "walk()" API

.github/workflows/ci.yml, cli/flags.rs, cli/main.rs, cli/standalone.rs, cli/tests/integration_tests.rs, cli/tests/standalone_import.ts, cli/tools/installer.rs, cli/worker.rs
Closes #986 
This implements the `deno compile` subcommand. It works be generating a new standalone binary, by appending a bundle of the source file and magic trailer from the current binary. If we find a magic trailer at the end of the the binary, we try to load the bundle that is embedded in the binary, and run it.
```
~/p/g/d/deno ❯❯❯ ./target/debug/deno compile https://deno.land/std/http/file_server.ts file_server
Bundle https://deno.land/std/http/file_server.ts
Check https://deno.land/std/http/file_server.ts
Compile https://deno.land/std/http/file_server.ts
~/p/g/d/deno ❯❯❯ ./file_server 
HTTP server listening on http://0.0.0.0:4507/
```
=> feat: deno compile

cli/tests/integration_tests.rs
Temporarly disabling tests for `--watch` flag which are very flaky.
=> disable flaky watch tests

cli/tools/repl.rs
Resolves #8568.
This just highlights them unconditionally; since they can technically be used as identifiers, the 'correct' way would check for that, but that would pretty much require a full parser.
=> fix(repl): higlight `async` and `of` in REPL

cli/ops/runtime.rs, cli/rt/99_main.js, cli/standalone.rs, cli/tests/integration_tests.rs, cli/tests/standalone_error.ts, cli/web_worker.rs, cli/worker.rs, core/lib.rs, core/runtime.rs
This commit disables source mapping of errors
for standalone binaries. Since applying source
maps relies on using file fetcher infrastructure
it's not feasible to use it for standalone binaries
that are not supposed to use that infrastructure.
Closes https://github.com/denoland/deno/issues/8578
=> fix(compile): disable source mapping of errors

.github/workflows/ci.yml
This will upload canaries before running tests, so canaries are uploaded regardless if the tests are flaky or not.
=> build: upload canaries before tests

std/wasi/snapshot_preview1.ts, std/wasi/snapshot_preview1_test.ts
This adds another entry point to Context called initialize for spinning up style modules.
Node has a similar API: https://nodejs.org/api/wasi.html#wasi_wasi_initialize_instance
For context, reactors are modules that don't have a main function and basically run forever in the background.
=> feat(std/wasi): add support for initializing reactors

std/wasi/snapshot_preview1.ts
This replaces the ternaries in the context constructor with nullish coalescing which is ever so slightly more readable.
=> refactor(std/wasi): prefer nullish coalescing

op_crates/web/01_event.js, op_crates/web/event_test.js
Hey, per the request in https://github.com/denoland/deno/issues/8606
This is this feature https://github.com/whatwg/dom/issues/911 I've implemented the spec I worked on in https://github.com/whatwg/dom/pull/919 and ported one WPT from https://github.com/web-platform-tests/wpt/pull/26472 
Is there a standard/easy way to port/run WPTs in Deno? If not - should I just add them in a separate file?
Fixes: https://github.com/denoland/deno/issues/8606
P.S.
I didn't forget the REPL or promise hooks bug - I've been sick, I feel better and I intend to pick those up (hopefully even tomorrow :])
=> feat(op_crates/web) EventTarget signal support

std/wasi/snapshot_preview1.ts
This renames a couple of identifiers from the ambiguous name "text" to the more explicit textEncoder and textDecoder depending on what they are.
Should have been done in the initial pass to camelCase all the identifiers.
=> refactor(std/wasi): prefer explicit encoder/decoder names

std/encoding/testdata/string.toml, std/encoding/toml.ts, std/encoding/toml_test.ts
* Rewrites toml parser not to use `eval()` (that would probably be a security risk).
* This PR also fixes #8433.
* Adds support for parsing unicode characters (`\uXXXX`, `\UXXXXXX`).
=> fix(std/encoding/toml): Rewrite toml parser not to use eval()

docs/toc.json, docs/tools.md, docs/tools/compiler.md
This PR adds documentation for the new `deno compile` command introduced in PR #8539 and discussed in #986
=> docs(tools): add documentation for deno compile cmd

std/io/bufio.ts, std/io/bufio_test.ts
Fix #7093
Removes "\r" from the end of lines when using `readLines`.
For example for a file containing `"A\r\nB\r\nC"`:
```javascript
let fr = await Deno.open("./file.txt");
for await (let line of readLines(fr)) {
console.log([line]);
}
/* 
Before:
[ "A\r" ]
[ "B\r" ]
[ "C" ]
Now:
[ "A" ]
[ "B" ]
[ "C" ]
*/
```
=> fix(std/bufio): Remove '\r' at the end of Windows lines

cli/flags.rs, cli/main.rs, cli/tools/installer.rs
Currently `Flags.v8_flags` is `Option<Vec<String>>`, but this can be simplified to just `Vec<String>` and checking for `is_empty()`
=> refactor(cli): remove Option from Flags.v8_flags

cli/tests/integration_tests.rs, docs/getting_started/typescript.md, std/tsconfig_test.json
Missed in #8050. Also updates doc surrounding `isolatedModules` and `--no-check`.
=> chore(std): Remove tsconfig_test.json

cli/ops/timers.rs, cli/rt/11_timers.js, cli/rt/40_performance.js
=> (fix): performance.now() should be a minimal op to avoid JSON deserialization overhead

cli/lsp/capabilities.rs, cli/lsp/handlers.rs, cli/lsp/mod.rs, cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
This adds basic `textDocument/completion` handling.
Currently text completions with `TextEdit`s do not work. I have not managed to figure out why though. Until I find the cause I have disabled the `includeCompletionsWithInsertText` TS user preference which should mitigate this.
```ts
function str(s?: Deno.File) {
s.
//  ^- complete here is not as nice as VSCode built in. (optional chaining)
}
```
In the future we should implement `completionItem/resolve` to support `documentation` and `details` field in the `CompletionItem`.
=> feat(lsp): basic support for textDocument/completion

core/gotham_state.rs
This commit adds a test case to core/gotham_state.rs that shows
that type aliases can't be used reliably. Instead wrapper types
should be used.
=> test(core): type aliases in OpState

Cargo.lock, core/Cargo.toml, core/async_cancel.rs, core/async_cell.rs, core/examples/http_bench_bin_ops.rs, core/examples/http_bench_json_ops.rs, core/lib.rs, core/resources2.rs
=> core: add plumbing for canceling ops when closing a resource

cli/tests/unit/fetch_test.ts, op_crates/fetch/lib.rs, test_util/src/lib.rs
Fixes #8576
This issue is related to the case where the fetch response header value is a non-ascii string.
As with the HTTP 301 response, some headers value can contain UTF-8 strings.
So, I simply changed the value as utf-8 string.
If you have a better idea, please give me feedback. :smile_cat:
=> fix(op_crates/fetch): support non-ascii response headers value

cli/lsp/analysis.rs, cli/lsp/config.rs, cli/lsp/mod.rs, cli/lsp/sources.rs, cli/lsp/state.rs, cli/lsp/tsc.rs
Supports specifying an import map in the configuration of a language server client and having that applied to the workspace.
=> feat(lsp): support import maps

Cargo.lock, cli/Cargo.toml, cli/ast.rs
Tokio 0.3 is now part of the dependencies, but only as a dev dependency in deno_doc. The duplication this causes will be resolved once we migrate to tokio 0.3.
=> chore: update swc_ecmascript to 0.15.0

std/io/README.md
Reflect recent name changes for these functions:
- `writerFromStreamWriter` (see [here][0])
- `readerFromStreamReader` (see [here][1])
[0]: https://github.com/denoland/deno/blob/723fbb8f68eeaf6e5c14d9f8ac2c32f986ed60d9/std/io/streams.ts#L4
[1]: https://github.com/denoland/deno/blob/723fbb8f68eeaf6e5c14d9f8ac2c32f986ed60d9/std/io/streams.ts#L17
=> [docs] fix: naming in `std/io` usage example

std/wasi/snapshot_preview1_test.ts
This runs the test runner with --no-check which shaves the time taken down from a bit over 1 minute to 5 seconds.
We still import "snapshot_preview1" file in the test file that prepares the test runner invocations so we still get type checking there, just omitting it in the runner.
=> test(std/wasi): run test runner with --no-check

std/wasi/snapshot_preview1.ts, std/wasi/snapshot_preview1_test.ts
This disallows start and initialize from being called multiple times with the same, or different instances.
Once a context has started, it is bound to that context forever and calls to start/initialize needs to reflect this.
Also; had a look at Node's implementation and this mimicks their start/initialize semantics.
=> fix(std/wasi): disallow multiple starts

docs/tools/repl.md
The keybindings are from upstream rustyline, I was a bit too blind
copying action descriptions and a reference to a issue stuck in to the
description of the ctrl-v binding.
This removes the offending reference.
=> docs(tools/repl): remove irrelevant reference to issue

cli/dts/lib.deno.unstable.d.ts
Resolves #8682 
Removed the function call and matched the style of the rejected console log rather than replacing with a different function call. Happy to change it.
=> Fix(doc): Remove a deprecated function call from docstring in Deno.permissions

cli/dts/lib.deno.ns.d.ts
This PR fix #8731 to remove annotaion about removed function `Deno.dir` like `(see also `Deno.dir("temp")`)`.
=> docs: fix doc to remove annotation about removed function `Deno.dir`

cli/tests/integration_tests.rs
Ref #8571 
Watcher-related tests are so flaky on macOS of GitHub Actions. I'm totally unsure what the cause is. All I can confirm is the performance of macOS instance is kinda worse compared to ubuntu or windows:
https://github.community/t/macos-performance/125281
So I suspect that the flakiness is simply because of performance issues on macOS. In this PR, I'll try to see it.
=> chore(test): increase timeout duration on macOS

docs/getting_started/setup_your_environment.md
Accidentally moved in a54ede099d58e8783c6511ff351aefba160b39d9.
Oops, we missed that.
=> docs(tools): Move setup environment's community paragraph back

cli/lsp/handlers.rs, cli/lsp/mod.rs, cli/lsp/state.rs, cli/lsp/tsc.rs, cli/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
=> refactor(lsp): optimise static assets

cli/tests/integration_tests.rs, cli/tests/stdout_write_all.out, cli/tests/stdout_write_all.ts
This adds an "await all writes" case that would previously dead-lock that has been solved with the new resource table as a regression test (https://github.com/denoland/deno/issues/6840#issuecomment-662569644).
Closes #6840
=> test(cli): ensure await all on stdout does not deadlock

runtime/ops/websocket.rs
@bartlomieju might there be other accidentally left debug prints?
=> fix(runtime/websocket): remove eprintln

cli/disk_cache.rs, cli/fs_util.rs, cli/http_cache.rs
This tries to fix an issue where files in the $DENO_DIR could be in an undermined state, where they are empty, only half written, or otherwise not correct. This issue may arise when multiple Deno processes try to cache the same file simultaneously. We should also consider adding integrity hashes to the files, so we can check if they are are valid when reading them from $DENO_DIR.
=> fix: atomically write files in $DENO_DIR

cli/tests/unit/chown_test.ts
Rewrites `chown_test.ts` to use the GNU `id` command instead of python. This won't work on Windows, but these tests aren't currently run on Windows anyway.
Ref #8254
=> refactor(cli/tests): rewrite chown_test.ts not to depend on python

cli/lsp/language_server.rs, cli/tests/lsp/initialize_request_disabled.json
This PR fixes situations with the lsp, where the extension is disable, but on hover and other requests, there are duplicate values reported to vscode.
=> fix(lsp): respect enable flag for requests

core/examples/http_bench_json_ops.js
Fixes the following runtime error for me when benchmarking:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: Error: Unregistered error class: "Error"
Connection reset by peer (os error 104)
Classes of errors returned from ops should be registered via
Deno.core.registerErrorClass().
at processResponse (deno:core/core.js:219:13)
at Object.jsonOpAsync (deno:core/core.js:240:12)
at async read (http_bench_json_ops.js:29:21)
at async serve (http_bench_json_ops.js:45:19)',
core/examples/http_bench_json_ops.rs:260:28
=> core: fix http_bench_json_ops, register Error

.gitignore
Hot fix for #8861
Preferably this would just write to a temporary directory, `itest` doesn't really want to roll that so I'll follow up with a PR to address the coverage tests as a whole.
=> fix(build): add generated coverage files to gitignore

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js
Provides diagnostics for unresolved modules.
An iteration on this would be to provide a quick fix to do the `deno cache` for non-local modules.
=> fix(lsp): provide diagnostics for unresolved modules

cli/tests/stdout_write_all.out, cli/tests/stdout_write_all.ts
Revisits the test case added in #8802 to be order sensitive.
See @piscisaureus's comment https://github.com/denoland/deno/pull/8802#issuecomment-749333750
=> test(cli): ensure await Promise.all does not race

cli/dts/lib.deno.shared_globals.d.ts, op_crates/web/lib.deno_web.d.ts
`ProgressEvent` is a global that is defined in the web op crate, and used there (including in the TS typings), but the type definition was part of `lib.deno.shared_globals`. This corrects this.
=> chore: move ProgressEvent type to deno.web lib

cli/main.rs, cli/tests/integration_tests.rs, cli/tests/run_coverage.ts, cli/tests/test_run_run_coverage.out, cli/tests/test_run_run_coverage.ts
This adds implicit coverage collection to the run command when a coverage collection directory is set (via an environment variable).
=> feat(cli): collect coverage from the run command

docs/getting_started/webassembly.md
Minor incremental improvement, adds a link back to the relevant section on MDN.
=> docs(webassembly): add a link to mdn documentation

cli/dts/lib.deno.unstable.d.ts, docs/introduction.md
- Improve capitalization in various places
- ~Remove unnecessary line break before long link~ (turns out this is enforced by `dprint`)
- Rework Goals section for grammatical and structural consistency
Also simplify docstring of `kill()` to use `sleep` directly instead of via Python, as initially suggested [here](https://github.com/denoland/deno/issues/8254#issuecomment-749100681).
=> docs(introduction): Improve wording and capitalization

Cargo.lock, cli/Cargo.toml, cli/tests/bundle/fixture02.out, cli/tests/bundle/fixture11.out, cli/tests/bundle/fixture14.out
Closes https://github.com/denoland/deno/issues/8828
Closes https://github.com/denoland/deno/issues/8770
Closes https://github.com/denoland/deno/issues/8746
Closes https://github.com/denoland/deno/issues/8736
Closes https://github.com/denoland/deno/issues/8734
Closes https://github.com/denoland/deno/issues/8725
Closes https://github.com/denoland/deno/issues/8722
Closes https://github.com/denoland/deno/issues/8680
Closes https://github.com/denoland/deno/issues/8679
Closes https://github.com/denoland/deno/issues/8620
Closes https://github.com/denoland/deno/issues/8597
Closes https://github.com/denoland/deno/issues/8545
Closes https://github.com/denoland/deno/issues/8541
Closes https://github.com/denoland/deno/issues/8285
Closes https://github.com/denoland/deno/issues/8211
=> upgrade: dprint, swc_bundler, swc_common, swc_ecmascript

cli/tests/error_024_stack_promise_all.ts, cli/tests/error_024_stack_promise_all.ts.out, core/error.rs
fixes #8871
There was a small bug where we were reporting the wrong index for the failing promise in a `Promise.all` call.
The `error_024_stack_promise_all` test was not robust enough to catch this (more details in #8871).
This PR fixes the bug and updates the test so that the failing promise is at index 1 instead of 0.
=> fix(core/error) Fix incorrect index in Promise.all error reporting

cli/flags.rs, cli/main.rs, cli/tools/installer.rs, runtime/permissions.rs
This PR refactors `cli/flags.rs` and `runtime/permissions.rs ` so that `allow_read`, `allow_write` and `allow_net` themselves will have allowlists.
In the current implementation, the allowlist for the `net` flag is stored in `net_allowlist: Vec<String>` and the presence of `allow-net` flag is stored in `allow_net: bool`. However, if we run deno with `deno run --allow-net=example.com`, `allow_net` will be `false` even though `allow-net` flag is present - which looks confusing to me. The relation between them is as follows:
|command|allow_net|net_allowlist|
|-------|---------|-------------|
|`deno run foo.ts`|`false`|`vec![]`|
|`deno run --allow-net foo.ts`|`true`|`vec![]`|
|`deno run --allow-net=example.com foo.ts`|`false`|`vec!["example.com"]`|
So in this PR, `net_allowlist` is removed …
=> refactor(cli/flags): change allow_read/write/net types from bool to Option<Vec<T>>

cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp/rename_did_open_notification.json, cli/tests/lsp/rename_request.json, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
Related #8643
Currently, the ConfigureRequest (in `cli/tsc/compiler.d.ts`) does not support `tsconfig.json`'s `include/exclude` field.
So the tsserver will rename symbols in only the opened text document or explicitly dependent text document.
=> feat(lsp):  Implement textDocument/rename

runtime/ops/net.rs, runtime/ops/tls.rs, runtime/resolve_addr.rs
This PR does refactoring for `runtime/resolve_addr.rs`.
At first I did it in the other PR (#8790) but I have extracted it as a separate PR to allow #8790 to focus on `Deno.resolveDns` API.
The changes in this PR are:
- to let `resolve_addr` and `resolve_addr_sync` return iterators of `SocketAddr`, not just a single `SocketAddr`. These functions previously called `.next()` on an iterator internally, and returned it, so the callers of these functions had no way of handling other items than the first item in the iterator.  This change allows the caller to decide how to use the returned iterator.
- to use `generic_error` in deno_core instead of `anyhow::Context`. When I worked on #8743, I didn't know there were utility error functions like `generic_error`. 
See also …
=> refactor(runtime): return iterator from resolve_addr

std/http/server.ts
This is resolvable by the consumer. Expose it as a `Promise` instead.
=> fix(std/http): Don't expose ServerRequest::done as Deferred

cli/file_fetcher.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/main.rs, cli/module_graph.rs, cli/ops/runtime_compiler.rs, cli/program_state.rs, cli/specifier_handler.rs, cli/tsc.rs
This adds a command to allow caching of files in the lsp.  For example in VSCode, a command can be created that will effectively do a `deno cache` on the currently open file, fetching all of its dependencies, including using any import map that is configured for the project.
There are a couple things that need to be done with the PR, before landing but raising for visibility.
=> feat(lsp): add cache command

docs/getting_started/setup_your_environment.md
The setup instructions for Vim/Neovim worked with Deno v1.6.0, but not with v1.6.2. :cry: This PR fixes the documentation so that it also works with Deno v1.6.2.
=> docs: Update instructions on how to setup development environment with Vim/Neovim

cli/dts/lib.deno.unstable.d.ts, cli/tests/error_015_dynamic_import_permissions.out, cli/tests/error_worker_permissions_remote.ts.out, cli/tests/unit/permissions_test.ts, docs/runtime/permission_apis.md, runtime/ops/net.rs, runtime/ops/permissions.rs, runtime/ops/tls.rs, runtime/permissions.rs, std/permissions/mod.ts
Allowlist checking already uses hosts but for some reason requests, revokes and the runtime permissions API use URLs.
- BREAKING(`lib.deno.unstable.d.ts`): Change `NetPermissionDescriptor::url` to `NetPermissionDescriptor::host`
- fix(`runtime/permissions`): Don't add whole URLs to the allowlist on request
- fix(`runtime/permissions`): Harden strength semantics (`{ name: "net", host: "127.0.0.1" }` _stronger than_ `{ name: "net", host: "127.0.0.1:8000" }`) for blocklisting
- refactor(`runtime/permissions`): Use tuples for hosts, make the host optional in `Permissions::{query_net, request_net, revoke_net}()`
---
Fixes #7587.
=> BREAKING(unstable): Use hosts for net allowlists

cli/tests/unit/fetch_test.ts, op_crates/fetch/26_fetch.js, test_util/src/lib.rs
Fix bug in regular expression and make the regular expression more
strict.
In a string passed to new RegExp(), '[\t\s]' is identical to '[ts]' and
not `/[\t\s]/`. For that, the backslash needs to be escaped in the
string. Futhermore, `\t` is the tab character and is included in the
special regexp value `\s` so is unnecessary.
That would reduce the RegExp to new RegExp(`^${value}\\s*;?`) but
there's no point in matching 0 or more space characters followed by 0 or
one semi-colons as that will match no matter what follows `value`.
To make it more strict, require one of space, semicolon, or
end-of-string after value.
=> fix(op_crates/fetch): correct regexp for fetch header

test_util/src/lib.rs
Use Tokio's single-threaded scheduler. The hyper server is used as a
point of comparison for the (single-threaded!) benchmarks in cli/bench.
We're not comparing apples to apples if we use the default
multi-threaded scheduler.
This drops the requests/sec from 284k to 130k on my 12 core Ryzen 5
system. That still leaves a 50k gap for us to close. Working on it!
=> fix(test_util): make hyper server single-threaded

.github/workflows/ci.yml
gcloud still depends on python - https://github.com/denoland/deno/runs/1636936462
This reverts commit 5937ee3fba24dac6be99c8cb0b4c9709d4656f71.
=> Revert "ci: don't install python (#8961)"

cli/disk_cache.rs, runtime/permissions.rs
Fixes #8958 
- `permissions.rs`: `check_specifier` no longer assumes a local-file specifier is valid
- `disk_cache.rs`: `get_cache_filename` gracefully handles invalid local-file specifiers
Working on tests now
=> fix: panic on invalid file:// module specifier

Cargo.lock, cli/Cargo.toml, cli/tests/integration_tests.rs, runtime/inspector.rs
Reverts denoland/deno#8894
This added a lot of `hello` messages to the log in tests, and pulled in openssl by importing reqwest directly instead of through `deno_fetch::reqwest`.
=> Revert "fix(inspector): add back list endpoint"

cli/tests/integration_tests.rs, runtime/inspector.rs
The child process kept running and printing "hello" to stdout.
This commit also removes the dependency on reqwest and instead
switches to the re-export from the fetch crate.
Refs commit 1a2e7741c33490d2a91147966019853c6b1d6a48.
Closes #8979
cc @lucacasonato @lperlaki
=> fix(inspector): kill child process after test

docs/contributing.md, std/encoding/testdata/cargo.toml
Quick PR to remove was seems to be obsolete information regarding `third_party`.
=> docs: Remove outdated information about third_party/ directory

cli/file_fetcher.rs, cli/flags.rs, cli/http_util.rs, cli/main.rs, cli/program_state.rs, cli/standalone.rs, cli/tests/integration_tests.rs, cli/tests/standalone_runtime_flags.ts, docs/tools.md, docs/tools/compiler.md, runtime/examples/hello_runtime.rs, runtime/http_util.rs, runtime/ops/fetch.rs, runtime/ops/websocket.rs, runtime/web_worker.rs, runtime/worker.rs
Supports permissions etc for executables created with `deno compile`, by appending serialized `Flags` after the source bundle.
Closes #8656.
=> feat(cli/standalone): Support runtime flags for deno compile

docs/examples/tcp_echo.md
As pointed out by @mk12 in the this pull request https://github.com/denoland/deno/pull/8991 The TCP echo server leaks resources as it does not close the connection. This fixes that bug. This is done in place of his PR as he is unable / unwilling to attempt get the CLA past his employer. I have no such restrictions. There are no tests to cover this as it's an documentation example.
=> docs(example/tcp_echo): fix TCP echo leaking resources

runtime/js/27_websocket.js, runtime/ops/websocket.rs
=> fix(runtime/websocket): respond to ping with pong

std/mime/multipart.ts
Changes `multipat` to `multipart` in the two usages of `multipartFormData()`.
=> chore(std/mime/multipart): fix misspelling of multipartFormData()

cli/tests/wpt.jsonc, op_crates/web/01_event.js, op_crates/web/02_abort_signal.js
=> fix: align AbortSignal to spec using WPT

std/wasi/snapshot_preview1.ts, std/wasi/snapshot_preview1_test.ts
This returns the exit code directly from the start entry point instead of throwing it and making the user handle that specific kind of error which is a bit too convoluted.
As a result the exit status is an implementation detail and has been made internal.
=> BREAKING(std/wasi): return exit code from start

.github/stale.yml
Closes #9035
This PR adds a bit of contextual information to the message text that the stale bot posts on issues:
Before:
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.
After:
> This issue [has been automatically marked as stale](https://probot.github.io/apps/stale/#how-it-works) because it has not had recent activity. It will be closed in 7 days if no further activity occurs. Thank you for your contributions.
=> github(probot): Add context information to stale bot message text

cli/tests/integration_tests.rs, cli/tests/subdir/branch.ts, cli/tests/test_branch_coverage.out, cli/tests/test_branch_coverage.ts, cli/tools/coverage.rs
Had a little off by one error where new line was not being taken into account for line offsets. In turn this was hiding the fact that partial lines don't get reported as uncovered.
This fixes both issues.
=> fix(coverage): report partial lines as uncovered

runtime/ops/fs.rs
This makes the following ops async:
- op_fstat_async
- op_ftruncate_async
- op_seek_async
- op_fdatasync_async
- op_fsync_async
- op_futime_async
Fixes #7400
=> fix(runtime): use tokio for async fs ops

cli/tests/unit/dom_exception_test.ts, cli/tests/wpt.jsonc, op_crates/web/00_dom_exception.js, op_crates/web/lib.deno_web.d.ts
Adds the `code` property to the class `DOMException`. It is pseudo-deprecated, as in new types of `DOMException` set it to zero. It is recommended for code to not rely on that value.
However, tests in the recently included web-platform-tests assert the value of the code, so we are forced to implement it. Issue #9009 highlights an example of such a test that rely on `code`.
Source of the values for each error type: https://developer.mozilla.org/en-US/docs/Web/API/DOMException#Error_names
=> feat(web): Implement DOMException#code

cli/tests/wpt.jsonc, op_crates/crypto/01_crypto.js
Fixed `crypto.getRandomValues()` so that it passes the tests from web-platform-tests. The core logic doesn't really change: it just adds validation that is expected in the [W3C recommandation](https://www.w3.org/TR/WebCryptoAPI/#Crypto-method-getRandomValues).
This follows #8990 and precedes #8984.
=> fix(op_crates/crypto): Test crypto.getRandomValues() with wpt

op_crates/websocket/01_websocket.js, op_crates/websocket/lib.rs
=> refactor(op_crates/websocket): refactor event loop

cli/tests/unit/text_encoding_test.ts, op_crates/web/08_text_encoding.js
fix #8795 
atob('foobar!!') returns a DOMException in chrome, but it returns a DataDecodeError in Deno.
I fixed atob function to throw DOMException instead of DataDecodeError.
=> fix(cli/web): fix atob to throw DOMException

cli/file_watcher.rs, cli/tests/integration_tests.rs
Fixes #9008 
In this PR, I have added a test that works fine on my machine. But unfortunately, because the test cases related to watcher functionality are quite flaky (ref #8571),  this test is marked as `#[ignore]`. This means the test I added here won't be executed in CI.
=> fix(watcher): keep working even when imported files has invalid syntax

cli/tests/078_unload_on_exit.ts, cli/tests/078_unload_on_exit.ts.out, cli/tests/integration_tests.rs, runtime/js/30_os.js
This PR adds the dispatching of `unload` event before sending op_exit. Closes #3603.
(The issue also suggests it should call `unload` hooks at signals like `SIGINT`, etc, but that seems very difficult (complex) to implement because if the process attach something to signal, the default behavior is lost. So we need to simulate the default behavior for each signal to do that, but that seems unreasonably complex to implement and maintain.)
=> fix(cli): dispatch unload on exit

cli/tests/integration_tests.rs
In Web Crypto, must test suites have their JavaScript entrypoint suffixed with `.worker.js`. These files were by default ignored by Deno's integration tests; now they are included.
JavaScript entrypoints meant to be included in HTML files reference their dependencies with `META` comments. JavaScript entrypoints for workers don't do that: they call a function `importScripts()`.
We therefore had to look for the patterns `importScripts("<path>");` in order to build the bundle for the test, as well as included in the bundle the function `importScripts()` as a no-op.
=> test(wpt): Enable wpt workers tests

cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
=> feat(lsp): Add textDocument/implementation

.github/workflows/ci.yml, cli/tests/integration_tests.rs, test_util/src/lib.rs
=> disable cafile_* tests

cli/tests/unit/process_test.ts, runtime/ops/process.rs
Previously, calling `Process#kill()` after the process had exited would
sometimes throw a `TypeError` on Windows. After this patch, it will
throw `NotFound` instead, just like other platforms.
This patch also fixes flakiness of the `runKillAfterStatus` test on
Windows.
=> refactor: make Process#kill() on Windows throw sensible errors

cli/tests/unit/console_test.ts, runtime/js/02_console.js
Right now, the `customInspect` function in core swallows all errors that are thrown in user defined inspection functions. ~I don't think there is a reason for this behavior to be inforced (in my particular use case this is swallowing Permission errors).~
With this PR, a warning will be appended to the inspected item showing the error thrown in the the inspect function
=> fix(core): Log customInspect implementation errors

cli/lsp/language_server.rs, cli/lsp/tsc.rs
In #9071 I added `DocumentSpan` and have noticed there are several cases where equivalent fields are hard-coded.
This PR is to replace those fields for `DocumentSpan`.
=> refactor(lsp): factor out fields to DocumentSpan

Cargo.lock, cli/bench/main.rs, cli/bench/throughput.rs, test_util/Cargo.toml, test_util/src/lib.rs
Replace `serde_json::value::Value` being passed around a lot in the benchmarks.
=> benchmark: cleanup serde_json values being passed around

cli/module_graph.rs, cli/ops/runtime_compiler.rs, cli/tests/080_deno_emit_permissions.ts, cli/tests/080_deno_emit_permissions.ts.out, cli/tests/integration_tests.rs
`await Deno.emit("std/examples/welcome.ts")` doesn't require permissions.
cc @kitsonk
=> fix(cli/runtime_compiler): Check permissions for Deno.emit()

cli/bench/main.rs
Fixes error introduced here https://github.com/denoland/deno/pull/9115/files#diff-8ea5cb8bf751f09968db92ba08d43368d2040b29c3cf0630c76afa15af39d25cL367
=> bench: fix off-by-one error in thread_count

std/node/process_test.ts
The process.cwd test relies on std being in a nested directory within the top level deno project; this makes it use temporary directories instead.
Came up when preparing the workflow for #9029 with @bartlomieju
=> test(std/node): avoid project directories for cwd case

std/node/process_test.ts
While PATH is commonly defined there is no guarantee that it will be defined and turns out it is undefined with GitHub's runner on Windows.
Came up when preparing the workflow for https://github.com/denoland/deno/issues/9029 with @bartlomieju
=> test(std/node): ensure process.env case doesn't rely on unset variables

op_crates/web/08_text_encoding.js, op_crates/web/text_encoding_test.js
Fixes what I had found, that I posted [in a comment](https://github.com/denoland/deno/issues/9006#issuecomment-761876048).
Currently, `TextEncoder#encodeInto` lets an exception propograte to the callee when called with a detached JS ArrayBuffer.
Detached array buffers have zero bytes, there is otherwise no way in JS (without V8 intrinsics) to determine whether or not an ArrayBuffer is detached.
As a side-effect, this optimizes the case when passing an empty ArrayBuffer that isn't detached into `TextEncoder#encodeInto`.
=> fix(op_crates/web) let TextEncoder#encodeInto accept detached ArrayBuffers

cli/main.rs
Currently `deno --help` and `deno --version` don't end with a new line, this fixes that.
This regression was introduced in https://github.com/denoland/deno/pull/9064
Closes https://github.com/denoland/deno/issues/9157
=> fix(cli): print a newline after help and version

cli/dts/lib.deno.shared_globals.d.ts, cli/tests/workers_test.ts
Not sure why this was missing, as mentioned on discord it makes accessing things like `Exclude<WorkerOptions["deno"], undefined | true>` easier.
=> feat(cli/dts/lib.deno.shared_globals): Add WorkerOptions

cli/flags.rs, cli/main.rs, cli/tools/standalone.rs, cli/tools/upgrade.rs
This commit adds `--target` and `--lite` flags to `deno compile` subcommand.
`--target` allows to cross-compile binary to different target architectures by
fetching appropriate binary from remote server on first run. All downloaded
binaries are stored in "$DENO_DIR/dl".
`--lite` allows to use lite version of the runtime (ie. the one that doesn't contain
built-in tooling like formatter or linter).
=> feat: Standalone lite binaries and cross compilation

cli/tools/installer.rs
Fixes #9168.
In `cli/tools/installer.rs` `--cached_only` is being passed as an executable arg instead of `--cached-only`
This pull request fixes that.
=> fix(installer): pass cached-only to executable_args

cli/tests/resolve_dns.ts, cli/tests/resolve_dns.ts.out, runtime/ops/net.rs
Deno.resolveDns() panics with non registered dns record. This PR changes it to JS error.
```shellsession
$ ./target/debug/deno run --unstable -A https://deno.land/posts/v1.7/dig.ts not-found-example.com
error: Uncaught (in promise) Error: no record found for name: not-found-example.com.local. type: A class: IN
throw new ErrorClass(res.err.message);
^
at processResponse (deno:core/core.js:212:11)
at Object.jsonOpAsync (deno:core/core.js:229:12)
at async https://deno.land/posts/v1.7/dig.ts:6:17
```
closes #9186
=> fix(ops/net): fix panic in op_dns_resolve

docs/typescript/configuration.md
Deno hard-codes `"useDefineForClassFields": true`
Updating the docs to reflect this.
=> docs(typescript): Implied tsconfig uses "useDefineForClassFields"

cli/tests/078_unload_on_exit.ts, cli/tests/integration_tests.rs, runtime/js/30_os.js, runtime/js/99_main.js
We introduced the dispatching of `unload` event in `Deno.exit()` in #9088, but that caused the recursive dispatches of the event when it's called in `unload` event handler (ref #9201 ).
This PR checks whether `unload` is triggered before dispatching it in `Deno.exit()`, and prevents the recursive dispatching of `unload` event.
fixes #9201
=> fix(Deno.exit): fix recursive dispatching of unload event

cli/tests/082_prepare_stack_trace_throw.js, cli/tests/082_prepare_stack_trace_throw.js.out, cli/tests/integration_tests.rs, core/error.rs
Fixes #9206.
@00ff0000red A reminder that user assignment of `Error.prepareStackTrace` isn't supported by Deno yet. This fixes the panic, but don't expect error stacks to work completely/correctly.
=> fix(core/error): Handle prepareStackTrace() throws

std/async/pool.ts, std/async/pool_test.ts
=> fix(std/async): Make pooledMap() errors catchable

cli/tools/standalone.rs, cli/tools/upgrade.rs
The zip unpacker was assuming the extension would be the same as the host platform (using `cfg!(windows)`), which worked fine for `upgrade` but not cross-compilation.
Fixes #9194.
=> fix(compile): panic when cross-compiling between windows and unix

std/node/module.ts, std/node/timers.ts
`module.ts` and `timers.ts` wouldn't previously work in workers, since `window` isn't defined.
=> fix(std/node): replace uses of `window` with `globalThis`

cli/flags.rs
`deno run --location file:/// mod.ts` panics.
=> fix(cli/flags): Don't panic on invalid location scheme

cli/tests/wpt.jsonc, runtime/js/40_performance.js
Fixes https://github.com/denoland/deno/issues/9009.
Does anything else need to be changed?
Also, Chromium has an argument length check,
> ```
> TypeError: Failed to construct 'PerformanceMark': 1 argument required, but only 0 present.
> ```
Should that be added too?
Update, I did it anyway.
=> fix(runtime/js) use DOMException in Performance#measure for WPT testing

cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs
I was still running into a few hangs while using the lsp.  Looking back at rust_analyzer, the in memory docs during the snapshot are simply cloned and not modifiable.  We were already in a situation where our in memory documents wouldn't be written with a snapshot, but we were still locking, and those locks I believe were causing some deadlocks when things like formatting and TypeScript diagnostics were happening in different threads at the same time.
=> fix(lsp): reduce deadlocks with in memory documents

docs/getting_started/setup_your_environment.md
ALE is a Vim plugin that does syntax checking and can act as a LSP client.
With [PR 3533]https://github.com/dense-analysis/ale/pull/3533) having been merged, ALE  brings support for Deno's LSP and Deno fmt.
This PR updates the "Getting Started" guide to include documentation on how to use ALE with Deno.
=> docs(tools): add documentation for Vim/Neovim plugin ALE

cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs
The LSP code had numerous places where competing threads could take out
out locks in different orders, making it very prone to deadlocks.
This commit sidesteps the entire issue by switching to a single lock.
The above is a little white lie: the Sources struct still uses a mutex
internally to avoid having to boil the ocean (because being honest about
what it does involves changing all its methods to `&mut self` but that
ripples out extensively...) I'll save that one for another day.
=> fix(lsp): fix deadlocks, use one big mutex

cli/lsp/diagnostics.rs
We were missing a few codes that indicated that a symbol was actually unused.
=> fix(lsp): complete list of unused diagnostics

cli/flags.rs
Closes: #9267 
> Running deno fmt --helpsays: Auto-format JavaScript/TypeScript source code.
In #8887 markdown support was added.
So the describtion should be also saying something like:
Auto-format JavaScript, TypeScript and Markdown files.
=> fix(cli): Added markdown description to `fmt --help`

cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/performance.rs, cli/tests/lsp/did_change_notification_large_02.json, cli/tests/lsp/did_change_notification_large_03.json, cli/tests/lsp/hover_request_large_01.json, cli/tests/lsp/hover_request_large_02.json, cli/tests/lsp/hover_request_large_03.json, cli/tests/lsp/performance_request.json
This PR adds performance measurements to the internals of the LSP, which are then available via the language services virtual status document.  In VSCode the output looks something like this:
This will help us better determine the performance of the lsp and any bottlenecks. It is only instrumented in the language server, and not into the internals of the TypeScript integration for example.
=> feat(lsp): add performance measurements

cli/tests/test_branch_coverage.out, cli/tests/test_coverage.out, cli/tests/test_run_combined_coverage.out, cli/tests/test_run_run_coverage.out, cli/tests/test_run_test_coverage.out, cli/tools/coverage.rs
This makes use of source maps and the original source when printing lacking line coverage in the pretty printer.
Only the executable lines are checked as before (as non-executable lines will always be ignored anyways).
The lines then mapped to the appropriate source line when a source map is present.
Closes #8923
=> fix(coverage): use source maps when printing pretty reports

cli/dts/lib.dom.asynciterable.d.ts, cli/tests/integration_tests.rs, cli/tests/lib_dom_asynciterable.ts, cli/tests/lib_dom_asynciterable.ts.out, cli/tsc.rs
Fixes #9218
Introduces a new lib `dom.asynciterable` to complement `dom` and `dom.iterable` until TypeScript fixes the issue upstream.
If you are using a `"lib"` option in a `tsconfig.json` or with `Deno.emit()` you would want to make it look something like this:
```json
{
"compilerOptions": {
"lib": [ "esnext", "dom", "dom.iterable", "dom.asynciterable" ]
}
}
```
=> fix(cli): add lib dom.asynciterable

cli/ops/runtime_compiler.rs, cli/tests/compiler_api_test.ts
This PR fixes the panic of Deno.emit when called with an module specifier with unknown media type, and improves the error message.
~~partially addresses #9277~~
This doesn't address the original issue, but I think this is still a fix for a different problem.
=> fix(cli): fix panic of Deno.emit

cli/tests/integration_tests.rs
After switching to slower CI runners it seems we can reenable file
watcher integration tests and avoid previous flakiness.
=> chore: reenable watch tests

cli/dts/lib.deno.ns.d.ts, cli/tests/unit/tls_test.ts, runtime/js/30_net.js, runtime/ops/fs.rs, runtime/ops/io.rs, runtime/ops/net.rs, runtime/ops/net_unix.rs, runtime/ops/process.rs, runtime/ops/tls.rs, runtime/ops/tty.rs, std/http/_mock_conn.ts, std/ws/test.ts
TODO:
* add test for TLS graceful close
* also create separate type for `UnixStreamResource`.
=> refactor: IO resource types, fix concurrent read/write and graceful close

cli/tests/integration_tests.rs, cli/tests/subdir/complex.ts, cli/tests/test_branch_coverage.out, cli/tests/test_comment_coverage.out, cli/tests/test_complex_coverage.out, cli/tests/test_complex_coverage.ts, cli/tests/test_coverage.out, cli/tests/test_run_combined_coverage.out, cli/tests/test_run_run_coverage.out, cli/tests/test_run_test_coverage.out, cli/tools/coverage.rs
Follow up to #8995 that I didn't think about at the time.
This uses the number of original mapped source lines as the basis for the number of lines hit and found rather than just relying on the total number of lines in the instrumented script.
For example, on canary:
```
cover file:///home/caspervonb/deno/cli/tests/subdir/complex.ts ... 72.727% (8/11)
25 | export function unused(
26 |   foo: string,
27 |   bar: string,
28 |   baz: string,
-----|-----
30 |   return complex(
31 |     foo,
32 |     bar,
33 |     baz,
34 |   );
35 | }
```
This patch (the number of missing lines are matching with the number of lines rendered as missing):
```
cover file:///home/caspervonb/deno/cli/tests/subdir/complex.ts ... 50.000% (10/20)
25 | export function unused(
26 |   foo: string,
27 |   bar: string,
28 …
```
=> fix(cli/coverage): display mapped instrumentation line counts

std/node/_fs/_fs_stat_test.ts
All the tests related to `std/node` `stat()` and `lstat()` would previously fail if `atime`, `mtime` or `birthtime` were null. This was because optional chaining always returns `undefined` (so `null?.foo === undefined`) and `Number(null) === 0`.
=> test(std/node): fix `assertStats` and `assertStatsBigInt` if atime, mtime or birthtime are null

Cargo.lock, cli/Cargo.toml, core/Cargo.toml, op_crates/fetch/Cargo.toml, op_crates/websocket/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
This upgrades Tokio to 1.1.1.
https://github.com/tokio-rs/tokio/releases/tag/tokio-1.1.1
=> chore: upgrade tokio to 1.1.1

cli/lsp/analysis.rs, cli/lsp/capabilities.rs, cli/lsp/config.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp/code_lens_request.json, cli/tests/lsp/code_lens_resolve_request.json, cli/tests/lsp/did_open_notification_cl_references.json, cli/tests/lsp/initialize_request.json, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts, core/module_specifier.rs
This add the infrastructure for providing code lenses in the LSP and adds the ability to display a lens for references for symbols in the code that aligns to the built-in functionality for TypeScript in VSCode.
I need to add an integration test for this feature.
=> feat(lsp): add references code lens

cli/tests/compiler_api_test.ts, cli/tsc/99_main_compiler.js
This addresses the 2nd case of #9277.
This PR keeps the mapping of original specifier and normalized specifier and uses the original specifier for looking up the source code instead of normalized specifier. This change prevents panic when compiling the specifier in non-normalized form.
=> fix(cli): fix handling of non-normalized specifier

cli/diff.rs, cli/program_state.rs, core/lib.rs, core/ops.rs, runtime/js.rs, runtime/ops/dispatch_minimal.rs
This PR annotates the tests that are not annotated currently with  `#[cfg(test)]`.
Tests in Rust work fine so long as they are annotated with `#[test]`, but adding `#[cfg(test)]` attributes to them is more desirable for the reasons described [here](https://doc.rust-lang.org/book/ch11-03-test-organization.html).
=> chore: make all tests annotated with `#[cfg(test)]`

cli/http_util.rs, op_crates/fetch/lib.rs, runtime/http_util.rs
Include the lower-level error message in the generic error message.
No test because I can't actually make it fail by passing it bad PEM.
I checked and `reqwest::Certificate::from_pem()` always returns `Ok()`.
Fixes #9364.
=> fix: improve http client builder error message

cli/lsp/README.md, cli/lsp/analysis.rs, cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp/code_action_request.json, cli/tests/lsp/code_action_response.json, cli/tests/lsp/did_open_notification_code_action.json, cli/tests/lsp/initialize_request.json, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts, op_crates/fetch/lib.rs, runtime/permissions.rs
This adds the feature that integrates TypeScript quick fix code actions into the LSP.
An example of it looks in VSCode:
=> feat(lsp): add TS quick fix code actions

cli/lsp/analysis.rs, cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/tests/lsp/code_action_resolve_request.json, cli/tests/lsp/code_action_resolve_request_response.json, cli/tests/lsp/code_action_response.json
This adds support for `codeAction/resolve` which supports lazily resolving items like "fix all" code actions which should make performance of the lsp slightly better when dealing with "fix all" code actions.
This will require an update to `vscode_deno` to use the 3.16 version of the lsp for the "fix all" code actions to work, which I will be raising soon.
=> fix(lsp): support codeAction/resolve

cli/program_state.rs, cli/tests/083_legacy_external_source_map.ts, cli/tests/integration_tests.rs
Fixes #6965.
I don't know if or where external source maps are still used, I guess that cleanup would be part of @kitsonk's TODOs here.
=> fix(cli/program_state): Check for inline source maps before external ones

cli/lsp/analysis.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs, cli/tests/lsp/did_open_notification_asset.json, cli/tests/lsp/hover_request_asset_01.json, cli/tests/lsp/hover_request_asset_02.json, cli/tests/lsp/virtual_text_document_request.json
The mutex was used to hide the fact that the Sources object mutates
itself when it's queried. Be honest about that and mark everything that
directly or indirectly mutates it as `mut`.
This is a follow-up to commit 2828690fc7bb510c3248dda7b1cda8793e789ca6
from last month ("fix(lsp): fix deadlocks, use one big mutex (#9271)")
Refs #9406.
=> fix(lsp): remove Sources mutex

cli/lsp/analysis.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp/code_lens_resolve_request_impl.json, cli/tests/lsp/did_open_notification_cl_impl.json, cli/tests/lsp/initialize_request.json
Requires a client that provides a configuration with the `codeLens.implementations` set to `true` (e.g. denoland/vscode_deno#319)
=> feat(lsp): add implementations code lens

cli/lsp/language_server.rs
There is no easy way to test this, but it causes issues when you change the configuration and the diagnostics don't get recalculated.
=> fix(lsp): prepare diagnostics when the config changes

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/utils.rs, cli/tests/lsp/code_lens_request_asset.json, cli/tests/lsp/code_lens_resolve_request_asset.json, cli/tests/lsp/did_open_notification_asset.json
This PR fixes two issues which were causing code lenses for assets and cached dependencies to not be properly handled.  The first bug was that tsc NavigationTrees were not being calculated and the second was that the code lens resolution was not formatting the URL properly to be consumed by an lsp client.
=> fix(lsp): handle code lenses for non-documents

core/runtime.rs
When upgrading `rusty_v8` I forgot to slip proper flag 🤦  it's surprising that it didn't panic without it
=> chore: add flag to v8

cli/tests/084_worker_custom_inspect.ts, cli/tests/084_worker_custom_inspect.ts.out, cli/tests/084_worker_custom_inspect_worker.ts, cli/tests/integration_tests.rs, cli/tests/unit/event_test.ts, op_crates/fetch/11_streams.js, op_crates/web/01_event.js, op_crates/web/11_url.js, op_crates/web/12_location.js, runtime/js/02_console.js
Pass `Deno.inspect()` as an arg to the internal custom inspect implementations.
Fixes #9446.
=> fix(op_crates): Don't use `Deno.inspect` in op crates

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs
Fixes #9425
Once #9408 lands though, we would want to refactor this to just pass the mut ref to the language server to `analyze_dependencies` I suspect in line with other refactors.
=> fix(lsp): handle type deps properly

cli/dts/lib.deno.ns.d.ts, cli/tests/041_dyn_import_eval.out, cli/tests/042_dyn_import_evalcontext.ts.out, cli/tests/070_location.ts.out, cli/tests/071_location_unset.ts.out, cli/tests/fix_js_imports.ts.out, cli/tests/top_level_await_loop.out, cli/tests/unit/console_test.ts, runtime/js/02_console.js
Addresses https://github.com/denoland/deno/issues/9333 
Running `deno eval "const x=()=>'x'; x.y=()=>'y'; x.z = function z() {return 'z'}; console.log({x});"` now properly logs the function's properties. I've added a basic test for this behavior.
=> fix(console) - log function object properties / do not log non-enumerable props by default 

cli/tests/unit/tls_test.ts, runtime/ops/tls.rs
Tiny fix, converts a process-killing panic into a standard runtime error.
Before: 
``` console
> await Deno.connectTls({hostname: '8.8.8.8', port: 443})
thread 'main' panicked at 'Invalid DNS lookup: InvalidDNSNameError', runtime/ops/tls.rs:208:45
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Object({"id": Number(2), "error": Object({"code": Number(-32000), "message": String("Execution context was destroyed.")})})', runtime/inspector.rs:978:8
stack backtrace:
...
```
After:
```
> await Deno.connectTls({hostname: '8.8.8.8', port: 443})
Uncaught Error: Invalid DNS lookup
at processResponse (deno:core/core.js:213:11)
at Object.jsonOpAsync (deno:core/core.js:230:12)
at async …
```
=> fix(runtime/tls): handle invalid host for connectTls/startTls

docs/introduction.md
Hi, noticed a dead link when browsing the manual.
=> Fix deno_std dead link

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/performance.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs, cli/tests/lsp/code_action_request_cache.json, cli/tests/lsp/code_action_response_cache.json, cli/tests/lsp/did_open_notification_cache.json
This PR also fixes a performance regression when accessing cached modules by creating an inner lock on the `Sources` struct.
It also instruments the tsc ops (which helped isolate the performance regression).
@bnoordhuis I tried to figure any easy way to not introduce an arc mutex for sources, but I really can't see a way.  We can't pass a clone of the arc mutex of the language server for the "snapshot" and I also tried just arc mutex'ing parts of sources, but I quickly ended up in deadlocks, it seems that only locking an inner in sources is the only way to avoid it.
Trying to chase down all the places where we might modify/hydrate the data in sources is really difficult, because we might become "aware" of needing to look in the Deno cache at several different points, and actually it is …
=> feat(lsp): add deno cache code actions

cli/lsp/analysis.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/lsp/text.rs, cli/lsp/tsc.rs, cli/tsc.rs
This fixes an issue when using the lsp with a tsconfig with references libraries that are not present in the tsc snapshot, but instead static assets built in Rust.
=> fix(lsp): properly handle static assets

cli/build.rs, cli/tests/unit/dispatch_json_test.ts, core/core.js, core/examples/hello_world.rs, core/examples/http_bench_json_ops.js, core/examples/http_bench_json_ops.rs, core/lib.deno_core.d.ts, core/ops.rs
(from #9422)
This PR makes json_op_sync/async generic to all Deserialize/Serialize types instead of the loosely-typed serde_json::Value. Since serde_json::Value implements Deserialize/Serialize, very little existing code needs to be updated, however as json_op_sync/async are now generic, type inference is broken in some cases (see [cli/build.rs:146](https://github.com/denoland/deno/pull/9423/commits/5e3143e76c0c9020cf8b7ab3db83d6471a44e40f#diff-fa76844bfec3519648a2d7493933ff3317fa3250dd913cc26d0e86b3b5d4465aR146)). I've found this reduces a good bit of boilerplate, as seen in the updated [deno_core examples](https://github.com/denoland/deno/commit/4782f3ec8d0232cd14222ab67dead9f94f0e4f28).
This change may also reduce serialization and deserialization overhead as serde has a better idea of …
=> feat(core): Strongly typed deserialization of JSON ops

cli/source_maps.rs, cli/tests/error_026_remote_import_error.ts, cli/tests/error_026_remote_import_error.ts.out, cli/tests/import_data_url_error_stack.ts.out, cli/tests/inline_js_source_map_2.js.out, cli/tests/integration_tests.rs
Fixes #6542.
Fixes #6965 (again).
Fixes #9443.
`deno run cli/tests/error_026_remote_import_error.ts`
Before:
```
error: Uncaught Error: bad
throw Error("bad");
^
at foo (error_001.ts:2:9)
at bar (error_001.ts:6:3)
at error_001.ts:9:1
```
After:
```
error: Uncaught Error: bad
throw Error("bad");
^
at foo (http://localhost:4545/cli/tests/error_001.ts:2:9)
at bar (http://localhost:4545/cli/tests/error_001.ts:6:3)
at http://localhost:4545/cli/tests/error_001.ts:9:1
```
=> fix(cli/source_map): Don't use file names from source maps

cli/disk_cache.rs, cli/file_fetcher.rs, cli/http_cache.rs, cli/lsp/language_server.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs
@lucacasonato this fixes the issue you have encountered where transitive type dependencies are not handled properly, causing incorrect diagnostics until the affected dependency is opened in the editor.
I still need to work on a test, though it is actually quite complicated to recreate in the test harness.
=> fix(lsp): handle  cached type dependencies properly

core/bindings.rs
Removes boilerplate in `bindings::initialize_context()` when setting core functions, improving readability.
`initialize_context()` is shortened from 98 to 36 lines, making the core logic easier to grasp.
=> refactor(core): Reduce verbosity of binding core functions

op_crates/web/00_webidl.js, op_crates/web/internal.d.ts
Part of https://github.com/denoland/deno/pull/9498#issuecomment-778815752
There is currently no generic checks or conversion to/from a WebIDL string enumeration, this PR adds an internal helper for use in implementing builtins.
=> (00_webidl.js): Add internal enumConverter helper

cli/dts/lib.deno.unstable.d.ts, cli/module_graph.rs, cli/ops/runtime_compiler.rs, cli/tests/compiler_api_test.ts
Closes #9204
Thanks @kdy1 for adding it to swc!  Finally got around to adding it to Deno.
=> feat(cli): Deno.emit supports bundling as IIFE

docs/getting_started/setup_your_environment.md, docs/linking_to_external_code/import_maps.md
I found that some code blocks on docs are rendered as invalid syntax because of commenting to JSON.
For example [this one](https://github.com/denoland/deno/blob/master/docs/getting_started/setup_your_environment.md#emacs).
I marked those blocks as ~JSON5~ JSONC for better syntax highlighting.
=> docs: Use JSONC code block for commenting

cli/import_map.rs, cli/lsp/sources.rs, cli/main.rs, cli/ops/runtime_compiler.rs, cli/program_state.rs, cli/tests/033_import_map_remote.out, cli/tests/import_maps/import_map_remote.json, cli/tests/import_maps/test_remote.ts, cli/tests/integration_tests.rs
This commit adds support for loading import maps from URLs,
both remote and local.
This feature is supported in CLI flag as well as in runtime
compiler API.
Closes https://github.com/denoland/deno/issues/9510
=> feat: support loading import map from URL

cli/dts/lib.deno.unstable.d.ts
`Deno.compile` appears in the documentation of `Deno.formatDiagnostics`, but it was replaced with `Deno.emit`.
https://github.com/denoland/deno/discussions/8800
https://github.com/denoland/deno/pull/8799
This PR updates the example so it will become accurate.
=> fix(dts): update doc of Deno.formatDiagnostics

cli/tests/integration_tests.rs, cli/tests/test_finally_cleartimeout.out, cli/tests/test_finally_cleartimeout.ts, runtime/js/40_testing.js
Fixes https://github.com/denoland/deno/issues/8954
=> fix(runtime/testing): false positive for timers when an error is thrown

cli/flags.rs
The inspect and inspect-brk flags seem to be the only runtime flags that have a description that is not capitalized, this fixes that.
=> chore(cli): capitalize inspect and inspect-brk descriptions

cli/tests/unit/fetch_test.ts, cli/tests/unit/test_util.ts
Fixes https://github.com/denoland/deno/issues/9379
As outlined in that issue, test `fetchConnectionError` assumes that nothing is listening on port 4000. Some users may have something listening on port 4000. To improve test reliability, we check if port 4000 is available by attempting to listen on it. If its not available, we will try the next port up until we find one that is available, or until we hit the maximum port we are willing to try.
=> fix(tests) - fix fetchConnectionError test if port 4000 is in use 

cli/tests/unit/os_test.ts, runtime/ops/os.rs
Fixes #9558
This PR added the validation for `std::env::set_var`. According to [doc](https://doc.rust-lang.org/std/env/fn.set_var.html#panics), the key doesn't support `""`, `"="`, and `"\0"` and the value also doesn't support `"\0"`. Therefore `Deno.env.set("", "")` is causing panics.
And also added the same validatoins to `env::var` and `env::remove_var`.
=> fix(runtime): Fix runtime panic caused by Deno.env.set("", "")

core/bindings.rs, core/modules.rs, core/runtime.rs
* remove "ModuleNameMap", instead define that map inline inside "Modules" struct
* remove "dyn_import_id" argument from "mod_instantiate"
* rename "Modules" struct to "ModuleMap"
* rename "JsRuntime::modules" to "JsRuntime::module_map"
More PRs to follow
=> refactor(core): cleanup module implementation

cli/tests/059_fs_relative_path_perm.ts.out, cli/tsc/compiler.d.ts, core/core.js, runtime/js/10_dispatch_minimal.js
This is needed for WebGPU, where many errors are DOMExceptions that
take two parameters, the message and the error type. Currently we have
no way to create errors that take more than one paramterer.
=> chore(core): optional args for registerErrorClass

cli/ops/errors.rs, cli/source_maps.rs, cli/tests/059_fs_relative_path_perm.ts.out, cli/tests/error_009_op_crates_error.js.out, cli/tests/error_019_stack_function.ts.out, cli/tests/error_020_stack_constructor.ts.out, cli/tests/error_021_stack_method.ts.out, cli/tests/error_022_stack_custom_error.ts.out, cli/tests/error_023_stack_async.ts.out, cli/tests/error_024_stack_promise_all.ts.out, cli/tests/workers/worker_error.ts.out, cli/tests/workers/worker_nested_error.ts.out
Don't show source lines for internal code. Where possible, instead use the top stack frame associated with user code i.e. the first location that is colourful and not a `deno:` URL.
```ts
// deno run -A temp.ts
await Deno.open("non-existent");
```
Before (1.7.5):
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
throw new ErrorClass(res.err.message);
^
at processResponse (deno:core/core.js:213:11)
at Object.jsonOpAsync (deno:core/core.js:231:12)
at async Object.open (deno:runtime/js/30_files.js:45:17)
at async file:///mnt/c/Users/Nayeem/projects/deno/temp.ts:2:9
```
After:
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
await Deno.open("non-existent");
^
at processResponse (deno:core/core.js:212:11)
at Object.jsonOpAsync …
```
=> feat(cli/source_map): Use top user frame for error source lines

cli/colors.rs, cli/info.rs, cli/main.rs, cli/media_type.rs, cli/module_graph.rs, cli/tests/017_import_redirect_info.out, cli/tests/022_info_flag_script.out, cli/tests/031_info_ts_error.out, cli/tests/049_info_flag_script_jsx.out, cli/tests/054_info_local_imports.out, cli/tests/055_info_file_json.out, cli/tests/065_import_map_info.out, cli/tests/076_info_json_deps_order.out, cli/tests/info_missing_module.out, cli/tests/info_recursive_imports_test.out, cli/tests/info_type_import.out, cli/tests/integration_tests.rs, cli/tools/coverage.rs, docs/schemas/module-graph.json
Fixes #7927
This PR provides better output for `deno info` and `deno info --unstable --json`.  Specifically it handles type only dependencies properly and for the JSON output, significantly restructures it to make it more usable and consumable down stream, effectively giving the user the same view as the module graph has.  There is a JSON Schema which describes this output, which is located in `/docs/schemas/module-graph.json` (which ideally we should serve up at `https://deno.land/x/schemas/module-graph.json`).
For example, the output for a circular dependency modules:
```json
{
"root": "file:///Users/kitsonk/github/deno/cli/tests/info_recursive_imports_test.ts",
"modules": [
{
"specifier": "file:///Users/kitsonk/github/deno/cli/tests/info_recursive_imports_test.ts",
"dependencies": [
{ …
```
=> feat(cli): represent type dependencies in info

docs/testing/assertions.md
Adding `assertObjectMatch` example.
=> docs(testing): Add assertObjectMatch example

cli/tests/unit/url_test.ts
=> test(op_crates/web): regression tests for bugs in old URL implementation

Cargo.lock, op_crates/fetch/Cargo.toml, op_crates/web/Cargo.toml, op_crates/websocket/Cargo.toml, runtime/Cargo.toml
=> Bump crates again

.github/workflows/ci.yml
| runner | before | after | after2
| --- | --- | --- | --- |
| test_release macos-10.15 | 41m 34s | 30m 49s | 25m 47s |
| test_release windows-2019 | 55m 34s | 33m 21s | 37m 57s | 
| bench ubuntu-latest-xl | 20m 49s | 20m 35s | 20m 25s |
| lint ubuntu-latest | 11m 40s | 4m 20s | 4m 24s |
| test_debug ubuntu-latest | 36m 56s | 34m 37s | 32m 42s |
| test_release ubuntu-18.04 | 35m 50s |  FAIL | 35m 50s |
=> Re-enable sccache

cli/main.rs, cli/tests/integration_tests.rs, cli/tools/standalone.rs
Fixes bug described in https://discord.com/channels/684898665143206084/689420767620104201/816669791359991828
Prevents appending `.exe` extensions on windows based on target.
Fixes #9667
=> fix(cli/compile): do not append .exe depending on target

cli/tests/coverage/complex.ts, cli/tests/coverage/expected_complex.lcov, cli/tests/coverage/expected_complex.out, cli/tools/coverage.rs
Fixes https://github.com/denoland/deno/issues/9589
=> fix(coverage): ensure single line functions don't yield false positives

core/runtime.rs
Extracted this bugfix from #9457.
In case JavaScript throws an unhandled error, part of the "shared_queue" could be still unprocessed. If this is the case; throw the js runtime error instead of asserting on the queue size not being 0.
=> fix(core) assertion failure in case of js error

op_crates/webgpu/lib.deno_webgpu.d.ts
Add Uint32Array type for `code` in `ShaderModuleDescriptor`, for which support was fixed in #9698
=> fix(webgpu): ShaderModuleDescriptor code type

cli/tests/integration_tests.rs
Let's get rid of a very annoying warning.  Not sure why this isn't fatal in CI.
=> chore: remove unused import on non-windows

op_crates/webgpu/01_webgpu.js
Reported by @DjDeveloper.
Will be tested by WebGPU CTS in the future.
=> fix: getBindGroupLayout always illegal invocation

.github/workflows/ci.yml
Experiencing CI issues: https://github.com/denoland/deno/runs/2099314334
See also https://github.com/actions-rs/cargo/issues/111, https://github.com/denoland/rusty_v8/commit/8e35aaf6ad0f996285275196f6d0e4a65763544f
=> Use workaround for serde_derive CI issue

cli/lsp/language_server.rs, cli/module_graph.rs, cli/tests/088_use_define_for_class_fields.ts, cli/tests/088_use_define_for_class_fields.ts.out, cli/tests/integration_tests.rs, cli/tsc_config.rs
We decided to do this around https://github.com/denoland/deno/issues/7148#issuecomment-678754613, added `"useDefineForClassFields"` to the set of ignored compiler options in #7228 and documented it as set to true in #9196. Unless there was a regression, I don't think we ever actually set it to true.
Fixes #9773 (the example now produces an intuitive type error).
=> fix(cli/module_graph): Set useDefineForClassFields to true

cli/lsp/language_server.rs, cli/module_graph.rs, cli/tests/088_use_define_for_class_fields.ts, cli/tests/088_use_define_for_class_fields.ts.out, cli/tests/integration_tests.rs, cli/tsc_config.rs
Backwards incompatible change cannot be made in-between patch releases.
This commit broke std tests https://github.com/denoland/deno_std/runs/2112369372
This reverts commit c4709834b37640fd3c9d492123e6add904546573.
cc @nayeemrmn
=> Revert "fix(cli/module_graph): Set useDefineForClassFields to true"

cli/lsp/capabilities.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp/completion_request.json, cli/tests/lsp/completion_resolve_request.json, cli/tests/lsp/did_open_notification_completions.json, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
This refactor is to give us a more solid base to build on for import completions.
It refactors some code and adds a completion resolver, plus some tests.
=> refactor(lsp): refactor completions and add tests

runtime/ops/fs.rs, runtime/ops/fs_events.rs, runtime/ops/io.rs, runtime/ops/net.rs, runtime/ops/os.rs, runtime/ops/permissions.rs, runtime/ops/plugin.rs, runtime/ops/process.rs, runtime/ops/signal.rs, runtime/ops/timers.rs, runtime/ops/tls.rs, runtime/ops/tty.rs, runtime/ops/worker_host.rs
Equivalent of #9817 for runtime ops
=> refactor(runtime/ops): move runtime ops to serde ops

cli/lsp/diagnostics.rs
This patch doesn't actually fix the bug I was hoping to fix, which is
that `update_diagnostics()` sometimes gets called even when there are
more updates that should be processed first. I did eventually figure out
that this issue is caused by Tokio's cooperative yielding, which
currently can't be disabled.
However overall it makes the debounce code somewhat more readable IMO,
which is why I'm suggesting to land it anyway.
=> refactor(lsp): slightly reorganize diagnostics debounce logic

core/examples/http_bench_bin_ops.rs, op_crates/fetch/lib.rs, op_crates/webgpu/binding.rs, op_crates/webgpu/buffer.rs, op_crates/webgpu/bundle.rs, op_crates/webgpu/command_encoder.rs, op_crates/webgpu/compute_pass.rs, op_crates/webgpu/lib.rs, op_crates/webgpu/pipeline.rs, op_crates/webgpu/queue.rs, op_crates/webgpu/render_pass.rs, op_crates/webgpu/sampler.rs, op_crates/webgpu/shader.rs, op_crates/webgpu/texture.rs, op_crates/websocket/lib.rs, runtime/ops/fs.rs, runtime/ops/fs_events.rs, runtime/ops/io.rs, runtime/ops/net.rs, runtime/ops/process.rs, runtime/ops/signal.rs, runtime/ops/tls.rs, runtime/ops/tty.rs
The type declared was hardly used earlier. This PR enforces its use across op args.
=> chores: enforce type ResourceId across codebase

runtime/js/11_workers.js, runtime/ops/worker_host.rs, runtime/permissions.rs
- `BooleanPermission` -> `UnitPermission`: Since it's not boolean. `UnaryPermission` queries with one argument, `UnitPermission` queries with 0 and is only associated with a single `PermissionState`.
- `{Read,Write,Net}Permission` -> `{Read,Write,Net}Descriptor`: `UnaryPermission<ReadDescriptor>` doesn't stutter, more accurate.
=> refactor(runtime/permissions): Rename permission structs

core/bindings.rs
Resolves #9812 . 
Will now throw type error when too many arguments are passed or the second argument can't be parsed into an integer. Had some trouble figuring out how to test the core changes. Would be great to get some direction if possible and a test is required.
=> fix(core): Adds type errors to invalid arguments for print

.github/workflows/ci.yml, Cargo.lock, cli/Cargo.toml, core/Cargo.toml, op_crates/console/Cargo.toml, op_crates/crypto/Cargo.toml, op_crates/fetch/Cargo.toml, op_crates/url/Cargo.toml, op_crates/web/Cargo.toml, op_crates/webgpu/Cargo.toml, op_crates/webidl/Cargo.toml, op_crates/websocket/Cargo.toml, runtime/Cargo.toml
=> chore: release crates

cli/lsp/tsc.rs
This patch removes the `asset` field of `State` because it seems to be unused.
Taking a glance at the commit history, this field was introduced in https://github.com/denoland/deno/pull/8771, and at that time the field value was used in [the `request_asset` function](https://github.com/denoland/deno/pull/8771/files#diff-5425491838b4e06f099e33c0663a61d3b088c0c193a5a484a9b797c2f4ee099bR1125).
After that, in https://github.com/denoland/deno/pull/8727, both `request_asset` and invoking `op_set_asset` from JS were removed:
- [`request_asset` was removed](https://github.com/denoland/deno/pull/8727/files#diff-5425491838b4e06f099e33c0663a61d3b088c0c193a5a484a9b797c2f4ee099bL1104)
- [invoking `op_set_asset` was removed](https://github.com/denoland/deno/pull/8727/files#diff-917b74af14d03b69b9948cd236 …
=> refactor(lsp): remove unused code

cli/main.rs, cli/tsc.rs
=> fix: include deno.crypto in `deno types`

core/bindings.rs
This uses `serde_v8` to serialize our `HeapStats` data instead of the previous "manual" serialization. This is less verbose and `serde` handles mapping keys to camelCase so the rust code is strongly typed and less prone to typos
This is a follow-up anticipated in https://github.com/denoland/deno/pull/9659, as per [this TODO comment](https://github.com/denoland/deno/pull/9659/files#diff-5b84637fa51710dd4ffc2f2370fb6bb77301603caac646be8184da12eedd7433R949)
=> core/bindings: simplify heapStats() by using serde_v8

cli/bench/deno_common.js
This PR aims to add a bench "suite" of commonly called deno functions, as a shared reference to track and measure performance regressions or improvements (e.g: following the op-ABI changes).
It's intentionally very simple, so it can easily be backported and tested on older releases or newer branches.
It might make sense to have something more sophisticated down the line, but this should be a fair start
It currently tracks:
- URL parsing: since deno is ~25x slower than Node/Chrome (https://github.com/denoland/deno/pull/9276#issuecomment-773865387)
- Basic IO, read/write to `/dev/null` and `/dev/zero`
- `performance.now()/op_now` since it's one of the lightest/fastest ops
On my m1 Air with `deno@1.8.2`:
```
❯ deno run -A ./cli/bench/deno_common.js
url_parse:           	n = 50000, dt = …
```
=> A bench "suite" of common Deno functions

core/error.rs
Similar to https://github.com/denoland/deno/pull/9901, this uses `serde_v8` to cleanup decoding `JsStackFrame`s.
- I used fully qualified paths (i.e: `serde::Deserialize`, `serde_v8::from_v8`, ...) instead of `use ...`, not sure if this goes against our stylistic guidelines, happy to switch it
- I feel like it's slightly cleaner to use fully qualified paths when there are only a handful of references and the paths are short/straightforward
=> refactor(core): decode JsStackFrames using serde_v8

serde_v8/examples/basic.rs, serde_v8/src/de.rs, serde_v8/src/error.rs, serde_v8/src/keys.rs, serde_v8/src/lib.rs, serde_v8/src/magic.rs, serde_v8/src/payload.rs, serde_v8/src/ser.rs, serde_v8/src/utils.rs, serde_v8/tests/de.rs, serde_v8/tests/magic.rs, serde_v8/tests/ser.rs
So `serde_v8` is consistent with other rust files in codebase, cc @bartlomieju
=> serde_v8: add Deno copyright headers to all rust files

op_crates/webgpu/error.rs, runtime/ops/webgpu.rs
Complements https://github.com/denoland/deno/pull/9909, cc @bartlomieju 
```bash
find . -name "*.rs" | grep -v "./target/" | xargs -I{} bash -c 'cat {} \
| grep "// Copyright 2018-2021 the Deno authors. All rights reserved. MIT license." \
&>/dev/null || echo {}'
```
```
./runtime/ops/webgpu.rs
./op_crates/webgpu/error.rs
```
=> chore: add missing copyright headers

op_crates/web/03_abort_signal.js, tools/wpt/expectation.json
tests that are failing that are actionable:
`ReadableStream: if pull rejects, it should error the stream`
`TransformStream constructor should not call setters for highWaterMark or size`
Required for #7819
=> chore: update wpt

cli/bench/deno_common.js
It's simply the inverse of the rate (ops/s), but it's often useful to look at time per op since it's easier to picture the upper bound and improvable delta.
=> feat(bench/deno_common): show ns/op

serde_v8/tests/de.rs, serde_v8/tests/ser.rs
Fixes compiler warnings for serde_v8 tests. (Discovered while debugging the CI for #9614)
=> chore: fix clippy warning in serde_v8

cli/bench/deno_common.js
This is another simple extension of the `cli/bench/deno_common.js` "benchsuite".
It benches `Date.now()` (a v8 builtin) to provide an indication of the upper bound for non-NOP ops.
(This should be our practical upper bound for all ops, even with v8 Fast API)
On my M1 Air:
```
❯ deno -V; deno run --unstable -A ./cli/bench/deno_common.js
deno 1.8.2
date_now:            	n = 500000, dt = 0.021s, r = 23809524/s, t = 42ns/op
perf_now:            	n = 500000, dt = 0.700s, r = 714286/s, t = 1400ns/op
url_parse:           	n = 50000, dt = 0.712s, r = 70225/s, t = 14240ns/op
read_zero:           	n = 500000, dt = 0.758s, r = 659631/s, t = 1516ns/op
write_null:          	n = 500000, dt = 0.739s, r = 676590/s, t = 1478ns/op
```
=> feat(bench/deno_common): track Date.now() as upper bound

Cargo.lock, serde_v8/Cargo.toml, serde_v8/benches/de.rs, serde_v8/benches/ser.rs
This restores the `serde_v8` benches from the original repo, using `bencher` like `core/benches/op_baseline`.
The original benches were compared to `serde_json` working on existing strings. Whilst useful, these `_json` benches can be misleading and lead people to believe that `serde_v8` is slower than using JSON for the op-layer, forgetting that using JSON requires the extra steps of `JSON.parse()/.stringify()` and co, not measured here.
Since they can't be meaningfully compared in absolute, it might make sense to remove them
```
running 15 tests
test de_array_json        ... bench:         488 ns/iter (+/- 9)
test de_array_v8          ... bench:         601 ns/iter (+/- 19)
test de_bool_json         ... bench:          21 ns/iter (+/- 1)
test de_bool_v8           ... bench:           7 …
```
=> serde_v8: restore ser/de benches

docs/examples/read_write_files.md
Updated typo in following line.
```
By combining `Deno.writeTextFile` and `JSON.stringify` you can easily write
```
=> Fix documentation typo

cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/lsp/completion_request_optional.json, cli/tests/lsp/completion_resolve_request_optional.json, cli/tests/lsp/did_open_notification_completion_optional.json
Fixes #9920 
The fix ended up being simple, but still added a regression test case anyways.  Might fix a few other things that were strange.
=> fix(lsp): ensure insert_text is passed back on completions

op_crates/web/lib.deno_web.d.ts
Fixes https://github.com/denoland/deno/issues/5666
=> fix(op_crates/web): align encoding type definitions to spec

core/core.js, core/ops.rs
This is an op-layer optimization follow-up to #9843.
It shaves off `~350ns/op` of baseline overhead, making them over 2x faster by reducing allocs.
Instead of returning JS results as tuples of `(Option<T>, Option<Err>)` it returns them as a conceptual union type, avoiding allocating the wrapping array. We then use a "special" key name to recognize errors.
So far I've picked the error-key to be `$err_class_name`, but this can be easily changed or adjusted.
Op-baseline benches:
```
Before:
test bench_op_nop     ... bench:     321,740 ns/iter (+/- 39,892)
test bench_op_pi_bin  ... bench:     786,395 ns/iter (+/- 23,765)
test bench_op_pi_json ... bench:     681,285 ns/iter (+/- 26,579)
After:
test bench_op_nop     ... bench:     318,910 ns/iter (+/- 16,233)
test bench_op_pi_bin  ... bench: …
```
=> core: js errors as unions vs tuples to reduce allocs

cli/dts/lib.deno.unstable.d.ts
I was working on `deno_std` and I saw an example for `futime` and `futimeSync`. as far as I know `Deno.openSync` needs `write` option alongside with `create`/`append` option. so I updated the example. let me know if I'm wrong.
ref: 
https://github.com/denoland/deno/blob/d6d5ced1ab90404d25a87a242ee5b03ca655abe5/cli/dts/lib.deno.ns.d.ts#L812
=> fix(cli/dts): fix futime and futime example

op_crates/websocket/01_websocket.js
It is possible that the WebSocket is already closed when we try to
close it with `WebSocket#close` or in the `error` or `close` events.
Currently this leads to an uncatchable promise rejection. This changes
this so that closing an already closed WebSocket is a noop.
Closes #9879
Closes #9958
=> fix(websocket): ignore resource close error

op_crates/web/lib.deno_web.d.ts
Reverts denoland/deno#9782
This breaks `std` and could have further breaking changes with downstream users... need to reland later in 1.9 in a non-breaking way.
=> revert: "fix(op_crates/web): align encoding type definitions to spec"

core/benches/op_baseline.rs
This extends the `op_baseline` bench introduced in https://github.com/denoland/deno/pull/9924 to also bench async ops.
Here's a comparison of `main` vs https://github.com/denoland/deno/pull/9947:
```
Before:
test bench_op_async   ... bench:   1,256,422 ns/iter (+/- 27,839)
test bench_op_nop     ... bench:     323,275 ns/iter (+/- 7,916)
test bench_op_pi_bin  ... bench:     810,688 ns/iter (+/- 26,193)
test bench_op_pi_json ... bench:     703,911 ns/iter (+/- 44,627)
After:
test bench_op_async   ... bench:     805,011 ns/iter (+/- 22,248)
test bench_op_nop     ... bench:     318,809 ns/iter (+/- 11,228)
test bench_op_pi_bin  ... bench:     408,557 ns/iter (+/- 21,002)
test bench_op_pi_json ... bench:     315,826 ns/iter (+/- 23,131)
```
=> perf: bench async op baseline

core/benches/op_baseline.rs
Follow-up PR to #9954 and #9944, which accidentally broke CI on `main` since `BufVec` was dropped by `#9944` which was merged first.
=> core/op_baseline: drop BufVec and minor cleanup

runtime/permissions.rs
```js
// test.js
await Deno.permissions.request({ name: `env` });
```
1. Run `deno run test.js`
2. When the prompt comes up, press `ctrl-d`
3. See following panic:
```
RUST_BACKTRACE=1 cargo run run test.js
Finished dev [unoptimized + debuginfo] target(s) in 0.56s
Running `target/debug/deno run test.js`
⚠️  ️Deno requests access to environment variables. Grant? [g/d (g = grant, d = deny)] thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', runtime/permissions.rs:698:35
stack backtrace:
0: rust_begin_unwind
at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
1: core::panicking::panic_fmt
at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
2: core::panicking::panic
at …
```
=> fix(permissions): don't panic when no input is given (#9633)

serde_v8/src/de.rs
So serde can optimize array allocation. Array deserialization on serde_v8's benches are 33% faster as a result.
```
Before:
test de_array_json        ... bench:         472 ns/iter (+/- 17)
test de_array_v8          ... bench:         578 ns/iter (+/- 15)
After:
test de_array_json        ... bench:         469 ns/iter (+/- 12)
test de_array_v8          ... bench:         386 ns/iter (+/- 8)
```
=> perf(serde_v8/de): implement SeqAccess size_hint

runtime/js/11_timers.js, runtime/ops/timers.rs
Making it 20% faster and simpler.
Comparing `performance.now()` (calling `op_now`) in the `deno_common` bench:
```
v1.8.2:
perf_now:                n = 500000, dt = 0.700s, r = 714286/s, t = 1400ns/op
Main:
perf_now:                n = 500000, dt = 0.403s, r = 1240695/s, t = 806ns/op
This PR:
perf_now:                n = 500000, dt = 0.331s, r = 1510574/s, t = 662ns/op
```
=> Switch op_now to be a json-op

serde_v8/src/ser.rs
Which substantially improves the performance of `to_v8()` by removing RC's overhead (extra allocs, drops, checks, etc...)
This breaks through the symbolic barrier of 200ns/op overhead (on my machine) ! 🚀 🚀 🚀 
(The last symbolic milestone before going sub 100ns/op, which will be very hard to cross ...)
Note that the before and after of these benches integrates changes from #9983.
```
Before:
test bench_op_async   ... bench:     716,780 ns/iter (+/- 28,508)
test bench_op_nop     ... bench:     213,206 ns/iter (+/- 5,618)
test bench_op_pi_bin  ... bench:     243,481 ns/iter (+/- 6,120)
test bench_op_pi_json ... bench:     227,972 ns/iter (+/- 5,995)
After:
test bench_op_async   ... bench:     647,272 ns/iter (+/- 57,528)
test bench_op_nop     ... bench:     157,173 ns/iter (+/- 2,096)
test …
```
=> perf(serde_v8): drop need for RC in serializer

Cargo.lock, core/Cargo.toml, core/bindings.rs, core/lib.rs, core/ops.rs, core/runtime.rs, core/v8_serializable.rs, serde_v8/src/lib.rs, serde_v8/src/serializable.rs
A more efficient replacement for `erased-serde` to box our async op returns.
It improves our op-baseline by ~60ns/op across all op-categories, which is a strong gain across the board, 20% of the current sync op baseline which is quite significant.
```
Before:
test bench_op_async   ... bench:     772,851 ns/iter (+/- 55,538)
test bench_op_nop     ... bench:     265,945 ns/iter (+/- 13,634)
test bench_op_pi_bin  ... bench:     291,033 ns/iter (+/- 16,716)
test bench_op_pi_json ... bench:     285,994 ns/iter (+/- 7,377)
After:
test bench_op_async   ... bench:     710,543 ns/iter (+/- 28,573)
test bench_op_nop     ... bench:     210,362 ns/iter (+/- 3,354)
test bench_op_pi_bin  ... bench:     238,992 ns/iter (+/- 20,449)
test bench_op_pi_json ... bench:     223,458 ns/iter (+/- 3,186)
```
=> perf(serde_v8): introduce Serializable boxable object

serde_v8/src/ser.rs
This is another improvement to `serde_v8`'s serialization code, it drops the need for creating a `v8::EscapableHandleScope` or "subscope". It's a simplication and optimization similar in nature to #9987.
This is very exciting since sub 100ns/op for sync-ops appears to be within reach ! (at least on my machine, M1 Air)
Using our trusty `op_baseline` bench to compare with `main`:
(Note that the before and after of these benches integrates changes from #9983)
```
Before:
test bench_op_async   ... bench:     647,272 ns/iter (+/- 57,528)
test bench_op_nop     ... bench:     157,173 ns/iter (+/- 2,096)
test bench_op_pi_bin  ... bench:     179,239 ns/iter (+/- 4,354)
test bench_op_pi_json ... bench:     175,075 ns/iter (+/- 1,814)
After:
test bench_op_async   ... bench:     564,882 ns/iter (+/- …
```
=> perf(serde_v8): drop need for EscapableHandleScope

serde_v8/src/ser.rs
This PR is an optimization pass on `serde_v8`
=> perf(serde_v8): preallocate vector when serializing arrays

cli/dts/lib.deno.ns.d.ts, cli/tests/unit/fetch_test.ts, cli/tests/unit/io_test.ts, runtime/js/12_io.js, runtime/js/40_process.js, runtime/js/40_read_file.js, runtime/js/40_write_file.js
This commit marks the `Deno.Buffer` / `Deno.readAll` /
`Deno.readAllSync` / `Deno.writeAll` / `Deno.writeAllSync` utils as
deprecated, and schedules them for removal in Deno 2.0. These
utilities are implemented in pure JS, so should not be part of the
Deno namespace.
These utilities are now available in std/io/buffer and std/io/util:
https://github.com/denoland/deno_std/pull/808.
This additionallty removes all internal dependance on Deno.Buffer.
Towards #9795
=> chore: deprecate Deno.Buffer and read/write utils

cli/dts/lib.deno.ns.d.ts
This commit marks the `Deno.iter` and `Deno.iterSync` utils as
deprecated, and schedules them for removal in Deno 2.0. These
utilities are implemented in pure JS, so should not be part of the
Deno namespace.
These utilities are now available in std/io/util:
denoland/deno_std#843.
Towards #9795
=> chore: deprecate Deno.iter and Deno.iterSync

core/core.js, core/ops.rs
Core no longer uses `serde_json` now, besides re-exporting it or in the module specifier tests.
This is a follow-up to #10009 and #9843
=> core: remove serde_json-isms in op_close() and op_resources()

runtime/ops/fs.rs, runtime/ops/mod.rs, runtime/ops/net.rs, runtime/ops/net_unix.rs, runtime/ops/os.rs, runtime/ops/tls.rs, runtime/ops/utils.rs
This is another continuation of #10009 and #9843. It refactors `runtime/ops/net` to follow our best practices.
- Introduced `OpConn` type returned by listening or connecting ops
- Introduced `OpAddr`, `IpAddr`, `UnixAddr` types to polymorphically encode transports and addresses
- Introduced `OpPacket` for datagram transports (`udp` and `unixpacket`)
- Cleaned up some utility functions
- Might fix tcp max-latency regression (https://github.com/denoland/deno/issues/2700)
=> refactor(runtime/net): remove serde_json

cli/lsp/language_server.rs, cli/lsp/urls.rs
=> fix(lsp): properly handle encoding URLs from lsp client

cli/dts/lib.deno.unstable.d.ts
EmitOptions and EmitResult are not available in `deno doc` command because these are not exported in d.ts file. With this change we can see the docs by the following commands:
```
deno doc --unstable --builtin Deno.EmitOptions
deno doc --unstable --builtin Deno.EmitResult
```
=> docs: export EmitOptions and EmitResult from d.ts

docs/runtime/workers.md
Fix a couple mistyped brackets (`[]` where `{}` is meant), and specify `"none"` arg instead of `false`.
=> docs(workers): Fix permissions examples

Cargo.toml
Specifically: deno_core, rusty_v8, serde_v8, serde, since they are central to op baseline performance.
**Impact:** gets us sub 100ns sync ops 🎉, and cuts async ops' baseline by ~70ns or 10%
Measured on the `op_baseline` bench:
```
Before:
test bench_op_async   ... bench:     608,301 ns/iter (+/- 16,057)
test bench_op_nop     ... bench:     112,457 ns/iter (+/- 2,073)
test bench_op_pi_bin  ... bench:     137,527 ns/iter (+/- 6,679)
test bench_op_pi_json ... bench:     128,126 ns/iter (+/- 2,241)
After:
test bench_op_async   ... bench:     536,888 ns/iter (+/- 13,096)
test bench_op_nop     ... bench:      71,331 ns/iter (+/- 2,728)
test bench_op_pi_bin  ... bench:      85,746 ns/iter (+/- 1,959)
test bench_op_pi_json ... bench:      87,541 ns/iter (+/- 6,453)
```
Optimizing these core libs …
=> perf(cargo): build core packages at opt-3

.github/workflows/ci.yml, tools/restore_mtime.py
This PR enables the incremental build of rust code in CI by the following changes:
- Enables it by env var `CARGO_INCREMENTAL=1`. (`release` profile has `incremental = false` setting by default.)
- Uses `matrix.kind` in part of cache key because `test_release` and `test_debug` can't share the cache.
- Restores each source file's timestamp based on git log. ( `./tools/restore_mtime.py` )
- git [doesn't store timestamp of files](https://git.wiki.kernel.org/index.php/Git_FAQ#Why_isn.27t_Git_preserving_modification_time_on_files.3F), and cargo triggers rebuild of source file based on timestamps. So we need to preserve timestamp of each file somehow. I found [this script](https://github.com/MestreLion/git-tools/blob/957810b10efa77d6ca4a3aa4f76883963621f31a/git-restore-mtime) (this script …
=> ci: use incremental build in ci

op_crates/file/01_file.js, op_crates/file/03_blob_url.js, op_crates/webidl/00_webidl.js, tools/wpt/expectation.json
This changes the custom input converters in deno_file to use deno_webidl
converters.
=> chore: update deno_file to use deno_webidl

.github/workflows/ci.yml
This adds the repository and ref to the cache key, making it scoped on an origin/branch pair basis to avoid clashes.
=> ci: use repository and ref as part of the cache key

.github/workflows/ci.yml
Creates cache for each branch to prevent the cache conflict. Uses main's cache for the first run in the branch.
related #10067
=> ci: fallback to main's cache

.github/workflows/ci.yml
This PR installs and uses GNU tar for extracting cache in macos runner of CI. (`actions/cache` step automatically picks gtar if it's available).
According to https://github.com/actions/cache/issues/403 BSD tar causes corruption of certain files such as `libserde_derive.dylib`. (see also https://github.com/rust-lang/cargo/issues/8603
This workaround should prevent this error https://github.com/denoland/deno/runs/2297003519
=> ci: use gnu tar on macos

cli/lsp/urls.rs
Fixes #9744
Fixes https://github.com/denoland/vscode_deno/issues/386
=> fix(lsp): normalize windows file URLs properly

.github/workflows/ci.yml
follow up of #10069
on mac CI, gnu-tar was not in PATH and we still have the issue https://github.com/actions/cache/issues/403. This PR fixes it.
=> ci: add gnu tar path

README.md
Add Discord to Readme
- Does not change any code
- Related to #9712
=> Add a link to the Discord server to the Readme

.github/workflows/ci.yml
Cache service often returns 429 response at Post cache step. ref [1](https://github.com/denoland/deno/pull/9376/checks?check_run_id=2302579454), [2](https://github.com/denoland/deno/pull/10078/checks?check_run_id=2302563352), [3](https://github.com/denoland/deno/runs/2302591438) (GitHub Actions cache now has 5GB limit for a single repository. Probably we exceed this limit.)
This change prevents creating new cache on every PR branch.
=> ci: do not include branch name in cache key

Cargo.toml
|        | incremental build (release) | full build (release) | binary size (release) |
|--------|-----------------------------|----------------------|-----------------------|
| main   | 4m 21s                      | 6m 24s               | 72M                   |
| #10039 | 1m 45s                      | 5m 28s               | 80M                   |
*incremental build is measured using `touch core/runtime.rs; cargo build --release`
=> Improve release build link time by disabling LTO, codegen-units = 1, opt-level = 'z' 

Cargo.toml
This reverts commit a87da4b19a6da67dde15d1d0ceefaad2bdad1637.
Although the binary size increase was known in advance, I'm having second thoughts after seeing the benchmarks page:
=> Revert "Improve incremental build time (#10039)"

Cargo.lock, cli/Cargo.toml, cli/ast.rs, cli/tests/bundle/fixture13.out, cli/tests/integration_tests.rs, cli/tests/lint/expected_from_stdin_json.out, cli/tests/lint/expected_json.out, cli/tests/lint/file2.ts, cli/tests/unit/buffer_test.ts, cli/tests/unit/console_test.ts, cli/tests/unit/dispatch_bin_test.ts, cli/tests/unit/fetch_test.ts, cli/tests/unit/filereader_test.ts, cli/tests/unit/files_test.ts, cli/tests/unit/globals_test.ts, cli/tests/unit/headers_test.ts, cli/tests/unit/http_test.ts, cli/tests/unit/net_test.ts, cli/tests/unit/test_util.ts, cli/tests/unit/text_encoding_test.ts, cli/tests/unit/timers_test.ts
Upgrades:
- swc_ecmascript
- swc_bundler
- deno_doc
- deno_lint
- dprint-plugin-typescript
=> chore: upgrade dependencies

runtime/inspector.rs
This partially fixes https://github.com/denoland/deno/issues/10113, by allowing Deno to use Chrome's builtin support for debugging NodeJS processes. Longterm we'll want to add first-class Deno support in devtools & chromium.
Users are shown a significantly more relevant DevTools view when clicking `inspect` (see screenshots below) and can also use `Open dedicated DevTools for Node` which will open a DevTools window (with relevant views) that auto-attaches to newly spawned inspectable (deno) processes, which is nice.
This compares the view users get when they go to `chrome://inspect` and click on `inspect`.
You'll notice this view includes web specific tabs such as Elements (DOM), Lighthouse, Application, etc...
This view now contains only the relevant tabs and (CPU) `Profiler` instead of …
=> inspector: leverage Chrome DevTools' builtin support for NodeJS

cli/dts/lib.deno.unstable.d.ts, cli/tests/integration_tests.rs, cli/tests/listen_tls_alpn.ts, runtime/js/40_tls.js, runtime/ops/tls.rs
This commit adds the ability for users to configure ALPN protocols when
calling `Deno.listenTls`.
Closes #6334.
=> feat(unstable): ALPN config in listenTls

Cargo.lock, op_crates/fetch/Cargo.toml, op_crates/fetch/lib.rs, tools/wpt/expectation.json
This commit adds data URL support in `fetch`. Tested via wpt.
=> feat: data URL support in fetch

cli/ast.rs, cli/lsp/language_server.rs, cli/module_graph.rs, cli/tests/091_use_define_for_class_fields.ts, cli/tests/091_use_define_for_class_fields.ts.out, cli/tests/bundle/fixture13.out, cli/tests/integration_tests.rs, cli/tsc_config.rs
#9774. The option is now also passed to swc, which supports it as of recently.
=> Reland #9774: Set useDefineForClassFields to true

core/bindings.rs, core/ops.rs, core/ops_bin.rs, core/ops_json.rs, core/runtime.rs, test_plugin/src/lib.rs
This is another op-layer optimization, it reduces the baseline overhead of async ops by ~10%. 
It removes an extra alloc/free per opcall that happened due to "reboxing" the future to insert the `PromiseId`. The `PromiseId` is now passed as a field of `OpPayload` so the async OpFn wrappers can insert it when mapping the future result.
I have another experiment in progress, but wanted to land this since it's simple and 10% is a respectable gain even if it's not "game changing".
```
Before:
test bench_op_async   ... bench:     533,080 ns/iter (+/- 14,308)
test bench_op_nop     ... bench:      71,169 ns/iter (+/- 2,998)
test bench_op_pi_bin  ... bench:      87,043 ns/iter (+/- 3,089)
test bench_op_pi_json ... bench:      85,530 ns/iter (+/- 1,801)
After:
test bench_op_async   ... bench: …
```
=> core: avoid async op future reboxing to bundle PromiseId

op_crates/web/08_text_encoding.js
According to https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder, TextEncoder should ignore the "encoding" parameter and always use "utf-8". It seems the current implementation already uses "utf-8" unconditionally.
Even if it didn't, a JS implementation of UTF-8 encoding is used, so it is better to leave only the rust implementation which is more efficient.
=> refactor(op_crates/web): Remove unused code path in TextEncoder

Cargo.lock, cli/file_fetcher.rs, op_crates/fetch/Cargo.toml, op_crates/fetch/lib.rs, op_crates/file/lib.rs, tools/wpt/expectation.json
This commit adds blob URL support in `fetch`. Tested via WPT. This is
the first op_crate to have a rust dependency on a different op_crate.
=> feat: blob URL support in fetch

cli/tests/unit/console_test.ts, op_crates/console/02_console.js
Fixes #10111
The behaviour for the second example in the issue (`console.table([ {a:0}, {a:1,c:1}, {a:2}, {a:3,c:3} ], ['a','b','c']);`) varies between browsers; this implementation is just the way which made the most sense to me. It matches the behaviour of Node and Safari. Chromium excludes the `b` column entirely, and Firefox orders them as `a, c, b` rather than `a, b, c`.
=> fix(op_crates/console): console.table value misalignment with varying keys

cli/tests/unit/test_util.ts, cli/tests/unit/timers_test.ts, runtime/js/11_timers.js
=> fix(runtime/js/timers): Use (0, eval) instead of eval()

runtime/permissions.rs
By converting `log_perm_access()` to a macro, so the message sub-expression is dropped at compile time in release mode. Otherwise it made allocations and added substantial overhead to opcalls.
Measured on `perf_now` (`op_now`) from `deno_common`:
```
Before:
perf_now:                n = 5000000, dt = 2.429s, r = 2058460/s, t = 485ns/op
After:
perf_now:                n = 5000000, dt = 1.773s, r = 2820079/s, t = 354ns/op
```
=> perf(runtime): optimize PermissionState::check

cli/tests/unit/http_test.ts, runtime/js/40_http.js
We were using a `for ... in` loop on a `Headers` object.
=> fix(runtime/js/http): Correctly parse user response headers

core/benches/op_baseline.rs, core/lib.rs, core/minvalue.rs, core/ops.rs, core/runtime.rs
This introduces `SerializablePkg` and `MinValue` as a fastpath for ops that return primitives, allowing us to save an alloc/free per opcall. This reduces async-op baseline overhead by ~20% or ~100ns/opcall.
⚠️ **Warning:** This uses `unsafe` code (`std::mem::transmute_copy`) and TypeId checks in lieu of specialization to detect primitives and opt-in to the fast path
```
Before:
test bench_op_async   ... bench:     489,671 ns/iter (+/- 8,368)
test bench_op_nop     ... bench:      71,506 ns/iter (+/- 1,612)
test bench_op_pi_json ... bench:      84,846 ns/iter (+/- 1,464)
After:
test bench_op_async   ... bench:     384,175 ns/iter (+/- 7,553)
test bench_op_nop     ... bench:      47,984 ns/iter (+/- 2,083)
test bench_op_pi_json ... bench:      59,100 ns/iter (+/- 1,868)
```
=> perf(core/ops): avoid allocs when returning primitives

op_crates/fetch/26_fetch.js
Which was unnecessarily wasteful and taking up 5% of the JS CPU time in the `deno_http_native` bench.
It's not clear why `byteUpperCase()` was useful, especially since we only return the uppercased method if it matches a whitelist of unambiguous strings.
=> perf(fetch): optimize normalizeMethod()

op_crates/fetch/26_fetch.js, runtime/js/40_http.js
This commit introduces a performance optimization for the native HTTP
server. From my testing it is about 2-6% faster than `main`. Request
headers in the HTTP servers are now lazilly instatated when they are
accessed, rather than being preemptively wrapped in the `Headers` class.
=> perf: lazy header instantiation for HTTP requests

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/net_test.ts
=> feat(cli/dts): stricter typings for Listener & Conn

cli/dts/lib.deno.unstable.d.ts, runtime/js/40_http.js
=> fix(cli/dts): Make respondWith() return a Promise

cli/main.rs, cli/main_runtime.rs, cli/unix_util.rs
Raise the soft limit to the hard limit when possible. This is similar
to what Node.js does to avoid running into "out of file descriptors"
errors too quickly.
On most Linux systems, raises the limit from 1,024 to 1,048,576.
On most macOS systems, raises the limit from 256 to 10,240.
Fixes #10148.
=> feat(cli): raise file descriptor limit on startup

runtime/js/40_http.js
```
[bailout (kind: deopt-soft, reason: Insufficient type feedback for generic named access): begin. deoptimizing 0x21fa08605435 <JSFunction next (sfi = 0x21fa0840e5e5)>, opt id 10, bytecode offset 76, deopt exit 2, FP to SP delta 64, caller SP 0x00016b5902b8, pc 0x21fa000901bc]
;;; deoptimize at <deno:runtime/js/40_http.js:84:48>
```
- There's still at least another v8 deopt in the http callstack, that I haven't optimized yet
=> perf(js/http): avoid v8 deopt in async iterator

Cargo.lock, Cargo.toml, op_crates/timers/01_timers.js, op_crates/timers/Cargo.toml, op_crates/timers/README.md, op_crates/timers/lib.rs, runtime/Cargo.toml, runtime/build.rs, runtime/ops/timers.rs, runtime/permissions.rs
Move timers out of runtime/ and into a standalone op crate.
<hr>
The diff looks biggish but it's mostly moving code around.
=> refactor: move timers to deno_timers op crate

cli/tests/unit/http_test.ts, runtime/js/40_http.js, runtime/ops/http.rs
fixes https://github.com/denoland/deno/issues/10182
=> fix(#10182): hang during http server response

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, runtime/js/40_tls.js
Fixes #10200 by widening the type accepted by `Deno.startTls()`.  There is an extra runtime guard to compensate for the weakend types.
=> fix(#10200): weaken  types so non-breaking

cli/flags.rs
Reorganizes subcommand & arg declarations & corresponding parse functions as they currently are all over the place. Order is subcommands alphabetically > args > parse. Parse functions are in the same order as subcommands & args.
Vastly simplifies working on (and in future, reviewing) #8617
=> refactor(cli/flags): reorganize declarations

cli/lsp/registries.rs
1. error: called `.iter().count()` on a `Vec`
(https://rust-lang.github.io/rust-clippy/master/index.html#iter_count)
2. error: inconsistent struct constructor
(https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_struct_constructor)
=> lint(cli/lsp): fix 2 lint errors

serde_v8/src/ser.rs
This fixes a new clippy lint warning: [inconsistent struct constructor](https://rust-lang.github.io/rust-clippy/master/index.html#inconsistent_struct_constructor)
=> lint(serde_v8): fix "inconsistent struct constructor"

core/bindings.rs, core/zero_copy_buf.rs
Also cleanup `bindings::deserialize()/decode()` so they use the `ZeroCopyBuf` abstraction rather than reimplementing it
This cleanup will facilitate moving `ZeroCopyBuf` to `serde_v8` since it's now self contained and there are no other `get_backing_store_slice()` callers
=> refactor(core): remove ZeroCopyBuf's dep on the bindings mod

cli/ops/mod.rs
These functions were unnecessarily duplicated
=> cleanup(cli): use runtime's reg_sync() and reg_async()

Cargo.lock, op_crates/url/Cargo.toml, op_crates/url/benches/url_ops.rs
This PR adds url parsing benches in `op_crates/url` named `url_ops`, which allow for scoped & fast iteration on url parsing performance (since the builds take ~30x less time to build than full deno bins).
This does a decent job at showcasing `bench_util` (#10223) outside of `op_baseline` and how in ~30 lines you can put together benches to track op performance that also generate clean profiles when `flamebench`'d.
```
test bench_url_parse ... bench:   5,822,207 ns/iter (+/- 231,035)
```
**Note:** this follows the same convention of 1000 real iters per bench iter as `op_baseline`, so just right shift 3 digits when reading these results.
As a sanity check we can see that these benches ~match the output of `deno_common`:
```
url_parse:           	n = 50000, dt = 0.290s, r = 172414/s, t = …
```
=> bench(url): basic url_ops bench

cli/tests/integration_tests.rs, cli/tests/workers/nonexistent_worker.out, cli/tests/workers/nonexistent_worker.ts, runtime/web_worker.rs
Fixes #10235
The panic was caused by the lack of an error class mapping for `futures::channel::TrySendError`, but it shouldn't have been throwing an error in the first place - when a worker has terminated, `postMessage` should just return. The issue was that the termination message hadn't yet been recieved, so it was carrying on with trying to send the message. This adds another check on the Rust side for if the channel is closed, and if it is the worker is treated as terminated.
=> fix(runtime): handle race condition in postMessage where worker has terminated but termination message has not been recieved

cli/tests/unit/http_test.ts, runtime/ops/http.rs
This commit fixes the URL returned from `request.url` in the HTTP server
to be fully qualified. This previously existed, but was removed and
accidentially not readded during optimizations of the HTTP ops.
Returning a non fully qualified URL from `Request#url` is not spec
compliant.
=> fix(rt/http): correct URL in Request

cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/performance.rs, cli/lsp/sources.rs
This PR improves the output of the LSP's diagnostic status page, which will help try to narrow down some issue that have been occurring.  The status page now looks something like this:
It provides an expandable list of the files "open", cached sources, and performance measures.  It also provides the averages of measurements in a table format now.
=> feat(lsp): improve diagnostic status page

cli/lsp/documents.rs, cli/lsp/language_server.rs
Fixes #10125
This was a "simple" fix, but creating a test that fails meant I had to restructure the test harness to be able to pass a fixture that is "dynamic", which was a lot more complex.
=> fix(#10125): remove documents when closed in the lsp

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/net_test.ts, runtime/js/40_tls.js
This reverts a8057e3e06962a8d7c6330a085704bb4493eed04 and 9c7c9a35c12625bd4793c21539391d6b08d17e73 which introduced breaking changes.
=> revert: Conn type changes in #10012 and #10061

Cargo.lock, cli/tests/077_fetch_empty.ts.out, cli/tests/unit/body_test.ts, cli/tests/unit/fetch_test.ts, cli/tests/unit/request_test.ts, op_crates/fetch/20_headers.js, op_crates/fetch/21_formdata.js, op_crates/fetch/22_body.js, op_crates/fetch/22_http_client.js, op_crates/fetch/23_request.js, op_crates/fetch/23_response.js, op_crates/fetch/26_fetch.js, op_crates/fetch/internal.d.ts, op_crates/fetch/lib.rs, op_crates/url/00_url.js, op_crates/url/Cargo.toml, op_crates/url/internal.d.ts, op_crates/url/lib.rs, op_crates/web/00_infra.js, op_crates/web/01_mimesniff.js, op_crates/web/03_abort_signal.js, op_crates/web/internal.d.ts, op_crates/webgpu/02_idl_types.js, op_crates/webidl/00_webidl.js, runtime/js/40_http.js, runtime/js/99_main.js, runtime/ops/http.rs, tools/wpt/expectation.json, tools/wpt/runner.ts
This commit aligns the `fetch` API and the `Request` / `Response`
classes belonging to it to the spec. This commit enables all the
relevant `fetch` WPT tests. Spec compliance is now at around 90%.
Performance is essentially identical now (within 1% of 1.9).
Closes #10002
=> chore: align fetch to spec

docs/getting_started/webassembly.md
Adds example code for how to use deno with .wasm files.
Not sure if something else is preffered over `readAll()` from `io/util.ts`, but it's what worked for me.
=> docs(manual/wasm): add more example code.

cli/tools/upgrade.rs
This very tiny PR just fixes a minor annoyance that has irked me (admittedly more than it should) when doing a `deno upgrade`:
```
Looking up latest version
Found latest version 1.9.1
Checking https://github.com/denoland/deno/releases/download/v1.9.1/deno-x86_64-unknown-linux-gnu.zip
Download has been found
Deno is upgrading to version 1.9.1
Archive:  /tmp/.tmp17l6Z9/deno..zip
inflating: deno                    
Upgraded successfully
```
Note that the archive path is `/tmp/.tmp17l6Z9/deno..zip` with `..zip` :scream:.
This is simply because [`PathBuf::with_extension`](https://doc.rust-lang.org/std/path/struct.Path.html#method.with_extension) expects the extension to not be prefixed by `.`. Other usages in the codebase (such as `.with_extension(exe_ext)` on the line below) already do this …
=> fix(runtime/cli): Remove double '.' from temporary archive extension on upgrade

cli/fs_util.rs, cli/tests/dont_panic_not_found_cwd.ts, cli/tests/integration_tests.rs, cli/tools/installer.rs, runtime/fs_util.rs, runtime/ops/runtime.rs, runtime/web_worker.rs, runtime/worker.rs
This PR replaces all instances of `current_dir().unwrap()` with `current_dir()?` except the ones in the tests and `core/module_sepcifier.rs`.
Closes https://github.com/denoland/deno/issues/9840
=> fix: do not panic on not found cwd

docs/examples/http_server.md, docs/runtime.md, docs/runtime/http_server_apis.md, docs/toc.json
Convert the example HTTP Server to use the Deno HTTP Server API and add a section to the Deno APIs about the HTTP Server APIs.
=> docs: document Deno's HTTP Server API

core/bindings.rs, core/core.js, core/runtime.rs
`init()` was previously needed to init the shared queue, but now that it's gone `init()` is only used to setup JsRuntime's `js_recv_cb`.
=> refactor(core): kill recv() and init()

bench_util/src/js_runtime.rs, cli/tsc/99_main_compiler.js, core/benches/op_baseline.rs, core/core.js, core/examples/hello_world.rs, core/examples/http_bench_json_ops.js, core/ops_json.rs, op_crates/url/benches/url_ops.rs, runtime/js/99_main.js
This PR simplifies error handling in `core.js`. v8 builtin errors are registered by default so new runtimes no longer need to bootstrap with:
```
Deno.core.registerErrorClass('Error', Error);
```
One less gotcha when bootstrapping runtimes
(consumers must provide a constructor with custom args, core simply provides msg arg)
=> refactor(core): simplify error handling

.github/workflows/ci.yml
This PR tries to separate CI cache into 2 pieces: one for Cargo home (~/.cargo) and one for build output (./target). And inside cargo home this change only caches necessary part of it.
=> ci: separate cache for cargo home and build output

op_crates/webgpu/bundle.rs, op_crates/webgpu/render_pass.rs
Due to this, currently a few webgpu examples dont work. Was introduced in #9944
=> fix(op_crates/webgpu): move non-null op buffer arg check when needed

cli/tools/standalone.rs
Remove old bin before writing new bin when generating `deno compile` standalone binaries, fixes #10310
With this PR's fix we no longer see the crash when running #10310's reproducible cases:
```
❯ cat <<EOF | bash
rm ./hello ./hello.js &>/dev/null
echo "console.log('Hello Dev')" > hello.js
./target/debug/deno compile --unstable hello.js
ls -hal ./hello
shasum ./hello
./hello
./target/debug/deno compile --unstable --lite hello.js
ls -hal ./hello
shasum ./hello
./hello
rm ./hello ./hello.js &>/dev/null
EOF
Bundle file:///Users/aaron/git/deno/hello.js
Compile file:///Users/aaron/git/deno/hello.js
Emit hello
-rwxrwxrwx  1 aaron  staff   244M Apr 22 12:06 ./hello
409ba1af12e17141c585d708244a8bb856df9965  ./hello
Hello Dev
Bundle file:///Users/aaron/git/deno/hello.js
Compile …
```
=> fix(cli): standalone bin corruption

cli/tests/unit/http_test.ts, runtime/js/40_http.js
=> fix(runtime/js/http): Cancel body on response failure

cli/tests/unit/request_test.ts, op_crates/fetch/23_request.js
Fixes #10334
If there is any contextual data to change, please let me know if I missed it.
=> fix(op_crates/fetch): Prevent throwing when inspecting a request

.github/workflows/ci.yml
Because CI is so slow on for OSX and Windows, we should only run WPT on Linux.
=> ci: only run WPT on linux

cli/dts/lib.deno.unstable.d.ts
Per its name it's synchronous for the current thread
=> fix(cli/dts): sleepSync doesn't return a Promise

core/runtime.rs
We previously made a strong distinction between isolates created for snapshotting and those not. I'm not sure that distinction is meaningful/useful anymore. We store relatively minimal shared state now, without the shared queue.
In Deno CLI we only create "opless" JsRuntimes when snapshotting, but I think removing that disparity would make them less of an edge-case and could allow interesting use-cases for end-users & embedders. We're also somewhat underusing snapshots, essentially "only" using them to preload builtin JS code and the initial JS bootstrap.
One could easily imagine how this could allow snapshots to be used with `deno compile` and enable users to do relatively heavy & complex init using regular Deno code (e.g: reading in files, prefetching network data, etc... at "compile …
=> feat(core): allow async opcalls in snapshots

bench_util/src/js_runtime.rs, cli/build.rs, cli/lsp/tsc.rs, cli/main.rs, cli/tsc.rs, cli/tsc/99_main_compiler.js, core/benches/op_baseline.rs, core/core.js, core/examples/hello_world.rs, core/examples/http_bench_json_ops.js, core/examples/http_bench_json_ops.rs, core/ops_json.rs, core/runtime.rs, op_crates/url/benches/url_ops.rs, runtime/js/99_main.js, runtime/web_worker.rs, runtime/worker.rs
Even if bootstrapping the JS runtime is low level, it's an abstraction leak of core to require users to call `Deno.core.ops()` in JS space.
So instead we're introducing a `JsRuntime::sync_ops_cache()` method, once we have runtime extensions a new runtime will ensure the ops cache is setup (for the provided extensions) and then loading/unloading plugins should be the only operations that require op cache syncs.
This also splits `Deno.core.ops()` into `Deno.core.syncOpsCache()` and `Deno.core.ops()`, which respectively sync the ops cache and return the ops cache without syncing it (useful for debugging or testing)
=> refactor(core): move op cache sync responsibility to rust space

cli/dts/lib.deno.unstable.d.ts, cli/module_graph.rs, cli/ops/runtime_compiler.rs, cli/tests/compiler_api_test.ts, docs/typescript/runtime.md, runtime/js/40_compiler_api.js
=> BREAKING(unstable): Rename Deno.emit() bundle options to "module" and "classic"

cli/tests/unit/tls_test.ts, core/error.rs, op_crates/websocket/lib.rs, runtime/ops/tls.rs
`InvalidDNSNameError` is thrown when a string is not a valid hostname,
e.g. it contains invalid characters, or starts with a numeric digit. It
does not involve a (failed) DNS lookup.
=> fix(tls): throw meaningful error when hostname is invalid

cli/dts/lib.deno.ns.d.ts
This PR fixes the example in the jsdoc of `ftruncateSync`.
closes https://github.com/denoland/doc_website/issues/191
=> docs: fix ftruncateSync example

.github/workflows/ci.yml
Currently we specify `--all-targets` when building. It's equivalent of `--lib --bins --tests --benches --examples` (ref: https://doc.rust-lang.org/cargo/commands/cargo-build.html#target-selection ), but in test release jobs, we don't need to build everything. So this PR reduces build target to only `--bin deno --bin test_server` in build phase, and reduces test targets to ` --bins --lib --tests`.
This skips the building of benches and examples in test release jobs.
=> ci: build and test only selected targets

core/extensions.rs, op_crates/console/lib.rs, op_crates/crypto/lib.rs, op_crates/fetch/lib.rs, op_crates/file/lib.rs, op_crates/timers/lib.rs, op_crates/url/lib.rs, op_crates/web/lib.rs, op_crates/webgpu/lib.rs, op_crates/webidl/lib.rs, op_crates/websocket/lib.rs, runtime/metrics.rs
Builder pattern is more flexible and expressive than the old constructors
Follow-up to #9800
=> refactor(extensions): reintroduce builder

.github/workflows/ci.yml
This reverts commit 48659c374d769b877905827362387da48cf57a9c.
50 minute mac build on docs-only change https://github.com/denoland/deno/runs/2462335233 
Notice 14m "test release" build. If you know how to avoid without reverting, please raise a PR to correct and close this one.
Merge on approval
=> Revert "ci: build only lib and bins (#10401)"

cli/tools/test_runner.rs
This moves test reporting into a trait in preparation for supporting more reporters, like json and terse.
The output remains unchanged and there's still room to clean up some small things later.
=> refactor(cli): move test reporting into a trait

cli/tests/unit/fetch_test.ts, op_crates/fetch/23_request.js
Fixes a pesky bug in the fetch implementation where if the init part is
specified in `fetch` instead of the `Request` constructor, the
fillHeaders function receives two references to the same object, causing
it to append to the same list being iterated over.
Fixes #10396
=> fix(op_crate/fetch): infinite loop on fill headers

Cargo.lock, cli/Cargo.toml, cli/flags.rs
This defaults to num_cpu's when no value is given for jobs, matching most implementations of -j, --jobs in the wild.
I had this hardcoded to two because there's a nightly function in std for getting the number of hardware threads, but nightlies can take forever to be stable so added a dependency on num_cpu's in the meantime.
=> fix(cli): default to num cpus when no value is given to `--jobs`

core/ops_builtin.rs, core/runtime.rs, runtime/web_worker.rs, runtime/worker.rs
Treats builtin ops (`op_resources`, `op_close`) and js (`core.js`, `error.js`) as a regular `JsRuntime` `Extension` that's always loaded (first, see the `.insert(0 ...`)
This guarantees that `op_close`, `op_resources` (and `op_print` with #10436) are ready to use after `JsRuntime::new`
Though builtins are special, they're not "that special", streamlining them will simplify things like moving JS src off heap generically for all extension provided JS without having to treat `core.js`, `error.js` as edge cases
- Now that the builtin ops are registered by default, the first op registered by the user after `JsRuntime::new` will no longer have an `OpId` of 1 since those builtin ops will have taken those slots. I fixed the tests that relied on that assumption and in general it's strongly …
=> refactor(core): provide builtins as an Extension

core/bindings.rs, docs/contributing/web_platform_tests.md
This is my first pull request in Deno.
I fixed one typo in the Throwed Error and one in contribution docs. 
Thanks.
=> Fixed Spelling in throwed error and contribution docs

docs/contributing/building_from_source.md
This removes wasm and wasi as prerequisites, as they haven't been since
we stopped building the wasi test suite from source which dates back
quite some time now.
I removed it from the CI back then but forgot to update the docs.
ref: #7512
=> docs: remove wasm and wasi as prerequisites

runtime/lib.rs
Very small change, I guess this is a minor "regression" that happened when we refactored timers out to its own crate.
=> chore(runtime): re-export deno_timers like all other deno crates

cli/lsp/tsc.rs, cli/tsc.rs
Makes the codebase more searchable and helps distinguish op functions from helper functions
Besides tests/examples/benches this convention appears to be followed everywhere else in the codebase
=> cleanup(cli): prefix all op functions with op_

cli/tests/test/deno_test_only.ts.out, cli/tests/test/quiet_test.out, cli/tools/test_runner.rs
Before:
```
running 1 tests from file://...
```
After:
```
running 1 test from file://...
```
=> fix: change inflection depending on number of pending tests

runtime/ops/fs.rs, runtime/ops/fs_events.rs, runtime/ops/http.rs, runtime/ops/io.rs, runtime/ops/net.rs, runtime/ops/os.rs, runtime/ops/permissions.rs, runtime/ops/plugin.rs, runtime/ops/process.rs, runtime/ops/runtime.rs, runtime/ops/signal.rs, runtime/ops/tls.rs, runtime/ops/tty.rs, runtime/ops/web_worker.rs, runtime/ops/worker_host.rs, runtime/web_worker.rs, runtime/worker.rs
Refactors `runtime/` to use the new `JsRuntime` `Extension`s landed in #9800, paves a first path for a more modular `runtime/` and streamlines worker init logic (having both web `extensions/` and `runtime/` init'd declaratively instead of imperatively)
- This refactoring doesn't include the runtime JS in Extensions, that will require more work, to avoid bugs and duplicating logic with snapshots
- For now we depend on `runtime/`'s JS to be provided via the snapshot, no different than in `main`
- However I think we should clean this up & decouple it, so we can boot a `Worker` without depending on that snapshot
=> refactor(runtime): use Extensions

cli/bench/deno_http_native.js
`Deno.core.*` is unstable and not fit for public consumption, although this is a somewhat internal bench some people may use it as reference code and start using `Deno.core.encode()` in their own code
=> cleanup(bench/deno_http_native): don't use Deno.core funcs

cli/tests/unit/fetch_test.ts, extensions/fetch/26_fetch.js, tools/wpt/expectation.json
Related to https://github.com/denoland/deno/pull/10203
Checks that fetch receives at least one arguement.
Relevant WebIDL:
```
partial interface mixin WindowOrWorkerGlobalScope {
[NewObject] Promise<Response> fetch(RequestInfo input, optional RequestInit init = {});
};
```
\- https://fetch.spec.whatwg.org/#fetch-method
`input` must be present.
=> fix(op_crates/fetch): check fetch() argument length 

core/ops_builtin.rs
Stderr is unbuffered on Linux/macOS (so doesn't need to be flushed), but I think it's undefined on Windows
Follow up to https://github.com/denoland/deno/pull/10436#pullrequestreview-650053348
=> fix(core/print): flush stderr

cli/dts/lib.deno.ns.d.ts
Truncate examples are using const and re-declaring in a single code block with multiple examples.
This splits them into using one code blocks per example program.
=> docs: use one code block per truncate example

cli/dts/lib.deno.ns.d.ts
The `writeAll`  examples are using const and re-declaring in a single code block with multiple examples.
This splits them into using one code blocks per example program.
=> docs: use one block per writeAll example

cli/tests/integration_tests.rs
ref: #10502
Prints the command output of "compile_windows_ext" to check what happens when the test is failed in CI.
=> test(compile): show command output to testing log for debugging purpose

docs/runtime/http_server_apis.md
I'm not sure if I understand it correctly. However, checking a promise in an `if` statement always returns `true` since it's an object. Would make more sense if it's awaited.
Please close if I'm missing anything.
=> docs(runtime): fix HTTP server example

cli/bench/lsp.rs, cli/lsp/diagnostics.rs
Resolves #10518
This PR refactors code so that diagnostics are published for each source "independently" when they become available.  While this increases the amount of data from the lsp to the client, it significantly improves the user perception of the "speed" of the diagnostics, as lint and module dependency diagnostics are available much quicker than TypeScript diagnostics.
=> refactor(lsp): publish diagnostics independently

Cargo.lock, test_plugin/Cargo.toml, test_plugin/src/lib.rs, test_plugin/tests/integration_tests.rs, test_plugin/tests/test.js
This PR add tests for plugin args with the new runtime extensions introduced in #9800.
=> feat(plugin): add tests for plugin args

test_util/src/lib.rs
Remove a function that was forgotten in commit 2638aa03a5 from January.
=> chore(test): remove unused function

cli/tests/integration_tests.rs
Disabling `deno test --watch` test on Windows as it is flaky; failures:
- https://github.com/denoland/deno/pull/10481/checks?check_run_id=2543043090
- https://github.com/denoland/deno/runs/2542717077
CC @Liamolucko
=> test: run deno test --watch test only on unix

.github/workflows/ci.yml
This PR improves the CI cache in the following ways:
- main branch always creates fresh `./target` cache (The cache key has `github.sha` at the end)
- PR branch uses the latest main branch cache.
With this change, main branch always creates fresh cache and PR branches can use the latest one. So the PR branch's build amount should be consistently minimal.
---
Note1: This change prevents the false detection of stale files, which, for example, happened in this run https://github.com/denoland/deno/runs/2462335233 where only one markdown file was changed, but 45 files were considered 'stale' at mtime restore step.
Note2: This PR uses `actions/cache@03e00da99d75a2204924908e1cca7902cafce66b` which is the merge head of https://github.com/actions/cache/pull/489 . cf `git ls-remote …
=> ci: create cache always in main, skip saving cache in PRs

cli/logger.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/performance.rs, cli/lsp/tsc.rs, cli/main.rs, cli/tsc.rs
Ref: #10368
The lsp would respect a setting which will log all the marks and measures to stderr along with their arguments which can be used to investigate certain issues (as well as more easily generate test cases).  This requires a client which can pass the configuration option (see: denoland/vscode_deno#406).
=> feat(lsp): add internal debugging logging

.github/workflows/ci.yml
rustc 1.52.1 was released with the bug fix in incremental compilation. Should be good to upgrade to it.
=> chore: upgrade Rust to 1.52.1

cli/bench/lsp.rs, cli/lsp/config.rs, cli/lsp/language_server.rs
This disables the workspace folder configuration functionality to work-around the deadlock issue introduced in #10488.
=> fix(#10603): revert minimal changes to resolve deadlock bug

cli/file_fetcher.rs, test_util/src/lib.rs
This PR changes the behavior of file_fetcher. Now file_fetcher doesn't follow the dts script referenced from `x-typescript-types` header when the script is not javascript or jsx.
Currently deno fetches dts file in x-typescript-types even when the script is typescript (you can check the behavior with this repro url `https://no-cache-script-repro-bf1c801d.deno.dev/foo.ts`), but dts only makes sense for javascript and jsx. So this PR prevents such redundant dts loading.
closes https://github.com/denoland/deno/issues/10279
=> fix(cli): ignore x-typescript-types header when media type is not js/jsx

cli/dts/lib.deno.unstable.d.ts, cli/lsp/language_server.rs
The default branch was changed from `master` to `main` a while ago. This link needs to follow the change.
=> docs(cli/dts): fix link from master to main

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, extensions/fetch/Cargo.toml, extensions/timers/Cargo.toml, extensions/webgpu/Cargo.toml, extensions/websocket/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
Tokio 1.6.0 was released with various improvements, so upgrades it from 1.4.0 to 1.6.0.
release notes:
- [1.5.0](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.5.0)
- [1.6.0](https://github.com/tokio-rs/tokio/releases/tag/tokio-1.6.0)
=> chore: upgrade Tokio to 1.6.0

core/core.js, core/ops_builtin.rs
Following #10448, flattening op args when possible is a best practice (since opcalls should conceptually be thought of as plain function calls)
=> cleanup(core): flatten print's op args

core/examples/hello_world.rs
Also avoids duplicate op errors, fixes #10632
=> cleanup(core/example/hello_world): use Deno.core.print instead of new op

cli/tsc/99_main_compiler.js
Closes https://github.com/denoland/deno/issues/10575
=> fix(lsp): skip type definition not found diagnostic

cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/tests/integration_tests_lsp.rs, cli/tools/fmt.rs
=> feat(lsp): support formatting json and markdown files

cli/ast.rs, cli/config_file.rs, cli/module_graph.rs, cli/tests/compiler_api_test.ts
This PR adds support for source maps to `Deno.emit` when the bundle option is used. By default, a corresponding `deno://bundle.js.map` file is produced matching the behavior of `Deno.emit` without the bundle option. You can opt for inline source map by passing `inlineSourceMap: true` to the config.
Closes https://github.com/denoland/deno/issues/10413
=> feat(Deno.emit): support source maps with bundle option

extensions/webstorage/01_webstorage.js, extensions/webstorage/Cargo.toml, extensions/webstorage/lib.rs
=> fix(extensions/webstorage): use opstate for sqlite connection

.github/workflows/ci.yml
In #10560, `shell` property wasn't set in `Skip save cache (PR)` step. So it's run in powershell in windows and `$GITHUB_ENV` part doesn't work, and therefore `Post Cache build output (PR)` step is not skipped in window. ex. https://github.com/denoland/deno/pull/10703/checks?check_run_id=2618387702
This PR fixes it by specifying `shell: bash`.
`Post Cache build output (PR)` step usually takes 4+ mins. So this fix should reduces typical windows CI time 4 mins.
=> ci: fix 'Skip save cache' step in windows CI

cli/bench/lsp.rs, cli/lsp/config.rs, cli/lsp/diagnostics.rs, cli/lsp/language_server.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/initialize_params.json, cli/tests/lsp/initialize_params_disabled.json, cli/tests/lsp/initialize_params_registry.json, cli/tests/lsp/initialize_params_unstable.json
This PR rewrites the way per resource configuration is handled in the language server.
There isn't specifically a test that tests for this deadlock yet, as I need to refactor the language server integration tests to a new structure that supports 2 way communication, which we have in the benchmark harness, but need to share with the integration tests.
=> fix(lsp): re-enable the per resource configuration without a deadlock

bench_util/src/js_runtime.rs
Running code in `bench_js_async` with ops that called into `tokio` would previously fail with:
```
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
=> fix(bench_util): correctly run async benches in tokio context

bench_util/benches/op_baseline.rs, bench_util/src/js_runtime.rs, extensions/url/benches/url_ops.rs
Since #9800, Extensions are the preferred way to init JsRuntimes
=> cleanup(bench_util): use Extensions for setup

cli/main.rs, cli/tests/integration_tests.rs
closes #10716 
This PR ensures the coverage dir exists when --coverage options is specified, and fixes panic of `deno test --coverage=<div>` when `<div>` doesn't exist.
Note: `PathBuf::from(coverage_dir).canonicalize()` returns error when the path doesn't exist.
=> fix(test): ensure coverage dir exists

Cargo.lock, Cargo.toml, cli/build.rs, cli/dts/lib.deno.shared_globals.d.ts, cli/main.rs, cli/program_state.rs, cli/standalone.rs, cli/tests/unit/broadcast_channel_test.ts, cli/tests/workers/broadcast_channel.ts, cli/tsc.rs, extensions/broadcast_channel/01_broadcast_channel.js, extensions/broadcast_channel/Cargo.toml, extensions/broadcast_channel/README.md, extensions/broadcast_channel/in_memory_broadcast_channel.rs, extensions/broadcast_channel/lib.deno_broadcast_channel.d.ts, extensions/broadcast_channel/lib.rs, extensions/web/02_event.js, runtime/Cargo.toml, runtime/build.rs, runtime/examples/hello_runtime.rs, runtime/js/99_main.js, runtime/lib.rs, runtime/web_worker.rs, runtime/worker.rs, tools/wpt/expectation.json, tools/wpt/runner.ts
Current approach is wrong and doesn't work
=> feat(extensions): Broadcast Channel API

cli/tests/integration_tests.rs, cli/tests/test/doc.out, cli/tools/test_runner.rs
Colon is reserved in windows so it cannot be in the file-path (see https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#file_and_directory_names).
This replaces `:` with `$` resulting in slightly uglier stack-traces in the short term until source maps are applied.
Closes https://github.com/denoland/deno/issues/10730
=> fix(cli/test): don't use reserved symbol `:` in specifier

cli/lsp/analysis.rs
Currently, the LSP returns only messages from `deno_lint`; hints are omitted even when they are.
Some lint rules are very unfriendly in the sense that their diagnostic messages give no information about how the lint errors should be addressed properly without having to suppress them.
One example is `ban-ts-comment` rule, as its message just tells that the directive is disallowed without comment - when seeing this, one may wonder what "comment" is. While the message is very unclear, the hint is so informative that it gives a concrete example of how to address it, like ``Add an in-line comment explaining the reason for using `@ts-expect-error`, like `// @ts-expect-error: <reason>``
Therefore, it would be very nice to show not only messages but also hints from `deno_lint`. This PR appends …
=> feat(lsp): show hints from `deno_lint` in addition to messages

extensions/fetch/23_request.js
This PR improves the type error message of Request constructor, which occurs when it's constructed with non null body and GET or HEAD method.
The browsers implements this message as:
- Chrome:  `Request with GET/HEAD method cannot have body.`
- Firefox: `HEAD or GET Request cannot have a body.`
- Safari: `Request has method 'GET' and cannot have a body`
=> fix(ext/fetch): fix error message of Request constructor

docs/runtime/http_server_apis.md
I got an error when I was trying to run following code from https://deno.land/manual/runtime/http_server_apis.
```ts
async function handle(conn: Deno.Conn) {
const httpConn = Deno.serveHttp(conn);
for await (const requestEvent of httpConn) {
await requestEvent.respondWith(new Response("hello world"), {
status: 200,
});
}
}
```
```
error: TS2554 [ERROR]: Expected 1 arguments, but got 2.
await requestEvent.respondWith(new Response("hello world"), {
^
at path/to/file.ts:4:65
```
According to the fetch and service worker specs, `{ status: 200 }` is a second argument of [`Response` constructor](https://fetch.spec.whatwg.org/#response-class
) instead of [`respondWith` function](https://w3c.github.io/ServiceWorker/#fetchevent-interface). Following snippet works fine with deno 1.10.1.
```ts
async …
```
=> docs(runtime): fix fetch API usage of HTTP server

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, extensions/fetch/Cargo.toml, extensions/timers/Cargo.toml, extensions/webgpu/Cargo.toml, extensions/websocket/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
Upgrades to Tokio 1.6.1. It is said that this version fixes a bug happening on Linux kernel 5.9 and 5.10.
https://github.com/tokio-rs/tokio/releases/tag/tokio-1.6.1
=> chore: upgrade Tokio to 1.6.1

core/extensions.rs, core/runtime.rs, extensions/timers/benches/timers_ops.rs, extensions/url/benches/url_ops.rs
This speeds up incremental rebuild when only touching JS files by 13-15%
Rebuild time after `touch 01_broadcast_channel.js`:
main: run 1 49.18s, run 2 50.34s
this: run 1 43.12s, run 2 43.19s
The reason for this speedup is that `deno_runtime(build.rs)` does not
need to be rebuilt on every js file change now.
Closes #10786
=> core: don't include_str extension js code

cli/dts/lib.deno.ns.d.ts, cli/tests/unit/fs_events_test.ts, runtime/js/40_fs_events.js
This PR adds `FsWatcher` interface to stable builtin APIs as suggested in #10577. This deprecates `.return?()` method of FsWatcher and instead adds `.close()`. The purpose of this change is to align the API design to other async iterable APIs such as .listen(), listenDatagram() .serveHttp(), .signal().
=> feat: add FsWatcher interface (deprecates .return(), adds .close() instead)

extensions/web/08_text_encoding.js, extensions/web/lib.deno_web.d.ts, tools/wpt/expectation.json
=> feat(web): support the stream option to TextDecoder#decode

cli/lsp/config.rs, cli/lsp/language_server.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/initialize_params_did_config_change.json
When working on a new feature, I discovered a bug where when you make a change to the configuration, some aspects of that change wouldn't be reflected until the server was restarted or the next configuration change.  This was because the workspace configuration was being processed under another thread while the main thread was reading the previous configuration to update features in the LSP.
This now processes the workspace configuration immediately, but processes updates to individual specifier settings in the other thread, which still avoids the deadlock issue which required us breaking it out.
=> fix(lsp): updates to workspace config are processed sync

cli/lsp/README.md, cli/lsp/completions.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/lsp/lsp_custom.rs, cli/lsp/mod.rs, cli/lsp/registries.rs, cli/tests/integration_tests_lsp.rs
Closes: #10194
Fixes: #10468
(this currently includes #10812 which I will rebase once that is merged)
=> feat(lsp): registry auto discovery

cli/file_fetcher.rs, cli/lsp/completions.rs, cli/lsp/diagnostics.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/media_type.rs, cli/tests/integration_tests_lsp.rs
Fixes #10815
This refactors how we determine if we respond to diagnostics, using what is provided by the language server client and doesn't respond for "diagnostic" related APIs for markdown JSON, JSONC.
ping @satyarohith
=> fix(#10815): lsp only responds to formatting for md, json, jsonc

.github/workflows/ci.yml
`gnu tar` is now pre-installed on mac runners. No need of explicit installation step anymore.
CI log shows this:
```
Warning: gnu-tar 1.34 is already installed and up-to-date.
To reinstall 1.34, run:
brew reinstall gnu-tar
```
ref: https://github.com/denoland/deno/runs/2728417623
Merge on approval
=> ci(mac): remove gnu tar installation

extensions/fetch/21_formdata.js, tools/wpt/expectation.json
=> feat(fetch): Implement newline normalization and escapes in the multipart/form-data serialization

cli/tests/unit/http_test.ts, runtime/ops/http.rs
This commit adds "CancelHandle" to "ConnResource" and changes
"op_http_next_request" to await for the cancel signal. In turn
when async iterating over "Deno.HttpConn" the iterator breaks
upon closing of the resource.
Ref https://github.com/denoland/deno/issues/10508
=> fix: hang in op_http_next_request

cli/bench/fixtures/code_lens.ts, cli/bench/lsp.rs, cli/lsp/analysis.rs, cli/lsp/code_lens.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/sources.rs, cli/lsp/tsc.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/code_lens_response_changed.json, cli/tests/lsp/code_lens_response_impl.json
This makes it easier to add the test code lens, but also paves a path to migrate tsc code lenses over to an swc AST and away from the tsc `NavigationTree` AST.
=> fix(lsp): refactor, fix issues and add benchmark for code lens

cli/flags.rs
We've discussed this several times, and 1.11 is high time to stabilize linter.
=> feat: make 'deno lint' stable

.github/stale.yml
This makes [stale bot](https://probot.github.io/apps/stale) comment with a different message on pull requests.
Before, it commented with _This **issue** has been automatically marked as stale_ which is wrong in the context of a pull request.
=> github(probot): Set specific comment for stale PRs

cli/lsp/language_server.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/lib.tsconfig.json
Currently lsp can't read correct --config option in windows. It is a regression because 1.7 didn't have this problem.
Close #10747.
=> fix(lsp): cannot read config option in windows

extensions/webidl/00_webidl.js
This commit optimizes the USVString WebIDL converter. This should solve some of
the perf issue in TextEncoder that the move to encoding in Rust created.
=> chore: optimize USVString webidl converters

.github/workflows/ci.yml, tools/wpt.ts, tools/wpt/runner.ts, tools/wpt/testharnessreport.js, tools/wpt/utils.ts
These reports can be consumed by tools like `wptreport` or
https://wpt.fyi. The old style report could be removed in a future PR
when wpt.deno.land is updated.
=> tests: generate and upload wptreport.json

core/bindings.rs, tools/util.js, tools/wpt/expectation.json, tools/wpt/runner.ts
This means scripts are now run in script context, and there are better
stack traces.
Also fixes a panic in core related to `Deno.core.evalContext`.
=> tests: run wpt scripts with Deno.core.evalContext

cli/lsp/README.md, cli/lsp/code_lens.rs, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/code_lens_response_test.json, cli/tests/lsp/did_open_params_test_code_lens.json, cli/tests/lsp/initialize_params_code_lens_test.json, cli/tests/lsp/initialize_params_code_lens_test_disabled.json
This PR add support for test code lenses, which allow clients to be able to launch the Deno CLI executing specific tests identified in the IDE.
=> feat(lsp): add test code lens

runtime/permissions.rs, tools/util.js
`./tools/lint.js` was never completing on my machine (was fine on WSL, but not Windows). I believe it is due to the stdout buffer of the launched process getting full when `Deno.run` is called.
Fixed by just always reading the output, then checking the status. ~~Seems like some clippy errors surfaced after doing that as well and those are also fixed.~~ Edit: These were Windows only clippy issues. Will fix them as well.
=> chore(tools): Fix stdout buffer of launched process getting full causing tools/lint.js to potentially hang

test_util/src/lib.rs
I was doing...
```
> cargo build
> cargo test
> wsl
$ cargo test
```
...then wondering why I was getting this...
```
---- file_fetcher::tests::test_fetch_cache_only stdout ----
test_server starting...
thread 'file_fetcher::tests::test_fetch_cache_only' panicked at 'failed to execute test_server: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', test_util\src\lib.rs:975:10
---- file_fetcher::tests::test_fetch_complex stdout ----
thread 'file_fetcher::tests::test_fetch_complex' panicked at 'assertion failed: `(left == right)`
left: `2`,
right: `1`', test_util\src\lib.rs:968:7
---- file_fetcher::tests::test_fetch_multiple_redirects stdout ----
thread …
```
=> chore: Instructive message when running the tests and forgetting to build first

cli/lsp/language_server.rs
We have had a few issues where users have had strange environment configurations that have lead to confusion when using the LSP.  This PR adds some additional logging to provide more information in the extension output channel.  It adds the path to the executable and the fully resolved import map and config files.
=> feat(lsp): add additional logging information

cli/tests/fix_worker_dispatchevent.ts, cli/tests/fix_worker_dispatchevent.ts.out, cli/tests/integration_tests.rs, runtime/js/99_main.js
I was working with workers and realised that if your overwrite `dispatchEvent` in the global scope, messages do not get sent to event listeners of `"message"` any longer.  This is because the runtime binds to the global `dispatchEvent` every time it tries to dispatch a message.
I checked that in browsers, if you  override `dispatchEvent` in a worker, messages still get sent to the event listeners, and so I have amended the runtime to bind early to the global `dispatchEvent` and this ensures the behaviour works as expected.
=> fix(runtime): early binding to dispatchEvent in workers

cli/tools/repl.rs
To help myself understand this code I went through and extracted out two new `ReplEditor` and `ReplSession` structs. The code should functionally be the same, but just reorganized.
It is easier to review this PR commit by commit.
This is preparation for adding type stripping to the REPL.
=> refactor(repl): Extract out structs

cli/tests/integration_tests.rs
Fixes:
```
> (Get-Process "deno").count
0
> cargo test
> (Get-Process "deno").count
2
> cargo test # errors
```
=> chore(tests): Kill orphaned deno processes spawned during the tests

cli/tests/089_run_allow_list.ts, cli/tests/integration_tests.rs, test_util/src/lib.rs
`cat` does not exist by default on Windows. GitHub actions adds a lot of stuff to the Windows runner to make it work, which is why the CI is ok (I'm often surprised at what works in there).
=> chore: Fix broken test on Windows

cli/ast.rs, cli/errors.rs, cli/module_graph.rs
1. For type stripping in the REPL it is nicer to get a diagnostic without the file name.
2. There actually will only ever be one diagnostic returned currently, so I removed `DiagnosticBuffer`. We can add back something similar, if we ever look at `parser.take_errors()` for diagnostics.
3. I was confused about what `EmitOptions#check_js` did then realized it was never used for emitting (therefore, not an emit option). I removed this and changed the other code to just look at the value from the tsconfig.json.
=> refactor(swc): Change AST parsing error to return struct with message and location

tools/wpt/runner.ts, tools/wpt/testharnessreport.js
Previously top level errors were swallowed.
Closes #10930
=> fix: propagate top level thrown errors in WPT

cli/dts/lib.deno.unstable.d.ts
Fixes #10919 
The main goal of this PR is to make it very clear to users, that they don't have to write a format function themselves, they would be well aware of `.formatDoagnostics`. Unfortunately, for a while I was using a custom function to create an error message based on each diagnostic.
Also included a note about what would happen if you try format an empty array. Because I was unsure myself: "What if i try format the diagnostics, but no errors were found so the parameter i pass is an empty array?"
=> docs(unstable/emit): Note that for emit, Deno.formatDiagnostics can be used

.github/workflows/wpt_epoch.yml, tools/upload_wptfyi.js, tools/wpt/runner.ts, tools/wpt/utils.ts
This adds a daily scheduled CI pipeline that runs WPT tests against
the most recent epochs/daily every night. Results are uploaded to
wpt.fyi.
WPTs are run on all supported platforms, on both stable and canary.
=> build: add wpt epoch/daily run

cli/tests/unit/http_test.ts, runtime/ops/http.rs
<s>Still need to come up with a test.</s>
Fixes https://github.com/denoland/deno/issues/10940
=> fix: poll connection after writing response chunk in Deno.serveHttp()

Cargo.lock, cli/Cargo.toml
Fixes #10893
Fixes #10954
Related to https://github.com/denoland/deno_lint/pull/732
=> chore: upgrade swc_ecmascript

extensions/console/01_colors.js, extensions/console/02_console.js
**Before**
Command prompt:
Windows terminal:
**After**
Command prompt:
Windows terminal:
Highlighting for `undefined` in the Rust and JS code now both use "grey" instead of "dim" and "grey".
Fixes #9761
=> fix(repl): Fix `undefined` result colour in cmd

cli/dts/lib.deno.shared_globals.d.ts, cli/dts/lib.deno.window.d.ts, cli/dts/lib.deno.worker.d.ts
This fixes issues with the Deno built-in types that prevented the appropriate type checking of web workers when using `addEventListener("message", /* ... */);` plus a few other improvements to align it more to the TypeScript libs.
=> fix(cli): improve worker types

extensions/fetch/20_headers.js, extensions/fetch/23_request.js, extensions/fetch/23_response.js, extensions/fetch/26_fetch.js
This is a minor optimization that removes some header key lowercasing
that previously happened on access, instead moving it to write.
=> refactor: store header keys lower case internally

extensions/timers/lib.rs
=> set minimum timeout to be 4 milliseconds

cli/tests/unit/console_test.ts, extensions/console/02_console.js
I was so confused why proxies weren't working in the inspector when working on a different fix.
Closes #10975.
Note: Target is the first argument provided to the constructor of `Proxy`
=> fix(inspector): Deno.inspect should inspect the object the proxy represents rather than the target

extensions/web/06_streams.js, tools/wpt/expectation.json
Took me 4 hours to find this. The long tail end of compat :-)
See https://github.com/whatwg/streams/pull/1137
I guess we were technically spec compliant before? :wink: 
Fixes #10980
=> fix: closing / aborting WritableStream is racy

.github/workflows/wpt_epoch.yml
Removes dependency on scheduled time being coordinated with wpt upstream.
=> tests: get epochs/daily commit with ./wpt rev-list

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, extensions/broadcast_channel/Cargo.toml, extensions/crypto/Cargo.toml, extensions/fetch/Cargo.toml, extensions/timers/Cargo.toml, extensions/webgpu/Cargo.toml, extensions/websocket/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
Upgrades to Tokio v1.7.0, which has just been out: https://github.com/tokio-rs/tokio/releases/tag/tokio-1.7.0
=> chore: upgrade Tokio to 1.7.0

docs/contributing/style_guide.md
Along with fixing #11004, this PR also removes or replaces any mentions of `cli/js` under the `Typescript` section as that folder no longer appears to exist and AFAIK any TS has been replaced with JS a while back. I could make a `Javascript` section for any JS code but I don't believe that is necessary as it'd be mostly repeating the Typescript section.
=> docs(contributing/style_guide) Fix #11004 and remove mentions of `cli/js`

.github/workflows/ci.yml, cli/bench/main.rs, cli/disk_cache.rs, cli/lsp/language_server.rs, cli/specifier_handler.rs, core/async_cancel.rs, core/bindings.rs, core/error.rs, runtime/ops/io.rs, runtime/web_worker.rs, runtime/worker.rs, test_util/src/lib.rs
Upgrades to Rust 1.53.0 and fix the code according to clippy.
=> chore: upgrade Rust to 1.53.0

cli/flags.rs, cli/lsp/mod.rs, cli/lsp/parent_process_checker.rs, cli/main.rs
This PR adds a new `--parent-pid <pid>` flag to `deno lsp` that when provided starts a task that checks for the existence of the provided process id (ex. vscode's) every 30 seconds. If the process doesn't exist (meaning the deno process has nothing interacting with it), then it terminates itself.
I am  not familiar with what the best way to check if a process is running on linux/mac. I am also not that familiar with win api. Please let me know if there is a better way of doing what's done in here.
Closes #11019
=> chore(lsp): Add `--parent-pid <pid>` flag

cli/lsp/parent_process_checker.rs
Funny that all the new linting errors were in the code I just committed.
=> chore: fix new linting errors flagged by Rust 1.53

extensions/fetch/26_fetch.js, test.ts, tools/wpt/expectation.json
HEAD and OPTIONS requests should not have bodies https://fetch.spec.whatwg.org/#concept-main-fetch
=> fix(extension/fetch): Fetching with method HEAD should not have body

cli/dts/lib.deno.shared_globals.d.ts, cli/tests/workers/test.ts
This commit updates type declarations for Worker to accept specifiers
as either strings or URL, bringing it in line with TypeScript
declarations and browser behavior.
Fixes https://github.com/denoland/deno/issues/11037
=> fix: Worker accepts specifier as URL

docs/getting_started/installation.md
Docs update to include a link to the official docker images repo. 
Related Issue #11026
=> docs(installation): Add official docker images link

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, extensions/broadcast_channel/Cargo.toml, extensions/crypto/Cargo.toml, extensions/fetch/Cargo.toml, extensions/timers/Cargo.toml, extensions/webgpu/Cargo.toml, extensions/websocket/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
Tokio 1.7.1 has just been released. https://github.com/tokio-rs/tokio/releases/tag/tokio-1.7.1
=> chore: upgrade Tokio to 1.7.1

cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/integration_tests_lsp.rs
Fixes https://github.com/denoland/vscode_deno/issues/450
This functionality is not the default with TypeScript so I believe this is a bug and we shouldn't do it.
=> fix(lsp): do not rename in strings and comments

core/README.md
The README had confused me while I was studying `deno_core`
=> docs(core): replaces dispatch references with op

cli/lsp/analysis.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/code_action_ignore_lint_params.json, cli/tests/lsp/code_action_ignore_lint_response.json
Introduces quick-fix actions to ignore lint errors.
https://user-images.githubusercontent.com/29819102/122170586-5a4abe80-ce9c-11eb-95b7-a1c939ffdd70.mp4
Closes #10122
=> feat(lsp): quick fix actions to ignore lint errors

cli/dts/lib.deno.unstable.d.ts
This was added in TypeScript 4.3 but we neglected to reflect it in the `Deno.CompilerOptions` interface.
=> fix: add support for module es2020 to Deno.emit

cli/main.rs, cli/standalone.rs, core/runtime.rs, runtime/examples/hello_runtime.rs, runtime/web_worker.rs, runtime/worker.rs
This commit changes "deno_core::JsRuntime" to always create
"deno_core::JsRuntimeInspector" instance.
<s>__Need to check if this commit has impact on startup and memory benchmarks__</s>
Seems there is no visible impact, however if benchmarks tank after this PR is merged, I will revert it.
=> refactor(core): always attach inspector to isolate

Cargo.lock, cli/dts/lib.deno.shared_globals.d.ts, cli/tests/unit/message_channel_test.ts, extensions/web/02_event.js, extensions/web/03_abort_signal.js, extensions/web/13_message_port.js, extensions/web/Cargo.toml, extensions/web/internal.d.ts, extensions/web/lib.deno_web.d.ts, extensions/web/lib.rs, extensions/web/message_port.rs, extensions/webidl/00_webidl.js, extensions/webidl/internal.d.ts, runtime/js/99_main.js, tools/wpt/expectation.json, tools/wpt/runner.ts
This commit introduces support for MessageChannel and MessagePort.
MessagePorts can be transfered across a message channel.
This PR does not support transfering ports between workers yet. I will
tackle moving over workers, and broadcast channel to use the same
transfer logic used here in a follow up.
Closes #6691
=> feat: `MessageChannel` and `MessagePort`

cli/tests/integration_tests.rs, core/ops_builtin.rs
Closes #10764
```bash
echo "console.log(123)" > log.ts
touch 404
chmod +x ./404
```
```bash
$ deno run log.ts | ./404
Failed to execute process './404'. Reason:
exec: Exec format error
The file './404' is marked as an executable but could not be run by the operating system.
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:940:9
fatal runtime error: failed to initiate panic, error 5
fish: Process 843852, “deno” “deno run log.ts | ./404” terminated by signal SIGABRT (Abort)
```
```bash
$ ./target/debug/deno run log.ts | ./404
Failed to execute process './404'. Reason:
exec: Exec format error
The file './404' is marked as an executable but could not be …
```
=> fix(core): don't panic on stdout/stderr write failures

cli/tests/unit/signal_test.ts, runtime/js/40_signals.js
This PR fixes the wrong detection of signal event in Promise API when disposing the signal stream.
closes #9806
=> fix(runtime): fix signal promise API

extensions/fetch/21_formdata.js, extensions/fetch/22_body.js, extensions/fetch/internal.d.ts
This new FormData Serializer takes a FormData and converts it into a new Blob with other preexisting Blob parts 
The benefits
- Less code
- Don't need to calculate the byte length (Content-Length) - you get it from the new blob instead
- Don't have to read the content of the File entries or keeping any of the File entry content in memory until it's necessary to read them after `blob.stream()` is called, hence more RAM friendly
- Still synchronous
- Good for when you eg have to clone a Response `new Response(new FormData()).clone()`? but why would you? have have no idea, still a valid case?
- partially solves a blocker of async blob sources (#10969)
Returning a ReadableStream or async iterator... Converting it to a blob seems to be the most easiest.
I have used this formdata-to-blob …
=> refactor(FormData/Serializer): Early fix for supporting async blob source

core/runtime.rs
Starting with V8 9.1, top-level-await is always enabled by default.
See https://v8.dev/blog/v8-release-91 for the release notes.
- Remove the now redundant v8 flag.
- Clarify doc comment and add link to the feature explainer.
=> cleanup(core): top-level-await is now always enabled

cli/flags.rs, cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/main.rs
After seeing the vscode PR, @kitsonk pointed out we should use some custom messaging in the lsp to pass the parent process id and this made sense to me as the `--parent-pid <pid>` flag was inconvenient because it required us to version sniff to ensure we didn't pass it to old versions of the executable (something I hadn't considered).
While investigating moving it to the LSP, I discovered that the parent PID is already passed to us for free (https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#initializeParams) 🙈
This will be much better and doesn't require any changes in vscode_deno. It's unfortunate we didn't notice this earlier for the patch release yesterday though.
=> chore(lsp): switch to use lsp to get parent process id

extensions/fetch/22_body.js, extensions/fetch/23_request.js, extensions/web/06_streams.js, extensions/web/internal.d.ts, tools/wpt/expectation.json
Additionally, if the existing `Request`'s body is disturbed, the `Request` creation should fail. This fixes #10993.
This change also updates the step numbers in the `Request` constructor to match whatwg/fetch#1249.
=> fix(extensions/fetch): Creating a Request from an existing Request should proxy its body

core/ops_json.rs
The first argument to opSync/opAsync is the op name. In the examples, the name is 'hello', and so it should be the first argument.
=> docs(core): Use op name in docs example

.github/workflows/ci.yml, Cargo.toml, cli/bench/deno_http_native.js, cli/bench/main.rs, cli/tools/installer.rs, tools/util.js, tools/wpt.ts, tools/wpt/utils.ts
~Depends on: https://github.com/denoland/rusty_v8/pull/708~
=> ci: run Linux release builds in sysroot with Ubuntu 18.04 and LLVM

docs/linking_to_external_code/private.md
Just a minor correction I spotted while reading through the docs.
=> docs(manual/private): fixed spelling mistake

cli/tests/unit/event_test.ts, extensions/web/02_event.js
Before in REPL:
```
> new Event("")
Event {
bubbles: false,
cancelable: false,
composed: false,
currentTarget: null,
defaultPrevented: false,
eventPhase: 0,
srcElement: null,
target: null,
returnValue: true,
timeStamp: 1623786515074,
type: ""
}
> Event.prototype
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\tools\repl.rs:550:49
```
After:
```
exit using ctrl+d or close()
> new Event("")
Event {
bubbles: false,
cancelable: false,
composed: false,
currentTarget: null,
defaultPrevented: false,
eventPhase: 0,
srcElement: null,
target: null,
returnValue: true,
timeStamp: 1623786578618,
type: ""
}
> Event.prototype
Event {
bubbles: [Getter/Setter],
cancelable: [Getter/Setter],
composed: …
```
=> fix(inspect): fix inspecting event classes

cli/tests/unit/event_test.ts, extensions/web/02_event.js, extensions/websocket/01_websocket.js
Fix the `Event` class so its readonly properties are actually readonly.
Refs:
* https://developer.mozilla.org/en-US/docs/Web/API/Event
* See https://github.com/denoland/deno/pull/10979#discussion_r652105638 for discussion
=> fix: make readonly `Event` properties readonly

cli/lsp/analysis.rs, cli/lsp/completions.rs, cli/lsp/documents.rs, cli/lsp/language_server.rs, cli/lsp/tsc.rs, cli/tests/integration_tests_lsp.rs, cli/tests/lsp/did_open_params_import_hover.json
This provides enhanced information when hovering over a module dependency.
For example:
This also refactors the way we identify import/export locations and stores them with the document.
=> feat(lsp): dependency hover information

cli/tests/unit/http_test.ts, cli/tests/unit/net_test.ts, cli/tests/unit/signal_test.ts, cli/tests/unit/test_util.ts, cli/tests/unit/timers_test.ts
This PR refactors the usages of `delay` utility in js unit testing. The same utiliy is defined in several places with different names. This PR replaces those usages with the one provided in `std/async/delay.ts` to improve the readability and consistency of test code.
=> test(cli): refactor the usages of delay

cli/tests/raw_mode_cbreak.ts, cli/tests/unit/signal_test.ts, core/lib.rs, core/ops_json.rs, runtime/ops/signal.rs
This PR restores the behavior of Deno.signal API. Signal API originally didn't block the runtime from exiting the process, but since #7118 it uses async (non-unref) op, which blocks the runtime from exiting.
This PR adds `op_async_unref` utility which registers the op as AsyncUnref op, and op_signal_poll uses it.
Added a test case which demonstrate that the runtime exits while for-await loop still awaiting the signals.
closes #10658
=> fix(runtime/signal): use op_async_unref for op_signal_poll

cli/tests/unit/http_test.ts, runtime/js/40_http.js
=> fix: specify AbortSignal for native http Request

tools/util.js, tools/wpt.ts
=> chore: use local deno_std in tools scripts

cli/fs_util.rs, cli/lsp/language_server.rs
The `remove_dir_all` function will error when the directory does not exist. This is the cause of https://github.com/denoland/vscode_deno/issues/394
Classic bug 😊
=> fix(lsp): reload import registries should not error when the module registries directory does not exist

cli/tools/coverage.rs
This pretty prints the intermediary coverage files avoiding having to format them to make them human readable.
=> fix(cli): pretty print coverage files

runtime/inspector_server.rs, runtime/web_worker.rs, runtime/worker.rs
Closes https://github.com/denoland/deno/issues/11135
This commit improves how Deno inspector presents itself in Chrome Devtools.
Before:
After:
For comparison here's Node's prompt:
=> feat(inspector): improve inspector prompt in Chrome Devtools

cli/tests/finalization_registry.js, cli/tests/finalization_registry.js.out, cli/tests/integration/run_tests.rs, core/runtime.rs
This commit adds support for Atomics and FinalizationRegistry by integrating
V8's message loop into "JsRuntime::poll_event_loop".
Fixes https://github.com/denoland/deno/issues/7674
=> feat(core): pump V8 message loop on event loop tick

cli/diff.rs
Also fixed a few additional bugs like:
1. It not displaying a diff when one text had a trailing newline and the other didn't.
2. Edge case where the line number width could be incorrect if the original text had say `99` lines and the edit text had `100` lines.
I commented everywhere in the PR that actually changed other than the refactor to make the borrow checker happy without duplicating code.
Closes #8118
=> fix(diff): better handling of text with only line ending differences

extensions/webstorage/01_webstorage.js
=> refactor: introduce primordials for extensions/webstorage

cli/tests/test/exit_sanitizer.out, runtime/js/01_build.js, runtime/js/01_errors.js, runtime/js/01_version.js, runtime/js/01_web_util.js, runtime/js/06_util.js, runtime/js/11_workers.js, runtime/js/12_io.js
Ref https://github.com/denoland/deno/issues/11224
=> refactor: use primordials in runtime/, part1

runtime/js/13_buffer.js, runtime/js/30_fs.js
=> refactor: use primordials for `13_buffer.js` and `30_fs.js`

cli/tests/test/exit_sanitizer.out, cli/tests/test/fail.out, cli/tests/test/fail_fast.out, cli/tests/test/finally_timeout.out, cli/tests/test/no_check.out, runtime/js/30_os.js, runtime/js/40_compiler_api.js, runtime/js/40_files.js, runtime/js/40_fs_events.js, runtime/js/40_permissions.js, runtime/js/40_process.js, runtime/js/40_signals.js, runtime/js/40_testing.js, runtime/js/40_write_file.js, runtime/js/41_prompt.js, runtime/js/99_main.js
=> refactor: use primordials in runtime/, part2

extensions/webgpu/01_webgpu.js, extensions/webgpu/02_idl_types.js
https://github.com/denoland/deno/issues/11224
=> refactor use primordials in extensions/webgpu

extensions/web/02_event.js
=> refactor: use primordials in extensions/web/02_event.js

cli/tests/unit/fetch_test.ts, extensions/fetch/26_fetch.js
Reverts changes from: https://github.com/denoland/deno/pull/11003
Related to: https://github.com/denoland/deno/issues/10990
=> fix(fetch): OPTIONS should be allowed a non-null body

cli/tests/test/exit_sanitizer.out, cli/tests/test/fail.out, cli/tests/test/fail_fast.out, cli/tests/test/finally_timeout.out, cli/tests/test/no_check.out
Test expectations have gotten a bit too strict to the point where a new line change will break the stack.
This applies more liberal use of wildcards in the stack traces where failures are displayed.
=> test(integration/test): be more liberal with expectation wildcards

Cargo.lock, bench_util/Cargo.toml, cli/Cargo.toml, core/Cargo.toml, extensions/broadcast_channel/Cargo.toml, extensions/crypto/Cargo.toml, extensions/fetch/Cargo.toml, extensions/net/Cargo.toml, extensions/timers/Cargo.toml, extensions/web/Cargo.toml, extensions/webgpu/Cargo.toml, extensions/websocket/Cargo.toml, runtime/Cargo.toml, test_util/Cargo.toml
Tokio 1.8.0 has  been released. https://github.com/tokio-rs/tokio/releases/tag/tokio-1.8.0
=> chore: Upgrade Tokio to 1.8.0

cli/tests/info/data_null_error/data_null_error.out, cli/tests/info/data_null_error/mod.ts, cli/tests/info/data_null_error/types.d.ts, cli/tests/integration/info_tests.rs
Closes #11196.
This was fixed in swc (#11284). This just adds a test to ensure the issue doesn't happen in the future.
=> chore: add tests for assertion error when file contains only triple slash references

extensions/fetch/01_fetch_util.js, extensions/fetch/20_headers.js, extensions/fetch/21_formdata.js, extensions/fetch/22_body.js, extensions/fetch/23_request.js, extensions/fetch/23_response.js, extensions/fetch/26_fetch.js
Best reviewable commit by commit.
Towards https://github.com/denoland/deno/issues/11224
=> refactor: use primordials in extensions/fetch

extensions/console/01_colors.js, extensions/console/02_console.js
=> refactor: use primordials for extensions/console

extensions/web/08_text_encoding.js
This works since both `core.encode` and the ops bindings to a Rust `String` will already replace any lone surrogates with the replacement character.
Part of #10978.
=> perf: Use the WebIDL conversion to DOMString rather than USVString for TextEncoder

core/internal.d.ts, extensions/web/02_structured_clone.js, extensions/web/03_abort_signal.js, extensions/web/04_global_interfaces.js, extensions/web/05_base64.js, extensions/web/08_text_encoding.js, extensions/web/12_location.js
Ref https://github.com/denoland/deno/issues/11224
=> refactor: use primordials in extensions/web

Cargo.lock, cli/file_fetcher.rs, cli/file_watcher.rs, cli/lsp/config.rs, cli/lsp/performance.rs, cli/lsp/sources.rs, cli/main.rs, cli/module_graph.rs, cli/ops/runtime_compiler.rs, cli/program_state.rs, cli/tools/doc.rs, cli/tools/installer.rs, cli/tools/repl.rs, cli/tsc.rs, core/Cargo.toml, core/inspector.rs, core/lib.rs, core/modules.rs, extensions/broadcast_channel/in_memory_broadcast_channel.rs, extensions/net/ops_tls.rs, extensions/web/blob.rs, runtime/ops/fs_events.rs, runtime/permissions.rs
We're already using parking_lot extensively, but transitvely in dependencies. For example, parking_lot is used by tokio instead of std::sync for locks as a performance optimization. It might be good for us to also use it as it uses less memory, is faster, and has more features (I've used it in my projects and the API is a bit better).
Relates to #3429.
From https://crates.io/crates/parking_lot
> When tested on x86_64 Linux, parking_lot::Mutex was found to be 1.5x faster than std::sync::Mutex when uncontended, and up to 5x faster when contended from multiple threads. The numbers for RwLock vary depending on the number of reader and writer threads, but are almost always faster than the standard library RwLock, and even up to 50x faster in some cases.
=> chore: use parking_lot instead of std::sync for locks

extensions/webgpu/01_webgpu.js, extensions/webgpu/buffer.rs
This commit fixes the webgpu error scope implementation. It was
completly wrong previously. This is a first step towards enabling
webgpu cts tests. I tested the cts against this locally, and this
part now seems to be relatively spec compliant (it isnt the cause
of all errors anymore).
=> fix(webgpu): align error scopes to spec

cli/tests/integration/run_tests.rs
A large number of my PR runs fail because of this flaky test. Let's just disable it temporarily until #11128 is resolved.
=> chore: temporarily disable flaky single_compile_with_reload test

tools/wpt.ts
Reverts denoland/deno#11306
This made a test flaky:
```
expected test failures that passed:
"/fetch/api/basic/request-upload.any.html - Fetch with POST with ReadableStream containing number"
final result: failed. 634 passed; 1 failed; 11 expected failure; total 635
```
=> Revert "tests: parallelize test runs in wpt"

extensions/crypto/00_crypto.js, extensions/crypto/key.rs, extensions/crypto/lib.rs
removes the `i8 => digest::Algorithm` mapping between JS and Rust
=> refactor(extensions/crypto): use key::CryptoHash with digest

cli/tools/lint.rs
This changes the output stream for `--json` to stdout rather than stderr keeping stderr free for diagnostics output without poisoning the requested json output.
=> fix(cli/tools/lint): output json reports to stdout

docs/runtime.md
fixes https://github.com/denoland/doc_website/issues/214
=> docs(runtime): fix link to API docs

cli/tools/coverage.rs
This adds local methods and types for the rest of the messages, parameters and return objects that coverage uses as a first pass towards a fully typed unified inspector client interface.
=> refactor(cli/tools/coverage): strongly type inspector values

core/bindings.rs
An optimization to the `encode()` binding, avoiding an extra alloc & copy, extracted from https://github.com/denoland/deno/pull/10532
Will likely need a lower level `encode/decode` benchmark to measure the delta of this change
=> perf(core): avoid extra alloc in Deno.core.encode()

cli/tests/integration/repl_tests.rs, cli/tools/repl.rs
These now work:
```ts
let str = "cow"
str.<tab>
let num = 5;
num.<tab>
5n.<tab>
let func = function test(){};
func.<tab>
```
Unfortunately the following still does not work (it doesn't work in node's repl either and it would require improving `get_expr_from_line_at_pos` to probably tokenize to properly find the expression):
```ts
"test".<tab>
```
Closes #11322
=> feat(repl): support autocomplete on declarations containing a primitive

cli/main.rs, cli/tests/integration/watcher_tests.rs
This implements support for using the `--doc` along side the `--watch` option.
Closes https://github.com/denoland/deno/issues/10599
=> fix(cli): make --doc work with --watch

Cargo.lock, Cargo.toml, cli/dts/lib.deno.unstable.d.ts, cli/tests/integration/lsp_tests.rs, runtime/js/40_plugins.js, runtime/js/90_deno_ns.js, runtime/ops/mod.rs, runtime/ops/plugin.rs, runtime/web_worker.rs, runtime/worker.rs, test_plugin/Cargo.toml, test_plugin/README.md, test_plugin/src/lib.rs, test_plugin/tests/integration_tests.rs, test_plugin/tests/test.js
We will be unable to land the new FFI system (#11152) in time for 1.12, so bringing back plugins.
This reverts commit 7dd4090c2a3dc0222fd6ff611eeb2bd69cd28224.
=> Revert "Remove unstable native plugins (#10908)"

.github/workflows/ci.yml, cli/bench/deno_tcp_proxy.ts, cli/dts/lib.deno.ns.d.ts, cli/tests/cat.ts, cli/tests/echo_server.ts, cli/tests/unit/files_test.ts, cli/tests/unit/io_test.ts, docs/examples/tcp_echo.md, docs/examples/unix_cat.md, docs/getting_started/first_steps.md
=> chore(runtime): deprecate `Deno.copy`

tools/wpt.ts, tools/wpt/expectation.json
Currently, a WPT test is considered failed if its status code is anything other than 0, regardless of whether the test suite completed running or not, and any subtests that haven't finished running are not considered to be failures.
But a test can exit with a zero status code before it has completed running, if the event loop has run out of tasks because of a bug in one of the ops, leading to false positives. This change fixes that.
=> chore(wpt): Mark a WPT test as failed if it exits before completion

runtime/js/40_testing.js
This moves the pledging and restoring of test permissions into a wrapper applied during registration with the rest of the wrappers like sanitizers.
=> refactor(runtime): parse test permissions during test registration

extensions/web/10_filereader.js, tools/wpt/expectation.json
Currently, calling the `abort()` method on a `FileReader` object aborts any current read operation, but it also prevents any read operation started at some later point from starting. The File API instead specifies that calling `abort()` should reset the `FileReader`'s state and result, as well as removing any queued tasks from the current operation that haven't yet run.
=> fix(extensions/web): Aborting a FileReader object should not affect later reads

cli/tests/integration/test_tests.rs, cli/tests/test/clear_timeout.out, cli/tests/test/clear_timeout.ts
This adds a regression test case for https://github.com/denoland/deno/issues/7844
=> test(cli): ensure clear timeout doesn't trigger sanitizers

cli/tests/integration/repl_tests.rs
Reason of this PR
---
I'm working on #11291 and found there is a weird integration test in `repl_tests.rs`.
In the test `pty_multiline`, some test inputs produce errors like below
```
> /{/'
parse error: Unexpected eof at 1:4
> /(/'
parse error: Unexpected eof at 1:4
> /[/'
parse error: Unterminated regexp literal at 1:0
```
I think this is a normal system test and these inputs should not be here.
I git-blamed but I couldn't figure out what the author add these inputs. There is similar test like `'('`, `'{'`, and `'['`, so I think this is a kind of typo.
What I did
---
I replaced them into the normal input.
=> fix(repl): fix inconsistent integration test

Cargo.lock, cli/Cargo.toml, cli/ast/mod.rs, cli/lsp/analysis.rs, cli/module_graph.rs
This upgrades swc to 0.46. There was a breaking change I did in swc for getting rid of the `source_map` dependency for #11345.
=> chore: upgrade to swc 0.46

cli/main.rs
This propagates errors for the coverage command all the way down to `main` rather than having ad-hoc `process::exit(1)` calls in the middle of the call chain.
=> fix(cli): return error from `coverage_command`

cli/tests/integration/run_tests.rs, cli/tests/worker_close_race.js, cli/tests/workers/close_race_worker.js, runtime/ops/worker_host.rs
The `op_host_terminate_worker` and `op_host_post_message` ops used to panic when called with a non-existent worker ID, since it would indicate an error in the JS side. However, #11416 shows that race conditions between a worker's `close()` function and the corresponding `Worker.prototype.terminate()` can lead to the JS side performing ops on the worker before being notified that the worker has terminated. As such, this change silently ignores non-existent worker IDs in those ops. 
Fixes #11416.
=> fix(workers): Silently ignore non-existent worker IDs

cli/dts/lib.esnext.array.d.ts, cli/dts/lib.esnext.d.ts, cli/dts/lib.esnext.string.d.ts, cli/dts/typescript.d.ts, cli/tests/unit/esnext_test.ts
Fixes: #11441
This manually adds the types for `.at()` types to arrays and strings.  It is a bit "hacky", but essentially the same way we add `"dom.asynciterable"` to TypeScript.
Something we should revert once in a released version of TypeScript (but will likely just overwrite when it is finally included).
Added a simply js_unit test which validates that it should pass type checking.
Also updated to the latest release version of TypeScript (4.3.2 -> 4.3.5).
=> fix(tsc): add .at() types manually to tsc, update to tsc v4.3.5

cli/tests/integration/repl_tests.rs, cli/tools/repl.rs
Reason of this PR
---
Close #11291 
As discussed in #11291, when the input is invalid, repl hangs forever.
This PR makes repl output error instead of hanging when the input is invalid.
What I did
---
Actually, repl looks hanging, but it just continues to read the next input that never end.
The reason is that repl thinks the input might be the middle of the template though the input is invalid.
However it continues to read when obviously it is not in a template.
I changed the condition that determines whether it continues to read or not.
When the error is `SyntaxError::UnterminatedTpl`, it continues to read, otherwise raise error.
When raising error, in the same way as unpaired braces, it marked the input as valid with no info and V8 raise the error instead.
=> fix(repl): output error without hanging when input is invalid

extensions/crypto/00_crypto.js, tools/wpt/expectation.json
Relevant spec change: https://github.com/w3c/webcrypto/pull/266
Closes #11445
=> fix: Big{U|}Int64Array in crypto.getRandomValues

cli/flags.rs
This PR adds a test case for checking the fix #11433, prevents #11432 happening again in the future.
=> test(cli): add test case for 'deno test --watch'

cli/tests/fetch_response_finalization.js, cli/tests/fetch_response_finalization.js.out, cli/tests/integration/run_tests.rs, extensions/fetch/26_fetch.js
This commit fixes fetch response bodies to be automatically closed if
the `Response.body` readable stream goes out of scope and is GC'ed.
Fixes #4735
=> fix: close fetch response body on GC

cli/lsp/config.rs, cli/lsp/language_server.rs
This add a representation of what the language server thinks are the current settings to the language server status page.
We have had several issues that have been difficult to diagnose because we don't know how workspace and global settings in vscode have had an impact on the lsp and this provides exactly what the LSP thinks things are.
=> feat(lsp): add workspace config to status page

cli/main.rs, cli/tests/test/exit_sanitizer.out, cli/tests/test/fail.out, cli/tests/test/fail_fast.out, cli/tests/test/finally_timeout.out, cli/tests/test/only.out, cli/tools/test_runner.rs
This normalises the test command from the bottom up to return errors all the way down the chain rather than calling `process::exit` at arbritary places.
=> fix(cli): normalize test command errors

cli/tests/unit/http_test.ts, extensions/http/01_http.js
The "connection" header should be case insensitive:
https://datatracker.ietf.org/doc/html/rfc7230#section-6.1
Fixes #11487
=> fix(http/ws): case insensitive connection header

runtime/js/99_main.js
`Deno.core.sharedQueue` was killed in #9843
=> cleanup(runtime): remove last references to Deno.core.sharedQueue

cli/tests/unit/http_test.ts, extensions/http/01_http.js
The "connection" header can have multiple connection-options separated by commas:
https://datatracker.ietf.org/doc/html/rfc7230#section-6.1
https://datatracker.ietf.org/doc/html/rfc7230#section-7
Fixes #11494
=> fix(http/ws): support multiple options in connection header

cli/tests/integration/test_tests.rs, cli/tests/test/meta.out, cli/tests/test/meta.ts, cli/tools/coverage.rs, cli/tools/test_runner.rs
This fixes a regression introduced in 1.9 where test modules became main modules.
This is undesirable as it will cause executables to start running when they're guarded with `import.meta.main`.
We now side load (import) the module being tested in a generated module but still mark it as the main module in places where it could be visible like the inspector (effectively everywhere but the import.meta.main flag).
Closes #11504
=> fix(cli/tools/test_runner): side-load test modules

cli/tests/test/doc.out, cli/tests/test/doc.ts, cli/tools/test_runner.rs
This augments the doc test feature to use the first attribute in markdown blocks as the media type and extension for the extracted example.
=> feat(cli/tools/test): imply media type from doc attribute

cli/lsp/language_server.rs, cli/tsc/99_main_compiler.js
This improves #10897 but doesn't completely resolve it.
The problem is that when a document with the same name of another document is re-opened, and that version of the document happened to not be changed, the version is both `"1"` and so tsc things nothing has changed and provides the diagnostics it provided before in response.  This means:
- If you open a document, but don't edit it.
- You rename or delete that document.
- You then rename another document to that original document.
- That "new" document will have the diagnostics for the previous file up until the file is edited.
I looked at how vscode handles this situation with the built in TypeScript language server and they have a complex buffer system where the re-calculate all the diagnostics.  I will look into it further down the …
=> refactor(lsp): minor improvements to handling closed documents

cli/flags.rs, cli/lsp/README.md, cli/lsp/config.rs, cli/lsp/language_server.rs, cli/lsp/registries.rs, cli/lsp/sources.rs, cli/program_state.rs, cli/specifier_handler.rs, cli/tests/integration/lsp_tests.rs, cli/tests/lsp/initialize_params.json, cli/tests/lsp/initialize_params_bad_config_option.json, cli/tests/lsp/initialize_params_code_lens_test.json, cli/tests/lsp/initialize_params_code_lens_test_disabled.json, cli/tests/lsp/initialize_params_did_config_change.json, cli/tests/lsp/initialize_params_disabled.json, cli/tests/lsp/initialize_params_registry.json, cli/tests/lsp/initialize_params_unstable.json, cli/tools/standalone.rs
Ref: denoland/vscode_deno#287
Add the ability to specify an override for the DENO_DIR via the language server configuration.  Previously the language server would have to be executed in an environment with the `DENO_DIR` environment setting, which makes it difficult to manage and customise per workspace.
=> feat(lsp): ability to set DENO_DIR via settings

extensions/fetch/lib.rs, runtime/build.rs, runtime/web_worker.rs, runtime/worker.rs
Add a new option named frozen_headers which
can contain headers that cannot be overriden
by end users.
=> feat(extensions/fetch): extend init options

cli/tests/workers/http_worker.js, cli/tests/workers/test.ts
The test was flaky because it was using port number that a lot of other tests are using as well.
=> fix: flaky worker test

cli/tests/doc/invalid_url.out, cli/tests/integration/doc_tests.rs, cli/tools/doc.rs
=> fix(cli): deno doc panics on invalid url

core/modules.rs, core/runtime.rs, runtime/web_worker.rs, runtime/worker.rs
Oneshot is more appropriate because mod_evaluate() only sends a single
value.
It also makes it easier to use it correctly. As an embedder, I wasn't
sure if I'm expected to drain the channel or not.
=> chore(core): use oneshot channel in mod_evaluate()

cli/lsp/parent_process_checker.rs
This change causes the parent process checker to actually exit on Mac and it seems some distros of linux.
=> fix(lsp): fix parent process checker to not output to stderr before exiting

cli/tests/unit/net_test.ts
Was failing every time on my machine because the port was in use. I just bumped it up one port number.
=> chore: fix failing netTcpListenCloseWhileIterating test on some machines

cli/import_map.rs, runtime/ops/tty.rs
I wrote an import map with a trailing comma and spent too long trying to figure out what was wrong. Would be better if the CLI told me what was wrong.
=> chore: surface import map JSON parse error to user

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/process_test.ts, runtime/js/40_process.js, runtime/ops/process.rs
=> feat(unstable): clean environmental variables for subprocess

cli/tests/unit/net_test.ts
This does not solve #11580, but it makes it so that when an assertion fails it will not happen in an unawaited promise.
=> chore: refactor `netHangsOnClose` test to not use `deferred`

cli/lsp/capabilities.rs, cli/lsp/language_server.rs, cli/lsp/mod.rs, cli/lsp/refactor.rs, cli/lsp/tsc.rs, cli/tests/integration/lsp_tests.rs, cli/tests/lsp/code_action_params_refactor.json, cli/tests/lsp/code_action_resolve_params_refactor.json, cli/tests/lsp/code_action_resolve_response_refactor.json, cli/tests/lsp/code_action_response_refactor.json, cli/tsc/99_main_compiler.js, cli/tsc/compiler.d.ts
Related https://github.com/denoland/vscode_deno/issues/433
=> feat(lsp): Implement refactoring

Cargo.lock, extensions/crypto/Cargo.toml, extensions/crypto/lib.rs
=> chore: Upgrade RSA to 0.5.0

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/permissions_test.ts, runtime/js/11_workers.js, runtime/js/40_permissions.js
Closes #11036
not only for `Deno.permissions`, but worker & test permissions as well.
=> feat(runtime): allow URL for permissions

cli/ast/mod.rs, cli/ast/transforms.rs, cli/tests/integration/repl_tests.rs
Just thought about this a bit more and I think it's useful. It does the following transforms in the REPL:
```ts
export class Test {}
----
class Test {}
```
```ts
export default class Test {}
----
class Test {}
```
```ts
export default class {}
----
;
```
```ts
export default 5;
----
5;
```
```ts
export * from "./test.ts";
----
await import("./test.ts");
```
```ts
export { test } from "./test.ts";
----
await import("./test.ts");
```
```ts
export { test };
----
;
```
This will help with usability and allow people to more easily copy and paste code into the repl.
=> feat(repl): strip exports in the REPL

Cargo.lock, cli/Cargo.toml, cli/ast/bundle_hook.rs, cli/ast/comments.rs, cli/ast/mod.rs, cli/ast/source_file_info.rs, cli/lsp/analysis.rs, cli/lsp/code_lens.rs, cli/module_graph.rs, cli/specifier_handler.rs, cli/tools/coverage.rs, cli/tools/repl.rs, cli/tools/test_runner.rs
This PR is the first two points in #11345.
Basically, this change does two main things:
1. Removes the use of swc's `SourceMap` and `SourceFile` in favour of the new `SourceFileInfo`, which implements `Sync`.
2. Moves out comments from `SingleThreadedComments` to a new immutable `MultiThreadedComments`.
=> refactor: make `ParsedModule` implement `Sync`

cli/dts/lib.deno.ns.d.ts, cli/tests/unit/write_file_test.ts, runtime/js/40_write_file.js
Refs #10181 
This continues the work in https://github.com/denoland/deno/pull/10943 and adds AbortSignal support to `writeFile` (and since it uses the same infrastructure `writeTextFile`)
cc @lucacasonato and @ry who reviewed the last one :)
=> feat(std) support AbortSignal in writeFile

cli/dts/lib.deno.ns.d.ts, cli/dts/lib.deno.unstable.d.ts, cli/tests/unit/permissions_test.ts, runtime/js/11_workers.js, runtime/js/40_permissions.js
Revert changes to "net" permissions in regards to handling URLs.
Introduced in https://github.com/denoland/deno/pull/11578
Reverting due to @lucacasonato comment: https://github.com/denoland/deno/pull/11578#issuecomment-894315667
=> revert: allow URL for permissions

cli/flags.rs, cli/main.rs, cli/tests/integration/repl_tests.rs, cli/tools/repl.rs, test_util/src/lib.rs
Closes #3173
At the moment, this only adds support for an `--eval <code>` flag to provide some code to execute on startup.
For example:
```bash
deno repl --eval 'import * as hash from "https://deno.land/std@0.77.0/hash#stdhash"'
```
1. On success, the result of running the script will not be outputted, but still assigned to _.
2. On thrown error, the error will be displayed to the user and assigned to _error (unless it's a parse error). The REPL will not fail to start in order to not block the user allowing them to ignore any setup errors and just use the REPL.
We will consider adding support for URL and file paths in the future, but for now this is a first step.
=> feat(repl): add --eval flag for evaluating code when the repl starts

cli/flags.rs
Fixes main. Occurred because merges happened one after the other after both CIs had run.
=> chore: fix repl_with_eval_flag test

cli/tests/unit/http_test.ts, extensions/http/01_http.js, extensions/websocket/01_websocket.js
=> fix(websocket): allow any close code for server

cli/http_util.rs
Minor fix to remove a compiler warning on Windows.
=> chore: remove windows-only compiler warning in http_util.rs

cli/program_state.rs, cli/tests/cafile_ts_fetch_unsafe_ssl.ts.out, cli/tests/cafile_url_imports_unsafe_ssl.ts.out, cli/tests/deno_land_unsafe_ssl.ts.out, cli/tests/localhost_unsafe_ssl.ts.out
Fixes the spelling of "certificate" in the warning message.
=> fix: correct spelling of certificate in `--unsafely-ignore-certificate-errors` warning message

cli/tools/lint.rs
Closes https://github.com/denoland/deno/issues/8227
Before:
```
$ deno lint --rules
Available rules:
- adjacent-overload-signatures
- ban-ts-comment
- ban-types
...
```
After:
```
Available rules:
- adjacent-overload-signatures
help: https://lint.deno.land/#adjacent-overload-signatures
- ban-ts-comment
help: https://lint.deno.land/#ban-ts-comment
- ban-types
help: https://lint.deno.land/#ban-types
- ban-unknown-rule-code
help: https://lint.deno.land/#ban-unknown-rule-code
...
```
Before:
```
(adjacent-overload-signatures) All `foo` signatures should be adjacent
foo(sn: string | number): void;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
at /Users/biwanczuk/dev/deno/foo.ts:5:2
hint: Make sure all overloaded signatures are grouped together
Found 1 problem
Checked 1 file
```
After:
``` …
```
=> fix(lint): add links to help at lint.deno.land

Cargo.toml
Closes #11301
```javascript
// bench_rsa.js
import {
bench,
runBenchmarks,
} from "https://deno.land/std@0.104.0/testing/bench.ts";
bench(async function iter10RSA4096(b){
b.start();
for (let i = 0; i < 10; i++) {
await crypto.subtle.generateKey({ name: "RSA-PSS", hash: "SHA-256", publicExponent: new Uint8Array([1,0,1]), modulusLength: 2048 }, true, ["sign"]);
};
b.stop();
});
runBenchmarks();
```
=> perf(wpt/crypto): optimize num-bigint-dig for debug builds

ext/crypto/00_crypto.js
`10.1.3` under [`18.4.4` Normalizing an algorithm](https://www.w3.org/TR/WebCryptoAPI/#algorithm-normalization-normalize-an-algorithm). Needed for #11654
=> fix(ext/crypto): handle idlValue may not be present

cli/fs_util.rs, cli/main.rs, cli/tools/test_runner.rs
Normalizes the naming of the functions used to determine if a path is a suitable match for the test runner and placed them both in the the fs_util module.
Added a test for `is_supported_test_ext` as-well.
=> refactor: normalize `is_supported_` check naming

cli/tools/repl.rs
This disables any highlighting when the completion mode is set to list.
Fixes https://github.com/denoland/deno/issues/10998
=> fix(cli/tools/repl): dont highlight candidate when completion is list

cli/file_fetcher.rs, ext/web/blob.rs
`Arc<T>` is already on the heap so `Arc<Box<T>>` is unnecessary, see: https://rust-lang.github.io/rust-clippy/master/index.html#redundant_allocation
=> cleanup(ext/web/BlobStore): avoid redundant alloc

ext/http/lib.rs
Keep `op_http_request_next`'s high-level logic simple, factor out `NextRequestResponse` building to `prepare_next_request()` for improved readability & maintainability
=> cleanup(ext/http): simplify op_http_request_next

ext/http/lib.rs
Use `Vec::join` instead of essentially reimplementing it, there should be no meaningful performance delta
=> cleanup(ext/http): simplify cookie header handling

cli/tools/lint.rs
This commit changes output color of the linter to not use gray for visibility on dark backgrounds.
Fixes https://github.com/denoland/deno_lint/issues/788
=> fix(cli/lint): don't use gray in diagnostics output for visibility

ext/webstorage/lib.rs
This PR improves localStorage write throughput by around 150x by caching
the prepared statements for SQLite.
Script to measure perf:
```js
const start = performance.now();
for (let i = 0; i < 100; i++) {
localStorage[i.toString()] = i.toString();
}
console.log(`${performance.now() - start}ms`);
```
```
/m/s/P/g/d/deno ❯❯❯ deno run --location https://deno.land test.js
1978ms
/m/s/P/g/d/deno ❯❯❯ cargo run run --location https://deno.land test.js
Compiling deno_runtime v0.22.2 (/mnt/starship/Projects/github.com/denoland/deno/runtime)
Compiling deno v1.13.0 (/mnt/starship/Projects/github.com/denoland/deno/cli)
Finished dev [unoptimized + debuginfo] target(s) in 31.73s
Running `target/debug/deno run --location 'https://deno.land' test.js`
14ms
```
=> perf: improve localStorage throughput

ext/crypto/00_crypto.js
`%TypedArray%.prototype.slice` cannot be called on `ArrayBuffer`. This code was unreachable so it never threw, noticed while working on #11642
=> fix(ext/crypto): fix copying buffersource

ext/http/lib.rs
This stood out on a flamegraph, it took up ~1% of a profiled loadtest of `cli/bench/deno_http_native.js`
(1% of total program time is not huge but not insignificant when optimizing this HTTP hot path)
You can see string concat benches here: https://github.com/hoodie/concatenation_benchmarks-rs, ran locally (M1 Air):
```
test array_concat                                 ... bench:          33 ns/iter (+/- 0)
test array_join                                   ... bench:          30 ns/iter (+/- 0)
test array_join_long                              ... bench:          33 ns/iter (+/- 0)
test collect_from_array_to_string                 ... bench:          66 ns/iter (+/- 0)
test collect_from_vec_to_string                   ... bench:          67 ns/iter (+/- 1)
test format_macro …
```
=> perf(ext/http): faster req_url string assembly

cli/dts/lib.deno.ns.d.ts
With the statically typed names, subclassing `Deno.errors` errors was not anymore possible.
Fixes #11713
=> fix: don't statically type name on Deno.errors

cli/tests/unit/webcrypto_test.ts, ext/crypto/00_crypto.js, ext/crypto/lib.deno_crypto.d.ts
My bad! Ref https://github.com/denoland/deno/pull/11367#issuecomment-899994010
Thanks @iugo for reporting this
Fixes typings and innerKey processing (WPT doesn't test `exportKey` for HMAC so this wasn't caught earlier).
=> fix(ext/crypto): exportKey() for HMAC

core/00_primordials.js
Because it was possible to disable those with a runtime flag, they were not available through primordials. The flag has since been removed upstream.
Refs: https://github.com/v8/v8/commit/d59db06bf5425ddb388fb5a576f4bf39bdcc0f8f
=> chore: add `FinalizationRegistry` and `WeakRef` to primordials

cli/tests/integration/watcher_tests.rs
This marks test watcher tests as flaky tests.
They still need to be re-worked as they are very flaky.
See https://github.com/denoland/deno/issues/10552
=> test: re-enable test watch tests and mark as flaky

Cargo.lock, ext/url/00_url.js, ext/url/Cargo.toml, ext/url/lib.rs
This splits the previous `op_url_parse` into:
- `op_url_parse`: parses a href with an optional base
- `op_url_reparse`: reparses a href with a modifier
This is a cleaner separation of concerns and it allows us to optimize & simplify args passed. Resulting in a 25% reduction in call overhead (`~5000ns/call` => `~3700ns/call` in the `url_ops` bench on my M1 Air)
=> perf(ext/url): cleanup and optimize url parsing op args

cli/lsp/README.md, cli/lsp/documents.rs, cli/lsp/language_server.rs
This adds a `LanguageId::Unknown` which better aligns to mapping to `MediaType`.  Also we were defaulting to `LanguageId::TypeScript` when we encountered an unknown/unsupported language id.  This cause diagnostics to appear in the file from tsc, even though it should have been considered "undiagnosable".
This also adds support for `"jsx"` and `"tsx"` language IDs.
Fixes #11521
Fixes #11742
=> fix(lsp): better handling of languageId

ext/url/00_url.js, ext/url/lib.rs
Marshalling it across the op-layer by joining the substrings into a single "fat" newline-joined string, then splitting JS side.
This shaves off a little over a 1/3 of the overhead per call:
`main` (after merging https://github.com/denoland/deno/pull/11763)
```
bench:   3,726,203 ns/iter (+/- 177,656)
```
this PR:
```
bench:   2,400,289 ns/iter (+/- 53,911)
```
So with this PR and #11763 that's a combined improvement of over 2x ! (~5000ns/call => ~2400ns/call)
Whilst this might appear counterintuitive and "hacky", it works because:
- We have 11 string values to return
- Marshalling them in a struct creates an obj + 11 optimized/internalized strings (the keys) + 11 unoptimized "normal" strings (the values) + 11 owned strings in Rust
- This approach creates 1 fat owned string in rust, then …
=> perf(ext/url): optimize UrlParts op serialization

core/01_core.js, core/runtime.rs
No user impact, but is simpler and aligns with `opcall()`
=> cleanup(core): rename handleAsyncMsgFromRust() to opresolve()

ext/url/00_url.js
Improves url parsing by ~20%:
- before: `~2450ns/parse`
- after: `~1950ns/parse`
This is safe since all these string values are immediately sent to the op-layer that uses `v8::String::to_rust_string_lossy()` with `REPLACE_INVALID_UTF8` effectively doing the same transform as our `USVString` webidl converter
=> perf(ext/url): use DOMString webidl instead of USVString 

Cargo.toml
A ~25% improvement: `~1950ns/call` => `~1500ns/call`
=> perf(url): build with opt-level 3

.dlint.json, ext/websocket/02_websocketstream.js, runtime/js/99_main.js, tools/lint.js
This PR upgrades `third_party` submodule to the latest to get dlint 0.12.0, and applies `prefer-primordials` to the files under runtime, ext, and core.
=> chore: upgrade dlint and run `prefer-primordials`
